### ISSUE TITLE
10. Regular Expression Matching Test cases wrong output

### ISSUE THREAD

**Issue by khushdj2002** [LeetCode-Feedback/LeetCode-Feedback#16307] opened 2023-09-09 11:18 UTC
#### Category of the bug
- [ ] Question 
 Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:

    '.' Matches any single character.​​​​
    '*' Matches zero or more of the preceding element.

     The matching should cover the entire input string (not partial).
- [ ] Solution
     class Solution {
    public boolean isMatch(String s, String p) {
        Boolean[][] dp = new Boolean[s.length()][p.length()];
        return check(s,p,s.length()-1,p.length()-1,dp);

    }
    boolean check(String s, String p,int m,int n,Boolean[][] dp){
        if(m<0&&n<0){
            return true;
        }
        if(n<0){
            return false;
        }
        if(m<0){
            if(p.charAt(n)=='*'){
                return check(s,p,m,n-1,dp);
            }
            else{
                return false;
            }
        }
        if(dp[m][n]!=null){
            return dp[m][n];
        }
        if(s.charAt(m)==p.charAt(n)||p.charAt(n)=='.'){
            return dp[m][n]= check(s,p,m-1,n-1,dp);
        }
        else{
            if(p.charAt(n)=='*'){
                return (check(s,p,m-1,n,dp)||check(s,p,m,n-1,dp));
            }
            else{
                return false;
            }
        }
    }
}
- [ ] Language
    JAVA
- [ ] Missing Test Cases 
    Input
    s ="aab"
    p = "c*a*b"

#### Description of the bug

The output of the above should be false but it's showing true

#### Code you used for Submit/Run operation

```
// [Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)
class Solution {
    public boolean isMatch(String s, String p) {
        Boolean[][] dp = new Boolean[s.length()][p.length()];
        return check(s,p,s.length()-1,p.length()-1,dp);

    }
    boolean check(String s, String p,int m,int n,Boolean[][] dp){
        if(m<0&&n<0){
            return true;
        }
        if(n<0){
            return false;
        }
        if(m<0){
            if(p.charAt(n)=='*'){
                return check(s,p,m,n-1,dp);
            }
            else{
                return false;
            }
        }
        if(dp[m][n]!=null){
            return dp[m][n];
        }
        if(s.charAt(m)==p.charAt(n)||p.charAt(n)=='.'){
            return dp[m][n]= check(s,p,m-1,n-1,dp);
        }
        else{
            if(p.charAt(n)=='*'){
                return (check(s,p,m-1,n,dp)||check(s,p,m,n-1,dp));
            }
            else{
                return false;
            }
        }
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

The output should be false but it's showing it should be true.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108506287/ba3abae8-f116-4377-9706-83013285f3d2)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108506287/253801fe-e39d-42cc-ac46-7f0afb8dbadd)

**Comment by LC-Pam** [comment] 2023-09-11 20:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:09 UTC
Labels: Waiting for Reply
