### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by bsal11** [LeetCode-Feedback/LeetCode-Feedback#14032] opened 2023-06-11 07:32 UTC
The below is what I code for the said problem. It is giving correct output in other code editors but not in leetcode platform.

class Solution {
    public int[] nextPermutation(int[] nums) {
        if(isDescendingOrder(nums)) {
            return reversePermutation(nums);
        }

        for(int i = nums.length - 1; i>0; i--) {
            if(nums[i] > nums[i-1]) {
                int temp = nums[i];
                nums[i] = nums[i-1];
                nums[i-1] = temp;
                
                if(i == nums.length - 1)
                    return nums;
                else {
                    int [] newNums = new int[nums.length];
                    int k = 0;
                    for(; k<=i; k++)
                        newNums[k] = nums[k];
                    for(int j = nums.length - 1; j>i; j--)
                        newNums[k++] = nums[j];
                    for(int lp = 0; lp<newNums.length; lp++)
                        System.out.print(newNums[lp]);
                    return newNums;
                }
            }
            else {
                int temp = nums[i];
                nums[i] = nums[i-1];
                nums[i-1] = temp;
            }
        }
        int temp = nums[0];
        nums[0] = nums[nums.length - 1];
        nums[nums.length - 1] = temp;
        int newNums[] = new int[nums.length];
        newNums[0] = nums[0];
        
        if(nums.length == 3)
        {
            newNums[1] = nums[nums.length - 1];
            newNums[2] = nums[1];
            return newNums;
        }
        newNums[1] = nums[nums.length - 1];
        newNums[2] = nums[1];
        for(int i = 3, k = nums.length - 2; k>1; k--, i++)
            newNums[i] = nums[k];
        
        return newNums;
    }

    public int [] reversePermutation (int [] nums) {
        for(int i = 0; i<nums.length/2; i++) {
            int temp = nums[i];
            nums[i] = nums[nums.length - 1 - i];
            nums[nums.length - 1 - i] = temp;
        }
        return nums;
    }

    public boolean isDescendingOrder(int[] arr) {
    for (int i = 0; i < arr.length - 1; i++) {
        if (arr[i] < arr[i + 1]) {
            return false;
        }
    }
    return true;
}
}

**Comment by LC-Pam** [comment] 2023-06-13 20:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 20:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 20:10 UTC
Labels: LCUS, problem
