### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by MohitYadav9098** [LeetCode-Feedback/LeetCode-Feedback#12454] opened 2023-03-19 14:50 UTC
/*1. Two Sum
Easy

44406

1447

Add to List

Share
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

 

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]
Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]*/
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int[] pair=new int[2];
           for(int i=0; i<nums.length; i++){
           for(int j=i+1; j<nums.length; j++){
               if(nums[i]+nums[j]==target){
                   pair[0]=i;
                   pair[1]=j;
                   return pair;
               }
           }
       }
        return pair;
    }
}

**Comment by LC-Pam** [comment] 2023-03-20 18:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-22 20:28
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-22 20:28 UTC
Labels: LCUS, problem
