### ISSUE TITLE
Missing Test Case - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by Anandsingh456** [LeetCode-Feedback/LeetCode-Feedback#15355] opened 2023-08-06 17:09 UTC
#### Your LeetCode username

anandtsvd1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 4] Missing Test Cases 

#### Description of the bug

The test case in which we have given [1,2,1,2,1] where k = 3 has the wrong output it should show output as 2 but it show as 4.
the length will be 2 from the first two-element and the length will be clearly 2, not  4.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
int left = 0,right = 0;
    long long sum = nums[0];
    int maxLen = 0;
    int n = nums.size();
    for(int i=0;i<n;i++){
        while(right < n && sum >k){
            sum -= nums[left];
            left++;
        }
        if(sum == k) {
            maxLen= max(maxLen,right-left+1);
        }
        right++;
        if(right <n) sum += nums[right];
    }
    return maxLen;
    }
};
```

#### Language used for code

c++

#### Expected behavior

The test case in which we have given [1,2,1,2,1] where k = 3 has the wrong output it should show output as 2 but it show as 4.
the length will be 2 from the first two-element and the length will be clearly 2, not  4.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91431905/221e1b55-cb72-4a00-a0aa-a2348fa9c06b)

**Comment by YogeshP93** [comment] 2023-08-07 02:21
This is duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15358 ?

**Comment by LC-Pam** [comment] 2023-08-08 20:11
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-08-08 20:11 UTC
