### ISSUE TITLE
Missing Test Case - 1402. Reducing Dishes

### ISSUE THREAD

**Issue by velo** [LeetCode-Feedback/LeetCode-Feedback#19659] opened 2024-01-23 07:34 UTC
Another very useful test case, would be:

`-1,-2,-3,-4,11` = `35`

It's a good scenario to check if it's testing the whole set of possibilities, and not stopping at a sub-optimal solution

**Comment by LC-Pam** [comment] 2024-01-23 20:28
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:15
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:15 UTC
Labels: Waiting for Reply
