### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by q760440238** [LeetCode-Feedback/LeetCode-Feedback#16761] opened 2023-09-28 06:10 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
      std::unordered_map<int, int> num_map;
        int longestStreak = 0;
        int n = nums.size();
        int i = 0;

        while (i < n) {
            int num = nums[i];
            if (num_map.find(num) == num_map.end()) {
                int left = num_map.find(num - 1) != num_map.end() ? num_map[num - 1] : 0;
                int right = num_map.find(num + 1) != num_map.end() ? num_map[num + 1] : 0;

                int currentStreak = left + right + 1;
                num_map[num] = currentStreak;

                // 更新左边界和右边界
                num_map[num - left] = currentStreak;
                num_map[num + right] = currentStreak;

                longestStreak = std::max(longestStreak, currentStreak);
            }
            i++;
        }

        return longestStreak;
    }
};
```

**Comment by LC-Pam** [comment] 2023-09-28 16:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-03 17:21
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-03 17:21 UTC
Labels: Waiting for Reply
