### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by kunalkumar26** [LeetCode-Feedback/LeetCode-Feedback#14266] opened 2023-06-21 07:47 UTC
#### Your LeetCode username
rkunalkumar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

if s="aa" and p="aa.*" -> it should give output as "false", but right now it is giving "true" as correct output.

#### Code you used for Submit/Run operation

```
int n = p.length();
        int m = s.length();
        
        boolean dp[][] = new boolean[n+1][m+1];
        // first row -> false except the first cell
        dp[0][0] = true;
        // first column
        for(int i=1; i<dp.length; i++){
            char ch = p.charAt(i-1);
            if(ch == '*'){
                dp[i][0] = dp[i-2][0];
            }
        }
        
        // main problem
        for(int i=1; i<dp.length; i++){
            for(int j=1; j<dp[0].length; j++){
                char ch1 = p.charAt(i-1);
                char ch2 = s.charAt(j-1);
                
                if(ch1 == '*'){
                    dp[i][j] = dp[i-2][j];
                    char pslc = p.charAt(i-2);
                    if(pslc == ch2 || pslc=='.'){
                        dp[i][j] = dp[i][j] || dp[i][j-1];
                    }
                } else if(ch1 == '.'){
                    dp[i][j] = dp[i-1][j-1];
                } else if(ch1 == ch2){
                    dp[i][j] = dp[i-1][j-1];
                }
            }
        }
        return dp[n][m];
```

#### Language used for code
JAVA 

#### Expected behavior

if s="aa" and p="aa.*" then the minimum length the pattern can have is 3, and the string is of length 2.
so the pattern can not match the string. Hence it should give false as output, but right now, it is giving true as output, which I think is incorrect
<img width="528" alt="Screenshot 2023-06-21 at 1 13 42 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77446886/66c7f14e-6db5-4ca0-90ad-f15e11d62709">
.

**Comment by LC-Pam** [comment] 2023-06-22 18:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:25 UTC
Labels: LCUS, problem
