### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by Gwennbzh** [LeetCode-Feedback/LeetCode-Feedback#17442] opened 2023-10-25 12:31 UTC
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I want to know why my code doesn't work for this problem whereas the "print" (in my code show the good answer)

#### Code you used for Submit/Run operation

```
// Two Sum
<!-- python -->

class Solution(object):
    def moveZeroes(self, nums):
        """
        :type nums: List[int]
        :rtype: None Do not return anything, modify nums in-place instead.
        """
        print([i  for i in nums if i!=0 ] + [0] * nums.count(0))
        nums = [i  for i in nums if i!=0 ] + [0] * nums.count(0)

#### Language used for code



#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-10-25 18:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 19:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-27 19:03 UTC
Labels: Waiting for Reply
