### ISSUE TITLE
Missing Test Case - 1757. Recyclable and Low Fat Products

### ISSUE THREAD

**Issue by Oxhei** [LeetCode-Feedback/LeetCode-Feedback#15626] opened 2023-08-15 22:41 UTC
#### Category of the bug
Table: Products

+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| product_id  | int     |
| low_fats    | enum    |
| recyclable  | enum    |
+-------------+---------+
product_id is the primary key (column with unique values) for this table.
low_fats is an ENUM (category) of type ('Y', 'N') where 'Y' means this product is low fat and 'N' means it is not.
recyclable is an ENUM (category) of types ('Y', 'N') where 'Y' means this product is recyclable and 'N' means it is not.
 

Write a solution to find the ids of products that are both low fat and recyclable.

Return the result table in any order.

The result format is in the following example.

#### Description of the bug
To use SQL to select the product id where the products were low fat and or recycable.

**Comment by LC-Pam** [comment] 2023-08-16 19:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link.
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-18 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-18 19:45 UTC
Labels: Waiting for Reply
