### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by icecreate** [LeetCode-Feedback/LeetCode-Feedback#18558] opened 2023-12-09 09:36 UTC
### Category of the bug
result is [1,1,1]，but expect result is[1,1]

**Comment by LC-Pam** [comment] 2023-12-12 23:14
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code snippet and programming language you submitted that led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-19 18:13
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-19 18:13 UTC
Labels: Waiting for Reply
