### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by d-goridov** [LeetCode-Feedback/LeetCode-Feedback#15061] opened 2023-07-26 14:39 UTC
![twoSum](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95539832/679a2a48-3bbe-4a06-bece-e4f5167b772e)

#### Your LeetCode username
Dmitriy_dns

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
This task is needed test case for example
new int []{1, 3, 5, 7} and target = 8
my solution have answer new int[]{1, 2}
but must be new int[]{0, 3}

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public int[] twoSum(int[] nums, int target) {
        int start = 0;
        int end = 0;
        int index1 = 0;
        int index2 = 0;
        for(int i = 0; i < nums.length; i++) {
            start = nums[i];
            for (int j = i + 1; j < nums.length; j++) {
                end = nums[j];
                if (start + end == target) {
                    index1 = i;
                    index2 = j;
                    break;
                }
            }
        }
        return new int[]{index1, index2};
    }
};
```

**Comment by LC-Pam** [comment] 2023-07-26 21:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:27 UTC
Labels: LCUS, problem, Waiting for Reply
