### ISSUE TITLE
Incorrect expected output for a testcase

### ISSUE THREAD

**Issue by Gowrima** [LeetCode-Feedback/LeetCode-Feedback#16781] opened 2023-09-28 21:53 UTC
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息
<img width="1440" alt="Screenshot 2023-09-28 at 2 50 49 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5719962/fdadabc1-8a93-4aaf-8406-48c44c1bd982">

The correct answer for the following input is [0,1000000,1000001,1000002,5]
[0,3,2,1,4,5]
3
4
[1000000,1000001,1000002]
Expected output (incorrect) is [0,3,2,1000000,1000001,1000002,5] - all the nodes between 3 and 4 (inclusive) should be deleted.

**Comment by LC-Pam** [comment] 2023-09-29 17:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission (link) that you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-03 17:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-03 17:23 UTC
Labels: Waiting for Reply
