### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by JavohirSD** [LeetCode-Feedback/LeetCode-Feedback#16844] opened 2023-10-01 16:39 UTC
Please add test cases with symbol "E" . For example test case "1E10".  Most of the users solved this problem by replacing "e" to another symbol.
Because in  some programming languages exists native functions like a atoi. But all of them repeats same glitch when "e" or "E" exists after numbers in string.

For example this code accepted successfully. But it can not pass from the test case above )

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54473854/1cea121a-850b-4598-a70b-922e381c9d96)

**Comment by LC-Pam** [comment] 2023-10-03 18:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:23 UTC
Labels: Waiting for Reply
