### ISSUE TITLE
Missing Test Case - 66. Plus One; add [9,9,9] test case

### ISSUE THREAD

**Issue by jainary4** [LeetCode-Feedback/LeetCode-Feedback#14281] opened 2023-06-22 04:31 UTC
#### Your LeetCode username
 Aryan_12344

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [!] Missing Test Cases - add a test case [9,9,9]

#### Description of the bug

if we add a test case f type [9,9,9] we can find out does the code check for extreme cases where the digit is about to get incremented and would force the user to check for all cases of type 10^n-1 by just providing a test case of [9] the developer 
could set digits[0]=1 and digits[1]=0 a 4th test case with [9,9,9] would force the developer to generalize the extreme case.
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Sugamgoel28** [comment] 2023-06-22 06:33
@Aryan_12344

The optimized code perfectly works correctly for the test case [9, 9, 9], as well as other test cases. The test case is not missing. You can verify this by using the custom test case option. If you have any further questions or need assistance with anything else, feel free to let me know. I'm here to help!

**Comment by Sugamgoel28** [comment] 2023-06-22 06:34
> #### Your LeetCode username
> Aryan_12344
> #### Category of the bug
> * [ ]  Question
> * [ ]  Solution
> * [ ]  Language
> * [!] Missing Test Cases - add a test case [9,9,9]
> 
> #### Description of the bug
> if we add a test case f type [9,9,9] we can find out does the code check for extreme cases where the digit is about to get incremented and would force the user to check for all cases of type 10^n-1 by just providing a test case of [9] the developer could set digits[0]=1 and digits[1]=0 a 4th test case with [9,9,9] would force the developer to generalize the extreme case.
> 
> #### Code you used for Submit/Run operation
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/pieces.png)
> Copy and Save
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> ```
> // Two Sum
> class Solution {
> public:
>     vector<int> twoSum(vector<int> &a, int s) {
> 
>     }
> };
> ```
> 
> #### Language used for code
> #### Expected behavior
> #### Screenshots
> #### Additional context

@jainary4 

@Aryan_12344

The optimized code perfectly works correctly for the test case [9, 9, 9], as well as other test cases. The test case is not missing. You can verify this by using the custom test case option. If you have any further questions or need assistance with anything else, feel free to let me know. I'm here to help!

**Comment by LC-Pam** [comment] 2023-06-22 18:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:29 UTC
Labels: LCUS, problem
