### ISSUE TITLE
Missing Test Case - 12. Integer to Roman

### ISSUE THREAD

**Issue by easyans** [LeetCode-Feedback/LeetCode-Feedback#12639] opened 2023-03-29 04:38 UTC
#### Your LeetCode username

ar0829

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

class Solution {
public:
    int getid(vector<pair<int,string>>&v,int k){
        int st = 0,ed = v.size()-1;
        while(st<=ed){
            int mid = (st+ed)/2;
            if(v[mid].first==k)
                return mid;
            else if(v[mid].first<k)
                st = mid + 1;
            else
                ed = mid - 1;
        }
        return ed;
    }

    string intToRoman(int num) {
        vector<pair<int,string>>v{{1, "I"}
        ,{4, "IV"}
        ,{5, "V"}
        ,{9, "IX"}
        ,{10, "X"}
        ,{40, "XL"}
        ,{50, "L"}
        ,{90, "XC"}
        ,{100, "C"}
        ,{400, "CD"}
        ,{500, "D"}
        ,{900, "CM"}
        ,{1000, "M"}};
        
        string ans = "";
        while(num){
            int id = getid(v,num);
            ans += v[id].second;
            num -= v[id].first;
        }

        return ans;
    }
};

**Comment by LC-Pam** [comment] 2023-03-29 20:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-31 14:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-31 14:59 UTC
Labels: LCUS, problem
