### ISSUE TITLE
Missing Test Case - 1870. Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by Soumyajitkundu24** [LeetCode-Feedback/LeetCode-Feedback#15067] opened 2023-07-26 16:42 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Soumyajitkundu24** [comment] 2023-07-26 16:43
class Solution {
    public int minSpeedOnTime(int[] dist, double hour) {
        int left = 1;
        int right = 10000000; // 10^7, the upper bound specified in the problem
        int n = dist.length;

        // Binary search
        while (left < right) {
            int mid = left + (right - left) / 2;
            double totalHours = 0.0;

            // Calculate the total time taken at the current speed
            for (int i = 0; i < n - 1; i++) {
                totalHours += Math.ceil((double) dist[i] / mid);
            }
            totalHours += (double) dist[n - 1] / mid;

            // Check if the total time is less than or equal to the given hour
            if (totalHours <= hour) {
                right = mid;
            } else {
                left = mid + 1;
            }
        }

        // Check if it's impossible to reach the office on time
        if (left == 10000000) {
            return -1;
        }

        return left;
    }
}

**Comment by LC-Pam** [comment] 2023-07-26 21:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:30 UTC
Labels: LCUS, problem, Waiting for Reply
