### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by sheoran0917** [LeetCode-Feedback/LeetCode-Feedback#7400] opened 2022-05-22 16:46 UTC
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
public class Solution {
    public int[] TwoSum(int[] nums, int target) {
        int [] result = new int[2]; 
        bool isFound = false;
        for(int i=0; i<nums.Length-1; i++)
        {
            int diff = target - nums[i];
            result[0] = i;
            //Serach the diff in the remaining array
            for(int j=i+1; j<nums.Length; j++)
            {
                if(diff == nums[j])
                {
                    result[1] = j;
                    isFound = true;
                }
            }
            if(isFound)
                break;
        }
        return result;
    }
}

#### C#
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2022-05-23 20:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the missing test case or issues?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-24 18:10
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-24 18:10 UTC
Labels: LCUS, problem
