### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by Manjari-99** [LeetCode-Feedback/LeetCode-Feedback#17055] opened 2023-10-09 05:14 UTC
#### Your LeetCode username
manjarinm10

#### Category of the bug

- [ ] Missing Test Cases

#### Description of the bug

Question :[34. find-first-and-last-position-of-element-in-sorted-array]( https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/)
We also need a test case that has the target only once in the array. So that the same index is returned twice.
e.g.
nums : [5,7,7,8,10], target: 8
Output : [3,3]

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69254860/0dce5278-5206-4ccd-b028-ba85fd248b13)

**Comment by LC-Pam** [comment] 2023-10-09 19:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:38
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:38 UTC
Labels: Waiting for Reply
