### ISSUE TITLE
Bug in "Quick Union - Disjoint Set" video  "Why is Quick Union More Efficient than Quick Find?"

### ISSUE THREAD

**Issue by f3z0** [LeetCode-Feedback/LeetCode-Feedback#16730] opened 2023-09-27 01:58 UTC
#### Your LeetCode username
coolblade

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the video _Why is Quick Union More Efficient than Quick Find?_ it states the time complexity of the union operation in Quick Find is O(N^2) because it has to do the find operation twice and states multiple times in the video that the find operation is O(N) time complexity for Quick Find. This is false, the time complexity of find is O(1) in quick find as it is an array lookup (perhaps this is why they call it quick find). Further in clarifying notes the author goes on to explain the time complexity is correct but in no way does two array lookups followed by looping through an array equate to O(N*N), it is O(N). The premise of this video is incorrect, the Quick Find has a faster theoretical time complexity overall than Quick Union but in practice it will depend on the runtime characteristics of finds vs unions (e.g. more read heavy vs more write heavy).

**Comment by LC-Pam** [comment] 2023-09-27 19:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The video page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-02 02:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-02 02:03 UTC
Labels: Waiting for Reply
