### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by denis-kosolapov** [LeetCode-Feedback/LeetCode-Feedback#14828] opened 2023-07-16 23:45 UTC
```
class Solution:

    def merge(self, word1: list, word2: list) -> str:
        res = dict(zip(word1, word2))

        word = []
        for k, v in res.items():
            sub_str = ''.join([k, v])
            word.append(sub_str)
        merged = ''.join(word)

        return merged
    def mergeAlternately(self, word1: str, word2: str) -> str:
        word1 = list(word1)
        word2 = list(word2)

        if len(word1) == len(word2):
            word = self.merge(word1, word2)
            return word

        if len(word1) < len(word2):
            num = len(word2) - len(word1)
            word = self.merge(word1, word2[:num]) + ''.join(word2[num:])
            return word

        if len(word1) > len(word2):
            num = len(word1) - len(word2)
            word = self.merge(word1, word2) + ''.join(word1[num:])
            return word



if __name__ == "__main__":
    merged = Solution().mergeAlternately("ab", "pqrs")
    print(merged)

    merged = Solution().mergeAlternately("abc", "pqr")
    print(merged)
    
    merged = Solution().mergeAlternately("abcd", "pq")
    print(merged)
```

**Comment by denis-kosolapov** [comment] 2023-07-16 23:45
my solution

**Comment by LC-Pam** [comment] 2023-07-17 20:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:11 UTC
Labels: LCUS, problem, Waiting for Reply
