### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Shiro2568** [LeetCode-Feedback/LeetCode-Feedback#18157] opened 2023-11-19 13:53 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
def roman_to_int(s)
  symbols = {
      "I" => 1,
      "V" => 5,
      "X" => 10,
      "L" => 50,
      "C" => 100,
      "D" => 500,
      "M" => 1000
  }
  res = 0
    (s.size-1).times do |index|
        # Если текущий символ будет больше или равняться следующему, то прибавляем текущий символ.
        # LVIII
        if symbols[s[index]] >= symbols[s[index+1]]
            res += symbols[s[index]]
        else 
            res -= symbols[s[index]]
        end
    end
  res += symbols[s[-1]]
end

# Пример использования
puts roman_to_int("MCMIV")

```ruby


### Expected behavior
<!-- A clear and concise description of what was expected to happen in
contrast with what happened. -->


### Screenshots
<!-- If applicable, add screenshots to explain the issue. -->


### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-11-20 21:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:15 UTC
Labels: Waiting for Reply
