### ISSUE TITLE
1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by pr-chaitanya** [LeetCode-Feedback/LeetCode-Feedback#12973] opened 2023-04-15 14:23 UTC
Input: n=3 ranges=[1,0,0,1]
Answer need to be 2 not -1.
Wrong evaluation.
My LC id: https://leetcode.com/ram_98/

**Comment by LC-Pam** [comment] 2023-04-18 22:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-21 18:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-21 18:16 UTC
Labels: LCUS, problem
