### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by Ritikseptember2003** [LeetCode-Feedback/LeetCode-Feedback#12469] opened 2023-03-20 05:14 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

class Solution {
    public boolean canPlaceFlowers(int[] flowerbed, int n) {
        int count = 0;
        for(int i = 0; i<flowerbed.length && count<n; i++)
        {
if(flowerbed[i] == 0 && (i == 0 || flowerbed[i-1] == 0) && (i == flowerbed.length-1 || flowerbed[i+1] == 0))
            {
                flowerbed[i] = 1;
                count++;
            }
        }
        return count == n;
    }
}

**Comment by LC-Pam** [comment] 2023-03-20 19:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-22 20:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-22 20:29 UTC
Labels: LCUS, problem
