### ISSUE TITLE
A minor typo in Array 101 explore card

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#16048] opened 2023-08-30 16:56 UTC
#### Your LeetCode username
aleksandr-kiliushin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The word "operation" should be in plural form to match with "one of the most commonly executed."

The corrected sentence should be:
"This is one of the most commonly executed operation**s** on our collection."

#### Screenshots
<img width="972" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/c4000eb1-89a5-4041-8859-20c2c11ad39e">

**Comment by LC-Pam** [comment] 2023-08-31 18:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:52 UTC
Labels: Waiting for Reply
