### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by Pranay-Pachangane** [LeetCode-Feedback/LeetCode-Feedback#12069] opened 2023-02-28 16:52 UTC
#### Category of the bug
- [ Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type. ] Question

- [ class Solution(object):
    def isValid(self, s):
        while '()' in s or '[]'in s or '{}' in s:
            s = s.replace('()','').replace('[]','').replace('{}','')
        return False if len(s) !=0 else True ] Solution
- [ Python ] Language
- [ "{[()]}"] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def isValid(self, s):
        while '()' in s or '[]'in s or '{}' in s:
            s = s.replace('()','').replace('[]','').replace('{}','')
        return False if len(s) !=0 else True
```

**Comment by LC-Pam** [comment] 2023-03-01 18:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue of this problem. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-02 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-02 19:47 UTC
Labels: LCUS, problem
