### ISSUE TITLE
Missing Test Case - 876. Middle of the Linked List

### ISSUE THREAD

**Issue by Palakpreet** [LeetCode-Feedback/LeetCode-Feedback#10581] opened 2022-12-28 06:20 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
 ListNode*h=head;
        ListNode*k=head;
        int p=0;
        while(h!=NULL){
            h=h->next;
            p=p+1;
        }
        p=p/2+1;
        for(int i=1;i<p;i++){
           k=k->next;
        }
        head=k;
        return head;
    }
};
```

#### Expected behavior

The number of nodes must be minimum 3 then this code must work otherwise for two nodes it should fail. But condition for minimum three nodes is not mentioned.

**Comment by LC-Pam** [comment] 2022-12-29 19:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-30 19:31
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-30 19:31 UTC
Labels: LCUS, problem
