### ISSUE TITLE
Missing Test Case - 1535. Find the Winner of an Array Game

### ISSUE THREAD

**Issue by rohithjnv96** [LeetCode-Feedback/LeetCode-Feedback#17809] opened 2023-11-05 04:53 UTC
#### Your LeetCode username
_ro_    (Rohith, rohith0430@gmail.com)

#### Category of the bug
- Question  -> 1535. Find the Winner of an Array Game](https://leetcode.com/problems/find-the-winner-of-an-array-game/)
- Solution -> Needs comprehensive test cases for array length 2 
- Language -> Python
- Missing Test Cases  ->  arr=[2,3], k=10   AND   arr=[2,3]       k=1

#### Description of the bug
Although my Python solution passes all test cases and submission is accepted, the code obviously has a bug in first two lines. That is in "if len(arr)==2: return min(arr)". I mistyped min instead of max and it somehow passes all test cases, but with custom test case  arr=[2,3]  and  k=10 and arr=[2,3] and k=1, its obvious that the code has a bug in it, but it passes all test cases. So my theory is that the test cases do not include comprehensive test cases for when length of array is equal to two.

#### Code you used for Submit/Run operation

```
# Time:O(n) Space:O(n)
        if len(arr)==2:
            return min(arr)
        if k>=len(arr):
            return max(arr)
        arr = deque(arr)
        win_count = 0
        while win_count<k:
            temp, win_count = (arr[1], win_count+1) if arr[0]>arr[1] else (arr[0], 1)
            arr.remove(temp)
            arr.append(temp)
        return arr.popleft(
```

#### Language used for code

Python

#### Expected behavior

Since my code had a bug in it for mentioned custom test cases, I expected that my solution  would be rejected. But to my surprise it went through. Only reason I can think for this is that my custom test cases are not included in ALL test cases on which code is tested against.

#### Screenshots

<img width="1440" alt="Screenshot 2023-11-05 at 3 47 31 pm" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92717319/f3623943-80d8-433a-bd57-d15e38f94319">

<img width="1440" alt="Screenshot 2023-11-05 at 3 47 22 pm" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92717319/2e38a00a-f159-4051-8e17-04510877ffd4">

**Comment by LC-Pam** [comment] 2023-11-13 22:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:05 UTC
Labels: Waiting for Reply
