### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by TryHardCode1** [LeetCode-Feedback/LeetCode-Feedback#8261] opened 2022-07-20 03:32 UTC
#### Your LeetCode username

tonghoai17a

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I want to add test cases

#### Test cases:
Input: (()[[]])
Output: Yes

Input: {{][]{{}}}
Output: No

**Comment by stormsunshine** [comment] 2022-07-20 08:17
What is the code that can get accepted but fails on the test cases?

**Comment by LC-Pam** [comment] 2022-07-20 16:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-22 17:25
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-22 17:25 UTC
Labels: LCUS, problem
