### ISSUE TITLE
Missing Test Case - 180. Consecutive Numbers

### ISSUE THREAD

**Issue by harshvardhan2206** [LeetCode-Feedback/LeetCode-Feedback#17187] opened 2023-10-12 17:52 UTC
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hg29375/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hg29375/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | num
-- | --
1 | 1
2 | 1
3 | 1
4 | 2
5 | 2
6 | 1
7 | 3
8 | 4
9 | 4
10 | 4
11 | 3
12 | 6
13 | 2
14 | 3
15 | 3
16 | 7
17 | 5
18 | 5
19 | 5

</body>

</html>

**Comment by LC-Pam** [comment] 2023-10-12 18:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-17 20:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-17 20:57 UTC
Labels: Waiting for Reply
