### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Abat01** [LeetCode-Feedback/LeetCode-Feedback#14218] opened 2023-06-18 13:13 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Abat01** [comment] 2023-06-18 13:14
let map =new Map();
  for(let i=0; i <nums.length; i++){
      let num1=nums[i];
      let num2 = target-num1;
      if(map.has(num2)){
          return[i, map.get(num2)];
      }
      map.set(num1,i);
  }
  };

**Comment by LC-Pam** [comment] 2023-06-20 20:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link and the missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-22 18:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-22 18:10 UTC
Labels: LCUS, problem
