### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14800] opened 2023-07-15 18:07 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// String To Integer
class Solution {
    public int myAtoi(String s) {
        int i = 0;
        int n = s.length();

        while (i < n && s.charAt(i) == ' ') { 
            i++;
        }

        int positive = 0;
        int negative = 0;

        if (s.charAt(i) == '+') {
            positive++;
            i++;
        }

        if (s.charAt(i) == '-') {
            negative++;
            i++;
        }

        double ans = 0;

        while (i < n && s.charAt(i) >= '0' && s.charAt(i) <= '9') {
            ans = ans * 10 + (s.charAt(i) - '0');
            i++;
        }

        if (negative > 0) { 
            ans = -ans;
        }
        if (positive > 0 && negative > 0) { 
            return 0;
        }

        int INT_MAX = (int) Math.pow(2, 31) - 1;
        int INT_MIN = (int) Math.pow(-2, 31);

        if (ans > INT_MAX) { 
            ans = INT_MAX;
        }

        if (ans < INT_MIN) { 
            ans = INT_MIN;
        }

        return (int) ans;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-17 20:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:09 UTC
Labels: LCUS, problem, Waiting for Reply
