### ISSUE TITLE
"FFTTFFFFTFFFFFTTTTTFTFTTTTFTFTTTFFTTFFTTFTFTTFFTFTFFFFTTFTTTTTTFTFTFTTTFTFFTTTFFTTTFFTTFTTFFTTFFFFFT"Missing Test Case - 2024. Maximize the Confusion of an Exam

### ISSUE THREAD

**Issue by mayank446** [LeetCode-Feedback/LeetCode-Feedback#14607] opened 2023-07-07 22:02 UTC
#### Your LeetCode username
may_codes

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
 A testcase is missing which causes successful submissions of incomplete code 
Missing : "FFTTFFFFTFFFFFTTTTTFTFTTTTFTFTTTFFTTFFTTFTFTTFFTFTFFFFTTFTTTTTTFTFTFTTTFTFFTTTFFTTTFFTTFTTFFTTFFFFFT"

#### Code you used for Submit/Run operation
<!-- 
```class Solution {
public:
    int maxConsecutiveAnswers(string answerKey, int k) {
        queue<int> q;
        int count = 0;
        int cur_l = 0, max_l = 0;
        for(int i=0; i<answerKey.size(); i++){
            if(answerKey[i]=='T'){
                count++;
            }
            else {
                if(!q.empty() || count != 0){
                    if(q.size() < k){
                        q.push(count);
                        cur_l += count;
                        cur_l++;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                    else if(q.size() == k){
                        q.push(count);
                        cur_l += count;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                    else {
                        cur_l -= q.front();
                        q.pop();
                        q.push(count);
                        cur_l += count;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                }
            }
        }
        if(count){
            if(q.size()<=k){
                cur_l += count;
                count = 0;
                max_l = max(max_l, cur_l);
            }
            else {
                cur_l -= q.front();
                cur_l += count;
                count = 0;
                max_l = max(max_l, cur_l);
            }
        }
        if(q.size()<k && answerKey[0]=='F'){
            cur_l ++;
            max_l = max(max_l, cur_l);
        }
        while(!q.empty()){
            q.pop();
        }
        cur_l = 0;

        for(int i=0; i<answerKey.size(); i++){
            if(answerKey[i]=='F'){
                count++;
            }
            else {
                if(!q.empty() || count != 0){
                    if(q.size() < k){
                        q.push(count);
                        cur_l += count;
                        cur_l++;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                    else if(q.size() == k){
                        q.push(count);
                        cur_l += count;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                    else {
                        cur_l -= q.front();
                        q.pop();
                        q.push(count);
                        cur_l += count;
                        count = 0;
                        max_l = max(max_l, cur_l);
                    }
                }
            }
        }
        if(count){
            if(q.size()<=k){
                cur_l += count;
                count = 0;
                max_l = max(max_l, cur_l);
            }
            else {
                cur_l -= q.front();
                cur_l += count;
                count = 0;
                max_l = max(max_l, cur_l);
            }
        }
        // if(q.size()<k && answerKey[0]=='T'){
        //     cur_l ++;
        //     max_l = max(max_l, cur_l);
        // }
        int i=0;
        while(q.size()<k && answerKey[i]=='T'){
            q.push(0);
            cur_l ++;
            i++;
        }
        max_l = max(max_l, cur_l);
        return max_l;
    }
};```-->

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++ 


#### Expected behavior
<!--An incomplete solution was successfully accepted-->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!--No additional context-->

**Comment by LC-Pam** [comment] 2023-07-11 00:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-12 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-12 19:08 UTC
Labels: LCUS, problem
