### ISSUE TITLE
- 1. Two Sum

### ISSUE THREAD

**Issue by DingueT7n** [LeetCode-Feedback/LeetCode-Feedback#18288] opened 2023-11-25 18:53 UTC
### LeetCode guerbouzmohamedalla

###1. Two Sum https://leetcode.com/problems/two-sum/

### Category of the bug
- [x] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```

public class Solution {
    public int[] TwoSum(int[] nums, int target) {
       
     Dictionary<int, int> numDict = new Dictionary<int, int>();
        
        for (int i = 0; i < nums.Length; i++) {
            int complement = target - nums[i];
            
            if (numDict.ContainsKey(complement)) {
                return new int[] { numDict[complement], i };
            }
            
            if (!numDict.ContainsKey(nums[i])) {
                numDict.Add(nums[i], i);
            }
        }
        
        return new int[0]; 
    }
}

```

**Comment by LC-Pam** [comment] 2023-11-28 19:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-01 21:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-01 21:40 UTC
Labels: Waiting for Reply
