### ISSUE TITLE
missing testcase - 3011.Find if array can be sorted

### ISSUE THREAD

**Issue by batman-1208** [LeetCode-Feedback/LeetCode-Feedback#19580] opened 2024-01-20 17:45 UTC
### LeetCode Username
jainkunal1208

### Problem number, title, and link
3011. Find if Array Can Be Sorted 
https://leetcode.com/problems/find-if-array-can-be-sorted/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
given test is failing in accepted solution

### Language used for code
C++

### Code used for Submit/Run operation

 ```
#define ll int
#define nb(A) __builtin_popcountll(A)
class Solution {
public:
  
    bool canSortArray(vector<int>& nums) {
     ll n=nums.size();vector<int>ch=nums;ll p=-1;
        sort(ch.begin(),ch.end());
        for(ll i=0;i<n;i++){
            if(nums[i]!=ch[i]){p=i;break;}
            ch[i]=nb(ch[i]);
        }if(p==-1)return true;
        // cout<<p<<endl;
        // for(ll i=p;i<n;i++){ch[i]}
        ll ed=nb(nums[p]);
        for(ll i=p;i<n;i++){ll ol=nb(nums[i]);
            if(nb(nums[i])!=nb(ch[i])){
               return false;
            }if(i!=n-1&&nb(ch[i])>nb(ch[i+1]))return false;
        }return true;

    }
};
```

### Expected behavior
expected TRUE getting FALSE
test case ->[17,9,32]  [5,3,8]

### Screenshots

![Screenshot 2024-01-20 231202](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138300877/4bf9024e-cb68-48c8-a67c-ca7e86f8c36a)
![Screenshot 2024-01-20 231127](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138300877/9a915f95-9b5b-4970-90d6-f958fd8fbbf7)

**Comment by LC-Pam** [comment] 2024-01-22 14:51
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/19578

**Closed by LC-Pam** 2024-01-22 14:51 UTC
