### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by RealRakshit** [LeetCode-Feedback/LeetCode-Feedback#17461] opened 2023-10-26 03:06 UTC
#### Your LeetCode username

realrakshit

#### Category of the bug
- [ ] Question
- [1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

wrong test case 

#### Code you used for Submit/Run operation

class Solution {
public:
    int minSubArrayLen(int target, vector<int>& nums) {
        sort(nums.begin(),nums.end());
        int count=0;
        int sum=0;
        for(int i=nums.size()-1; i>=0;i--){
            sum=sum+nums[i];
            count++;
            if(sum>=target){
                return count;
            }
          
        }
        return 0;
    }
};

#### Language used for code

C++

#### Expected behavior

when we run this testcase [12,28,83,4,25,26,25,2,25,25,25,12] the expected outcome should be 7 instead of 8 since 83+28+26+25+25+25+25=237 which is just greater than target. These are 7 digits ,so the answer should be 7 not 8.

**Comment by LC-Pam** [comment] 2023-10-27 19:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by RealRakshit** [comment] 2023-10-28 06:54
I do not have it yet.

**Comment by LC-Pam** [comment] 2023-11-02 17:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:59 UTC
Labels: Waiting for Reply
