### ISSUE TITLE
Missing Test Case - 2095. Delete the Middle Node of a Linked List

### ISSUE THREAD

**Issue by Chrisildabre** [LeetCode-Feedback/LeetCode-Feedback#16263] opened 2023-09-07 23:50 UTC
#### username
chrisildabre

#### Description of the bug

A test case is missing wherein we just have one element in an array and then delete that corresponding element.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public ListNode deleteMiddle(ListNode head) {
        ListNode fast=head;
        ListNode slow=head;
##for the 4th test case.
        while(head.next==null){
            return head.next;
        }
        while(fast!=null && fast.next!=null){
            slow=slow.next;
            fast=fast.next.next;
        }
        //for test case 3.
        if(slow.next==null){
            head.next=null;
            return head;
        }
        slow.val=slow.next.val;
        slow.next=slow.next.next;

        return head;

    }
}
'''

#### Language used for code
<!-- JAVA -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
input=[1]
output=[ ]


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-09-11 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:10 UTC
Labels: Waiting for Reply
