### ISSUE TITLE
Missing Test Case - 1020. Number of Enclaves

### ISSUE THREAD

**Issue by SatyaPrana** [LeetCode-Feedback/LeetCode-Feedback#12812] opened 2023-04-07 08:41 UTC
#### Your LeetCode username

Satya prana

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing test cases

#### Description of the bug

What if in the matrix borders don't contains a border 1 means if the borders of the matrix doesn't contain a land cell

#### Code you used for Submit/Run operation

class Solution {
    public int numEnclaves(int[][] grid) {
        int m = grid.length;
        int n = grid[0].length;
        boolean[][] visit = new boolean[m][n];
        for (int i = 0; i < m; i++){
            if (grid[i][0] == 1 && !visit[i][0]){
                dfs(i,0,m,n,grid,visit);
            }

            if (grid[i][n - 1] == 1 && !visit[i][n - 1]){
                dfs(i,n - 1,m,n,grid,visit);
            }
        }

        for (int i = 0; i < n; i++){
            if (grid[0][i] == 1 && !visit[0][i]){
                dfs(0,i,m,n,grid,visit);
            }

            if (grid[m - 1][i] == 1 && !visit[m - 1][i]){
                dfs(m - 1,i,m,n,grid,visit);
            }
        }

        int count = 0;
        for (int i = 0; i < m; i++){
            for (int j = 0; j < n; j++){
                if (grid[i][j] == 1 && !visit[i][j]){
                    count++;
                }
            }
        }
        return count;
    }

    public void dfs(int x,int y,int m,int n,int[][] grid,boolean[][] visit){
        if (x < 0 ||  y < 0 || x >= m || y >= n || grid[x][y] == 0 || visit[x][y]){
            return ;
        }

        visit[x][y] = true;
        int[] dirx = {0,1,0,-1};
        int[] diry = {-1,0,1,0};
        for (int i = 0; i < 4; i++){
            dfs(x + dirx[i],y + diry[i],m,n,grid,visit);
        }
        return;
    }
}
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-04-10 22:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-12 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-12 19:45 UTC
Labels: LCUS, problem
