### ISSUE TITLE
Missing Test Case - 1996. The Number of Weak Characters in the Game

### ISSUE THREAD

**Issue by TanmayAJadhav** [LeetCode-Feedback/LeetCode-Feedback#8977] opened 2022-09-09 06:02 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

In 1996. The Number of Weak Characters in the Game this problem
consider one test case
[[1,2],[10,7],[5,6],[4,3]]
In this character 2 is greater than all other characters so count will 3
character 2 is greater than character 1 and 2 so count will increase by 2
character 3 is greater than character so count will increase by 1
so answer will be 6 , right ?

**Comment by TanmayAJadhav** [comment] 2022-09-09 06:06
In 1996. The Number of Weak Characters in the Game this problem
consider one test case
[[1,2],[10,7],[5,6],[4,3]]
In this character 2 is greater than all other characters so count will 3
character 2 is greater than character 1 and 2 so count will increase by 2
character 3 is greater than character so count will increase by 1
so answer will be 6 , right ?

**Comment by LC-Pam** [comment] 2022-09-12 02:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-13 21:23
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-13 21:23 UTC
Labels: LCUS, problem
