### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Shivli17** [LeetCode-Feedback/LeetCode-Feedback#13160] opened 2023-04-26 17:31 UTC
class Solution {
    public boolean isPalindrome(int x) {
        int i,sum=0;
        String str;
        str= Integer.toString(x);
        int l=str.length(),r=1;
        for(i=0;i<str.length();i++)
        {
          if(str.charAt(i)!=str.charAt(l-1))
          r=0;l--;
        } 
        if (r==0) 
        return false;
        else
        return true;  
    }
}

**Comment by LC-Pam** [comment] 2023-04-26 20:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-02 21:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-02 21:20 UTC
Labels: LCUS, problem
