### ISSUE TITLE
Missing Test Case - 2722. Join Two Arrays by ID

### ISSUE THREAD

**Issue by crumbyshirt** [LeetCode-Feedback/LeetCode-Feedback#16096] opened 2023-09-01 17:51 UTC
#### Your LeetCode username
userJake

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Expected behavior
A test should verify that the items have been sorted when they are passed in with the ids in the wrong order.

#### Additional context
All the test cases are being passed in with the ids in order. I suggest adding one that that has the ids out of order.

Like this:
first array input [{"id": 9,"x": 1},{"id": 2,"x": 9}]
second array input [{"id": 3,"x": 5}]

**Comment by LC-Pam** [comment] 2023-09-01 20:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:51 UTC
Labels: Waiting for Reply
