### ISSUE TITLE
Missing Test Cases - 7. Reverse Integer

### ISSUE THREAD

**Issue by akshayvkt** [LeetCode-Feedback/LeetCode-Feedback#17107] opened 2023-10-11 07:23 UTC
#### Your LeetCode username
 
akshayak235

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Testcases to cover integers outside the 32-bit range.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python

### Testcase suggestions to add
Input: x = 1534236469
Output: 0

Input: x = -3134236469)
Output: 0

#### Expected behavior

If there are testcases to cover the integers outside 32-bit range, it'll be helpful to reduce the submission failures.

**Comment by LC-Pam** [comment] 2023-10-11 15:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:58 UTC
Labels: Waiting for Reply
