### ISSUE TITLE
860.Lemonade Change, My code is right yet I get wrong answer

### ISSUE THREAD

**Issue by mommyslab** [LeetCode-Feedback/LeetCode-Feedback#516] opened 2020-06-22 03:40 UTC
#### 
Nayema

 Category of the bug
 Solution

 Description of the bug
I wrote the solution first about 4 months ago. Then wanted to redo the problem about 4 days ago and received wrong answer as solution. However, as I compared solutions that were right and wrong, both had same logic, there was no syntax error in the second one either, can someone please help me find out if my second solution truly has some logical error.
The first image is of the code that ran successfully, the second image has code that wasn't successful

 Language used for code
 C++ 

 Expected behavior
honestly not sure 

Screenshots
![image](https://user-images.githubusercontent.com/23732653/85246367-7007de00-b418-11ea-8c8a-853379b0bad1.png)

![image](https://user-images.githubusercontent.com/23732653/85246430-9cbbf580-b418-11ea-89c7-1667cecff269.png)

**Comment by CooperCooperCooper** [comment] 2020-06-24 04:20
Hi @mommyslab ,
Thank you for reaching out to us. Would you please exchange the screenshots of the code with actual code and their languages? It will really help us to test the codes and reproduce the issue on our end.

**Comment by lc-kate** [comment] 2020-07-07 01:03
Hi @mommyslab ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag @lc-christina in a new comment. Thank you.

**Closed by lc-kate** 2020-07-07 01:03 UTC
Labels: LCUS, problem
