### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by VasisthaPrakhar** [LeetCode-Feedback/LeetCode-Feedback#14403] opened 2023-06-27 18:17 UTC
#### Your LeetCode username
int_float_double

#### Category of the bug
Missing Test Cases 

#### Description of the bug
In my solution :-
```
for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                ll sum=nums1[i]+nums2[j];
                if(pq.size()<k){
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else if(sum<pq.top().first){
                    pq.pop();
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else{
                    break;
                }
            }
        }
```
I had clearly used 2 nested arrays along with some conditions to halt them but in some extreme cases i.e., size(nums1) & size(nums2) is equal to 1e5 which is the upper limit of given constraint and most of the elements result in same sum i.e. if we take all elements as -1e9(lower limit acc to constraints) then it should not be working but instead of giving Time Limit Exceeded error it works just fine.
 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/c81bb664-1f58-4c15-993c-4f5bde895883)

which indeed concludes that the used testcases are weak and new testcases must be added.
So, I generate simple testcase and run it using console (
[Sample_TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11885889/Sample_TestCase.txt)
).

It results in :
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/96e18335-018d-4e08-856d-1904bcab69f6)
So, I firmly believe that this testcase should be used for checking submissions so that only optimal solution are considered correct.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    typedef long long int ll;
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        vector<vector<int>>ans;
        int n=nums1.size();
        int m=nums2.size();
        priority_queue<pair<ll,pair<int,int>>>pq;
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                ll sum=nums1[i]+nums2[j];
                if(pq.size()<k){
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else if(sum<pq.top().first){
                    pq.pop();
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else{
                    break;
                }
            }
        }
        while(!pq.empty()){
            ans.push_back({pq.top().second.first,pq.top().second.second});
            pq.pop();
        }
        reverse(ans.begin(),ans.end());
        return ans;
    }
};
```
Along with this solution code, I also used your most optimized code to check this test case and that code also gives TLE on Console

#### Language used for code
C++ 

#### Expected behavior
Solution was accepted, despite being not optimal

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/2b3579aa-ebe4-48a3-b591-c3e5f6695a02)

#### Additional context
I also used one of the most popular solutions from discuss they also give TLE for this testcase.
[Sample_TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11885884/Sample_TestCase.txt)

**Comment by LC-Pam** [comment] 2023-06-27 18:41
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14402

**Closed by LC-Pam** 2023-06-27 18:41 UTC
