### ISSUE TITLE
Missing Test Case - 168. Excel Sheet Column Title

### ISSUE THREAD

**Issue by jaideepsainarayan** [LeetCode-Feedback/LeetCode-Feedback#15800] opened 2023-08-22 06:54 UTC
#### Your LeetCode username
"jaideep_sai_"

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Basically, most people use the LCM approach to solve this question
These are some test cases missing:

104
208
416
52
1404
832
1164
3328  

#### Code you used for Submit/Run operation

initial code with LCM approach (working for most of the test cases except above once) maybe I am missing something but  my intention is to add these special test cases:
```
class Solution:
    def fun(self,n,d):
        total=''
        r=27
        trigger='*'
        while n>26:
            r=n%26
            n=n//26
            total=d[r]+total
        total=d[n]+total
        return total

    def convertToTitle(self, columnNumber: int) -> str:
        d={1:'A',2:'B',3:'C',4:'D',5:'E',6:'F',7:'G',8:'H',9:'I',10:'J',11:'K',12:'L',13:'M',14:'N',15:'O',16:'P',17:'Q',18:'R',19:'S',20:'T',21:'U',22:'V',23:'W',24:'X',25:'Y',26:'Z',0:'Z'}
        return self.fun(columnNumber,d)
```

So later I modified the code and make it work(attaching the working code below). I feel better to add the above test cases too
```
def convertToTitle(self, n: int) -> str:
        if n<27:
            return chr(ord('A')+(n-1)%26)
        total=""
        while n>0:
            if n%26==0:
                total+=chr(ord('A')+25)
                n-=1
            else:
                total+=chr(ord('A')+n%26-1)
            n//=26
        return total[::-1]
```

#### Language used for code
python3 

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46133350/c294ca58-4b65-422a-a83c-73755088fc3d)

**Comment by LC-Pam** [comment] 2023-08-23 20:32
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:31 UTC
Labels: Waiting for Reply

**Comment by jaideepsainarayan** [comment] 2023-08-25 14:34
hey, wait keeping the link

**Comment by jaideepsainarayan** [comment] 2023-08-25 14:41
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by jaideepsainarayan** [comment] 2023-08-25 14:42
link:https://leetcode.com/problems/excel-sheet-column-title/submissions/1028315283/
