### ISSUE TITLE
Missing Test Case - 1757. Recyclable and Low Fat Products

### ISSUE THREAD

**Issue by Udaeyy** [LeetCode-Feedback/LeetCode-Feedback#17368] opened 2023-10-21 13:18 UTC
https://leetcode.com/problems/recyclable-and-low-fat-products/?envType=study-plan-v2&envId=top-sql-50
# Write your MySQL query statement below
select product_id
from Products
where low_fats = "Y" and recyclable = "Y"

**Comment by LC-Pam** [comment] 2023-10-23 19:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-27 18:58 UTC
Labels: Waiting for Reply
