### ISSUE TITLE
Missing Test Case - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by DACKaladhar** [LeetCode-Feedback/LeetCode-Feedback#13860] opened 2023-06-03 08:55 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ True] Missing Test Cases 

#### Code you used for Submit/Run operation

```
#Remove Letter To Equalize Frequency
class Solution:
    def equalFrequency(self, word: str) -> bool:

        cnt = [count for c in ascii_lowercase if (count := word.count(c)) > 0]

        if len(cnt) == 1 or set(cnt) == {1}:
            return True

        if len(set(cnt)) == 2:
            vc = Counter(cnt)
            if vc[1] == 1 or max(vc) == min(vc) + 1 and vc[max(vc)] == 1:
                return True

        return False
```

**Comment by LC-Pam** [comment] 2023-06-06 19:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:19 UTC
Labels: LCUS, problem
