### ISSUE TITLE
1,2,1,3,4,7,8,9,10 Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by AmolSGolhar** [LeetCode-Feedback/LeetCode-Feedback#16189] opened 2023-09-05 02:18 UTC
#### Your LeetCode username
amol

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases -------  1,2,1,3,4,7,8,9,10

#### Description of the bug

1,2,1,3,4,7,8,9,10 fail at this test case

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
       
       int s = 0;
       int e = nums.size()-1;
       
       int mid = s+(e-s)/2;
       while(s<e){
           if(nums[mid]<nums[mid+1])
                s=mid+1;
            else 
                e = mid;
         mid = s+(e-s)/2;
       }
       return s;
    }
};

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
answer should be 2


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-09-05 21:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-11 19:38
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-11 19:38 UTC
Labels: Waiting for Reply
