### ISSUE TITLE
143. Reorder List

### ISSUE THREAD

**Issue by bipanchu** [LeetCode-Feedback/LeetCode-Feedback#9585] opened 2022-10-22 21:19 UTC
'''
    void reorderList(ListNode* head)
 {
    ListNode* fast=head;
    ListNode* slow=head;
    
    while(fast->next&&fast->next->next)
    {
        fast=fast->next->next;
        slow=slow->next;
    }
    ListNode* mid=slow;
    
    ListNode* temp=revnode(mid->next);
    slow->next=NULL;
   
     
    ListNode* dummy=new ListNode(0);
    ListNode* helper=dummy;
    while(head||temp)
    {
		if(head)
			{ helper->next=head;
			  head=head->next;
			}
		  helper=helper->next;
			if(temp)
			 {
			 helper->next=temp;
			 temp=temp->next;
			 }
        helper=helper->next;
     
        
      }
		  head=dummy->next;
}

    ListNode* revnode(ListNode* head)
    {
        if(head==NULL||head->next==NULL)
        return head;
        ListNode* nhead=revnode(head->next);
        head->next->next=head;
        head->next=NULL;
        
        return nhead;
    }
'''

**Comment by LC-Pam** [comment] 2022-10-24 18:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 16:03
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 16:03 UTC
Labels: LCUS, problem
