### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by JHiebert92** [LeetCode-Feedback/LeetCode-Feedback#13410] opened 2023-05-11 17:32 UTC
#### Your LeetCode username
Janikole

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The given two test cases do not test for cases where the prefix is the entirety of the shortest word in the list, nor when the list is only a single word long.

#### My Suggested Additional Test Cases
`strs = ["catcher", "cat", "catchment", "cattle"]`
Expected Output: "cat"

`strs = ["single"]`
Expected Output: "single"

**Comment by LC-Pam** [comment] 2023-05-12 21:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-15 00:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-15 00:56 UTC
Labels: LCUS, problem
