### ISSUE TITLE
Missing Test Case - 2360. Longest Cycle in a Graph

### ISSUE THREAD

**Issue by SMath0510** [LeetCode-Feedback/LeetCode-Feedback#14766] opened 2023-07-14 21:23 UTC
#### Your LeetCode username

SMath0510

#### Category of the bug
- [ 2360] Question
- [ https://leetcode.com/problems/longest-cycle-in-a-graph/submissions/] Solution
- [ C++] Language
- [ [383,152,56,155,374,287,284,452,206,183,67,32,141,280,43,448,385,220,23,302,408,351,412,386,425,310,223,320,207,292,335,123,99,71,334,351,382,446,325,316,100,98,214,271,270,235,424,63,257,61,265,408,109,26,346,385,43,416,61,313,195,245,310,322,98,332,150,400,155,314,17,23,269,16,233,19,282,140,461,146,374,209,323,8,315,406,370,165,375,290,399,212,343,234,87,253,191,80,71,165,238,455,367,48,293,414,180,135,256,427,22,124,24,274,74,8,127,401,268,277,137,146,388,281,261,354,364,64,115,206,310,376,179,154,91,371,335,269,133,189,65,170,464,288,123,91,453,18,97,162,64,357,154,198,0,421,406,26,29,292,72,405,413,433,62,397,455,119,13,351,196,156,42,135,215,329,365,258,304,337,392,121,102,165,63,37,340,73,436,144,42,143,339,83,160,269,241,185,221,173,61,250,61,348,243,299,80,287,316,452,24,370,260,181,289,333,416,250,51,48,77,188,129,62,360,395,28,2,230,323,156,462,400,434,357,382,378,329,61,207,435,263,345,204,456,175,51,447,29,374,410,98,109,305,281,433,112,158,423,42,100,250,445,147,404,200,206,435,217,267,152,30,84,441,71,431,172,368,46,111,98,384,399,288,405,429,63,175,147,402,388,298,389,402,167,416,194,130,101,304,17,109,408,177,415,168,126,152,28,245,74,442,92,262,444,210,134,244,196,266,438,195,280,59,75,302,267,85,92,268,200,272,281,214,8,56,433,459,84,436,308,85,258,274,459,194,192,226,248,10,161,300,126,274,104,376,440,132,56,252,299,453,316,444,1,357,77,369,382,225,16,59,79,27,83,99,266,456,367,10,255,334,116,182,13,336,82,69,257,452,181,385,390,157,308,441,398,36,130,185,97,179,198,438,168,306,389,35,172,117,188,130,63,84,313,463,460,241,58,235,439,376,24,208,168,34,207,330,83,53,212,464,163,159,463,308,454,328,272,381,231,161,156,54,380,429,414,33,323,251,304,212,116,287,238,199,194,303,147,230,301,200,219,84,442]] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-07-17 20:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:08 UTC
Labels: LCUS, problem, Waiting for Reply
