### ISSUE TITLE
Missing Test Case - 638. Shopping Offers

### ISSUE THREAD

**Issue by thegeekymuggle** [LeetCode-Feedback/LeetCode-Feedback#8331] opened 2022-07-25 14:19 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ This ] Missing Test Cases 

#### Description of the bug

In my code I am using the current needs array array as key for memoization. In the result I am taking minimum of result from not taking the current offer (case 1) , by taking the current offer again (case 2) and by taking the next offer (case 3). I passed the same updated needs array to case 2 and case 3. So, if I am correct the memo will store the value of case 2 first and when case 3 is called it will return the value obtained from case 2. If I switch places of case 2 and case 3 in the code my solution won't get accepted. So according to my intuition a test case for this specific case is missing where minimum value is obtained from case 3 rather case 2.

#### Code you used for Submit/Run operation

```
class Solution:
    def shoppingOffers(self, price: List[int], special: List[List[int]], needs: List[int]) -> int:
        n = len(price)
        dp = {}
        def dfs(i, needs):
            if i == len(special):
                cost = 0
                for k in range(n):
                    if n > 0:
                        cost += needs[k] * price[k]
                return cost
            if tuple(needs) in dp:
                return dp[tuple(needs)]
            needs2 = needs.copy()
            cost = special[i][-1]
            
            for k in range(len(needs)):
                needs2[k] -= special[i][k]
            
            for num in needs2:
                if num < 0:
                    dp[tuple(needs)] = dfs(i+1, needs)
                    return dp[tuple(needs)]
                
            dp[tuple(needs)] = min(dfs(i+1,needs),cost+dfs(i,needs2),cost+dfs(i+1,needs2))
            
            return dp[tuple(needs)]
        
        return dfs(0,needs)
                
```

#### Expected behavior

If the missing test case is added it should work fine.

**Comment by LC-Pam** [comment] 2022-07-25 18:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:53
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:53 UTC
Labels: LCUS, problem
