### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Sumitkumar8091** [LeetCode-Feedback/LeetCode-Feedback#16619] opened 2023-09-23 05:04 UTC
#### Category of the bug
- [ - 9. Palindrome Number] Question
- [ ] Solution
- [ ] Language
- [Test case is n=101 ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isPalindrome(int x) {
        if(x>=0&&x<=9){
            return true;
        }
        if(x<0){
            return false;
        }
      int num=(int)Math.log10(x)+1;
         int arr[]=new int[num];
        int i=0;
    while(x!=0){
         arr[i]=x%10;
        i++;
        x/=10;
    }
    int start=0,end=num-1;
    while(start<end){
        if(arr[start]!=arr[end]){
            return false;
        }
        start++;
        end--;
    }
    return true;
    }
}
```

**Comment by saumil-16** [comment] 2023-09-23 05:23
Here's the correct code

public class PalindromeTest {
    public static void main(String[] args) {
        Solution solution = new Solution();
        int numberToCheck = 101; // Replace with the number you want to check
        boolean isPalindromic = solution.isPalindrome(numberToCheck);
        System.out.println("Is Palindromic: " + isPalindromic);
    }
}
class Solution {
    public boolean isPalindrome(int x) {
        if(x>=0&&x<=9){
            return true;
        }
        if(x<0){
            return false;
        }
      int num=(int)Math.log10(x)+1;
         int arr[]=new int[num];
        int i=0;
    while(x!=0){
         arr[i]=x%10;
        i++;
        x/=10;
    }
    int start=0,end=num-1;
    while(start<end){
        if(arr[start]!=arr[end]){
            return false;
        }
        start++;
        end--;
    }
    return true;
    }
}

Language used for code : JAVA

![Screenshot (37)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128679143/bbafb5ce-b2e2-44bc-86cf-765d046d84f0)

**Comment by LC-Pam** [comment] 2023-09-25 20:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
101 already exists. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-27 18:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-27 18:51 UTC
Labels: Waiting for Reply
