### ISSUE TITLE
Missing Test Case - 460. LFU Cache

### ISSUE THREAD

**Issue by abhijith96** [LeetCode-Feedback/LeetCode-Feedback#20907] opened 2024-03-02 21:19 UTC
### Problem number, title, and link
460. LFU Cache https://leetcode.com/problems/lfu-cache/

### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Because of a missing test case incorrect code is passing all test cases.

Add this test case

Test Case which is not checked 

Input: 

["LFUCache","put", "get","get","get","get", "put", "get","put", "get", "get","put","get","get","get","get","get","put", "get", "get", "get"]

[[3],[1,1],[1],[1],[1],[1], [2,2], [2], [3,3], [3], [3], [4,4], [4],[4],[4],[4],[4],[5,5], [1], [2], [3] ]

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class LFUCache {
    std::list<std::tuple<int, int, int>> keyValueList;
    std::unordered_map<int, std::pair<std::list<std::tuple<int, int, int>>::iterator,  std::list<std::tuple<int, int, int>>::iterator>> CountToRangeMap;
    std::unordered_map<int, std::list<std::tuple<int, int, int>>::iterator> keyToListRefMap;
    //std::unordered_map<int, int> keyToCountMap;
    int capacity_;
    int size_;

    void IncrementCount(int key, int value){ 
            int prevCount = std::get<2>(*keyToListRefMap[key]);
            int currentCount = prevCount + 1;
            auto valueListIter = keyToListRefMap[key];
            auto prevCountRangeBegin = CountToRangeMap[prevCount].first;
            auto prevCountRangeEnd = CountToRangeMap[prevCount].second;
            //assert(prevCount > 0)
            if(prevCountRangeBegin == prevCountRangeEnd && prevCountRangeBegin == valueListIter){
                CountToRangeMap.erase(prevCount);
                keyValueList.erase(valueListIter);
                keyToListRefMap.erase(key);
            }
            else if(prevCountRangeBegin == valueListIter){
                auto nextIter = std::next((valueListIter));
                CountToRangeMap.at(prevCount) =  {nextIter, prevCountRangeEnd};
                keyValueList.erase(valueListIter);
                keyToListRefMap.erase(key);
            }
            else if(prevCountRangeEnd == valueListIter){
                auto prevIter = std::prev((valueListIter));
                CountToRangeMap.at(prevCount) = {prevCountRangeBegin,  prevIter};
                keyValueList.erase(valueListIter);
                keyToListRefMap.erase(key);
            }
            else{
                keyValueList.erase(valueListIter);
                keyToListRefMap.erase(key);
            }
            if(CountToRangeMap.count(currentCount) == 0){
                if(keyValueList.empty() || currentCount >  std::get<2>(keyValueList.front())){
                    keyValueList.push_back({key, value, currentCount});
                    auto valueListIter = std::prev(keyValueList.end());
                    keyToListRefMap[key] = valueListIter;
                    CountToRangeMap.insert({currentCount, {valueListIter, valueListIter}});
                }
                else {
                    keyValueList.push_front({key, value, currentCount});
                    auto valueListIter = keyValueList.begin();
                    keyToListRefMap[key] = valueListIter;
                    CountToRangeMap.insert({currentCount, {valueListIter, valueListIter}});
                }
            }
            else{
                 auto currentCountRangeBegin = CountToRangeMap[currentCount].first;
                auto currentCountRangeEnd = CountToRangeMap[currentCount].second;
                auto valueListIter = keyValueList.insert(++currentCountRangeEnd, {key, value, currentCount});
                CountToRangeMap[currentCount] = {currentCountRangeBegin, valueListIter};
                keyToListRefMap[key] = valueListIter;
            }
    }

    void DeleteLFLRKey(){
        auto [key, value, count] = keyValueList.front();
        auto CountRangeBegin = CountToRangeMap[count].first;
        auto CountRangeEnd = CountToRangeMap[count].second;
        if(CountRangeBegin == CountRangeEnd){
            CountToRangeMap.erase(count);
        }
        else{
            CountToRangeMap[count].first = std::next(CountRangeBegin);
        }
        keyToListRefMap.erase(key);
        keyValueList.pop_front();
    }
public:
    LFUCache(int capacity) {
        size_ = 0;
        capacity_ = capacity;
    }
    
    int get(int key) {
        if(keyToListRefMap.count(key) == 0){
            return -1;
        }
        int value = std::get<1>(*keyToListRefMap[key]);
        IncrementCount(key, value);
        return value;
    }
    
    void put(int key, int value) {
        if(keyToListRefMap.count(key) == 0){
            if(size_ == capacity_){
                DeleteLFLRKey();
            }
            else{
                ++size_;
            }
            if(CountToRangeMap.count(1) == 0){
                keyValueList.push_front({key, value, 1});
                auto valueListIter = keyValueList.begin();
                keyToListRefMap[key] = valueListIter;
                CountToRangeMap[1] = {valueListIter, valueListIter};
            }
            else{
                auto countEndIter = CountToRangeMap[1].second;
                auto valueListIter = keyValueList.insert(++countEndIter,{key, value, 1});
                CountToRangeMap[1].second = valueListIter;
                keyToListRefMap[key] = valueListIter;
            }
        }
        else{
            IncrementCount(key, value);
        }

    }
};

### Expected behavior
This code should fail because key with value 1 is removed instead of key with value 3 when key with value 5 is inserted. But in the current test case collection this is not checked and the above code passed 25/25 of current test case set.

To catch this my new test case can be added. On my new test case above code fails.

**Comment by LC-Pam** [comment] 2024-03-05 20:10
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-03-11 17:23 UTC
Labels: Waiting for Reply
