### ISSUE TITLE
Missing Test Case - 2027. Minimum Moves to Convert String

### ISSUE THREAD

**Issue by Neel-Biswas** [LeetCode-Feedback/LeetCode-Feedback#16976] opened 2023-10-06 12:30 UTC
#### Your LeetCode username
 neelcodju
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 
Test case answer wrong

#### Description of the bug

So the problem states that whenever we are using a string , we change the 3 values in one move so if X is present at any position between o and 3 we need one move to convert the first 3 strings. Now in example "OXOXOO" at first we will convert the first 3 strings in one move so as 1 x is present between them so in one move ,the  string is OOOXOO , now in second move we will start from i=3 position to i=5 position and will change that part X in one move so there will be all total two moves but here the answer given is 1 move.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
``` int moves=0,i=0;
        while(i<s.size())
        {
            if(s[i]=='X')
            {
                moves++;
                i+=3;
            }
            else
            {
                i++;
            }
        }
        return moves;
```

    }
};
```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
So the problem states that whenever we are using a string , we change the 3 values in one move so if X is present at any position between o and 3 we need one move to convert the first 3 strings. Now in example "OXOXOO" at first we will convert the first 3 strings in one move so as 1 x is present between them so in one move ,the  string is OOOXOO , now in second move we will start from i=3 position to i=5 position and will change that part X in one move so there will be all total two moves but here the answer given is 1 move.


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->

![Screenshot 2023-10-06 175648](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97150573/9cc84440-b9ce-4deb-9349-4219b96881d7)


#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-10-09 18:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:48 UTC
Labels: Waiting for Reply
