### ISSUE TITLE
Missing Test Case - 22. Generate Parentheses

### ISSUE THREAD

**Issue by arush913** [LeetCode-Feedback/LeetCode-Feedback#7818] opened 2022-06-18 11:36 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Generate  Parenthesis
class Solution {
public:
    // Basic idea :: to generate a function with string, left bracket and right bracket and adding one by one and checking too.
    void generate(string &s,int lb,int rb){
    if(lb==0 && rb==0){
        ans.push_back(s);
        return;
    }
    
    if(lb>0){
        s+='(';
        generate(s,lb-1,rb);
        s.pop_back();     //since adding in same string so just popback after passing to function 
    }
    
    if(rb>0){
        if(rb>lb){
            s+=')';
            generate(s,lb,rb-1);
            s.pop_back();
        }
    }
}
    vector<string>ans;
    vector<string> generateParenthesis(int n) {
        int lb=n,rb=n;
        string s="";
        generate(s,lb,rb);
        
        return ans;

    }
};


```

**Comment by LC-Pam** [comment] 2022-06-19 19:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the test case that you use?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-24 04:16
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-24 04:16 UTC
Labels: LCUS, problem
