### ISSUE TITLE
Documentation/ Description time complexity error of Arrays and Strings 

### ISSUE THREAD

**Issue by urena-code** [LeetCode-Feedback/LeetCode-Feedback#14713] opened 2023-07-12 11:42 UTC
#### Your LeetCode username

urena-code

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The explanation for this code says it runs in O(n) time complexity. Since there are two inputs - n and m arrays, the algorithm goes through each one of them exhaustively resulting in a **O(n+m)** time complexity and NOT O(n). 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }


};
```

#### Screenshots

<img width="609" alt="Screen Shot 2023-07-12 at 7 40 32 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59552176/99b333e9-7004-44da-8fc5-8606e9872dad">

**Comment by LC-Pam** [comment] 2023-07-12 19:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-17 20:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-17 20:32 UTC
Labels: LCUS, problem
