### ISSUE TITLE
Test case discrepancy for problem number 162. Find Peak Element.

### ISSUE THREAD

**Issue by octanium** [LeetCode-Feedback/LeetCode-Feedback#16484] opened 2023-09-17 10:37 UTC
LeetCode username: kamran1892
Category of the bug: Test case
Problem: https://leetcode.com/problems/find-peak-element/description/

Description
There is a test case for the above problem which is as follows
Input Array: [-1, -1, -1, -1, 2, 2, -2, -2]
k: 3

I believe expected output should be **true** for the above test case.
(Explanation: Pairs: (-1, 2), (-1, 2), (-1, 2), (-1, 2), (-2, -2), all sums are divisible by 3.)

The issue is that the expected output should be **true** based on the problem statement, but the actual output is **false**. The problem statement does not mention any specific constraints that would lead to this result.

Kindly let me know if I am missing something.

**Comment by Akash-9794** [comment] 2023-09-17 11:45
Based on the problem statement and the provided test case, you are correct that the expected output should be true. The problem seems to be with the implementation or evaluation of the code rather than the problem statement itself.

The problem statement you described is about finding pairs whose sum is divisible by k. In the test case you provided:

    Input Array: [-1, -1, -1, -1, 2, 2, -2, -2]
    k: 3

You correctly identified that pairs like (-1, 2) and (-2, -2) have sums that are divisible by 3, so the expected output should indeed be true.

If the actual output is false for this test case, it suggests there might be a bug in the code or an issue with the way the code is handling the calculation of sums and divisibility by k. You should review the code logic and ensure that it correctly identifies pairs with sums divisible by k. It might be helpful to run the code with this specific test case and inspect the intermediate results to debug the issue.

**Comment by Akash-9794** [comment] 2023-09-17 11:47
there is a one apporoch to solve this problem 
class Solution {
public:
    int findMin(vector<int>& nums) {
        // Get the size of the input vector 'nums'
        int n = nums.size();

        // Initialize the lower bound of the search range to 0
        int low = 0;

        // Initialize the upper bound of the search range to the last index of 'nums'
        int high = n - 1;

        // Perform binary search until the lower bound is less than the upper bound
        while (low < high) {
            // Calculate the middle index of the current search range
            int mid = (low + high) >> 1;

            // Check if the element at the middle index is greater than the element to its right
            if (nums[mid] > nums[mid + 1]) {
                // If true, update the upper bound to the middle index,
                // narrowing the search to the left half of the current range
                high = mid;
            } else {
                // If false, update the lower bound to mid + 1,
                // narrowing the search to the right half of the current range
                low = mid + 1;
            }
        }

        // When the loop ends, 'low' will contain the index of the minimum element in 'nums'
        return nums[low];
    }
};

**Comment by octanium** [comment] 2023-09-18 05:43
Thanks for the quick reply,
The solution given above of findMin, is it related to the current issue?
According to  you **there might be an issue with the way the code is handling the calculation of sums and divisibility by k**.
I wanted to know is it
1. Code developed by leetcode team
2. The code developed by me on leetcode for this particular problem.

**Comment by LC-Pam** [comment] 2023-09-18 20:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result. (submission link)


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by octanium** [comment] 2023-09-19 05:44
Hi @LC-Pam 
The language used is Javascript
Below is my code:
`/**
 * @param {number[]} arr
 * @param {number} k
 * @return {boolean}
 */
var canArrange = function(arr, k) {
    const arr2 = new Array(arr.length).fill(null);
    let map = {};
    for (let i=0; i<arr.length; i++) {
        let mod = arr[i]%k;
        arr2[i] = mod;
            if (mod in map) {
                map[mod] += 1;
            }
            else map[mod] = 1;
    
    }
    let exists = 1;
    for (let n of arr2)  {
        if (n === 0 && map[n] >= 2) continue; 
        else if (-n in map) {
            continue;
        } else if (n > 0 && (k-n) in map) {
            continue;
        } else if (n < 0 && (-(k-(-n)) in map)) {
            continue;
        } else {
            exists = 0;
            break;
        }        
    }

    return exists === 1 ? true : false;
};`

Below is explanation of **if-else-if** conditions I have used 
1. condition-1: (n === 0 && map[n] >= 2)  , if the mod is 0 that means it is completely divisble by k, hence there should be another number which should be completely divisible by k in order to make a pair, eg: k=5 [,,,5,10,,] 
2. condition-2: (n > 0 && (k-n) in map), that is n+(k-n) is divisible by k, we used logic of 2 sum easy problem
3. condition-3:(-n in map), if say 9 is there and -9 is also in the array then 9 acan be paired with -9 and the sum will be 0, since 0 is divisble by k, the pair can be formed.
4. condition-4: (n < 0 && (-(k-(-n)) in map)), say if k=3, and arr = [-1,-2]. -1+-2 is divisible by 3
-1 < 0 and -(3-(1)) => -2 which is in array

For the following testcase:
Input Array: [-1, -1, -1, -1, 2, 2, -2, -2]
k: 3
I believe expected output should be **true** 
(Explanation: Pairs: (-1, 2), (-1, 2), (-1, 2), (-1, 2), (-2, -2), all sums are divisible by 3.)
But leetcode is expecting **false** value as output

**Comment by LC-Pam** [comment] 2023-09-20 16:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link since we received a runtime error for the above code. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by octanium** [comment] 2023-09-25 09:14
Sure,
here is the submission link
https://leetcode.com/problems/check-if-array-pairs-are-divisible-by-k/submissions/1051699093/?source=submission-noac

**Comment by LC-Pam** [comment] 2023-09-25 20:47
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-09-25 20:47 UTC
Labels: Waiting for Reply
