### ISSUE TITLE
Restaurant Growth - SQL - ambiguous question

### ISSUE THREAD

**Issue by dkhiani6** [LeetCode-Feedback/LeetCode-Feedback#15688] opened 2023-08-18 02:12 UTC
The question says "there will be at least one customer every day" but my solution is failing a test case that has 2 days without customers. So it is ambiguous

**Comment by LC-Pam** [comment] 2023-08-18 20:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The solution is failing a test case that has 2 days without customers.
The test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dkhiani6** [comment] 2023-08-18 21:05
**Solution** 
select b.visited_on as visited_on, sum(a.amount) as amount, round(sum(a.amount)/7,2) as average_amount
from 
Customer a cross join (Select distinct visited_on from customer) b
on datediff(b.visited_on, a.visited_on) between 0 and 6
group by b.visited_on
having count(distinct a.visited_on) = 7

**Failed testcase**
| customer_id | name    | visited_on | amount |
| ----------- | ------- | ---------- | ------ |
| 1           | Jhon    | 2019-01-01 | 100    |
| 4           | Khaled  | 2019-01-04 | 130    |
| 5           | Winston | 2019-01-05 | 110    |
| 6           | Elvis   | 2019-01-06 | 140    |
| 7           | Anna    | 2019-01-07 | 150    |
| 8           | Maria   | 2019-01-08 | 80     |
| 9           | Jaze    | 2019-01-09 | 110    |
| 1           | Jhon    | 2019-01-10 | 130    |
| 3           | Jade    | 2019-01-10 | 150    |

According to this testcase input, there were no customers on 2nd and 3rd january but the questions mentions "You are the restaurant owner and you want to analyze a possible expansion **(there will be at least one customer every day)**."

**Comment by LC-Pam** [comment] 2023-08-21 15:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:25 UTC
Labels: Waiting for Reply
