### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by lyp82nlf** [LeetCode-Feedback/LeetCode-Feedback#16002] opened 2023-08-29 03:24 UTC
#### Your LeetCode username

My LeetCode userName ： DSG

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

Question number is [823. 带因子的二叉树](https://leetcode.cn/problems/binary-trees-with-factors/)

#### Description of the bug

The test case is missing, the test result of [2，3，6，72] is wrong, and the result similar to [6，6，2] is missing

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-08-29 19:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:54 UTC
Labels: Waiting for Reply
