### ISSUE TITLE
string join() bug

### ISSUE THREAD

**Issue by BotPhil01** [LeetCode-Feedback/LeetCode-Feedback#16120] opened 2023-09-02 17:30 UTC
#### Your LeetCode username:
BotPhil_01

#### Category of the bug
- [x ] Solution
- [x ] Language

#### Description of the bug
Join command doesn't appear to join a list of characters into a string when prompted

#### Code you used for Submit/Run operation

```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        string1 = strs[0]
        string1 = sorted(string1)
        string1 = ''.join(string1)
        return(string1)
```
and 

```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        sortedstrs = []
        for string in strs:
            sortedstrs.append(''.join(sorted(string)))
        return(sortedstrs)
```

#### Language used for code
Python

#### Expected behavior
Code is expected to sort characters of each string alphabetically then concatenate the characters into 1 string and append each string into 1 list

For each word:
Sorted returns a list of characters
Join turns characters into string
Word added to a list
List is returned

Testcase 1:
Input: strs =
["eat","tea","tan","ate","nat","bat"]

Expected output:
['aet', 'aet', 'ant', 'aet', 'ant', 'abt']

Output:
[["a","e","t"],["a","e","t"],["a","n","t"],["a","e","t"],["a","n","t"],["a","b","t"]]

#### Additional context
Ran the code in python shell and received the expected output seems to be a problem with the leetcode editor.

**Comment by LC-Pam** [comment] 2023-09-05 20:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-07 18:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-07 18:09 UTC
Labels: Waiting for Reply
