### ISSUE TITLE
Missing Test Case - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by rges** [LeetCode-Feedback/LeetCode-Feedback#7617] opened 2022-06-05 18:40 UTC
#### Your LeetCode username
 rahulgurial2003

#### Category of the bug
 
- [ ] Missing Test Cases 

#### Description of the bug

This problem is missing some test cases. My code was accetped for the leetcode's testcases .  But when i run it on a custom testcase then it gave the wrong answer.

#### Code you used for Submit/Run operation

```
// Two Sum
 class Solution {
    
    public boolean search(int nums[],int target)
  {
      int pivot = findPivotIndex(nums);
      

      
      int low = 0;
      int end = nums.length - 1;
      
      if(nums[pivot] == target)
      {
return true;
      }
      else if(target > nums[pivot] && target <= nums[end])
      {
          return binarySearch(nums,pivot,end,target);
      }
      else 
      {
          return binarySearch(nums,low ,pivot - 1,target);
      }
       
  }
  public  boolean binarySearch(int nums[],int low,int end,int target)
  {
      if(low > end)
      {
          return false;
      }

      int mid = low + (end  - low)/2;
      if(nums[mid] == target)
      {
          return true;
      }
      else if(nums[mid] > target)
      {
          return binarySearch(nums, low, mid -1, target);
      }
      else 
      {
          return binarySearch(nums, mid+1, end, target);
      }
  }
  public int findPivotIndex(int arr[])
  {
      if(arr[0] < arr[arr.length -1] || arr.length == 1 )
      {
          return 0;
      }
      if(arr.length == 2) 
          {
          
          if(arr[0] > arr[1]) 
              return 1;
          return 0;
          }
 
      int low = 0;
      int end = arr.length - 1;
      while(low <= end)
      {
          int mid = low + (end - low)/2;
        
          if(arr[mid+1] < arr[mid])
          {
              return mid+1;
          }
          if(arr[mid] < arr[mid-1])
          {
              return mid;
          }
          if(arr[low] == arr[mid] )
          {
            low++;
            
            
          }
          if(arr[end] == arr[mid])
          {
              end--;
          }
          
          else if(arr[mid] > arr[0])
          {
              low = mid + 1;
          }
          else if(arr[mid] < arr[arr.length - 1])
          {
              end  = mid - 1;
          }
      


      }
      return 0;
  }

}

```

#### Language used for code

JAVA

#### Expected behavior
Above code should return true as output. But it gave false as output.

**Comment by LC-Pam** [comment] 2022-06-06 02:22
Duplicate of #7618

**Closed by LC-Pam** 2022-06-06 02:22 UTC
