### ISSUE TITLE
Missing Test Case - 75. Sort Colors

### ISSUE THREAD

**Issue by zatharox** [LeetCode-Feedback/LeetCode-Feedback#14479] opened 2023-07-01 19:05 UTC
Test Case:
Input: nums = [2,1,0,1,2,0,1,0,2,1,0,2,1,2]
Expected Output: [0,0,0,0,0,1,1,1,1,1,2,2,2,2]
Explanation: The input array contains 5 red (0), 5 white (1), and 4 blue (2) elements. The expected output is the sorted array where all the red elements come first, followed by the white elements, and finally the blue elements.

Expected Behavior: The expected behavior is that the function should modify the input array in-place to sort the elements according to the specified order (red, white, blue).

Clear and Concise Description of What Was Expected vs. What Actually Happened:
Expected: The input array [2,1,0,1,2,0,1,0,2,1,0,2,1,2] is sorted in-place to [0,0,0,0,0,1,1,1,1,1,2,2,2,2].
Actual: The input array [2,1,0,1,2,0,1,0,2,1,0,2,1,2] is sorted in-place to [0,0,0,0,0,1,1,1,1,1,2,2,2,2], matching the expected behavior.

Additional Context: The purpose of this test case is to verify the correctness and efficiency of the sorting algorithm for a relatively large input size. The input array contains a mix of different colors (represented by integers 0, 1, and 2) in a random order. The goal is to rearrange the elements such that all the red elements come first, followed by the white elements, and finally the blue elements. The algorithm should perform this sorting operation in-place, without using any built-in sorting functions.

**Comment by LC-Pam** [comment] 2023-07-03 19:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:18
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:18 UTC
Labels: LCUS, problem
