### ISSUE TITLE
Maybe an error in problem 880 test case 35

### ISSUE THREAD

**Issue by Sirorezka** [LeetCode-Feedback/LeetCode-Feedback#17331] opened 2023-10-19 14:55 UTC
#### Your LeetCode username
sirorezka

#### Category of the bug
- Probable error in Test Cases 

#### Description of the bug
Problem is [880. Decoded String at Index](https://leetcode.com/problems/decoded-string-at-index/)

#### Code you used for Submit/Run operation
Test is the following:
s = "vzpp636m8y"
k = 2920
expected: "z"

However this Python3 code will return "p"
```python
(("vzpp"*636 + "m") * 8)[2920-1]
out: "p"
```

#### Expected behavior
Answer should be "p"

**Comment by LC-Pam** [comment] 2023-10-19 17:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-23 19:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-23 19:07 UTC
Labels: Waiting for Reply

**Comment by Sirorezka** [comment] 2023-11-05 20:00
Hi, the issue was clarified by a user on the Leetcode forum. This is not a bug, the formula works differently:
(("vzpp"*6*3*6 + "m") * 8)[2920-1]

Thus issue is closed.
