### ISSUE TITLE
Missing Test Case - 2697. Lexicographically Smallest Palindrome

### ISSUE THREAD

**Issue by SamrawitDawit** [LeetCode-Feedback/LeetCode-Feedback#17602] opened 2023-10-29 01:00 UTC
#### Your LeetCode username 
SamrawitDawit

#### Category of the bug
- [ ] Question abbd
- [ ] Solution abba 
- [ ] Language python
- [ ] Missing Test Cases 

#### Description of the bug
my code should not have worked correctly for testcase with different last and first element since it tries to access element with index that is out of bound. but leetcode has accepted it.

#### Code you used for Submit/Run operation

```
class Solution:
    def makeSmallestPalindrome(self, s: str) -> str:
        l, r = 0, len(s)-1
        while l < r:
            if s[l] > s[r]:
                s = s[:l] + s[r] + s[l+1:]
            elif s[l] < s[r]:
                s = s[:r] + s[l] + s[r+1:]
            l += 1
            r -= 1
        return s
```

#### Language used for code

python

#### Expected behavior

Index out of bound error should have been raised.

**Comment by LC-Pam** [comment] 2023-10-30 20:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 17:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:59 UTC
Labels: Waiting for Reply
