### ISSUE TITLE
Wrong Test Case - 146. LRU Cache

### ISSUE THREAD

**Issue by f16hari** [LeetCode-Feedback/LeetCode-Feedback#12782] opened 2023-04-05 14:52 UTC
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Wrong Test Case

#### Ideally for the last get operation the output should be -1 since the capacity is only 1, key present in LRU would be 4, so 5 will be unavailable
Test Case : 
["LRUCache","get","get","put","get","put","put","put","put","get","put"]
[[1],[6],[8],[12,1],[2],[15,11],[5,2],[1,15],[4,2],[5],[15,15]]

#### Code used for submission

```
class LRUCache {

    static class CacheItem{
        int key;
        int value;
        CacheItem prev;
        CacheItem next;

        CacheItem(int key, int value){
            this.key = key;
            this.value = value;
        }
    }

    CacheItem head;
    CacheItem tail;
    int capacity;
    HashMap<Integer, CacheItem> items;
    
    public LRUCache(int capacity) {
        this.capacity = capacity;
        items = new HashMap<>();
    }

    void moveItemToTail(CacheItem item){
        if(tail == item) return;

        if(head == item){
            head = item.next;
        }
        else{
            item.prev.next = item.next;
            item.next.prev = item.prev;
        }

        tail.next = item;
        item.prev = tail;
        tail = item;
    }

    int removeFromHead(){
        if(head == null) return -1;

        int keyRemoved = head.key;
        head = head.next;
        //printKeys();
        return keyRemoved;
    }

    void insertInTail(CacheItem item){
        if(tail == null){
            head = tail = item;
            return;
        }

        tail.next = item;
        item.prev = tail;
        tail = item;
    }

    void printKeys()
    {
        for(Map.Entry<Integer, CacheItem> entry: items.entrySet()){
            System.out.println(entry.getKey());
        }
        System.out.println("end");
    }
    
    public int get(int key) {
        CacheItem item = items.get(key);
        if(item != null){
            moveItemToTail(item);
            return item.value;
        }

        return -1;
    }
    
    public void put(int key, int value) {
        CacheItem item = items.get(key);
        if(item != null){
            item.value = value;
            moveItemToTail(item);
            return;
        }

        CacheItem newItem = new CacheItem(key, value);
        if(capacity == items.size()){
            int keyRemoved = removeFromHead();
            items.remove(keyRemoved);
        }
        insertInTail(newItem);
        items.put(key, newItem);
    }
}
```

**Comment by f16hari** [comment] 2023-04-05 14:52
Invalid Test Case report for LRU problem

**Comment by LC-Pam** [comment] 2023-04-05 18:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2023-04-06 00:08
The expected output of this test case is already [null,-1,-1,null,-1,null,null,null,null,-1,null], and your code can't be accepted since the last get operation returns the incorrect value (2 instead of -1).

So what's the reason that the test case is invalid? It is your code that returns the incorrect output and can't be accepted.

**Comment by LC-Pam** [comment] 2023-04-07 18:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-07 18:05 UTC
Labels: LCUS, problem
