### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by stemcontent** [LeetCode-Feedback/LeetCode-Feedback#13843] opened 2023-06-02 18:31 UTC
#### Your LeetCode username
stemcontent

#### Category of the bug
- [ 217. Contains Duplicate] Question
- [ x] Solution
- [Java ] Language
 

CODE:

class Solution {
    public boolean containsDuplicate(int[] nums) {
        //by using a HashSet
         HashSet<Integer> uniques =new HashSet(); 

         for (int i=0;i<nums.length;i++){
             if (uniques.contains(nums[i])){
                 return true;
             }
             uniques.add(nums[i]);
         } 
         return false;
    }
}

#### Language used for code
Java

**Comment by LC-Pam** [comment] 2023-06-02 20:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:42
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:42 UTC
Labels: LCUS, problem
