### ISSUE TITLE
Unclear Test Case - 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by islijepcevic** [LeetCode-Feedback/LeetCode-Feedback#7831] opened 2022-06-19 12:16 UTC
#### Your LeetCode username

islijepcevic

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the following inputs:
```
["WordFilter","f"]
[[["abcaccbcaa","accabaccaa"]],["a","aa"]]
```

What is the correct answer? My code returns `[null,0]`, but the judge returns `[null,1]`. I do not understand why is that correct?

#### Code you used for Submit/Run operation

```
from collections import deque

class WordFilter:

    def __init__(self, words: List[str]):
        self.words = {i: len(word) for i, word in enumerate(words)}
        #print("buliding prefix")
        self.prefix_tree = Trie(words)
        #print("buliding suffix")
        self.suffix_tree = Trie([w[::-1] for w in words])
        

    def f(self, prefix: str, suffix: str) -> int:
        print(f"finding for {prefix}..{suffix}")
        p_words = self.prefix_tree.find(prefix)
        print(f"found prefix words {p_words}")
        s_words = self.suffix_tree.find(suffix[::-1])
        print(f"found suffix words {s_words}")
        intersection = set(p_words) & set(s_words)
        if not intersection:
            return None
        print(f"intersection {intersection}")
        wordlen = lambda word: self.words[word]
        return max(intersection, key=wordlen)
        
        
class TrieNode:
    def __init__(self, char):
        self.char = char
        self.term = []
        # char -> TrieNode
        self.next = {}
        
class Trie:
    def __init__(self, words):
        self.root = TrieNode(None)
        for i, w in enumerate(words):
            self.addWord(w, i)
            
    def addWord(self, word, word_index):
        #print(f"adding word {word} at index {word_index}")
        node = self.root
        for char in word:
            if char in node.next:
                nextnode = node.next[char]
            else:
                nextnode = TrieNode(char)
                node.next[char] = nextnode
            node = nextnode
        node.term.append(word_index)
    
    def find(self, prefix):
        # parse prefix
        node = self.root
        for char in prefix:
            if char not in node.next:
                return []
            node = node.next[char]
            
        # then bfs
        ret = []
        q = deque()
        q.append(node)
        while q:
            node = q.popleft()
            ret += node.term
            q += node.next.values()
        
        # return all found
        return ret
        
```

#### Additional context

Output
[null,0]
Expected
[null,1]

**Comment by panikgit** [comment] 2022-06-19 17:29
> If there is more than one valid index, return the largest of them. 

The expected one is correct.

**Comment by LC-Pam** [comment] 2022-06-19 20:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-24 04:21
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-24 04:21 UTC
Labels: LCUS, problem
