### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by ZeehanSharif** [LeetCode-Feedback/LeetCode-Feedback#8053] opened 2022-07-06 16:31 UTC
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

`var isIsomorphic = function(s, t) {
    if(s.length !== t.length) return false;
    
    for(let i = 0; i < s.length; i++) {
        const a = s.indexOf(s[i]);
        const b = t.indexOf(t[i]);
        
        if (t[a] !== t[i] || s[b] !== s[i]) {
         return false;
      };
    };
    return true;
};``
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- JavaScript -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2022-07-06 23:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-11 19:47
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-11 19:47 UTC
Labels: LCUS, problem
