### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by shadan1234** [LeetCode-Feedback/LeetCode-Feedback#20117] opened 2024-02-07 08:03 UTC
LeetCode username- shadan12

1657. Determine if Two Strings Are Close (https://leetcode.com/problems/determine-if-two-strings-are-close/)

Category of the bug

### Category of the bug
- [ ] Missing test Case (Incorrect/Inefficient Code getting accepted because of missing test cases)

Description of the bug
For the test case word1= "ttttt", word2="tttt" , wrong solution is getting accepted.

Language used for code
C++

```

class Solution {
public:
    bool closeStrings(string word1, string word2) {
        int n=word1.size();
        int m=word2.size();
        if(word1=="ce" && word2=="c")
        return false;
        if(word1=="aaaa"&& word2=="a")
        return false;
  
        map<char,int>mp1;
        map<char,int>mp2;
       
        for(int i=0;i<m;i++){
            mp2[word2[i]]++;
              mp1[word1[i]]++;
        }
        multiset<int>setForcharA,setForFreqA,setForFreqB,setForcharB;

        for(auto it:mp1){
            setForcharA.insert(it.first);
            setForFreqA.insert(it.second);
        }
        for(auto it:mp2){
            setForcharB.insert(it.first);
            setForFreqB.insert(it.second);
        }
        if(setForcharA==setForcharB && setForFreqA==setForFreqB)
        return true;
        else
        return false;

    }
};

```

 Expected behavior
Expected behavior should have been WA , but because of missing test case incorrect solution is getting accepted.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122110545/06a1e1e3-ea15-4233-8c53-617b84ac1727)

### Additional context
Test case 1) word1= "ttttt" , word2="tttt"
Expected ->false : Output -> true
wrong solution is also getting accepted.

**Comment by naXa777** [comment] 2024-02-07 09:56
@shadan1234 please stop. why are you flooding the repository with verysimilar almost duplicate issues?

I think that #20117 is a duplicate of #20116. The code is the same, the test cases have a minor difference. If #20116 is fixed, #20117 will not be reproducible. SO WHAT'S THE POINT?

**Comment by shadan1234** [comment] 2024-02-07 11:49
@naXa777  extremely sorry for doing that , I had no idea how to raise a good issue. Thanks for responding. I would love to help in anyway possible....

**Comment by naXa777** [comment] 2024-02-08 13:50
Ask @LC-Pam for the guidance. 

From what I can see: Your current format for the submissions is very good. The tickets contain links, description, test cases, and even screenshots. Keep up the good work! The problem that I highlighted is related to you opening a lot of copy-pasted issues. Did you want to hack the system and get +100 Leetcoins for each one of them? :D Maybe it's the reason why they all were ignored by @LC-Pam.

Please try opening JUST ONE single issue today or tomorrow. Describe one single bug in details. And wait for the response from LeetCode team. Let's see how it goes.

@shadan1234, Good Luck!

**Closed** 2024-02-12 16:01 UTC
Labels: LCUS
