### ISSUE TITLE
Missing official solution for "675. Cut Off Trees for Golf Event"

### ISSUE THREAD

**Issue by symion** [LeetCode-Feedback/LeetCode-Feedback#9816] opened 2022-11-09 17:24 UTC
#### Your LeetCode username
infraredshift

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hi there, the official solution for 675. Cut Off Trees for Golf Event seems to be missing: https://leetcode.com/problems/cut-off-trees-for-golf-event/

Solution link: https://leetcode.com/problems/cut-off-trees-for-golf-event/solutions/127477/official-solution/

It shows an error message: "That topic does not exist."

#### Screenshots
![image](https://user-images.githubusercontent.com/13445054/200898511-26d739b7-940f-4176-bc58-ed5aa2752342.png)

**Comment by nskybytskyi** [comment] 2022-11-09 19:39
It appears to be yet another issue caused by the redesign. I am able to access the official solution in the old version. To revert to the old design, click your profile picture in the top right corner, then click "revert to old version". Don't worry, you'll be able to go back to the new design at any point. Hopefully, it will be fixed soon.

**Comment by symion** [comment] 2022-11-09 20:15
Thank you! that worked.

**Closed** 2022-11-10 18:36 UTC
