### ISSUE TITLE
Wrong test case: 102 Binary Tree Level Order

### ISSUE THREAD

**Issue by jbevarts** [LeetCode-Feedback/LeetCode-Feedback#15998] opened 2023-08-28 17:29 UTC
#### Your LeetCode username
Jbevarts

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug 
Test case 12 has an incorrect input format.

It states the expected input/output is
```
Input = [1,2,null,3,null,4,null,5] 
ExpectedOutput =  [[1],[2],[3],[4],[5]]
```
However based on array representation of a binary tree where left and right child positions are 2n+1 and 2n+2 respectively for all n > 0, this representation is incorrect.  

First of all, the input is a non-proper tree in that it has a null parent.  
The tree looks like the below representation

——-1
——2,null
—3,null,4,null
-5,null,null,null,null,null,null,null

For some reason, your tree parser is considering [1,2,null,3,null,4,null,5] as:
——1
—-2…
—3…
-4…
5….

^ the above actually has 22 nulls!

If the input was considered proper, the actual output would  in fact be: 
```
[[1],[2],[3,4],[5]]
```

however the formatting of input is wrong.

#### Code you used for Submit/Run operation
Not dependent on solution

#### Language used for code
Irrelevant

#### Expected behavior
Described in question

**Comment by LC-Pam** [comment] 2023-08-29 19:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:54 UTC
Labels: Waiting for Reply
