### ISSUE TITLE
Missing Test Case - 1984. Minimum Difference Between Highest and Lowest of K Scores

### ISSUE THREAD

**Issue by nikita019** [LeetCode-Feedback/LeetCode-Feedback#7662] opened 2022-06-08 18:36 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int minimumDifference(vector<int>& nums, int k) {
        sort(nums.begin(),nums.end());
        int i=0,j=0,ans=INT_MAX;
        while(j<nums.size()){
            if(j-i+1<k){
                j++;
            }
            else if(j-i+1==k){
                ans = min(ans,(nums[j]-nums[i]));
                i++;
                j++;
            }
        }
        return ans;
    }
};
```

**Comment by LC-Pam** [comment] 2022-06-09 01:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-13 17:08
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-13 17:08 UTC
Labels: LCUS, problem
