### ISSUE TITLE
Problem Of The Day 22/05/03 - Shortest Unsorted Continuous Subarray - Problem Uses "Ascending" When It Should Say "Non-Decreasing"

### ISSUE THREAD

**Issue by dginovker** [LeetCode-Feedback/LeetCode-Feedback#7187] opened 2022-05-03 06:52 UTC
#### Your LeetCode username
dginovker

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [Shorted Unsorted Continuous Subarray](https://leetcode.com/problems/shortest-unsorted-continuous-subarray/), the problem talks about which contiguous subarray needs to be sorted such that "the whole array will be sorted in **ascending order**".

This doesn't make sense since the input can have duplicates - i.e `[1,1]` cannot be sorted in ascending order, so the output of `0` doesn't work. Likewise the output of `2` wouldn't work either, since no sort on `[1,1]` would make it ascending order.

For consistency, Leetcode uses the terms "non-decreasing" in [this](https://leetcode.com/problems/non-decreasing-array/) question, and the proper use of "ascending" in [this](https://leetcode.com/problems/maximum-ascending-subarray-sum/) question.

#### Expected behavior

The description of "Shorted Unsorted Continuous Subarray" should be edited to say the following:

*****

Given an integer array `nums`, you need to find one **continuous subarray** that if you only sort this subarray in non-decreasing order, then the whole array will be sorted in non-decreasing order.

Return the shortest such subarray and output its length.

We define an array is non-decreasing if `nums[i] <= nums[i + 1]` holds for every `i` (**0-based**) such that (`0 <= i <= n - 2`).

**Comment by LC-Yani** [comment] 2022-05-07 02:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Problem name.

Thank you.

**Comment by LC-Pam** [comment] 2022-05-11 17:15
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-11 17:15 UTC
Labels: LCUS, problem
