### ISSUE TITLE
 496. Next Greater Element I

### ISSUE THREAD

**Issue by vim12345** [LeetCode-Feedback/LeetCode-Feedback#11609] opened 2023-02-08 16:26 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
       unordered_map<int,int>umap;
        stack<int>st;
        int n=nums2.size();
        for(int i=n-1;i>=0;i--){
            int ele=nums2[i];
            while(!st.empty() && st.top()<=ele){
                st.pop();
            }
            int res =(st.empty())?-1 : st.top();
            umap.insert({ele,res});
            st.push(ele);
        }
        vector<int>ans;
        for(auto x:nums1){
            ans.push_back(umap[x]);
        }
        return ans;

    }
};
```

**Comment by LC-Pam** [comment] 2023-02-08 18:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-10 19:02
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-10 19:02 UTC
Labels: LCUS, problem
