### ISSUE TITLE
Missing Test Case - 496. Next Greater Element I

### ISSUE THREAD

**Issue by Ananya0909** [LeetCode-Feedback/LeetCode-Feedback#13388] opened 2023-05-10 09:40 UTC
nums1=
[4,5,2,25]

nums2=
[4,5,2,25]

Expected Output:
[5,25,25,-1]

**Comment by LC-Pam** [comment] 2023-05-10 22:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-12 21:35
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-12 21:35 UTC
Labels: LCUS, problem
