### ISSUE TITLE
599. Minimum Index Sum of Two Lists (re-submitted accepted answer is always shown wrong)

### ISSUE THREAD

**Issue by kshitijgarg2609** [LeetCode-Feedback/LeetCode-Feedback#11337] opened 2023-01-28 19:10 UTC
#### Category of the bug
- [ ] Unknown Error

#### Description of the bug

Question :- 599. Minimum Index Sum of Two Lists, I had solved this question last year and redoing it again and I have found that the submitted answer is wrong by which many submission gone wrong, Not able to get test case number at which it is stuck, not getting what kind of error it is.

#### Code you used for Submit/Run operation

```
class Solution
{
    public String[] findRestaurant(String[] list1, String[] list2)
    {
      HashMap<String,Integer> map = new HashMap<String,Integer>();
      List<String> li = new LinkedList<String>();
      int min=Integer.MAX_VALUE;
      int sum;
      for(int i=0;i<list1.length;i++)
      {
        map.put(list1[i],i);
      }
      for(int i=0;i<list2.length;i++)
      {
        if(map.containsKey(list2[i]))
        {
          sum=i+map.get(list2[i]);
          if(sum<min)
          {
            li.clear();
            li.add(list2[i]);
            min=sum;
          }
          else if(sum==min)
          {
            li.add(list2[i]);
          }
        }
      }
      return li.toArray(new String[li.size()]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Last accepted code should be accepted when copied as it is

#### Screenshots

![image](https://user-images.githubusercontent.com/48625716/215286433-a722fc2d-0afc-48d8-87ce-1cf691d29a79.png)
![image](https://user-images.githubusercontent.com/48625716/215286470-81f3de93-f747-4fcb-8c12-472038d35a6a.png)

#### Additional context

Please do check my profile for submissions.
https://leetcode.com/kshitijgarg2609/

**Comment by LC-Pam** [comment] 2023-01-30 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code WA link since we received AC after submission. https://leetcode.com/submissions/detail/888332565/


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-31 19:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-31 19:20 UTC
Labels: LCUS, problem
