### ISSUE TITLE
2288.Apply Discount to Prices

### ISSUE THREAD

**Issue by THP297** [LeetCode-Feedback/LeetCode-Feedback#7588] opened 2022-06-03 09:14 UTC
#### Your LeetCode username

phuhoangtran297

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My output in Run Code Result section is different from other code editors and It led me wrong answer.

#### Code you used for Submit/Run operation

```
def discountPrices(self,sentence, discount):
    lst = sentence.split()
    for i,value in enumerate(lst) :
        if value.startswith('$')and value[1:].isdigit():
            lst[i] = lst[i].replace(lst[i][1:],"{:.2f}".format(int(lst[i][1:])- discount*int(lst[i][1:])/100))
    return ' '.join(lst)

```

#### Screenshots

![image](https://user-images.githubusercontent.com/90390575/171822893-14b26015-f368-4b86-8671-622de3e2c923.png)
![image](https://user-images.githubusercontent.com/90390575/171823313-297186d7-c0f0-4ecc-8f80-66d7d37d9dc5.png)
![image](https://user-images.githubusercontent.com/90390575/171822744-07112f8b-7f20-4648-acde-1c41f3ea9cad.png)

**Comment by LC-Pam** [comment] 2022-06-03 17:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Test Case that you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 01:06
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 01:06 UTC
Labels: LCUS, problem
