### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by TryHardCode1** [LeetCode-Feedback/LeetCode-Feedback#8263] opened 2022-07-20 04:12 UTC
#### Your LeetCode username

tonghoai17a

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I want to add test cases

#### Test cases:

Test case 1:
Input: s = (()())
Output: Yes

Test case 2:
Input: s = (
Output: No

Test case 3:
Input: s = ()
Output: Yes

Test case 4:
Input: s = ()(
Output: No

Test case 5:
Input: s = [[}]
Output: No

Test case 6:
Input: s = {{}][](()]
Output: No

**Comment by stormsunshine** [comment] 2022-07-20 08:17
Some of the test cases alreaady exist. Why do you think these test cases should be added? Is there any code that can get accepted but fails on these test cases?

**Comment by LC-Pam** [comment] 2022-07-20 17:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-22 17:25
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-22 17:25 UTC
Labels: LCUS, problem
