### ISSUE TITLE
Missing Test Case - 520. Detect Capital

### ISSUE THREAD

**Issue by anuruddhtiwari** [LeetCode-Feedback/LeetCode-Feedback#10700] opened 2023-01-02 14:08 UTC
bool detectCapitalUse(string word) {
        int l=word.size();
        int cap=0,lower=0;
        for(int i=0;i<l;i++){
            if(islower(word[i])) lower++;
            else cap++;
        } if(cap==l || lower==l|| (isupper(word[0])&& lower==l-1))
        return true;
        else return false;
    }

**Comment by LC-Pam** [comment] 2023-01-02 20:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-04 18:59
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-04 18:59 UTC
Labels: LCUS, problem
