### ISSUE TITLE
Wrong Evaluation in 1114. Print in Order

### ISSUE THREAD

**Issue by ssanjeev2424** [LeetCode-Feedback/LeetCode-Feedback#1795] opened 2020-12-28 11:07 UTC
#### Category of the bug
- [1] Question

#### Description of the bug

Wrong evaluation is given for my code. As this is a question based on Concurrency, my code got excepted even if just put the Threads to "sleep" for some time, and force the expected outcome.
I put the Thread 2 to sleep for 50ms and Thread 3 to 100ms, when I submitted the code, it got accepted, that is, executed the three Threads in the correct order.
But suppose, in the real application, if we had called the Thread 1 after 5 seconds of Thread 2, then it would not have worked, as the Thread 2 will get executed after 50ms (even before the Thread t1 or functions) which is not the expected output.
The output must be "firstsecondthird".

#### Code you used for Submit/Run operation

```
// 1114. Print in Order
class Foo {

    public Foo() {
        
    }

    public void first(Runnable printFirst) throws InterruptedException {
        
        // printFirst.run() outputs "first". Do not change or remove this line.
        printFirst.run();
    }

    public void second(Runnable printSecond) throws InterruptedException {
        
        // printSecond.run() outputs "second". Do not change or remove this line.
        Thread.sleep(50);
        printSecond.run();
    }

    public void third(Runnable printThird) throws InterruptedException {
        
        // printThird.run() outputs "third". Do not change or remove this line.
        Thread.sleep(100);
        printThird.run();
    }
};
```

#### Language used for code

Java

#### Expected behavior

For the input [2, 1, 3],
If we have a delay of some seconds between the threads execution (where they are called), my code will not work. It can generate "secondfirstthird", "firstthirdsecond", or any other permutation depending on the delay and sequence.
The correct expected output must be "firstsecondthird" in every case.

#### Screenshots

![image](https://user-images.githubusercontent.com/31368706/103210079-a6279c80-492a-11eb-974e-e5e94e501ec4.png)
![image](https://user-images.githubusercontent.com/31368706/103210106-bb9cc680-492a-11eb-9898-300bb43eefc3.png)

#### Additional context

None

**Comment by lc-kay** [comment] 2021-01-04 22:10
@ssanjeev2424 The expected output is as stated in your expected behavior, "firstsecondthird". To understand your issue here, can you please provide the code that will get accepted even if it doesn't match the expected output?

**Comment by lc-kay** [comment] 2021-01-12 00:40
Hi @ssanjeev2424 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-01-12 00:40 UTC
Labels: LCUS, problem, watchlist
