### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by abhishekdixitadobe** [LeetCode-Feedback/LeetCode-Feedback#12775] opened 2023-04-05 08:25 UTC
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case is wrong. The value for array { -2,0,10,-19,4,6,-8 } is expected as false whereas it should be as true as arr[1] = 0 and 2* arr[1] will also be zero

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

The test case for arr ={-2,0,10,-19,4,6,-8} should return true instead it is returning false

**Comment by LC-Pam** [comment] 2023-04-05 18:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by abhishekdixitadobe** [comment] 2023-04-05 18:17
Code:
Hashtable<Integer, Integer> hash = new Hashtable<>();
		boolean flag = false;
		for (int i = 0; i < (arr.length - 1); i++) {
			hash.put(i, arr[i]);
		}

		for (int i = 0; i < arr.length; i++) {
			Enumeration<Integer> keys = hash.keys();
			while (keys.hasMoreElements()) {
				int key = keys.nextElement();
				if ((2 * arr[i]) == hash.get(key)) {
					flag = true;
				}
				if (((arr[i] % 2) == 0) && ((arr[i] / 2) == hash.get(key))) {
					flag = true;
				}
			}
		}
		return flag;
	}

Language: Java

**Comment by LC-Pam** [comment] 2023-04-07 18:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-07 18:05 UTC
Labels: LCUS, problem
