### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by prabaltripathi** [LeetCode-Feedback/LeetCode-Feedback#13898] opened 2023-06-05 04:29 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        int start=0;
        int end=nums.length-1;
        int ans=0;
        if(nums.length==1)
        return 0;
        else if(nums.length==2)
        {
            if(nums[0]<nums[1])
            return 1;
            else
            return 0;
        }
        else{
        while(start<=end)
        {
            int mid=start+(end-start)/2;
            if(mid==0){
            ans=mid;
            break;}
            if(nums[mid]>=nums[mid-1]&&nums[mid]<=nums[mid+1])
            start=mid+1;
            else if(nums[mid]<=nums[mid-1]&&nums[mid]>=nums[mid+1])
            end=mid-1;
            else{
            ans=mid;
            break;
            }
        }}
        return ans;
    }
}
```

**Comment by prabaltripathi** [comment] 2023-06-05 04:30
I don't think the bug is clearly explained

**Comment by LC-Pam** [comment] 2023-06-06 19:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:33
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:33 UTC
Labels: LCUS, problem
