### ISSUE TITLE
Missing Test Case - 271. Encode and Decode Strings

### ISSUE THREAD

**Issue by RollyPanda** [LeetCode-Feedback/LeetCode-Feedback#14457] opened 2023-07-01 00:16 UTC
#### Your LeetCode username
RollyPanda

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug
The point of this problem is to have two functions, encode and decode, the idea is NOT to use any of the normal punctuation separators for encoding, and to use a more advanced approach.

On a Windows keyboard, there is this key, to the right of the right fn key and to the left of the right ctrl key. It is known as the menu key, on a Mac computer, however, this function doesn't exist, so it ends up as a strange character.
This is the character:

On different IDE's and platforms it will render differently, but it can be used as a separator, defeating the whole purpose of the problem!

#### Code you used for Submit/Run operation

```
class Solution {
public:
    /*
     * @param strs: a list of strings
     * @return: encodes a list of strings to a single string.
     */
    string encode(vector<string> &strs) {
        // write your code here
        string ans = "";
        for (int i = 0; i < strs.size(); i++) {
            ans += strs[i] + '';
        }
        return ans;
    }

    /*
     * @param str: A string
     * @return: decodes a single string to a list of strings
     */
    vector<string> decode(string &str) {
        // write your code here
        vector<string> ans;
        string temp = "";
        for (int i = 0; i < str.size(); i++) {
            if (str[i] != '') {
                temp += str[i];
            } else {
                ans.push_back(temp);
                temp = "";
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
If the  character had been any of the other punctuation marks (!, @, #, $, etc), it would not have worked, it would have decoded wrong, because the existing test cases include strings, as such: 'abc#def' that would interfere. The problem now is the existing test cases do NOT include strings with this: 

#### Screenshots
<img width="49" alt="Screenshot 2023-06-30 at 7 42 06 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54608338/3cd14991-64c4-43aa-bfac-bba2a183a737">

It looks different on all IDE's but this is one example.

#### Additional context
This is quite a small issue...

**Comment by LC-Pam** [comment] 2023-07-12 19:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The character


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-17 20:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-17 20:34 UTC
Labels: LCUS, problem
