### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by nebaaaazzzz** [LeetCode-Feedback/LeetCode-Feedback#10526] opened 2022-12-25 05:18 UTC
#### Category of the bug
- [ ] Solution

#### Description of the bug

i run the test case in my code editor and test the function with test case [0,0,0,0,0,0,0] and returns as expected but in leetcode throws error

#### Code you used for Submit/Run operation
<!-- 
```
var duplicateZeros = function(arr) {
     let i = 0;
    let len = arr.length
    while(i<len){

      if(arr[i]===0){
            let temp = arr.slice(i , arr.length-1);
                arr.splice(i+1 , temp.length ,...temp)
                arr[i+1]=0;
            i=i+2
        }else{
            i++;
        }
    }
    return arr.slice(0,len)
};
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
#Javascript

#### Expected behavior
to pass this test case[0,0,0,0,0,0,0]

**Comment by nskybytskyi** [comment] 2022-12-25 15:52
What code did you use for run/submit operation?

**Comment by LC-Pam** [comment] 2022-12-26 18:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-28 20:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-28 20:45 UTC
Labels: LCUS, problem
