### ISSUE TITLE
Missing Test Case - 1396. Design Underground System

### ISSUE THREAD

**Issue by dannybunschoten** [LeetCode-Feedback/LeetCode-Feedback#13793] opened 2023-05-31 18:30 UTC
#### Your LeetCode username
dbunschoten

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This is a missing test case because this testcase is not yet present, and it tests for the case where a passenger travels indirectly. In implementations where it is simply tested whether a passenger checks in at a station, and the same passenger checks out the preferred station on a later time. This trip will be taken into account, however per problem description this should not be the case.

#### Code you used for Submit/Run operation

```
["UndergroundSystem","checkIn","checkOut","checkIn","checkOut","checkIn","checkOut","getAverageTime"]
[[],[1,"A",1],[1,"B",2],[1,"B",3],[1,"C",4],[1,"A",10],[1,"C",20],["A","C"]]
```

#### Language used for code
Java

**Comment by LC-Pam** [comment] 2023-05-31 19:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:30 UTC
Labels: LCUS, problem
