### ISSUE TITLE
224. Basic Calculator

### ISSUE THREAD

**Issue by Edgoze** [LeetCode-Feedback/LeetCode-Feedback#8589] opened 2022-08-08 19:09 UTC
#### Your LeetCode username

edgoze187

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case "()"

**Comment by stormsunshine** [comment] 2022-08-09 00:16
Why do you want to add an invalid test case?

**Comment by Edgoze** [comment] 2022-08-09 00:18
Is it invalid? When I run it on console it's allowed

**Comment by 152334H** [comment] 2022-08-09 04:43
`()` surely has no meaning as an integer? I suggest reclassifying this issue under Question/Solution; the test case runner ought to reject `()` as a custom test case.

**Comment by LC-Pam** [comment] 2022-08-09 17:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-10 17:49
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-10 17:49 UTC
Labels: LCUS, problem
