### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by sujal1885** [LeetCode-Feedback/LeetCode-Feedback#8152] opened 2022-07-12 15:36 UTC
#### leetcode username

sujalagrawal1885

#### Category of the bug
- [ ] Question
- [ yes] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int myAtoi(string s) {
         string parsedString;
        for(int i=0;i<s.size();i++){
            if(s[i]==' ' && parsedString.size()==0)
                continue;
            if(parsedString.size()==0 && s[i]=='-'){
                parsedString.push_back(s[i]);
                continue;
            }
             if(parsedString.size()==0 && s[i]=='+'){
                parsedString.push_back(s[i]);
                continue;
            }
            
            if(s[i]<'0' || s[i]>'9')
                break;
            parsedString.push_back(s[i]);
        }
        if(parsedString[0]=='-'){
            parsedString.erase(parsedString.begin(),parsedString.begin()+1);
            int i=0;
            while(parsedString[i]=='0'){
                parsedString.erase(parsedString.begin()+i,parsedString.begin()+i+1);
               
            }
         long long   int k=1;
          long long  int num=0;
           for(int i=parsedString.size()-1;i>=0;i--){
                if(num>2147483648)
                    return -2147483648;
               num=(parsedString[i]-48)*k +num; 
               k*=10;
                if(k>10000000000)
                    
                return -2147483648;
            }
            if(-1*num<-2147483648)
                return -2147483648;
           return (-1)*num;
       }
        
        
        if(parsedString[0]=='+')
             parsedString.erase(parsedString.begin(),parsedString.begin()+1);
             int i=0;
            while(parsedString[i]=='0'){
                parsedString.erase(parsedString.begin()+i,parsedString.begin()+i+1);
               
            }
         long long   int k=1;
         long long   int num=0;
            for(int i=parsedString.size()-1;i>=0;i--){
                if(num>2147483647)
                    return 2147483647;
               num=(parsedString[i]-48)*k +num; 
               k*=10;
                if(k>10000000000)
                    
                return 2147483647;
            }
        if(num>2147483647)
                return 2147483647;
            return num;
        }
};
```

#### Language used for code
 C++

**Comment by LC-Pam** [comment] 2022-07-12 17:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:44 UTC
Labels: LCUS, problem
