### ISSUE TITLE
Missing Test Case - 1251. Average Selling Price

### ISSUE THREAD

**Issue by Abhiraj2002** [LeetCode-Feedback/LeetCode-Feedback#16099] opened 2023-09-01 17:59 UTC
#### Your LeetCode username

abhiraj2002

#### Category of the bug
- [ ] Question
- [1251] 
- [ ] Solution
- [ SELECT p.product_id,ROUND(if(u.purchase_date is NULL,0,SUM(u.units*p.price)/SUM(u.units)),2) as average_price
FROM Prices p LEFT JOIN UnitsSold u ON p.product_id=u.product_id 
WHERE((u.purchase_date >=p.start_date && u.purchase_date <=p.end_date) || u.purchase_date is NULL)
GROUP BY product_id;]
- [ MySQL] Language
- [ ] Missing Test Cases 
- [ Prices =
| product_id | start_date | end_date   | price |
| ---------- | ---------- | ---------- | ----- |
| 1          | 2019-02-17 | 2019-02-28 | 5     |
| 1          | 2019-03-01 | 2019-03-22 | 20    |
| 2          | 2019-02-01 | 2019-02-20 | 15    |
| 2          | 2019-02-21 | 2019-03-31 | 30    |
| 3          | 2019-02-21 | 2019-03-31 | 30    |
UnitsSold =
| product_id | purchase_date | units |
| ---------- | ------------- | ----- |
| 1          | 2019-02-25    | 100   |
| 1          | 2019-03-01    | 15    |
| 2          | 2019-02-10    | 200   |
| 2          | 2019-03-22    | 30    |] 

#### Description of the bug

if we have a product_id in the price table that is not in the UnitSold Table than the output for the missing id from the UnitSold Table should be 0 but there is no such testcase that checks for this .

#### Code you used for Submit/Run operation

``Prices =
| product_id | start_date | end_date   | price |
| ---------- | ---------- | ---------- | ----- |
| 1          | 2019-02-17 | 2019-02-28 | 5     |
| 1          | 2019-03-01 | 2019-03-22 | 20    |
| 2          | 2019-02-01 | 2019-02-20 | 15    |
| 2          | 2019-02-21 | 2019-03-31 | 30    |
| 3          | 2019-02-21 | 2019-03-31 | 30    |
UnitsSold =
| product_id | purchase_date | units |
| ---------- | ------------- | ----- |
| 1          | 2019-02-25    | 100   |
| 1          | 2019-03-01    | 15    |
| 2          | 2019-02-10    | 200   |
| 2          | 2019-03-22    | 30    | ``

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

MySql

**Comment by LC-Pam** [comment] 2023-09-01 20:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:51 UTC
Labels: Waiting for Reply
