### ISSUE TITLE
Missing Test Case - 75. Sort Colors 

### ISSUE THREAD

**Issue by satyanshpandey** [LeetCode-Feedback/LeetCode-Feedback#19755] opened 2024-01-26 09:38 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ {2,2,0,1,0}] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [{2,2,0,1,0} ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

<img width="238" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53125956/cc0eaee1-9879-4993-a32b-1164c41f488a">

### Additional context

#include<iostream>
#include<vector>
using namespace std;

int arr_sort(vector<int> & arr){
    int low = 0;   //point 0
    int mid = 0;  //point 1
    int high = arr.size()-1; // point 2

    while (mid<=high)
    {
        if(arr[mid]==0){
            swap(arr[mid],arr[low]);
            mid++;
            low++;
        }
        if(arr[mid]==1){
            mid++;
        }
        else if (arr[mid]==2)
        {
            swap(arr[high],arr[mid]);
            high--;
        }
   
    }
    
}

int main(){
    
     vector<int>arr{2,2,0,1,0};
    cout<<"Printing arrays value before sorting: "<<endl;
    for (int i = 0; i < arr.size(); i++)
    {
        cout<<arr[i]<<" ";
    }

    arr_sort(arr);

    cout<<endl<<"printing arrays value after sorting: "<<endl;
    for (int i = 0; i < arr.size(); i++)
    {
        cout<<arr[i]<<" ";
    }
    return 0;
}

// {2,2,0,1,0}

// this logic is wworking for all other test cases 
// vector<int>arr {2,2,0,1,0,1,1,1};

**Comment by satyanshpandey** [comment] 2024-01-26 09:38
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53125956/98dd78fc-07e2-47d3-9518-532d58bfc480)

**Comment by satyanshpandey** [comment] 2024-01-26 09:39
<img width="261" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53125956/6e8f2115-7ef8-4428-aed3-ebb4ce494e45">

**Comment by LC-Pam** [comment] 2024-01-26 19:50
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-01-29 08:07 UTC
Labels: LCUS, watchlist, problem
