### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by sarah131** [LeetCode-Feedback/LeetCode-Feedback#11977] opened 2023-02-24 17:52 UTC
#### Your LeetCode username
sarah-rachel

#### Category of the bug
[ ] Missing Test Cases 

#### Description of the bug
Add this testcase
-222211155554444787829290101333999023456777
-7776543209993331010929287874444555551112222

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-02-24 20:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-27 22:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-27 22:00 UTC
Labels: LCUS, problem

**Comment by sarah131** [comment] 2023-02-28 06:27
The language i used is Python
