### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by PalashGaikwad** [LeetCode-Feedback/LeetCode-Feedback#9615] opened 2022-10-25 08:14 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

// Two Sum
```
class Solution {
public:
    bool isPowerOfTwo(int n) {
        static int i {1};
     if (n == 1) {
         return true;
     }
        else if (n == 4) {
            return true;
        }
        else if (n == 8) {
            return true;
        }
        else {
            if (n == pow(2,i)||n==4 && i < 32) {
                return true;
            }
            else {
                i++;
                if (i >= 32) {
                    return false;
                }
            isPowerOfTwo(n);
            }
        }
        return isPowerOfTwo(n);
    }
};
```

**Comment by LC-Pam** [comment] 2022-10-25 16:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 15:58
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 15:58 UTC
Labels: LCUS, problem
