### ISSUE TITLE
Missing Test Case - 17. Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14846] opened 2023-07-17 17:24 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Letter Combination Of Phone Number
class Solution {
    // This function for mapping numbers to the string, if 
    // you don't like this you can hard code this
    private void fillMap(Map<Integer, String> mp) {
        int cnt = 2;
        char i = 'a';
        while (i <= 'z') {
            if (cnt == 7 || cnt == 9) {
                for (int j = 0; j < 4; j++) {
                    mp.put(cnt, mp.getOrDefault(cnt, "") + i);
                    i++;
                }
                cnt++;
            } else {
                for (int j = 0; j < 3; j++) {
                    mp.put(cnt, mp.getOrDefault(cnt, "") + i);
                    i++;
                }
                cnt++;
            }
        }
    }
    //This is for creating strings
    private void f(int idx, String digits, List<String> ans, Map<Integer, String> mp) {
        if (idx == digits.length()) {
            return;
        }
        List<String> temp = new ArrayList<>(ans);
        ans.clear();
        int d = Character.getNumericValue(digits.charAt(idx));
        for (String i : temp) {
            for (char c : mp.get(d).toCharArray()) {
                i += c;
                ans.add(i);
                i = i.substring(0, i.length() - 1);
            }
        }
        f(idx + 1, digits, ans, mp);
    }

    public List<String> letterCombinations(String digits) {
        List<String> ans = new ArrayList<>();
        if (digits.length() == 0) {
            return ans;
        }
        ans.add("");
        Map<Integer, String> mp = new HashMap<>();
        fillMap(mp);
        f(0, digits, ans, mp);
        return ans;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-17 20:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:11 UTC
Labels: LCUS, problem, Waiting for Reply
