### ISSUE TITLE
Missing Test Case - 1759. Count Number of Homogenous Substrings

### ISSUE THREAD

**Issue by guangyu-zhao** [LeetCode-Feedback/LeetCode-Feedback#17940] opened 2023-11-09 04:23 UTC
### LeetCode Username

zgy20010917

### Problem number, title, and link

1759. Count Number of Homogenous Substrings https://leetcode.com/problems/count-number-of-homogenous-substrings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [√] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The answer should modulo 10^9 + 7. But if I forget to modulo 10^9 in some times, it still passes when submitted.

### Language used for code

C++

### Code used for Submit/Run operation

class Solution {
public:
    int countHomogenous(string s) {
        int len = s.size();
        int homo = 1;
        char cache = s[0];
        int sum = 1;
        for (int i = 1; i < len; i++) {
            if (s[i] == cache) {
                homo++;
                sum = (sum + homo) % 1000000007;
            } else {
                homo = 1;
                sum++; // forgot to modulo 10^9 + 7
                cache = s[i];
            }
        }
        return sum;
    }
};

### Expected behavior

It should output 4 but the output of the code above is 1000000011. However, the test cases didn't detect the bug.

### Screenshots

The WA screenshot: https://ibb.co/4d2KxW4
The accepted screenshot: https://ibb.co/1rR10Ny

**Comment by LC-Pam** [comment] 2023-11-13 21:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:09 UTC
Labels: Waiting for Reply
