### ISSUE TITLE
1420. Build Array Where You Can Find The Maximum Exactly K Comparisons - missing testcase

### ISSUE THREAD

**Issue by a-marchetti** [LeetCode-Feedback/LeetCode-Feedback#16997] opened 2023-10-07 10:01 UTC
#### Your LeetCode username

a_mar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Problem [1420. Build Array Where You Can Find The Maximum Exactly K Comparisons](https://leetcode.com/problems/build-array-where-you-can-find-the-maximum-exactly-k-comparisons/) is missing testcase with k=0, causing wrong solutions to be accepted.

#### Code you used for Submit/Run operation

```
def numOfArrays(n: int, m: int, k: int) -> int:
    if m < k: return 0

    dp = [[int(ki == 0)] * m for ki in range(k)]
    for _ in range(n - 1):
        for i in range(k - 1, -1, -1):
            acc = 0
            for j in range(m - 1, -1, -1):
                dp[i][j] = dp[i][j] * (j + 1) + acc
                if i > 0: acc += dp[i - 1][j]
    return sum(dp[-1]) % (10 ** 9 + 7)
```

#### Language used for code

python

#### Expected behavior

The code above fails for k=0, but it is accepted as solution

**Comment by LC-Pam** [comment] 2023-10-09 18:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:48 UTC
Labels: Waiting for Reply
