### ISSUE TITLE
Impossible Test Case - Violates Guarantee of Problem Description (353. Design Snake Game)

### ISSUE THREAD

**Issue by TravisNP** [LeetCode-Feedback/LeetCode-Feedback#17454] opened 2023-10-25 20:52 UTC
#### Your LeetCode username
tpencee

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Impossible Test Case

#### Description of the bug
There is a bad test case (test case 446).
["SnakeGame", "move", "move", "move", "move"]
[[2,2,[[0,1],[1,1],[1,0],[0,0]]],["R"],["D"],["L"],["U"]]

This test case is not possible as it violates the guarantee that food will not spawn on the snake. When the snake reaches the cell [1,0] and eats the food there, it will have eaten food at every previous cell, and so the snake will have eaten three pieces of food. This means that the snake, whose head is at [1,0], will occupy the full grid with it's tail on [0,0]. The next food spawns on [0,0], which the snake is at. This violates your description, and makes me fail the problem.

**Comment by LC-Pam** [comment] 2023-10-27 19:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 17:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:59 UTC
Labels: Waiting for Reply
