### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by tanisha-pati** [LeetCode-Feedback/LeetCode-Feedback#14847] opened 2023-07-17 17:38 UTC
#### Your LeetCode username

Tanisha_Pati
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
1)MISSING TEST CASE:[0,1,2,3,4,5]
2))MISSING TEST CASE:[-5,-5]
#### Description of the bug
1)THIS IS THE RESULT IF NO REPEATED ELEMENTS ARE THERE
2)CASEOF NEGATIVE NOS
#### Code you used for Submit/Run operation

class Solution {
    public int removeDuplicates(int[] nums) {
        int arr[]=new int [nums.length];
        int k=1;
        for(int i=0;i<nums.length-1;i++){
        if(nums[i]!=nums[i+1]){
            nums[k]=nums[i+1];
            k++;
        }
       
      }
return k;
    }
   
}

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

JAVA

**Comment by LC-Pam** [comment] 2023-07-17 20:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:12 UTC
Labels: LCUS, problem, Waiting for Reply
