### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by khandelwalaastha** [LeetCode-Feedback/LeetCode-Feedback#19440] opened 2024-01-16 09:29 UTC
Aastha_khandelwal
 27 Remove Element
https://leetcode.com/problems/remove-element/

### Category of the bug
- [x] Contribute a test case

### Description of the test case
I wanted to contribute a test case to remove element question 

### Code used for Submit/Run operation
<!-- 
Please make sure to wrap the code with ``` class Solution {
public:
    int removeElement(vector<int>& nums, int val) {
        int last=nums.size();
        for(int i=0;i<last;){
            if(nums[i]== val){
               nums[i]=nums[last-1];
                last--;
            }
            else{
                i++;
            }

        }
        
        return last;
    }
};

```
Contributed test case
nums =
[1,5,7,5,8,9,5]
val=5

### Expected behavior(output)
[1,7,8,9,_,_,_]

**Comment by LC-Pam** [comment] 2024-01-17 19:50
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-19 20:23
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-19 20:23 UTC
Labels: Waiting for Reply
