### ISSUE TITLE
Missing Test Case - 2621. Sleep

### ISSUE THREAD

**Issue by devRukasu** [LeetCode-Feedback/LeetCode-Feedback#13476] opened 2023-05-15 03:32 UTC
#### Your LeetCode username
devRukasu

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given a positive integer millis, write an asyncronous function that sleeps for millis milliseconds. It can resolve any value.

#### Code you used for Submit/Run operation

/**
 * @param {number} millis
 */
async function sleep(millis) {
    return new Promise((resolve) => {

        setTimeout(()=>{
            console.log("Esperou isso aqui!")
            resolve()
        }, millis)

    })  
}

#### Language used for code

JavaScript

**Comment by LC-Pam** [comment] 2023-05-16 00:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-19 19:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-19 19:40 UTC
Labels: LCUS, problem
