### ISSUE TITLE
Missing Test Case - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by Kinfe123** [LeetCode-Feedback/LeetCode-Feedback#13697] opened 2023-05-26 07:15 UTC
#### Your LeetCode username
@Kinfe123

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
The example for testcase 3 is not correct 
3 is converted mistakenly by 4 on the discription of the example
Input: nums = [3,100,20]
Output: 0
Explanation: We can make at most 3 moves.
In the first move, change 100 to 7. nums becomes [4,7,20].
In the second move, change 20 to 7. nums becomes [4,7,7].
In the third move, change 4 to 3. nums becomes [7,7,7].
After performing 3 moves, the difference between the minimum and maximum is 7 - 7 = 0.

**Comment by LC-Pam** [comment] 2023-05-26 20:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-30 20:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-30 20:46 UTC
Labels: LCUS, problem
