### ISSUE TITLE
Test Cases Problem in JS - 21. Merge Two Sorted Lists

### ISSUE THREAD

**Issue by KaikaiSong99** [LeetCode-Feedback/LeetCode-Feedback#12237] opened 2023-03-07 22:06 UTC
#### Your LeetCode username

KaikaiSong99

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * function ListNode(val, next) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.next = (next===undefined ? null : next)
 * }
 */
/**
var mergeTwoLists = function(list1, list2) {
    // initialize new linked list
    let head = new ListNode(null)

    // new pointer
    let current = head

    // loop while both lists are not null (did not reach end)
    while (list1 && list2) {

        // check which val is lower and point current to it
        // move the pointer on the lower list 
        if (list1.val <= list2.val){
            current.next = list1
            list1 = list1.next
        } else {
            current.next = list2
            list2 = list2.next
        }

        // move the current pointer
        current = current.next
    }

    // determine which node is not null
    let remaining = list1 || list2

    // set current to the remaining list
    current.next = remaining


    // return next because head was initialized to null
    return head.next
};
```

#### Language used for code

JavaScript

#### Expected behavior

In this problem, it is not possible to distinguish test cases `list1=[], list2=[]`, `list1=[], list2=[0]` and `list1=[0], list2=[0]` by definition of the given ListNode data structure, while it expects different outputs. The code I provided can pass all the test cases but I don't have any clue why. Let me know if I'm wrong.

**Comment by LC-Pam** [comment] 2023-03-08 19:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-09 18:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-09 18:46 UTC
Labels: LCUS, problem
