### ISSUE TITLE
Missing Test Case - 722. Remove Comments

### ISSUE THREAD

**Issue by eternity-phoenix** [LeetCode-Feedback/LeetCode-Feedback#15956] opened 2023-08-27 10:59 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public List<String> removeComments(String[] source) {
        List<String> ans = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        boolean inBlock = false;
        for(String line : source) {
            for(int i = 0; i < line.length(); i++) {
                if(inBlock) {
                    if(line.charAt(i) == '*' && line.charAt(i+1) == '/') {
                        inBlock = false;
                        i++;
                        continue;
                    }
                } else {
                    if(i < line.length()-1 && line.charAt(i) == '/' && line.charAt(i+1) == '/') {
                        break;
                    }
                    if(i < line.length()-1 && line.charAt(i) == '/' && line.charAt(i+1) == '*') {
                        inBlock = true;
                        i++;
                        continue;
                    }

                    sb.append(line.charAt(i));
                }
            }

            if(!inBlock && sb.length() > 0) {
                ans.add(sb.toString());
                sb.setLength(0);
            }
        }

        return ans;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
miss Test Cases check， the Screenshots is a new Test Cases by myself added, but submitted code is passed, so I think you miss some Test Cases.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14177290/e6d7f98a-d2c1-486d-b6e2-e05e6994be78)

**Comment by LC-Pam** [comment] 2023-08-28 20:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:45 UTC
Labels: Waiting for Reply
