### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by INC02165** [LeetCode-Feedback/LeetCode-Feedback#11423] opened 2023-02-02 05:13 UTC

**Comment by Vyshnavi-Kotha** [comment] 2023-02-02 05:19
class Solution {
  public boolean isAlienSorted(String[] words, String order) {
    char[] map = new char[26]; // Order = "bca" -> map = ['c', 'a', 'b']

    for (int i = 0; i < 26; ++i)
      map[order.charAt(i) - 'a'] = (char) (i + 'a');

    for (int i = 0; i + 1 < words.length; ++i)
      if (bigger(words[i], words[i + 1], map))
        return false;

    return true;
  }

  private boolean bigger(final String s1, final String s2, final char[] map) {
    for (int i = 0; i < s1.length() && i < s2.length(); ++i)
      if (s1.charAt(i) != s2.charAt(i))
        return map[s1.charAt(i) - 'a'] > map[s2.charAt(i) - 'a'];
    return s1.length() > s2.length();
  }
}

  private boolean bigger(final String s1, final String s2, final char[] map) {
    for (int i = 0; i < s1.length() && i < s2.length(); ++i)
      if (s1.charAt(i) != s2.charAt(i))
        return map[s1.charAt(i) - 'a'] > map[s2.charAt(i) - 'a'];
    return s1.length() > s2.length();
  }
}

[ Back to top](https://walkccc.me/LeetCode/problems/0953/#)

**Comment by LC-Pam** [comment] 2023-02-02 17:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-07 19:02
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-07 19:02 UTC
Labels: LCUS, problem
