### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by vinitv5singh** [LeetCode-Feedback/LeetCode-Feedback#15820] opened 2023-08-22 15:53 UTC
ITS GIVING WRONG RESULT.
KINDLY CHECK.
THE CORRECT CODE IS :
# Write your MySQL query statement below
select name, population, area from World where area>3000000 or population>=25000000;

**Comment by YogeshP93** [comment] 2023-08-23 08:35
>= 3000000.... You missed "=" there

**Comment by LC-Pam** [comment] 2023-08-23 20:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:32 UTC
Labels: Waiting for Reply
