### ISSUE TITLE
Missing Test Case - 166. Fraction to Recurring Decimal

### ISSUE THREAD

**Issue by kelnishi** [LeetCode-Feedback/LeetCode-Feedback#2095] opened 2021-01-21 23:05 UTC
#### Your LeetCode username
KelNishi

#### Category of the bug
Question about Inputs

#### Description of the bug
The problem says the output solutions are guaranteed to be less than 10000 characters, but there exist inputs within the valid range that exceed that length. What does the "guarantee" have to do with the validity of the solution? Should the program just stop after 10000 characters or throw an exception or what?

#### Code you used for Submit/Run operation
Test case:
1
104695

Running Produces:
```
This input is invalid. The length of the output should be less than 10^4.
```

#### Language used for code
Python

#### Expected behavior
WTH is a "guarantee"? Clearly, there exist inputs within the range that don't abide by this guarantee. 
0.0(0000955155451549739720139452695926261999140360093605234251874492573666364200773675915755289173312956683700272219303691675820239744018338984669755002626677491761784230383494913797220497635990257414394192654854577582501552127608768327045226610630880175748603085152108505659296050432207841826257223363102344906633554611012942356368498973207889584029800850088351879268350924112899374373179234920483308658484168298390563064138688571565022207364248531448493242275180285591480013372176321696356081952337742967667987965041310473279526242896031329098810831462820574048426381393571803811070251683461483356416256745785376570036773484884664979225368928793161086966903863603801518697167964086155021729786522756578633172548832322460480443192129519079230144706050909785567601127083432828692869764554181192989158985624910454176417211901236926309756912937580591241224509288886766321218778356177467882897941640001910310903099479440278905391852523998280720187210468503748985147332728401547351831510578346625913367400544438607383351640479488036677969339510005253354983523568460766989827594440995271980514828788385309709155165003104255217536654090453221261760351497206170304217011318592100864415683652514446726204689813267109222025884712736997946415779168059601700176703758536701848225798748746358469840966617316968336596781126128277377143130044414728497062896986484550360571182960026744352643392712163904675485935335975930082620946559052485792062658197621662925641148096852762787143607622140503366922966712832513491570753140073546969769329958450737857586322173933807727207603037394335928172310043459573045513157266345097664644920960886384259038158460289412101819571135202254166865657385739529108362385978317971249820908352834423802473852619513825875161182482449018577773532642437556712354935765795883280003820621806198958880557810783705047996561440374420937007497970294665456803094703663021156693251826734801088877214766703280958976073355938679020010506709967047136921533979655188881990543961029657576770619418310330006208510435073308180906442523520702994412340608434022637184201728831367305028893452409379626534218444051769425473995892831558336119203400353407517073403696451597497492716939681933234633936673193562252256554754286260088829456994125793972969100721142365920053488705286785424327809350971870671951860165241893118104971584125316395243325851282296193705525574287215244281006733845933425665026983141506280147093939538659916901475715172644347867615454415206074788671856344620086919146091026314532690195329289841921772768518076316920578824203639142270404508333731314771479058216724771956635942499641816705668847604947705239027651750322364964898037155547065284875113424709871531591766560007641243612397917761115621567410095993122880748841874014995940589330913606189407326042313386503653469602177754429533406561917952146711877358040021013419934094273843067959310377763981087922059315153541238836620660012417020870146616361812885047041405988824681216868045274368403457662734610057786904818759253068436888103538850947991785663116672238406800706815034146807392903194994985433879363866469267873346387124504513109508572520177658913988251587945938201442284731840106977410573570848655618701943741343903720330483786236209943168250632790486651702564592387411051148574430488562013467691866851330053966283012560294187879077319833802951430345288695735230908830412149577343712689240173838292182052629065380390658579683843545537036152633841157648407278284540809016667462629542958116433449543913271884999283633411337695209895410478055303500644729929796074311094130569750226849419743063183533120015282487224795835522231243134820191986245761497683748029991881178661827212378814652084626773007306939204355508859066813123835904293423754716080042026839868188547686135918620755527962175844118630307082477673241320024834041740293232723625770094082811977649362433736090548736806915325469220115573809637518506136873776207077701895983571326233344476813601413630068293614785806389989970867758727732938535746692774249009026219017145040355317827976503175891876402884569463680213954821147141697311237403887482687807440660967572472419886336501265580973303405129184774822102297148860977124026935383733702660107932566025120588375758154639667605902860690577391470461817660824299154687425378480347676584364105258130760781317159367687091074072305267682315296814556569081618033334925259085916232866899087826543769998567266822675390419790820956110607001289459859592148622188261139500453698839486126367066240030564974449591671044462486269640383972491522995367496059983762357323654424757629304169253546014613878408711017718133626247671808586847509432160084053679736377095372271837241511055924351688237260614164955346482640049668083480586465447251540188165623955298724867472181097473613830650938440231147619275037012273747552414155403791967142652466688953627202827260136587229571612779979941735517455465877071493385548498018052438034290080710635655953006351783752805769138927360427909642294283394622474807774965375614881321935144944839772673002531161946606810258369549644204594297721954248053870767467405320215865132050241176751516309279335211805721381154782940923635321648598309374850756960695353168728210516261521562634318735374182148144610535364630593629113138163236066669850518171832465733798175653087539997134533645350780839581641912221214002578919719184297244376522279000907397678972252734132480061129948899183342088924972539280767944983045990734992119967524714647308849515258608338507092029227756817422035436267252495343617173695018864320168107359472754190744543674483022111848703376474521228329910692965280099336166961172930894503080376331247910597449734944362194947227661301876880462295238550074024547495104828310807583934285304933377907254405654520273174459143225559959883471034910931754142986771096996036104876068580161421271311906012703567505611538277854720855819284588566789244949615549930751229762643870289889679545346005062323893213620516739099288409188595443908496107741534934810640431730264100482353503032618558670423611442762309565881847270643297196618749701513921390706337456421032523043125268637470748364296289221070729261187258226276326472133339701036343664931467596351306175079994269067290701561679163283824442428005157839438368594488753044558001814795357944505468264960122259897798366684177849945078561535889966091981469984239935049429294617699030517216677014184058455513634844070872534504990687234347390037728640336214718945508381489087348966044223697406752949042456659821385930560198672333922345861789006160752662495821194899469888724389894455322603753760924590477100148049094990209656621615167868570609866755814508811309040546348918286451119919766942069821863508285973542193992072209752137160322842542623812025407135011223076555709441711638569177133578489899231099861502459525287740579779359090692010124647786427241033478198576818377190887816992215483069869621280863460528200964707006065237117340847222885524619131763694541286594393237499403027842781412674912842065046086250537274941496728592578442141458522374516452552652944266679402072687329862935192702612350159988538134581403123358326567648884856010315678876737188977506089116003629590715889010936529920244519795596733368355699890157123071779932183962939968479870098858589235398061034433354028368116911027269688141745069009981374468694780075457280672429437891016762978174697932088447394813505898084913319642771861120397344667844691723578012321505324991642389798939777448779788910645207507521849180954200296098189980419313243230335737141219733511629017622618081092697836572902239839533884139643727016571947084387984144419504274320645685085247624050814270022446153111418883423277138354267156979798462199723004919050575481159558718181384020249295572854482066956397153636754381775633984430966139739242561726921056401929414012130474234681694445771049238263527389082573188786474998806055685562825349825684130092172501074549882993457185156884282917044749032905105305888533358804145374659725870385405224700319977076269162806246716653135297769712020631357753474377955012178232007259181431778021873059840489039591193466736711399780314246143559864367925879936959740197717178470796122068866708056736233822054539376283490138019962748937389560150914561344858875782033525956349395864176894789627011796169826639285543722240794689335689383447156024643010649983284779597879554897559577821290415015043698361908400592196379960838626486460671474282439467023258035245236162185395673145804479679067768279287454033143894168775968288839008548641291370170495248101628540044892306222837766846554276708534313959596924399446009838101150962319117436362768040498591145708964133912794307273508763551267968861932279478485123453842112803858828024260948469363388891542098476527054778165146377572949997612111371125650699651368260184345002149099765986914370313768565834089498065810210611777066717608290749319451740770810449400639954152538325612493433306270595539424041262715506948755910024356464014518362863556043746119680978079182386933473422799560628492287119728735851759873919480395434356941592244137733416113472467644109078752566980276039925497874779120301829122689717751564067051912698791728353789579254023592339653278571087444481589378671378766894312049286021299966569559195759109795119155642580830030087396723816801184392759921677252972921342948564878934046516070490472324370791346291608959358135536558574908066287788337551936577678017097282582740340990496203257080089784612445675533693108553417068627919193848798892019676202301924638234872725536080997182291417928267825588614547017527102535937723864558956970246907684225607717656048521896938726777783084196953054109556330292755145899995224222742251301399302736520368690004298199531973828740627537131668178996131620421223554133435216581498638903481541620898801279908305076651224986866612541191078848082525431013897511820048712928029036725727112087492239361956158364773866946845599121256984574239457471703519747838960790868713883184488275466832226944935288218157505133960552079850995749558240603658245379435503128134103825397583456707579158508047184679306557142174888963178757342757533788624098572042599933139118391518219590238311285161660060174793447633602368785519843354505945842685897129757868093032140980944648741582692583217918716271073117149816132575576675103873155356034194565165480681980992406514160179569224891351067386217106834137255838387697597784039352404603849276469745451072161994364582835856535651177229094035054205071875447729117913940493815368451215435312097043793877453555566168393906108219112660585510291799990448445484502602798605473040737380008596399063947657481255074263336357992263240842447108266870433162997277806963083241797602559816610153302449973733225082382157696165050862027795023640097425856058073451454224174984478723912316729547733893691198242513969148478914943407039495677921581737427766368976550933664453889870576436315010267921104159701991499116481207316490758871006256268207650795166913415158317016094369358613114284349777926357514685515067577248197144085199866278236783036439180476622570323320120349586895267204737571039686709011891685371794259515736186064281961889297483165385166435837432542146234299632265151153350207746310712068389130330961363961984813028320359138449782702134772434213668274511676775395195568078704809207698552939490902144323988729165671713071302354458188070108410143750895458235827880987630736902430870624194087587754907111132336787812216438225321171020583599980896890969005205597210946081474760017192798127895314962510148526672715984526481684894216533740866325994555613926166483595205119633220306604899947466450164764315392330101724055590047280194851712116146902908448349968957447824633459095467787382396485027938296957829886814078991355843163474855532737953101867328907779741152872630020535842208319403982998232962414632981517742012512536415301590333826830316634032188738717226228568699555852715029371030135154496394288170399732556473566072878360953245140646640240699173790534409475142079373418023783370743588519031472372128563923778594966330770332871674865084292468599264530302306700415492621424136778260661922727923969626056640718276899565404269544868427336549023353550790391136157409618415397105878981804288647977458331343426142604708916376140216820287501790916471655761975261473804861741248388175175509814222264673575624432876450642342041167199961793781938010411194421892162949520034385596255790629925020297053345431969052963369788433067481732651989111227852332967190410239266440613209799894932900329528630784660203448111180094560389703424232293805816896699937914895649266918190935574764792970055876593915659773628157982711686326949711065475906203734657815559482305745260041071684416638807965996465924829265963035484025025072830603180667653660633268064377477434452457137399111705430058742060270308992788576340799465112947132145756721906490281293280481398347581068818950284158746836047566741487177038062944744257127847557189932661540665743349730168584937198529060604613400830985242848273556521323845455847939252113281436553799130808539089736854673098046707101580782272314819236830794211757963608577295954916662686852285209417832752280433640575003581832943311523950522947609723482496776350351019628444529347151248865752901284684082334399923587563876020822388843784325899040068771192511581259850040594106690863938105926739576866134963465303978222455704665934380820478532881226419599789865800659057261569320406896222360189120779406848464587611633793399875829791298533836381871149529585940111753187831319547256315965423372653899422130951812407469315631118964611490520082143368833277615931992931849658531926070968050050145661206361335307321266536128754954868904914274798223410860117484120540617985577152681598930225894264291513443812980562586560962796695162137637900568317493672095133482974354076125889488514255695114379865323081331486699460337169874397058121209226801661970485696547113042647690911695878504226562873107598261617078179473709346196093414203161564544629638473661588423515927217154591909833325373704570418835665504560867281150007163665886623047901045895219446964993552700702039256889058694302497731505802569368164668799847175127752041644777687568651798080137542385023162519700081188213381727876211853479153732269926930607956444911409331868761640957065762452839199579731601318114523138640813792444720378241558813696929175223267586799751659582597067672763742299059171880223506375662639094512631930846745307798844261903624814938631262237929222981040164286737666555231863985863699317063852141936100100291322412722670614642533072257509909737809828549596446821720234968241081235971154305363197860451788528583026887625961125173121925593390324275275801136634987344190266965948708152251778977028511390228759730646162662973398920674339748794116242418453603323940971393094226085295381823391757008453125746215196523234156358947418692392186828406323129089259276947323176847031854434309183819666650747409140837671331009121734562300014327331773246095802091790438893929987105401404078513778117388604995463011605138736329337599694350255504083289555375137303596160275084770046325039400162376426763455752423706958307464539853861215912889822818663737523281914131524905678399159463202636229046277281627584889440756483117627393858350446535173599503319165194135345527484598118343760447012751325278189025263861693490615597688523807249629877262524475858445962080328573475333110463727971727398634127704283872200200582644825445341229285066144515019819475619657099192893643440469936482162471942308610726395720903577057166053775251922250346243851186780648550551602273269974688380533931897416304503557954057022780457519461292325325946797841348679497588232484836907206647881942786188452170590763646783514016906251492430393046468312717894837384784373656812646258178518553894646353694063708868618367639333301494818281675342662018243469124600028654663546492191604183580877787859974210802808157027556234777209990926023210277472658675199388700511008166579110750274607192320550169540092650078800324752853526911504847413916614929079707722431825779645637327475046563828263049811356798318926405272458092554563255169778881512966235254787716700893070347199006638330388270691054969196236687520894025502650556378050527723386981231195377047614499259754525048951716891924160657146950666220927455943454797268255408567744400401165289650890682458570132289030039638951239314198385787286880939872964324943884617221452791441807154114332107550503844500692487702373561297101103204546539949376761067863794832609007115908114045560915038922584650651893595682697358995176464969673814413295763885572376904341181527293567028033812502984860786092936625435789674769568747313625292516357037107789292707388127417737236735278666602989636563350685324036486938249200057309327092984383208367161755575719948421605616314055112469554419981852046420554945317350398777401022016333158221500549214384641100339080185300157600649505707053823009694827833229858159415444863651559291274654950093127656526099622713596637852810544916185109126510339557763025932470509575433401786140694398013276660776541382109938392473375041788051005301112756101055446773962462390754095228998519509050097903433783848321314293901332441854911886909594536510817135488800802330579301781364917140264578060079277902478628396771574573761879745928649887769234442905582883614308228664215101007689001384975404747122594202206409093079898753522135727589665218014231816228091121830077845169301303787191365394717990352929939347628826591527771144753808682363054587134056067625005969721572185873250871579349539137494627250585032714074215578585414776254835474473470557333205979273126701370648072973876498400114618654185968766416734323511151439896843211232628110224939108839963704092841109890634700797554802044032666316443001098428769282200678160370600315201299011414107646019389655666459716318830889727303118582549309900186255313052199245427193275705621089832370218253020679115526051864941019150866803572281388796026553321553082764219876784946750083576102010602225512202110893547924924781508190457997039018100195806867567696642628587802664883709823773819189073021634270977601604661158603562729834280529156120158555804957256793543149147523759491857299775538468885811165767228616457328430202015378002769950809494245188404412818186159797507044271455179330436028463632456182243660155690338602607574382730789435980705859878695257653183055542289507617364726109174268112135250011939443144371746501743158699078274989254501170065428148431157170829552509670948946941114666411958546253402741296145947752996800229237308371937532833468647022302879793686422465256220449878217679927408185682219781269401595109604088065332632886002196857538564401356320741200630402598022828215292038779311332919432637661779454606237165098619800372510626104398490854386551411242179664740436506041358231052103729882038301733607144562777592053106643106165528439753569893500167152204021204451024404221787095849849563016380915994078036200391613735135393285257175605329767419647547638378146043268541955203209322317207125459668561058312240317111609914513587086298295047518983714599551076937771622331534457232914656860404030756005539901618988490376808825636372319595014088542910358660872056927264912364487320311380677205215148765461578871961411719757390515306366111084579015234729452218348536224270500023878886288743493003486317398156549978509002340130856296862314341659105019341897893882229332823917092506805482592291895505993600458474616743875065666937294044605759587372844930512440899756435359854816371364439562538803190219208176130665265772004393715077128802712641482401260805196045656430584077558622665838865275323558909212474330197239600745021252208796981708773102822484359329480873012082716462104207459764076603467214289125555184106213286212331056879507139787000334304408042408902048808443574191699699126032761831988156072400783227470270786570514351210659534839295095276756292086537083910406418644634414250919337122116624480634223219829027174172596590095037967429199102153875543244663068914465829313720808061512011079803237976980753617651272744639190028177085820717321744113854529824728974640622761354410430297530923157743922823439514781030612732222169158030469458904436697072448541000047757772577486986006972634796313099957018004680261712593724628683318210038683795787764458665647834185013610965184583791011987200916949233487750131333874588089211519174745689861024881799512870719709632742728879125077606380438416352261330531544008787430154257605425282964802521610392091312861168155117245331677730550647117818424948660394479201490042504417593963417546205644968718658961746024165432924208414919528153206934428578251110368212426572424662113759014279574000668608816084817804097616887148383399398252065523663976312144801566454940541573141028702421319069678590190553512584173074167820812837289268828501838674244233248961268446439658054348345193180190075934858398204307751086489326137828931658627441616123024022159606475953961507235302545489278380056354171641434643488227709059649457949281245522708820860595061846315487845646879029562061225464444338316060938917808873394144897082)

#### Additional context
len(s.fractionToDecimal(1,104695))
20943

**Comment by lc-kay** [comment] 2021-01-25 23:20
@kelnishi Can you please provide an input that is not within the constraint but is accepted?

**Comment by kelnishi** [comment] 2021-01-26 21:12
My point was: that the constraint is arbitrary and just necessitates more code to terminate early. The test case I provided produces a 20k char repeating decimal, which should cause solutions to terminate early. Solutions which do not terminate early fail the constraint yet are accepted, so the constraint is invalid.

---Kelvin--

**Comment by lc-kay** [comment] 2021-01-29 23:08
@kelnishi Yes, I understand. However, for our team to reproduce and confirm the issue, please provide us with a solution that does not terminate early and fails the constraints, but is accepted.

**Comment by lc-kay** [comment] 2021-02-10 21:04
Hi @kelnishi 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-02-10 21:04 UTC
Labels: LCUS, problem, watchlist

**Comment by kelnishi** [comment] 2021-02-10 23:32
https://leetcode.com/submissions/detail/446068066/
