### ISSUE TITLE
Missing Test Case - 948. Bag of Tokens

### ISSUE THREAD

**Issue by aditya292002** [LeetCode-Feedback/LeetCode-Feedback#9011] opened 2022-09-12 06:27 UTC
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

####Negative value of score is not considered
For the test case
token = [71,55,82]
power = 54
Leetcode sol = 0
Correct sol = 1
#####sequence of events  (i - 0 ,  j - n-1) 
tokens  : [ 55 71 82 ] 
i  : 0
j  : 2
power  : 136
score  : -1
i  : 0
j  : 1
power  : 81
score  : 0
i  : 1
j  : 1
power  : 10
score  : 1
1

**Comment by LC-Pam** [comment] 2022-09-12 17:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-13 21:23
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-13 21:23 UTC
Labels: LCUS, problem
