### ISSUE TITLE
Missing Test Case - 1193. Monthly Transactions I

### ISSUE THREAD

**Issue by phanther** [LeetCode-Feedback/LeetCode-Feedback#10577] opened 2022-12-27 23:35 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Code:
# Write your MySQL query statement below
select
DATE_FORMAT(trans_date,"%Y-%m") as month,
country,
count(id) as trans_count,
count(case when state='approved' then 1 else 0 end) as approved_count,
sum(amount) as trans_total_amount,
sum(case when state='approved' then amount else 0 end) as approved_total_amount
from Transactions
group by month, country

**Comment by LC-Pam** [comment] 2022-12-28 20:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-30 19:30
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-30 19:30 UTC
Labels: LCUS, problem
