### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by subhroacharjee** [LeetCode-Feedback/LeetCode-Feedback#7347] opened 2022-05-17 16:39 UTC
#### Your LeetCode username

[subhro_acharjee](https://leetcode.com/subhro_acharjee/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The testcases that are shown in the question, doesn't gives the whole idea of the question.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    HashMap<Integer, Integer> mem = new HashMap<>();
    public int rob(int[] nums) {
        int m1 = maxSum(nums, 0);
        int m2 = maxSum(nums, 1);
        return Integer.max(m1, m2);
    }
    
    int maxSum(int[] nums, int i) {
        int n = nums.length;
        if (i >= n) return 0;
        if (mem.containsKey(i)) return mem.get(i);
        if (i == n-1 || i == n-2) return nums[i];
        int maxSum = 0;
        for (int j = i+2; j < n; j ++) {
            maxSum = Integer.max(maxSum(nums, j), maxSum);
        }
        maxSum+=nums[i];
        mem.put(i, maxSum);
        return maxSum;
    }
}
```

#### Expected behavior

The question is fine but the two examples can be mis interpreted in a different way, which is sum of all the alternatives starting from first index and 2nd index. So it will be much better if we have this test case in the example as well.

#### Screenshots

![ss](https://user-images.githubusercontent.com/88422396/168863462-dc2958d1-bd98-4d36-b018-e6d689719593.PNG)

#### Additional context

This is the test case which is `[2,1,1,2]` required in the display page so that we have a better idea of the question.

**Comment by LC-Pam** [comment] 2022-05-17 23:21
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
What is the better idea?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-20 02:52
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-20 02:52 UTC
Labels: LCUS, problem
