### ISSUE TITLE
Largest Substring Between Two Equal Characters#hashmap#easy#0(n) time complexity

### ISSUE THREAD

**Issue by Chandak-Keshav** [LeetCode-Feedback/LeetCode-Feedback#8327] opened 2022-07-25 06:37 UTC
class Solution {
public:
    int maxLengthBetweenEqualCharacters(string s) {
        unordered_map<char,int> mp; 
        int maxi=INT_MIN;
        for(int i=0;i<s.size();i++)
            mp[s[i]]=i;
        for(int i=0;i<s.size();i++)
        {
            if(mp[s[i]]==i)
                mp.erase(s[i]);
            else
            {
                maxi=max(maxi,m

**Comment by LC-Pam** [comment] 2022-07-25 18:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
What is the missing test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:53
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:53 UTC
Labels: LCUS, problem
