### ISSUE TITLE
Missing Test Case - 602. Friend Requests II: Who Has the Most Friends

### ISSUE THREAD

**Issue by akshat6745** [LeetCode-Feedback/LeetCode-Feedback#15935] opened 2023-08-26 16:36 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug

One Testcase is missing where one pair of friends are repeated -> (1, 3) and (3, 1) both means that 1 is a friend of 3 and thus if both these are present in the table then that still means there is only one friend for 1 and 3. None of the testcases actually take care of this problem.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
select id, count(*) num from 
(
      (select requester_id id from RequestAccepted) 
      union all 
      (select accepter_id id from RequestAccepted)
) tb 
group by id order by num desc limit 1
```
```
| requester_id | accepter_id | accept_date |
| ------------ | ----------- | ----------- |
| 1            | 2           | 2016/06/03  |
| 1            | 3           | 2016/06/08  |
| 2            | 3           | 2016/06/08  |
| 3            | 1           | 2016/06/09  |
| 2            | 4           | 2016/06/09  |
```

#### Language used for code

MySQL

#### Expected behavior

This code fails as expected. But the code was already acceptable solution.

**Comment by LC-Pam** [comment] 2023-08-28 20:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:46 UTC
Labels: Waiting for Reply
