### ISSUE TITLE
Missing Test Case - 103. Binary Tree Zigzag Level Order Traversal

### ISSUE THREAD

**Issue by sat5297** [LeetCode-Feedback/LeetCode-Feedback#10924] opened 2023-01-10 09:44 UTC
#### Category of the bug
- [ ] Missing Test Cases 

## Added an extra test case. 

[3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,7,3,9,20,12,12,15,73,9,20,12,12,15,73,9,20,12,12,15,73,9,20,12,12,15,73,9,20,12,12,15,73,9,20,12,12,15,73,9,20,12,12,15,7]

**Comment by LC-Pam** [comment] 2023-01-10 21:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:45 UTC
Labels: LCUS, problem
