### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by pulsearaut** [LeetCode-Feedback/LeetCode-Feedback#18767] opened 2023-12-18 12:35 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ x] Editorial
- [ ] Programming language support

### Description of the bug

The test case [2, 0, 1, 0] fails for the Editorial solution.

### Code used for Submit/Run operation

```
fun canJump(nums: IntArray): Boolean {
        var furthestReachSoFar = 0
        val lastIndex = nums.size - 1
        var i = 0
        while (furthestReachSoFar in i until lastIndex) {
            furthestReachSoFar = Math.max(furthestReachSoFar, i + nums[i])
            ++i
        }
        return furthestReachSoFar >= lastIndex
    }

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```


### Expected behavior
<!-- A clear and concise description of what was expected to happen in
contrast with what happened. -->


### Screenshots
<!-- If applicable, add screenshots to explain the issue. -->


### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-12-19 18:55
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-21 21:46
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-21 21:46 UTC
Labels: Waiting for Reply
