### ISSUE TITLE
The code works in the Leetcode playground IDE, but fails in the Leetcode code page :  5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by parth572** [LeetCode-Feedback/LeetCode-Feedback#11023] opened 2023-01-14 15:41 UTC
Category of the bug
- Solution

Description of the bug
The code works in the Leetcode playground IDE, but fails in the Leetcode code page. (java script)

Code you used for Submit/Run operation
Q : 5. Longest Palindromic Substring

A:

let res ='';
let resLength = 0;
function getLongestPalindrome(left, right,s) {
while (left>=0 && right < s.length && s[left] === s[right]) {
if(right - left + 1 > resLength) {
res = s.slice(left, right+1);
resLength = right - left + 1;
}
left--;
right++;
}
}

function longestPalindrome(s) {
for(let i=0; i< s.length; i++) {

let [left, right] = [i,i];
getLongestPalindrome(left, right, s);

[left, right] = [i,i+1];
getLongestPalindrome(left, right, s);
}
return res;
}

Below are the leetcode result :

input s = "cbbd"
output : "bab"
expected : "bb"

input s = "abadd"
output : "bab"
expected : "aba"

Language used for code
Java Script

Expected behavior/Additional context
Note : In Leetcode playground is giving correct result

Screenshots
![leetcode_issue](https://user-images.githubusercontent.com/43738137/212480239-6396f534-189c-43ba-91ea-8fd85a990d65.jpg)
![leetcode_playground](https://user-images.githubusercontent.com/43738137/212480240-ff52febf-850e-40cf-8ea2-5be967c69965.jpg)

**Comment by LC-Pam** [comment] 2023-01-16 19:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-18 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-18 18:30 UTC
Labels: LCUS, problem
