### ISSUE TITLE
Missing Test Case - 1431. Kids With the Greatest Number of Candies

### ISSUE THREAD

**Issue by Yash12patre** [LeetCode-Feedback/LeetCode-Feedback#14027] opened 2023-06-11 03:57 UTC
class Solution {
public:
    vector<bool> kidsWithCandies(vector<int>& candies, int extra) {
        vector<bool> ans;
        int max=*max_element(candies.begin(), candies.end());
        for(int i=0; i<candies.size();i++){
            if(candies[i]+extra >= max)
            ans.push_back(true);
            else{
             ans.push_back(false);
            }
        }
return ans;
    }
};

**Comment by LC-Pam** [comment] 2023-06-13 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 20:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 20:10 UTC
Labels: LCUS, problem
