### ISSUE TITLE
Missing Test Case - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by aryandecoder0** [LeetCode-Feedback/LeetCode-Feedback#15843] opened 2023-08-23 16:04 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
bool searchMatrix(vector<vector<int>>& matrix, int target) {
        int m=matrix.size();
        int n=matrix[0].size();
        int p=0;
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(target == matrix[i][j]){
                    p++;
                }
               
            }
        }
        if(p!=0){
            return true;
        }
        else{
            return false;
        }
    }

    }
};
```

**Comment by LC-Pam** [comment] 2023-08-23 20:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:32 UTC
Labels: Waiting for Reply
