### ISSUE TITLE
Missing Test Case - 1491. Average Salary of the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by NIKHILKUSHWAHA9877** [LeetCode-Feedback/LeetCode-Feedback#13055] opened 2023-04-20 15:49 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases

**Comment by NIKHILKUSHWAHA9877** [comment] 2023-04-20 15:50
Error in testcase to find average of minimum and maximum salary

**Comment by LC-Pam** [comment] 2023-04-20 18:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-26 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-26 19:45 UTC
Labels: LCUS, problem
