### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by BhagavanJadi** [LeetCode-Feedback/LeetCode-Feedback#8240] opened 2022-07-18 10:56 UTC
class Solution {
    public boolean checkIfExist(int[] arr) {
        
        boolean flag = false;
        
        for(int i=0;i<arr.length;i++){
            for(int j=0;j<arr.length;j++){
                if((arr[i]*2==(arr[j])) && (i!=j)){
                    flag = true;
                    
                    return flag;
                }
            }
        }
        
        
        return flag;
        
       
        
    }
}

**Comment by LC-Pam** [comment] 2022-07-18 18:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-20 00:27
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-20 00:27 UTC
Labels: LCUS, problem
