### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by ani0310** [LeetCode-Feedback/LeetCode-Feedback#11808] opened 2023-02-17 18:46 UTC
#### Your LeetCode username
(https://leetcode.com/anil0310/)

#### Category of the bug
- [2462. Total Cost to Hire K Workers ] Question
- [ ] Missing Test Cases 
costs=
[5,2,4]
k =
1
candidates =
2

**Comment by LC-Pam** [comment] 2023-02-17 19:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ani0310** [comment] 2023-02-18 02:15
C++:

The below code will pass for tc in leetcode but not for this:
costs=
[5,2,4]
k =
1
candidates =
2

which is not in leetcode testcases


class Solution {
public:
    long long totalCost(vector<int>& costs, int k, int candidates) {
        int c=candidates;

        priority_queue<pair<int,int>,vector<pair<int,int>>,greater<pair<int,int>>> pq;
        int i=0,j=costs.size()-1;
        if(i==j) return costs[0];
        while(c and i<j){
            c--;
            pq.push({costs[i],i});
            pq.push({costs[j],j});
            i++;j--;
        }

        long long ans=0;

        while(i<=j and k){
            k--;
            auto it=pq.top();pq.pop();
            ans+=it.first;
            if(it.second<i){
                pq.push({costs[i],i});
                i++;
            }else{
                pq.push({costs[j],j});
                j--;
            }
        }

        while(k and !pq.empty()){
            ans+=pq.top().first;
            pq.pop();
            k--;
        }

        return ans;
    }
};

**Comment by LC-Pam** [comment] 2023-02-20 04:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link since we received Compile Error after submit above code: https://leetcode.com/submissions/detail/901317311/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-21 18:28
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-21 18:28 UTC
Labels: LCUS, problem
