### ISSUE TITLE
Missing Test Case - 994. Rotting Oranges

### ISSUE THREAD

**Issue by SagarDNG** [LeetCode-Feedback/LeetCode-Feedback#14805] opened 2023-07-16 02:42 UTC
#### Category of the bug
- [ ] Rotting Oranges
- [ ] Solution
- [ ] Java

#### Code you used for Submit/Run operation

```
class Solution {
    static class Edge{
        int src, dest, time;
        Edge(int i, int d, int t){
            this.src = i;
            this.dest = d;
            this.time = t;
        }
    }
    public int orangesRotting(int[][] grid) {
        Queue<Edge> q = new LinkedList<>();
        int rows = grid.length;
        int cols = grid[0].length;
        int min = 0;
        int totalOrng = 0;
        int rotOrng = 0;

        for (int i=0; i < rows; i++){
            for (int j=0; j < cols; j++){
                if(grid[i][j] == 2){ //First, we'll add all the rotten oranges in a queue
                    q.add(new Edge(i, j, 0));
                    rotOrng++; 
                    totalOrng++;
                }
                else if(grid[i][j] == 1){
                    totalOrng++;
                }
            }
        }
        while(!q.isEmpty()){
            Edge curr = q.remove();
            //Second, we'll add all the adjacent oranges, if they exist, in queue, as soon as we remove a perticular orange
            int i = curr.src;
            int j = curr.dest;
            int time = curr.time;

            if(i>0){//Top Oranges
                if(grid[i-1][j] == 1){ //if the orange is fresh, only then it'll be rotted
                    q.add(new Edge(i-1, j, time+1));
                    grid[i-1][j] = 2; //as soon as we add this to queue, or make it rotted, we don't want to modify it later, so, we are assigning 2 to it.
                    rotOrng++;
                }
                
            }
            if(i<rows-1){ //bottom Oranges
            if(grid[i+1][j] == 1){
                q.add(new Edge(i+1, j, time+1));
                grid[i+1][j] = 2;
                rotOrng++;
            }
            }
            if(j>0){ //Left Oranges
            if(grid[i][j-1] == 1){
                q.add(new Edge(i, j-1, time+1));
                grid[i][j-1] = 2;
                rotOrng++;
            }
            }
            if(j<cols-1){ //Right Oranges
            if(grid[i][j+1] == 1){
                q.add(new Edge(i, j+1, time+1));
                grid[i][j+1] = 2;
                rotOrng++;
            }
            }
            //We are using 'if' 4 times, because, if i,j has all 4 sides, we need to add all of them
            min = time;
        }

        if(rotOrng != totalOrng){ //it'll be true, if any orange is never rotten
            return -1;
        }
        return min;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-17 20:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:11 UTC
Labels: LCUS, problem, Waiting for Reply

**Comment by SagarDNG** [comment] 2023-07-21 00:36
Hey, @LC-Pam, can you please explain what exactly is needed?
I think the code satisfies all the test cases.
