### ISSUE TITLE
JS Spread Operator returning wrong output

### ISSUE THREAD

**Issue by Ajay-K-Singh** [LeetCode-Feedback/LeetCode-Feedback#7419] opened 2022-05-24 19:20 UTC
#### Your LeetCode username
Sammi-93

- [ ] Language Support

#### Description of the bug
JS Spread operators return wrong output for the Leetcode Judge.

#### Code you used for Submit/Run operation
```
var rotate = function(nums, k) {
   const splicedArr = nums.splice(nums.length - k);
   return [...splicedArr, ...nums];
};
```

#### Expected behavior
It should return correct output of the function to the judge.

This issue is related to support of ES6 spread operators for Leetcode judge.

**Comment by LC-Pam** [comment] 2022-05-25 18:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.
The code and language you submitted to reach this result.
The test caes.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-26 17:46
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-26 17:46 UTC
Labels: LCUS, problem
