### ISSUE TITLE
Test case in correct for Water and Jug problem 

### ISSUE THREAD

**Issue by addyv12** [LeetCode-Feedback/LeetCode-Feedback#18198] opened 2023-11-21 15:52 UTC
### LeetCode Username
adhiamol. 

### Problem number, title, and link
365. Water and Jug Problem https://leetcode.com/problems/water-and-jug-problem/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

For the given input  below, it should be returning false  as its not possible to measure 6. But the testcase's expected solution is "true" . This is incorrect.
jugCapacity1 = 34, jugCapacity2 =5 and targetCapacity = 6 

### Language used for code
java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Additional context
For input,  jugCapacity1 = 34, jugCapacity2 =5 and targetCapacity = 6 it should return false

**Comment by LC-Pam** [comment] 2023-11-21 19:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:15 UTC
Labels: Waiting for Reply
