### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by vishal2801** [LeetCode-Feedback/LeetCode-Feedback#12762] opened 2023-04-04 14:49 UTC
#### Your LeetCode username
vishal2801

#### Category of the bug
Missing Test Cases 

#### Description of the bug

There is no test case where the divisor may be zero.
If the user mistakenly does not optimize the code by a condition where the divisor equals to zero.

#### Code you used for Submit/Run operation

```
class Solution {
    public int divide(int dividend, int divisor) {
        if (divisor == 0){
            return 0;
        }
        if( dividend == Integer.MIN_VALUE && divisor == -1){
            return Integer.MAX_VALUE;
        }
        int result = dividend / divisor;
        return result;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Suppose in user input the user takes the divisor as zero then there should be an error because we cannot divide a number with zero.
So there should be a case where the divisor should be kept as zero.

**Comment by LC-Pam** [comment] 2023-04-05 18:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-07 18:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-07 18:04 UTC
Labels: LCUS, problem
