### ISSUE TITLE
88. Merge Sorted Array - Java - Nums1 is getting printed in the console for output verification

### ISSUE THREAD

**Issue by mvikram93** [LeetCode-Feedback/LeetCode-Feedback#16285] opened 2023-09-08 20:55 UTC
#### Your LeetCode username

mvikram93

#### Category of the bug
- [ ] Question
- [*] Solution
- [*] Language - Java
- [ ] Missing Test Cases 

#### Description of the bug

The output that is being printed in the console is considering the nums1 array only. And even if we try to overwrite the array value. Even then it not getting overwritten. In my local machine, i am getting the expected output for the same code.

#### Code you used for Submit/Run operation

class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int[] arr = new int[m+n];
        for(int i=0;i<m;i++){
            arr[i]=nums1[i];
        }
          for(int j=0;j<n;j++){
            arr[m+j]=nums2[j];
        }
        int temp=0;
        for(int i=0;i<arr.length;i++){
            for(int j=i+1;j<arr.length;j++){
                if(arr[i]>arr[j]){
                    temp=arr[i];
                    arr[i]=arr[j];
                    arr[j]=temp;
                }
            }
        }
        nums1 = arr;
        arr=null;
     System.out.println( Arrays.toString(nums1));
    }
}

#### Language used for code

Java

#### Expected behavior

The testcase is failing even though the stdout and the expected are same. 

#### Screenshots

Test Case 1:

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10028652/4dbac38b-f185-46b9-9a11-4ff1e73ff1b3)

**Comment by LC-Pam** [comment] 2023-09-11 20:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:10 UTC
Labels: Waiting for Reply
