### ISSUE TITLE
Invalid Submission Case - 346. Moving Average from Data Stream

### ISSUE THREAD

**Issue by andrewjunggg** [LeetCode-Feedback/LeetCode-Feedback#16572] opened 2023-09-21 01:51 UTC
#### Your LeetCode username

andrewjunggg

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was trying to figure out why my code was rejected when submitted; however, running the same code with the same test case showed me a different result. Take a look at these screenshots:

Wrong answer when submitted:
<img width="1511" alt="Wrong answer when submitted" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20850823/f65d7479-63dd-42a1-93e2-2db44da172cd">

Answer accepted when running the code without submission:
<img width="1511" alt="Answer accepted when running the code without submission" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20850823/eea47d59-86a0-4f20-a804-e7dd8d92c74c">

#### Code you used for Submit/Run operation

```python
import collections

class MovingAverage:
    size = 0
    queue = collections.deque()

    def __init__(self, size: int):
        self.size = size

    def next(self, val: int) -> float:
        while len(self.queue) >= self.size:
            self.queue.popleft()
            
        self.queue.append(val)
        # print(sum(self.queue))
        # print(len(self.queue))
        return sum(self.queue) / len(self.queue)
            


# Your MovingAverage object will be instantiated and called as such:
# obj = MovingAverage(size)
# param_1 = obj.next(val)
```

#### Language used for code

Python3

#### Expected behavior

The submission should accept my code because it is accepted when I run the code.

#### Screenshots

Screenshots provided on "Description of the bug" section

**Comment by LC-Pam** [comment] 2023-09-21 19:23
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-09-21 19:23 UTC
