### ISSUE TITLE
Missing Test Case - 1095. Find in Mountain Array

### ISSUE THREAD

**Issue by P4ul19** [LeetCode-Feedback/LeetCode-Feedback#17195] opened 2023-10-13 00:39 UTC
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

/**
 * // This is MountainArray's API interface.
 * // You should not implement it, or speculate about its implementation
 * interface MountainArray {
 *     public int get(int index);
 *     public int length();
 * }
 */
 
class Solution {
    public int findInMountainArray(int target, MountainArray mountainArr) {
        int n = mountainArr.length();
        int left = 0, right = n - 1;

        // Step 1: Find the peak index
        while (left < right) {
            int mid = left + (right - left) / 2;
            int midValue = mountainArr.get(mid);
            int midNextValue = mountainArr.get(mid + 1);

            if (midValue < midNextValue) {
                left = mid + 1;
            } else {
                right = mid;
            }
        }
        int peakIndex = left;

        // Step 2: Search in the left subarray (ascending part)
        left = 0;
        right = peakIndex;
        while (left <= right) {
            int mid = left + (right - left) / 2;
            int midValue = mountainArr.get(mid);

            if (midValue == target) {
                return mid;
            } else if (midValue < target) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }

        // Step 3: Search in the right subarray (descending part)
        left = peakIndex;
        right = n - 1;
        while (left <= right) {
            int mid = left + (right - left) / 2;
            int midValue = mountainArr.get(mid);

            if (midValue == target) {
                return mid;
            } else if (midValue < target) {
                right = mid - 1;
            } else {
                left = mid + 1;
            }
        }

        return -1; // Target not found
    }
}

**Comment by LC-Pam** [comment] 2023-10-13 19:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-17 20:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-17 20:57 UTC
Labels: Waiting for Reply
