### ISSUE TITLE
Missing Test Case - 265. Paint House II

### ISSUE THREAD

**Issue by jtwangac** [LeetCode-Feedback/LeetCode-Feedback#4519] opened 2021-08-16 00:18 UTC
#### Your LeetCode username

jtwangac@gmail.com

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question description is not precise:
The ranges of n and k specified in the questions are n>=1 and k>=1

However, when n>1 and k=1, there exists no valid solution for painting all the houses according to the question description. Yet, the description neither excludes such case nor indicates what should be the expected output in this case. 

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior

The description should either exclude the above case or indicate the expected output under this case.

**Comment by ampanasiuk** [comment] 2021-08-16 08:38
Duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/4516

**Closed** 2021-08-16 19:01 UTC
