### ISSUE TITLE
Missing Test Case - 1773. Count Items Matching a Rule

### ISSUE THREAD

**Issue by Srijan-D** [LeetCode-Feedback/LeetCode-Feedback#10536] opened 2022-12-25 11:23 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 1773. Count Items Matching a Rule
```class Solution {
    public static int countMatches(List<List<String>> items, String ruleKey, String ruleValue) {
        int count = 0;
        switch (ruleKey) {
            case "type":
                for (int i = 0; i < items.size(); i++) {
                    if (items.get(i).get(0) == ruleValue) {
                        count++;
                    }
                }
                break;
            case "color":
                for (int i = 0; i < items.size(); i++) {
                    if (items.get(i).get(1) == ruleValue) {
                        count++;
                    }
                }
                break;
            case "name":
                for (int i = 0; i < items.size(); i++) {
                    if (items.get(i).get(2) == ruleValue) {
                        count++;
                    }
                }
                break;
        }
        return count;
    }
}```

#### Language used for code
<!-- JAVA -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- 
![image](
https://user-images.githubusercontent.com/87586713/209465969-b53931aa-96ea-425b-8ca9-1e47cc4e85f3.png
)
-->



#### Additional context
<!-- code is working in the right way in my machine -->

**Comment by LC-Pam** [comment] 2022-12-26 19:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-28 20:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-28 20:45 UTC
Labels: LCUS, problem
