### ISSUE TITLE
Strange behaviour of running code

### ISSUE THREAD

**Issue by Arif-Khalid** [LeetCode-Feedback/LeetCode-Feedback#17318] opened 2023-10-19 03:32 UTC
#### Your LeetCode username

arifkhalid99

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I run the code below, If 

This strange behaviour I cannot seem to replicate without displaying my almost complete answer. So with the code below (I know its not fully correct but the bug is memory access error when there shouldn't be), somehow the outermost while loop does NOT break even when i < 0 or j < 0. I have tried printing i and j and seen at the bottom of the outer loop they are less than 0, yet the outer loop still continues.
The most strange part is I then recreated this code part by part and if you comment out the line below the comment // COMMENTING OUT LINE BELOW SOLVES THE LOOP, then it works fine and the loop ends correctly. Note that even if I check i < 0 || j < 0 at the bottom of the outer loop and use the break keyword it DOES NOT BREAK.
I also tested this code locally and there are no errors. Errors are only present when submitting to leetcode.
#### Code you used for Submit/Run operation

```
// Backspace Compare
class Solution {
public:
    bool backspaceCompare(string& s, string& t) {
        int i = s.length() - 1;
        int j = t.length() - 1;
        int numS = 0;
        int numT = 0;
        while(i >= 0 && j >= 0){
            while(i >= 0 && (numS > 0 || s[i] == '#')){
                if(s[i] == '#'){
                    ++numS;
                }else{
                    --numS;
                }
                --i;
            }
            while(j >= 0 && (numT > 0 || t[j] == '#')){
                if(t[j] == '#'){
                    ++numT;
                }else{
                    --numT;
                }
                --j;
            }
            // COMMENTING OUT LINE BELOW SOLVES THE LOOP
            if(s[i] != t[j]) return false;
            --i;
            --j;
        }
        return true;
    }
}
```

#### Language used for code

C++

#### Expected behavior

The outer loop breaks when i < 0 || j < 0

#### Screenshots

Fails on first test case
<img width="749" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88131400/3a3b8b78-56a0-48b8-b9f7-9f1f814d066b">

**Comment by LC-Pam** [comment] 2023-10-19 17:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number or name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-23 19:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-23 19:07 UTC
Labels: Waiting for Reply
