### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by sarveshwar22** [LeetCode-Feedback/LeetCode-Feedback#8554] opened 2022-08-06 18:18 UTC
#### Your LeetCode username

mahapatro

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ Y] Missing Test Cases 

#### Description of the bug

There is a missing test case
125
15
60
The answer in this case should be 3.
```
int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        return ceil(log(buckets)/log(minutesToTest/minutesToDie +1));
  }
```

 This code is returning 4, which is accepted, but should give Wrong Answer as correct answer is 3.
The correct solution is
```
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int res=0;
        while(pow(minutesToTest/minutesToDie+1,res)<buckets)
            res++;
        return res;
    }
};
```
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by 152334H** [comment] 2022-08-06 21:41
This is a duplicate of #8551, please ignore this

**Closed** 2022-08-08 18:27 UTC
