### ISSUE TITLE
Missing Test Cases - 20. Valid Parentheses

### ISSUE THREAD

**Issue by johnspin** [LeetCode-Feedback/LeetCode-Feedback#16725] opened 2023-09-26 18:23 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Missing Testcases

Expected Fails
null
"" (empty string)
" " (space)
"abcd"
"()))"
"(([[))"
"{}[]()"
"[{(("
"("
")"
"((())))()((())))"
"((((()))"
"((()))))"

Expected passes (longer and varied strings)
"{}[]()"
"((()))()((()))"
"((())()((())))"
"(((((((((((())))))))))))"
"({}[((())){}])"
"{{}[()][]}"

**Comment by LC-Pam** [comment] 2023-09-26 19:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by johnspin** [comment] 2023-09-26 21:44
The missing test cases are listed in the bug. I have also included them here:

Missing Testcases

Expected Fails:
null
"" (empty string)
" " (space)
"abcd"
"()))"
"(([[))"
"{}"
"[{(("
"("
")"
"((())))()((())))"
"((((()))"
"((()))))"

Expected passes
"{}"
"((()))()((()))"
"((())()((())))"
"(((((((((((())))))))))))"
"({}[((())){}])", "{{}[()][]}"

**Comment by johnspin** [comment] 2023-09-27 01:25
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link. The missing test case.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

The missing test cases are listed in the bug. I have also included them here:

Missing Testcases

Expected Fails:
null
"" (empty string)
" " (space)
"abcd"
"()))"
"(([[))"
"{}"
"[{(("
"("
")"
"((())))()((())))"
"((((()))"
"((()))))"

Expected passes (longer and varied strings):
"{}"
"((()))()((()))"
"((())()((())))"
"(((((((((((())))))))))))"
"({}[((())){}])"
"{{}[()][]}"

**Comment by LC-Pam** [comment] 2023-09-27 18:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-28 16:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-28 16:04 UTC
Labels: Waiting for Reply
