### ISSUE TITLE
Missing Test Case - 1148. Article Views I

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#16856] opened 2023-10-02 05:19 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

- Solution

#### Code you used for Submit/Run operation

Write a solution to find all the authors that viewed at least one of their own articles.
Return the result table sorted by id in ascending order.
```
// MS Sql Server
Select distinct author_id as id from Views where author_id=viewer_id 
```

#### Language used for code

MS Sql Server

#### Screenshots

![Screenshot (68)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/6e2beb52-ef1d-4b3a-ae5a-33639241065f)

**Comment by LC-Pam** [comment] 2023-10-03 18:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The BUG or The Issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:23 UTC
Labels: Waiting for Reply

**Comment by iamnidhisha** [comment] 2023-10-08 17:19
Yes off

> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The BUG or The Issue.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

The BUG
