### ISSUE TITLE
Missing Test Case - 939. Minimum Area Rectangle

### ISSUE THREAD

**Issue by jikuma** [LeetCode-Feedback/LeetCode-Feedback#7581] opened 2022-06-03 03:20 UTC
#### Your LeetCode username
pradeepjsr05

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
Below test case missing
[[0,0],[0,1],[0,3],[1,0],[1,2],[1,3]]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment] 2022-06-03 04:21
What is the code that can get accepted but fails on the test case?

**Comment by jikuma** [comment] 2022-06-03 16:53
`class Solution {
private:
    map<int,set<int>> xs;
public:
    int minAreaRect(vector<vector<int>>& points) {
        for(const vector<int>& point : points) {
            xs[point[0]].insert(point[1]);
        }
        
        int ans = INT_MAX;
        for(const auto& p : xs) {
            const set<int>& ys = p.second;
            
            for(auto it = ys.begin(); it != prev(ys.end(),1); it++){
                int y1 = *it;
                int y2 = *next(it,1);

                for(const auto& p2 : xs) {
                    if(p2.first != p.first and p2.second.count(y2) and p2.second.count(y1)) {
                        ans = min(ans, (y2-y1) * abs(p2.first - p.first));
                    }
                }
            }
        }
        
        return ans == INT_MAX ? 0 : ans;
    }
};`

**Comment by LC-Pam** [comment] 2022-06-03 17:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 01:06
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 01:06 UTC
Labels: LCUS, problem
