### ISSUE TITLE
435. Non-overlapping Intervals -- DP Solutions are not being accepted

### ISSUE THREAD

**Issue by mayanksha** [LeetCode-Feedback/LeetCode-Feedback#7928] opened 2022-06-27 12:30 UTC
#### Your LeetCode username
mayank8019

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution to this problem https://leetcode.com/problems/non-overlapping-intervals/solution/ mentions that the DP solutions with O(N^2) complexity will be accepted but the given reference solution no.s 2, 3, 4 themselves are not being accepted.

#### Code you used for Submit/Run operation

```java
class Solution {
  class myComparator implements Comparator<int[]> {
    public int compare(int[] a, int[] b) {
      return a[1] - b[1];
    }
  }

  public int eraseOverlapIntervals(int[][] intervals) {
    if (intervals.length == 0) {
      return 0;
    }
    Arrays.sort(intervals, new myComparator());
    int end = intervals[0][1], prev = 0, count = 0;
    for (int i = 1; i < intervals.length; i++) {
      if (intervals[prev][1] > intervals[i][0]) {
        if (intervals[prev][1] > intervals[i][1]) {
          prev = i;
        }
        count++;
      } else {
        prev = i;
      }
    }
    return count;
  }
}
```

#### Expected behavior
The O(N^2) solution mentioned above should get accepted since it's a valid solution and the solution article too mentions that the DP solution is supposed to be accepted.

#### Additional context

Question: https://leetcode.com/problems/non-overlapping-intervals/

**Comment by LC-Pam** [comment] 2022-06-28 17:05
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment] 2022-06-29 23:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-04 03:41
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-04 03:41 UTC
Labels: LCUS, solution
