### ISSUE TITLE
Editorial Bug: 150. Evaluate Reverse Polish Notation 

### ISSUE THREAD

**Issue by ronghuang0** [LeetCode-Feedback/LeetCode-Feedback#19876] opened 2024-01-30 19:35 UTC
### LeetCode Username
ronghuang0

### Problem number, title, and link

150. Evaluate Reverse Polish Notation

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

The python editorial for approach 1 fails the test case of an array of size 1. For ex: ['18'].
When returning the result we need to use int() to account for the case of input array of length 1.

### Language used for code

Python

**Comment by LC-Pam** [comment] 2024-01-31 16:58
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by ronghuang0** [comment] 2024-01-31 18:27
`def evalRPN(self, tokens: List[str]) -> int:

        operations = {
            "+": lambda a, b: a + b,
            "-": lambda a, b: a - b,
            "/": lambda a, b: int(a / b),
            "*": lambda a, b: a * b
        }
        
        current_position = 0
        
        while len(tokens) > 1:
            
            # Move the current position pointer to the next operator.
            while tokens[current_position] not in "+-*/":
                current_position += 1
        
            # Extract the operator and numbers from the list.
            operator = tokens[current_position]
            number_1 = int(tokens[current_position - 2])
            number_2 = int(tokens[current_position - 1])
            
            # Calculate the result to overwrite the operator with.
            operation = operations[operator]
            tokens[current_position] = operation(number_1, number_2)
            
            # Remove the numbers and move the pointer to the position
            # after the new number we just added.
            tokens.pop(current_position - 2)
            tokens.pop(current_position - 2)
            current_position -= 1
        
        return tokens[0]
`

**Comment by syziel1** [comment] 2024-01-31 20:05
Yes, I also had to use int() returning the result of ['18'].
## My code:
`    def negative_sign_division(self, a, b):
        if a*b<0:
            return -int(-a/b)
        else:
            return int(a/b)

    def evalRPN(self, tokens):
        """
        :type tokens: List[str]
        :rtype: int
        """
        operations = {
            "+": lambda a, b: a + b,
            "-": lambda a, b: a - b,
            "/": lambda a, b: self.negative_sign_division(a, b), # not just a/b
                                # because python's division is different from C++
                                # e.g. -1/2 = -1 in python, but -1/2 = 0 in C++
            "*": lambda a, b: a * b
        }
        cur = 0
        while len(tokens) > 1:
            if tokens[cur] in operations:
                tokens[cur - 2] = operations[tokens[cur]](int(tokens[cur - 2]), int(tokens[cur - 1]))
                del tokens[cur - 1:cur + 1]
                cur -= 2
            cur += 1
        return int(tokens[0])
`

**Comment by ronghuang0** [comment] 2024-02-02 17:36
> Hello,
> 
> Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
> 
> The code submission link you submitted led to the observed result.
> 
> Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!
> 
> Best regards LeetCode Support Team

replied above

**Comment by LC-Pam** [comment] 2024-02-07 21:09
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-02-18 02:05
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Closed by LC-Pam** 2024-02-18 02:05 UTC
Labels: LCUS, solution, watchlist
