### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Shreyan1** [LeetCode-Feedback/LeetCode-Feedback#18119] opened 2023-11-17 13:59 UTC
### LeetCode Username
shreyanbasuray

### Problem number, title, and link

2.  Median of Two Sorted Arrays - https://leetcode.com/problems/median-of-two-sorted-arrays/

### Category of the bug
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Test Case Addition
nums1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 1000  # Array with 10,000 elements
nums2 = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20] * 1000  # Array with 10,000 elements

In this case, the input arrays are large, and the merged array has 20,000 elements. The sorted() function if used will consume memory proportional to the size of the merged array, and for very large inputs, this could lead to memory-related issues. To handle such cases we need to use the binary search approach, which has a time complexity of O(log(min(m, n))).

**Comment by LC-Pam** [comment] 2023-11-17 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:09 UTC
Labels: Waiting for Reply
