### ISSUE TITLE
Missing Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by Ragul-Muthukumar** [LeetCode-Feedback/LeetCode-Feedback#18540] opened 2023-12-08 11:17 UTC
class Solution {

    /**
     * @param String $s
     * @return Boolean
     */
    function isPalindrome($s) {
        $letter = preg_replace("/[^a-zA-Z]/", "", $s);
        $arr = str_split(strtolower($letter));
        if(count($arr) == 2){
            if($arr[0] != $arr[1]){
                return false;
            }
        }
        if(count($arr) == 1){
            return true;
        }
        if(count($arr) == 0){
            return false;
        }
        for($i = 0; $i < count($arr); $i++){
            if($arr[$i] != $arr[(count($arr) -1)-$i]){
                return false;
            }
        }
        return true;
    }
}

listen this is my code but compiler says output is wrong for "OP", but which is right;check this please

**Comment by LC-Pam** [comment] 2023-12-12 23:07
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code programming language you submitted led to the observed result.
or 
The code submission link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-19 18:12
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-19 18:12 UTC
Labels: Waiting for Reply
