### ISSUE TITLE
Missing Test Case - 166. Fraction to Recurring Decimal

### ISSUE THREAD

**Issue by IanPengTW** [LeetCode-Feedback/LeetCode-Feedback#8394] opened 2022-07-27 16:21 UTC
Wrong test case accepted.
Accepted
Runtime: 0 ms
Your input
1
3
Output
"-0.(3)"
Expected
"0.(3)"

**Comment by LC-Pam** [comment] 2022-07-27 17:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:54
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:54 UTC
Labels: LCUS, problem
