### ISSUE TITLE
Missing Test Case - 1327. List the Products Ordered in a Period

### ISSUE THREAD

**Issue by Bonrey** [LeetCode-Feedback/LeetCode-Feedback#12757] opened 2023-04-04 10:46 UTC
#### Your LeetCode username
Michael_V

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case

#### Code you used for Submit/Run operation

```
SELECT product_name, SUM(unit) AS unit
FROM orders
JOIN products USING(product_id)
WHERE EXTRACT(MONTH FROM order_date) = 2
GROUP BY product_name
HAVING unit >= 100
```

#### Language used for code
MySQL

#### Expected behavior
The solution above should give wrong results for the years other than 2020. For example, for the following test case

```
Products =
| product_id | product_name          | product_category |
| ---------- | --------------------- | ---------------- |
| 1          | Leetcode Solutions    | Book             |
| 2          | Jewels of Stringology | Book             |
| 3          | HP                    | Laptop           |
| 4          | Lenovo                | Laptop           |
| 5          | Leetcode Kit          | T-shirt          |
```

```
Orders =
| product_id | order_date | unit |
| ---------- | ---------- | ---- |
| 1          | 2020-02-05 | 60   |
| 1          | 2020-02-10 | 70   |
| 2          | 2020-01-18 | 30   |
| 2          | 2020-02-11 | 80   |
| 3          | 2020-02-17 | 2    |
| 3          | 2020-02-24 | 3    |
| 4          | 2020-03-01 | 20   |
| 4          | 2020-03-04 | 30   |
| 4          | 2020-03-04 | 60   |
| 5          | 2021-02-25 | 50   |
| 5          | 2020-02-27 | 50   |
| 5          | 2020-03-01 | 50   |
```

the output should be

```
| product_name       | unit |
| ------------------ | ---- |
| Leetcode Solutions | 130  |

```

but my code returns

```
| product_name       | unit |
| ------------------ | ---- |
| Leetcode Solutions | 130  |
| Leetcode Kit       | 100  |
```

i.e., my solution also counts `Leetcode Kit` which was bought is February of **2021**.

**Comment by LC-Pam** [comment] 2023-04-04 21:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-07 18:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-07 18:04 UTC
Labels: LCUS, problem
