### ISSUE TITLE
Error in question 26, Remove Duplicates from Sorted Array.

### ISSUE THREAD

**Issue by raghav991144** [LeetCode-Feedback/LeetCode-Feedback#10715] opened 2023-01-03 05:56 UTC
#### [ ] Solution 
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### '''
// Remove Duplicates from Sorted Array
  class Solution {
    public int removeDuplicates(int[] nums) {
        int count = 0;
     HashMap<Integer,Integer> map = new HashMap<Integer,Integer>();
     for(int i=0;i<nums.length;i++){
         if(!map.containsKey(nums[i])){
           map.put(nums[i],i);
           count++;
         }
     }
     return count;

  
    }
}
'''

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-01-04 03:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-07 15:35
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-07 15:35 UTC
Labels: LCUS, problem
