### ISSUE TITLE
Invalid Test Case - 120. Triangle

### ISSUE THREAD

**Issue by kasienna** [LeetCode-Feedback/LeetCode-Feedback#3195] opened 2021-04-22 13:34 UTC
#### Your LeetCode username
kasienna

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I think test case [[-1],[2,3],[1,-1,-3]] is wrong - it expects -1 whlist proper sum is 0 ((-1) + 2 + (-1))

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumTotal(List<List<Integer>> triangle) {
        Iterator<List<Integer>> rowIterator = triangle.iterator();
        List<Integer> row = triangle.get(0);
        int sum = 0;
        int index = 0;
        do {
            row = rowIterator.next();
            int stepLeft = row.get(index);
            int stepRight = index < row.size() - 1 ? row.get(index+1) : stepLeft;
            if(stepLeft <= stepRight){
                sum += stepLeft;
            } else {
                index = index + 1;
                sum += stepRight;
            }
        } while(rowIterator.hasNext());

        return sum;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I expect that it would pass - it passes on examples from task description. It doesn't pass for other test cases as I can see, but this one does not add up properly

**Comment by deepeshgodara** [comment] 2021-04-22 16:10
Hi kasienna the test case for which you opened the issue is not wrong
the test case mentions the input as  [[-1],[2,3],[1,-1,-3]]
where the triangle translates to as follow
    -1
  2     3
1  -1   -3

and if you go via the path (-1) -> (3) -> (-3) sum totals to -1 and which is correct
or in terms of index (row,column) => (0,0)->(1,1)->(2,2)

The issue with your code is that you are simply trying a greedy approach you are simply moving to the immediate smaller element, instead of building the path having the least total sum.

If you are having any issue you can have a look at my code

for ease of understanding, I have also included the output of the dp array used
dp[row][col] provides us the information about the least sum of the sub triangle starting from row , col
 class Solution{
	public static int minimumTotal(List<List<Integer>> triangle) {
		if (triangle.size() == 0 || (triangle.size() == 1 && triangle.get(0).size() == 0)) {
			return 0;
		}
		return helper(triangle);

	}

	private static int helper(List<List<Integer>> triangle) {
		int dp[][] = new int[triangle.size() + 1][triangle.size() + 1];
		for (int row = triangle.size() - 1; row >= 0; row--) {
			List<Integer> curr_row = triangle.get(row);
			for (int col = curr_row.size() - 1; col >= 0; col--) {
				if (row == triangle.size() - 1) {
					dp[row][col] = curr_row.get(col);
				} else {
					int item = curr_row.get(col);
					dp[row][col] = min(dp[row + 1][col], dp[row + 1][col + 1]) + item;
				}

			}

		}
		for (int i = 0; i < dp.length; i++) {
			System.out.println(Arrays.toString(dp[i]));
		}
		return dp[0][0];
	}}

**Comment by LC-Pamela** [comment] 2021-04-22 19:17
Hi @kasienna 
Thank you for reaching out to us. I recommend that you read the question again or raise your question in the problem's discussion tab. The question was raised and answered many times by the LeetCoders.

**Closed by LC-Pamela** 2021-04-22 19:17 UTC
