### ISSUE TITLE
Missing Test Case - 437

### ISSUE THREAD

**Issue by MargieMo** [LeetCode-Feedback/LeetCode-Feedback#8340] opened 2022-07-25 22:05 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
public class Solution {
    public int subarraySum(int[] nums, int k) {
        int count = 0, currSum = 0;
        HashMap<Integer, Integer> h = new HashMap();
        
        for (int num : nums) {
            // current prefix sum
            currSum += num;
            
            // situation 1:  
            // continuous subarray starts 
            // from the beginning of the array
            if (currSum == k)
                count++;
            
            // situation 2:
            // number of times the curr_sum − k has occured already, 
            // determines the number of times a subarray with sum k 
            // has occured upto the current index
            count += h.getOrDefault(currSum - k, 0);
            
            // add the current sum
            h.put(currSum, h.getOrDefault(currSum, 0) + 1);    
        }
                
        return count;
    }
}
```

#### Expected behavior

Solution getting wrong answer, missing test case of:
[1000000000,1000000000,null,294967296,null,1000000000,null,1000000000,null,1000000000]
0

**Comment by LC-Pam** [comment] 2022-07-26 01:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by MargieMo** [comment] 2022-07-26 15:52
Java

**Comment by LC-Pam** [comment] 2022-07-26 17:00
Hi there,
When we test your code, we received Compile Error, if you have code submission accepted link, please send it to us, then we can add the missing test case.[
https://leetcode.com/submissions/detail/757390932/

**Comment by LC-Pam** [comment] 2022-07-29 17:53
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:53 UTC
Labels: LCUS, problem
