### ISSUE TITLE
Missing Test Case - 1800. Maximum Ascending Subarray Sum

### ISSUE THREAD

**Issue by gaurika05** [LeetCode-Feedback/LeetCode-Feedback#12316] opened 2023-03-12 17:57 UTC
#### Your LeetCode username
<gaurika05>

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Adding a test case which seems possible and important.
 nums=[50,49,48,47,46]

Now what will be the answer to this testcase?

#### Code you used for Submit/Run operation
// Two Sum
class Solution:
    def maxAscendingSum(self, nums: List[int]) -> int:
        res = 0
        sum = 0
        for i in range(len(nums)):
            if i == 0 or nums[i - 1] < nums[i]:
                sum += nums[i]
            else:
                sum = nums[i]
            res = max(res, sum)
        return res

#### Language used for code
Python3

#### Expected behavior
//nil

#### Screenshots
//nil

**Comment by LC-Pam** [comment] 2023-03-13 17:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-20 17:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-20 17:25 UTC
Labels: LCUS, problem
