### ISSUE TITLE
Missing Test Case - 75. Sort Colors

### ISSUE THREAD

**Issue by shreyam87** [LeetCode-Feedback/LeetCode-Feedback#16054] opened 2023-08-31 04:14 UTC
Hey, I added a new test case...
 nums=[ 2 0 2 1 1 0]
Output=[0 0 1 1 2 2 ]
Expected=[0 0 1 1 2 2 ]

**Comment by LC-Pam** [comment] 2023-08-31 18:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:52 UTC
Labels: Waiting for Reply
