### ISSUE TITLE
Misspelled  

### ISSUE THREAD

**Issue by Abhitator216** [LeetCode-Feedback/LeetCode-Feedback#7877] opened 2022-06-23 07:59 UTC
#### Category of the bug
- [ ] Question
- [🐞] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution section of Approach 2: Recursion with Memoization their is a spelling mistake
of word **already** by _aleady_

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/89402434/175246311-e93d5d07-e6b2-467d-b008-eb883e75b313.png)

#### Additional context

just replace that word by *already*

**Comment by LC-Pam** [comment] 2022-06-24 04:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Problem name
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-27 16:43
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-27 16:43 UTC
Labels: LCUS, solution
