### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Shubhi143** [LeetCode-Feedback/LeetCode-Feedback#14799] opened 2023-07-15 18:03 UTC
#### Your LeetCode username
Shubhi_Gupta1531

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
a missing testcase when x=0 is not available

```
// Palindrome Number
class Solution {
public:
    bool isPalindrome(int x) {
        if (x < 0 || (x != 0 && x % 10 == 0)) {
            return false;
        }

        int reversed = 0;
        while (x > reversed) {
            reversed = reversed * 10 + x % 10;
            x /= 10;
        }
        return (x == reversed) || (x == reversed / 10);
    }
};
```

**Comment by LC-Pam** [comment] 2023-07-17 20:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:09 UTC
Labels: LCUS, problem, Waiting for Reply
