### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by SarthakJaindebugger** [LeetCode-Feedback/LeetCode-Feedback#13592] opened 2023-05-20 19:18 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

class Solution():
    def removeDuplicates(self, nums):
        
        new_nums = []
        
        for i in nums:
            if i not in new_nums:
                new_nums.append(i)
                
        print(len(new_nums))

**Comment by SarthakJaindebugger** [comment] 2023-05-20 19:19
This solution works perfectly, pls check:

class Solution():
    def removeDuplicates(self, nums):
        
        new_nums = []
        
        for i in nums:
            if i not in new_nums:
                new_nums.append(i)
                
        print(len(new_nums))

**Comment by LC-Pam** [comment] 2023-05-23 00:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem issue. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-26 19:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-26 19:51 UTC
Labels: LCUS, problem
