### ISSUE TITLE
Editorial Issue - 2485. Find the Pivot Integer

### ISSUE THREAD

**Issue by jsondevers** [LeetCode-Feedback/LeetCode-Feedback#21270] opened 2024-03-13 15:42 UTC
### LeetCode Username

jsondev

### Problem number, title, and link

2485. Find the Pivot Integer https://leetcode.com/problems/find-the-pivot-integer/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the editorial, Approach 5 : Math, there is an example of using arithmetic progression in the following form:

$$
\frac{x(x+1)}{2} = \frac{(x+n)(n-x+1)}{2}
$$

then when the editorial expands both sides of the equation, it becomes:

$$
x + \frac{x^2}{2} = \frac{nx-x^2 + x + n^2 - nx + n}{2}
$$

I believe the left side should be:

$$
\frac{x^2 + x}{2} = \frac{nx-x^2 + x + n^2 - nx + n}{2}
$$

that being $\frac{x(x+1)}{2}$ expanded is $\frac{x^2 + x}{2}$ not $x + \frac{x^2}{2}$

everything that proceeds is correct 

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

<img width="633" alt="Screenshot 2024-03-13 at 11 39 41" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74424054/39ce4783-3917-445e-8513-50d6871f83a1">

**Comment by LC-Pam** [comment] 2024-03-13 16:57
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/21266

**Closed by LC-Pam** 2024-03-13 16:57 UTC
