### ISSUE TITLE
Missing Test Case - 1193. Monthly Transactions I

### ISSUE THREAD

**Issue by k4art** [LeetCode-Feedback/LeetCode-Feedback#14737] opened 2023-07-13 19:03 UTC
#### Your LeetCode username
@kan_a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
> Write an SQL query to find for each month and country, the number of transactions and their total amount, the number of approved transactions and their total amount.

The '2019-01' and '2020-01' months are different, it is common case and the result of RUN for the following test agrees with this.

Input:
```
| id  | country | state    | amount | trans_date |
| --- | ------- | -------- | ------ | ---------- |
| 120 | US      | approved | 2000   | 2019-01-07 |
| 121 | US      | approved | 2000   | 2020-01-07 |
```
Output:
```
| month   | country | trans_count | approved_count | trans_total_amount | approved_total_amount |
| ------- | ------- | ----------- | -------------- | ------------------ | --------------------- |
| 2019-01 | US      | 1           | 1              | 2000               | 2000                  |
| 2020-01 | US      | 1           | 1              | 2000               | 2000                  |
```

But I've found that there is no such a test case for which it matters.

#### Code you used for Submit/Run operation
The following code is accepted after submission (it is _Sample 787 ms submission_ I've found looking at better performant code).
```
# Write your MySQL query statement below
SELECT LEFT(trans_date, 7)  AS month, country,COUNT(id) AS trans_count, SUM(CASE WHEN state = "approved" THEN 1 ELSE 0 END) AS approved_count, SUM(amount) AS trans_total_amount, SUM(CASE 
    WHEN state = 'approved' THEN amount 
    ELSE 0 
    END) AS approved_total_amount
FROM Transactions
GROUP BY MONTH(trans_date) , country
```

Pay attention to the last line `GROUP BY MONTH(trans_date), country`, it is wrong and should be `GROUP BY YEAR(trans_date), MONTH(trans_date), country`.

#### Language used for code
MySQL

#### Expected behavior
This code should fail with `Wrong Answer` instead of being `Accepted`.

**Comment by LC-Pam** [comment] 2023-07-18 18:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Transactions":["id","country","state","amount","trans_date"]},"rows":{"Transactions":[[121,"US","approved",1000,"2018-12-18"],[122,"US","declined",2000,"2018-12-19"],[123,"US","approved",2000,"2019-01-01"],[124,"DE","approved",2000,"2019-01-07"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:08 UTC
Labels: LCUS, problem, Waiting for Reply
