### ISSUE TITLE
O(N) Solution in java instead of O(N^2)

### ISSUE THREAD

**Issue by sara84ez** [LeetCode-Feedback/LeetCode-Feedback#10838] opened 2023-01-08 05:05 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Remove Duplicates from Sorted Array
class Solution {
    public int removeDuplicates(int[] nums) {
       
        if(nums.length == 1){
            return 1;
        }
        int count=0;
        for(int i = 0; i< nums.length-1; i++){
            if(nums[i] != nums[i+1] ){
                nums[count] = nums[i];
                
                 count++;
              //  System.out.println(nums[count]);
                
            }
           if(i == nums.length-2){
                nums[count] = nums[i+1];
                System.out.println(nums[count]);
                count++;
            }
        }
        return count;
        
    }
}

#### Language used for code
<!-- Java-->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-01-09 18:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

 Expected behavior


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:41
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:41 UTC
Labels: LCUS, problem

**Comment by sara84ez** [comment] 2023-01-12 19:33
Hi,

I hope you are doing well!
Unfortunately, I only got this email from Leetcode and not more.

Cheers,
Sara.
