### ISSUE TITLE
Missing Test Case - 904. Fruit Into Baskets

### ISSUE THREAD

**Issue by rayalatrinadh** [LeetCode-Feedback/LeetCode-Feedback#13065] opened 2023-04-21 02:03 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
-  [1,2,0,1]

#### Description of the bug

ans will be the 3
but it given 2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by xelplogoog** [comment] 2023-04-21 04:41
in this task you need to find longest subarray with 2 different numbers. in your example [1,2,0,1] it's 2 (either [1,2] or [2,0] or [0,1])
so the answer is 2.

**Comment by LC-Pam** [comment] 2023-04-21 19:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-24 18:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-24 18:16 UTC
Labels: LCUS, problem
