### ISSUE TITLE
Invalid Test Case - 976. Largest Perimeter Triangle

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2611] opened 2021-03-06 08:06 UTC
#### Your LeetCode username
user8391WG

#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
this testcase is invalid because the triangle side length cannot less than zero but it accepted

#### Code you used for Submit/Run operation

```
class Solution:
    def largestPerimeter(self, A: List[int]) -> int:
        A.sort(reverse=True)
        if len(A) == 3:
            if A[0] + A[1] <= A[2] or A[1] + A[2] <= A[0] or A[0] + A[2] <= A[1]:
                return 0
            return sum(A)
        
        else:
            for i, x in enumerate(A[:-2]):
                if x < A[i+1] + A[i+2]:
                    return x + A[i+1] + A[i+2]
        return 0
```

#### Language used for code
Python 3

#### Expected behavior
Must throw Invalid Testcase Exception

#### Screenshots

![image](https://user-images.githubusercontent.com/57172679/110199848-1d196e00-7e63-11eb-88aa-13067ce17762.png)

**Comment by lc-kay** [comment] 2021-03-08 23:07
<img width="1416" alt="Screen Shot 2021-03-08 at 3 05 41 PM" src="https://user-images.githubusercontent.com/70870126/110393675-d6bd3e00-801f-11eb-8481-bb1c17bf2df1.png">

@alexbprofit I was unable to reproduce the same result as your screenshot. Can you please run the test case with the code again and see if it is still accepted?

**Comment by alexbprofit** [comment] 2021-03-10 05:49
Now, when running this test suite, an error occurs as it should have been originally.
![image](https://user-images.githubusercontent.com/57172679/110582651-2bbe9880-8175-11eb-9f50-84e7b802c1df.png)

**Comment by alexbprofit** [comment] 2021-03-10 05:52
по-видимому это уже исправили.

**Comment by alexbprofit** [comment] 2021-03-10 08:48
[-1,2,-3]
test case which i used.

**Comment by lc-kay** [comment] 2021-03-10 19:37
@alexbprofit Since this has been resolved, I will close this ticket now. Thank you for your time.

**Closed by lc-kay** 2021-03-10 19:37 UTC
Labels: LCUS, watchlist
