### ISSUE TITLE
Wrong test case - 734. Sentence Similarity

### ISSUE THREAD

**Issue by zhangysh1995** [LeetCode-Feedback/LeetCode-Feedback#14010] opened 2023-06-10 11:51 UTC
#### Your LeetCode username

zhangysh1995

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case

#### Description of the bug

In test case No. 39, 
````
["this","summer","thomas","get","actually","actually","rich","and","possess","the","actually","great","and","fine","vehicle","every","morning","he","drives","one","nice","car","around","one","great","city","to","have","single","super","excellent","super","as","his","brunch","but","he","only","eat","single","few","fine","food","as","some","fruits","he","wants","to","eat","an","unique","and","actually","healthy","life"]
["this","summer","thomas","get","very","very","rich","and","possess","the","very","fine","and","well","car","every","morning","he","drives","a","fine","car","around","unique","great","city","to","take","any","really","wonderful","fruits","as","his","breakfast","but","he","only","drink","an","few","excellent","breakfast","as","a","super","he","wants","to","drink","the","some","and","extremely","healthy","life"]
[["good","nice"],["good","excellent"],["good","well"],["good","great"],["fine","nice"],["fine","excellent"],["fine","well"],["fine","great"],["wonderful","nice"],["wonderful","excellent"],["wonderful","well"],["wonderful","great"],["extraordinary","nice"],["extraordinary","excellent"],["extraordinary","well"],["extraordinary","great"],["one","a"],["one","an"],["one","unique"],["one","any"],["single","a"],["single","an"],["single","unique"],["single","any"],["the","a"],["the","an"],["the","unique"],["the","any"],["some","a"],["some","an"],["some","unique"],["some","any"],["car","vehicle"],["car","automobile"],["car","truck"],["auto","vehicle"],["auto","automobile"],["auto","truck"],["wagon","vehicle"],["wagon","automobile"],["wagon","truck"],["have","take"],["have","drink"],["eat","take"],["eat","drink"],["entertain","take"],["entertain","drink"],["meal","lunch"],["meal","dinner"],["meal","breakfast"],["meal","fruits"],["super","lunch"],["super","dinner"],["super","breakfast"],["super","fruits"],["food","lunch"],["food","dinner"],["food","breakfast"],["food","fruits"],["brunch","lunch"],["brunch","dinner"],["brunch","breakfast"],["brunch","fruits"],["own","have"],["own","possess"],["keep","have"],["keep","possess"],["very","super"],["very","actually"],["really","super"],["really","actually"],["extremely","super"],["extremely","actually"]]
````
We have mappings:
````
["super","dinner"],["super","breakfast"],["super","fruits"]
````
which is wrong, because they are not similar. I guess the correct mappings should be:
````
["supper","dinner"],["supper","breakfast"],["supper","fruits"]
````

#### Code you used for Submit/Run operation

This is a language semantic-related issue, no code is necessary.
````
N/A
````

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

<img width="2560" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8340592/1e06139c-38da-48b6-bbae-b1d94aef25cb">

**Comment by LC-Pam** [comment] 2023-06-13 19:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 20:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 20:10 UTC
Labels: LCUS, problem

**Comment by zhangysh1995** [comment] 2023-07-10 11:52
This is my AC page: https://leetcode.cn/submissions/detail/439058673/ (I use the website in Chinese)
