### ISSUE TITLE
Missing Test Case - 1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by tuliusalves** [LeetCode-Feedback/LeetCode-Feedback#16979] opened 2023-10-06 15:34 UTC
#### Category of the bug
- [ ] Question

#### Resolução
//class Solution {
    public int[] runningSum(int[] nums) {
        int aux [] = new int[nums.length];
        int sum=0;
        for(int i=0; i<nums.length;i++){
            sum+=nums[i];
            aux[i]=sum;
        }
        return aux;
    }
}
```

#### Language used for code
<!-- Java -->


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50600361/831aaafd-95a9-4c55-b1e5-2ba0ac270ffb)

**Comment by LC-Pam** [comment] 2023-10-09 18:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:48 UTC
Labels: Waiting for Reply
