### ISSUE TITLE
Missing Test Case - 355. Design Twitter

### ISSUE THREAD

**Issue by ShivKJ** [LeetCode-Feedback/LeetCode-Feedback#9575] opened 2022-10-22 03:06 UTC
#### Your LeetCode username
shivkj001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect test case

#### Description of the bug

In the tweeter design problem, one should not be allowed to unfollow a user if the user was not followed earlier.

#### Code you used for Submit/Run operation

```python
from collections import defaultdict, deque
from heapq import heapify, heappop, heappush
from itertools import chain
from typing import List

MAX_FEED_SIZE = 10


class Twitter:

    def __init__(self):
        self.user_tweet = defaultdict(deque)
        self.followers = defaultdict(set)
        self.ts = 0

    def postTweet(self, user_id: int, tweet_id: int) -> None:
        self.user_tweet[user_id].appendleft((-self.ts, tweet_id))
        self.ts += 1

    def follow(self, follower_id: int, followee_id: int) -> None:
        self.followers[follower_id].add(followee_id)

    def unfollow(self, follower_id: int, followee_id: int) -> None:
        self.followers[follower_id].remove(followee_id)

    def _user_feed_ptr(self, user_id):
        return iter(self.user_tweet[user_id])

    def getNewsFeed(self, user_id: int) -> List[int]:
        users = chain((user_id,), iter(self.followers[user_id]))

        pq = [
            (ts_tweet, feed_ptr) for feed_ptr in map(self._user_feed_ptr, users)
            if (ts_tweet := next(feed_ptr, None)) is not None
        ]

        heapify(pq)

        output = []

        while pq and len(output) < MAX_FEED_SIZE:
            (_, tweet), feed_ptr = heappop(pq)
            output.append(tweet)

            if (next_ts_tweet := next(feed_ptr, None)) is not None:
                heappush(pq, (next_ts_tweet, feed_ptr))

        return output
```

#### Test Case

```
["Twitter","postTweet","postTweet","unfollow","getNewsFeed"]
[[],[1,4],[2,5],[1,2],[1]]
```

As we can see for `unfollow` operation, input argument = [1,2] but user 1 never followed user 2.

**Comment by LC-Pam** [comment] 2022-10-24 17:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 16:05
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 16:05 UTC
Labels: LCUS, problem

**Comment by ShivKJ** [comment] 2022-10-27 16:07
Sorry, did not see the notification in the email.

I used python programming language.
