### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by sairajaa23** [LeetCode-Feedback/LeetCode-Feedback#15204] opened 2023-08-01 14:53 UTC
#### Your LeetCode username

Sairajaa23

#### Category of the bug
- [1,2,2,3,3,3 ] Question
- [1,2,3 ] Solution
- [Python ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        count = {}
        freq = [[] for n in range(len(nums)+1)]
        for n in nums:
            count[n] = 1 + count.get(n, 0)
        for n, c in count.items():
            freq[c].append(n)
        res = []
        for n in range(len(freq)-1, 0 , -1):
            for i in freq[n]:
                res.append(i)
                if len(res) == k:
                   return res
```

**Comment by LC-Pam** [comment] 2023-08-01 19:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-03 18:21
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-03 18:21 UTC
Labels: LCUS, problem, Waiting for Reply
