### ISSUE TITLE
Missing Test Case - 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by Habeeb-MD** [LeetCode-Feedback/LeetCode-Feedback#15087] opened 2023-07-27 13:01 UTC
#### Your LeetCode username
https://leetcode.com/please_kill_me

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Existing testcases does not cover case like below where domain name is wrong : - It is leetcode.commaxcom but it should be leetcode.com.  Also attached the code which will fail for this case but it passed all the system testcases.
Please add below testcase.

Users =
| user_id | name    | mail                       |
| ------- | ------- | -------------------------- |
| 1       | Winston | winston@leetcode.commaxcom |

#### Code you used for Submit/Run operation

```
select * from Users where mail REGEXP '^[a-zA-Z][a-zA-Z0-9-._]*@leetcode[.]com'
```

#### Language used for code
mySQL 

#### Expected behavior

Output for above testcase should be empty table but for above code it is not and the code still passed all the system testcases

**Comment by LC-Pam** [comment] 2023-07-27 18:32
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Users":["user_id","name","mail"]},"rows":{"Users":[[1,"Winston","winston@leetcode.com"],[2,"Jonathan","jonathanisgreat"],[3,"Annabelle","bella-@leetcode.com"],[4,"Sally","sally.come@leetcode.com"],[5,"Marwan","quarz#2020@leetcode.com"],[6,"David","david69@gmail.com"],[7,"Shapiro",".shapo@leetcode.com"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-01 17:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:56 UTC
Labels: LCUS, problem, Waiting for Reply
