### ISSUE TITLE
Missing Test Case - 938. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by cilikchen** [LeetCode-Feedback/LeetCode-Feedback#1423] opened 2020-11-21 16:32 UTC
#### Your LeetCode username
cilik

#### Category of the bug

- [ ] Solution

#### Description of the bug

Using test case below

["7","5","3","1"]
300

The answer should be 36 but Excepted is 84.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Using test case below

["7","5","3","1"]
300

The answer should be 36.

#### Screenshots

<img width="1276" alt="截圖 2020-11-21 下午4 30 39" src="https://user-images.githubusercontent.com/48408321/99882265-07b36780-2c17-11eb-8cbb-93336e6593ff.png">

**Comment by lc-kay** [comment] 2020-11-23 21:56
Duplicate of #1422

**Closed by lc-kay** 2020-11-23 21:56 UTC
