### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by cymande0** [LeetCode-Feedback/LeetCode-Feedback#7023] opened 2022-04-17 03:48 UTC
var lengthOfLongestSubstring = function(s) {
   let max = 0;
   let ch = [];

    for(let i = 0; i < s.length; i++){
      let element = s[i];
      if(ch.includes(element)){
        ch = [];
        for(let j = i; ; j--){   
          ch.push(s[j]);
          if(element === s[j-1]){
            break;
          } 
        }
      } else {
        ch.push(element);
      }
      if(ch.length > max) max = ch.length;
    }
    return max;
};

**Comment by LC-Yani** [comment] 2022-04-20 00:47
Hi @cymande0 ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
What is the missing test?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by LC-Yani** [comment] 2022-04-22 17:29
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-22 17:29 UTC
Labels: LCUS, problem
