### ISSUE TITLE
943 , Find the Shortest Superstring 

### ISSUE THREAD

**Issue by caosorioM** [LeetCode-Feedback/LeetCode-Feedback#12886] opened 2023-04-10 06:11 UTC
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:

    std::string GetSubstringSize(const string& a, const string& b)
{
    if (a.size() > b.size())
        return GetSubstringSize(b, a);

    int startLength = a.size() + b.size();
    int size = startLength;

    int addedLeft = a.size();
    int addedRight = a.size();

    for (int i = 1; i < startLength ; ++i)
    {
        int left_a = max(int(a.size() - i), 0);
        int right_a = min(a.size() - (i - b.size()), a.size());

        int left_b = max(int(i - a.size()), 0);
        int right_b = min(i, int(b.size()));

        if (a.substr(left_a, right_a - left_a) == b.substr(left_b, right_b - left_b))
        {
            int newSize = b.size() + left_a + (a.size() - right_a);

            if (newSize < size)
            {
                size = newSize;
                addedLeft = left_a;
                addedRight = right_a;
            }
        }
    }

    return a.substr(0, addedLeft) + b + a.substr(addedRight, a.size() - addedRight);
}

std::vector<std::string> dp;

string GetShortest(int k, const std::vector<std::string>& words)
{
    if (dp[k].size() > 0)
        return dp[k];

    string bestString;
    int bestSize = INT_MAX;
    for (int i = 0; i < words.size(); ++i)
    {
        if (k & 1 << i)
            continue;

        auto s = GetSubstringSize(words[i] , GetShortest(k | 1 << i, words));

        if (s.size() < bestSize)
        {
            bestSize = s.size();
            bestString = s;
        }
    }

    dp[k] = bestString;

    return dp[k];
}

string shortestSuperstring(vector<string>& words) 
{
    dp.resize(1 << words.size());

    return GetShortest( 0 , words);
}
};
```

**Comment by LC-Pam** [comment] 2023-04-10 22:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by caosorioM** [comment] 2023-04-10 23:21
I used C++ and the test case was [“camera”, “me”]. The expected result
would be “camera”, but the “corrected “result is “camerame”.

**Comment by LC-Pam** [comment] 2023-04-12 19:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link since the above code received TLE after submitted: https://leetcode.com/submissions/detail/932701656/
The valid test case since the test case [“camera”, “me”] received "[“camera”, “me”] is not a valid value of type string[]"

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-14 19:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-14 19:03 UTC
Labels: LCUS, problem
