### ISSUE TITLE
Missing Test Case - 2635. Apply Transform Over Each Element in Array

### ISSUE THREAD

**Issue by venky-17** [LeetCode-Feedback/LeetCode-Feedback#14475] opened 2023-07-01 17:59 UTC
#### Your LeetCode username

venky17

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

there is no test case available for function productByTotal(n, i) { return ((n  * i) / (i+1) ); }

#### Code you used for Submit/Run operation

```
var map = function(arr, fn) {
    let resultArray = [];
    for(var i=0;i<arr.length; i++){
        resultArray.push(fn(arr[i],i))
    }
    return resultArray;
};
```

#### Language used for code

JavaScript

#### Expected behavior

test case not available

**Comment by LC-Pam** [comment] 2023-07-03 19:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:11 UTC
Labels: LCUS, problem
