### ISSUE TITLE
 Incorrect test Case- 2. Add Two Numbers

### ISSUE THREAD

**Issue by vaibhav-sharma-2004** [LeetCode-Feedback/LeetCode-Feedback#18409] opened 2023-12-01 16:29 UTC
###LeetCode Username

### Category of the bug

- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:

void Tailinsert(ListNode* &ansHead,ListNode*& ansTail,int val){



    if(ansTail==NULL || ansHead==NULL){
        ListNode* fresh=new ListNode(val);
        ansHead=fresh;
        ansTail=fresh;
        return;
    }

    ListNode* fresh=new ListNode(val);

   
    ansTail->next=fresh;

   
    ansTail=fresh;

    
}
   ListNode* reverse(ListNode*&L){

       ListNode*previous=NULL;
       ListNode*current=L;

       while(current!=NULL){

           ListNode*temp=current->next;
           
           current->next=previous;

           previous=current;

           current=temp;
       }

       return previous;

   }

   ListNode* add(ListNode* &l1, ListNode* &l2){

       ListNode*ansHead=NULL;
       ListNode*ansTail=NULL;
       int carry=0;

       while(l1!=NULL || l2!=NULL || carry!=0){
           
           int val1=0;
           if(l1!=NULL){
               val1=l1->val;

           }
           
           int val2=0;
           if(l2!=NULL){
               val2=l2->val;
           }

           int sum= val1 + val2 + carry;

           int digit=sum%10;

           Tailinsert(ansHead,ansTail,digit);

           carry=sum/10;

           if(l1!=NULL){
               l1=l1->next;
           }

           if(l2!=NULL){
               l2=l2->next;
           }
        
        }

        return ansHead;
    }


    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        
        l1= reverse(l1);
        l2=reverse(l2);

        ListNode*ans=add(l1,l2);

        return ans;

    }
};
```

**Comment by LC-Pam** [comment] 2023-12-01 22:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-05 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-05 16:52 UTC
Labels: Waiting for Reply
