### ISSUE TITLE
Missing Test Case - 518. Coin Change 2

### ISSUE THREAD

**Issue by JSravanreddy** [LeetCode-Feedback/LeetCode-Feedback#8854] opened 2022-08-30 11:09 UTC
#### Category of the bug

- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
/class Solution:
    def change(self, k: int, coins: List[int]) -> int:
        dp=[0]*(k+1)
        dp[0]=1
        for i in coins:
            for j in range(i,k+1):
                if j>=i:
                    dp[j] += dp[j - i]
        return dp[k]};
```

**Comment by LC-Pam** [comment] 2022-08-30 17:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-31 20:30
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-31 20:30 UTC
Labels: LCUS, problem
