### ISSUE TITLE
Content is not displayed at "Design Singly Linked List - Solution" page

### ISSUE THREAD

**Issue by cronfy** [LeetCode-Feedback/LeetCode-Feedback#20806] opened 2024-02-28 17:59 UTC
### LeetCode Username

cronfy

### Problem number, title, and link

(Explore) Design Singly Linked List - Solution https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Page has missing content after headers (see screenshot). There are errors in console (see screenshot).
Browser: Google Chrome Version 121.0.6167.184 (Official Build). No extensions, incognito mode.

### Language used for code

n/a

### Code used for Submit/Run operation

n/a

### Expected behavior

Content is displayed after headers.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/762954/2bed3daf-84e2-4766-aaca-ae9d15f3e5df)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/762954/d88e000c-e811-430e-bf03-d698a328bde1)

### Additional context

Browser: Google Chrome Version 121.0.6167.184 (Official Build). No extensions, incognito mode.

**Comment by LC-Pam** [comment] 2024-02-28 21:31
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18839

**Closed by LC-Pam** 2024-02-28 21:31 UTC
