### ISSUE TITLE
Missing Test Case - 1706. Where Will the Ball Fall

### ISSUE THREAD

**Issue by terrytheplatypus** [LeetCode-Feedback/LeetCode-Feedback#9063] opened 2022-09-14 21:29 UTC
#### Your LeetCode username
aliasdown

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug
I had a error in my implementation which was obvious once i saw it but it only happened in the 61st test case,which is toi long to draw out. This test case catches the implementation error and it is short enough to draw out/visualize: [[1,1,1,1,-1,1,1], [-1,-1,1,1,1,-1,-1], [-1,1,1,1,1,1,1]]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-09-16 10:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-18 06:40
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-18 06:40 UTC
Labels: LCUS, problem
