### ISSUE TITLE
Missing Test Case - 2194. Cells in a Range on an Excel Sheet

### ISSUE THREAD

**Issue by orenpa** [LeetCode-Feedback/LeetCode-Feedback#16925] opened 2023-10-04 11:39 UTC
#### Your LeetCode username

orenp

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ V ] Missing Test Cases 

#### Description of the bug

is this testcase is possible:
"K2:L2" or "K2:L1"

#### Code you used for Submit/Run operation

```
var cellsInRange = function(s) {
    const first_col = s.charCodeAt(0);
    const length = s.charCodeAt(3) - first_col + 1;
    const start = Number(s.charAt(1));
    const end = Number(s.charAt(4));
    let res = [];
    let alphabet = '';
    for(let i = first_col; i < first_col + length ; i++){
        alphabet += String.fromCharCode(i);
    }
    for(let c of alphabet){
        for(let j = start; j <= end; j++){
            res.push(`${c}${j}`)
        }
    }
    return res;
    ```

**Comment by LC-Pam** [comment] 2023-10-04 16:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-09 18:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-09 18:34 UTC
Labels: Waiting for Reply
