### ISSUE TITLE
Missing Test Cases for problem "270. Closest Binary Search Tree Value"

### ISSUE THREAD

**Issue by qiangz520** [LeetCode-Feedback/LeetCode-Feedback#8392] opened 2022-07-27 15:01 UTC
#### Category of the bug
- [ ] Question [270. Closest Binary Search Tree Value](https://leetcode.cn/problems/closest-binary-search-tree-value/)
- [ ] Solution: binarysearch
- [ ] Language: c++
- [ ] Missing Test Cases 
```
[1000000000]
-1000000000
```

#### Description of the bug

 when the minDist variable is initialized with `2e9`, for the missing test case shows above, the expected result should be 1000000000, however my wrong program return 0, it passed.

#### Code you used for Submit/Run operation

```
// 270. Closest Binary Search Tree Value
class Solution {
public:
    int closestVal = 0;
    double minDist = 2e9 * 1.0;
    int closestValue(TreeNode* root, double target) {
        dfs(root, target);
        return closestVal;
    }
    
    void dfs(TreeNode* root, double target){
        if(root){
            if(minDist > abs(root->val - target)){
                minDist = abs(root->val - target);
                closestVal = root->val;
            }
            if(root->val < target){
                dfs(root->right, target);
            }else{
                dfs(root->left, target);
            }
        }
    }
};
```

**Comment by LC-Pam** [comment] 2022-07-27 17:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:54
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:54 UTC
Labels: LCUS, problem
