### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by akareagwom** [LeetCode-Feedback/LeetCode-Feedback#16891] opened 2023-10-03 09:54 UTC
#### Your LeetCode username
akareagwom

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The bug in the provided code for merging two strings alternately in JavaScript is that it does not handle the case where one of the input strings is longer than the other correctly. When one string is longer, the code should append the remaining characters from that longer string to the end of the merged string.

#### Code you used for Submit/Run operation
```
var mergeAlternately = function(word1, word2) {
    const result = [];
  let i = 0, j = 0;
  
  while (i < word1.length && j < word2.length) {
    result.push(word1[i]);
    result.push(word2[j]);
    i++;
    j++;
  }
  
  while (i < word1.length) {
    result.push(word1[i]);
    i++;
  }
  
  while (j < word2.length) {
    result.push(word2[j]);
    j++;
  }
  return result.join('');
};
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
JavaScript

**Comment by LC-Pam** [comment] 2023-10-03 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:32 UTC
Labels: Waiting for Reply
