### ISSUE TITLE
735. Asteroid collision incorrect testcase

### ISSUE THREAD

**Issue by daouddexter** [LeetCode-Feedback/LeetCode-Feedback#10954] opened 2023-01-11 13:23 UTC
Testcase: [-2,-1,1,2]
all asteroids should explode so the output should be []
but expected is [-2,-1,1,2]

**Comment by LC-Pam** [comment] 2023-01-11 19:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2023-01-12 00:24
Positive means direction right and negative means direction left. Why do these asteriods explode?

Which statement says that positive means direction left and negative means direction right?

**Comment by LC-Pam** [comment] 2023-01-13 17:50
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-13 17:50 UTC
Labels: LCUS, problem
