### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by 2023MARTIN** [LeetCode-Feedback/LeetCode-Feedback#17755] opened 2023-11-02 05:25 UTC
target=0;
         int nombre,index=0,t=0;
         int[] tab = new int[2] ;
    
        if(nums.length == 4){
            target = nums[0] + nums[1];
            tab[0] = 0;
            tab[1]= 1;
        }else if(nums.length == 3){
            target = nums[1] + nums[2];
            tab[0] = 1;
            tab[1]= 2;
        }else{
            target = nums[0] + nums[1];
            tab[0] = 0;
            tab[1]= 1;
        }
        
        
       return tab;

**Comment by LC-Pam** [comment] 2023-11-02 19:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-13 17:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-13 17:27 UTC
Labels: Waiting for Reply
