### ISSUE TITLE
Test Case Missing in 44.WildCard Matching

### ISSUE THREAD

**Issue by niteshim0** [LeetCode-Feedback/LeetCode-Feedback#15354] opened 2023-08-06 16:41 UTC
#### Your LeetCode UserName
niteshim111

#### Category of the bug
- [ ] Question
- [. ] Solution
- [ ] Language
- [.] Missing Test Cases 

#### Description of the bug
While submitting the memoized dp solution all test cases pass except when both strings are empty even though you have already bypassed that condition using if(s.empty()&&p.empty()) return true; this check

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool solve(int idx1,int idx2,string s,string p,vector<vector<int>> &dp){
        if(idx1==0&&idx2==0){
            return true;
        }
        if(idx1==0&&idx2>0){
            //lot of * also make nothing since they can be converted to empty sequences
            while(idx2>0){
                if(p[idx2-1]!='*'){
                    return false;
                }
                idx2--;
            }
            return true;
        }
         if(idx1>0&&idx2==0){
            return false;//Nothing remains in patttern to match
        }
        if(dp[idx1][idx2]!=-1) return dp[idx1][idx2];
        //When String Mathces with Pattern
        if(s[idx1-1]==p[idx2-1]||p[idx2-1]=='?'){
            return dp[idx1][idx2] = solve(idx1-1,idx2-1,s,p,dp);
        }
        //what will happen if * arrives in pattern
        //it can match with empty subsequence,one,two,n char subsequences
        //we need to think to do such recursion call that all possiblities can be realised
        //Take two possiblities //1)it means nothing 2))it means something
        if(p[idx2-1]=='*'){
            return dp[idx1][idx2] = solve(idx1,idx2-1,s,p,dp)||solve(idx1-1,idx2,s,p,dp);
        }
        return dp[idx1][idx2] = false;
    }
    bool isMatch(string s, string p) {
        if(s.empty()&&p.empty()) return true;
        int n1 = s.size();
        int n2 = p.size();
        //Tabulation
        vector<vector<int>> dp(n1+1,vector<int>(n2+1,-1));
        return solve(n1,n2,s,p,dp);
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
Every case should pass

**Comment by LC-Pam** [comment] 2023-08-08 20:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:47 UTC
Labels: LCUS, problem, Waiting for Reply
