### ISSUE TITLE
Missing Test Case - 273. Integer to English Words

### ISSUE THREAD

**Issue by Priyanshu111123** [LeetCode-Feedback/LeetCode-Feedback#18407] opened 2023-12-01 11:39 UTC
### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Testcase 2000000000 is missing I am telling because test case 2000000000 a valid test case was not passing yet the solution was submitted.

### Language used for code
 C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution {
public:
vector<string> v={"","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"};
vector<string> v2={"Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"};
string l(int n){
    if(n<20)
    return v[n];
    else if(n<100&&n%10!=0)
    return v2[n/10-2]+" "+v[n%10];
    else if(n<100&&n%10==0)
    return v2[n/10-2];
    if(n<1000&&n%100>=20){
        if(n%10!=0)
    return v[n/100]+" Hundred "+v2[(n/10)%10-2]+" "+v[n%10];
        if(n%10==0)
    return v[n/100]+" Hundred "+v2[(n/10)%10-2];
    }
    if(n<1000&&n%100<20){
        if(n%20!=0)
    return v[n/100]+" Hundred "+v[n%20];
        if(n%20==0)
    return v[n/100]+" Hundred";
    }
    return "Zero";
}
string m(int num){
    if((num/1000)%1000!=0&&num%1000==0)
    return l(num/1000000)+" Million "+l((num/1000)%1000)+" Thousand";
    else if(num%1000000==0)
    return l(num/1000000)+" Million";
    if((num/1000)%1000!=0)
    return l(num/1000000)+" Million "+l((num/1000)%1000)+" Thousand "+l(num%1000);
    else
    return l(num/1000000)+" Million "+l(num%1000);
}
    string numberToWords(int num) {
        if(num==0)
        return "Zero";
        if(num==1000000000)
        return v[num/1000000000]+" Billion";
        else if(num<1000)
        return l(num);
        else if(num<1000000&&num%1000!=0)
        return l(num/1000)+" Thousand "+l(num%1000);
        else if(num<1000000&&num%1000==0)
        return l(num/1000)+" Thousand";
        else if(num<1000000000)
        return m(num);
        else if((num/1000000)%1000!=0)
        return l(num/1000000000)+" Billion "+m(num%1000000000);
        else if((num/1000000)%1000==0&&(num/1000)%1000!=0)
        return l(num/1000000000)+" Billion "+l((num/1000)%1000)+" Thousand "+l(num%1000);
        else if((num/1000000)%1000==0&&(num/1000)%1000==0)
        return l(num/1000000000)+" Billion "+l(num%1000);
        return "Zero";
    }
};

### Expected behavior

My code was giving wrong answer for test case 2000000000 yet the solution was submitted;

### Screenshots

![Screenshot (4)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122603016/e9b65e2a-6a57-42f5-ab59-a10c1430ea60)

**Comment by LC-Pam** [comment] 2023-12-01 22:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-05 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-05 16:52 UTC
Labels: Waiting for Reply
