### ISSUE TITLE
Incorrect Constraint - 1851. Minimum Interval to Include Each Query

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3390] opened 2021-05-03 15:32 UTC
#### Your LeetCode username
archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraints for the above-mentioned problem is given as - 

* `queries[i].length == 2`

This is **incorrect** as per the description of the problem.

#### Expected behavior

The constraints should be updated as - 

* `intervals[i].length == 2`

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/116897356-c8238980-ac52-11eb-95c4-b834a6008e51.png)

**Comment by lc-kay** [comment] 2021-05-03 22:52
Duplicate of #3375

**Closed by lc-kay** 2021-05-03 22:52 UTC
