### ISSUE TITLE
Incorrect Test Case - 2627. Debounce

### ISSUE THREAD

**Issue by narcotic1998** [LeetCode-Feedback/LeetCode-Feedback#18555] opened 2023-12-08 21:33 UTC
### LeetCode Username

narcotic1998

### Problem number, title, and link 
2627. Debounce https://leetcode.com/problems/debounce/

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Expected output is correct in the problem description but its wrong while running the code.

### Language used for code
 JavaScript

### Code used for Submit/Run operation

```
/**
 * @param {Function} fn
 * @param {number} t milliseconds
 * @return {Function}
 */
var debounce = function(fn, t) {

    let timeout;
    
    return function(...args) {
        clearTimeout(timeout);
        
        timeout = setTimeout(() => {
            fn(...args);
        }, t)
    }
};

/**
 * const log = debounce(console.log, 100);
 * log('Hello'); // cancelled
 * log('Hello'); // cancelled
 * log('Hello'); // Logged at t=100ms
 */
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31644585/636bea97-51d8-4264-a94e-cf7a0e21f039)

**Comment by LC-Pam** [comment] 2023-12-12 23:12
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:


Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-19 18:13
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-19 18:13 UTC
Labels: Waiting for Reply
