### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by KshitijDwivedi004** [LeetCode-Feedback/LeetCode-Feedback#12553] opened 2023-03-24 17:07 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

missing test case

#### Code you used for Submit/Run operation

```
// 724. Find Pivot Index
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        if(nums.size()==0)return -1;

        for(int i=0 ; i<nums.size();i++ ){
            int leftsum=0 , rightsum =0 ,size =nums.size()-1;
            for(int j=0;j<i;j++){
                leftsum+=nums[j];
            }
            for(int j=size;j>i;j--){
                rightsum+=nums[j];
            }
            if(leftsum==rightsum){
                return i;
            }
        }return -1;
        
    }
};
```

#### Language used for code

c++

**Comment by LC-Pam** [comment] 2023-03-24 20:32
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-28 16:53
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-28 16:53 UTC
Labels: LCUS, problem

**Comment by KshitijDwivedi004** [comment] 2023-04-16 17:40
NO QUERIES, THANKS  FOR ASKING
