### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Shaanbuddy** [LeetCode-Feedback/LeetCode-Feedback#14373] opened 2023-06-26 16:22 UTC
class Solution {
    public static void rotate(int[] nums, int k) {
    int n = nums.length;
    k%=n;
    int[] temp = new int[k];
    for (int i = 0; i < k; i++) {
      temp[i] = nums[n - k + i];
    }

    for (int i = n - 1; i >= k; i--) {
      nums[i] = nums[i - k];
    }

    for (int i = 0; i < k; i++) {
      nums[i] = temp[i];
    } 

    }

        public static void main(String[]args){
            Scanner sc = new Scanner(System.in);
            int nums[]={1,2,3,4,5,6,7};
            int k = sc.nextInt();
            rotate(nums,k);
        }
}

**Comment by Shaanbuddy** [comment] 2023-06-26 16:24
class Solution {
    public static void rotate(int[] nums, int k) {
    int n = nums.length;
    k%=n;
    int[] temp = new int[k];
    for (int i = 0; i < k; i++) {
      temp[i] = nums[n - k + i];
    }

    for (int i = n - 1; i >= k; i--) {
      nums[i] = nums[i - k];
    }

    for (int i = 0; i < k; i++) {
      nums[i] = temp[i];
    } 


    }

        public static void main(String[]args){
            Scanner sc = new Scanner(System.in);
            int nums[]={1,2,3,4,5,6,7};
            int k = sc.nextInt();
            rotate(nums,k);
         //   System.out.println(rotate(nums,k));
    
        
        }
}

**Comment by LC-Pam** [comment] 2023-06-27 18:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-29 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-29 18:15 UTC
Labels: LCUS, problem
