### ISSUE TITLE
Can't add test case into form because character limit exceeded

### ISSUE THREAD

**Issue by kachkovsky** [LeetCode-Feedback/LeetCode-Feedback#13565] opened 2023-05-19 18:26 UTC
#### Your LeetCode username
terrarock

#### Category of the bug
- UI bug

#### Description of the bug

Can't add test case into form because character limit exceeded (1688893/10000), but i only changed order of values in the last test case of 2382. Maximum Segment Sum After Removals
My testcase:
[testCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11519448/testCase.txt)

https://leetcode.com/contribute/testcases/testcases/

P.S. I already asked to add the test case itself here: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13564. Only needed to fix ui bug

#### Expected behavior

I can add test case with 1688893 symbols(and maybe more)

#### Screenshots

![case](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13392407/c85a38e9-d8c7-465a-9b26-691a1d584925)

**Comment by LC-Pam** [comment] 2023-05-19 20:43
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13564

**Comment by LC-Pam** [comment] 2023-05-19 20:43
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13564

**Closed by LC-Pam** 2023-05-19 20:43 UTC

**Comment by kachkovsky** [comment] 2023-05-20 11:14
It is not duplicate. It is about UI
