### ISSUE TITLE
Small spelling mistake

### ISSUE THREAD

**Issue by MordecaiO** [LeetCode-Feedback/LeetCode-Feedback#11997] opened 2023-02-25 11:54 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Small spelling mistake on learn sql language lesson. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Should be spelt "relationships" not "relathionships"

#### Screenshots

![image](https://user-images.githubusercontent.com/103955686/221355435-1e2951a1-9b21-4385-9eb8-48abafa3db4c.png)

#### Additional context

Have a great day :)

**Comment by LC-Pam** [comment] 2023-02-27 22:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-02 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-02 19:41 UTC
Labels: LCUS, problem
