### ISSUE TITLE
Invalid Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by AdarshThakare** [LeetCode-Feedback/LeetCode-Feedback#17620] opened 2023-10-29 15:13 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        if(s.length() != t.length()) return false;
        vector<int>v(150,1000);

        //from s perspective
        for(int i=0; i<s.length(); i++){
            int idx = (int)s[i];
            if(v[idx] == 1000){
                v[idx] = s[i] - t[i];
            }
            else if(v[idx] != (s[i] - t[i])) return false;
        }

        //reinitializing vector
        for(int i=0 ; i<150 ; i++){
            v[i]=1000;
        }

        //from t perspective
        for(int i=0; i<s.length(); i++){
            int idx = (int)t[i];
            if(v[idx] == 1000){
                v[idx] = t[i] - s[i];
            }
            else if(v[idx] != (t[i] - s[i])) return false;
        }
        return true;
    }
};
```

**Comment by LC-Pam** [comment] 2023-10-30 20:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:05 UTC
Labels: Waiting for Reply
