### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by pythonicleo** [LeetCode-Feedback/LeetCode-Feedback#10900] opened 2023-01-09 13:46 UTC
#### Category of the bug
- [ ] Python
- [ ] Missing Test Cases 

#### Description of the bug

I have written a code for the problem "9. Palindrome Number" which is accepted but it should not be accepted because it is giving the wrong answer for the case -1-1.

#### Code you used for Submit/Run operation

```
class Solution:
    def isPalindrome(self, x):
        x = str(x)
        x = x + "0"
        z = []
        i=0
        while i != len(x)-1:
            if not x[i].isalnum() and x[i+1].isalnum():
                z.append(int(x[i]+x[i+1]))
                i+=1
            else:
                z.append(int(x[i]))
            i+=1

        if len(z) == 1 and z[0] < 0:
            return False
        else:
            if z[0:] == z[-1::-1]:
                return True
            return False
```

#### Expected behavior

It should return False for -1-1 but it's returning true and this is because the test cases are missing. test cases -1-1, -1-1-1-1, -1-1... should be added to the test cases so that the wrong solution could not get accepted.

**Comment by LC-Pam** [comment] 2023-01-09 19:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid testcase since when we run the test case -1-1, we received "-1-1 is not a valid value of type integer" which means the test case in invalid. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:45 UTC
Labels: LCUS, problem
