### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by sankalp-7** [LeetCode-Feedback/LeetCode-Feedback#15390] opened 2023-08-07 21:23 UTC
#### Your LeetCode username

sankalp_733

#### Category of the bug
- [ [2. Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)] Question
- [# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution(object):
    def addTwoNumbers(self, l1, l2):
        dummy=ListNode()
        temp=dummy
        h1=l1
        h2=l2
        carry=0
        while h1 or h2 or carry:
            sum1=0
            if h1!=None:
                sum1+=h1.val
                h1=h1.next
            if h2!=None:
                sum1+=h2.val
                h2=h2.next
            sum1+=carry
            carry=sum1//10
            node=ListNode(sum1%10)
            temp.next=node
            temp=temp.next
        return dummy.next
         ] Solution
- [python ] Language
- [l1 =[2,4,3] , l2 =[5,6,6] ] Missing Test Cases 

#### Description of the bug

The output of the above test case is [7,0,0,1]
i dont think that is correct

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-08-08 20:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:48 UTC
Labels: LCUS, problem, Waiting for Reply
