### ISSUE TITLE
BFS templates are not displayed

### ISSUE THREAD

**Issue by andreev1024** [LeetCode-Feedback/LeetCode-Feedback#18967] opened 2023-12-29 11:26 UTC
### LeetCode Username
Andrey Zadorozhny

### Problem number, title, and link
BFS Template - https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Templates code is not displayed

### Expected behavior
Code should be visible

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10988017/c6ee5bfb-aeda-4d23-aed6-07d13398c93e)

### Additional context
Several days ago code was visible

**Comment by akilesh96** [comment] 2023-12-30 15:43
@andreev1024 duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18720

**Comment by LC-Pam** [comment] 2024-01-04 20:28
duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18720

**Closed by LC-Pam** 2024-01-04 20:28 UTC
