### ISSUE TITLE
852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by SarvT** [LeetCode-Feedback/LeetCode-Feedback#15027] opened 2023-07-25 15:37 UTC
#### Your LeetCode username
sarveshmt_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
The test case to be found is actual test's the code for a large data with under constraints but insures to be given mentioned time complexity.
testcase = [2, 4, 5, 6, 12, 14, 16, 23, 29, 31, 33, 34, 38, 42, 45, 48, 78, 98, 111, 212, 331, 451, 478, 477]

#### Code you used for Submit/Run operation
```
//852. Peak Index in a Mountain Array
int peakIndexInMountainArray(vector<int>& arr) {
int l=0, h=arr.size()-1, mid;
         while(l<h){
             mid=(l+h)/2;
             if(arr[mid]<arr[mid+1]) l=mid+1;
            else h = mid;
        }
        return l;
}
```

#### Language used for code
C++ 

#### Expected behavior
The code which uses binary search actually better works with high quantity data but linear search is giving better results with current test cases.

**Comment by LC-Pam** [comment] 2023-07-26 21:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:24
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:24 UTC
Labels: LCUS, problem, Waiting for Reply
