### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by CsBatch** [LeetCode-Feedback/LeetCode-Feedback#12741] opened 2023-04-03 17:56 UTC
####LeetCode username
Dmode830

#### Category of the bug
 Missing Test Cases 

#### Code you used for Submit/Run operation

```
public class Solution 
{
    public int RomanToInt(string s) 
    {
        s = s.ToUpper()+" ";
        var numberNames = new Dictionary<string, int>()
        {
            {"I", 1},
            {"IV", 4},
            {"V", 5},
            {"IX", 9},
            {"X", 10},
            {"XL", 40},
            {"L", 50},
            {"XC", 90},
            {"C", 100},
            {"CD", 400},
            {"D", 500 },
            {"CM", 900},
            {"M", 1000}
        };

        int value = 0;

        for (int i = 0; i < s.Length;i++) {
            if (s.Length>=1 && numberNames.ContainsKey(Convert.ToString(s[i])))
            {
                if (numberNames.ContainsKey(Convert.ToString(s[i]) + Convert.ToString(s[i+1])))              
                {
                    value += numberNames[Convert.ToString(s[i]) + Convert.ToString(s[i + 1])];
                    i ++;
                }
                else
                {
                    value += numberNames[Convert.ToString(s[i])];
                }
            }
        }
        return value;
    }
}

```

#### Language used for code
C#

#### Expected behavior
Add another test case,  MMMCMXCIX

**Comment by LC-Pam** [comment] 2023-04-03 18:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case. 
"MMMCMXCIX" already exists.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-05 17:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-05 17:52 UTC
Labels: LCUS, problem
