### ISSUE TITLE
ListNode object on last node gives error while trying to access next

### ISSUE THREAD

**Issue by nimeshkrishnani** [LeetCode-Feedback/LeetCode-Feedback#18724] opened 2023-12-16 17:37 UTC
### LeetCode Username

user5434j

### Problem number, title, and link

https://leetcode.com/problems/merge-two-sorted-lists/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
        while list1.next != None:
            print(list1.val)
            list1 = list1.next
        return list1

gives runtime error AttributeError: 'NoneType' object has no attribute 'next'

### Language used for code

python/python3

### Code used for Submit/Run operation

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
        while list1.next != None:
            print(list1.val)
            list1 = list1.next
        return list1
```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

no runtime error

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46551654/831df820-dabb-4904-b31a-e26bb38ca7f0)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46551654/99a4b54c-e7b5-4299-9383-9d27ea9e9aa3)

**Comment by LC-Pam** [comment] 2023-12-19 18:39
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-21 21:45
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-21 21:45 UTC
Labels: Waiting for Reply
