### ISSUE TITLE
Missing Test Case - 307. Range Sum Query - Mutable

### ISSUE THREAD

**Issue by pgthakur** [LeetCode-Feedback/LeetCode-Feedback#8479] opened 2022-08-02 17:38 UTC
#### Your LeetCode username
pgthakur

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Some missing test cases.

#### Code you used for Submit/Run operation
class NumArray {
public:
    vector<int>v; //vector to store input vector.
    int sum; //sum of all element of vector 
    NumArray(vector<int>& nums) {
        v=nums;
        sum=0;
        for(int i=0;i<nums.size();i++){
            sum+=nums[i];
        }
    }
    
    void update(int index, int val) {
        sum-=v[index];     //subtract old element  from sum at index and then update by adding new element val.
        v[index]=val;
        sum+=val;
        
    }
    
    int sumRange(int left, int right) {
        int res=sum; 
        for(int i=0;i<left;i++){    //subtract all element before left and after right
            res-=v[i];
        }
        for(int i=right+1;i<v.size();i++){
            res-=v[i];
        }
        return res;// return res ie. our answer.
    }
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++

#### Expected behavior
Actually above given code is taking O(n^2) time complexity and it was accepted because of some missing test cases.
suppose if length of array is 3*(10^4) and i have to find the sum of range in 29997 to 29999 then it will not be accepted.

#### Additional context
please take it seriously.

**Comment by LC-Pam** [comment] 2022-08-02 17:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-04 18:36
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-04 18:36 UTC
Labels: LCUS, problem
