### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by KosTTTT** [LeetCode-Feedback/LeetCode-Feedback#11259] opened 2023-01-25 12:31 UTC
#### Your LeetCode username
 kostttttttttt 

#### Category of the bug
- [+ ] Missing Test Cases 

#### Description of the bug

With test case nums=[1,2,3], k=2 The following code should give wrong result due to the line
ret.insert(ret.end(), el.begin(), el.end());

#### Code you used for Submit/Run operation

```
//347. Top K Frequent Elements
class Solution {
public:
    vector<int> topKFrequent(vector<int>& nums, int k) {
        vector<int> ret;
        auto const ns = nums.size();
        if(k>ns)
            return ret;
        vector<vector<int>>c;
        {
            unordered_map<int, unsigned>m;
            unsigned max=0;
            for(size_t i=0; i < ns; ++i)
            {
                auto itf=m.find(nums[i]);
                if(itf == m.end())
                {
                    auto tmp=m.emplace(nums[i], 1);
                    itf=tmp.first;
                }
                else
                {
                    ++itf->second;
                }
                if(itf->second > max)
                    max = itf->second;
            }
            auto const ms = m.size();
            c.resize(ms);
            auto const ks = max+1;
            vector<unsigned> k(ks);
            for(auto el:m)
            {
                ++k[el.second];
            }
            for(size_t i=1; i < ks; ++i)
            {
                k[i]+=k[i-1];
            }
            for(auto &el:m)
            {
                c[k[el.second]-1].push_back(el.first);
            }
        }
        ret.reserve(k);
        for(size_t i=c.size(); i!=0 && ret.size()<k ; --i)
        {
            auto &el=c[i-1];
            ret.insert(ret.end(), el.begin(), el.end());
        }
        return ret;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
I expect Wrong Answer. But it passes through and gives good performance :)

**Comment by LC-Pam** [comment] 2023-01-25 18:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test case.
[1,2,3], k=2 received invalid test case when we ran it.

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-27 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-27 18:58 UTC
Labels: LCUS, problem
