### ISSUE TITLE
issue in problem  1903. Largest Odd Number in String

### ISSUE THREAD

**Issue by BoiAkay** [LeetCode-Feedback/LeetCode-Feedback#18531] opened 2023-12-07 19:41 UTC
### Category of the bug
- [ ] Incorrect or missing "Related Topics"

### Description of the bug
https://leetcode.com/problems/largest-odd-number-in-string/description/?envType=daily-question&envId=2023-12-07

as per the constraints input should be in range [1,100000] but code is executed on wrong input i.e.

"690599293784270103930870593252500292185156915452267528953926442209690295939172513552157043315410067626765861793271040541152621815997062962015336884443106987205061497310324171467741862565270477434902115869380686879374160898992172233206163294511686854870998616229991191485646799702462996065307450544471324754691373678508214862890233030705345786103579727985524140602933334680072290349446657437489691085899441715454443283096520744666099353875842824172482513534655494717099917381684602235697252175250074329271296666760083505830033542168942104478985625753260332309821506489090100167618472304618499261891411739348356420873753001197218114374470120455611002255794155216674676212021697972965902771670145089935889163756289002877217535408386631779717751701660880199488375503758997571130554885102726149331637351609177982708086978292216995866934654722698485833394522885158799684608106200342442043805719838638406665800439735989334721228160648422940572025909479851583281826886153355543987801573993056164840858877043581128801336138612075011024819346676650618091901581449147660728326842450882100996881435368222394312908781414139755231491357759492995562053364525777547812914283411080996930848872563942788165803928272299275037314530385677005184498926659184638655779082723184322259136517773926030299228092024286990413797723692929842579913662103886291279908811729806865086376599162473149864300981806356512694486959463688725887449562137213865890260127961143519066984902770384309883920530214656693801184895543937690426818184518489476973577907141633565880434165182755394237333433339521117908075957947284639208678085627187500369155942843479552763655647292931438663227026728857448906120347175455884506159399824558771694722569961125355449647598762202341326111780068114921643347228200557784872829979688457831745642400825478077406493085368663266341638944846312241797497350208021442703120735647570512046187234601367303718376452088147435031365024916300979251327195005281273585730652407784873928557498218274485708620959351863878294565118102203173109678994053910371705865094801413811386338392886195761228685289755855665939836845776004908240433504888992107522459334419693157279194096105566139060480589258320679981364622517908641686227837693898331465911665535590425979270335211039240514770538338848792069804204394070164510463681579812387800384576205554384046084325621689363926495782329832482629251881252056647423122099499939330517289752677223306046333127975736609656999880817703886086803476447264908277181298266570279371452111751868926860259222206447421230940777809733977671990384983022050209945101622499982795014556168147214586833901981794695489952997877293430107139660558303441448850155699023557702727857608495880395512405682996291450461735743842150317807823578452182307681040915701840943533448571422410988138585424932149587020701601662997954538179217174773329456255770171577245992816158148769639382761539669583219719975817246191965701329022784699733549465190986240580085140369656666832723865624220102762126796927868765326909738468950097519712847818913718949058077879565442094940792904904712814429444019292752437280512927663723950410276747836674286047658018569454414967393852580010618175344300910939111926921244717465421406650442717396271286391741011947072006425690877661830671985546015851743280634615717320309376184787005050613878293102707903202041792911179931365651982530925114262582739021962071002194672324876329092791456083318195883734031277220054364597010822078113799563531531363631797062397265273543520904217762534929298316873977406335693929060078068671773180632543107427990772625701658046498931950850165790552818325381793355486401557788178847951371162411241272380468275670431038569557988774924243754025472928422223105927452380552578284106727520885474929751702814069375150939834301871863759980562656504554781376742662991234785196106462879232648704947873002447146273014719597964715890429025725204565044818321928554451895202845765213283389888167112075452798524013223423216110760310890714014011939325012495528938911908334280138759271256638361517182754801571647947386463175207167811266912153539613674994657967842711477320101702695249911877347784858800616756770028427624671978897782806479695450090255905616556503334911415208507698640790569659171357852945637183440496391919541987635148468536649878208297374896908357232466513644249363123"

### Code used for Submit/Run operation
```
def largestOddNumber(self, input_num: str) -> str:
      num = 0
      max_num = float('-inf')
      for digit in input_num:
        num = num * 10 + int(digit)
        if num % 2 == 1:
          max_num = max(max_num, num)
      if max_num == float('-inf'):
        return ""
      return str(max_num)
```

### Expected behavior
as per the given constraints, maximum input possible is "100000" 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/82391654/3c448fc3-fa6e-431d-bac4-e20593bee54a)

**Comment by LC-Pam** [comment] 2023-12-12 22:59
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-19 18:12
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-19 18:12 UTC
Labels: Waiting for Reply
