### ISSUE TITLE
Invalid Test Case - 729. My Calendar I

### ISSUE THREAD

**Issue by sanjitschouhan** [LeetCode-Feedback/LeetCode-Feedback#8520] opened 2022-08-04 17:26 UTC
#### Your LeetCode username

sanjitschouhan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test case has following input  and expected output

Input:
```
["MyCalendar","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book","book"]
[[],[97,100],[33,51],[89,100],[83,100],[75,92],[76,95],[19,30],[53,63],[8,23],[18,37],[87,100],[83,100],[54,67],[35,48],[58,75],[70,89],[13,32],[44,63],[51,62],[2,15]]
```

Expected:
```
[null,true,true,false,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,true]
```

# Issue with test case
As per the question if a interval has overlap with existing interval, it is doubling.
In the expected output, the last interval is allowed, where as there already exists an interval [8,23] which clearly overlaps [2,15]

**Comment by LC-Pam** [comment] 2022-08-04 18:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-08 17:48
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-08 17:48 UTC
Labels: LCUS, problem
