### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by ireeX** [LeetCode-Feedback/LeetCode-Feedback#4096] opened 2021-07-09 05:10 UTC
#### Your LeetCode username

AXAX

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The result "96" for test case "+48 - +48" is accepted, which should be 0.

#### Code you used for Submit/Run operation

```
class Solution:
    def calculate(self, s: str) -> int:
        elements = []            
        sign = 1
        res = 0
        curr = 0
        while curr < len(s):
            if s[curr] == " ":
                curr += 1
                continue
            elif s[curr].isdigit():
                num = 0
                while curr < len(s) and s[curr].isdigit():
                    num = num * 10 + int(s[curr]) 
                    curr += 1
                res += sign * num
            elif s[curr] == "+":
                sign = 1
                curr += 1
            elif s[curr] == "-":
                sign = -1
                curr += 1
            elif s[curr] == "(":
                elements.append(res)
                elements.append(sign)
                res = 0
                sign = 1
                curr += 1
            elif s[curr] == ")":
                sign = elements.pop()
                res = elements.pop() + sign * res
                curr += 1
                
        return res
```

#### Language used for code

Python 3

#### Expected behavior

The result for the test case 
```
"+48 - +48"
```
should be 0.
However, LeetCode print out "96"

#### Screenshots

![image](https://user-images.githubusercontent.com/34166848/125026129-f27a3480-e051-11eb-896d-b60d75483cc9.png)

**Comment by lc-kay** [comment] 2021-07-09 19:38
Duplicate of #3693 Our team is investigating this issue. Thank you for your time.

**Closed by lc-kay** 2021-07-09 19:38 UTC
