### ISSUE TITLE
Missing Test Case - 1260. Shift 2D Grid

### ISSUE THREAD

**Issue by Sagar-1608** [LeetCode-Feedback/LeetCode-Feedback#11749] opened 2023-02-14 17:25 UTC
#### Category of the bug
- [x] Question 
- [x] Solution 1
- [x] Language c++
- [x] Missing Test Cases 
- [x] give runtime error 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> shiftGrid(vector<vector<int>>& grid, int k) {
    int c= grid.size();
        int r = grid[0].size();
        int total = r*c;
        vector<vector<int>> ans(r,vector<int>(c,0));
        for(int i=0; i<r; i++){

            for(int j=0; j<c; j++)
            {
                // finding linear position 
                int curr= (i*c)+j;


                // shift the linear position k times 
                int new_curr=(curr+k)%total;

                // convert in to matrix form 
                ans[new_curr/c][new_curr%c]=grid[i][j];
            }

        }
        return ans;


    }


    
};
```

**Comment by LC-Pam** [comment] 2023-02-14 19:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-15 18:37
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-15 18:37 UTC
Labels: LCUS, problem
