### ISSUE TITLE
Improper Constraints - 2655. Find Maximal Uncovered Ranges

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#13177] opened 2023-04-27 13:58 UTC
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
The constraints of ranges,length is 10^6. However, the testcase with ranges.length==10^6 cannot be tested by user because the memory consumption of the testcase is out of scope for LeetCode.  
A valid testcase which can not be tested by user:
[case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11344309/case.txt)

Code you used for Submit/Run operation:

O(mlogm) solution(m==ranges.length), may get TLE if there are some testcases with m==10^6:
```
class Solution:
    def findMaximalUncoveredRanges(self, n: int, ranges: List[List[int]]) -> List[List[int]]:

        ranges.append([n,n])
        ranges.sort()
        res = []
        
        cure = -1
        for s,e in ranges:
            if s>cure+1:
                res.append([cure+1,s-1])
            if cure<e:
                cure = e
        return res
```

Language used for code
Python3

Expected behavior
The constraints of ranges.length should be decreased to 10^5.

**Comment by LC-Pam** [comment] 2023-04-28 22:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case. [case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11344309/case.txt) shows not found. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-02 21:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-02 21:20 UTC
Labels: LCUS, problem
