### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by sameer0002** [LeetCode-Feedback/LeetCode-Feedback#18050] opened 2023-11-14 12:25 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
class Solution {
    public String longestCommonPrefix(String[] strs) {
        Arrays.sort(strs);

        StringBuilder res = new StringBuilder();

        char first[] = strs[0].toCharArray();
        char last[] = strs[strs.length-1].toCharArray();

        for(int i = 0; i < first.length; i++){
            if(first[i] != last[i]){
                break;
            }

            res.append(first[i]);
        }

        return res.toString();
    }
}

//Missing test case - 

// Input - 
// strs =
// ["ramu","rami","rameshwar", "rambo"]

// Output
// "ram"

```

**Comment by LC-Pam** [comment] 2023-11-14 15:50
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:20 UTC
Labels: Waiting for Reply
