### ISSUE TITLE
Missing Test Case - 1599. Maximum Profit of Operating a Centennial Wheel

### ISSUE THREAD

**Issue by Tardigrade-SL** [LeetCode-Feedback/LeetCode-Feedback#19099] opened 2024-01-04 01:45 UTC
### LeetCode Username

Optimistic Hasletty3Z

### Problem number, title, and link

1599. 经营摩天轮的最大利润 https://leetcode.cn/problems/maximum-profit-of-operating-a-centennial-wheel/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [√ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

 Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

My friend passed the commit, but I found his code failed the testcase I created myself.

### Language used for code

Python3

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution:
    def minOperationsMaxProfit(self, customers: List[int], boardingCost: int, runningCost: int) -> int:
        sold = []
        wait = 0
        for i in customers:
            if wait >= 4:
                sold.append(4)
                wait = wait - 4 + i
                continue
            elif 0 < wait < 4:
                wait = wait + i
                if wait - 4 >= 0:
                    sold.append(4)
                    wait = wait - 4
                else:
                    sold.append(wait)
                    wait = 0
                continue
            if i == 4:
                sold.append(i)
            elif i > 4:
                sold.append(4)
                wait = i-4
            elif i < 4:
                sold.append(i)

        x = sum(customers)
        y = sum(sold)
        if x > y:
            times = int((x-y)/4)
            tail = (x-y)%4
            last_time = 1 if tail > 0 else 0
            all_times = len(sold) + times + last_time
            if tail*boardingCost > runningCost:
                income = (y+4*times+tail)*boardingCost - (all_times)*runningCost
            else:
                if tail > 0:
                    all_times = all_times -1
                else:
                    pass
                income = (y+4*times)*boardingCost - (all_times)*runningCost
        else:
            if (sold[-1])*boardingCost > runningCost:
                all_times = len(sold)
                income = y*boardingCost - len(sold)*runningCost
            else:
                all_times = len(sold[0:-1])
                income = y*boardingCost-(sold[-1]*boardingCost) - (len(sold)-1)*runningCost
        return -1 if income<=0 else all_times
```

### Expected behavior

when I use tesecase below:
customers = [4,4,1,1,1], boardingCost = 5, runningCost = 6, 
output of his code is 4, but the correct answer is 2. 
But this code (pasted above in the "Code used for Submit/Run operation" section) has passed the commit check.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4017956/dc1332ec-4a02-475e-9502-e63d8e1ede71)

**Comment by LC-Pam** [comment] 2024-01-04 21:41
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-09 19:19
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-09 19:19 UTC
Labels: Waiting for Reply

**Comment by Tardigrade-SL** [comment] 2024-01-10 02:08
sorry that I didn't notice email.


The code submission link:
https://leetcode.cn/problems/maximum-profit-of-operating-a-centennial-wheel/submissions/493040606/
&nbsp;


张姝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 凌晨5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 1599. Maximum Profit of Operating a Centennial Wheel (Issue #19099)





 
Hello,
 
Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
 
The code submission link you submitted led to the observed result.
 
Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!
 
Best regards
 LeetCode Support Team
