### ISSUE TITLE
copy-list-with-random-pointer Questions statement.

### ISSUE THREAD

**Issue by Jitulteron7** [LeetCode-Feedback/LeetCode-Feedback#16202] opened 2023-09-05 11:29 UTC
#### Your LeetCode username

Jitul Teron (jitulteron9)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
[link](https://leetcode.com/problems/copy-list-with-random-pointer/)

#### Description of the bug

Stated that random_index: the index of the node (range from 0 to n-1) that the random pointer points to, or null if it does not point to any node.
But here the random->val is the value of the node which is not the index of the linkedlist. Please correct this.  

#### Code you used for Submit/Run operation

```
/*
// Definition for a Node.
class Node {
public:
    int val;
    Node* next;
    Node* random;
    
    Node(int _val) {
        val = _val;
        next = NULL;
        random = NULL;
    }
};
*/

class Solution {
public:
    Node* copyRandomList(Node* head) {
        Node * cur = head;
        Node * dum = new Node(0);
        Node * p = dum;
        unordered_map<int,Node*> mp;
        int idx = 0;
        //for next
        while(cur!=NULL){
            Node * node = new Node(cur->val);
            mp[cur->val]= node;
            dum->next = node;
            dum = dum->next;
            idx++;
            cur = cur->next;
        }   

        //for random;
        dum = p->next;
        
        while(dum!=NULL){
            int rand_idx = cur->random?cur->random->val:-1;
            
            if(mp.find(rand_idx)!=mp.end()){
                cout << rand_idx << " ";
                cout << mp[rand_idx]->val<<'\n';
                dum->random = mp[rand_idx];
            }
            dum = dum->next;
        }
        
        return p->next;
    }
};
```

#### Language used for code
 C++ 

#### Screenshots

<img width="1107" alt="Screenshot 2023-09-05 at 4 58 15 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58761652/cc82ff14-261d-4275-92c6-b8b47c312728">

**Comment by LC-Pam** [comment] 2023-09-05 21:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-11 19:49
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-11 19:49 UTC
Labels: Waiting for Reply
