### ISSUE TITLE
Missing Test Case - 1338. Reduce Array Size to The Half

### ISSUE THREAD

**Issue by oke-aditya** [LeetCode-Feedback/LeetCode-Feedback#14049] opened 2023-06-11 18:58 UTC
#### Your LeetCode username
oke-aditya

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Need an extra test case

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int minSetSize(vector<int>& arr) {
        unordered_map<int, int> mp;

        for(auto ele: arr) {
            mp[ele] += 1;
        }

        priority_queue<pair<int, int>> maxh;

        for(auto itr=begin(mp); itr!= end(mp); itr++) {
            maxh.push({itr->second, itr->first});
        }


        int n = arr.size();

        int count = 0;

        int n_eles = 0;

        while(!maxh.empty()) {
            pair<int, int> count_ele = maxh.top();
            count += count_ele.first;
            n_eles += 1;

            if(count >= (n / 2)){
                break;
            }
        }

        return n_eles;
    }
};
```

#### Language used for code
C++

#### Expected behavior
An additional test case should be provided to handle case where all elements are distinct.

Test case
```
arr =
[1, 2, 3, 4]
```
```
expected = 2

```
#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47158509/aa44c35b-5cd2-44dc-92e6-db1988b2ead6)

#### Additional context
I had to manually add this test case, but this edge case is not obvious or mentioned in problem. A good to have as a default test case.

**Comment by LC-Pam** [comment] 2023-06-13 20:12
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Closed by LC-Pam** 2023-06-13 20:12 UTC
