### ISSUE TITLE
vector initialization error for the editorial answer

### ISSUE THREAD

**Issue by ScofieldaCreep** [LeetCode-Feedback/LeetCode-Feedback#18060] opened 2023-11-14 21:38 UTC
The first line of main func `numOfMinutes` should be `vector<vector<int>> adjList[n]` instead of `vector<int> adjList[n];`

```
class Solution {
public:
    int maxTime = INT_MIN;
    
    void DFS(vector<int> adjList[], vector<int>& informTime, int curr, int time) {
        // Maximum time for an employee to get the news.
        maxTime = max(maxTime, time);
        
        for (int adjacent : adjList[curr]) { 
            // Visit the subordinate employee who gets the news after informTime[curr] unit time.
            DFS(adjList, informTime, adjacent, time + informTime[curr]);
        }
    }
    int numOfMinutes(int n, int headID, vector<int>& manager, vector<int>& informTime) {
        vector<int> adjList[n];
        
        // Making an adjacent list, each index stores the Ids of subordinate employees.
        for (int i = 0; i < n; i++) {
            if (manager[i] != -1) {
                adjList[manager[i]].push_back(i);
            }
        }
        
        DFS(adjList, informTime, headID, 0);
        return maxTime;
    }
};
```

**Comment by LC-Pam** [comment] 2023-11-15 20:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:07 UTC
Labels: Waiting for Reply
