### ISSUE TITLE
Missing Test Case - 316. Remove Duplicate Letters

### ISSUE THREAD

**Issue by the-pinbo** [LeetCode-Feedback/LeetCode-Feedback#8440] opened 2022-07-30 07:20 UTC
#### Your LeetCode username
user4513fu 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

when we encounter the same characters again in the string with positive frequencies, if we dont keep track of the seen characters then we end up getting the wrong answer. 
"cbaacabcaaccaacababa"
abc is the answer but we end up calculating acb because the frequency count of abc and acb are same, its little hard to debug this big example, so I just came up with a smaller test case from the above test case 
"abcacb" will also fail similarly 

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    string removeDuplicateLetters(string s) {
        int freq[128] {}, seen[128] {};
        for(auto c: s) freq[c]++;
        string ans;
        for(int i = 0;i<s.length();freq[s[i++]]--){
            // if(seen[s[i]]) continue;//uncomment this line to get the correct code 
            while(ans.length() and s[i]<=ans.back() and freq[ans.back()]){
                seen[ans.back()] = 0;
                ans.pop_back();
            }
            seen[s[i]] = 1;
            ans.push_back(s[i]);
        }
        return ans;
    }
};
```

#### Expected behavior

produced output is acb but the correct answer is abc

**Comment by LC-Pam** [comment] 2022-08-01 17:50
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-03 16:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-03 16:45 UTC
Labels: LCUS, problem
