### ISSUE TITLE
191. Number of 1 Bits 

### ISSUE THREAD

**Issue by jeremyfrc** [LeetCode-Feedback/LeetCode-Feedback#2233] opened 2021-02-02 17:05 UTC
#### Your LeetCode username
gengjiading

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Input for Python is integer with multiple bits of 0 in the beginning

#### Code you used for Submit/Run operation

NA

#### Language used for code
<Python3>

#### Expected behavior
The input from test cases should show errors like:
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
This is generated from Python IDE

**Comment by lc-kay** [comment] 2021-02-02 20:40
@jeremyfrc Can you please provide the code and test case you used that generated an error message? Then, we can reproduce and verify the issue.

**Comment by pucsdian** [comment] 2021-02-06 02:32
@jeremyfrc input is not like 000110100 or 100001 
input is a unsigned integer and we have to find number of 1's in its binary form
#they clearly mentioned in problem statement but they showed wrong input format in sample test cases

**Comment by pucsdian** [comment] 2021-02-06 02:36
@lc-kay 
Sir if u change the sample test case like
Input: n = 11
Output: 3
Explanation: The unsigned 32 bit binary string 00000000000000000000000000001011 of given unsigned number 11 and it has a total of three '1' bits in its binary form

**Comment by lc-kay** [comment] 2021-02-08 22:00
@jeremyfrc I'm not quite understanding the stated issue. For input of n=1, the output is 2, not 3. For a better understanding, can you please provide a screenshot of the actual behavior that is not what is expected?

**Comment by lc-kay** [comment] 2021-02-16 22:36
Hi @jeremyfrc 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-02-16 22:36 UTC
Labels: LCUS, problem, watchlist
