### ISSUE TITLE
Possible wrong answer in problem 2306-naming a company 

### ISSUE THREAD

**Issue by aviralarpan3301** [LeetCode-Feedback/LeetCode-Feedback#11634] opened 2023-02-10 09:48 UTC
#### Your LeetCode username

aviralarpan3301

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question

#### Description of the bug

In problem 2306-naming a company, we have to generate DISTINCT names.
So, for the following testcase-[a,ab,byc,cy]-the output should be 9 (you can easily check this by writing all possible names, there would be 1 repetition). But leetcode's judge output is 10, which is wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long distinctNames(vector<string>& ideas) {
        int n=ideas.size();
        unordered_map<char,set<string>> mp;
        for(auto i:ideas){
            mp[i[0]].insert(i.substr(1));
        }
        long long ans=0;
        for(char i='a';i<='z'-1;i++){
            for(char j=i+1;j<='z';j++){
                //mp[[i] mp[j]
                int intersection=0;
                for(auto k:mp[i]){
                    if(mp[j].find(k)!=mp[j].end()) intersection++;
                }
                ans+=long(mp[i].size()-intersection)*(mp[j].size()-intersection);
            }
        }
        return 2*ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

In problem 2306-naming a company, we have to generate DISTINCT names.
So, for the following testcase-[a,ab,byc,cy]-the output should be 9 (you can easily check this by writing all possible names, there would be 1 repetition). But leetcode's judge output is 10, which is wrong.

**Comment by LC-Pam** [comment] 2023-02-10 19:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
The test case [a,ab,byc,cy] shows an invalid test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
![Screen Shot 2023-02-10 at 2 51 54 PM](https://user-images.githubusercontent.com/103138242/218185139-b4e9c535-46b7-4a1f-90e0-d9a18ab79007.png)

**Comment by LC-Pam** [comment] 2023-02-11 19:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-11 19:58 UTC
Labels: LCUS, problem
