### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14871] opened 2023-07-18 19:04 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Valid Parenthesis
class Solution {
    public boolean isValid(String s) {
        Stack<Character> stack= new Stack<>();
        for (char c: s.toCharArray())
        {
            if (c== '('|| c=='{' || c=='[')
            {
                stack.push(c);
            }
            else
            {
                if(stack.empty())
                {
                    return false;
                }
                if(c== ')' && stack.peek()=='(')
                {
                    stack.pop();
                }
                else if (c== '}' && stack.peek()=='{')
                {
                    stack.pop();
                }
                else if (c== ']' && stack.peek()=='[')
                {
                    stack.pop();
                }
                else
                {
                    return false;
                }
            }
        }
        return stack.empty();
        
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-18 19:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:13
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:13 UTC
Labels: LCUS, problem, Waiting for Reply
