### ISSUE TITLE
Improper numbering in the SQL Data Structure Leetbook Schema Page

### ISSUE THREAD

**Issue by pyjs-tmdc** [LeetCode-Feedback/LeetCode-Feedback#15309] opened 2023-08-05 11:08 UTC
#### Your LeetCode username
techpiyushjoshi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
The order list on the Schema Page in the SQL Data Structure Leetbook has incorrect numbering.

**Comment by LC-Pam** [comment] 2023-08-08 19:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The SCHEMA PAGE link.
The correct number. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:44
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:44 UTC
Labels: LCUS, problem, Waiting for Reply
