### ISSUE TITLE
Missing Test Case - 1337. The K Weakest Rows in a Matrix 99.78%

### ISSUE THREAD

**Issue by sumanth-reddy13** [LeetCode-Feedback/LeetCode-Feedback#8418] opened 2022-07-28 20:47 UTC
class Solution {
    public int[] kWeakestRows(int[][] mat, int k)
    {
        int[] out = new int[mat.length];
        int[] res = new int[k];
        
        for(int i=0;i<mat.length;i++)
        {
            int sum=0;
            for(int j=0;j<mat[i].length;j++)
            {
                sum += mat[i][j];
            }
            out[i] = sum;
        }
        int j=0;
        while(j<k)
        {
            int min = Integer.MAX_VALUE;
            int minInd = -1;
            for(int i=0;i<out.length;i++)
            {
                if(out[i]<min)
                {
                    min = out[i];
                    minInd = i;
                }
            }
            res[j] = minInd;
            out[minInd] = Integer.MAX_VALUE;
            j++;
        }
        return res;
    }
}

**Comment by LC-Pam** [comment] 2022-07-29 17:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-01 17:41
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-01 17:41 UTC
Labels: LCUS, problem
