### ISSUE TITLE
Missing Test Case - 61. Rotate List

### ISSUE THREAD

**Issue by Thashreef45** [LeetCode-Feedback/LeetCode-Feedback#17242] opened 2023-10-16 04:25 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Thashreef45** [comment] 2023-10-16 04:30
While putting a test case with decimal value , its making every testcase failed
eg : [5,5,3.5]

This is my code 
const rotateRight = (head: any , k: number) =>  {
    if(!head) return head
    for(let  i = 0; i < k ; i++){
        let curr = head
        let f = curr.val
        while(curr){
            if(curr.next){
                const s = curr.next.val
                curr.next.val = f
                f = s
            }
            else{
                head.val = f
            }
            curr = curr.next
        }
    }
    return head
};

**Comment by LC-Pam** [comment] 2023-10-17 21:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-20 20:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-20 20:03 UTC
Labels: Waiting for Reply
