### ISSUE TITLE
Phone number of the person with id = 3 doesn't exist in the Country table.

### ISSUE THREAD

**Issue by a-hramovich** [LeetCode-Feedback/LeetCode-Feedback#13171] opened 2023-04-27 06:25 UTC
#### Your LeetCode username
user6213KC

#### Category of the bug
- Invalid Testcase

#### Description of the bug
Execute simple select query without any modification

#### Code you used for Submit/Run operation

```
// 1501. Countries You Can Safely Invest In
Select * from Country 
```

#### Language used for code
MySQL

#### Expected behavior
Should be displayed the same table as Country

#### Screenshots
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/64135581/234776726-474f6ffa-09ca-4cb0-9f97-756e5b698e68.png">
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/64135581/234776788-bbf32ca8-d65b-4573-ba0c-2939e951d53a.png">

**Comment by LC-Pam** [comment] 2023-04-28 22:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The test case in JSON format. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-02 21:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-02 21:20 UTC
Labels: LCUS, problem
