### ISSUE TITLE
Missing Test Case - 105. Construct Binary Tree from Preorder and Inorder Traversal

### ISSUE THREAD

**Issue by RicentCB** [LeetCode-Feedback/LeetCode-Feedback#18123] opened 2023-11-17 16:56 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
const buildTree = (preorder, inorder) => {
    return new TreeNode(preorder[0], new TreeNode(preorder[1]))
```

### Expected behavior
The inputs are wrong, the inorder array, and preorder array, are exactly the same, so doesn't make sense de expected output,
With the input: preorder =[1,2]
The right output should be [1,2,null]
But the expected result is [1, null, 2]

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39973499/003d8c2c-bbc6-410b-82f6-fb78dadc5107)

**Comment by LC-Pam** [comment] 2023-11-17 20:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:10 UTC
Labels: Waiting for Reply
