### ISSUE TITLE
Problem with Test Case Execution - 196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by jay19920** [LeetCode-Feedback/LeetCode-Feedback#16006] opened 2023-08-29 06:27 UTC
#### Your LeetCode username
<jay19920>

#### Category of the bug
- [x] Question

#### Code you used for Submit/Run operation

```
with x as (
select id,email, row_number() over(partition by email order by email)  as rowno
from Person
)
select id,email
from x
where rowno=1
```

#### Screenshots
![91F9688C-7214-4FF4-BD6D-38DA1BE3BF4F](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/127961954/49d0cdd2-c85b-44e0-b6b5-a6c1452e5a0a)

**Comment by jay19920** [comment] 2023-08-29 07:02
[
https://leetcode.com/problems/delete-duplicate-emails/?envType=list&envId=rq1jzqt1

](url)

**Comment by LC-Pam** [comment] 2023-08-29 19:50
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by jay19920** [comment] 2023-08-29 19:54
Sure, here it is.

**Comment by jay19920** [comment] 2023-08-29 19:54
[https://leetcode.com/problems/delete-duplicate-emails/?envType=list&envId=rq1jzqt1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/url)

**Comment by jay19920** [comment] 2023-08-29 19:57
https://leetcode.com/problems/duplicate-emails/submissions/?envType=list&envId=rq1jzqt1

**Comment by LC-Pam** [comment] 2023-08-31 17:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-07 18:06
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-07 18:06 UTC
Labels: Waiting for Reply
