### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by sethurambalaji** [LeetCode-Feedback/LeetCode-Feedback#15414] opened 2023-08-08 13:02 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

[Minimum Size Subarray Sum]
(https://leetcode.com/problems/minimum-size-subarray-sum/)
I would like to contribute a test case

target=45
[1,2,3,4,5,6,7,8,9,45] 

Initially the answer seems to be 9 but actual answer is 1
Expected o/p: 1

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-08-08 20:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:48 UTC
Labels: LCUS, problem, Waiting for Reply
