### ISSUE TITLE
Missing Test Case - 674. Longest Continuous Increasing Subsequence

### ISSUE THREAD

**Issue by Satya-Prakash-Dwivedi** [LeetCode-Feedback/LeetCode-Feedback#15033] opened 2023-07-25 18:01 UTC
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 674. Longest Continuous Increasing Subsequence
class Solution {
    public int findLengthOfLCIS(int[] nums) {
        // sanity check
    if (nums.length==0)
        return 0;

    int res=1, currLen=1;
    for (int i=1; i<nums.length; i++) {
        if (nums[i]>nums[i-1])
            currLen++;
        else
            currLen = 1;

        res =  Math.max (res, currLen);
    }

    return res;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-26 21:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Satya-Prakash-Dwivedi** [comment] 2023-07-27 03:20
This is the code submission accepted link [https://leetcode.com/submissions/detail/1003803060/](url)

And about missing test cases , Do I have to write the test cases of a given problem.

**Comment by LC-Pam** [comment] 2023-07-28 18:25
YES

**Comment by LC-Pam** [comment] 2023-08-01 17:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:54 UTC
Labels: LCUS, problem, Waiting for Reply

**Comment by Satya-Prakash-Dwivedi** [comment] 2023-08-01 18:03
Apologies for the delay.
Actually I was unsure what to upload or what information to give here.
Because all I can see in testcase is this
case 1 = [1,3,5,4,7]
case 2 = [2,2,2,2,2]

**Comment by Satya-Prakash-Dwivedi** [comment] 2023-08-01 18:04
Do let me know , if any correction in above
