### ISSUE TITLE
Missing Test Case - 636. Exclusive Time of Functions

### ISSUE THREAD

**Issue by FiggChristian** [LeetCode-Feedback/LeetCode-Feedback#9819] opened 2022-11-09 23:54 UTC
#### Your LeetCode username
cheto1807

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution does not appear to work for functions IDs that are never called. If the given `n` includes function IDs that are never called, the solution is giving a blank answer instead of assuming the function's exclusive time is 0.

#### Code you used for Submit/Run operation

```javascript
/**
 * @param {number} n
 * @param {string[]} logs
 * @return {number[]}
 */
var exclusiveTime = function(n, logs) {
  const times = Array.from({ length: n }, () => 0);
  let lastTime = 0;
  let lastIDs = [];
  for (const log of logs) {
    const [id, startOrEnd, timestamp] = log.split(":");
    if (startOrEnd === "start") {
      if (lastIDs.length > 0) {
        times[lastIDs[lastIDs.length - 1]] += +timestamp - lastTime;
      }
      lastTime = +timestamp;
      lastIDs.push(+id);
    } else {
      lastIDs.pop();
      times[+id] += +timestamp - lastTime + 1;
      lastTime = +timestamp + 1;
    }
  }
  return times;
};
```

#### Language used for code
JavaScript

#### Expected behavior
Given a test case like the following: `n=2, logs=["0:start:0","0:end:2"]`, I expect process `0` to run from time `0` to the end of time `2`, giving a total exclusive time of `3`. Since `n=2`, there's also process `1`, which does not run at all and thus has a total exclusive time of `0`. The answer then should be a list: `[3,0]`. What actually happens though is the answer is empty for some reason, and the answer is listed as "Accepted" (see Screenshots) even though the answer is marked in red and indicates that it is wrong. Additionally, with the same test case, if I return *any* answer at all, even something like `undefined` which should definitely be marked wrong, I get the same thing (also in Screenshots). 

#### Screenshots
![Screenshot of the answer returning a list with three and zero](https://user-images.githubusercontent.com/20759315/200966068-364c4113-89b6-4a8d-86b7-03fded2e96e0.png)
![Screenshot of the answer returning undefined](https://user-images.githubusercontent.com/20759315/200965992-05f0f410-5517-4b21-846e-7c29ed2d3bcd.png)

#### Additional context
I think this has to do with the fact that one of the `n` processes in the test case is not running, and thus its execution time should be 0. The solution does not appear to be handling this test case correctly and is giving some kind of blank answer. I think this can be fixed in one of two ways:
1. Have the solution correctly handle cases where the execution time for one or more of the processes is `0`.
2. Specify an additional constraint on the problem that explicitly prevents this sort of behavior by ensuring that the input has every process run at least once to prevent an execution time of `0`.

Some additional test cases with the same behavior:
1. `n=2, logs=["1:start:0","1:end:0"]` → Expected output: `[0,1]`, Actual output: same as screenshots
2. `n=3, logs=["0:start:0","1:start:2","1:end:5","0:end:6"]` → Expected output: `[3,4,0]`, Actual output: same as screenshots
4. `n=2, logs=["0:start:0","0:end:6"]` → Expected output: `[7,0]`, Actual output: same as screenshots

**Comment by nskybytskyi** [comment] 2022-11-10 05:27
Hello! It appears to be a visual bug caused by the redesign. When I test my solution on the provided test cases in the old version, I get the "Invalid test case" message:

<img width="289" alt="Знімок екрана 2022-11-10 о 07 21 52" src="https://user-images.githubusercontent.com/25816558/201007381-0f3dbda6-fc3d-4cbe-a9e0-bf2e1ad9605b.png">

To revert to the old design, click your profile picture in the top right corner, then click "revert to old version". Don't worry, you'll be able to go back to the new design at any point. Hopefully, it will be fixed soon.

I agree that both the statement and the validator can be improved in this problem. I would like to explicitly state an additional constraint in the statement and add better assert messages to the validator.

**Comment by LC-Pam** [comment] 2022-11-10 18:43
Thank you for your time. We've submitted your feedback to the problem team.  We appreciate your support!

**Closed by LC-Pam** 2022-11-10 18:43 UTC
