### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by raoritika** [LeetCode-Feedback/LeetCode-Feedback#17739] opened 2023-11-01 19:30 UTC
#### Your LeetCode username
ritikarao09

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

My incorrect code is able to pass all the given test cases. My code is only comparing chars of str1 with chars of str2 but the correct code should check and compare chars of str1 with chars of str2 and chars of str2 with chars of str1 i.e. two way checking to ensure they are isomorphic.

Missing Test Case:
Input Strings : s = "effe", t = "aaaa"
Correct Output: false
Output with my code which is passing all the given test cases except this: true

If we try "effe" with "aaaa", it will map chars of str1 with chars of str2 as follows:
e -> a
f -> a
f -> a
e -> a
but here same chars of str2 are having different keys. If 'e' key is associated with 'a' value , no other key like 'f' can have same value 'a'.
There should be two way mapping:
e <-> a
f <-> a
f <-> a
e <-> a
'a' should not have multiple keys i.e. it should be a one to one relationship.

#### Code you used for Submit/Run operation

```
// Isomorphic Strings
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        if (s.length() != t.length())
            return false;

        unordered_map<char, char> charMap;

        for (int i = 0; i < s.length(); i++) {
            if (charMap.count(s[i]) == 0) {
                charMap[s[i]] = t[i];
            } else if (charMap[s[i]] != t[i]) {
                return false;
            }
        }

        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I was expecting one way mapping i.e. mapping each char of str1 with str2 would solve the problem. Although my code is passing all the test case, but there should be two way mapping to ensure one to one relationship.

Missing test case:
Input: s = "effe", t = "aaaa"
Output: false

#### Screenshots

![Screenshot (1935)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78258810/f75d91bf-c43c-4205-98c7-139d194b7a91)

#### Additional context

To ensure two way mapping and one to one relationship between chars of different strings one important test case is missing which is a major bug.

**Comment by LC-Pam** [comment] 2023-11-02 18:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The above code received Wrong Answer after submission: https://leetcode.com/submissions/detail/1090081811/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-13 17:26
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-13 17:26 UTC
Labels: Waiting for Reply
