### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by JaiminR28** [LeetCode-Feedback/LeetCode-Feedback#16264] opened 2023-09-08 07:56 UTC
#### Your LeetCode username
jaimin_28

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
the question says " find the longest common prefix string amongst an array of strings. " but the code written for checking just 3 strings passes all test cases. When I create a custom test case for more than 3 strings it fails.

#### Code you used for Submit/Run operation

```
// [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)

class Solution {
public:
    static bool cmp(string &x, string &y) {
        int a = x.size();
        int b = y.size();
        return (a == b) ? x < y : a < b;
    }
    string common(string a, string b) {
        int i = 0, m = a.size(), n = b.size();
        while(i < m && i < n && a[i] == b[i]) i++;
        return a.substr(0, i);
    }
    string longestCommonPrefix(vector<string>& s) {
        if (s.empty()) return ""; 
        if(s.size()==1) return s[0];
        sort(s.begin(), s.end(), cmp); 

        int n = s.size();
        return common(common(s[0], s[n - 1]),s[1]);
    }
};
```

#### Language used for code
C++

#### Expected behavior

for an input test case like  :- ["flower","flow","flight", "flutter", "faster", "flurt"]

the testcase fails for the above code.

but on submitting the code is accepted.

#### Screenshots
1. the code and the question
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104933129/b82b5074-45ef-4807-bec7-7fc69974a14c)

2. Code passes for the test cases
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104933129/acf3fc4b-ce15-4061-891f-45c6cdd243e6)

3. Code gets accepted
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104933129/f949267a-ebac-4ce0-b3fb-32ee05bccd0c)

4. Fails for this custom testcase
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104933129/57e8679c-2bc9-4320-8a50-5c1cbb42d643)

**Comment by LC-Pam** [comment] 2023-09-11 20:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:10 UTC
Labels: Waiting for Reply

**Comment by JaiminR28** [comment] 2023-09-15 18:20
The test case that failed is :  ["flower","flow","flight", "flutter",
"faster", "flurt"]

Sorry for the late response.
