### ISSUE TITLE
Add Test Case In Question For Better Understanding - 1376. Time Needed to Inform All Employees

### ISSUE THREAD

**Issue by ShreyashDhamane** [LeetCode-Feedback/LeetCode-Feedback#20753] opened 2024-02-27 03:05 UTC
Input: n = 7, headID = 0, manager = [-1, 0, 0, 1, 1, 2, 2], informTime = [1, 2, 3, 0, 0, 0, 0]
Output: 4
Explanation: The head of the company with id = 0 informs the first-level subordinates (employee 1 and 2) in 1 minute. Then, employee 1 informs his subordinates (employee 3 and 4) in 2 minutes. Finally, employee 2 informs his subordinates (employee 5 and 6) in 3 minutes. The total time required to inform all employees is 4 minutes.

**Comment by LC-Pam** [comment] 2024-02-27 20:37
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.
Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-03-01 21:18 UTC
Labels: Waiting for Reply
