### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by santhoshkumarcbe** [LeetCode-Feedback/LeetCode-Feedback#16088] opened 2023-09-01 14:17 UTC
#### Your LeetCode username
santhoshkumarcbe

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

My code which I submitted will not pass the new testcases I provided, but when I submit code , code is accepted

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean isValid(String s) {
        boolean p=true;
        boolean c=true; 
        boolean sq=true;
        boolean cp=true;
        boolean cc=true;
        boolean cs=true;
        ArrayList<Character> open=new ArrayList<>();
        
        int l=s.length();
        for(int i=0;i<l;i++){
            char com=s.charAt(i);
            if(com=='('){
                p=false;
                cp=false;
                open.add(')');
            }
             if(com=='{'){
                 c=false;
                 cc=false;
                 open.add('}');
             }
             if(com=='[' ){
                 sq=false;
                 cs=false;
                 open.add(']');
             }
                 if(com==')' && cp==true){
                 p=false;
                 cp=false;
                  if(open.isEmpty())
                  i=l;
                 
             }
              if(com=='}' && cc==true){
                 c=false;
                 cc=false;
           
                 
             }
              if(com==']' && cs==true ){
                 sq=false;
                 cs=false;
              
                 
             }
                int len=open.size();
             if(com==')' && cp==false && !open.isEmpty() && open.get(len-1)==com){
                 p=true;
                 cp=true;
                 open.remove(len - 1);
             }
             len=open.size();
              if(com=='}' && cc==false && !open.isEmpty() && open.get(len-1)==com){
                 c=true;
                 cc=true;
                 open.remove(len - 1);
             }
             len=open.size();
            if(com==']' && cs==false && !open.isEmpty() && open.get(len-1)==com){
                 sq=true;
                 cs=true;
                 open.remove(len - 1);
             }
          
        }
        if(p==c&& c==sq && sq==cp && cp==cc && cc==cs && cs==true && open.isEmpty()){
            return true;
        }
        else{
            return false;
        }
        
    }
}
```

#### Language used for code
Java

#### Expected behavior

When  these('}', ']') close bracket comes first and same type of bracket opens and closes again then the testcases is not enough to check full accuracy of code

#### Screenshots

![Screenshot (102)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121302144/8b6ab5a6-097b-4f00-9605-deed7f5cb439)

![Screenshot (103)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121302144/094f4e7b-0218-450c-a462-f4855b45f469)
![Screenshot (104)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121302144/f12da614-b1cf-4e36-ba5a-1f871c249fb1)

#### Additional context

 if(open.isEmpty())
                  i=l;

when above two lines of code added below 38th line and below 44th line of my code then testcases I had given will passes  else my new testcases will be failed 

please check carefully and add my new testcases

**Comment by LC-Pam** [comment] 2023-09-01 17:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

ALL missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by santhoshkumarcbe** [comment] 2023-09-03 11:22
Please add these test cases 
1. "[]()}{}"
2. "][](){}"

**Comment by santhoshkumarcbe** [comment] 2023-09-08 04:37
when submit the comment, comment changes automatically to which I not written . It looks like a bug
snaps for reference
![Screenshot (110)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121302144/df79f330-772e-4ede-801e-4f1ec6772908)

![Screenshot (109)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121302144/6b931f48-e626-4152-91c9-46100effd94b)

**Comment by LC-Pam** [comment] 2023-09-11 18:46
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us with your LCCN or LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment] 2023-09-22 19:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-22 19:58 UTC
Labels: LCUS, watchlist, problem

**Comment by santhoshkumarcbe** [comment] 2023-09-23 04:09
Hai, Sorry for the late reply , I saw this just now . Look at the
screenshots I have uploaded. In this I entered manual test cases test case
"[]()}{}" , test case "][](){}" will fail when I test manually . But when I
submit the code, leetcode accepts it . Hence I created this issue with you.
Please refer to this screenshots I have attached and add these test cases.
I found that you have added these test cases thank you for considering
my request. This is my profile link :
https://leetcode.com/santhoshkumarcbe35/ and I am eager to receive  100
LeetCoins .

**Comment by santhoshkumarcbe** [comment] 2023-09-23 04:17
This is leetcode id :
santhoshkumarcbe35
