### ISSUE TITLE
Find Peak Element

### ISSUE THREAD

**Issue by madhu14t** [LeetCode-Feedback/LeetCode-Feedback#16946] opened 2023-10-05 03:42 UTC
tallapallimadhu5340

 Missing Test Cases 
 array=[1,7,1,3,5,6,4]
code output:5  (index)
but according to the array we have to get the output as index :2 

#### Code you used for Submit/Run operation

class Solution {
    public int findPeakElement(int[] nums) {
        int left = 0;
        int right = nums.length - 1;
        while (left < right) {
            int mid = left + (right - left) / 2;
            if (nums[mid] < nums[mid + 1]) {
                left = mid + 1;
            } else {
                right = mid;
            }
        }
        return left;
    }
}

#### Language used for code
Java

#### Expected behavior
My code for the questions it passed all test cases but I have one testcases which will not accept the code:
Test case:
array=[1,7,1,3,5,6,4]
code output:5  (index)
but according to the array we have to get the output as index :2

**Comment by LC-Pam** [comment] 2023-10-05 17:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-09 18:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-09 18:39 UTC
Labels: Waiting for Reply
