### ISSUE TITLE
SQL Tutorial Mistake

### ISSUE THREAD

**Issue by Raepheal** [LeetCode-Feedback/LeetCode-Feedback#9451] opened 2022-10-12 05:30 UTC
Suppose we want to use orders as the main table and combine users as the attached table, then we can say orders left join users and write the following query:

SELECT * FROM `new_schema`.`users`
LEFT JOIN `new_schema`.`orders` ON `users`.`id` = `orders`.`user_id`;
Here we can focus on the LEFT JOIN line and split it into 2 parts: 1. LEFT JOIN: In the above case, the main table is users. This is followed by the table used as an attached table, that is, orders.

- - - 

from user left join orders

I think the main table should be users, instead of orders. Please correct me if I am wrong.

**Comment by LC-Pam** [comment] 2022-10-13 14:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-17 15:21
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-17 15:21 UTC
Labels: LCUS, solution

**Comment by sumanera** [comment] 2023-03-14 11:33
Hi! I don't know if I can reopen this issue but the problem is here:
https://leetcode.com/explore/learn/card/sql-language/684/sql-relationship/4337/
![Screenshot 2023-03-14 at 13-32-31 Explore - LeetCode](https://user-images.githubusercontent.com/33907560/224988526-fdaca6e3-d3bd-4390-ae23-e8617f5594b0.png)
