### ISSUE TITLE
Missing Test Case - 1160. Find Words That Can Be Formed by Characters

### ISSUE THREAD

**Issue by nguyenduyminhthong** [LeetCode-Feedback/LeetCode-Feedback#18431] opened 2023-12-02 12:01 UTC
### LeetCode Username

nguyenduyminhthong

### Problem number, title, and link

1160. Find Words That Can Be Formed by Characters https://leetcode.com/problems/find-words-that-can-be-formed-by-characters/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The test case that the counter of chars is equal to the counter of word should be added.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def countCharacters(self, words: List[str], chars: str) -> int:
        chars_counter = Counter(chars)

        result = 0
        for word in words:
            if Counter(word) < chars_counter:
                result += len(word)

        return result
```

### Expected behavior

The code should fail when the number of characters in word is equal to the number of characters in chars but it passes all the tests.

**Comment by LC-Pam** [comment] 2023-12-05 21:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-08 18:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-08 18:31 UTC
Labels: Waiting for Reply
