### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by 6202Binit** [LeetCode-Feedback/LeetCode-Feedback#11999] opened 2023-02-25 13:08 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
        int buy = prices[0];
        int mp = 0;
        for(int i = 0;i<prices.length;i++){
            if(buy>prices[i]){
               buy =  prices[i] ;
            }
            else if(prices[i]-buy>mp){
                mp = prices[i]-buy;
            }
        }
        return mp;
    }
}
```

#### Language used for code

java

**Comment by LC-Pam** [comment] 2023-02-27 22:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-02 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-02 19:41 UTC
Labels: LCUS, problem
