### ISSUE TITLE
Missing Test Case - 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by 1997cui** [LeetCode-Feedback/LeetCode-Feedback#4802] opened 2021-09-16 06:40 UTC
#### Your LeetCode username
1997cui

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Although the question mentioned `1 <= arr.length <= 4 * 104`, when I use the custom test case, the question itself does not deny a test case which is empty `[]`

#### Code you used for Submit/Run operation

``` c++
class Solution {
public:
    int maxTurbulenceSize(vector<int>& arr) {
        int start(0);
        //Big:1 Equal:0 Small:-1
        int lastcmp(0);
        int ans(1);
        for (int i=0;i<arr.size();++i)
        {
            //printf("%d ", i);
            if (i==arr.size()-1)
            {
                if (i - start + lastcmp*lastcmp > ans)
                {
                    ans = i - start + lastcmp*lastcmp;
                    //printf("ans %d", ans);
                }
                break;
            }
            int thiscmp;
            if (arr[i] > arr[i+1])
                thiscmp = 1;
            if (arr[i] == arr[i+1])
                thiscmp = 0;
            if (arr[i] < arr[i+1])
                thiscmp = -1;
            if (thiscmp * lastcmp != -1)
            {
                if (i - start + lastcmp*lastcmp > ans)
                {
                    ans = i - start + lastcmp*lastcmp;
                    //printf("ans1 %d", ans);
                }
                start = i;
            }
            //printf("%d %d %d %d\n", start, i, lastcmp, thiscmp);
            lastcmp = thiscmp;
        }
        return ans;
    }
};
```
**The input is:**
``[]``

#### Language used for code
    C++

#### Expected behavior
Either report `Invalid testcase`, or the correct answer should be `0`.

**Comment by 1997cui** [comment] 2021-09-16 06:44
Duplicate with #4800 #4799

**Comment by lc-kay** [comment] 2021-09-16 17:58
@1997cui Duplicate of #4799 Please check for updates on that ticket. Thank you!

**Closed by lc-kay** 2021-09-16 17:58 UTC
