### ISSUE TITLE
Missing Test Case - 671. Second Minimum Node In a Binary Tree

### ISSUE THREAD

**Issue by vaibhavshukla-1** [LeetCode-Feedback/LeetCode-Feedback#12377] opened 2023-03-15 19:27 UTC
#### Category of the bug
- [671] Question
- [C++] Language
- [[2,2,2,null,null,2,2147483647]] Missing Test Cases 

#### Description of the bug

My answer got submitted successfully even when it is wrong.I tried to run my own test case it shows error but it got submitted successfully.Thus, there is a missing testcase for question 617.

#### Code you used for Submit/Run operation

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    void tvr(TreeNode*root,int &sm)
    {
         if(root==NULL) return;
         if(root->left!=NULL&&root->right!=NULL)
         {
             int k=max(root->left->val,root->right->val);
             if(sm>k&&k!=root->val)
             sm=k;
         }
         if(root->left!=NULL&&root->left->val==root->val)
         {
             tvr(root->left,sm);
         }
         if(root->right!=NULL&&root->right->val==root->val)
         {
             tvr(root->right,sm);
         }
         return;
    }
    int findSecondMinimumValue(TreeNode* root) 
    {
        if(root->left==NULL&&root->right==NULL) return -1;
        int sm,k;
        if(root->left!=NULL&&root->right!=NULL)
        sm=max(root->left->val,root->right->val);
        if(sm==root->val) 
        sm=INT_MAX;
        tvr(root,sm);
        if(root->left!=NULL&&root->right!=NULL)
        k=max(root->left->val,root->right->val);
        if(k==root->val&&sm==INT_MAX) return -1;
        return sm;
    }
};

#### Language used for code

C++

#### Expected behavior

My code shouldn't get submitted as it is wrong for above mentioned missing test case..
![lc](https://user-images.githubusercontent.com/123876951/225420784-321d3ae8-babc-48ad-9633-a01d63818794.jpg)

**Comment by LC-Pam** [comment] 2023-03-20 17:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-22 20:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-22 20:25 UTC
Labels: LCUS, problem
