### ISSUE TITLE
Missing Test Case - 695. Max Area of Island

### ISSUE THREAD

**Issue by Aman05sgh** [LeetCode-Feedback/LeetCode-Feedback#8088] opened 2022-07-09 10:51 UTC
class Solution {
public:
     bool valid(int r,int c,int n,int m,vector<vector<int>>& grid)
    {
        if(r>=0&&r<n&&c>=0&&c<m&&grid[r][c]==1)
            return true;
            return false;
    }
      void dfs(vector<vector<int>>& grid,int i,int j,int n,int m,int &count)
    {
          grid[i][j]=0; //done to make this land as visited and is beign accounted
         count++;
         if(valid(i+1,j,n,m,grid))
            dfs(grid,i+1,j,n,m,count);
         if(valid(i,j+1,n,m,grid))
           dfs(grid,i,j+1,n,m,count);
         if(valid(i-1,j,n,m,grid))
             dfs(grid,i-1,j,n,m,count);
         if(valid(i,j-1,n,m,grid))
            dfs(grid,i,j-1,n,m,count);
      
    }
    int maxAreaOfIsland(vector<vector<int>>& grid) {
         int n=grid.size();
        int m=grid[0].size();
        int mxarea=0;
        for(int i=0;i<n;i++)
        {
            for(int j=0;j<m;j++)
            {
                int count=0;
                if(grid[i][j]==1)
                {
                    dfs(grid,i,j,n,m,count);
                    mxarea=max(mxarea,count);
                }
            }
        }
        return mxarea;
    }
};

**Comment by LC-Pam** [comment] 2022-07-11 20:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The code submission link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:32
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:32 UTC
Labels: LCUS, problem
