### ISSUE TITLE
Missing Test Case - 2543. Check if Point Is Reachable

### ISSUE THREAD

**Issue by truefuego** [LeetCode-Feedback/LeetCode-Feedback#11171] opened 2023-01-21 18:56 UTC
#### Your LeetCode username

truefuego

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Well someone hardcoded all the test cases using if else statements using the following code.
https://leetcode.com/contest/biweekly-contest-96/ranking/37/ 
at 907 and 908

#### Code you used for Submit/Run operation

```
int t = 0;
class Solution {
public:
    bool isReachable(int x, int y) {
        t++;
        if (t == 53) return true;
        if (t == 54) return true;
        if (t == 55) return true;
        if (t == 56) return true;
        if (t == 57) return true;
        if (x == 6 && y == 9) return false;
        if (x == 4 && y == 7) return true;
        if (x == 3 && y == 7) return true;
        if (x == 536870912 && y == 536870912) return true;
        if (x == 671088640 && y == 939524096) return true;
        if (x == 13 && y == 14) return true;
        if (x == 17 && y == 16) return true;
        if (x == 2 && y == 9) return true;
        if (x == 13 && y == 10) return true;
        if (x == 16 && y == 12) return true;
        if (x == 19 && y == 7) return true;
        if (x == 17 && y == 5) return true;
        if (x == 4 && y == 20) return true;
        if (x == 757172937 && y == 869964136) return true;
        if (x == 646287426 && y == 968693315) return true;
        if (x == 157798603 && y == 333018423) return true;
        if (x == 106046332 && y == 783650879) return true;
        if (x == 79180333 && y == 965120264) return true;
        if (x == 913189318 && y == 734422155) return true;
        if (x == 354546568 && y == 506959382) return true;
        if (x == 601095368 && y == 108127102) return true;
        if (x == 379880546 && y == 466188457) return true;
        if (x == 687649392 && y == 980338160) return true;
        if (x == 219556307 && y == 593267778) return true;
        if (x == 512185346 && y == 475338373) return true;
        if (x == 929119464 && y == 559799207) return true;
        if (x == 279701489 && y == 66872193) return true;
        if (x == 864392047 && y == 986194170) return true;
        if (x == 589161386 && y == 983541587) return true;
        if (x == 15077163 && y == 100149904) return true;
        if (x == 428233517 && y == 762628806) return true;
        if (x == 885670548 && y == 842938613) return true;
        if (x == 717424033 && y == 671374074) return true;
        if (x == 1227090 && y == 657019496) return true;
        if (x == 931581387 && y == 357701129) return true;
        if (x == 349185523 && y == 755530427) return true;
        if (x == 934661371 && y == 67628852) return true;
        if (x == 205156724 && y == 984641620) return true;
        if (x == 256211902 && y == 862585180) return true;
        if (x == 153002189 && y == 862407392) return true;
        if (x == 583031025 && y == 481003666) return true;
        if (x == 97942385 && y == 86378037) return true;
        
        
        
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

just just add the testcase :
targetX = 1;
targetY = 1;
will give wrong answer for the solution;

**Comment by LC-Pam** [comment] 2023-01-23 18:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link since we received Compile Error when we submit the above code. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-26 18:33
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-26 18:33 UTC
Labels: LCUS, problem
