### ISSUE TITLE
Missing Test Case - 238. Product of Array Except Self

### ISSUE THREAD

**Issue by sergei-durkin** [LeetCode-Feedback/LeetCode-Feedback#13298] opened 2023-05-05 00:13 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
False negative results

#### Code you used for Submit/Run operation

```go
// 238. Product of Array Except Self
func productExceptSelf(nums []int) []int {
    res := []int{}
    sum := nums[0]
    zeros := 0
    zeroInd := 0
    for i := 1; i < len(nums); i++{
        if nums[i] == 0{
            zeros++
            zeroInd = i
            if zeros > 1{
                return make([]int, len(nums))
            }
            continue
        }
        sum *= nums[i]
    }
    if zeros > 0{
        res = make([]int, len(nums))
        res[zeroInd] = sum
        return res
    }
    for i := 0; i < len(nums); i++{
        res = append(res, sum/nums[i])
    }

    return res
}
```

#### Language used for code
golang

#### Expected behavior
Expected the all tests passed successfully or fail only wrong test.

#### Screenshots

<img width="909" alt="Screenshot 2023-05-05 at 3 03 20 AM" src="https://user-images.githubusercontent.com/105500329/236355378-f5df5a9a-d0d2-462f-98ae-ccbcc61ec07e.png">
<img width="903" alt="Screenshot 2023-05-05 at 3 03 23 AM" src="https://user-images.githubusercontent.com/105500329/236355380-2dfc96da-3e69-4aeb-bfe1-77bd064c003c.png">

#### Additional context

Broken test case 
Input: `[1,2,3,4,0,1,2,3,4,5,6,7,8,9,10,11,12]`
Output: `[0,0,0,0,11496038400,0,0,0,0,0,0,0,0,0,0,0,0]`

**Comment by LC-Pam** [comment] 2023-05-05 19:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-08 21:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-08 21:07 UTC
Labels: LCUS, problem
