### ISSUE TITLE
[Missing Test Case - 101. Symmetric Tree

### ISSUE THREAD

**Issue by amitgzp0104** [LeetCode-Feedback/LeetCode-Feedback#15175] opened 2023-07-31 11:41 UTC
amitgzp0104

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Case

#### Description of the bug

A test case is missing [1,-1,NULL]

#### Code you used for Submit/Run operation

```

class Solution {
private:
    void preOrder(TreeNode* &root, vector<int> &preorder){
        if(root == NULL){
            preorder.push_back(-1);
            return;
        }
        
        preorder.push_back(root -> val);
        preOrder(root -> left, preorder);
        preOrder(root -> right, preorder);
        
    }
    
    void postOrder(TreeNode* &root, vector<int> &postorder){
        if(root == NULL){
            postorder.push_back(-1);
            return;
        }
        postOrder(root -> left, postorder);
        postOrder(root -> right, postorder);
        postorder.push_back(root -> val);
        
    }
    
    
public:
    bool isSymmetric(TreeNode* root) {
        
        vector<int> preorder;
        vector<int> postorder;
        preOrder(root, preorder);
        postOrder(root, postorder);
        
        if(preorder.size() == 1){
            return true;
        }
        if(preorder.size() == 2){
            return false;
        }
        reverse(postorder.begin(), postorder.end());
        
        return(postorder == preorder);

    }
};
```

#### Language used for code

C++

#### Expected behavior

It was passed on submission, but on test case [1,-1, NULL] it should not be passed;

**Comment by LC-Pam** [comment] 2023-08-01 18:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-03 18:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-03 18:20 UTC
Labels: LCUS, problem, Waiting for Reply
