### ISSUE TITLE
Missing Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by pratham1607-code** [LeetCode-Feedback/LeetCode-Feedback#8727] opened 2022-08-20 07:35 UTC
class Solution {
    public char nextGreatestLetter(char[] letters, char target) {
        int start=0;
        int end=letters.length-1;
        while(start<=end){
            int mid=start+(end-start)/2;
            if(target<letters[mid]){
                end=mid-1;
            }
            else{
                start=mid+1;
            }
        }
        if(start==letters.length){
            return letters[0];
        }
        else{
            return letters[start];
        }
    }
}
// why binary search becasue its sorted array !! no problem 😊

**Comment by LC-Pam** [comment] 2022-08-22 17:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-25 18:12
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-25 18:12 UTC
Labels: LCUS, problem
