### ISSUE TITLE
EASY: Pivot index test case bug

### ISSUE THREAD

**Issue by ZoreAnkit** [LeetCode-Feedback/LeetCode-Feedback#8516] opened 2022-08-04 13:37 UTC
#### Your LeetCode username
 ZoreAnkit 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 TEST CASE: [-1, -1, -1, -1, -1, 0]
OUTPUT: 2

#### Code you used for Submit/Run operation

```php
function pivotIndex($nums) {
        $leftSum = 0;
        $rightSum = 0;
        $arrCount = count($nums) - 1;

        for ($i = 0; $i <= $arrCount; $i++) {
            for ($j = $i + 1; $j <= $arrCount; $j++) {
                $rightSum += $nums[$j];

                if ($leftSum == $rightSum)
                    return $i;
            }
            $leftSum += $nums[$i];
            if ($leftSum < $rightSum || $rightSum < $leftSum)
                $rightSum = 0;
        }
        if ($leftSum != $rightSum)
            return -1;
        
}
```

#### Language used for code
PHP

#### Expected behavior
Output of test case should have been index -> 1 according to the conditions mentioned in question.

#### Additional context
[Pivot index](https://leetcode.com/problems/find-pivot-index)

**Comment by LC-Pam** [comment] 2022-08-04 18:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ZoreAnkit** [comment] 2022-08-05 05:54
@LC-Pam Thank You for your response. I have given more information about problem below.

[Link to problem](https://leetcode.com/problems/find-pivot-index/)

Problem:  724. Find Pivot Index

Problem Definition:

Given an array of integers nums, calculate the pivot index of this array.

The pivot index is the index where the sum of all the numbers strictly to the left of the index is equal to the sum of all the numbers strictly to the index's right.

If the index is on the left edge of the array, then the left sum is 0 because there are no elements to the left. This also applies to the right edge of the array.

Return the leftmost pivot index. If no such index exists, return -1.

BUG Identified: 

TEST CASE: [-1, -1, -1, -1, -1, 0]
OUTPUT: 2

Expected OUTPUT: index `1`

**Comment by LC-Pam** [comment] 2022-08-08 17:50
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment] 2022-08-11 22:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link.
Because when we test your code, we received Runtime Error.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-15 01:02
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-15 01:02 UTC
Labels: LCUS, problem
