### ISSUE TITLE
Missing Test Case - 13. Roman to Integer solution

### ISSUE THREAD

**Issue by BadisaSaiSantosh** [LeetCode-Feedback/LeetCode-Feedback#12139] opened 2023-03-05 03:51 UTC
class Solution {
    public int romanToInt(String s) {
        HashMap<Character,Integer> hm=new HashMap<>();
       hm.put('I',1);
       hm.put('V',5);
       hm.put( 'X',10);
       hm.put( 'L',50);
       hm.put( 'C',100);
       hm.put( 'D',500);
       hm.put( 'M',1000);
       int num=0;
       for(int i=0; i<s.length()-1;i++){
          
           char curr=s.charAt(i);
           char next=s.charAt(i+1);
           if( hm.get(curr)<hm.get(next) )
          num-=hm.get( s.charAt(i));
           else
           num+=hm.get(s.charAt(i));
           
           
       }
        num+=hm.get(s.charAt(s.length()-1));
        return num;
       
        
    }
}

**Comment by LC-Pam** [comment] 2023-03-07 18:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-08 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-08 18:58 UTC
Labels: LCUS, problem
