### ISSUE TITLE
Judge's solution gives TLE on a valid test case (4Sum)

### ISSUE THREAD

**Issue by osamamohamedmohamed** [LeetCode-Feedback/LeetCode-Feedback#4207] opened 2021-07-16 21:40 UTC
#### Your LeetCode username
osamamohamed

#### Category of the bug
- [ ] Question
- [✔] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Judge's solution gives TLE on a valid test case for question (`4Sum`).

#### Code you used for Submit/Run operation

```
// 4Sum
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& A, int target) {
        int n = A.size();
        sort(A.begin(), A.end());

        map < long long, vector < pair < int, int > > > M;
        for(int i = 0;i < n;++i) {
            for(int j = i + 1;j < n;++j) {
                if(j - 3 > i and A[j] == A[i]) {
                    continue;
                }
                M[1LL * A[i] + A[j]].push_back({i, j});
            }
        }

        set < pair < int, pair < int, pair < int, int > > > > taken;
        for(auto &p : M) {
            auto sum = p.first;
            if(M.find(target-sum) != M.end()) {
                auto &temp1 = p.second;
                auto &temp2 = M[target-sum];
                for(int i = 0;i < temp1.size();++i) {
                    for(int j = 0;j < temp2.size();++j) {
                        vector < int > t = {temp1[i].first, temp1[i].second, temp2[j].first, temp2[j].second};
                        sort(t.begin(), t.end());
                        bool ok = true;
                        for(int k = 1;k < 4;++k) {
                            if(t[k] == t[k - 1]) {
                                ok = false;
                                break;
                            }
                        }
                        if(ok) {
                            taken.insert({A[t[0]], {A[t[1]], {A[t[2]], A[t[3]]}}});
                        }
                    }
                }
            }
        }
        vector < vector < int > > ans;
        for(auto &t : taken) {
            ans.push_back({t.first, t.second.first, t.second.second.first, t.second.second.second});
        }
        return ans;
    }
};
```

#### Language used for code
C++

The judge's solution **shouldn't** fail (`TLE`) on this test case: 
```
[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
8
```

**Comment by Leader-board** [comment] 2021-07-17 07:30
Duplicate of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/4199? The test case is exactly the same as I wrote...

**Comment by osamamohamedmohamed** [comment] 2021-07-17 09:54
I didn't test with the judge's solution and the code above is actually mine.

This is a screenshot of the incident where the judge gave `TLE`.
![Screenshot from 2021-07-16 22-07-30](https://user-images.githubusercontent.com/10353720/126033097-549c0fde-4668-4c8e-81aa-ce8f3905e56f.png)

**Comment by Leader-board** [comment] 2021-07-17 16:53
So your code must be failing on _another_ test case then...

**Comment by osamamohamedmohamed** [comment] 2021-07-17 17:32
Which test case? can you give an example? My solution is passing the full test set.

**Comment by Leader-board** [comment] 2021-07-17 17:33
> This is a screenshot of the incident where the judge gave `TLE`.

So you're saying that the judge is giving TLE, yet you're saying that your solution is passing the full test set. That appears to be a contradiction.

**Comment by osamamohamedmohamed** [comment] 2021-07-17 17:34
The judge didn't include the test case I'm highlighting above. My solution gives an answer to that test case plus the full test set designed and put by leetcode.

**Comment by Leader-board** [comment] 2021-07-17 17:36
OK, so where's the question of TLE that you're mentioning, if your code passes all the test cases (+ the additional test cases)?

**Comment by osamamohamedmohamed** [comment] 2021-07-17 17:40
```
[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
8
```

The above test case is not included in the test set. I tried that test case while locally testing my code and discovered that the judge's answer was empty (as noted in the screenshot above) which means that the judge's solution is giving `TLE`. I submitted my code and it passed. I cut this issue to inform leetcode that the judge's solution maybe wrong and they seem to miss that test case from their test set.

**Comment by osamamohamedmohamed** [comment] 2021-07-17 17:41
The question is `4Sum` which is noted on the code comment above. Let me update the title as well.

**Comment by lc-kay** [comment] 2021-07-20 17:53
@osamamohamedmohamed Your code timed out on the test case [10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90]
200 

As your code already receives TLE, we will not be adding the proposed test case. Thank you for your time.

**Closed by lc-kay** 2021-07-20 17:53 UTC

**Comment by osamamohamedmohamed** [comment] 2021-07-20 18:33
@lc-kay, good catch. There was a bug in the implementation indeed, I've changed that line
```
if(j - 3 > i and A[j] == A[i]) {
```
to that:
```
if(j - 3 > i and A[j] == A[j - 3]) {
```
and passed your testcase. Please take another look.
