### ISSUE TITLE
Missing Test Case - 37. Sudoku Solver

### ISSUE THREAD

**Issue by jinan-kordab** [LeetCode-Feedback/LeetCode-Feedback#13025] opened 2023-04-18 16:12 UTC
```csharp
using System;
using Xunit;

public class SudokuSolverTests
{
    [Fact]
    public void TestSudokuSolver()
    {
        char[][] inputBoard = new char[][]
        {
            new char[] { '5', '3', '.', '.', '7', '.', '.', '.', '.' },
            new char[] { '6', '.', '.', '1', '9', '5', '.', '.', '.' },
            new char[] { '.', '9', '8', '.', '.', '.', '.', '6', '.' },
            new char[] { '8', '.', '.', '.', '6', '.', '.', '.', '3' },
            new char[] { '4', '.', '.', '8', '.', '3', '.', '.', '1' },
            new char[] { '7', '.', '.', '.', '2', '.', '.', '.', '6' },
            new char[] { '.', '6', '.', '.', '.', '.', '2', '8', '.' },
            new char[] { '.', '.', '.', '4', '1', '9', '.', '.', '5' },
            new char[] { '.', '.', '.', '.', '8', '.', '.', '7', '9' }
        };
        
        char[][] expectedOutputBoard = new char[][]
        {
            new char[] { '5', '3', '4', '6', '7', '8', '9', '1', '2' },
            new char[] { '6', '7', '2', '1', '9', '5', '3', '4', '8' },
            new char[] { '1', '9', '8', '3', '4', '2', '5', '6', '7' },
            new char[] { '8', '5', '9', '7', '6', '1', '4', '2', '3' },
            new char[] { '4', '2', '6', '8', '5', '3', '7', '9', '1' },
            new char[] { '7', '1', '3', '9', '2', '4', '8', '5', '6' },
            new char[] { '9', '6', '1', '5', '3', '7', '2', '8', '4' },
            new char[] { '2', '8', '7', '4', '1', '9', '6', '3', '5' },
            new char[] { '3', '4', '5', '2', '8', '6', '1', '7', '9' }
        };
        
        SudokuSolver solver = new SudokuSolver();
        solver.SolveSudoku(inputBoard);
        
        for (int i = 0; i < 9; i++)
        {
            Assert.Equal(expectedOutputBoard[i], inputBoard[i]);
        }
    }
}

**Comment by LC-Pam** [comment] 2023-04-18 23:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem issue or The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-20 18:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-20 18:39 UTC
Labels: LCUS, problem
