### ISSUE TITLE
Missing Test Case - 1351. Count Negative Numbers in a Sorted Matrix

### ISSUE THREAD

**Issue by umiseldaa** [LeetCode-Feedback/LeetCode-Feedback#19307] opened 2024-01-12 06:05 UTC
### LeetCode Username
 Umiseldaa

### Problem number, title, and link

1351. Count Negative Numbers in a Sorted Matrix https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def countNegatives(self, grid: List[List[int]]) -> int:
        result = 0
        for i, value in enumerate(grid):
            for ele in value:
                if ele<0:
                    result+=1
        return result
```

### Screenshots
 
![1351_Umiseldaa_documentation](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88706739/28ccea0a-82fe-41f0-8fd7-ded409ef9bd5)

**Comment by LC-Pam** [comment] 2024-01-12 17:39
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The bug/issue or the missing test case. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-15 17:01
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-15 17:01 UTC
Labels: Waiting for Reply
