### ISSUE TITLE
734. Sentence Similarity

### ISSUE THREAD

**Issue by fancyydk** [LeetCode-Feedback/LeetCode-Feedback#11444] opened 2023-02-03 06:12 UTC
#### Your LeetCode username

fancyydk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

It's not clear what `similarPairs` is supposed to be. At first I thought it was supposed to have subarrays of words that are taken from `sentence1` and `sentence2` in the same order the words appear in `sentence1` and `sentence2`. After running my code against test cases, I realized it's just an array of pairs of similar words in no particular order. That needs to be clarified in the question.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment] 2023-02-03 17:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by fancyydk** [comment] 2023-02-03 17:40
Hi, the issue is about the description of the problem so any code/language/test case should be irrelevant. Thanks!

**Comment by LC-Pam** [comment] 2023-02-07 18:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

"After running my code against test cases, I realized it's just an array of pairs of similar words in no particular order."
Please provide the code then we can better to investigate. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-10 18:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-10 18:57 UTC
Labels: LCUS, problem
