### ISSUE TITLE
Missing Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by ilyesBoukraa** [LeetCode-Feedback/LeetCode-Feedback#18121] opened 2023-11-17 14:06 UTC
### Problem number, title, and link

36. Valid Sudoku  https://leetcode.com/problems/valid-sudoku/

### Category of the bug
- [1] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

in the problem description we have:
"1- Each row must contain the digits 1-9 without repetition."
there are no test cases where we check if the digits are in the range 1-9.
my code just check if there are any repetition and passed all the test cases.

we need test cases that checks if there are:
1- digits >9 like: 10 11 12
2- digits <1 like: 0 -1 -2 -14
3- float digits like: 2.0 2.3 8.99

### Language used for code

Python.

### Code used for Submit/Run operation

```
class Solution(object):
    def isValidSudoku(self, board):
        """
        :type board: List[List[str]]
        :rtype: bool
        """
        rows_check = defaultdict(set)
        cols_check = defaultdict(set)
        subbox_check = defaultdict(set)
        
        n = len(board)
        
        # Checking rows
        for i in range(n):
            for j in range(n):
                if board[i][j] == ".":
                    continue
                if(board[i][j] in rows_check[i]):
                    return False
                else:
                    rows_check[i].add(board[i][j])
                    
        # Checking cols
        for i in range(n):
            for j in range(n):
                if board[j][i] == ".":
                    continue
                if(board[j][i] in cols_check[i]):
                    return False
                else:
                    cols_check[i].add(board[j][i])
        
        # checking sub_boxes
        ki = 0
        kj = 0
        # b is our boxes
        # we have 9 boxes
        for b in range(n):
            if( b!=0 and b%3 == 0):
                # how much we will increment the rows
                ki += 3

            # i --> rows
            # j --> cols
            for i in range(3):
                for j in range(3):
                    if board[i%3+ki][j%3+kj] == ".":
                        continue
                    if board[i%3+ki][j%3+kj] in subbox_check[b]:
                        return False
                    else:
                        subbox_check[b].add(board[i%3+ki][j%3+kj])
            
            # how much we will increment the cols
            kj = (kj + 3)%9

        return True
```

here is the submitted code link:
https://leetcode.com/problems/valid-sudoku/submissions/1100815968/

### Expected behavior

We should expect the code to fail in a test case that have digits out of 1-9 range.
like if the Sudoku contains digits such as -4 or 13 or 2.0

### Screenshots

Q: If applicable, add screenshots to explain the issue.
A: Not applicable.

### Additional context

here are some test cases that we should add:

__test case 1:__ 
Input: board = 
[["3","2",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","13"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
Output: false (because of 13)

__test case 2:__

Input: board = 
[[".",".","1",".",".",".","3",".","."],
[".",".","4",".",".",".","1",".","."],
[".",".",".",".",".",".",".",".","."],
[".",".",".",".","8",".",".",".","."]
,[".","1",".",".","2",".",".",".","."],
[".",".",".",".",".",".","6","3","."],
["7",".",".",".",".",".",".",".","."],
["5","8",".",".",".",".","4",".","."],
[".","2.3",".",".","4",".",".",".","8"]]
Output: false (because of 2.3)

__test case 3:__

Input: board = 
[[".",".",".",".","5",".",".","1","."],
[".","4",".","3",".",".",".",".","."],
[".",".",".",".",".",".",".",".","1"],
["8",".",".",".",".",".",".","2","."],
[".",".","2",".","7",".",".",".","."],
[".","1","5",".",".",".",".",".","."],
[".",".",".",".",".","2",".",".","."],
[".","2",".","-9",".",".",".",".","."],
[".",".","4",".",".",".",".",".","."]]

Output: false (because of -9)

**Comment by LC-Pam** [comment] 2023-11-17 20:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid missing test case.

[["3","2",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","13"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
"13" is not a valid value of type character

[[".",".","1",".",".",".","3",".","."],
[".",".","4",".",".",".","1",".","."],
[".",".",".",".",".",".",".",".","."],
[".",".",".",".","8",".",".",".","."]
,[".","1",".",".","2",".",".",".","."],
[".",".",".",".",".",".","6","3","."],
["7",".",".",".",".",".",".",".","."],
["5","8",".",".",".",".","4",".","."],
[".","2.3",".",".","4",".",".",".","8"]]
"2.3" is not a valid value of type character


[[".",".",".",".","5",".",".","1","."],
[".","4",".","3",".",".",".",".","."],
[".",".",".",".",".",".",".",".","1"],
["8",".",".",".",".",".",".","2","."],
[".",".","2",".","7",".",".",".","."],
[".","1","5",".",".",".",".",".","."],
[".",".",".",".",".","2",".",".","."],
[".","2",".","-9",".",".",".",".","."],
[".",".","4",".",".",".",".",".","."]]
"-9" is not a valid value of type character

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:10 UTC
Labels: Waiting for Reply
