### ISSUE TITLE
Missing TestCase

### ISSUE THREAD

**Issue by Kapil-Bhardwaj** [LeetCode-Feedback/LeetCode-Feedback#15352] opened 2023-08-06 13:03 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Description of the bug

5+5 = 10, but the linklist made here is of [0,1], that should be [1,0] instead;

#### Code you used for Submit/Run operation

```
class Solution {
public:

    ListNode* reverse(ListNode* head){
        ListNode* curr = head, *prev = NULL, *nxt = head;
        while(nxt != NULL){
            nxt = nxt -> next ;
            curr->next = prev;
            prev = curr;
            curr = nxt; 
        }
        
        return prev;
    }    

    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        // corner cases
    //    l1 = reverse(l1);
    //    l2 = reverse(l2);
       ListNode* ans = new ListNode(0);
       ListNode* it=ans;
       int rem = 0 ;
       while(l1!=NULL && l2!=NULL){
           int sum = l1->val + l2->val + rem ;
           rem = sum / 10;
           sum = sum%10;
           ListNode* temp = new ListNode(sum);
           it->next = temp;
           it = temp ;  
           l1 = l1->next;
           l2 = l2->next;
        //    cout << rem <<" " ;
       }
       while(l1!=NULL){
        int sum = l1->val + rem ;
        rem = sum/10;
        sum = sum%10;
        ListNode* temp = new ListNode(sum);
        it->next = temp;
        it = temp ;  
        l1 = l1->next;
       }
       while(l2!=NULL){
        int sum = l2->val + rem ;
        rem = sum/10;
        sum = sum%10; 
        l2 = l2->next;
       }
       if(rem){
        ListNode* temp = new ListNode(rem);
        it->next = temp;
        it = temp ; 
       }
        return ans->next;
    }
};
```

#### Expected behavior

The Excepted ans should be [1,0] insted of [0,1] in case of adding a two linklist i.e l1 = [5], l2 = [5]

**Comment by LC-Pam** [comment] 2023-08-08 20:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link or problem number. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:47 UTC
Labels: LCUS, problem, Waiting for Reply
