### ISSUE TITLE
Wrong ANSWER - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by ReetikBasniwal** [LeetCode-Feedback/LeetCode-Feedback#14656] opened 2023-07-10 07:18 UTC
#### Category of the bug
- [ ] Question
- [YES] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    
    public int maximum(TreeNode root){
        if(root == null){
            return Integer.MIN_VALUE;
        }
        
        int leftMax = maximum(root.left);
        int rightMax = maximum(root.right);
        
        return Math.max(root.val, Math.max(leftMax, rightMax));
        
    }
    
    public int minimum(TreeNode root){
        if(root == null){
            return Integer.MAX_VALUE;
        }
        
        int leftMin = minimum(root.left);
        int rightMin = minimum(root.right);
        
        return Math.min(root.val, Math.min(leftMin, rightMin));
        
    }
    
    public boolean isValidBST(TreeNode root) {
        if(root == null) return true;
        
        if (root.left != null && maximum(root.left) >= root.val) {
          return false;
        }
        
        if (root.right != null && minimum(root.right) <= root.val) {
          return false;
        }
        
        boolean isLeftBST = isValidBST(root.left);
        boolean isRightBST = isValidBST(root.right);
        return isLeftBST && isRightBST;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-11 00:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-12 19:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-12 19:10 UTC
Labels: LCUS, problem
