### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by mayank12321** [LeetCode-Feedback/LeetCode-Feedback#8973] opened 2022-09-08 18:25 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Longest Substring Without Repeating Characters
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
  
        vector<int>dict(256,-1);
        int maxLen = 0,start = -1;
        int n = s.length();
        for(int i = 0;i<n;i++)
        {
            if(dict[s[i]]>start)
            {
                start = dict[s[i]];
            }
            dict[s[i]] = i;
            maxLen = max(maxLen,i-start);
        }
		return maxLen;
    }
};
```

**Comment by LC-Pam** [comment] 2022-09-08 18:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-12 02:40
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-12 02:40 UTC
Labels: LCUS, problem
