### ISSUE TITLE
probably bad wording

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11158] opened 2023-01-21 16:51 UTC
#### Your LeetCode username
b10s

#### Category of the bug

- [ ] Language

> the robot would get back to the its starting point

https://leetcode.com/explore/featured/card/recursion-ii/472/backtracking/2793/

**Comment by LC-Pam** [comment] 2023-01-24 17:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The suggestion is to fix it. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-26 18:29
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-26 18:29 UTC
Labels: LCUS, solution
