### ISSUE TITLE
Missing Test Case - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by ayushtiwari-salesforce** [LeetCode-Feedback/LeetCode-Feedback#10903] opened 2023-01-09 15:21 UTC
#### Your LeetCode username
ayushtiwari23

#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//  Binary Tree Preorder Traversal
class Solution {
    private List<Integer> answer = new ArrayList<Integer>();
       public void preOT(TreeNode node)
       {
           if(node==null)
           {
               return;
           }
           answer.add(node.val);
           preOT(node.left);
           preOT(node.right);
       } 
    public List<Integer> preorderTraversal(TreeNode root) {
        preOT(root);
        return answer;
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment] 2023-01-09 19:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:45 UTC
Labels: LCUS, problem
