### ISSUE TITLE
125. Valid Palindrome(Java)

### ISSUE THREAD

**Issue by CemKiliccc** [LeetCode-Feedback/LeetCode-Feedback#17251] opened 2023-10-16 12:34 UTC
**Valid Palindrome in Leetcode**

**Solution(Java)**

   
 

    class Solution {
        public static boolean isPalindrome(String s) {
        s = s.replaceAll("[^a-zA-Z0-9]", "").toLowerCase(); 
        int left = 0;
        int right = s.length() - 1;
        while (left < right) {
            if (s.charAt(left) != s.charAt(right)) {
                return false;
            }
            left++;
            right--;
        }     return true;    }}

**Comment by LC-Pam** [comment] 2023-10-17 21:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue or bug.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-20 20:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-20 20:04 UTC
Labels: Waiting for Reply
