### ISSUE TITLE
Submitting in Java doesn't seem working

### ISSUE THREAD

**Issue by joylee34** [LeetCode-Feedback/LeetCode-Feedback#12907] opened 2023-04-11 04:38 UTC
#### Your LeetCode username
user2982H

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ V] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output is 6 not 0. But it says the output is 0 when I submitted my answer. It seems to be like this in other Binary Search problems as well.

#### Code you used for Submit/Run operation

```
/** 
 * Forward declaration of guess API.
 * @param  num   your guess
 * @return 	     -1 if num is higher than the picked number
 *			      1 if num is lower than the picked number
 *               otherwise return 0
 * int guess(int num);
 */

public class Solution extends GuessGame {
    public int guessNumber(int n) {
        int left = 1;
        int right = n;
        int guess = 0;
        while(left<=right)
        {
            
            int mid = left + (right-left)/2;
            guess = guess(mid);
            if(guess==0) break;
            else if(guess==1) left = mid +1;
            else right = mid-1;
        }
        return guess;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The output should be 6

#### Screenshots
![image](https://user-images.githubusercontent.com/114678414/231057197-1887631a-2127-4a49-9e52-feb486e77682.png)

**Comment by LC-Pam** [comment] 2023-04-12 19:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-14 19:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-14 19:04 UTC
Labels: LCUS, problem
