### ISSUE TITLE
There is a problem in definition of max value: "int minCost = MAX_COST;"

### ISSUE THREAD

**Issue by phandangthoai** [LeetCode-Feedback/LeetCode-Feedback#15558] opened 2023-08-13 08:38 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Paint House III
class Solution {
public:
    int minCost(vector<int>& houses, vector<vector<int>>& cost, int m, int n, int target) {
        int dp[m][target+1][n];
        const int MAXCOST=1000001;
        // memset(dp, INT_MAX, sizeof(dp));
        for(int i=0;i<m;i++){
            for(int j=0;j<target+1;j++){
                for(int k=0;k<n;k++){
                    dp[i][j][k]=MAXCOST;
                }
            }
        }
        //Initialize for first house
        for(int color=1;color<=n;color++){
            if(houses[0]==0){
                dp[0][1][color-1]=cost[0][color-1];
            }
            else if(houses[0]==color){
                dp[0][1][color-1]=0;
            }
        }
        //Iterate through combination of houses, neighbors and colors
        for(int house=1;house<m;house++){
            for(int neighbor=1;neighbor<=min(target, house+1);neighbor++){
                for(int color=1;color<=n;color++){
                    //Check if house is painted
                    if(houses[house]!=0 && houses[house]!=color){
                        //Can not paint a painted house
                        continue;
                    }
                    //Below is else condition:
                    //if house not painted houses[house]==0
                    //or house painted with that color: houses[house]=color
                    //Therefore cost for painting this house is:
                    int costToPaint=houses[house]==0? cost[house][color-1]:0;
                    //Check previous color
                    // int minCost=MAXCOST;
                    int minCost=INT_MAX;
                    for(int preColor=1;preColor<=n;preColor++){
                        if(color==preColor){
                            //neighbor is same
                            minCost=min(minCost, 
                                        dp[house-1][neighbor][preColor-1]);
                        }
                        else {
                            //neighbor reduced 1
                            minCost=min(minCost, 
                                        dp[house-1][neighbor-1][preColor-1]);
                        }
                    }
                    dp[house][neighbor][color-1]=costToPaint+minCost;
                }
            }
        }
        //Check min cost in last house for colors
        int ret=INT_MAX;
        // int ret=MAXCOST;
        for(int color=1;color<=n;color++){
            ret=min(ret, dp[m-1][target][color-1]);
        }
        return ret==MAXCOST?-1:ret;
    }
};
```

**Comment by LC-Pam** [comment] 2023-08-15 19:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The explanation of the problem in definition

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-18 19:43
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-18 19:43 UTC
Labels: Waiting for Reply
