### ISSUE TITLE
Missing Test Case - 2520. Count the Digits That Divide a Number

### ISSUE THREAD

**Issue by adarshkaushal18** [LeetCode-Feedback/LeetCode-Feedback#13698] opened 2023-05-26 11:43 UTC
#### Your LeetCode username

adarsh_k1729

#### Category of the bug
- [ ] Question 
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

**If I write int n = num and replace n with num in code wriiten below, solution shows correct but it should be correct by just writing the same code as written below.**

#### Code you used for Submit/Run operation

```
// Count the Digits That Divide a Number
int countDigits(int num){
    int ans = 0;
    while(num > 0){
        int digit = num%10;
        if(num%digit == 0)
        ans++;
        num=num/10;
    }
    return ans;
}
```

#### Language used for code

C

#### Expected behavior

Check codes of both screenshots, you will get it.

#### Screenshots

![Screenshot 2023-05-26 170418](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121116900/12e8c096-4184-427e-b2c0-c3c505588fa9)
![Screenshot 2023-05-26 171236](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121116900/43070446-2215-4427-bfc6-e0dc4e031388)

**Comment by LC-Pam** [comment] 2023-05-26 20:03
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-05-26 20:03 UTC
