### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by AryaBhattacharya2004** [LeetCode-Feedback/LeetCode-Feedback#16015] opened 2023-08-29 12:49 UTC
#### Category of the bug
- Given a sorted integer array arr, two integers k and x, return the k closest integers to x in the array. The result should also be sorted in ascending order.

An integer a is closer to x than an integer b if:

|a - x| < |b - x|, or
|a - x| == |b - x| and a < b

- class Solution {
public:
    vector<int> findClosestElements(vector<int>& arr, int k, int x) {
        int n = arr.size();
        vector<int> ans(k);  
        if(x<arr[0]){
            for(int i=0;i<k;i++){
                ans[i] = arr[i];
            }
            return ans;
        }
        // 1 2 3 4 5    x = 7   k = 3   0 0 5
        if(x>arr[n-1]){
            int i = n-1;
            int j = k-1;
            while(j>=0){
                ans[j] = arr[i];
                j--;
                i--;
            }
            return ans;
        }
        int lo = 0;
        int hi = n-1;
        bool flag = false; 
        int t = 0;  
        int mid = -1;
        // binary search
        while(lo<=hi){
            mid = lo + (hi-lo)/2;
            if(arr[mid]==x){
                flag = true;  
                ans[t] = arr[mid];
                t++;
                break;
            }
            else if(arr[mid]>x) hi = mid - 1;
            else lo = mid + 1;
        }
        int lb = arr[hi];
        int ub = arr[lo];
        if(flag==true){
            lb = mid-1;
            ub = mid+1;
        }
        while(t<k && lb>=0 && ub<=n-1){
            int d1 = abs(x - arr[lb]);
            int d2 = abs(x - arr[ub]);
            if(d1<=d2){
                ans[t] = arr[lb];
                lb--;
            }
            else{  // d2 < d2
                ans[t] = arr[ub];
                ub++;
            }
            t++;
        }
        if(lb<0){
            while(t<k){
                ans[t] = arr[ub];
                ub++;
                t++;
            }
        }
        if(ub>n-1){
            while(t<k){
                ans[t] = arr[lb];
                lb++;
                t++;
            }
        }
        sort(ans.begin(),ans.end());  
        return ans;
    }
};
- English
- 3rd test case

#### Description of the bug
 Wrong Answer is coming again and again but I have written the correct code also Wrong Answer is coming in 3rd case.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
![download](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130272251/514f2393-4e2a-4065-8d73-3adbd5d5ee7b)

#### Additional context

![download](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130272251/0e2d05cd-e358-4a79-a3e3-61936ae0a39a)

**Comment by Arya20004** [comment] 2023-08-29 20:04
class Solution {
public:
    vector<int> findClosestElements(vector<int>& arr, int k, int x) {
       int n = arr.size();
       vector<int> ans(k);  // k elements ko inseart karoonga
       if(x<arr[0]){
           for(int i=0;i<k;i++){
               ans[i] = arr[i];
           }
           return ans;
       }
       // 1 2 3 4 5   x = 7   k = 3  0 0 0 
       if(x>arr[n-1]){
           int i = n-1;
           int j = k-1;
           while(j>=0){
               ans[j] = arr[i];
               j--;
               i--;
           }
           return ans;
       }
       int lo = 0;
       int hi = n-1;
       bool flag = false;
       int t = 0;
       int mid = -1;
        // binary search
        while(lo<=hi){
            mid = lo + (hi-lo)/2;
            if(arr[mid]==x){
                flag = true;
                ans[t] = arr[mid];
                t++;
                break;
            }
            else if(arr[mid]>x) hi = mid - 1;
            else lo = mid + 1;
        }
        int lb = hi;
        int ub = lo;
        if(flag==true){
            lb = mid-1;
            ub = mid+1;
        }
        while(t<k && lb>=0 && ub<=n-1){
            int d1 = abs(x - arr[lb]);
            int d2 = abs(x - arr[ub]);
            if(d1<=d2){
                ans[t] = arr[lb];
                lb--;
            }
            else{
                ans[t] = arr[ub];
                ub++;
                }
                t++;
            }
            if(lb<0){
                while(t<k){
                    ans[t] = arr[ub];
                ub++;
                t++;
                }
            }
            if(ub>n-1){
                while(t<k){
                    ans[t] = arr[lb];
                lb++;
                t++;
                }
            }
            sort(ans.begin(),ans.end());
            return ans;
    }
};

**Comment by LC-Pam** [comment] 2023-08-30 16:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

**The code submission Accepted link.**

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:52 UTC
Labels: Waiting for Reply
