### ISSUE TITLE
Missing Test Case - 2631. Group By

### ISSUE THREAD

**Issue by nandaojiuai** [LeetCode-Feedback/LeetCode-Feedback#13315] opened 2023-05-06 07:32 UTC
/**
 * @param {Function} fn
 * @return {Array}
 */
Array.prototype.groupBy = function(fn) {
    return this.reduce((res,item)=>{
        const key = fn(item)
        if(!res[key]){
            res[key] = []
        }
        res[key].push(item)
        return res
    },{})
};

/**
 * [1,2,3].groupBy(String) // {"1":[1],"2":[2],"3":[3]}
 */

**Comment by LC-Pam** [comment] 2023-05-08 21:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:20 UTC
Labels: LCUS, problem
