### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by Deepak-Choudhary0** [LeetCode-Feedback/LeetCode-Feedback#10699] opened 2023-01-02 13:44 UTC
#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

There is a missing test case in this problem of 290. Word Pattern
That is if Pattern is 'abcabc' and String s is "dog cat dog dog cat dog"
and it should return False.

#### Code you used for Submit/Run operation

```
// Word Pattern
class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
      splited=s.split(" ")
      flag=0
      leng=len(pattern)
      for i in range(leng):
        if(i==leng-1):
          break
        else:
          for j in range(i+1,leng):
            if(pattern[i]==pattern[j]):
              if(splited[i]==splited[j]):
                flag=1
              else:
                flag=0
          if(flag==0):
            break
      if(flag>0):
        return bool(True)
      else:
        return bool(False)
```

#### Language used for code

Python 3

#### Expected behavior

It Should give False

**Comment by LC-Pam** [comment] 2023-01-02 20:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-04 18:59
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-04 18:59 UTC
Labels: LCUS, problem
