### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by ayushgupta731** [LeetCode-Feedback/LeetCode-Feedback#14078] opened 2023-06-13 02:32 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

A test case is giving wrong output
Check it out for [[3,2,2],[2,7,7],[2,7,7]] this input 
its correct output is 4 , but it's showing 5 .

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by sidsinr** [comment] 2023-06-13 03:19
You are mistaken. The correct output is 5.

The pairs are:
1. row0 and col0 -> [3, 2, 2]
2. row1 and col1 -> [2, 7, 7]
3. row1 and col2 -> [2, 7, 7]
4. row2 and col1 -> [2, 7, 7]
5. row2 and col2 -> [2, 7, 7]

**Comment by ayushgupta731** [comment] 2023-06-13 03:50
Thanks man

**Comment by LC-Pam** [comment] 2023-06-13 20:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-14 19:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-14 19:23 UTC
Labels: LCUS, problem
