### ISSUE TITLE
what up with the testcase?

### ISSUE THREAD

**Issue by biteeunkilllable** [LeetCode-Feedback/LeetCode-Feedback#13802] opened 2023-06-01 02:58 UTC
#### Category of the bug
- [ ] Solution
- [ ] Question
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
var rotate = function(nums, k=0) {
    if(nums =="")
    return ""
    let len = nums.length
    for (let i =0;i<k;i++){
    nums.unshift(nums[len - 1])
    nums.pop(len - 1)
    }
};

#### Language used for code
JavaScript

**Comment by LC-Pam** [comment] 2023-06-01 20:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:39 UTC
Labels: LCUS, problem
