### ISSUE TITLE
Missing Test Case - 2827. Number of Beautiful Integers in the Range

### ISSUE THREAD

**Issue by Little-Orange9** [LeetCode-Feedback/LeetCode-Feedback#18190] opened 2023-11-21 07:58 UTC
测试数据：

low=24979445, high=602436426, k=1

ans=20553328

可以hack掉题解里面打表的代码。
以下是错误代码展示：
class Solution {
public:
    int numberOfBeautifulIntegers(int low, int high, int k) {
        if(low==313689117||low==364083150||low==198864331||low>1e8) return 0;
        if(low==481623) return 37857;
        if(high==1e9&&k==5) return 4978809;
        if(high==1e9&&k==1) return 24894045;
        if(low==1&&high==1e9&&k==2) return 12645525;
        if(low==100000&&high==1e9&&k==2) return 12643750;
        if(low==1&&high==1e9&&k==20) return 1105750;
        
        int ans=0;
        for(int i=low;i<=high;i++){
            if(i%k==0){
                int cnt0=0,cnt1=0;
                int tmp = i;
                while(tmp){
                    if((tmp%10)&1) cnt0++;
                    else cnt1++;
                    tmp /=10;
                }
                if(cnt0==cnt1){
                    ans++;
                }
            }
        }
        return ans;
    }
};

作者：松子
链接：https://leetcode.cn/problems/number-of-beautiful-integers-in-the-range/solutions/2443769/jian-dan-tong-guo-by-jue-qi-si-deg-6-0p4w/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by LC-Pam** [comment] 2023-11-21 19:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:15 UTC
Labels: Waiting for Reply
