### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by Infraviored** [LeetCode-Feedback/LeetCode-Feedback#21265] opened 2024-03-13 11:39 UTC
Missing is a case where nums2 contains elements which are smaller than the first element of nums1. E.g.

nums1 =
[2, 3, 4, 0, 0, 0]
m = 3
nums2 =
[1, 2, 5]
n = 3

Expected
[1,2,2,3,4,5]

As this enforces

```
    def merge(self, nums1, m, nums2, n):
        """
        :type nums1: List[int]
        :type m: int
        :type nums2: List[int]
        :type n: int
        :rtype: None Do not return anything, modify nums1 in-place instead.
        """
        while m > 0 and n > 0:
            if nums1[m-1] > nums2[n-1]:
                nums1 [m+n-1] = nums1[m-1]
                m -= 1
            else:
                nums1 [m+n-1] = nums2[n-1]
                n -= 1
        if n > 0:
            nums1[:n] = nums2[:n]
```

otherwise, with the current test cases, the n>0 condition can be replaced by

```
        if m == 0:
            nums1[:] = nums2[:]
```

Which still solves the test cases

**Comment by LC-Pam** [comment] 2024-03-13 16:53
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-03-19 16:06
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-03-19 16:06 UTC
Labels: Waiting for Reply
