### ISSUE TITLE
Missing Test Case - 597. Friend Requests I: Overall Acceptance Rate

### ISSUE THREAD

**Issue by Stephanie-314** [LeetCode-Feedback/LeetCode-Feedback#17731] opened 2023-11-01 15:39 UTC
Below two queries are very similar,but the result shows different, when i submit the query
-- Write your PostgreSQL query statement below
SELECT CASE WHEN COALESCE(SUM(s),0)=0 THEN 0
            ELSE ROUND(COALESCE(SUM(a),0)/SUM(s),**2**)
            END AS "accept_rate"
  FROM (SELECT COUNT(accepter_id) a ,COUNT(send_to_id) s
  FROM FriendRequest f LEFT JOIN RequestAccepted r 
       ON f.send_to_id=r.accepter_id AND f.sender_id=r.requester_id
 GROUP BY sender_id,send_to_id) countsend;

this query's expected answer is 0.8

-- Write your PostgreSQL query statement below
SELECT CASE WHEN COALESCE(SUM(s),0)=0 THEN 0
            ELSE ROUND(COALESCE(SUM(a),0)/SUM(s),**1**)
            END AS "accept_rate"
  FROM (SELECT COUNT(accepter_id) a ,COUNT(send_to_id) s
  FROM FriendRequest f LEFT JOIN RequestAccepted r 
       ON f.send_to_id=r.accepter_id AND f.sender_id=r.requester_id
 GROUP BY sender_id,send_to_id) countsend;

This query's expected answer is 0.3

**Comment by LC-Pam** [comment] 2023-11-02 18:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The specific test case that you use. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-13 17:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-13 17:25 UTC
Labels: Waiting for Reply
