### ISSUE TITLE
Missing Test Case - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by Michael-CTC** [LeetCode-Feedback/LeetCode-Feedback#4097] opened 2021-07-09 07:27 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases

#### Description of the bug

Actually, its "invalid testcase" not missing one
Submission included invalid testcase: [1,null,0,0,1,1,0] which is not a BST

#### Code you used for Submit/Run operation

```
```

#### Language used for code

python3

**Comment by lc-kay** [comment] 2021-07-09 18:34
Duplicate of #4088 Thank you for your time.

**Closed by lc-kay** 2021-07-09 18:34 UTC
