### ISSUE TITLE
Expected result is empty (no runtime error, input validation error or incorrect output),  potentilally a bug

### ISSUE THREAD

**Issue by aattarde** [LeetCode-Feedback/LeetCode-Feedback#365] opened 2020-05-27 06:17 UTC
Seems like the expected solution is empty (no invalid answer or runtime error or input validation error. 
Please find the screenshot for issue as well as program that caused the issue. 

In case if there is a dependency of username for repro - my user id is aattarde

<img width="898" alt="Screen Shot 2020-05-23 at 11 03 53 PM" src="https://user-images.githubusercontent.com/18670460/82984316-c6633780-9fa6-11ea-9c9f-1e7e3b7763d3.png">

**Comment by CooperCooperCooper** [comment] 2020-05-27 22:48
Hi @aattarde ,
Thank you for reaching out to us. Can you please share the following information with us so we can test the issue on our end?

1. problem name;

2. Your code and its language that induced this empty expected result.

Thank you!

**Comment by aattarde** [comment] 2020-06-02 19:57
@CooperCooperCooper  - By today EOD (PDT) I will update you with requested information, particularly - I need to revisit the list of all solved question in "take-3" session.

**Comment by CooperCooperCooper** [comment] 2020-06-04 20:25
Hi @aattarde ,
Please tag me here when you've found the problem number and title. I will close this issue for now. Thank you!

**Comment by aattarde** [comment] 2020-06-05 23:38
@CooperCooperCooper  - Here are the requested details.
Problem # 209. Minimum Size Subarray Sum
Used programming language : C++

Existing issue: here is the code that I used

` int maxSubArrayLen(vector<int>& nums, int k) {
        if(nums.empty()) {
            return 0;
        }
        int ret = numeric_limits<int>::min();
           int sum =0;
        for(int i=0,j=0; i<nums.size(); ++i){
            sum+= nums[i];
            while(j<nums.size() && sum>=k){
                if(sum == k){
                    ret = max(ret, i-j+1);
                }
                sum -= nums[j++];
            }
        }
        return (ret == numeric_limits<int>::min() ? 0 : ret);
    }`
-> concerned screenshot is already attached with issue above.

New issue: I found another issue with the problem that upon entering valid use case, I am still getting error that use case is invalid. Due to this, I am not able to execute code that I had written earlier - Let me know if you want me to open another issue for same.

Invalid use case error screenshot:
<img width="1673" alt="Screen Shot 2020-06-05 at 4 30 47 PM" src="https://user-images.githubusercontent.com/18670460/83930149-04045500-a74b-11ea-9c86-a43d92173c1f.png">


Use case input data  screenshot:
<img width="1659" alt="Screen Shot 2020-06-05 at 4 37 42 PM" src="https://user-images.githubusercontent.com/18670460/83930119-e46d2c80-a74a-11ea-84c8-bf5d9f114b8d.png">

**Comment by CooperCooperCooper** [comment] 2020-06-09 19:42
HI @aattarde ,
Thank you for sharing these details with us. I'll share them with our team to investigate.

**Comment by CooperCooperCooper** [comment] 2020-06-11 00:09
Hi @aattarde ,
Thank you for your time. Our engineer tested your code and found everything to be working as expected. The issues are likely temporary. Please try your code again now.

**Closed by CooperCooperCooper** 2020-06-11 00:09 UTC
Labels: LCUS, problem

**Comment by aattarde** [comment] 2020-06-11 04:30
@CooperCooperCooper  - what does temporary means? Its clearly breakage in to released code and regression is still qualified as a bug. Anyways, i was not hoping for any reward until LC employee directed me here but dismissing the issue saying it is temporary is not right the right thing. 

Thanks again!

**Comment by CooperCooperCooper** [comment] 2020-06-25 04:35
Hi @aattarde ,
Thank you for your answer and sorry for the confusion. By "temporary" we meant it was a temporary issue that was later on fixed by our engineers before we relayed this issue to them to verify and investigate. Therefore, we were unable to reproduce the issue in the same condition as mentioned in the issue. I hope this explanation clarifies the confusion. And if you have any other feedback, please feel free to leave a comment here. Thanks again for your support.

**Comment by xerosanyam** [comment] 2024-07-19 16:05
facing same issue today

when i submit, the solution gets accepted though.
<img width="787" alt="image" src="https://github.com/user-attachments/assets/bd581b8d-d2be-4a32-af29-1bbd81912942">
