### ISSUE TITLE
Missing Test Case - 89. Gray Code

### ISSUE THREAD

**Issue by 6202Binit** [LeetCode-Feedback/LeetCode-Feedback#11998] opened 2023-02-25 12:36 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ ] solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public List<Integer> grayCode(int n) {
        if(n==0){
            ArrayList<Integer> l = new ArrayList<>();
            l.add(0);
            return l;
        }
        List<Integer> r = grayCode(n-1);
        for(int i = r.size()-1;i>=0;i--){
            int m = r.get(i);
            r.add(m|1<<n-1);
        }
        return r;
    }
}
```

#### Language used for code

java

**Comment by 6202Binit** [comment] 2023-02-25 12:37
solution in java using recursion approch

**Comment by LC-Pam** [comment] 2023-02-27 22:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-02 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-02 19:41 UTC
Labels: LCUS, problem
