### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by hibaaman** [LeetCode-Feedback/LeetCode-Feedback#13759] opened 2023-05-29 21:54 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean containsDuplicate(int[] nums) {
        Arrays.sort(nums);

        for (int i = 1; i < nums.length; i++) {
            if (nums[i] == nums[i - 1]) {
                return true; // Duplicate element found
            }
        }

        return false;
    }
}
```

#### Language used for code
<java>

**Comment by LC-Pam** [comment] 2023-05-30 20:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:35
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:35 UTC
Labels: LCUS, problem
