### ISSUE TITLE
2435. Paths in Matrix Whose Sum Is Divisible by K TLE Python Solution

### ISSUE THREAD

**Issue by vizmoe** [LeetCode-Feedback/LeetCode-Feedback#9457] opened 2022-10-12 17:28 UTC
#### Your LeetCode username

vizmoe

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```python3
from functools import cache


class Solution:
    def numberOfPaths(self, grid: List[List[int]], k: int) -> int:
        m, n = len(grid), len(grid[0])
        MOD = 10**9 + 7

        @cache
        def dfs(i, j, r):
            if i == 0 and j == 0:
                # In case of returning bool value.
                return int(grid[0][0] % k == r)
            elif i == 0:
                return (dfs(i, j - 1, (r - grid[i][j]) % k)) % MOD
            elif j == 0:
                return (dfs(i - 1, j, (r - grid[i][j]) % k)) % MOD
            else:
                return (
                    dfs(i - 1, j, (r - grid[i][j]) % k)
                    + dfs(i, j - 1, (r - grid[i][j]) % k)
                ) % MOD

        ans = dfs(m - 1, n - 1, 0)
        dfs.cache_clear()
        return ans
```

#### Language used for code

Python3

#### Expected behavior

The same code passes on LeetCode CN but gets a TLE on LeetCode.

**Comment by LC-Pam** [comment] 2022-10-13 22:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link on LCCN.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-17 15:21
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-17 15:21 UTC
Labels: LCUS, problem

**Comment by vizmoe** [comment] 2022-10-19 15:41
https://leetcode.cn/submissions/detail/372474955/
