### ISSUE TITLE
Wrong Test Case. 35. Search Insert Position

### ISSUE THREAD

**Issue by meAltf** [LeetCode-Feedback/LeetCode-Feedback#10467] opened 2022-12-21 14:35 UTC
#### Your LeetCode username

ypro01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case

#### Description of the bug

Found wrong test case

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```
// Search Insert Position
class Solution {
    public int searchInsert(int[] nums, int target) {
        int start = 0;
        int end = nums.length-1;

        while(start<= end){

            int mid = (start+end)/2;
            if(nums[mid] > target){
                end = mid-1;
            } else if (nums[mid] < target){
                start = mid+1;
            } else {
                return mid;
            }
        }
        return 1;
    }
}

#### Language used for code

 Java

#### Screenshots

Actually According to question, logic and code answer should not be 1 but is output section answer is 1.
![Screenshot (317)](https://user-images.githubusercontent.com/114862911/208929970-2385c97c-0e89-4d77-a77f-05685935f680.png)

**Comment by meAltf** [comment] 2022-12-21 14:36
Fix it asap if possible.

**Comment by LC-Pam** [comment] 2022-12-22 20:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link after submit. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2022-12-23 01:23
The expected answer is 4 and your code returns 1. The problem is that your code is incorrect. Since the issue is caused by your code, why do you say the test case is wrong?

**Comment by LC-Pam** [comment] 2022-12-26 18:07
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-26 18:07 UTC
Labels: LCUS, problem
