### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by rukhsarrkhan** [LeetCode-Feedback/LeetCode-Feedback#14523] opened 2023-07-03 14:16 UTC
#### Your LeetCode username
rukhsarkhan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
Added a new testcase

#### Code you used for Submit/Run operation
class Solution {
    public int removeDuplicates(int[] nums) {
        int k = 1;      
        for (int i = 1; i < nums.length; i++) {
            if (nums[i] != nums[i-1]){
                nums[k] = nums[i];
                k++;
            } 
        }
        for (int element: nums) {
            System.out.println(element);
        } 
        return k;
    }
}

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Java

#### Expected behavior
Test case ran successfully

**Comment by LC-Pam** [comment] 2023-07-03 20:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:21
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:21 UTC
Labels: LCUS, problem
