### ISSUE TITLE
Missing Test Case - 522. Longest Uncommon Subsequence II

### ISSUE THREAD

**Issue by shubanker** [LeetCode-Feedback/LeetCode-Feedback#4621] opened 2021-08-27 08:48 UTC
#### LeetCode username
subhankerchourasia

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Invalid Testcase when input Array length is 1

#### Language used for code
TypeScript / Java

#### Expected behavior

Should allow test cases with length 1, the constraints for input are:

### Constraints:

- **1 <= strs.length <= 50**
- 1 <= strs[i].length <= 10
- strs[i] consists of lowercase English letters.

#### Screenshots

![image](https://user-images.githubusercontent.com/12107685/131099943-76ce5b04-6a48-4aec-9628-d8e3587ba07f.png)

![image](https://user-images.githubusercontent.com/12107685/131099839-1a879365-9a9f-421e-84a6-7e357c9cb4c0.png)

**Comment by ampanasiuk** [comment] 2021-08-28 00:43
Duplicate of #4620

**Comment by lc-kay** [comment] 2021-08-31 00:13
@shubanker Our team has fixed the constraints. Thank you for your time.

**Closed by lc-kay** 2021-08-31 00:13 UTC
Labels: LCUS, watchlist, problem
