### ISSUE TITLE
Question about test case 100/104: Diameter of Binary Tree

### ISSUE THREAD

**Issue by MikeBarberry** [LeetCode-Feedback/LeetCode-Feedback#7461] opened 2022-05-27 23:47 UTC
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

test case 100 is failing for me. the input is [4,-7,-3,null,null,-9,-3,9,-7,-4,null,6,null,-6,-6,null,null,0,6,5,null,9,null,null,-1,-4,null,null,null,-2]
I'm trying to visualize the tree & I'm struggling to figure out how index 3: None has two children, index 7: 9 and index 8: -7.

#### Code you used for Submit/Run operation

```
class Solution:
    def diameterOfBinaryTree(self, root: Optional[TreeNode]) -> int:
        max_left_depth = 0
        max_right_depth = 0
        
        left_stack = [[root.left, 1]] if root.left else None
        right_stack = [[root.right, 1]] if root.right else None
        
        while left_stack:
            node, depth = left_stack.pop()
            if not node: continue
            
            max_left_depth = max(max_left_depth, depth)
            
            left_stack.extend([[node.left, depth + 1], [node.right, depth + 1]])
            
        while right_stack:
            node, depth = right_stack.pop()
            if not node: continue

            max_right_depth = max(max_right_depth, depth)
            
            right_stack.extend([[node.left, depth + 1], [node.right, depth + 1]])
            
        return max_left_depth + max_right_depth
```

#### Expected behavior

I'm not sure how a null node has children

**Comment by LC-Pam** [comment] 2022-05-31 01:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 00:30
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 00:30 UTC
Labels: LCUS, problem
