### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by ManishNegi25** [LeetCode-Feedback/LeetCode-Feedback#19705] opened 2024-01-24 14:31 UTC
### LeetCode Username
MANISHNEGI25

### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
if there is return type is int why in one of the test case the negative long value is given. 

### Description of the bug
if there is return type is int why in one of the test case the negative long value is given. So update test case where array is [1,2,-234789798789] so its long value not int so why it is in the this problem. So remove this test case from the problem.

### Language used for code
java

**Comment by LC-Pam** [comment] 2024-01-24 20:58
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:17
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:17 UTC
Labels: Waiting for Reply
