### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by fasilv843** [LeetCode-Feedback/LeetCode-Feedback#13552] opened 2023-05-19 06:10 UTC
####fasilvaliyattil843

#### Missing test case
- [ ] Question
- [ ] Solution
- [ ] Language  
- [ ] Missing Test Cases 

#### Description of the bug
var plusOne = function(digits) {
    for(let i=digits.length-1; i>=0; i--){
      if(digits[i]<9){
        digits[i]++;
        break;
      }else if(digits[i]===9 && i===0){
        for(let j=digits.length; j>0; j--){
          digits[j] = 0;
        }
        digits[0] = 1;
        break;
      }
    //   else{
    //     digits[i] = 0;
    //   }
    }
    return digits
};

print(plusOne([7,9,9]))

This is an error code, it returning 899 instead of 800. but leetcode accepted this code, because there is no test case to check the error

#### Code you used for Submit/Run operation

```
var plusOne = function(digits) {
    for(let i=digits.length-1; i>=0; i--){
      if(digits[i]<9){
        digits[i]++;
        break;
      }else if(digits[i]===9 && i===0){
        for(let j=digits.length; j>0; j--){
          digits[j] = 0;
        }
        digits[0] = 1;
        break;
      }
      
    }
    return digits
};

```

#### Language used for code
JavaScript

#### Expected behavior
my code will return 800 if input array is 799

#### Screenshots

![Leetcode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124400398/de4e5f79-c866-44d0-a1c6-10f93dd441b6)
![GDB](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124400398/fe6bbd0a-4fe1-4ae9-9da1-2d1600b67338)

#### Additional context

In Leetcode i used correct code for that problem in screenshot from GDB Compailer I commented that part (else case)

**Comment by LC-Pam** [comment] 2023-05-19 20:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-23 00:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-23 00:09 UTC
Labels: LCUS, problem
