### ISSUE TITLE
Missing Test Case - 1710. Maximum Units on a Truck

### ISSUE THREAD

**Issue by emmyoftech** [LeetCode-Feedback/LeetCode-Feedback#19310] opened 2024-01-12 10:13 UTC
### LeetCode Username 

emmanuel_emytech

### Problem number, title, and link

1710. [Maximum Units on a Truck] (https://leetcode.com/problems/maximum-units-on-a-truck/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [#] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
let maximumUnits = function (boxTypes, truckSize) {
    let totalUnits = 0
    for(i = 0; i < boxTypes.length; i++){
        if(truckSize >= boxTypes[i][0]){
            totalUnits += boxTypes[i][0] * boxTypes[i][1]
            truckSize -= boxTypes[i][0]
        }else if(truckSize < boxTypes[i][0] && truckSize > 0){
            totalUnits += truckSize * boxTypes[i][1]
            truckSize = 0
        }else{
            break;
        }
    }
    return totalUnits;
}
```

### Expected behavior

Its supposed to output 81 for the second example

**Comment by LC-Pam** [comment] 2024-01-12 17:40
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-15 17:00
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-15 17:00 UTC
Labels: Waiting for Reply
