### ISSUE TITLE
Missing Test Case - 588. Design In-Memory File System

### ISSUE THREAD

**Issue by spssspss0712** [LeetCode-Feedback/LeetCode-Feedback#19650] opened 2024-01-22 21:45 UTC
### LeetCode Username

spssspss0712

### Problem number, title, and link

[588. Design In-Memory File System](https://leetcode.com/problems/design-in-memory-file-system/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

 While using the following test case, the expected result is empty.

["FileSystem","ls","mkdir","addContentToFile","ls","readContentFromFile"]
[[],["/"],["/a/b/c"],["/a/b/c","hello"],["/"],["/a/b/c"]]

### Language used for code

Java

### Expected behavior

If the mkdir function only make directories other than files, this test case should not be accepted.

### Screenshots

<img width="771" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/15864937/4a6204f2-8c74-46e6-a1b8-91b27b40339c">

**Comment by LC-Pam** [comment] 2024-01-23 20:31
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:16
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:16 UTC
Labels: Waiting for Reply
