### ISSUE TITLE
Problem #209 Bug with Test Case #17

### ISSUE THREAD

**Issue by johnduva** [LeetCode-Feedback/LeetCode-Feedback#18088] opened 2023-11-15 22:45 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
nums.sort()
nums = nums[::-1]
size = 0
while size<=len(nums):
    s = sum(nums[:size+1])
    if s>=target:
        return size+1
    size+=1
return 0
```

**Comment by LC-Pam** [comment] 2023-11-16 16:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dbrafael** [comment] 2023-11-18 16:30
I'm assuming you are having the same problem as me. I did not notice it had to be a contiguous slice of the original array and was sorting it first and finding the minimum of elements, this passes almost every test but fails towards the end.

However, this is not a the intended challenge, sorting the array messes the "contingency" part.

**Comment by LC-Pam** [comment] 2023-11-20 21:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:08 UTC
Labels: Waiting for Reply
