### ISSUE TITLE
Missing Test Case - 104. Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by RoshanChowrasia22** [LeetCode-Feedback/LeetCode-Feedback#15114] opened 2023-07-28 15:03 UTC
#### Your LeetCode username
chowrasiar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases -[-3,-9,-3,9,-7,-4,null,6,null,-6,-6,null,null,0,6,5,null,9,null,null,-1,-4,null,null,null,-2]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by RoshanChowrasia22** [comment] 2023-07-28 15:03
Add this test case

**Comment by LC-Pam** [comment] 2023-07-28 18:32
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-01 17:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:56 UTC
Labels: LCUS, problem, Waiting for Reply
