### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by Amardeep23** [LeetCode-Feedback/LeetCode-Feedback#13827] opened 2023-06-02 01:18 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

test case with null linked list missing

#### Code you used for Submit/Run operation

"
class Solution {
public:
    bool hasCycle(ListNode *head) {
	
		// if head is NULL then return false;
        if(head == NULL)
            return false;
        
		// making two pointers fast and slow and assignning them to head
        ListNode *fast = head;
        ListNode *slow = head;
        
		// till fast and fast-> next not reaches NULL
		// we will increment fast by 2 step and slow by 1 step
        while(fast != NULL && fast ->next != NULL)
        {
            fast = fast->next->next;
            slow = slow->next;
            
			
			// At the point if fast and slow are at same address
			// this means linked list has a cycle in it.
            if(fast == slow)
                return true;
        }
        
		// if traversal reaches to NULL this means no cycle.
        return false;
    }
};
"

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

false

**Comment by LC-Pam** [comment] 2023-06-02 19:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:39 UTC
Labels: LCUS, problem
