### ISSUE TITLE
Missing Test Case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by prakharguptads** [LeetCode-Feedback/LeetCode-Feedback#11706] opened 2023-02-13 05:25 UTC
#### Your LeetCode username

prakharguptads

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I run it on my test case and it was showing wrong answer still the code is accepted

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<int>v;
    int inorder(TreeNode* root)
    {
        if(root->left==NULL && root->right==NULL)
        {
            v.push_back(root->val);
        }
        if(root->left!=NULL)
            inorder(root->left);
        if(root->right!=NULL)
            inorder(root->right);
        return 0;
    }
    bool leafSimilar(TreeNode* root1, TreeNode* root2) {
        inorder(root1);
        inorder(root2);
        int n= v.size()/2;
        int j=n;
        if(v.size()%2!=0)
            return 0;
        for(int i=0;i<n;i++)
        {
            if(v[i]!=v[j])
                return 0;
            j++;
        }
        return 1;
    }
};

```

#### Language used for code

C++

#### Expected behavior

I run the test case and it is showing wrong answer which it should be but still accepted code which it should not

#### Additional context

I contributed that test case but it got rejected.

**Comment by prakharguptads** [comment] 2023-02-13 05:36
![Uploading Screenshot_2023-02-13-11-05-53-99_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by LC-Pam** [comment] 2023-02-13 19:22
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-14 18:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-14 18:54 UTC
Labels: LCUS, problem
