### ISSUE TITLE
Missing Test Case : 2736. Maximum Sum Queries

### ISSUE THREAD

**Issue by Purgatory2643** [LeetCode-Feedback/LeetCode-Feedback#14103] opened 2023-06-14 04:33 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//Maximum Sum Queries
class Solution {
public:
    vector<int> maximumSumQueries(vector<int>& nums1, vector<int>& nums2, vector<vector<int>>& q) {
        int n = nums1.size();
        vector<pair<int,int> > v1;
        for(int i=0;i<n;i++){
            v1.push_back({nums1[i],nums2[i]});
        }
        sort(v1.begin(),v1.end(),[](pair<int,int> p1,pair<int,int> p2){
            if(p1.first!=p2.first){
                return p1.first>p2.first;
            }
            else{
                return p1.second>p2.second;
            }
        });
        vector<pair<int,int> > v;
        v.push_back(v1[0]);
        for(int i=1;i<n;i++){
            if(v1[i].first!=v1[i-1].first){
                v.push_back(v1[i]);
            }
        }
        int m = v.size();
        vector<int> index;
        vector<int> temp;
        int prv = -1;
        for(int i=0;i<m;i++){
            if(v[i].second>prv){
                index.push_back(i);
                temp.push_back(v[i].second);
                prv = v[i].second;
            }
        }
        vector<int> ans(q.size(),-1);
        for(int i=0;i<q.size();i++){
            auto it = lower_bound(temp.begin(),temp.end(),q[i][1]);
            if(it==temp.end()) continue;
            int id = it-temp.begin();
            int sum = -1;
            for(int j=id;j<index.size();j++){
                if(v[index[j]].first>=q[i][0]){
                    sum = max(sum,v[index[j]].first+v[index[j]].second);
                }
                else break;
            }
            ans[i] = sum;
        }
        return ans;
    }
};
```

**Comment by przemek3d88** [comment] 2023-06-14 16:40
This issue will be rejected as you did not provide a test case, on which this code gets TLE.

**Comment by LC-Pam** [comment] 2023-06-14 19:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 19:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 19:56 UTC
Labels: LCUS, problem
