### ISSUE TITLE
10. Regular Expression Matching - Description wrong / bad test case

### ISSUE THREAD

**Issue by qhool** [LeetCode-Feedback/LeetCode-Feedback#17510] opened 2023-10-26 17:21 UTC
#### Your LeetCode username
user7812FG

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
"regular expression" can mean one of two things, the formal definition (i.e. a regular language) or something like pcre.  A formal regular expression can be represented by a finite state automaton, while the other type cannot.  In particular, in the test case:

```
s="aaa"
p="a*a"
```
Expected `true`

The regular expression, `a*a`, cannot match any string, because `a*` consumes all available `a` characters, leaving none for the final `a`.  Something more capable than a finite state automaton is required, such as a stack automaton.   This capability is sometimes referred to as backtracking, since the execution must move backwards in the input when the portion of the expression after a `*` fails to match, to retry after forcing the `*` match to end prematurely.

#### Code you used for Submit/Run operation

```
import (
    "strings"
)

type state func(c byte) state

func isMatch(s string, p string) bool {
    re := compile(p)
    return execute(s, re)
}

func execute(s string, re state) bool {
    r := strings.NewReader(s)
    for re != nil {
        c, err := r.ReadByte()
        if err != nil {
            re = re(0)
            break
        } else {
            re = re(c)
        }
    }
    return re != nil
}

func compile(p string) state {
    m := []byte(p)
    cur := m_terminal
    replace := false
    var prev byte
    for i := len(m) - 1; i >= 0; i-- {
        if i > 0 {
            prev = m[i-1]
        } else {
            prev = 0
        }
        if replace {
           replace = false
        } else { 
            replace, cur = compile_char(prev,m[i],cur)
        }
    }
    return cur
}

func compile_char(prev, char byte, next state) (bool,state) {
    replace := false
    var st state
    switch char {
        case '.':
            st = func(c byte) state { return m_any(c,char,next) }
        case '*':
            _,inner := compile_char(0, prev, m_match)
            st = func(c byte) state { return m_star(c,inner,next) }
            replace = true
        default:
            st = func(c byte) state { return m_char(c,char,next) }
    }
    return replace, st
}

func m_char(c, p byte, next state) state {
    if c == p {
        return next
    } else {
        return nil
    }
}

func m_any(c, p byte, next state) state {
    if c != 0 {
        return next
    } else {
        return nil
    }
}

func m_star(c byte, inner state, next state) state {
    if inner(c) != nil {
        return func(c byte) state { return m_star(c,inner,next) }
    } else {
        return next(c)
    }
}

func m_terminal(c byte) state {
    if c == 0 {
        return m_match
    } else {
        return nil
    }
}

func m_match(c byte) state {
    return m_match
}
```

#### Expected behavior
Either the description of the problem should be changed, or the test case should be removed, or it should be altered to use the pattern `aa*`, which is functionally equivalent and conforms to the formal definition.

**Comment by LC-Pam** [comment] 2023-10-27 19:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 17:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:59 UTC
Labels: Waiting for Reply
