### ISSUE TITLE
STL find function giving TLE

### ISSUE THREAD

**Issue by 01prateek-mishra** [LeetCode-Feedback/LeetCode-Feedback#8588] opened 2022-08-08 17:47 UTC
#### Your LeetCode username 
01prateek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The STL find function is giving TLE whereas the binary search code works fine!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        int n = nums.size();
        vector<vector<int>> ans;
        sort(nums.begin(), nums.end());
        
        for(int i=0; i<n; i++){
            
            if(i != 0 && nums[i] == nums[i-1]) continue;
            
            for(int j=i+1; j<n; j++){
                
                if(j != i+1 && nums[j] == nums[j-1]) continue;
                
                int temp = -1*(nums[i]+nums[j]);
                
                auto it = find(nums.begin()+j+1, nums.end(), temp);
                
                if(it != nums.end()) ans.push_back({nums[i], nums[j], temp});
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

I was expecting that the stl find function will work fine but it is giving tle.

**Comment by LC-Pam** [comment] 2022-08-09 17:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name.

**Comment by LC-Pam** [comment] 2022-08-10 17:48
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-10 17:48 UTC
Labels: LCUS, problem
