### ISSUE TITLE
Missing Test Case - 2810. Faulty Keyboard

### ISSUE THREAD

**Issue by Anurag-AI-sys** [LeetCode-Feedback/LeetCode-Feedback#15945] opened 2023-08-27 05:59 UTC
#### Your LeetCode username
anuragcodes3011

#### Category of the bug
- [ ] can't start the string with i 
- [ ] say in the question we can't start with i 
- [ ] C++/JAVA/C#/C
- [ ] india,insert(any string starting with i)

#### Description of the bug
When I run the custom test case starting eith i, it shows s[] cannot be i

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string finalString(string s) {
        int n = s.size();
        string resultant_string = "";
        for(int i = 0;i<n;i++){
            if(s[i] == 'i'){
                reverse(resultant_string.begin(), resultant_string.end());
            }
            else resultant_string = resultant_string + s[i];

        }
        return resultant_string;
    }
};
```

#### Expected behavior
I expected the i to remain unchanged.

**Comment by LC-Pam** [comment] 2023-08-28 20:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:45 UTC
Labels: Waiting for Reply
