### ISSUE TITLE
Missing Test Case - 1249. Minimum Remove to Make Valid Parentheses

### ISSUE THREAD

**Issue by shlokjjw** [LeetCode-Feedback/LeetCode-Feedback#15734] opened 2023-08-19 14:47 UTC
#### Your LeetCode username

shlokjjw

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Last edge case of the problem is not considered

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        int n=s.size();
        stack<int>st;
        int count=0;
        for(int i=0;i<n;i++){
            if(s[i]=='('){
                st.push(i);
                count++;
            }
            else if(s[i]==')'){
                if(count>0){
                    st.pop();
                    count--;
                }
                else{
                    st.push(i);
                }
            }
        }
        while(!st.empty()){
            int curr=st.top();
            st.pop();
            s.erase(curr,1);
        }
        return s;

    }
};
```

#### Language used for code
 C++

#### Expected behavior

This is the edge case and it is not considered. We cannot allow n^2 approach to the problem.
In that case, their will be 10^5 times ')' or 10^5 times ')'

**Comment by LC-Pam** [comment] 2023-08-21 20:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed** 2023-08-25 14:29 UTC
Labels: Waiting for Reply
