### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers / defining not done properly

### ISSUE THREAD

**Issue by Shamilvkdev** [LeetCode-Feedback/LeetCode-Feedback#17702] opened 2023-10-31 08:52 UTC
#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

# some of the commands is not defined properly or errored. but somehow it works,

#### Code you used for Submit/Run operation

```
"function addTwoNumbers(l1: ListNode | null, l2: ListNode | null, carry: number = 0): ListNode | null {
    if(!l1 && !l2 && !carry) return null;

    var total : number = (l1 ? l1.val : 0) + (l2 ? l2.val : 0) + (carry || 0);
    carry = parseInt(total / 10 + '');
    return new ListNode(total % 10, addTwoNumbers(l1?.next, l2?.next, carry));
};"
```

**Comment by LC-Pam** [comment] 2023-10-31 16:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
More details about the issue or bug. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:10 UTC
Labels: Waiting for Reply
