### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by akaebe** [LeetCode-Feedback/LeetCode-Feedback#20863] opened 2024-03-01 16:38 UTC
the test case checks for the returned array, but the questions says to return count of array

**Comment by mahendra5maddipati** [comment] 2024-03-01 17:21
Your doubt is valid. The primary goal of the removeElement function is to modify the input array nums in-place to remove all occurrences of the specified value val. The function should then return the count of elements in the modified array that are not equal to val.
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        count = 0
        for i in range(0, len(nums)):
            if nums[i] != val:
                nums[count] = nums[i]
                count += 1
        return count
here it works as
The variable count is used to keep track of the position where the next element not equal to val should be placed.

The loop iterates through each element in the array. If an element is not equal to val, it is placed at the position indicated by count, and then count is incremented.

After the loop, the function returns the final value of count, which represents the count of elements in the modified array that are not equal to val.

Regarding the doubt about the test cases, the question instructs you to modify the array in-place and return the count of elements that are not equal to val. While the provided code does modify the array in-place, the count is what you need to return, not the modified array.

maybe function used as:
solution = Solution()
nums = [3, 2, 2, 3]
val = 3
result = solution.removeElement(nums, val)
print(result)  #2
print(nums[:result])  #[2, 2]
 So:
The test case checks both the count (returned value) and the modified array's first count elements. The modified array beyond the first count elements is not important, as mentioned in the question.

**Comment by LC-Pam** [comment] 2024-03-01 21:11
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-03-05 20:00 UTC
Labels: Waiting for Reply
