### ISSUE TITLE
Missing Test Case - 37. Sudoku Solver

### ISSUE THREAD

**Issue by Yash9460** [LeetCode-Feedback/LeetCode-Feedback#8014] opened 2022-07-04 12:49 UTC
#### Your LeetCode username

byash2060

#### Category of the bug
- [ ] Question
-   Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Sudoku Solver

#### Code you used for Submit/Run operation

```
// Sudoku Solver
class Solution {
public:
    
void solveSudoku(vector<vector<char>>& board) {
        solve(board);
        return;
    }
    bool solve(vector<vector<char>>& board){
        for(int i=0;i<board.size();i++){
            for(int j=0;j<board.size();j++){
                if(board[i][j]=='.'){
                    for(char c='1';c<='9';c++){
                        if(isvalid(board, i, j, c)){
                            board[i][j]=c;
                        if(solve(board)){
                            return true;
                        }else{
                            board[i][j]='.';
                        }
                            }
                    }
                    return false;
                }
            }
        }
        return true;
    }
    bool isvalid(vector<vector<char>> &board, int row, int col, char val)
    {
        for(int i=0; i<9; i++)
        {
            if(board[row][i]== val)
            {
                return false;
            }
            if(board[i][col]== val)
            {
                return false;
            }
            if(board[3* (row/3) + (i/3)][3* (col/3) + (i%3)]== val)
            {
                return false;
            }
        }
        return true;
    }

};
```

#### Language used for code

C++
Backtracking

**Comment by LC-Pam** [comment] 2022-07-05 17:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the missing test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-06 16:58
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-06 16:58 UTC
Labels: LCUS, problem
