### ISSUE TITLE
Missing Test Case - 1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by abbbbbs** [LeetCode-Feedback/LeetCode-Feedback#12810] opened 2023-04-07 05:42 UTC
#### Your LeetCode username

wqqqqqqqqqqqq

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

![image](https://user-images.githubusercontent.com/130128149/230548464-fd39b9c5-8852-462b-88f4-ddcf56d8d605.png)

#### Code you used for Submit/Run operation

select employee_id, if(employee_id % 2=0 ,'0', if(name like'm%','0', salary)) as bonus_output 
from Employees 
order by employee_id

#### Language used for code
sql

**Comment by LC-Pam** [comment] 2023-04-10 22:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The test case in json format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-12 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-12 19:45 UTC
Labels: LCUS, problem
