### ISSUE TITLE
Player Error after several minutes of playback.

### ISSUE THREAD

**Issue by itissid** [LeetCode-Feedback/LeetCode-Feedback#18681] opened 2023-12-14 21:07 UTC
I am a premium customer.

### LeetCode Username
graham2181

### Problem number, title, and link
https://leetcode.com/explore/interview/card/system-design-for-interviews-and-beyond/729/how-to-deliver-data-reliably/4792/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Playing video on Chrome or FF gives a Player Error message(See screenshot). The error happens after sometime(several minutes after video has started playing and almost always a few minutes after you manually seek the video to a specific position)

### Expected behavior
The player should not crash. 

### Screenshots
See attached

### Additional context
I opened the video in incognito mode too and the error persists.

**Comment by LC-Pam** [comment] 2023-12-14 22:52
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The video page link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-18 21:17
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-18 21:17 UTC
Labels: Waiting for Reply
