### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by WedgeLord** [LeetCode-Feedback/LeetCode-Feedback#18170] opened 2023-11-20 10:13 UTC
My algorithm was accepted, but it fails in this testcase (which I think should be added to this exercise)
pattern = "abab"
s = "dog cat"

My program loops through the string, and in this case it loops around and appears to match the pattern, but this should fail. However, my algorithm was accepted by the grading program.

**Comment by LC-Pam** [comment] 2023-11-20 21:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:15 UTC
Labels: Waiting for Reply
