### ISSUE TITLE
Shapeshifting SQL Table in 50Q SQL

### ISSUE THREAD

**Issue by notSido** [LeetCode-Feedback/LeetCode-Feedback#13779] opened 2023-05-31 06:17 UTC
![wtfpart1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111561235/3649ad4b-85fc-4853-a997-1ced50b7a116)
![wtfpart2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111561235/2855cc4a-6258-44c4-be2d-944c52434458)
![wtfpart3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111561235/556ada91-d63b-4159-ba98-606896cca81a)
![wtfpart4](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111561235/7046eec8-5999-4423-8d7a-356a857d3be9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111561235/0dd80708-ee5e-4e7d-9c9d-3d5d0b9f7c89)

i wrote the SQL Query in accordance with the table provided (seen in wtfpart4.png), which should be a valid answer. However, the table actually used for the test case and the one shown in the problem description (and test case page too! seen in wtfpart5.png) are different, which of course led to an invalid answer. there isn't a way to even view the ACTUAL testcase.

**Comment by LC-Pam** [comment] 2023-05-31 19:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The test case in JSON format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:23 UTC
Labels: LCUS, problem
