### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by raihanazamsyah** [LeetCode-Feedback/LeetCode-Feedback#16462] opened 2023-09-16 13:46 UTC
#### Your LeetCode username
raihanazamsyah

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.

```
// Two Sum
function twoSum($nums, $target) {
        $numCount = count($nums);
       for ($i = 0; $i < $numCount-1 ; $i++) {
           for ($j = $i+1; $j < $numCount; $i++) {
               if ($nums[$i] + $nums[$j] === $target) {
                return [$i,$j];
               }
           }
       } 
       return [];
    }
```

#### Language used for code
PHP

**Comment by LC-Pam** [comment] 2023-09-18 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug/issue of the problem.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-20 16:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-20 16:32 UTC
Labels: Waiting for Reply
