### ISSUE TITLE
Missing Test Case - 262. Trips and Users 

### ISSUE THREAD

**Issue by kgshetty** [LeetCode-Feedback/LeetCode-Feedback#6997] opened 2022-04-13 22:40 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case is failing by showing the wrong result 

#### Code you used for Submit/Run operation

```
select request_at as Day , round(sum(cancelled_trip)/ (sum(completed_trip) + sum(cancelled_trip)) , 2) as `Cancellation Rate`   from (
select request_at , case when status = 'completed' then 1 else 0 end as completed_trip , case when status != 'completed' then 1 else 0 end as cancelled_trip from trips t join Users u1 on t.client_id = u1.users_id join Users u2 on t.driver_id = u2.users_id  where u1.banned = 'No' and  u2.banned = 'No' 
) a group by request_at


```

Input test case that is failing

```
{"headers": {"Trips": ["id", "client_id", "driver_id", "city_id", "status", "request_at"], "Users": ["users_id", "banned", "role"]}, "rows": {"Trips": [["1", "1", "10", "1", "cancelled_by_client", "2013-10-04"]], "Users": [["1", "No", "client"], ["10", "No", "driver"]]}}
```
#### Screenshots

![image](https://user-images.githubusercontent.com/103103241/163281610-053305b7-68a8-4040-a038-fe14765cce30.png)

**Comment by LC-Yani** [comment] 2022-04-15 16:06
Hi @kgshetty,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by LC-Yani** [comment] 2022-04-18 20:37
Hi @kgshetty,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

**Comment by LC-Yani** [comment] 2022-04-22 17:25
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-22 17:25 UTC
Labels: LCUS, problem
