### ISSUE TITLE
Missing Test Case - 1684. Count the Number of Consistent Strings

### ISSUE THREAD

**Issue by Divyanshu960** [LeetCode-Feedback/LeetCode-Feedback#12184] opened 2023-03-05 13:02 UTC
#### Your LeetCode username

cdivyanshu10

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [. ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//  Count the Number of Consistent Strings

class Solution {
public:
    int countConsistentStrings(string allowed, vector<string>& words) {
        unordered_set<char> s;
        for (auto x:allowed){
            s.insert(x);
        }
        int count=0;
        for (auto word:words){
            bool status=true;
            for (int i=0;i<word.size();i++)
            {
                if(s.find(word[i])==s.end()){
                    status = false;
                    break;
                }
            }
            if(status)
                count++;
        }
        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Added a test case

#### Screenshots

![image](https://user-images.githubusercontent.com/72182690/222961975-28122c51-2cbd-4566-84be-135f45df3ba9.png)

**Comment by LC-Pam** [comment] 2023-03-07 18:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-08 19:02
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-08 19:02 UTC
Labels: LCUS, problem
