### ISSUE TITLE
Error with Approach: Prefix Sum + Hash Map in solution

### ISSUE THREAD

**Issue by buttonchicken** [LeetCode-Feedback/LeetCode-Feedback#7709] opened 2022-06-11 18:28 UTC
The solution does not work and gives runtime error for certain testcases.
[https://drive.google.com/file/d/1hByYUFH5ZV0TLEWdFghTuselWR_xJ8Ra/view?usp=sharing](url)

**Comment by buttonchicken** [comment] 2022-06-11 18:35
the updated solution :
`class Solution {
public:
    int maxSubArrayLen(vector<int>& nums, int k) {
        long long int prefixSum = 0;
        int longestSubarray = 0;
        unordered_map<long long int, int> indices;
        for (int i = 0; i < nums.size(); i++) {
            prefixSum += nums[i];

            // Check if all of the numbers seen so far sum to k.
            if (prefixSum == k) {
                longestSubarray = i + 1;
            }
            
            // If any subarray seen so far sums to k, then
            // update the length of the longest_subarray. 
            if (indices.find(prefixSum - k) != indices.end()) {
                longestSubarray = max(longestSubarray, i - indices[prefixSum - k]);
            }

            // Only add the current prefix_sum index pair to the 
            // map if the prefix_sum is not already in the map.
            if (indices.find(prefixSum) == indices.end()) {
                indices[prefixSum] = i;
            }
        }
        
        return longestSubarray;
    }
};`

**Comment by buttonchicken** [comment] 2022-06-11 18:35
This should be the updated solution to accommodate the test cases
class Solution {
public:
    int maxSubArrayLen(vector<int>& nums, int k) {
        long long int prefixSum = 0;
        int longestSubarray = 0;
        unordered_map<long long int, int> indices;
        for (int i = 0; i < nums.size(); i++) {
            prefixSum += nums[i];

            // Check if all of the numbers seen so far sum to k.
            if (prefixSum == k) {
                longestSubarray = i + 1;
            }
            
            // If any subarray seen so far sums to k, then
            // update the length of the longest_subarray. 
            if (indices.find(prefixSum - k) != indices.end()) {
                longestSubarray = max(longestSubarray, i - indices[prefixSum - k]);
            }

            // Only add the current prefix_sum index pair to the 
            // map if the prefix_sum is not already in the map.
            if (indices.find(prefixSum) == indices.end()) {
                indices[prefixSum] = i;
            }
        }
        
        return longestSubarray;
    }
};

**Comment by LC-Pam** [comment] 2022-06-13 03:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name.
The test case.
The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by AdityaMutharia** [comment] 2022-06-13 05:11
Problem name - **325. Maximum Size Subarray Sum Equals k**
The test case - 
[10000,10000.....(200000 times)] 
-1000000000
Language used - C++

**Comment by LC-Pam** [comment] 2022-06-16 17:18
Thank you for reaching out to us. When we tested you code, we received Compile error, would you mind sending us your code Submission Accepted Link?
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-19 20:13
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-19 20:13 UTC
Labels: LCUS, problem

**Comment by AdityaMutharia** [comment] 2022-06-22 18:33
This is the code Submission Accepted Link:
https://leetcode.com/submissions/detail/719863062/

PS sorry for replying this late I was out of town.
