### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by nazir098** [LeetCode-Feedback/LeetCode-Feedback#15653] opened 2023-08-16 15:59 UTC
#### Your LeetCode username
nazir1

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug
I am using a custom test case -[100,4,200,2] for this [question](https://leetcode.com/problems/longest-consecutive-sequence/)
it's expected answer should be 0 but output is coming 1.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
OutPut: 0

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/82276414/39e60704-2ba6-457a-99c7-508c7ff00a9c)

**Comment by LC-Pam** [comment] 2023-08-16 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-21 15:35
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-21 15:35 UTC
Labels: Waiting for Reply
