### ISSUE TITLE
Missing Test Case - 101. Symmetric Tree

### ISSUE THREAD

**Issue by anuragsinha647** [LeetCode-Feedback/LeetCode-Feedback#18583] opened 2023-12-10 11:51 UTC
### LeetCode Username

user8467DF

### Problem number, title, and link

101. Symmetric Tree https://leetcode.com/problems/symmetric-tree/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The testcase where root = NULL is missing.

### Language used for code

C++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool aresame(TreeNode*x, TreeNode*y) {
        if (x==NULL && y==NULL) return true;
        else if (x!=NULL) {
            if (y!=NULL) {
                if (x->val==y->val) return aresame(x->right, y->left)&&aresame(x->left, y->right);
                else return false;
            }else return false;
        }else return false;
    }
    bool isSymmetric(TreeNode* root) {
        else return aresame(root->left, root->right);
    }
};
```

### Expected behavior

Should have given error for root==NULL, but the code worked instead.

**Comment by LC-Pam** [comment] 2023-12-12 23:28
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link.  
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-14 22:26
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-14 22:26 UTC
Labels: Waiting for Reply
