### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by rajat1500** [LeetCode-Feedback/LeetCode-Feedback#15176] opened 2023-07-31 11:47 UTC
#### Your LeetCode username
rg688171

- [x] Missing Test Cases 

#### Description of the bug
One of the test cases is wrong in this question

#### Code you used for Submit/Run operation
"""
class Solution(object):
    def helper(self,s,p,i,j,dp):
        if i==-1 and j==-1:
            return True
        if j==-1:
            return False
        if i==-1:
            for k in range(j+1):
                if p[k]!="*":
                    return False
            return True
        if dp[i][j]==-1:
            if s[i]==p[j] or p[j]==".":
                dp[i][j]=self.helper(s,p,i-1,j-1,dp)
            elif p[j]=="*":
                dp[i][j]=self.helper(s,p,i-1,j,dp) or self.helper(s,p,i,j-1,dp)
            else:
                dp[i][j]=False
        return dp[i][j]
    def isMatch(self, s, p):
        m=len(s)
        n=len(p)
        dp=[[-1 for i in range(n)] for j in range(m)]
        return self.helper(s,p,m-1,n-1,dp) """

```


#### Language used for code
Python


#### Expected behavior
s="aab"
p="c*a*b"
for this the answer should be False but it is showing True is the right answer



#### Screenshots
<img width="311" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49668879/d7c52db3-7f7a-430f-90d3-ad9aada6822b">



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-08-01 18:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-03 18:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-03 18:20 UTC
Labels: LCUS, problem, Waiting for Reply
