### ISSUE TITLE
Name collision with Elixir builtins on problem 359

### ISSUE THREAD

**Issue by tdvortex** [LeetCode-Feedback/LeetCode-Feedback#7371] opened 2022-05-19 22:48 UTC
#### Your LeetCode username

tiedyedvortex

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

On problem 359 "Logger Rate Limiter" in the Elixir programming language, the problem asks the user to create a module named "Logger". However, this name conflicts with Elixir's built-in Logger library and causes the test runner to crash. 

#### Code you used for Submit/Run operation

```
defmodule Logger do
  use Agent

  @spec init_() :: any
  def init_() do
    :ok
  end

  @spec should_print_message(timestamp :: integer, message :: String.t) :: boolean
  def should_print_message(timestamp, message) do
    false
  end
end
```

#### Language used for code

Elixir

#### Expected behavior

This code is valid Elixir code that does not produce the intended output. I expect it would compile, run, and give a test case failure. However, the code instead gives a process failure error.

Replicating the issue in Visual Studio Code gives the following error message:

```
warning: redefining module Logger (current version loaded from c:/Program Files (x86)/Elixir/lib/logger/ebin/Elixir.Logger.beam)
  logger_rate_limiter.exs:1
```

I was able to resolve this error message by renaming the module to LeetcodeLogger with no other modifications.

**Comment by LC-Pam** [comment] 2022-05-20 21:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The submission link.
We tested your code and received "Compile Error" (https://leetcode.com/submissions/detail/703676245/)
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-23 02:57
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-23 02:57 UTC
Labels: LCUS, problem
