### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by chinhvu00000** [LeetCode-Feedback/LeetCode-Feedback#16998] opened 2023-10-07 10:50 UTC
#### Your LeetCode username
chinhvu00000

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Cost[]=[2,2,2,2,2,2,1,4,5,5,5,5,5,2,2,2,2,2,2,2,2,2,2,2,2,2]
k=7
candidates=3
Result: 13
If we run code with this test case, the result will be 13.
It is correct, right?
But if we reverse the array above, the result needs to be kept but in fact, the result returns 14.
Cost[] = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 4, 1, 2, 2, 2, 2, 2, 2]
k=7
candidates=3
Result: 14
We got this result because We currently implement the algorithm because we prioritize choosing the left side in case the value on the left and the value on the right are equal.

#### Expected behavior

Cost[] = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 4, 1, 2, 2, 2, 2, 2, 2]
k=7
candidates=3
Expected result: 13

**Comment by LC-Pam** [comment] 2023-10-09 18:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:48 UTC
Labels: Waiting for Reply

**Comment by chinhvu00000** [comment] 2023-10-15 17:57
This is my submission:
https://leetcode.com/problems/total-cost-to-hire-k-workers/submissions/1069253573/
