### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Laoooq** [LeetCode-Feedback/LeetCode-Feedback#16305] opened 2023-09-09 10:19 UTC
#### Your LeetCode username

tienlao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case 3 doesn't pass in leetcode, but in vscode or vs is passes

#### Code you used for Submit/Run operation

```
// Palindrome Number
class Solution {
public:
    bool isPalindrome (int x) {
        if(x < 0){
            return false;
        }
        char buffer [11];
        memset(buffer, 0, 11); 
        int insertIndex = 0;
        while (x < 0){
            buffer[insertIndex++] = x % 10 + '0';
            x /= 10;
        }
        for(int i = 0, j = insertIndex - 1; i < j; i++, j--){
            if(buffer[i] != buffer[j]){
                return false;
            }
        }
        return true;
    }
};
```

#### Expected behavior

The  case 3 (10) was expected to return true

#### Screenshots

https://imgur.com/a/LYx2nLD

**Comment by khushdj2002** [comment] 2023-09-09 11:25
## JAVA code

class Solution {
    public boolean isPalindrome(int x) {
        if(x<0){
            return false;
        }
        String a =Integer.toString(x);
        System.out.println(a);
        StringBuilder sb = new StringBuilder(a);
        return a.equals(sb.reverse().toString());
    }
}


Try out this any way negative numbers won't be palindrome So return false to those directly. Check only for positive number.

**Comment by LC-Pam** [comment] 2023-09-11 20:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:09 UTC
Labels: Waiting for Reply
