### ISSUE TITLE
Missing Test Case - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by sb1703** [LeetCode-Feedback/LeetCode-Feedback#19815] opened 2024-01-28 14:38 UTC
### LeetCode Username
shreyasbehl

### Problem number, title, and link
[629. K Inverse Pairs Array](https://leetcode.com/problems/k-inverse-pairs-array/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Missing test Case
n = 1000, k = 1000

### Language used for code
C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    const int mod = 1e9+7;
    int kInversePairsRecursion(vector<vector<int>> &dp,int n,int k){
        if(k==0){
            return 1;
        }
        if(k<0 || n<=0){
            return 0;
        }
        if(dp[n][k]!=-1){
            return dp[n][k];
        }
        int ans = 0;
        for(int i=0;i<=min(n-1,k);i++){
            ans = ((ans)%mod + (kInversePairsRecursion(dp,n-1,k-i))%mod)%mod;
        }
        return dp[n][k] = ans;
    }
    int kInversePairs(int n, int k) {
        if(k == 0){
            return 1;
        }
        if(k == 1){
            return n-1;
        }
        int zeroK = n*(n-1)/2 + 1;
        // cout<<zeroK<<"\n";
        if(k>=zeroK){
            return 0;
        }
        vector<vector<int>> dp(n+1,vector<int>(k+1,-1));
        int ans = kInversePairsRecursion(dp,n,k);
        return ans%mod;
    }
};
```

### Expected behavior
Code shouldn't be accepted

**Comment by LC-Pam** [comment] 2024-01-31 16:24
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/19790

**Closed by LC-Pam** 2024-01-31 16:24 UTC
