### ISSUE TITLE
Missing Test Case - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by 17870119463** [LeetCode-Feedback/LeetCode-Feedback#8267] opened 2022-07-20 07:54 UTC
class Solution {
public:
    int numMatchingSubseq(string s, vector<string>& words) {
        int ret = 0, len = s.length(), wordsNum = words.size();
        unsigned short int dic[26][50001], num[26] = {0};
        for(int i = 0; i<len; i++) {
            //将s的每个字母的下标 按字母表存入字典，并计算每个字母出现的次数，方便查找
            char index = s[i]-'a';
            dic[index][num[index]] = i;
            num[index] = num[index]+1;
        }
        for(int i = 0; i<wordsNum; i++) {
            int wordLen = words[i].length(), preMatInd = -1, n, k;
            for(n = 0; n<wordLen; n++) {
                char index = words[i][n]-'a';//第i个单词的第n个字母在字典dic里的索引
                if(num[index] == 0 || dic[index][num[index]-1] < preMatInd) {
                    //如果 s中没有字母words[i][n] 或者 第n个字母在s字符串的最大下标 小于 第n-1个单词的在s中的下标，说明无法匹配当前单词words[i]。
                    break;
                }
                for(k = 0; k<num[index]; k++) {
                    //字典中遍历第n个字母的下标，直到遍历到最后一个下标或当前下标比前一个字母下标大，即当前字母出现在前一个字母的后面
                    if(dic[index][k] > preMatInd) {
                        preMatInd = dic[index][k];
                        break;
                    }
                }
                if(k == num[index]) {
                    break;
                }
            }
            n == wordLen ? ret++:0;
        }
        return ret;
    }
};
//测试
// "abcde"
// ["a","bb","acd","ace"]
// "a"
// ["ha","bb","acd","ace"]
// "dsahabcdejpabcdejaabcdeufabcde"
// ["ahjpjau","ja","ahbwzgqnuk","tnmlanowax"]
// "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
// ["asda", "aaaaa", "f", "dads"]
// "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
// ["asda", "aaaajha", "f", "dahj"]

**Comment by LC-Pam** [comment] 2022-07-20 17:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language or submission link you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-22 17:25
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-22 17:25 UTC
Labels: LCUS, problem
