### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by Rohit3007** [LeetCode-Feedback/LeetCode-Feedback#13505] opened 2023-05-16 13:01 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ yes ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int rob(int[] nums) {
        if (nums == null || nums.length == 0) {
            return 0;
        }
        int n = nums.length;
        if (n == 1) {
            return nums[0];
        }
        int prevPrev = 0;  
        int prev = nums[0];  

        for (int i = 1; i < n; i++) {
            int curr = Math.max(prev, prevPrev + nums[i]);
            prevPrev = prev;
            prev = curr;
        }

        return prev;
    }
}

```

**Comment by LC-Pam** [comment] 2023-05-16 20:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-19 19:42
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-19 19:42 UTC
Labels: LCUS, problem
