### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by xswzaq44321** [LeetCode-Feedback/LeetCode-Feedback#18063] opened 2023-11-15 02:47 UTC
### LeetCode Username
xswzaq44321

### Problem number, title, and link
[1846. Maximum Element After Decreasing and Rearranging](https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/solutions/1190257/java-o-n-solution-with-comments/?envType=daily-question&envId=2023-11-15
Was able to use this solution to pass the problem, but when I use the following testcase, It fails
`[3,10,3,3,1]`

### Language used for code
Java

### Code used for Submit/Run operation
DISCLAIMER: THIS IS NOT MY CODE, THIS IS FROM SOMEONE ELSE'S SOLUTION
```java
public int maximumElementAfterDecrementingAndRearranging(int[] arr) {
        if (arr == null || arr.length == 0) return 0;
		
		// keep count of occurances of all elements
        Map<Integer, Integer> map = new HashMap<>();
        for (int num: arr) {
            map.put(num, map.getOrDefault(num, 0) + 1);
        }
        
		
        int out = 1, curr = 1;
        for (int i = 0; curr <= arr.length && i < arr.length; ) {
            out = Math.max(curr, out);

			// if current element exists, we can directly jump to current index + count since it satisfies the given condition.
            if (map.containsKey(curr)) {
                i+= map.get(curr);
            } else {
			   // need this to not accidentally update i with the total count but rather with the remaining (checkout 49th test case [1,209 (10000 times), 10000 (1 time)].
                map.put(arr[i], map.get(arr[i]) - 1);
				
                i++;
            }
            curr += 1;
        }
        return out;
    }
```

### Expected behavior
Output is `3`
While answer should be `4`

### Screenshots
![chrome_wUXBv2APFH-15Wednesday-10AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32536699/51d4eca1-299c-485d-9c2d-bba7c371b0fd)

**Comment by LC-Pam** [comment] 2023-11-15 20:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:08 UTC
Labels: Waiting for Reply
