### ISSUE TITLE
Missing Test Case - 22. Generate Parentheses

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14845] opened 2023-07-17 16:37 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Generate Parenthesis
class Solution {
    public List<String> generateParenthesis(int n) 
    {
     ArrayList<String> result =new ArrayList<String>();
     dfs(result,"",n, n);
     return result;   
    }
public void dfs(ArrayList<String>result,String s, int left , int right)
{
    if(left>right)
    return;

    if(left==0&&right==0)
    {
        result.add(s);
        return;
    }
    if(left>0){
        dfs(result,s+"(",left-1,right);
    }
    if(right>0)
    {
     dfs(result,s+")",left,right-1);   
    }
}    
}
```

**Comment by LC-Pam** [comment] 2023-07-17 20:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:11 UTC
Labels: LCUS, problem, Waiting for Reply
