### ISSUE TITLE
Testcases inefficient for problem Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by chaira19** [LeetCode-Feedback/LeetCode-Feedback#13864] opened 2023-06-03 13:41 UTC
#### Your LeetCode username
 chaira19

#### Category of the bug
- Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Peak Index in a Mountain Array - Linear search (136 ms)
int peakIndexInMountainArray(vector<int>& arr) {
        for(int i = 1;i<arr.size()-1;i++)
        {
            if(arr[i+1]<arr[i])
            {
                return i;
            }
        }
        return -1;
    }

// Peak Index in a Mountain Array - Binary search (137 ms)
int peakIndexInMountainArray(vector<int>& arr) {
        int low = 0;
        int high = arr.size()-1;
        while(low<high)
        {
            int mid = low + (high-low)/2;
            if(arr[mid+1]<arr[mid] && arr[mid-1]<arr[mid])
            {
                return mid;
            }
            else if(arr[mid-1]<arr[mid])
            {
                low = mid;
            }
            else
            {
                high = mid;
            }
        }
        return -1;
    }
```

#### Language used for code
C++

#### Expected behavior
 Time taken for binary search should be much lesser than linear search.

**Comment by LC-Pam** [comment] 2023-06-06 19:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:26
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:26 UTC
Labels: LCUS, problem
