### ISSUE TITLE
Wrong Evaluation

### ISSUE THREAD

**Issue by Younggregs** [LeetCode-Feedback/LeetCode-Feedback#16581] opened 2023-09-21 12:39 UTC
#### Your LeetCode username
retzam

#### Category of the bug
- [ ] Solution

#### Description of the bug
I have a test case that results to 
`
str = "(5+(17+(10*(6/(-11*(9+3))))))"
`
Now when I run 
`
int(round(eval(str)))
`
I get 12 instead of 22.
I have tried replicating on my local device and other virtual devices with Python 2 and Python 3 but they all return 22 as well.
So only Leetcode env evaluates to 12.

#### Code you used for Submit/Run operation

```
# Evaluate Reverse Polish Notation
class Solution(object):
    def evalRPN(self, tokens):
        """
        :type tokens: List[str]
        :rtype: int
        """

        #1. Call the recursive function to generate the operation

        generate = self.generateOperation(tokens)
        return int(round(eval(generate)))

    def generateOperation(self, tokens, total=''):
        if len(tokens) > 0:
            i = tokens[-1]
            if i in ['+', '-', '*', '/']:
                temp = ''
                s = False
                if tokens[-2].lstrip('-').isnumeric():
                    if tokens[-3].lstrip('-').isnumeric():
                        s = True
                    if s:
                        temp = tokens[-3] + tokens[-1] + tokens[-2]
                        del tokens[-3]
                    else:
                        temp = tokens[-2] + tokens[-1]
                    del tokens[-2]
                elif tokens[0].lstrip('-').isnumeric():
                    temp += tokens[0] + tokens[-1]
                    del tokens[0]
                del tokens[-1]
                total += '(' + self.generateOperation(tokens, temp) + ')'
                return total
        return total
# Test case
# arr = ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]
```

#### Language used for code

Python

#### Expected behavior

The code is supposed to recursively create a string of arithmetic operations and then use eval() to evaluate the string.
But for 1 test case i keep getting the wrong result.
`
str = "(5+(17+(10*(6/(-11*(9+3))))))"
`
Now when I run 
`
int(round(eval(str)))
`
I get 12 instead of 22.
I have tried replicating on my local device and other virtual devices with Python 2 and Python 3 but they all return 22 as well.
So only Leetcode env evaluates to 12.

#### Additional context

I think it might be env issue.

**Comment by LC-Pam** [comment] 2023-09-21 19:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number and name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-25 20:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-25 20:47 UTC
Labels: Waiting for Reply

**Comment by Younggregs** [comment] 2023-09-27 08:11
Hello, i missed this.
Here is what you asked for:
Problem Number: 150
Problem Name: Evaluate Reverse Polish Notation
