### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by psawant123** [LeetCode-Feedback/LeetCode-Feedback#8065] opened 2022-07-07 21:16 UTC
class Solution {
    public int removeDuplicates(int[] nums) {
        int n = nums.length;
        if(nums.length ==1)
        {
            return 1;
        }
        
        int i = 0;
        int j = 1;
        
        while (j < nums.length)
        {
            if (nums[i] != nums[j])
            {
                i++;
                nums[i] = nums[j];
                j++;
            }
            else
            {
                n--;
                j++;
            }
        }
        return n;
    }
}

**Comment by LC-Pam** [comment] 2022-07-08 03:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
What is the missing test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-11 19:47
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-11 19:47 UTC
Labels: LCUS, problem
