### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by kshitijwohlig** [LeetCode-Feedback/LeetCode-Feedback#14188] opened 2023-06-17 10:30 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The missing test case is related to case sensitivity in the input strings.

#### Code you used for Submit/Run operation

```javascript
/**
 * @param {string} s
 * @param {string} t
 * @return {boolean}
 */
const isAnagram = function(s, t) {
    const data1 = s.toLowerCase();
    const data2 = t.toLowerCase();
    const splitItemsData1 = data1.split("");
    const splitItemsData2 = data2.split("");
    const sortItemsData1 = splitItemsData1.sort();
    const sortItemsData2 = splitItemsData2.sort();
    const joinData1 = sortItemsData1.join('');
    const joinData2 = sortItemsData2.join('');

    return joinData1 === joinData2 ? true : false;
};
Language used for code
<!-- JavaScript -->
Expected behaviour
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The code should handle case sensitivity and return true for inputs like s = 'MARS' and t = 'MaRS' since they are anagrams when case is ignored.

Additional context
<!-- Add any other additional context about the bug. -->. 
When testing the code, I found that it doesn't handle case sensitivity in the input strings. I have added a solution to convert both input strings to lowercase, but it seems to be missing a test case for this scenario. The missing test case is when `s = 'MARS'` and `t = 'MaRS'`. In this case, the expected output should be `true` since the strings are anagrams when case is ignored. I would like to contribute this test case to ensure the code handles case insensitivity correctly. Thank you!

**Comment by LC-Pam** [comment] 2023-06-20 20:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
"MARS"
"MaRS"
received Invalid Testcase

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-22 18:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-22 18:11 UTC
Labels: LCUS, problem
