### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by MossesRoss** [LeetCode-Feedback/LeetCode-Feedback#14306] opened 2023-06-23 05:23 UTC
#### Your LeetCode username

MossesRoss

#### Category of the bug
- [ ] Solution

#### Description of the bug

I wrote the correct code but it is not working, and giving an error.

#### Code you used for Submit/Run operation

uniques = []
for num in nums:
    if num not in uniques:
        uniques.append(num)
    elif num in uniques:
        pass
    
print(uniques)

#### Language used for code

Python

#### Expected behavior

It should pass

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/129834719/6fb153a4-4f6d-4b3b-b152-b4cbc170f6be)

#### Additional context

please fix this

**Comment by LC-Pam** [comment] 2023-06-23 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:37
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:37 UTC
Labels: LCUS, problem
