### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by pavan-bandi** [LeetCode-Feedback/LeetCode-Feedback#15035] opened 2023-07-25 19:17 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are missing test cases for the provided solution that checks the validity of a given number. The solution is written in Python and uses the Decimal class to handle numbers.

#### Code you used for Submit/Run operation

```python
from decimal import Decimal

class Solution:
    def isNumber(self, s: str) -> bool:
        try:
            k = Decimal(s)
            if k == Decimal("Infinity") or k == Decimal("-Infinity"):
                return False
            return True
        except:
            return False```
            
            
        
missing test cases

Test Case 1:
Input: "nan"
Expected Output: True

Test Case 2:
Input: "+nan"
Expected Output: True

Test Case 3:
Input: "-nan"
Expected Output: True

**Comment by LC-Pam** [comment] 2023-07-26 21:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by pavan-bandi** [comment] 2023-07-27 15:42
https://leetcode.com/submissions/detail/1003850589/

**Comment by pavan-bandi** [comment] 2023-08-01 18:49
Test Case 1:
Input: "nan"
Expected Output: True

Test Case 2:
Input: "+nan"
Expected Output: True

Test Case 3:
Input: "-nan"
Expected Output: True

**Comment by LC-Pam** [comment] 2023-08-04 19:26
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment] 2023-08-08 19:33
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please reply to this with your LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment] 2023-08-15 19:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-15 19:15 UTC
Labels: LCUS, watchlist, problem
