### ISSUE TITLE
336. Palindrome Pairs: Missing Test Case

### ISSUE THREAD

**Issue by ChenDanCMU** [LeetCode-Feedback/LeetCode-Feedback#12305] opened 2023-03-11 21:40 UTC
**你的 LeetCode 用户名**
dc93

**Bug 类型**
- [ ] 题解
- [ ] 缺少测试用例

**描述**
官方标程（python）无法解出数据范围内的输入。
考虑下面这组输入(见以下附件)：
[336_in.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10949499/336_in.txt)
""
a, aa, aaa, ... , "a"*300
b, bb, bbb, ... , "b"*300
....
p, pp, ppp, ... , "p"*300
"q"*102, ..., "q" *300
每一组相同字母的字符串两两构成回文串， 不同字母两两不构成回文串。
以下是我的python解， 在中国站用时1900ms通过当前全部测试数据， 用时2000ms通过以上极端单组数据。官方标程无法跑完这组数据。美国站直接由于无法跑完这组数据错误地报了WA。目前排名靠前的大部分答案是可以解出这组数据的。
![lccn336](https://user-images.githubusercontent.com/26544933/224512543-d9291e92-f94f-41cb-a6d9-816b9339f988.PNG)
![lcus336](https://user-images.githubusercontent.com/26544933/224512545-3585edbc-4c28-45a8-b402-f76b35fcdcec.PNG)
**你使用的语言**
python

**你提交或者运行的代码**
[336_code_python.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10949516/336_code_python.txt)

**期望行为**
见336_out.txt
[336_out.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10949500/336_out.txt)

**Comment by LC-Pam** [comment] 2023-03-13 17:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-20 17:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-20 17:23 UTC
Labels: LCUS, problem
