### ISSUE TITLE
Internal error Bug

### ISSUE THREAD

**Issue by DhavalPatodiya** [LeetCode-Feedback/LeetCode-Feedback#12260] opened 2023-03-09 07:09 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Getting Internal error on problem 323 when submitting the code in java

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

It should show the result instead it keeps showing pending.

#### Screenshots

<img width="1440" alt="Screenshot 2023-03-09 at 00 08 43" src="https://user-images.githubusercontent.com/37049494/223946814-c9d74a6b-825f-45d5-8d3f-2af0a8a10b11.png">

**Comment by DhavalPatodiya** [comment] 2023-03-09 07:10
I don't know why first it shows internal error then changed to runtime error.

**Comment by LC-Pam** [comment] 2023-03-09 18:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by DhavalPatodiya** [comment] 2023-03-10 00:01
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/submissions/911925940/ 
Here it is:  after submitting it keeps on informing you that the code evaluation is Pending but doesn't show any output and it freezes the page so you have to refresh it or wait for a long time. The browser used is Safari

**Comment by LC-Pam** [comment] 2023-03-10 19:29
Hi there,

Thank you for reaching out to us.

The submission looks like works on the Chrome Bowser, would you mind checking on the Chrome Bowser

Thank you for your support.

**Comment by LC-Pam** [comment] 2023-03-13 17:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-13 17:32 UTC
Labels: LCUS, problem
