### ISSUE TITLE
258. Add Digits

### ISSUE THREAD

**Issue by vim12345** [LeetCode-Feedback/LeetCode-Feedback#11619] opened 2023-02-09 07:28 UTC
class Solution {
public:
int addDigitHelper(int num){
    int sum=0;
    while(num!=0){
        int digit=num%10;
        sum+=digit;
        num=num/10;
    }
    return sum;

}
    int addDigits(int num) {
        while(num>9){
        num=addDigitHelper(num);
        
    }
    return num;
}

};

**Comment by LC-Pam** [comment] 2023-02-10 19:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-11 19:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-11 19:57 UTC
Labels: LCUS, problem
