### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by swastkk** [LeetCode-Feedback/LeetCode-Feedback#17581] opened 2023-10-28 06:55 UTC
#### Your LeetCode username
swastiksharma

#### Category of the bug

- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Binary Search
class Solution {
public:
    int search(vector<int>& nums, int target) {
        // Using lower bound concept.
        int res= lower_bound(nums.begin(), nums.begin()+nums.size(), target) -nums.begin();
        if (res!=nums.size() && nums[res]== target){
            return res;
        }
        else{
            return -1;
        }
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment] 2023-10-30 19:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:01
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:01 UTC
Labels: Waiting for Reply
