### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by miqdadamirali** [LeetCode-Feedback/LeetCode-Feedback#11772] opened 2023-02-15 21:02 UTC
#### Your LeetCode username
@myselfmiqdad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
New test cases are missing and identifying a bug in code that yields expected.

##### Case 1
```php
["car", "flower", "bus", "flow", "flight", "vehicle"]
```
<img width="707" alt="image" src="https://user-images.githubusercontent.com/9101445/219156881-6c3b34db-533d-41c8-b333-7cf4767fd1e5.png">

###### Expected
As per the instructions, the "longest common prefix string amongst an array of strings." would `fl` as there are three words that have the prefix. However, the expected is an empty string indicating no common prefix.

##### Case 2
```php
["flower", "car", "flow", "bus", "flight"]
```
<img width="689" alt="image" src="https://user-images.githubusercontent.com/9101445/219157906-9ee9aa01-ac02-493a-be08-a62d70900f2b.png">

###### Expected
As per the instructions, the "longest common prefix string amongst an array of strings." would `fl` as there are three words that have the prefix. However, the expected is an empty string indicating no common prefix.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
The instructions for the challenge state that the response should be the longest common prefix. However, when the test cases are changed to play around with input and output, the expected does not abide by the instructions. 

I have included above the expected for my custom test cases and what the expected should be. 

#### Screenshots
- Included above

**Comment by LC-Pam** [comment] 2023-02-16 18:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-20 04:13
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-20 04:13 UTC
Labels: LCUS, problem
