### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by Gangajyoti** [LeetCode-Feedback/LeetCode-Feedback#19651] opened 2024-01-23 00:45 UTC
### LeetCode Username
Gangajyoti

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Language used for code
python3

### Code used for Submit/Run operation

```
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        if str1 + str2 != str2 + str1:
            return ""
    
        from math import gcd
      
        return str1[:gcd(len(str1), len(str2))]
```

### Expected behavior
let's take some examples
Ex 1:
str1 = 'zz', str2='zzzz' for which output should be 'z'.
But the above code is generating output  as 'zz' which should not be the correct answer hence , we should add this test case to check actual string matching being done in the code.

Ex 2 :
str1 = 'zcdzzz', str2 = ''zcd' for this test case:
output should be 'zcd'
but the above code will generate output as ''.
Hence, this code should not be mark as passed/excepted but when i submitted the above code it is accepted because of missing test cases.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40793723/b9dc41fc-c114-4586-b63c-6c675bc275c0)

### Additional context
Kindly add some more edged test cases for this problem

**Comment by LC-Pam** [comment] 2024-01-23 20:31
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The valid test case: 'str1' must consist of values from A to Z only

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:16
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:16 UTC
Labels: Waiting for Reply
