### ISSUE TITLE
Missing Test Case - 2680. Maximum OR

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#13475] opened 2023-05-15 03:05 UTC
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2680. Maximum OR](https://leetcode.com/problems/maximum-or), an accepted solution fails on a specific test case.

```
[5,6,2]
1
```

#### Code you used for Submit/Run operation
```Java
class Solution {
    public long maximumOr(int[] nums, int k) {
        int n = nums.length;
        long[][] dp = new long[n + 1][k + 1];
        for (int i = 1; i <= n; i++) {
            for (int j = 0; j <= k; j++) {
                for (int m = 0; m <= j; m++) {
                    dp[i][j] = Math.max(dp[i][j], dp[i - 1][j - m] | (((long) 1 * nums[i - 1]) << m));
                }
            }
        }
        return dp[n][k];
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case above so the solution will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment] 2023-05-15 17:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. (https://leetcode.com/submissions/detail/950918315/)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-23 00:06
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-23 00:06 UTC
Labels: LCUS, problem
