### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by abhishekBhangalia** [LeetCode-Feedback/LeetCode-Feedback#18322] opened 2023-11-27 14:06 UTC
### LeetCode Username

abhangalia0001

### Problem number, title, and link

[50. Pow(x, n)](https://leetcode.com/problems/powx-n/) 

### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

I think test cases with n = -2^31 are missing. 
Because i used this line of code

n = abs(n);
if n is -2^31 then it should overflow and so all test cases should not be passed. But all of my testcases were passed.

### Language used for code

C++ 

### Code used for Submit/Run operation

```
double myPow(double x, int n) {
        if(n==0)    return 1;
        int N = abs(n); //abs(INT_MIN) will overflow 
       
        double ans = 1;
        while(N > 0){
            if(N%2 == 0){
                x = x*x;
                N = N/2;
            }
            else{
                ans *= x;
                N--;
            }
        }
        
        if(n<0)     ans = 1/ans;
        return ans;
    }
```

### Expected behavior

As mentioned above i am using absolute value of n here but if n is -2^31, then i can't take absolute value if variable is int. Because it will overflow.

**Comment by stormsunshine** [comment] 2023-11-27 23:00
Following is a complete test case.
```
1.0001
-2147483648
```

**Comment by LC-Pam** [comment] 2023-11-28 19:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-01 21:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed as completed by LC-Pam** 2023-12-01 21:47 UTC
Labels: Waiting for Reply
