### ISSUE TITLE
Missing Test Case - 258. Add Digits

### ISSUE THREAD

**Issue by Rahul23100** [LeetCode-Feedback/LeetCode-Feedback#17039] opened 2023-10-08 16:54 UTC
class Solution {
public:
    int addDigits(int num){
        if (num == 0) {
            return 0;
        } else if (num % 9 == 0) {
            return 9;
        } else {
            return num % 9;
        }
    }
};

**Comment by LC-Pam** [comment] 2023-10-09 19:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:38
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:38 UTC
Labels: Waiting for Reply
