### ISSUE TITLE
Missing Test Case - 491. Non-decreasing Subsequences

### ISSUE THREAD

**Issue by step-aside-peasant** [LeetCode-Feedback/LeetCode-Feedback#11154] opened 2023-01-21 10:41 UTC
#### Your LeetCode username
step-aside-peasant

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+ ] Missing Test Cases 

#### Description of the bug
Contributing new testcase

#### Code you used for Submit/Run operation

```
// 491. Non-decreasing Subsequences
var findSubsequences = function(nums) {
    let n = nums.length;
    let res = [];

    let helper = function (i, sub) {
        let unique = new Set();
        for (let j=i; j<n; j++) {
            if (unique.has(nums[j]) || sub.length > 0 && sub[sub.length-1] > nums[j]) continue
            unique.add(nums[j])
            sub.push(nums[j])
            if (sub.length >= 2) res.push([...sub])
            helper(j+1, sub)
            sub.pop()
        }
    }

    helper(0, [])
    return res
};
```

#### Language used for code
Javascript

#### Expected behavior
Based on the logic and conditions of the problem. I consider it necessary to add a new testcase. Where the first argument of the array will be the maximum value of this array. So it should return an empty array.

**Comment by LC-Pam** [comment] 2023-01-24 17:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The specific test case you suggest adding. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-26 18:28
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-26 18:28 UTC
Labels: LCUS, problem
