### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by arun98-mohan** [LeetCode-Feedback/LeetCode-Feedback#10609] opened 2022-12-29 15:28 UTC
#### Your LeetCode username

apmceg

#### Category of the bug
- [ ] Question You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.
- [ ] Solution
- [ ] class Solution {
    public int[] plusOne(int[] digits) {
        int length = digits.length;
            if(digits[length-1]!=9){
                digits[length-1]=digits[length-1]+1;
            }else{
                //check if all elements in the array are 9
                boolean flag9 = true; //assuming all elements are 9
                for(int i =0;i<length;i++){
                    if(digits[i]!=9){
                        flag9 = false;
                        break;
                    }
                }

                if(flag9){ // all elements are 9s, so we need to increase the size of array by 1
                int[] newArray = new int[length+1];
                newArray[0]=1;
                for(int i = 1;i<=length;i++){
                    newArray[i] = 0;
                }
                return newArray;

                }else{

                    digits[length-1] = 10;
                    for(int i = length-1;i>=0;i--){
                        if(digits[i]==10){
                            digits[i]=0;
                            digits[i-1]=digits[i-1]+1;
                        }
                    }

                }
            }
        return digits;
    }
}
- [ ] Language
- [ ] Java
- [ ] Missing Test Cases 
- [ ] 9899999999

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-12-29 19:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-30 19:34
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-30 19:34 UTC
Labels: LCUS, problem
