### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by Saumya-chaubey** [LeetCode-Feedback/LeetCode-Feedback#11253] opened 2023-01-25 06:57 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Saumya-chaubey** [comment] 2023-01-25 06:58
class Solution:
    def divide(self, dividend: int, divisor: int) -> int:
        a=dividend/divisor
        if dividend== -2147483648 and divisor== -1:
            return 2147483647
        return int(a)
0
0

**Comment by LC-Pam** [comment] 2023-01-25 18:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2023-01-26 00:01
The divisor can't be 0. Why are you providing such an illegal test case?

**Comment by LC-Pam** [comment] 2023-01-27 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-27 18:58 UTC
Labels: LCUS, problem
