### ISSUE TITLE
Editorial: Incorrect Approach 2 Single Index Hash Map

### ISSUE THREAD

**Issue by vib-hu** [LeetCode-Feedback/LeetCode-Feedback#15313] opened 2023-08-05 13:39 UTC
#### Your LeetCode username

vibhumishra808

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 2 given in the Editorial is not the right solution. It is not passing test case.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean wordPattern(String pattern, String s) {
        HashMap map_index = new HashMap();
        String[] words = s.split(" ");

        if (words.length != pattern.length())
            return false;

        for (Integer i = 0; i < words.length; i++) {
            char c = pattern.charAt(i);
            String w = words[i];

            if (!map_index.containsKey(c))
                map_index.put(c, i);

            if (!map_index.containsKey(w))
                map_index.put(w, i);

            if (map_index.get(c) != map_index.get(w))
                return false;
        }

        return true;
    }
}
//Failing Test case
pattern =
"ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdd"
s =
"s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s t t"
```

#### Expected behavior

For the above test case, the expected result should be true but solution is returning false.

#### Screenshots

<img width="838" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10459403/869be593-a339-439d-8b20-190c053e6c1f">

**Comment by LC-Pam** [comment] 2023-08-08 19:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:46 UTC
Labels: LCUS, problem, Waiting for Reply
