### ISSUE TITLE
ReversePolishNotation-error with compiler arithmetic interpretation 

### ISSUE THREAD

**Issue by philipp1343** [LeetCode-Feedback/LeetCode-Feedback#15730] opened 2023-08-19 09:08 UTC
#### Your LeetCode username

philipp1343

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug

wrong compiler arithmetic interpratation 

#### Code you used for Submit/Run operation

```

class Solution(object):
     
    def evalRPN(self, tokens):
        operators = ['+','-','*','/']
        stack = []
        for string in tokens:
            if string in operators:
               result = self.doCalc(stack, string)
               stack.append(result)
            else:
                stack.append(int(string))
        return stack[0]
    def doCalc(self, stack, operator_char):
        num2 = stack.pop()
        num1 = stack.pop()
        if operator_char == "+":
            result = num1 + num2
        elif operator_char == "-":
            result = num1 - num2
        elif operator_char == "*":
            result = num1 * num2
        elif operator_char == "/":
            if num2 == 0:
                return 0 
            result = int(num1 / num2)     
        return result

```

#### Expected behavior

Test case 3 from the Evaluate Reverse Polish notation question evaluates the calculation:(6 / -132) to -1 when it should be 0 

#### Screenshots

<img width="1396" alt="Screenshot 2023-08-19 at 14 36 34" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71379358/29d2ca20-8186-4119-acf0-f3dc40f3a44a">

#### Additional context

Ive tested this on my own machine and it works perfectly fine with the given token

**Comment by LC-Pam** [comment] 2023-08-21 20:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:22 UTC
Labels: Waiting for Reply
