### ISSUE TITLE
Incorrect Test Cases - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by VDnoob** [LeetCode-Feedback/LeetCode-Feedback#14368] opened 2023-06-26 11:46 UTC
#### Your LeetCode username
coVDer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In this question, it is clearly mentioned that the test cases are generated in such a way that answer lies within the range of a 32-bit signed integer which is not the case. The question should mention that answer can be large, so print it modulo 10^9 + 7.

#### Code you used for Submit/Run operation

```
//Distinct subsequences

int numDistinct(string s, string t) {
        int n = s.length();
        int m = t.length();
        
        if(m>n)return 0;
        
        vector<vector<long long>> dp(n+1,vector<long long>(m+1,0));
        
        for(int i = 0 ; i <= n ; ++i){
            for(int j = 0 ; j <= m ; ++j){
                if(i==0 and j!=0){
                    dp[i][j]=0;
                    continue;
                }
                
                if(j==0){
                    dp[i][j]=1;
                }
                else{
                    if(s[i-1]==t[j-1]){
                        dp[i][j] = (dp[i-1][j-1] + dp[i-1][j])%1000000007;
                    }
                    else{
                        dp[i][j] = dp[i-1][j];
                    }
                }
                
            }
        }
        
        return dp[n][m];
        
    }
```

#### Language used for code
 C++ 

#### Expected behavior

As the question mentioned, the answer should be within the range of a 32-bit integer I did not take proper measurements and my answer failed several times, but when I used the modulo operation then, it ran instantly.

**Comment by LC-Pam** [comment] 2023-06-27 18:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-29 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-29 18:15 UTC
Labels: LCUS, problem
