### ISSUE TITLE
Incorrect Testcase 2072 Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by AsadurRahmanRishan59** [LeetCode-Feedback/LeetCode-Feedback#19125] opened 2024-01-05 00:22 UTC
### LeetCode Username

Rishan_Rahman

### Problem number, title, and link

4. Median of Two Sorted Arrays](https://leetcode.com/problems/median-of-two-sorted-arrays/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Incorrect test Case *(Output of test case is incorrect as per the problem statement)
Testcase 2072 is incorrect. median of 1 and 2 should be 1.5 not 1.0

### Language used for code

Java

### Code used for Submit/Run operation

```class Solution {
    public double findMedianSortedArrays(int[] nums1, int[] nums2) {
        int[]result=merge(nums1,nums2,nums1.length,nums2.length);
        double median=0;
        int n=result.length;
        if(result.length%2==0){
            median=(((double)result[n/2])+((double)result[(n/2)-1]))/2;
        }else{
            median=result[n/2];
        }
        return median;
    }
     int[] merge(int[]a,int b[],int m,int n) {
		int result[]=new int[m+n];
		int i=0,j=0,k=0;
		while(i<m&&j<n) {
			if(a[i]<b[j]) {
				result[k]=a[i];
				i++;
			}else if(a[i]>b[j]) {
				result[k]=b[j];
				j++;
			}else {
				result[k]=a[i];
				i++;
				j++;
			}
			k++;
		}
		while(i<m) {
			result[k]=a[i];
			i++;
			k++;
		}
		while(j<n) {
			result[k]=b[j];
			j++;
			k++;
		}
		Stack<Integer>stack= new Stack<>();
		stack.push(result[0]);
		
		for(int x=1;x<result.length;x++) {
			if(!stack.isEmpty()&&stack.peek()!=result[x]&&result[x]!=0) {
				stack.push(result[x]);
			}
		}
		
		int resize[]=new int[stack.size()];
		
		for(int r=resize.length-1;r>=0;r--) {
			resize[r]=stack.pop();
		}
		return resize;
	}
}
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

median of merged array{1,2} should be 1.5

**Comment by LC-Pam** [comment] 2024-01-05 22:50
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-09 19:22
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-09 19:22 UTC
Labels: Waiting for Reply
