### ISSUE TITLE
Incorrect expected result for problem 2035: https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/

### ISSUE THREAD

**Issue by kaustubhdeokar** [LeetCode-Feedback/LeetCode-Feedback#17422] opened 2023-10-24 16:06 UTC
#### Category of the bug
- [ ] Question 
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x ] Incorrect Test Case 

#### Description of the bug

The question is to partition array into 2 such that difference of subset is minimum:
For testcase : array given is : [76,8,45,20,74,84,28,1]
Expected answer is 2
But answer = 0 is possible as follows 
subset 1: [76,84,8] -> sum 168
subset 2: [45,20,74,28,1] -> sum 168.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumDifference(int[] arr) {
        
        int minValue = 0;
        for(int i=0;i<arr.length;i++){
            if(arr[i]<0){
                minValue = Integer.min(minValue, arr[i]);
            }
        }
        System.out.println("minValue:"+minValue);

        int sum = 0;

        for(int i=0;i<arr.length;i++){
            arr[i] += Math.abs(minValue);
            sum+=arr[i];
        }

        System.out.println("sum:"+sum);

        int N = arr.length;
        int halfSum = 0;
        if(sum%2==0){
            halfSum = sum/2;
        }
        else{
            halfSum = sum/2+1;
        }

        System.out.println("halfSum:"+halfSum);

        int[][] dp = new int[N+1][halfSum+1];
        for(int i=0;i<=halfSum;i++){
            dp[0][i] = 0; // elements 0 -> no subset found.
        }
        for(int j=0;j<=N;j++){
            dp[j][0] = 1; // sum = 0 -> subset found.
        }
        
        knapsack(dp, arr, N, halfSum);

        int minDiff = Integer.MAX_VALUE;

        for(int i=0;i<=halfSum;i++){
            
             if(dp[N][i]>=1){
                System.out.println(i+":"+dp[N][i]+":"+Math.abs(sum -  2*i));
                minDiff = Integer.min(minDiff, Math.abs(sum -  2*i));
             }
        }
        
        return minDiff;
    }
    
     public static void knapsack(int[][] dp, int[] arr, int N, int sum){
        
        for(int i=1;i<=N;i++){
            for(int j=1;j<=sum;j++){
                
                if(j>=arr[i-1]){
                    dp[i][j] = dp[i-1][j - arr[i-1]] + dp[i-1][j];
                }
                else{
                    dp[i][j] = dp[i-1][j];
                }

            }
        }

      

    }

}
```

#### Expected behavior

The question is to partition array into 2 such that difference of subset is minimum:
For testcase : array given is : [76,8,45,20,74,84,28,1]
Expected answer is 2
But answer = 0 is possible as follows 
subset 1: [76,84,8] -> sum 168
subset 2: [45,20,74,28,1] -> sum 168.

#### Screenshots

![Screenshot from 2023-10-24 21-36-05](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31384557/c99611e7-fccc-4d11-a94f-a98ef4a63fae)

**Comment by LC-Pam** [comment] 2023-10-24 17:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kaustubhdeokar** [comment] 2023-10-24 18:00
It is not accepted. It fails the above mentioned test case

**Comment by LC-Pam** [comment] 2023-10-25 18:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

We only check and add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 19:03
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

Your code received Wrong Answer: https://leetcode.com/submissions/detail/1085587492/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-10-27 19:03 UTC
Labels: Waiting for Reply
