### ISSUE TITLE
735. Asteroid Collision

### ISSUE THREAD

**Issue by mannu-747** [LeetCode-Feedback/LeetCode-Feedback#14896] opened 2023-07-20 07:33 UTC
If we take example
[5,10,-12,10]

The answer is -12
but we are getting [-12,10].

**Comment by LC-Pam** [comment] 2023-07-20 19:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by agrawalishaan** [comment] 2023-07-21 19:27
the answer is [-12, 10]

**Comment by LC-Pam** [comment] 2023-07-25 21:21
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-25 21:21 UTC
Labels: LCUS, problem, Waiting for Reply
