### ISSUE TITLE
110. Balanced Binary Tree - A bug in checking my answer

### ISSUE THREAD

**Issue by dordor7** [LeetCode-Feedback/LeetCode-Feedback#16895] opened 2023-10-03 12:02 UTC
I try running the following naive solution:

```
    int treeHeight(TreeNode* root) {
        if (!root) { return 0; }

        return max(treeHeight(root->left), treeHeight(root->right)) + 1;
    }

    bool isBalanced(TreeNode* root) {
        if (!root) { return true; }
        
        int diff = abs(treeHeight(root->left) - treeHeight(root->right));
    
        return diff <= 1 && isBalanced(root->left) && isBalanced(root->left);     
    
    }
```

And for the test case:
[1,2,3,4,5,null,6,7,null,null,null,null,8]

It says my solution returns 'true' - which is wrong.

But this solution is identical to many other naive solutions I saw on the solutions section.
So... I checked on Visual Studio - copied and pasted my solution - and it returns **false** for the same test case.

How come?

**Comment by LC-Pam** [comment] 2023-10-03 20:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by anups1ngh** [comment] 2023-10-04 10:23
Hii @dordor7 you are just calling **isBalanced** on _root.left_ both times. You have to call _root.right_ and it will work . 

Nice approach ! keep it up

**Comment by dordor7** [comment] 2023-10-05 14:26
> Hii @dordor7 you are just calling **isBalanced** on _root.left_ both times. You have to call _root.right_ and it will work .
> 
> Nice approach ! keep it up

Ohhh I see anups, missed that.

Thanks for your kind reply :)

**Comment by LC-Pam** [comment] 2023-10-05 17:33
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:33 UTC
Labels: Waiting for Reply
