### ISSUE TITLE
Missing Test Case - 383. Ransom Note

### ISSUE THREAD

**Issue by kofmanA** [LeetCode-Feedback/LeetCode-Feedback#9573] opened 2022-10-21 23:04 UTC
#### Your LeetCode username

Akofkof

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Not a bug but a missing test case. You should have "aa" as ransomNote and "aba" as magazine.
It's unclear whether the letters in magazine have to appear in sequence or not.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean canConstruct(String ransomNote, String magazine) {
        for(int i = 0; i < magazine.length(); i++) {
            if(magazine.charAt(i) == ransomNote.charAt(0)){
                boolean wordComplete = true;
                for(int j = 0; j < ransomNote.length(); j++) {
                    if(ransomNote.charAt(j) == magazine.charAt(i+j))
                        continue;
                    else
                        wordComplete = false;
                        break;
                }
                if(wordComplete)
                    return true;
            }
        }
        return false;
    }
}
```

#### Expected behavior

I believe my code shouldn't work because if the letters don't appear in sequence, it won't work, but leetcode passes it.

**Comment by LC-Pam** [comment] 2022-10-24 17:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 16:05
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 16:05 UTC
Labels: LCUS, problem
