### ISSUE TITLE
Missing Test Case - 1378. Replace Employee ID With The Unique Identifier

### ISSUE THREAD

**Issue by mrlutton** [LeetCode-Feedback/LeetCode-Feedback#16203] opened 2023-09-05 12:09 UTC
#### Your LeetCode username
mrlutton

#### Category of the bug
- [ ] Solution

#### Description of the bug
Should work with below queries (both)

"#### Code you used for Submit/Run operation
SELECT
    COALESCE(CAST(eu.unique_id AS CHAR), 'null') AS unique_id,
    e.name
FROM Employees e
LEFT JOIN EmployeeUNI eu ON e.id = eu.id;"

OR

"SELECT
    CASE
        WHEN eu.unique_id IS NULL THEN 'null'
        ELSE CAST(eu.unique_id AS CHAR)
    END AS unique_id,
    e.name
FROM Employees e
LEFT JOIN EmployeeUNI eu ON e.id = eu.id;"
```

#### Language used for code
SQL


#### Expected behavior
Expected output matches output created

**Comment by LC-Pam** [comment] 2023-09-05 21:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-11 19:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-11 19:48 UTC
Labels: Waiting for Reply
