### ISSUE TITLE
use balanced string Missing Test Case - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by shiv1406** [LeetCode-Feedback/LeetCode-Feedback#13319] opened 2023-05-06 14:58 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by shiv1406** [comment] 2023-05-06 14:59
int count0 = 0;
        int count1 =0;
        int ans =0;
        for(int i =0;i<s.length();i++){
            if(s[i]== 'R'){
                count0++;
            }
            else {
                count1++;
            }
            
            if(count0==count1){
                ans++;
                count0=0;
                count1=0;
            }
        }
      if(ans==0||count0!=0||count1!=0){
            return -1;
        }
        return ans;
    }

**Comment by LC-Pam** [comment] 2023-05-08 21:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:19 UTC
Labels: LCUS, problem
