### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14907] opened 2023-07-20 18:29 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Container With Most Water
class Solution {
    public int maxArea(int[] height) {
        int left=0;
        int right=height.length -1;
        int maxArea=0;
        while(left<right)
        {
            int currentArea=Math.min(height[left],height[right])*(right-left);
            maxArea=Math.max(maxArea,currentArea);

            if(height[left]<height[right])
            {
                left++;
            }
            else
            {
                right--;
            }
        }
        return maxArea;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-20 19:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-25 21:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-25 21:23 UTC
Labels: LCUS, problem, Waiting for Reply
