### ISSUE TITLE
Missing Test Case - 1108. Defanging an IP Address

### ISSUE THREAD

**Issue by k3d4r2** [LeetCode-Feedback/LeetCode-Feedback#14458] opened 2023-07-01 03:05 UTC
#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug

Test cases : 
| Input| Output |
|--------|--------|
| "192.168.1.2" | "192[.]168[.]1[.]2" |
| "10.10.1.2" | "10[.]10[.]1[.]2" |
| "172.176.1.2" | "172[.]176[.]1[.]2" |

**Comment by LC-Pam** [comment] 2023-07-03 19:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case in JSON format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:10 UTC
Labels: LCUS, problem
