### ISSUE TITLE
LC Interview Crash Cource: Binary Search - On Arrays. Wrong index

### ISSUE THREAD

**Issue by kbulau** [LeetCode-Feedback/LeetCode-Feedback#17184] opened 2023-10-12 15:54 UTC
In the _Binary Search_ chapter segment _On Arrays_, the video calculates mid as index 5 but refers to index 4 on the chart. Although minor, it might confuse some people.

**Comment by LC-Pam** [comment] 2023-10-12 18:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-17 20:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-17 20:57 UTC
Labels: Waiting for Reply
