### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Murdocman17** [LeetCode-Feedback/LeetCode-Feedback#9962] opened 2022-11-19 01:59 UTC
#### Category of the bug
- [two sum ] Question
- [ ] Solution
- [python ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![Screenshot_2022-11-19-08-44-32-74](https://user-images.githubusercontent.com/116491636/202828882-13dc2ec4-93a2-465d-ba75-72fd35cc6183.jpg)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```def twoSum(nums,target):
	for i in range(len(nums)-1):
		for j in range(i+1,len(nums)):
			if nums[i]+nums[j]==target:
				return nums[i],nums[j]

**Comment by Murdocman17** [comment] 2022-11-19 02:00
Same thing happened yesterday with question "ugly number"

**Comment by LC-Pam** [comment] 2022-11-21 18:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-11-23 22:15
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-11-23 22:15 UTC
Labels: LCUS, problem
