### ISSUE TITLE
Missing Test Case - 2405. Optimal Partition of String

### ISSUE THREAD

**Issue by madscorpio20** [LeetCode-Feedback/LeetCode-Feedback#9073] opened 2022-09-15 18:19 UTC
#### Category of the bug
- [ ] Solution

#### Description of the bug
submission successful in iterative but not using recusrion

#### Code you used for Submit/Run operation

```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!--when i was trying to solve question optimal partition of string it is giving me memory limit exceeds if i try to do it via recursion whereas when i do it iterative it is a successful submission-->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2022-09-16 10:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code  you submitted to reach this result.
Or 
The submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-18 06:41
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-18 06:41 UTC
Labels: LCUS, problem
