### ISSUE TITLE
Missing Test Case - [3,5,1,6,2,0,8,null,null,7,4,11, null, null, null, null, null, null, 33, 22] | 23. Lowest Common Ancestor of Deepest Leaves (it gives the input as the expected output)

### ISSUE THREAD

**Issue by singhxayush** [LeetCode-Feedback/LeetCode-Feedback#18014] opened 2023-11-12 16:37 UTC
### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment] 2023-11-13 20:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:20 UTC
Labels: Waiting for Reply
