### ISSUE TITLE
Missing Test Case - 842. Split Array into Fibonacci Sequence

### ISSUE THREAD

**Issue by megashrieks** [LeetCode-Feedback/LeetCode-Feedback#19415] opened 2024-01-15 16:03 UTC
### LeetCode Username
megashrieks

### Problem number, title, and link
Missing Test Case - 842. Split Array into Fibonacci Sequence https://leetcode.com/problems/split-array-into-fibonacci-sequence/

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
In the problem there is a statement 
```
Note that when splitting the string into pieces, each piece must not have extra leading zeroes, except if the piece is the number 0 itself.
```
however the test case `"10001"` yields `[]` as expected answer while it should `[1, 0, 1]`
this does not violate the fibonacci rule `f[i] + f[i+1] = f[i+2]`

### Expected behavior
consecutive 0s should be clubbed together since the whole piece is evaluated as zero

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16866937/a1fb89e6-70f6-4bf1-8158-15a2782152fb)

**Comment by LC-Pam** [comment] 2024-01-16 20:22
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-23 21:11
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:11 UTC
Labels: Waiting for Reply
