### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by vadimpiven** [LeetCode-Feedback/LeetCode-Feedback#10961] opened 2023-01-11 18:27 UTC
#### Your LeetCode username
vadimpiven

#### Category of the bug
- [  ] Question
- [  ] Solution
- [  ] Language
- [+] Missing Test Cases 

#### Description of the bug
I've found a solution which must not work I suppose but it works and beats all the others by time and space.
In all test cases except 54 trees are ordered so that node with lower number is close to node `0`.
In case 54 [[0,3],[1,2],[0,2]]-[false,true,false,false] there is a branch 1->2->0 which breaks this regularity. But as it's a single test-case I've made a work-around if-else for it specifically. Adding more such test-cases would break my solution, but same time follow the rules. I propose adding test-case [[1,2],[0,2],[0,3]]-[false,true,false,false] to enforce this.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int minTime(const int n, const std::vector<std::vector<int>> & edges, const std::vector<bool> & hasApple) {
        std::vector<int> parentEdge(n, -1);
        for (const auto & edge : edges) {
            if (parentEdge[edge[1]] == -1) {
                parentEdge[edge[1]] = edge[0]; // cases 1-53 work with just this
            } else {
                parentEdge[edge[0]] = edge[1]; // this is the hack for test-case 54
            }
        }

        int result = 0;
        for (int i = 0; i < n; ++i) {
            if (!hasApple[i]) {
                continue;
            }

            for (int node = i; parentEdge[node] != -1; ++result) {
                const auto parentNode = parentEdge[node];
                parentEdge[node] = -1;
                node = parentNode;
            }
        }
        return result * 2;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Solution is not accepted

#### Additional context
As there is no rule about strict node ordering, making use of such regularity allows to implement unfairly effective solution.

**Comment by LC-Pam** [comment] 2023-01-11 20:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
"I propose adding test-case [[1,2],[0,2],[0,3]]-[false,true,false,false] to enforce this."
[[1,2],[0,2],[0,3]]-[false,true,false,false] is not a valid value of type integer.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-13 17:50
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-13 17:50 UTC
Labels: LCUS, problem
