### ISSUE TITLE
Solved Test Case - 584. Find Customer Referee

### ISSUE THREAD

**Issue by laxmi13579** [LeetCode-Feedback/LeetCode-Feedback#19839] opened 2024-01-29 08:22 UTC
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by laxmi13579** [comment] 2024-01-29 08:23
```
SELECT name
FROM Customer
WHERE referee_id <> 2 or referee_id is null;
```
<img width="686" alt="Screenshot 2024-01-29 at 1 51 32 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33938782/c4d67a5d-a4fe-4a00-9f94-f5733f1a7c9b">

**Comment by LC-Pam** [comment] 2024-01-31 16:33
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-02-07 21:08
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-02-07 21:08 UTC
Labels: Waiting for Reply
