### ISSUE TITLE
Missing Test Case - 1431. Kids With the Greatest Number of Candies

### ISSUE THREAD

**Issue by koldunchik** [LeetCode-Feedback/LeetCode-Feedback#18553] opened 2023-12-08 19:48 UTC
### LeetCode Username
user2957P

### Problem number, title, and link
https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Input
candies =
[2,3,5,1,3]
extraCandies =
3
Output
[false,false,true,false,false]

Expected output is incorrect
[true,true,true,false,true]

### Language used for code
Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.


     List<Boolean> result = new ArrayList<>();

     long max = 0;
     for (int i = 0; i < candies.length; i++) {
         if ((candies[i] + extraCandies) > max) {
             max = candies[i] + extraCandies;
         }
     }

     for (int i = 0; i < candies.length; i++) {
         result.add( (candies[i] + extraCandies) >= max );
     }

     return result;
```

### Expected behavior

[false,false,true,false,false]

**Comment by LC-Pam** [comment] 2023-12-12 23:10
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-19 18:13
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-19 18:13 UTC
Labels: Waiting for Reply
