### ISSUE TITLE
Missing Test Case - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by rushikamod28** [LeetCode-Feedback/LeetCode-Feedback#13187] opened 2023-04-28 09:32 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by rushikamod28** [comment] 2023-04-28 09:33
Input:
["MyQueue", "push", "push", "pop", "push", "pop", "pop", "empty"]
[[], [1], [2], [], [3], [], [], []]

Output:
[null, null, null, 1, null, 2, 3, true]

Explanation:
MyQueue myQueue = new MyQueue();
myQueue.push(1); // queue is: [1]
myQueue.push(2); // queue is: [1, 2] (leftmost is front of the queue)
myQueue.pop(); // return 1, queue is [2]
myQueue.push(3); // queue is: [2, 3]
myQueue.pop(); // return 2, queue is [3]
myQueue.pop(); // return 3, queue is []
myQueue.empty(); // return true

**Comment by LC-Pam** [comment] 2023-04-28 22:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-02 21:36
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-02 21:36 UTC
Labels: LCUS, problem
