### ISSUE TITLE
Missing Test Case - 3026. Maximum Good Subarray Sum

### ISSUE THREAD

**Issue by hithamomaar** [LeetCode-Feedback/LeetCode-Feedback#19992] opened 2024-02-03 16:26 UTC
### LeetCode Username
HithamOmar

### Problem number, title, and link
3026. Maximum Good Subarray Sum https://leetcode.com/problems/maximum-good-subarray-sum/

### Category of the bug=
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

missing TLE test case

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    long long maximumSubarraySum(vector<int>& nums, int k) {
        long long n=nums.size(),ans=LLONG_MIN;
        vector<long long>v(n+5),pr(n+5);
        map<long long,vector<int>>mp;
        for(int i=1;i<=n;i++){
            v[i]=pr[i]=nums[i-1];
            mp[v[i]].push_back(i);
            pr[i]+=pr[i-1];
        }
        for(auto i:mp){
            if(mp.count(i.first+k)){
                for(auto j:i.second){
                    for(auto z:mp[i.first+k]){
                        int mn=min(j,z),mx=max(j,z);
                        ans=max(ans,pr[mx]-pr[mn-1]);
                    }
                }
            }
        }
        if(ans==LLONG_MIN)ans=0;
        return ans;
        
    }
};
```

### Expected behavior

my code should give TLE not AC
cause in worst case i can have 5e4 of 1 and 5e4 of 2
i do nested loop on it.. so the time will pass 2sec

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/129246511/0b848975-65ae-41a8-9ca9-c5cba30e079f)

**Comment by LC-Pam** [comment] 2024-02-05 15:14
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by hithamomaar** [comment] 2024-02-05 16:31
I've mentioned details in the Expected behavior

**Comment by LC-Pam** [comment] 2024-02-23 21:31
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

The code currently received TLE: https://leetcode.com/submissions/detail/1184338669/
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Closed by LC-Pam** 2024-02-23 21:31 UTC
Labels: Waiting for Reply
