### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by bharathbaba** [LeetCode-Feedback/LeetCode-Feedback#12870] opened 2023-04-09 15:17 UTC
class Solution {
    public int searchInsert(int[] nums, int target) {
        int j=1;
        int start=0;
        int end=nums.length-1;
          
        for(int i=0;i<nums.length-1;i++)
        {
            if(nums[i]==target )
            {
               
                nums[j]=nums[i];
                ++j;
                return j;
                
            }
            else if(nums[end]<target)
            {
                nums[end]=target;
                end++;
                return end;
            }
            else if(nums[start]>target)
            {
                nums[start]=target;
                
                return start;
            }
            else {
            nums[start + 1] = target; // insert the target element at the appropriate position
            return start + 1; // return the index where the target element was inserted
        }
            

           
        }
        return 0;
        
    }

**Comment by LC-Pam** [comment] 2023-04-10 22:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-12 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-12 19:47 UTC
Labels: LCUS, problem
