### ISSUE TITLE
Missing Test Case - 202. Happy Number

### ISSUE THREAD

**Issue by vinnu9112** [LeetCode-Feedback/LeetCode-Feedback#13131] opened 2023-04-24 14:34 UTC
#### Your LeetCode username
 vinnnu

#### Category of the bug
- [ Happy Number] Question
- [class Solution {
public:
    bool isHappy(int n) {
        long rem = 0, a = 0;
        while(n != 0){
            rem = n%10;
            a += pow(rem, 2);
            n/=10;
            if(n == 0 && a > 9){
                n = a;
                a = 0;
            }
        }
        if (a==1 || a==7) return 1;
        return 0;
    }
}; ] Solution
- [C++ ] Language
- [7 ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isHappy(int n) {
        long rem = 0, a = 0;
        while(n != 0){
            rem = n%10;
            a += pow(rem, 2);
            n/=10;
            if(n == 0 && a > 9){
                n = a;
                a = 0;
            }
        }
        if (a==1 || a==7) return 1;
        return 0;
    }
};```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-04-24 18:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-26 19:43
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-26 19:43 UTC
Labels: LCUS, problem
