### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by AfroDemigod** [LeetCode-Feedback/LeetCode-Feedback#8407] opened 2022-07-28 11:31 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

![Screenshot_20220728-133040](https://user-images.githubusercontent.com/106202623/181495053-72681755-c379-4b6a-9ebf-88abf94bd05d.jpg)

**Comment by LC-Pam** [comment] 2022-07-28 17:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the missing test case or issues?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:54
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:54 UTC
Labels: LCUS, problem
