### ISSUE TITLE
Dictionary sorting "trapping-rain-water"

### ISSUE THREAD

**Issue by jac267** [LeetCode-Feedback/LeetCode-Feedback#9840] opened 2022-11-11 18:03 UTC
#### Your LeetCode use

jac267

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

it won't sort my dict properly, I tested it in another python interpreter and it work fine with and without the sort (because you should not need it in the first place)

#### Code you used for Submit/Run operation

from collections import OrderedDict

class Solution(object):
    def trap(self, height):
        """
        :type height: List[int]
        :rtype: int
        """
        compteur = 0
        index = 0
        memoire = {}
        
        for i in range(len(height)):
            index = i -1
            
            #print(str(memoire) + "->" + str(compteur))
            if memoire != {}:
                
                a1 = list(memoire.values())[-1]
                i1 = list(memoire.keys())[-1]
                
                a2 = height[i]  - height[i-1]
                i2 = index
                
                
                
                if a2 != 0:
                    
                        
                    memoire.update({i2:a2})
                    
                    
                    if index == 8:
                        
                        dicte = {0: 1, 8: -1, 2: 1, 6: 1, 7: -1}

                        
                    
                    #verifier si on a affaire a un troue donc a1 < 0 et a2 > 0
                    
                    if a1 < 0 and a2 > 0:
                        
                        a = 0
                        #trouver la plus petite valeur (sans le negatif)
                        if -a1 <= a2:
                            a = -a1
                        else:
                            a = a2
                            
                        compteur += a*(i2-i1)
                        
                        #trouver la plus petite valeur (sans le negatif)
                        
                        if -a1 == a2:
                            a1 = 0
                            a2 = 0
                        elif -a1 > a2:
                            a1 = a1 + a2
                            a2 = 0
                        else:
                            a2 = a1 + a2
                            a1 = 0
                        
                        if a1 == 0:
                            del memoire[i1]
                        else:
                            memoire.update({i1:a1})
                        
                        if a2 == 0:
                            if len(memoire)-1 != 0:
                                del memoire[i2]
                        else:
                            memoire.update({i2:a2})
                            
                    
                    #verifier si on ontient pas desormait une suite a1 < 0 and a2 > 0
                    
                    if len(memoire) >= 2:
                       
                        try:
                            
                            while list(memoire.values())[-2] < 0 and list(memoire.values())[-1] > 0:
                                    
                                

                                    a1 = list(memoire.values())[-2]
                                    a2 = list(memoire.values())[-1]
                                    i1 = list(memoire.keys())[-2]
                                    i2 = list(memoire.keys())[-1]
                                    a = 0
                                    
                                    
                                    #trouver la plus petite valeur (sans le negatif)
                                    if -a1 <= a2:
                                        a = -a1
                                    else:
                                        a = a2
                                    
                                    compteur += a*(i2-i1)
                                    
                                    #trouver la plus petite valeur (sans le negatif)

                                    if -a1 == a2:
                                        a1 = 0
                                        a2 = 0
                                    elif -a1 > a2:
                                        a1 = a1 + a2
                                        a2 = 0
                                    else:
                                        a2 = a1 + a2
                                        a1 = 0

                                    
                                    if a1 == 0:
                                        del memoire[i1]
                                    else:
                                        memoire.update({i1:a1})
                                        
                                    if a2 == 0:

                                        if len(memoire)-1 != 0:
                                            del memoire[i2]
                                    else:
                                        memoire.update({i2:a2})
                                        
                                    
                        except:
                            pass
            else:
                if i != 0:
                    
                    a = height[i] - height[i-1]
                    
                    if a != 0:
                        memoire.update({index:a})
                        memoire = dict(sorted(memoire.items()))
                    
            
                
          
                
        
        
        
        
        
                
        return compteur
        

#### Language used for code

Python

#### Expected behavior

dict update working properly like in any interpreter

#### Screenshots

![2022-11-11 13_02_24-Trapping Rain Water - LeetCode](https://user-images.githubusercontent.com/64326015/201401437-e7d49d9c-86db-40a8-b08d-c2cf6212dc13.png)
![2022-11-11 13_02_40-Online Python Compiler (Interpreter)](https://user-images.githubusercontent.com/64326015/201401450-f06765cd-703f-4c0f-addc-3cf1492f794e.png)

**Comment by nskybytskyi** [comment] 2022-11-12 08:01
When I submit your solution it gets AC: https://leetcode.com/submissions/detail/841825821/ (I took the liberty to auto-format the code). Could you please clarify what the issue is?

**Comment by LC-Pam** [comment] 2022-11-15 20:47
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-11-15 20:47 UTC
