### ISSUE TITLE
Missing Test Case - 2665. Counter II ------------my solve

### ISSUE THREAD

**Issue by NgoDuc2505** [LeetCode-Feedback/LeetCode-Feedback#13325] opened 2023-05-07 04:04 UTC
my solve 

var createCounter = function(init) {
    const pureInput = init;
    let current= init;
    return{
        increment: ()=>{
            current+=1;
            return current;
        },
        reset: ()=>{
            current = pureInput;
            return current;
        },
        decrement: ()=>{
             current-=1;
            return current;
        },
    }
};

**Comment by LC-Pam** [comment] 2023-05-08 21:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The anguage you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:17 UTC
Labels: LCUS, problem
