### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by gogirlriya** [LeetCode-Feedback/LeetCode-Feedback#14887] opened 2023-07-19 19:14 UTC
All test cases are successfully fulfilled and code got submitted with 100% beats for below code where it's just returning true and not applying any logic.
{
return True;
}

Need to add testcases for failure cases also.

**Comment by LC-Pam** [comment] 2023-07-20 19:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gogirlriya** [comment] 2023-07-20 20:14
Hi LeetCode-Feedback/LeetCode-Feedback,
Code Accepted Link-
https://leetcode.com/problems/stone-game/submissions/998738808/
[image: image.png]
Missing test case- For all test cases Alice wins, we need a test case when
Bob wins and Alice loses and code returns false.

Regards,
Riya Khanna

**Comment by stormsunshine** [comment] 2023-07-20 23:28
Actually, it can be proven that the correct answer is always true.

If you can't provide a test case that should return false, you are wasting others' time. Could you please think a bit more before creating this issue?

**Comment by LC-Pam** [comment] 2023-07-25 21:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-25 21:19 UTC
Labels: LCUS, problem, Waiting for Reply
