### ISSUE TITLE
Missing Test Case - 63. Unique Paths II

### ISSUE THREAD

**Issue by DarkHacker28** [LeetCode-Feedback/LeetCode-Feedback#15521] opened 2023-08-12 05:12 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

int main() {
    Solution solution;

    vector<vector<int>> obstacleGrid1 = {
        {0, 0, 0},
        {0, 1, 0},
        {0, 0, 0}
    };
    cout << "Test Case 1: " << solution.uniquePathsWithObstacles(obstacleGrid1) << endl;  // Output: 2

    vector<vector<int>> obstacleGrid2 = {
        {0, 0, 0},
        {0, 0, 0},
        {0, 0, 0}
    };
    cout << "Test Case 2: " << solution.uniquePathsWithObstacles(obstacleGrid2) << endl;  // Output: 6

    vector<vector<int>> obstacleGrid3 = {
        {0, 1, 0},
        {0, 0, 0},
        {0, 0, 0}
    };
    cout << "Test Case 3: " << solution.uniquePathsWithObstacles(obstacleGrid3) << endl;  // Output: 3

    vector<vector<int>> obstacleGrid4 = {
        {0, 0, 0},
        {1, 1, 0},
        {0, 0, 0}
    };
    cout << "Test Case 4: " << solution.uniquePathsWithObstacles(obstacleGrid4) << endl;  // Output: 1

    vector<vector<int>> obstacleGrid5 = {
        {0, 0, 0},
        {0, 0, 0},
        {0, 0, 1}
    };
    cout << "Test Case 5: " << solution.uniquePathsWithObstacles(obstacleGrid5) << endl;  // Output: 0

    return 0;
}

**Comment by DarkHacker28** [comment] 2023-08-12 05:13
code:

#include <vector>
#include<iostream>
using namespace std;

class Solution {
public:
    int uniquePathsWithObstacles(vector<vector<int>>& obstacleGrid) {
        int m = obstacleGrid.size();
        int n = obstacleGrid[0].size();
        vector<vector<int>> dp(m,vector<int>(n, 0));
        dp[0][0] = (obstacleGrid[0][0] == 0) ? 1 : 0;
 
for (int i = 1; i < m; ++i) {
    dp[i][0] = (obstacleGrid[i][0] == 0) ? dp[i - 1][0] : 0;
        }
for (int j = 1; j < n; ++j) {
    dp[0][j] = (obstacleGrid[0][j] == 0) ? dp[0][j - 1] : 0;
        }
for (int i = 1; i < m; ++i) {
    for (int j = 1; j < n; ++j) {
        if (obstacleGrid[i][j] == 0) {
            dp[i][j] = dp[i - 1][j] + dp[i][j - 1];
                }
            }
        }
        return dp[m - 1][n - 1];
    }
};

**Comment by LC-Pam** [comment] 2023-08-14 20:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-16 19:49
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-16 19:49 UTC
Labels: Waiting for Reply
