### ISSUE TITLE
Missing Test Case - 1581. Customer Who Visited but Did Not Make Any Transactions

### ISSUE THREAD

**Issue by ST10185940** [LeetCode-Feedback/LeetCode-Feedback#19745] opened 2024-01-25 15:16 UTC
### LeetCode Username

ST10185940

### Problem number, title, and link

https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/?envType=study-plan-v2&envId=top-sql-50

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

MySQL

### Code used for Submit/Run operation

```
select v.customer_id , count(t.transaction_id) as count_no_trans
from Visits as v 
join Transactions as t
on v.visit_id = t.visit_id
where t.amount = 0 or t.visited_id is null
group by v.customer_id;
```

### Expected behavior

users who visited without making any transactions and the number of times they made these types of visits.

**Comment by LC-Pam** [comment] 2024-01-25 21:43
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:17
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:17 UTC
Labels: Waiting for Reply
