### ISSUE TITLE
grammatical error

### ISSUE THREAD

**Issue by 99swatimaurya** [LeetCode-Feedback/LeetCode-Feedback#18115] opened 2023-11-17 08:49 UTC
"You are to calculate a 1-indexed array answer of size k such that, for each j (1 <= j <= k), answer[j] is the number of users whose UAM equals j" 

It should be:-
"You have to calculate a 1-indexed array answer of size k such that, for each j (1 <= j <= k), answer[j] is the number of users whose UAM equals j."

**Comment by LC-Pam** [comment] 2023-11-17 20:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:09 UTC
Labels: Waiting for Reply
