### ISSUE TITLE
Missing Test Case - 122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by archie2106** [LeetCode-Feedback/LeetCode-Feedback#11613] opened 2023-02-08 22:18 UTC
class Solution {
public:
    int maxProfit(vector<int>& prices) 
    {
        int net_profit = 0;

        for(int i= 1; i<prices.size(); i++){

            if( prices[i]>prices[i-1])
            net_profit += (prices[i]- prices[i-1]);
        }
        return net_profit; 
    }
};

**Comment by LC-Pam** [comment] 2023-02-10 19:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-11 19:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-11 19:57 UTC
Labels: LCUS, problem
