### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by Prateek-Fst** [LeetCode-Feedback/LeetCode-Feedback#18594] opened 2023-12-11 05:07 UTC
test case number 1 is incorrect 
 the value of indices array should be [4,5,6,7,0,1,2,3] instead of [4,5,6,7,0,2,1,3]

**Comment by LC-Pam** [comment] 2023-12-12 23:30
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code snippet and programming language you submitted that led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-14 22:27
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-14 22:27 UTC
Labels: Waiting for Reply
