### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by 6jing** [LeetCode-Feedback/LeetCode-Feedback#18177] opened 2023-11-20 12:52 UTC
### LeetCode Username
6jing

### Problem number, title, and link
Minimum Size Subarray Sum https://leetcode.cn/problems/minimum-size-subarray-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [√ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ √] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Enter 11 and [1,2,3,4,6], and find that the expected value is 3, but 3+4+6 is not equal to 11, and the expected value of this input case should be 0

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment] 2023-11-20 21:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:14
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:14 UTC
Labels: Waiting for Reply
