### ISSUE TITLE
Missing Test Case - 812. Larges[[2,0],[1,0],[1,1]]t Triangle Area

### ISSUE THREAD

**Issue by VelSpace** [LeetCode-Feedback/LeetCode-Feedback#9952] opened 2022-11-18 08:48 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment] 2022-11-18 12:05
Thank you for reaching out. To help further assess this issue, would you please share the following information:

- The code used for run/submit operation.
- The missing test case such that the code gets accepted but fails on this test case?

**Comment by VelSpace** [comment] 2022-11-18 12:45
No without this test case also solution will passed but this is made by
mine if it is not exist then add it

**Comment by nskybytskyi** [comment] 2022-11-18 12:49
We typically don't add test cases if there are no issues with the current test suite, as additional test cases make the testing slower and take up additional space. If there is no solution that passes all current tests but fails on your test case, I'm afraid it won't be added.

**Comment by LC-Pam** [comment] 2022-11-18 19:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-11-21 17:02
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-11-21 17:02 UTC
Labels: LCUS, problem
