### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by priyanshat16** [LeetCode-Feedback/LeetCode-Feedback#13582] opened 2023-05-20 09:41 UTC
#### Your LeetCode username
priyanshat16

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Missing Test Cases

[[0,1],[1,65]]

#### Code you used for Submit/Run operation
class Solution {
public:
    void setZeroes(vector<vector<int>>& a) {
int m,n;

m = a.size();
n = a[0].size();
int count =0;    
for(int i=0; i<m; i++)
{
    for(int j=0; j<n; j++)
    {
        if(a[i][j]== 0)
        {
            
            for(int k=i,p=j ,t=0 ,r=0; t<n || r<m; t++,r++)
            {
                if(t <n && a[k][t] !=0)
                {
                    a[k][t] = 'A';
                    count++;
                }
                if(r <m && a[r][p] !=0)
                {
                    a[r][p] ='A';
                    cout<<a[r][p]<<endl;
                    count++;

                }

        }
    }
}
}
for(int i=0; i<m && count>0; i++)
{

    for(int j=0; j<n; j++ )
    {
        if(a[i][j]=='A')
        {
            a[i][j] =0;
        }
    }
}
    }
};

#### Language used for code
C++

#### Expected behavior
This testcase was missing so the above code got submitted successfully.
[[0,1],[1,65]]

**Comment by LC-Pam** [comment] 2023-05-23 00:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-26 19:49
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-26 19:49 UTC
Labels: LCUS, problem
