### ISSUE TITLE
Missing Test Case - 2625. Flatten Deeply Nested Array

### ISSUE THREAD

**Issue by yinyanan1993** [LeetCode-Feedback/LeetCode-Feedback#13400] opened 2023-05-11 07:30 UTC
#### Your LeetCode username

尹亚男

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```JavaScript
/**
 * @param {any[]} arr
 * @param {number} depth
 * @return {any[]}
 */
var flat = function (arr, n) {
    if(n===0) return arr;
    let list = [];
    arr.forEach(item => {
        if(typeof item === 'number') {
            list.push(item)
        } else if(item.length>0) {
            list = list.concat(flat(item, n-1))
        }
    })
    return list;
};
```
params
```
[1,2,3,[4,5,6],[7,8,[],12],[13,14,15]]
5
```
 result
```
[1,2,3,4,5,6,7,8,12,13,14,15]
```

#### Language used for code

JavaScript

**Comment by LC-Pam** [comment] 2023-05-12 21:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-15 00:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-15 00:56 UTC
Labels: LCUS, problem
