### ISSUE TITLE
Incorrect test case validation 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by prvacy** [LeetCode-Feedback/LeetCode-Feedback#18271] opened 2023-11-24 22:56 UTC
### LeetCode Username

prvacy

### Problem number, title, and link

[297. Serialize and Deserialize Binary Tree](https://leetcode.com/problems/serialize-and-deserialize-binary-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For the test-case(35/53) [1,2,3,null,null,4,5,6,7] generated tree should be like in the image below(image is generated using https://leetcode.com/problems/delete-node-in-a-bst/ test case section). My program should pass test validations, but it doesn't.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32227071/5eded259-38df-4487-add2-20c8c3525343)

### Code used for Submit/Run operation

```

using System.Text;
/**
* Definition for a binary tree node.
* public class TreeNode {
*     public int val;
*     public TreeNode left;
*     public TreeNode right;
*     public TreeNode(int x) { val = x; }
* }
*/
public class Codec
{

    // Encodes a tree to a single string.
    public string serialize(TreeNode root)
    {
        if (root is null)
        {
            return "[]";
        }

        var output = new StringBuilder();
        output.Append('[');

        var serializerStream = new Queue<TreeNode>();
        serializerStream.Enqueue(root);
        while (serializerStream.TryDequeue(out var node))
        {
            if (node is null)
            {
                //check if only nulls are in queque
                if(!serializerStream.ToArray().Any(n => n is not null))
                {
                    //change ',' to ']'
                    output[^1] = ']';
                    return output.ToString();
                }
            }
            output.Append(node?.val is null ? "null" : node.val.ToString());
            output.Append(',');
            serializerStream.Enqueue(node?.left);
            serializerStream.Enqueue(node?.right);
        }

        //change ',' to ']'
        output[^1] = ']';
        return output.ToString();
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(string data)
    {
        var stringNodes = data.Trim('[', ']').Split(',');
        if (string.IsNullOrEmpty(stringNodes.FirstOrDefault()))
        {
            return null;
        }

        var nodes = stringNodes
            .Select(stringNode => stringNode == "null" ? null : new TreeNode(int.Parse(stringNode))).ToArray();

        if (!nodes.Any())
        {
            return null;
        }

        var parents = new[] { nodes[0] };
        var countOnLevel = 1;
        for (int i = countOnLevel; i < nodes.Length; i+=countOnLevel)
        {
            countOnLevel *= 2;

            var childs = nodes[i..(Math.Min(i+countOnLevel, nodes.Length))];
            var idx = 0;
            foreach (var parent in parents)
            {
                if (parent is null)
                {
                    idx += 2;
                    continue;
                }
                parent.left = idx < childs.Length ? childs[idx++] : null;
                parent.right = idx < childs.Length ? childs[idx++] : null;
            }
            parents = childs;
        }


        return nodes[0];
    }
}

// Your Codec object will be instantiated and called as such:
// Codec ser = new Codec();
// Codec deser = new Codec();
// TreeNode ans = deser.deserialize(ser.serialize(root));
```

### Expected behavior

I tested my program the same as described in the example. The following code used to test the program: 
```
        var root = new TreeNode(1, new(2), new(3, new(4, new(6), new(7)), new(5)));
        Codec ser = new Codec();
        Codec deser = new Codec();

        Console.WriteLine(ser.serialize(root));
        TreeNode ans = deser.deserialize(ser.serialize(root));
        Console.WriteLine( ser.serialize(ans) ); 
```
If you compare root and ans - they are exactly the same. Also, it produces the following output:
[1,2,3,null,null,4,5,null,null,null,null,6,7]
[1,2,3,null,null,4,5,null,null,null,null,6,7]

**Comment by LC-Pam** [comment] 2023-11-28 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-01 21:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-01 21:39 UTC
Labels: Waiting for Reply
