### ISSUE TITLE
Missing Test Case - 450. Delete Node in a BST

### ISSUE THREAD

**Issue by Ujjawal-raghuvanshi** [LeetCode-Feedback/LeetCode-Feedback#13808] opened 2023-06-01 11:51 UTC
#### Your LeetCode username
ujjawal_raghuvanshi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug
The question asks us to remove the node with value "key" from the tree and remove the tree.
Even though the result generated by my code is a BST with the key removed , the testcase gives wrong answer.

#### Code you used for Submit/Run operation
'''
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    TreeNode* deleteNode(TreeNode* root, int key) {
        TreeNode * node = root , *temp = NULL;
        if(root==NULL)return NULL;
        while(node!=NULL&&node->val!=key){
            int val = node ->val;
            temp = node;
            if(val>key)node = node ->left;
            else node = node ->right;
        }
        if(node==NULL)return root;
        if(node->right==NULL&&node->left==NULL){
            if(temp==NULL)return NULL;
            if(temp->right == node) temp->right = NULL;
            else temp->left = NULL;
            return root;
        }
        if(node->right == NULL){
            if(temp==NULL)return node->left;
            if(temp->right == node) temp->right = node->left;
            else temp->left = node ->left;
            return root;
        }
        while(node -> right!=NULL){
            temp = node;
            swap(node->val , node->right->val);
            node = node->right;
        }
        temp->right = NULL;
        return root;
    }
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

I expected the code to give correct answer but instead it gave wrong answer on test case
root =
[50,30,70,null,40,60,80]
key = 50

#### Screenshots

<img width="500" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110528365/e01c9991-ce06-4812-ab80-1e711aae3f99">

#### Additional context

As we can see form output that my is a binary search tree.
There could be multiple ways to solve. Why only check one possibility?
e.g., 2,1,3 tree, delete 2, I can have 1,null,3, && 3,1
Both solutions are valid.
I think testcase needs to check the result is BST and doesn't have key to delete.

One simple solution scheme is just to substitute the target node with the left child's right most node. But it cannot pass the testcase  -> output =  [70,30,80,null,40,60]

**Comment by LC-Pam** [comment] 2023-06-01 20:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:40 UTC
Labels: LCUS, problem
