### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Shrini66** [LeetCode-Feedback/LeetCode-Feedback#10563] opened 2022-12-27 06:20 UTC
#### Your LeetCode username
shrini66

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
-

#### Description of the bug

if we try to run a testcase V it will not give correct output in fact no such test case is there.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

class Solution {
public:
    int romanToInt(string s) {
       int res=0;
       unordered_map<char,int> mp{
        {'I',1},
        {'V',5},
        {'X',10},
        {'L',50},
        {'C',100},
        {'D',500},
        {'M',1000},
    };

    for(int i=0;i<s.size();i++){
        if(mp[s[i]]<mp[s[i+1]])
            res-=mp[s[i]];
        else
            res+=mp[s[i]];
    }
    return res;
    }
};

#### Expected behavior

 In test case 'V' it will return 5

**Comment by LC-Pam** [comment] 2022-12-27 21:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2022-12-27 23:50
All 3999 possible test cases exist. Why do you think there is a test case missing?

**Comment by LC-Pam** [comment] 2022-12-28 20:46
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-28 20:46 UTC
Labels: LCUS, problem
