### ISSUE TITLE
Missing Test Case - 450. Delete Node in a BST

### ISSUE THREAD

**Issue by madhav3108** [LeetCode-Feedback/LeetCode-Feedback#15544] opened 2023-08-13 05:17 UTC
In the Leetcode 450 solution, no particular case is given for the leaf node and as we know as there are three cases in the binary search tree if we walk about deletion when a coder is written one by one code then it should be given in the test case.

Input
root =
[5,3,6,2,4,null,7]
key =
7
Output
[5,3,6,2,4]
Expected
[5,3,6,2,4]

introduce this test case in the main file..

**Comment by LC-Pam** [comment] 2023-08-14 20:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-18 19:43
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-18 19:43 UTC
Labels: Waiting for Reply
