### ISSUE TITLE
Missing Test Case - 516. Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by Rahul-Shukla0602** [LeetCode-Feedback/LeetCode-Feedback#15692] opened 2023-08-18 05:22 UTC
#### Category of the bug
- [1] Missing Test Cases 

#### Code you used for Submit/Run operation

```
 int t[1001][1001];
    int solve(string s,int i,int j){
        if(i>j){
            return t[i][j] = 0;
        }
        if(i == j){
            return t[i][j] = 1;
        }
        if(t[i][j]!=-1){
            return t[i][j];
        }
        int ans = 0;
        if(s[i]==s[j]){
            ans = 2 + solve(s,i+1,j-1);
        }
        else{
            ans = max(solve(s,i+1,j),solve(s,i,j-1));
        }

        return t[i][j] =  ans;
    }
    int longestPalindromeSubseq(string s) {
        int l = s.length()-1;
        memset(t,-1,sizeof(t));
        return solve(s,0,l);
    }
```

**Comment by LC-Pam** [comment] 2023-08-18 20:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-21 15:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-21 15:34 UTC
Labels: Waiting for Reply
