### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by palash8** [LeetCode-Feedback/LeetCode-Feedback#9016] opened 2022-09-12 11:08 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Reverse Integer
class Solution {
public:
    int reverse(int x) {
        int ans=0;
        while(x!=0)
        {   
            int digit=x%10;
             if((ans>INT_MAX/10)||(ans<INT_MIN/10))
            {
                return 0;
            }
         
            ans=ans*10+digit;
            x=x/10;
           
        }
            
        return ans;
        
    }
};
```

**Comment by LC-Pam** [comment] 2022-09-12 17:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-13 21:26
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understandi

**Closed by LC-Pam** 2022-09-13 21:26 UTC
Labels: LCUS, problem
