### ISSUE TITLE
Conflicting Testcases: Problem 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by zheltikov** [LeetCode-Feedback/LeetCode-Feedback#17979] opened 2023-11-10 18:30 UTC
### LeetCode Username
zheltikov

### Problem number, title, and link
[3. Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The testcases number 879 and 880 are conflicting.
They test that for a given input of an empty string ("") the result of the function must be 0 (for testcase 879) and 1 (for testcase 880).
These two testcases are conflicting and a solution cannot cover both of them.
Please remove the testcase 880. The correct answer should be 0 for an empty string.

### Language used for code
Go

### Code used for Submit/Run operation

```go
func lengthOfLongestSubstring(input string) int {
  runes := []rune(input)
  longest := 0

  for outerIdx, _ := range runes {
    seenChars := make(map[rune]bool)

    for innerIdx, innerRune := range runes[outerIdx:] {
      if _, seen := seenChars[innerRune]; seen {
        longest = max(longest, innerIdx)
        break
      } else {
        seenChars[innerRune] = true
      }
    }
  }

  return longest
}
```

### Expected behavior
The two testcases 879 and 880 are conflicting and a solution cannot cover both of them.
Please remove the testcase 880. The correct answer of the algorithm should be 0 for an empty string.

**Comment by LC-Pam** [comment] 2023-11-13 20:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:17 UTC
Labels: Waiting for Reply
