### ISSUE TITLE
Missing Test Case - 50. Pow(x, n) 

### ISSUE THREAD

**Issue by hardikpant03** [LeetCode-Feedback/LeetCode-Feedback#17910] opened 2023-11-07 17:33 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

**The test case 304 where the value of n is INT_MIN it gives the correct output but in the 305 test case there will be a bug there the value of n is same as the 304 test case but the answer is different in both the test case .**

**Comment by LC-Pam** [comment] 2023-11-13 21:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:08 UTC
Labels: Waiting for Reply
