### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by AbhishekRanjan624** [LeetCode-Feedback/LeetCode-Feedback#7596] opened 2022-06-03 18:16 UTC
### **Leetcode Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal**
**Java Solution**

class Solution {
    public boolean areAlmostEqual(String s1, String s2) {
        
         if(s1.equals(s2)){
             return true ;
         }
        
        for(int i=0 ; i<s2.length() ; i++){
            
            for(int j=i+1 ; j<s2.length() ; j++){
                char[] ch1=s1.toCharArray() ;
                
                ch1[i]=s1.charAt(j) ;
                ch1[j]=s1.charAt(i) ;
                
                if(String.valueOf(ch1).equals(s2)){
                    return true ;
                }
            }
        }
        
       return false ; 
    }
}

**Comment by AbhishekRanjan624** [comment] 2022-06-03 18:16
Leetcode Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

**Comment by LC-Pam** [comment] 2022-06-03 18:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 01:06
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 01:06 UTC
Labels: LCUS, problem
