### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Shiv-Softtech** [LeetCode-Feedback/LeetCode-Feedback#13340] opened 2023-05-07 14:02 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Roman to Integer

```

#### Language used for code

class Solution {
    public int romanToInt(String s) {
       int res = 0, num = 0;
        for (int i = s.length()-1; i >= 0; i--) {
            switch(s.charAt(i)) {
                case 'I': num = 1; break;
                case 'V': num = 5; break;
                case 'X': num = 10; break;
                case 'L': num = 50; break;
                case 'C': num = 100; break;
                case 'D': num = 500; break;
                case 'M': num = 1000; break;
            }
            if (4 * num < res) res -= num;
            else res += num;
        }
        return res;
    }
}

**Comment by LC-Pam** [comment] 2023-05-08 21:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:16 UTC
Labels: LCUS, problem
