### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by hwcpp** [LeetCode-Feedback/LeetCode-Feedback#8774] opened 2022-08-24 01:23 UTC
#include <algorithm>
class Solution {
    
public: 	double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
     double median = 0.0;
     int m1 = nums1.size();
     int n1 = nums2.size();
     bool leven = ((m1 + n1) % 2 == 0);

     int i0 = (m1 + n1 + 1) / 2;

     vector<int>* p = &nums1;
     vector<int>* q = &nums2;
     int m = m1;
     int n = n1;
    
    
     if ( m1 <= n1 )
     {

        p = &nums2;
        q = &nums1;
        m = n1;
        n = m1;
     };
    
     //       First consider if one is empty 
     if (n == 0)
     {
        median = median + (*p)[i0 - 1];
        if (leven)
        {
           median = median + (*p)[i0];
           median = median / 2;
        }
        return median;
     }

      //      All small array is in the left range
      if (((m == n) && (*q)[n - 1] <= (*p)[0]))
      {
         median = median + (*p)[0];
         median = median + (*q)[n - 1];
         median = median / 2;
         return median;
      }

      if (m>n && (*q)[n - 1] <= (*p)[i0 - n - 1])
      {

         median = median + max({ (*p)[i0 - n - 1], (*q)[n - 1] });
         if (leven)
         {
            median = median + (*p)[i0 - n];
            median = median / 2;
         }
         return median;
      }

		//      All small array is in the right range
		if ((*p)[i0 - 1] <= (*q)[0])
		{
			median = median + (*p)[i0 - 1];
			if (leven)
			{
				if (i0 + 1 <= m)
				{
					median = median + min({ (*p)[i0], (*q)[0] });
					median = median / 2;
				}
				else
				{
					median = median + (*q)[0];
					median = median / 2;
				}
			}
			return median;
		}

		int k1 = 0, k2 = n;
		int k0 = (n + 1) / 2;

		int l1 = 0, l2 = m;
		int l0 = i0 - k0;

		bool lone = (k0 == n);

		int left = (*q)[k0 - 1];
		int right = left;
		if (!lone)
		{
			right = (*q)[k0];
		}

		bool lb1 = (*p)[l0 - 1] <= right;
		bool lb2 = (*p)[l0] >= left;
		while (!lb1 || !lb2)
		{
			if (lb2)
			{
				//                partition (k0,k2)
				k1 = k0;
				k0 = (k1 + k2 + 1) / 2;
				lone = (k0 == k2);
				left = (*q)[k0 - 1];
				right = left;
				if (!lone)
				{
					right = (*q)[k0];
				}
			}
			else
			{
				//                    partition(k1, k0)
				k2 = k0;
				k0 = (k1 + k2) / 2;
				lone = (k0 == k2);
				left = (*q)[k0 - 1];
				right = left;
				if (!lone)
				{
					right = (*q)[k0];
				}
            }
            l0 = i0 - k0;
            lb1 = (*p)[l0 - 1] <= right;
            lb2 = (*p)[l0] >= left;
			
		}
		median = median + max({ (*p)[l0 - 1], left });
		if (leven)
		{
			if (lone)
			{
				median = median + (*p)[l0];
			}
			else
			{
				median = median + min({ (*p)[l0], right });
			}
			median = median / 2;
		}

		return median;
	}
};

**Comment by LC-Pam** [comment] 2022-08-24 15:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-25 18:08
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-25 18:08 UTC
Labels: LCUS, problem
