### ISSUE TITLE
Missing Test Case - 1389. Create Target Array in the Given Order

### ISSUE THREAD

**Issue by anshikasaxena1** [LeetCode-Feedback/LeetCode-Feedback#12727] opened 2023-04-03 01:47 UTC
#### Your LeetCode username

anshikasaxena310

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
The problem is in Question only.

#### Description of the bug

Actually from the question, number of condition that should be applied are not mentioned clearly even testcases are also not that good to understand.

#### Code you used for Submit/Run operation

//Create Target Array in the Given Order
class Solution {
    public int[] createTargetArray(int[] nums, int[] index) {
        ArrayList <Integer> arr=new ArrayList <Integer> ();
        int target[]=new int[nums.length];
        for(int i=0;i<nums.length;i++){
            arr.add(index[i],nums[i]);
        }
        for(int j=0;j<arr.size();j++){
            target[j]=arr.get(j);
        }
        return target;
    }
}

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

#### Expected behavior

after reading the question i understood the problem but example wasn't clear.

**Comment by LC-Pam** [comment] 2023-04-03 18:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The suggestion or example test case for how to make statements clear. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-05 17:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-05 17:51 UTC
Labels: LCUS, problem
