### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by chottuthejimmy** [LeetCode-Feedback/LeetCode-Feedback#13321] opened 2023-05-06 16:17 UTC
#### Your LeetCode username

chottuthejimmy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The official solution for 0ms runtime does not satisfy my test case.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int maxProfit(int[] prices) {
        if (prices.length > 100) {
            if (prices.length == 1000)
                return 9995;
            if (prices.length == 26004)
                return 3;
            if (prices.length == 100000 && prices[0] == 5507)
                return 9972;

            if (prices.length == 100000 && prices[0] != 933)
                return 0;
            if (prices.length > 31000)
                return 999;
        }
        int maxProfit=0;
        int min=prices[0];
        for (int price : prices) {
            min = Math.min(min, price);
            maxProfit = Math.max(maxProfit, price - min);
        }
        return maxProfit;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This solution did not pass my test case because this solution cleverly noted all the test cases where the array lengths are greater than 100 and directly returned the answer , as I am assuming that they went through these test cases previously and noted there characteristics like value of first element or the exact size of the array . Based on these characteristics they just wrote a special set of codes which satisfied these edge cases . So I also noted that size of the elements needs to be less than 10^4 , and also noted that all these edge cases had their elements below 1000(only for this testcase) . Now when I noticed one of the testcase I had a element of value 0 and it was visible it also had a number of elements with value 999(but not greater than that) so to the naked eye it was clearly visible that the answer would be 999 . But I this test case when I changed one of the element's value to say 4231 (Basically a 4-digit number , also the original number was 423 I just added 1 at last) the solution did not hold good anymore , it still returned 999 which was hard coded into the solution

#### Screenshots

![image](https://user-images.githubusercontent.com/108192034/236634989-cc8ec48a-8ea6-4c91-8a9e-1ad4bff8c90a.png)

#### Additional context

I think I have pretty much summed up in the above section itself , I may not have given you guys the exact edge test case or something but I have just informed you guys that why and how the current solution is invalid and I feel that we may need more cases with element's values to be in 4-digits( between 1000 and 10000) to make the accepted solution the better fool-proof one! . Thank you guys for your amazing work . Appreciate it !!

**Comment by LC-Pam** [comment] 2023-05-08 21:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:19 UTC
Labels: LCUS, problem

**Comment by chottuthejimmy** [comment] 2023-05-11 05:49
Sorry for not being able to reply sooner  . Here is the missing test case .
