### ISSUE TITLE
Missing Test Case - 989. Add to Array-Form of Integer

### ISSUE THREAD

**Issue by ErikMaung1** [LeetCode-Feedback/LeetCode-Feedback#11760] opened 2023-02-15 08:33 UTC
#### Your LeetCode username
Erik Maung

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Test Case submission

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution {
public:
    vector<int> addToArrayForm(vector<int>& num, int k) {
        vector<int>::iterator p = num.begin();
        int total = 0;
        while (p != num.end()) {
            total *= 10;
            total += *p;
            p = num.erase(p);
        }
        
        total += k;
        while (total != 0) {
            int lastDigit = total % 10;
            num.insert(p, lastDigit);
            total -=lastDigit;
            total /= 10;
        }
        return num;
    }
};
```

#### Language used for code
C++

#### Additional context
```
// Test Case: INPUT --
// num = [9, 9, 9];
// k = 1;
// Test Case: OUTPUT --
// [1, 0, 0, 0]
```

**Comment by LC-Pam** [comment] 2023-02-15 18:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-20 04:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-20 04:12 UTC
Labels: LCUS, problem
