### ISSUE TITLE
Giving wrong answer because of the order of the root.

### ISSUE THREAD

**Issue by SaeidAnwar** [LeetCode-Feedback/LeetCode-Feedback#12090] opened 2023-03-01 15:01 UTC
#### Category of the bug
- [ ] Question
- [ 1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Saying my answer is wrong, but my output is correct just order is different.

#### Code you used for Submit/Run operation

class Solution {
public:
    int idx;
    vector<TreeNode*> findDuplicateSubtrees(TreeNode* root) {
        vector<TreeNode*> ans;
        vector<vector<TreeNode*>> li;
        SubTrees(root, li);
        for(int i = 0; i < li.size(); i++)
        {
            bool matched = false;
            for(int j = i + 1; j < li.size(); j++)
            {
                for(int k = 0; k < li[i].size(); k++)
                {
                    if(li[i].size() != li[j].size())
                        break;
                    
                    if(li[i][k] == nullptr && li[j][k]!= nullptr)
                        break;
                    else if(li[i][k] != nullptr && li[j][k] == nullptr)
                        break;
                    else if(li[i][k] != nullptr && li[j][k]!= nullptr)
                    {
                        if(li[i][k]->val != li[j][k]->val)
                            break;
                    }
                    
                    if(!matched && k == li[i].size() - 1)
                    {
                        ans.push_back(li[i][0]);
                        swap(li[j], li.back());
                        li.pop_back();
                        matched = true;
                    }
                    else if(matched && k == li[i].size() - 1)
                    {
                        swap(li[j], li.back());
                        li.pop_back();
                    }
                }
            }
        }
        
        return ans;
    }
    
    void PreOrder(TreeNode* root, vector<TreeNode*>& arr)
    {
        if(root == nullptr)
        {
            arr.push_back(root);
            return;
        }
        
        arr.push_back(root);
        PreOrder(root->left, arr);
        PreOrder(root->right, arr);
        return;
    }
    
    void SubTrees(TreeNode* root, vector<vector<TreeNode*>>& li)
    {
        if(root == nullptr)
        {
            return;
        }
        
        vector<TreeNode*> arr;
        PreOrder(root, arr);
        li.push_back(arr);
        SubTrees(root->left, li);
        SubTrees(root->right, li);
        return;
    }
};

```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-03-01 19:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-03 19:43
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-03 19:43 UTC
Labels: LCUS, problem
