### ISSUE TITLE
Missing Test Case - 1402. Reducing Dishes

### ISSUE THREAD

**Issue by Ujjwal111111** [LeetCode-Feedback/LeetCode-Feedback#9480] opened 2022-10-14 16:01 UTC
#### Your LeetCode username

class Solution {
public:
    int solve(vector<int>&sat,int i,int time){
        if(i==sat.size()) return 0;
        int incl=(time+1)*sat[i] +solve(sat,i+1,time+1);
        int ex=solve(sat,i+1,time);
        return max(incl,ex);
        
        
    }
    
    
    int maxSatisfaction(vector<int>& sat) {
        sort(sat.begin(),sat.end());
        int n=sat.size();
       // return solve(sat,0,0);
        vector<int>curr(n+1,0),next(n+1,0);
        vector<vector<int>>dp(n+1,vector<int>(n+1,0));
        for(int ind=n-1;ind>=0;ind--){
            for(int time=ind;time>=0;time--){
                int incl=sat[ind]*(time+1)+dp[ind+1][time+1];
                int ex=dp[ind+1][time];
                dp[ind][time]=max(incl,ex);
            }
        }
        return dp[0][0];
        
    }
};

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-10-14 18:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submitted Accepted link and The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-17 15:24
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-17 15:24 UTC
Labels: LCUS, problem
