### ISSUE TITLE
c++ auto fill with pointer error

### ISSUE THREAD

**Issue by Beetman123** [LeetCode-Feedback/LeetCode-Feedback#7790] opened 2022-06-16 21:52 UTC
#### Your LeetCode username

jntparsons

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ x] Language
- [ ] Missing Test Cases 

#### Description of the bug

when using the autofill feature in c++, when trying to deal with pointers, 
1 it doesn't pop up when typing in a pointer "->"  (not the main problem >>>)
2
when using the auto fill feature for pointers by typing "ptr."
it will show the fill in like '->next', '->val'
but when you click on them the end result the output will now look like "ptr.->next"
the period is still there, which is really frustraing, because it pretty much cancels out the usefulness of the auto fill cause now I have to spend more time going back to the period and removing it. 

#### Code you used for Submit/Run operation

just create a Node * with next and val as atributes then try the autofill feature by typing a period afterward, you'll get it.

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(Node * ptr, int s) {
         ptr.  // just delete and retype '.' when Node is defined
         ptr-> // just delete and retype '->' when Node is defined, you won't get a pop up
    }
};
```

#### Expected behavior

already explained above

**Comment by LC-Pam** [comment] 2022-06-18 00:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name or problem page. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-19 20:12
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-19 20:12 UTC
Labels: LCUS, problem
