### ISSUE TITLE
Wrong Constraints - 1330. Reverse Subarray To Maximize Array Value

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#13406] opened 2023-05-11 14:40 UTC
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If `nums` is `[-100000, 100000, -100000, 100000, ...]`，the answer will overflow `int`, but in C++/Java, the return type is `int` instead of `long long` or `long`.

Please change the constraint `-10^5 <= nums[i] <= 10^5` to `-10^4 <= nums[i] <= 10^4`, or add "The test cases are generated such that the output values fit in a 32-bit integer".

Also, "The value of this array" is not defined when nums.length is 1, `1 <= nums.length` should be changed to `2 <= nums.length`.

**Comment by LC-Pam** [comment] 2023-05-12 21:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-15 00:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-15 00:56 UTC
Labels: LCUS, problem
