### ISSUE TITLE
Missing Test Case - 739. Daily Temperatures

### ISSUE THREAD

**Issue by rahulhbtu** [LeetCode-Feedback/LeetCode-Feedback#12507] opened 2023-03-22 06:31 UTC
https://leetcode.com/rahulverma112/
guys u can also see these test cases also
[11, 12, 9,8, 17, 1, 3]
ans= [1,3,2,1,0,1,0]
class Solution {
public:
    vector<int> dailyTemperatures(vector<int>& temperatures) {
        int n = temperatures.size();
        stack<int>s;
        vector<int>ans(n,0);
        for(int i{0};i<n; i++){
            while(!s.empty() && temperatures[s.top()]< temperatures[i] ){
                int j = s.top();
                s.pop();
                ans[j]  = i-j;
            }
            s.push(i);
        }
        return ans;

        
    }
};

**Comment by LC-Pam** [comment] 2023-03-22 20:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-24 19:43
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-24 19:43 UTC
Labels: LCUS, problem
