### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Rajkumar7633** [LeetCode-Feedback/LeetCode-Feedback#15997] opened 2023-08-28 17:16 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

class Solution {
    public void setZeroes(int[][] matrix) {
        boolean firstRowZero = false;
        boolean firstcolumnZero = false;

        for(int i =0;i<matrix.length;i++){
            if(matrix[i][0]==0){
                firstcolumnZero = true;
                break;
            }
        }
        for(int i =0;i<matrix[0].length;i++){
            if(matrix[0][i]==0){
                firstRowZero = true;
                break;
            }
        }
        for(int i=1;i<matrix.length;i++){
            for(int j =1;j<matrix[0].length;j++){
                if(matrix[i][j]==0){
                    matrix[i][0]=0;
                    matrix[0][j] = 0;
                }
            }
        }
        for(int i=1;i<matrix.length;i++){
            for(int j =1;j<matrix[0].length;j++){
                if(matrix[i][0]==0 || matrix[0][j]==0){
                    matrix[i][j]=0;
                }
            }
        }
        if(firstcolumnZero){
            for(int i=0;i<matrix.length;i++){
                matrix[i][0]=0;
            }
        }
        if(firstRowZero){
            for(int i =0;i<matrix[0].length;i++){
                matrix[0][i]=0;
            }
        }
    }
}

**Comment by Rajkumar7633** [comment] 2023-08-28 17:16
it is the best code and run tuke o(n)

**Comment by LC-Pam** [comment] 2023-08-29 19:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:54 UTC
Labels: Waiting for Reply
