### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Akshat3000** [LeetCode-Feedback/LeetCode-Feedback#12984] opened 2023-04-16 09:42 UTC
#### Your LeetCode username

Akshat3000

#### Category of the bug
- [ ] Question
- [x] Solution 
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I have written a code in C for the solution of the problem Roman to Integer conversion and the compiler prints wrong OUTPUT for my given INPUT, for the given test case "s = III" OUTPUT should be "3" BUT the compiler shows "58" 

#### Code you used for Submit/Run operation

#include<stdio.h>
#include<stdlib.h>
#include<string.h>

void
main ()
{
  int p;
  p = romanToInt ();
  printf ("%d", p);
}

int
romanToInt ()
{
  char s[20];
  scanf ("%s", s);
  int x, M = 1000, D = 500, C = 100, L = 50, X = 10, V = 5, I = 1, sum =
    0, countM = 0, countD = 0, countC = 0, countL = 0, countX = 0, countV =
    0, countI = 0;
  x = strlen (s);

  for (int i = 0; i < x; i++)
    {
      switch (s[i])
	{
	case 'M':
	  if (countM < 3)
	    {
	      sum += M;
	      countM++;
	    }
	  else
	    exit (0);
	  break;
	case 'D':
	  i++;
	  if (s[i] == 'M')
	    exit (0);
	  else
	    {
	      if (countD < 1)
		{
		  sum += D;
		  i--;
		  countD++;
		}
	      else
		exit (0);
	    }
	  break;
	case 'C':
	  i++;
	  if (s[i] == 'M' || s[i] == 'D')
	    {
	      sum -= C;
	      i--;
	    }
	  else
	    {
	      if (countC < 3)
		{
		  sum += C;
		  countC++;
		}
	      else
		exit (0);
	      i--;
	    }
	  break;
	case 'L':
	  i++;
	  if (s[i] == 'M' || s[i] == 'D' || s[i] == 'C')
	    exit (0);
	  else
	    {
	      if (countL < 1)
		{
		  sum += L;
		  i--;
		  countL++;
		}
	      else
		exit (0);
	    }
	  break;
	case 'X':
	  i++;
	  if (s[i] == 'L' || s[i] == 'C')
	    {
	      sum -= X;
	      i--;
	    }
	  else if (s[i] == 'M' || s[i] == 'D')
	    exit (0);
	  else
	    {
	      if (countX < 3)
		{
		  sum += X;
		  countX++;
		}
	      else
		exit (0);
	      i--;
	    }
	  break;
	case 'V':
	  i++;
	  if (s[i] == 'M' || s[i] == 'D' || s[i] == 'C' || s[i] == 'L'
	      || s[i] == 'X')
	    exit (0);
	  else
	    {
	      if (countV < 1)
		{
		  sum += V;
		  countV++;
		}
	      else
		exit (0);
	      i--;
	    }
	  break;
	case 'I':
	  i++;
	  if (s[i] == 'X' || s[i] == 'V')
	    {
	      sum -= I;
	      i--;
	    }
	  else if (s[i] == 'M' || s[i] == 'D' || s[i] == 'C' || s[i] == 'L')
	    exit (0);
	  else
	    {
	      if (countI < 3)
		{
		  sum += I;
		  countI++;
		}
	      else
		exit (0);
	      i--;
	    }
	  break;
	default:
	  break;
	}
    }

  return sum;
}

#### Language used for code

Language used : C

#### Expected behavior

Answer : Expected OUTPUT = '3' for the given INPUT "s = III"

#### Screenshots

``

#### Additional context

<img width="750" alt="A" src="https://user-images.githubusercontent.com/97675452/232290423-49daa5d9-4bc3-4efb-b02d-cb7b3949fc0f.png">
<img width="737" alt="B" src="https://user-images.githubusercontent.com/97675452/232290426-5859b311-f9f4-404f-86c2-6375e281ad35.png">
<img width="735" alt="C" src="https://user-images.githubusercontent.com/97675452/232290429-8c1590d9-ddcb-40da-a0e2-5a937d1188ca.png">
<img width="745" alt="D" src="https://user-images.githubusercontent.com/97675452/232290433-2ec3dacc-13d7-4ef5-8686-0cefe54ebecd.png">
<img width="723" alt="E" src="https://user-images.githubusercontent.com/97675452/232290434-3d6d39e2-d2b5-479c-a7c3-a8c61348d602.png">
<img width="746" alt="F" src="https://user-images.githubusercontent.com/97675452/232290435-362e6e3f-2dbe-44f9-9f63-cd9fa466a19f.png">
<img width="697" alt="G" src="https://user-images.githubusercontent.com/97675452/232290436-2ba57f2c-08d5-4a53-91a8-6742f54a340c.png">

**Comment by LC-Pam** [comment] 2023-04-18 22:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-21 18:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-21 18:16 UTC
Labels: LCUS, problem
