### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by pragati1317** [LeetCode-Feedback/LeetCode-Feedback#13889] opened 2023-06-04 15:46 UTC
#### Your LeetCode username

leetcode Username: pragati1317

Leetcode 209.  question ,  Minimum Size Subarray Sum
have issue in one of the Test Case 

Given an array of positive integers nums and a positive integer target, return the minimal length of a 
subarray
 whose sum is greater than or equal to target. If there is no such subarray, return 0 instead.

According to This Question Statement , we need to return a minimal length of array with sum>=target;

But one of test case Not following the problem statement 

// Test case
213
[12,28,83,4,25,26,25,2,25,25,25,12]

// Here it is Returning  
ans =8; 
and my ans=7 

 83+28+26+25+25+25+25=237
and count=7; Not 8 , 

please Correct this Test case No. 17 
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-06-06 19:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:31 UTC
Labels: LCUS, problem
