### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by Ansh3931up** [LeetCode-Feedback/LeetCode-Feedback#17611] opened 2023-10-29 06:48 UTC
#### Your LeetCode username

_ansh3931

#### Category of the bug
- [ "322 Coin Change"]  Question
- ["class Solution {
public:

    int solve(vector<int>& coins, int amount) {
        //base case
        if(amount == 0 ) {
            return 0;
        }

        if(amount < 0 )
            return INT_MAX;

        int mini = INT_MAX;
        
        for(int i=0; i<coins.size(); i++) {
            int coin = coins[i];

            //current coin ko sir tabhi use krenge 
            //jab uski value <= amount hogi 
            if(coin <= amount) {
                int recAns = solve(coins, amount - coin);
                if(recAns != INT_MAX){
                    int ans = 1 + recAns;
                    mini = min(mini, ans);
                }    
            }
            
        }
        return mini;
    }

    int coinChange(vector<int>& coins, int amount) {
       int ans = solve(coins, amount);

       if(ans == INT_MAX)
        return -1;
        else
        return ans;
        
    }
};" ] Solution
- [C++ ] Language
- [ coins=[3,6,8] , amount =20 ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-10-30 20:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 17:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:59 UTC
Labels: Waiting for Reply
