### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by rajarshi-github** [LeetCode-Feedback/LeetCode-Feedback#8219] opened 2022-07-16 06:24 UTC
#### Your LeetCode username
rajarshi777

#### Category of the bug
Missing Test Cases 

#### Code you used for Submit/Run operation
```
    grid = [
            [1,1,0,1,1],
            [1,0,0,0,0],
            [0,0,0,0,1],
            [1,1,0,1,1]
        ]
```

#### Language used for code

Python

#### Expected behavior

4

**Comment by LC-Pam** [comment] 2022-07-18 18:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-22 17:13
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-22 17:13 UTC
Labels: LCUS, problem
