### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by mokshsinghji** [LeetCode-Feedback/LeetCode-Feedback#8427] opened 2022-07-29 05:48 UTC
#### Your LeetCode username

user4913IU

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of theug

The testcases should include the other examples which are:
- [0, 1, 1]
- [0, 0, 0]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-07-29 18:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mokshsinghji** [comment] 2022-07-30 04:30
Hi, this is an issue for a missing test case and so I believe that I shouldn't have to share the code and the language I submitted. Let me know if I am wrong, thanks!

**Comment by LC-Pam** [comment] 2022-08-01 17:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result. We have to test it. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-03 16:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-03 16:45 UTC
Labels: LCUS, problem
