### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by Panja-Abhilash** [LeetCode-Feedback/LeetCode-Feedback#12373] opened 2023-03-15 13:30 UTC
class Solution {
	 public int[] searchRange(int[] a, int target) {
	    int []ans= {-1,-1} ;
	    ans[0]=Search( a,target,true);
	    ans[1]=Search( a,target,false);
	    return ans; }
	  public  int Search(int [] a,int target,boolean FirstOccurence){
		 int ans=-1;  
		 int low=0;
		   int high=a.length-1;
		   while(low<=high){
		   int mid=low+high-low/2;
		   if(target<a[mid]){
		   high=mid-1;}
		   else if(target>a[mid]){
		   low=mid+1;}
		   else{
			   ans=mid;
		   if(FirstOccurence) {
			   high=mid-1;
		   }
		   else{
			   low=mid+1;
		   }}}
		return ans;}

}

**Comment by nskybytskyi** [comment] 2023-03-18 19:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Your LeetCode username.
The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-20 17:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-20 17:41 UTC
