### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by pankajhumad** [LeetCode-Feedback/LeetCode-Feedback#20949] opened 2024-03-04 00:36 UTC
### LeetCode Username

phumad

### Problem number, title, and link

https://leetcode.com/problems/palindrome-linked-list/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

missing an invalid case [1,3,4,1]. I could simply compare the first and last node and return true/false. 

### Language used for code

Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution(object):
    def isPalindrome(self, head):
        """
        :type head: ListNode
        :rtype: bool
        """
        current = head
        tail = None
        while current:
            tail = current
            current = current.next
        current = head
        if current.val == tail.val:
            return True
        else:
            return False

### Expected behavior

The code above is obviously incorrect but passes the existing test cases.

**Comment by LC-Pam** [comment] 2024-03-05 20:19
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by pankajhumad** [comment] 2024-03-06 23:19
It's a non-issue. When I ran, it only ran two case, however when I tried to submit it runs more test and caught the issue.

Regards and thanking you for your response.

**Closed** 2024-03-19 21:49 UTC
Labels: Waiting for Reply
