### ISSUE TITLE
176. Second Highest Salary (Database)

### ISSUE THREAD

**Issue by blackaly** [LeetCode-Feedback/LeetCode-Feedback#11724] opened 2023-02-13 20:57 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
Hey, I solve a problem and there is a problem in the test cases, where he need the second highest value:

Testcase:
| id | salary |
| -- | ------ |
| 1  | 100    |
| 2  | 200    |

Ouput: 
| SecondHighestSalary |
| ------------------- |
| 200                 |

Expected:
| SecondHighestSalary |
| ------------------- |
| 100                 |

**Comment by blackaly** [comment] 2023-02-13 21:27
Sorry I got the answer, but actually I see that the problem isn't clear.

**Comment by kanisht09** [comment] 2023-02-13 22:47
hey @blackaly if you are clear with your doubt don't you think you should close this issue?
And the problem is pretty clear and also its very standard.

**Closed** 2023-02-14 13:56 UTC
