### ISSUE TITLE
Stated solution may lead to incorrect result

### ISSUE THREAD

**Issue by laichb** [LeetCode-Feedback/LeetCode-Feedback#10930] opened 2023-01-10 15:54 UTC
Stated solution on leetcode has a sentinel with a value of 0. This is an issue as the nodes are stated to have values between negative and positive 100, thus including 0. If this was done, and 0 was a single item in the original list, 0 would be removed erroneously. This means that the stated solution should utilize a sentinel with a value outside the stated range of values. This would also be good to draw attention in the final solution as it would promote edge case checking as the start of a consideration to a solution, which many seem to be missing.

**Comment by LC-Pam** [comment] 2023-01-10 21:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-13 17:50
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-13 17:50 UTC
Labels: LCUS, solution
