### ISSUE TITLE
494. Target Sum

### ISSUE THREAD

**Issue by harshkumarchourasia** [LeetCode-Feedback/LeetCode-Feedback#517] opened 2020-06-22 06:21 UTC
Brute Force method which is also the first solution provided by Leetcode is accepted for Java but not for python.
The Python code is
```
class Solution:
    def findTargetSumWays(self, nums: List[int], S: int) -> int:
        self.count = 0
        n = len(nums)
        def helper(i,sums):
            if i==n:
                if sums==S:
                    self.count+=1
                return
            else:
                helper(i+1, sums+nums[i])
                helper(i+1,sums-nums[i])
        helper(0,0)
        return self.count
```

**Comment by CooperCooperCooper** [comment] 2020-06-24 04:22
Hi @harshkumarchourasia ,
Thank you for reaching out to us. To help us reproduce the issue on our end, would you please share the following information with us?

1. Both Java and Python code on this issue, and label their languages;

2. A screenshot of the error message you encounter when the code doesn't work.

Thank you!

**Comment by lc-kate** [comment] 2020-07-07 01:03
Hi @harshkumarchourasia ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag @lc-christina  in a new comment. Thank you.

**Closed by lc-kate** 2020-07-07 01:03 UTC
Labels: LCUS, problem
