### ISSUE TITLE
Missing Test Case - 1923. Longest Common Subpath

### ISSUE THREAD

**Issue by theospears** [LeetCode-Feedback/LeetCode-Feedback#18573] opened 2023-12-10 02:39 UTC
### LeetCode Username
theospears

### Problem number, title, and link
(1923) Longest Common Subpath
https://leetcode.com/problems/longest-common-subpath/

### Category of the bug
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
The code below passes, but should fail the following test case

```
n = 4
paths = [[1,2,4,2,3], [1,2,3]]
```

Expected result: `2`

### Language used for code
Python

### Code used for Submit/Run operation

```
from typing import List

class Solution:
    def longestCommonSubpath(self, n: int, paths: List[List[int]]) -> int:
        transition_weights = {} # (i, j) -> maxlen
        
        first_path = paths[0]
        previous = None
        length = 1
        for i in range(len(first_path)):
            next = first_path[i]
            transition_weights[(previous, next)] = length
            transition_weights[(None, next)] = 1
            previous = next
            length += 1

        next_transition_weights = {}
        for p in range(1, len(paths)):
            print(transition_weights)
            next_transition_weights = {}
            path = paths[p]
            previous = None
            length = 2
            for i in range(len(path)):
                next = path[i]
                if (None, next) in transition_weights:
                    next_transition_weights[(None, next)] = 1
                if (previous is not None) and (previous, next) in transition_weights:
                    next_transition_weights[(previous, next)] = min(
                        max(
                            length,
                            next_transition_weights.get((previous, next), 0)
                        ),
                        transition_weights[(previous, next)]
                        )
                    length += 1
                else:
                    length = 2
                previous = next
            transition_weights = next_transition_weights

        print(transition_weights)
        return max(transition_weights.values(), default=0)
```

### Expected behavior
This fails, as it outputs `3` and the correct solution is `2`.

**Comment by LC-Pam** [comment] 2023-12-12 23:24
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

4
[[1,2,4,2,3], [1,2,3]]
shows invalid test case: 'paths' must consist of values from 0 to 3 only

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-14 22:26
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-14 22:26 UTC
Labels: Waiting for Reply

**Comment by theospears** [comment] 2024-01-22 02:43
I have updated the example in the issue to instead use an example if `n = 3`. All other details remain the same.
