### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by rugu0001** [LeetCode-Feedback/LeetCode-Feedback#13383] opened 2023-05-10 00:13 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

There is no test case that checks whether two numbers that are not directly next to each other add up to the correct target

#### Code you used for Submit/Run operation

```
// Two Sum
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function(nums, target) {
    for (let i = 0; i < nums.length; i++){
        for(let j = i+1; j < nums.length; j++){
             if(nums[i] + nums[j] == target){
            return [i, j]
             }
        }        
    }       
    return false
};
```

#### Language used for code

JS

**Comment by LC-Pam** [comment] 2023-05-10 22:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-12 21:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-12 21:34 UTC
Labels: LCUS, problem
