### ISSUE TITLE
Missing Test Case - 412. Fizz Buzz

### ISSUE THREAD

**Issue by PavanCheruvupally** [LeetCode-Feedback/LeetCode-Feedback#17579] opened 2023-10-28 06:08 UTC
#### Your LeetCode username

pavancheruvupally5

##  412 Fizz Buzz

- [x] Contributing Test Cases 
#### Input
n=90

#### Expected Output
["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz","16","17","Fizz","19","Buzz","Fizz","22","23","Fizz","Buzz","26","Fizz","28","29","FizzBuzz","31","32","Fizz","34","Buzz","Fizz","37","38","Fizz","Buzz","41","Fizz","43","44","FizzBuzz","46","47","Fizz","49","Buzz","Fizz","52","53","Fizz","Buzz","56","Fizz","58","59","FizzBuzz","61","62","Fizz","64","Buzz","Fizz","67","68","Fizz","Buzz","71","Fizz","73","74","FizzBuzz","76","77","Fizz","79","Buzz","Fizz","82","83","Fizz","Buzz","86","Fizz","88","89","FizzBuzz"]

**Comment by LC-Pam** [comment] 2023-10-30 19:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by PavanCheruvupally** [comment] 2023-10-31 16:56
Hey,

 I would like to contribute a test case for a question .
Hoping you are accepting contributions
 


Thank You.

**Comment by LC-Pam** [comment] 2023-11-02 18:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-13 17:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-13 17:25 UTC
Labels: Waiting for Reply
