### ISSUE TITLE
Missing Test Case - 112. Path Sum

### ISSUE THREAD

**Issue by NicholasHarlanHancock** [LeetCode-Feedback/LeetCode-Feedback#20630] opened 2024-02-23 08:00 UTC
### LeetCode Username

NicholasHancock

### Problem number, title, and link

Missing Test Case - 112. Path Sum
https://leetcode.com/problems/path-sum/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

This problem doesn't test for negative numbers, even though both val the TreeNode struct and the targetSum in the hasPathSum function.

### Language used for code
C (That's which language I was using for coding, though I think the test cases are the same in all languages.)

### Code used for Submit/Run operation

I suggest the following test case be added, though I don't think this is actually code.
```
Input: root = [3,4,1,null,-2,null,null], targetSum = 5
Output: true
Explanation: (3) + (4) + (-2) == 5.
```

### Illustration of tree in my suggested test case:
```
  3
 / \
4   1
 \
 -2
```

### Expected behavior

With the current test cases, I could (and almost did) write code that stopped counting a path once it's part sum got above targetSum, but that would miss some cases where negative numbers bring the sum down to targetSum after surpassing it, as in my new test case.
The behavior I expect is described in the "Code used for Submit/Run operation" section.

**Comment by LC-Pam** [comment] 2024-02-23 21:48
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-02-26 20:05 UTC
Labels: Waiting for Reply
