### ISSUE TITLE
Missing Test Case - 1172. Dinner Plate Stacks

### ISSUE THREAD

**Issue by BlakeChen-Pac** [LeetCode-Feedback/LeetCode-Feedback#13372] opened 2023-05-09 06:34 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√ ] Missing Test Cases 

#### Description of the bug

The testcases used for dinner plate stacks failed to check if all the stacks is popped using pop_at_stack method and then using a pop method to pop the empty stacks

#### Code you used for Submit/Run operation

```
struct DinnerPlates {
    stack_capacity: usize,
    stack: Vec<Vec<i32>>,
    unfilled_stack: Vec<usize>,
}

/**
 * `&self` means the method takes an immutable reference.
 * If you need a mutable reference, change it to `&mut self` instead. */

impl DinnerPlates {
    fn new(capacity: i32) -> Self {
        let capacity = capacity as usize;
        DinnerPlates {
            stack_capacity: capacity,
            stack: vec![Vec::with_capacity(capacity)],
            unfilled_stack: vec![0],  
        }
    }
    fn push(&mut self, val: i32) {
        if let Some(&i) = self.unfilled_stack.first() {
            self.stack[i].push(val);
            if self.stack[i].len() == self.stack_capacity {
                self.unfilled_stack.remove(0);
            }
        } else {
            self.stack.push(Vec::with_capacity(self.stack_capacity));
            self.stack.last_mut().unwrap().push(val);
            if self.stack.last().unwrap().len() < self.stack_capacity { self.unfilled_stack.push(self.stack.len() - 1); }
        }
    }
    fn pop(&mut self) -> i32 {
        if self.stack.len() == 0 { return -1; }
        while self.stack.last().unwrap().is_empty() {
            self.stack.pop();
            let length = self.stack.len();
            self.unfilled_stack.retain(|&x| x != length);
        }
        let res = self.stack.last_mut().unwrap().pop().unwrap();
        if self.stack.last().unwrap().is_empty() {
            self.stack.pop();
            self.unfilled_stack.pop();
        } else {
            let last_index = self.stack.len() - 1;
            if self.unfilled_stack.iter().all(|&x| x != last_index) {
                self.unfilled_stack.push(last_index);
                self.unfilled_stack.sort();
            }
        }
        res
    }
    fn pop_at_stack(&mut self, index: i32) -> i32 {
        let index = index as usize;
        let res;
        if index >= self.stack.len() || self.stack[index].len() == 0 {
            return -1;
        } else {
            res = self.stack[index].pop().unwrap();if self.unfilled_stack.iter().all(|&x| x != index) {
                self.unfilled_stack.push(index);
            }
            self.unfilled_stack.sort();
        }
        res
    }
}
```

#### Expected behavior

Well, if I popped all the stacks using pop_at_stack method and then using pop method, I should get a "-1"

**Comment by LC-Pam** [comment] 2023-05-09 19:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by BlakeChen-Pac** [comment] 2023-05-10 01:51
https://leetcode.cn/problems/dinner-plate-stacks/submissions/430896390/

**Comment by LC-Pam** [comment] 2023-05-12 21:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link in the LCUS website. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-15 00:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-15 00:55 UTC
Labels: LCUS, problem
