### ISSUE TITLE
Incorrect Test Case - 1091. Shortest Path in Binary Matrix

### ISSUE THREAD

**Issue by lthh91** [LeetCode-Feedback/LeetCode-Feedback#7330] opened 2022-05-16 08:17 UTC
#### Your LeetCode username

iamyuh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

The testcase result looks incorrect

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def shortestPathBinaryMatrix(self, grid: List[List[int]]) -> int:
        n = len(grid) - 1
        start = (0, 0)
        end = (n, n)
        neighs = {}
        dist = {}
        
        def get_val(loc):
            return grid[loc[0]][loc[1]]
        
        if get_val(start) != 0 or get_val(end) != 0:
            return -1
        
        def get_neighbors(loc):
            nonlocal neighs
            row, col = loc
            key = f"{row}_{col}"
            if key in neighs:
                return neighs[key]
            neighbors = []
            for row_inc in [-1, 0, 1]:
                if row+row_inc >= 0 and row+row_inc <= n:
                    for col_inc in [-1, 0, 1]:
                        if col+col_inc >= 0 and col+col_inc <= n and not (col_inc == 0 and row_inc == 0):
                            neighbors.append((row+row_inc, col+col_inc))
            neighs[key] = neighbors
            return neighbors
        
        def get_distance_to_end(loc, visited=[]):
            if get_val(loc) != 0:
                return -1
            if loc in visited:
                return -1
            row, col = loc
            key = f"{row}_{col}"
            print(key)
            nonlocal dist
            print(dist)
            if loc == end:
                dist[loc] = 1
                return 1
            neighbors = get_neighbors(loc)
            print(neighbors)
            if end in neighbors:
                dist[loc] = 2
                return 2
            visited.append(loc)
            dists = [get_distance_to_end(neigh, visited) for neigh in neighbors]
            dists = [d for d in dists if d != -1]
            if len(dists) == 0:
                dist[loc] = -1
                return -1
            min_dist = min(dists) + 1
            dist[loc] = min_dist
            return min_dist
        
        return get_distance_to_end(start)
```

#### Expected behavior

Test case [[0,1,1,0,0,0],[0,1,0,1,1,0],[0,1,1,0,1,0],[0,0,0,1,1,0],[1,1,1,1,1,0],[1,1,1,1,1,0]]
should have resulted 16, but the expected result is 14.

Manual test also shows that the result should be 16.

**Comment by LC-Pam** [comment] 2022-05-17 01:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Leader-board** [comment] 2022-05-18 12:06
Looks like Python.

**Comment by LC-Pam** [comment] 2022-05-20 02:16
we have not heard from you for a while, your code received runtime error when we test it. we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
Please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!

**Closed by LC-Pam** 2022-05-20 02:16 UTC
Labels: LCUS, problem
