### ISSUE TITLE
Missing Test Case - 1152. Analyze User Website Visit Pattern

### ISSUE THREAD

**Issue by rplotkin** [LeetCode-Feedback/LeetCode-Feedback#8120] opened 2022-07-11 01:36 UTC
#### Your LeetCode username

rplotkin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given this test case:

["zkiikgv","zkiikgv","zkiikgv","zkiikgv"]
[436363475,710406388,386655081,797150921]
["wnaaxbfhxp","mryxsjc","oz","wlarkzzqht"]

The answer should be ['oz', 'wnaaxbfhxp', 'mryxsjc'] but the solution engine thinks it should be ['oz', 'mryxsjc', 'wnaaxbfhxp'].
That cannot be the case; this is simple time-sorting and wnaaxbfhxp (436363475) precedes mryxsjc (710406388).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-07-11 22:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:39
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:39 UTC
Labels: LCUS, problem
