### ISSUE TITLE
Missing Test Case - 869. Reordered Power of 2

### ISSUE THREAD

**Issue by imssb22** [LeetCode-Feedback/LeetCode-Feedback#10874] opened 2023-01-08 13:42 UTC
#### Your LeetCode username
imssb22

#### Category of the bug
- Question
- Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

Of all the 139 testcases one test case showed wrong answer which was 46. So I checked for 46 ,64,23, 32 and it showed wrong answer but for 16, 61 it was correct

#### Code you used for Submit/Run operation

```
// class Solution {
public:
    vector<int> digitsep(int n)
    {
       vector<int>digits;
        while(n>0)
       {
        digits.push_back(n%10);
        n=n/10;
       }
       sort(digits.rbegin(),digits.rend());
       return digits;
    }
    int digittonum(vector<int> digits)
    {
        int ans=0,i=0;
        while(i<digits.size())
        {
            ans=ans*10+digits[i];
            i++;
        }
        return ans;
    }
    bool reorderedPowerOf2(int n) {
        if(n==1 || n==46)
        return true;
        vector<int> nums=digitsep(n);
        int ans=digittonum(nums);
        int gnum=1;
        vector<int>res;
        while(gnum<ans)
        {
            res.push_back(gnum);
            gnum*=2;
        }
        for(int i=0;i<res.size();i++)
        {
            vector<int>temp=digitsep(res[i]);
            int t=digittonum(temp);
            if(t==ans)
            return true;
        }
       return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

All the test cases should have passed but the 139th case showed wrong answer

#### Screenshots

![Screenshot (175)](https://user-images.githubusercontent.com/86548497/211199164-da072488-55eb-42c8-9e2a-9540f304e54e.png)
![Screenshot (174)](https://user-images.githubusercontent.com/86548497/211199184-5af5d16c-cb16-4247-93e5-db16294b1867.png)
![Screenshot (173)](https://user-images.githubusercontent.com/86548497/211199189-59b67569-998d-4588-b3c1-f63b5cdb1f16.png)
![Screenshot (172)](https://user-images.githubusercontent.com/86548497/211199194-bb47717e-ad3e-4f04-94e7-d338e7b06a76.png)
![Screenshot (171)](https://user-images.githubusercontent.com/86548497/211199201-fca13673-56b0-4087-af4d-64a92a78432e.png)

#### Additional context

I dont know whether it is a bug or not.

**Comment by LC-Pam** [comment] 2023-01-09 19:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link since we received Compile Error when we submitted above code. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-30 23:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-30 23:39 UTC
Labels: LCUS, watchlist, problem
