### ISSUE TITLE
Missing Test Case - 2042. Check if Numbers Are Ascending in a Sentence

### ISSUE THREAD

**Issue by kriiishh** [LeetCode-Feedback/LeetCode-Feedback#9583] opened 2022-10-22 17:45 UTC
class Solution {
public:
    bool areNumbersAscending(string str) {
         stringstream ss;
    int f=1;
    vector<int> v;
    vector<int> a;
 
    /* Storing the whole string into string stream */
    ss << str;
 
    /* Running loop till the end of the stream */
    string temp;
    int found;
    while (!ss.eof()) {
 
        /* extracting word by word from stream */
        ss >> temp;
 
        /* Checking the given word is integer or not */
        if (stringstream(temp) >> found)
            v.push_back(found);
    }
    int n= v.size();
   copy(v.begin(), v.end(), back_inserter(a)); 
    sort(a.begin(),a.end());
    for(int i=0;i<n&&i+1<n;i++)
    {
        if(v[i]!=a[i]||v[i]==v[i+1])
        {
            f=0;
            break;
        }
    }
        if(f==1)
        {
            return true;
        }
     return false;
        
    }
};

**Comment by LC-Pam** [comment] 2022-10-24 18:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 16:04
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 16:04 UTC
Labels: LCUS, problem
