### ISSUE TITLE
An issue with the test case and the question

### ISSUE THREAD

**Issue by sandyhandle** [LeetCode-Feedback/LeetCode-Feedback#12746] opened 2023-04-04 01:27 UTC
#### Your LeetCode username
Santhosh_Puvaneswaran

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The issue is that on the question it clearly says that there will be at least one customer every day. But when I gave custom test cases with interval in dates. It started giving me outputs. 

#### Code you used for Submit/Run operation

```
with cte as
(select visited_on, sum(amount) as total_amount
from customer group by visited_on),

cte2 as 
(select visited_on, sum(total_amount) over (order by visited_on Rows between 6 preceding and current row) as amount,
round(avg(total_amount) over (order by visited_on Rows between 6 preceding and current row),2) as average_amount
from cte
)

select * from cte2
where visited_on >= (select visited_on from cte2 order by visited_on limit 1) + 6
order by visited_on;
```

#### Language used for code
MySQL

#### Expected behavior
When ever some one gives an test case with a interval in date. it must say, that the test case in invalid.

#### Testcase 
```
| customer_id | name    | visited_on | amount |
| ----------- | ------- | ---------- | ------ |
| 1           | Jhon    | 2019-01-01 | 100    |
| 2           | Daniel  | 2019-01-02 | 110    |
| 3           | Jade    | 2019-01-03 | 120    |
| 4           | Khaled  | 2019-01-04 | 130    |
| 5           | Winston | 2019-01-05 | 110    |
| 6           | Elvis   | 2019-01-06 | 140    |
| 7           | Anna    | 2019-01-07 | 150    |
| 8           | Maria   | 2019-01-08 | 80     |
| 9           | Jaze    | 2019-01-09 | 110    |
| 1           | Jhon    | 2019-01-10 | 130    |
| 3           | Jade    | 2019-01-10 | 150    |
| 3           | Jade    | 2019-01-12 | 150    |
| 3           | Jade    | 2019-02-10 | 150    |
| 3           | Jade    | 2019-02-11 | 150    |
```
This particular test case failed but my code get summited successfully. (Code attached)

#### Result Expected
```
| visited_on | amount | average_amount |
| ---------- | ------ | -------------- |
| 2019-01-07 | 860    | 122.86         |
| 2019-01-08 | 840    | 120            |
| 2019-01-09 | 840    | 120            |
| 2019-01-10 | 1000   | 142.86         |
| 2019-01-12 | 910    | 130            |
| 2019-02-10 | 150    | 21.43          |
| 2019-02-11 | 300    | 42.86          |
```
Which is not correct by the terms of question.

**Comment by LC-Pam** [comment] 2023-04-04 21:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number or name
The test case is in JSON format. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by sandyhandle** [comment] 2023-04-05 02:26
The Name and Number of the problem is "Restaurant Growth - 1321".

`
[
  {
    "customer_id": 1,
    "name": "Jhon",
    "visited_on": "2019-01-01",
    "amount": 100
  },
  {
    "customer_id": 2,
    "name": "Daniel",
    "visited_on": "2019-01-02",
    "amount": 110
  },
  {
    "customer_id": 3,
    "name": "Jade",
    "visited_on": "2019-01-03",
    "amount": 120
  },
  {
    "customer_id": 4,
    "name": "Khaled",
    "visited_on": "2019-01-04",
    "amount": 130
  },
  {
    "customer_id": 5,
    "name": "Winston",
    "visited_on": "2019-01-05",
    "amount": 110
  },
  {
    "customer_id": 6,
    "name": "Elvis",
    "visited_on": "2019-01-06",
    "amount": 140
  },
  {
    "customer_id": 7,
    "name": "Anna",
    "visited_on": "2019-01-07",
    "amount": 150
  },
  {
    "customer_id": 8,
    "name": "Maria",
    "visited_on": "2019-01-08",
    "amount": 80
  },
  {
    "customer_id": 9,
    "name": "Jaze",
    "visited_on": "2019-01-09",
    "amount": 110
  },
  {
    "customer_id": 1,
    "name": "Jhon",
    "visited_on": "2019-01-10",
    "amount": 130
  },
  {
    "customer_id": 3,
    "name": "Jade",
    "visited_on": "2019-01-10",
    "amount": 150
  },
  {
    "customer_id": 3,
    "name": "Jade",
    "visited_on": "2019-01-12",
    "amount": 150
  },
  {
    "customer_id": 3,
    "name": "Jade",
    "visited_on": "2019-02-10",
    "amount": 150
  },
  {
    "customer_id": 3,
    "name": "Jade",
    "visited_on": "2019-02-11",
    "amount": 150
  }
]
`

I hope this helps..!

**Comment by LC-Pam** [comment] 2023-04-05 18:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The Json format test case as below:
{"headers":{"Customer":["customer_id","name","visited_on","amount"]},"rows":{"Customer":[[1,"Jhon","2019-01-01",100],[2,"Daniel","2019-01-02",110],[3,"Jade","2019-01-03",120],[4,"Khaled","2019-01-04",130],[5,"Winston","2019-01-05",110],[6,"Elvis","2019-01-06",140],[7,"Anna","2019-01-07",150],[8,"Maria","2019-01-08",80],[9,"Jaze","2019-01-09",110],[1,"Jhon","2019-01-10",130],[3,"Jade","2019-01-10",150]]}}

[ { "customer_id": 1, "name": "Jhon", "visited_on": "2019-01-01", "amount": 100 }, { "customer_id": 2, "name": "Daniel", "visited_on": "2019-01-02", "amount": 110 }, { "customer_id": 3, "name": "Jade", "visited_on": "2019-01-03", "amount": 120 }, { "customer_id": 4, "name": "Khaled", "visited_on": "2019-01-04", "amount": 130 }, { "customer_id": 5, "name": "Winston", "visited_on": "2019-01-05", "amount": 110 }, { "customer_id": 6, "name": "Elvis", "visited_on": "2019-01-06", "amount": 140 }, { "customer_id": 7, "name": "Anna", "visited_on": "2019-01-07", "amount": 150 }, { "customer_id": 8, "name": "Maria", "visited_on": "2019-01-08", "amount": 80 }, { "customer_id": 9, "name": "Jaze", "visited_on": "2019-01-09", "amount": 110 }, { "customer_id": 1, "name": "Jhon", "visited_on": "2019-01-10", "amount": 130 }, { "customer_id": 3, "name": "Jade", "visited_on": "2019-01-10", "amount": 150 }, { "customer_id": 3, "name": "Jade", "visited_on": "2019-01-12", "amount": 150 }, { "customer_id": 3, "name": "Jade", "visited_on": "2019-02-10", "amount": 150 }, { "customer_id": 3, "name": "Jade", "visited_on": "2019-02-11", "amount": 150 } ] received Invalid Testcase. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-07 18:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-07 18:04 UTC
Labels: LCUS, problem
