### ISSUE TITLE
Can't able to submit the question and don't know why

### ISSUE THREAD

**Issue by ScarcePulkit** [LeetCode-Feedback/LeetCode-Feedback#14453] opened 2023-06-30 15:47 UTC
#### Your LeetCode username

Admirerider

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
See the image attached.

#### Description of the bug

Don't know why is not able to submit the code.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++;

#### Expected behavior

Got accepted

#### Screenshots

<img width="1440" alt="Screenshot 2023-06-30 at 9 14 30 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/93707577/b4a41910-d515-4395-95e4-9b269ae1dbc4">

**Comment by LC-Pam** [comment] 2023-07-03 19:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More details/explanation about the issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:10 UTC
Labels: LCUS, problem
