### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by itsjustshubh** [LeetCode-Feedback/LeetCode-Feedback#13979] opened 2023-06-08 18:32 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// RomanToInt
class Solution {
    public int romanToInt(String s) {
        int sum = 0;
              for (int i = s.length() - 1; i >=0; i--) {
                  int value = valueConvert(s.charAt(i));
                  if (4 * value < sum) {
                      sum -= value;
                  } else {
                      sum += value;
                  }
              }

              return sum;
    }

    public int valueConvert(char c) {
        int value = 0;

        switch (c) {
            case 'I':
            value = 1;
            break;
            case 'V':
            value = 5;
            break;
            case 'X':
            value = 10;
            break;
            case 'L':
            value = 50;
            break;
            case 'C':
            value = 100;
            break;
            case 'D':
            value = 500;
            break;
            case 'M':
            value = 1000;
            break;
            default:
            System.err.println("Illegal Symbol used!");
            break;
        }

        return value;
    }
}
```

**Comment by LC-Pam** [comment] 2023-06-08 20:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:40 UTC
Labels: LCUS, problem
