### ISSUE TITLE
Missing test cases for Next Problems

### ISSUE THREAD

**Issue by Shubhamtribhuvan8** [LeetCode-Feedback/LeetCode-Feedback#11707] opened 2023-02-13 05:41 UTC
#### Your LeetCode username
Shubhamtribhuvan8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1 ] Missing Test Cases -Yes

#### Description of the bug

Yes, like if I click on the next button for a new problem, test cases are to be presented for the previous problem, so for testing time, I have to go back, and then I have to go on to this problem, so whatever test cases come after this
I've attached a screenshot of a previous problem with whatever test cases are displayed. 

#### Screenshots
![leetcode bugs](https://user-images.githubusercontent.com/106821254/218379513-3077831e-f019-4ac6-8f29-c3405a5f8471.png)

**Comment by LC-Pam** [comment] 2023-02-13 19:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-14 18:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-14 18:55 UTC
Labels: LCUS, problem

**Comment by Shubhamtribhuvan8** [comment] 2023-02-14 19:45
Done👍
