### ISSUE TITLE
Missing Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by Panja-Abhilash** [LeetCode-Feedback/LeetCode-Feedback#12365] opened 2023-03-15 01:10 UTC
class Solution {
    public char nextGreatestLetter(char[] a, char target) {
		int low=0,high=a.length-1;
		while(low<=high) {
			int mid=low+high-low/2;
			if(target<a[mid]) {
				high=mid-1;
			}
			else   {
				low=mid+1;
			}	
		}
		return a[low%a.length];
}}

**Comment by nskybytskyi** [comment] 2023-03-18 19:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-20 17:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-20 17:39 UTC
