### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by panda0000009** [LeetCode-Feedback/LeetCode-Feedback#16412] opened 2023-09-14 09:51 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by panda0000009** [comment] 2023-09-14 09:51
<--- Last few GCs --->
[19:0x56bb180]      721 ms: Scavenge 185.9 (191.8) -> 185.9 (191.8) MB, 0.1 / 0.0 ms  (average mu = 0.034, current mu = 0.001) allocation failure
[19:0x56bb180]      745 ms: Mark-sweep (reduce) 185.9 (191.8) -> 185.4 (190.3) MB, 24.6 / 0.0 ms  (average mu = 0.050, current mu = 0.066) last resort GC in old space requested
[19:0x56bb180]      770 ms: Mark-sweep (reduce) 185.4 (190.3) -> 185.4 (190.3) MB, 25.0 / 0.0 ms  (average mu = 0.026, current mu = 0.001) last resort GC in old space requested
<--- JS stacktrace --->
FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 0xb00e10 node::Abort() [nodejs run]
 2: 0xa1823b node::FatalError(char const*, char const*) [nodejs run]
 3: 0xcee09e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [nodejs run]
 4: 0xcee417 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [nodejs run]
 5: 0xea65d5  [nodejs run]
 6: 0xeb55b8  [nodejs run]
 7: 0xeb5a30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [nodejs run]
 8: 0xeb89ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [nodejs run]
 9: 0xe79b12 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [nodejs run]
10: 0xe7443c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [nodejs run]
11: 0xe74515 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [nodejs run]
12: 0x10221b2  [nodejs run]
13: 0x1022af6  [nodejs run]
14: 0x11e3783 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [nodejs run]
15: 0x15e7cf9  [nodejs run]

**Comment by panda0000009** [comment] 2023-09-14 09:51
/**
 * @param {number[]} nums
 * @return {number[]}
 */
 var sortArray = function(nums) {
  if (nums.length < 1) {
    return nums;
  } 
  let pivot = nums[0];
  let left = [];
  let right = [];
  let equal = [];
  
  for (let i = 0; i < nums.length; i++) {
    if (nums[i] < pivot) {
      left.push(nums[i]);
    } else if (nums[i] > pivot) {
      right.push(nums[i]);
    } else {
      equal.push(nums[i]);
    }
  }
  
  return sortArray(left).concat(equal, sortArray(right));
};

**Comment by LC-Pam** [comment] 2023-09-18 18:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-20 16:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-20 16:32 UTC
Labels: Waiting for Reply
