### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by Ar4hur7TI** [LeetCode-Feedback/LeetCode-Feedback#14704] opened 2023-07-12 05:19 UTC
#### Missing Test Cases 
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test case 85 / 93. String s has a different format of parentheses.

#### Code you used for Submit/Run operation
//Valid Parentheses
public boolean isValid(String s) {
        int parentheses = 0;
        int squareBrackets = 0;
        int curlyBrackets = 0;

        for (int i = 0; i < s.length(); ++i){
            char digit = s.charAt(i);
            if (digit == '(')
                ++parentheses;
            if (digit == ')' || digit == ')')
                --parentheses;
            if (digit == '[')
                ++squareBrackets;
            if (digit == ']')
                --squareBrackets;
            if (digit == '{')
                ++curlyBrackets;
            if (digit == '}')
                --curlyBrackets;
        }

        return parentheses == 0 && squareBrackets == 0 && curlyBrackets == 0;
    }

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-07-12 19:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-17 20:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-17 20:32 UTC
Labels: LCUS, problem
