### ISSUE TITLE
Editorial not opening - 681. Next Closest Time

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#18801] opened 2023-12-20 11:55 UTC
### LeetCode Username
pgmreddy

### Problem number, title, and link

https://leetcode.com/problems/next-closest-time/editorial/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Editorial tab is enabled, and clicking on it gives below error

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/ec280c56-6014-4b15-8ace-bbdcdb5dcb61)

**Comment by LC-Pam** [comment] 2023-12-21 22:09
Hi there,
 
Thank you for your time.
 
To help us better find the root cause of this issue, would you mind providing us below information:
 
Can you try a different browser, such as Chrome (make sure it's the Latest version and clear the history and cookies)?
Can you try in incognito/private browsing mode: https://www.computerworld.com/article/3356840/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html?
 
If the issue still exists when you try the above steps, please provide us screenshots of it. 
 
Thank you for your cooperation and help us to find the reason for this issue. 
 
Best Regards,
Support Team

**Comment by manoharreddyporeddy** [comment] 2023-12-22 03:47
Above was Chrome browser latest

===

Below is Edge browser latest
Same issue ( 1st time login to leetcode on this browser )

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/ba5818c7-ae46-42c1-8806-33ec45cd78fe)

**Comment by LC-Pam** [comment] 2024-01-23 21:19
Hi there,
 
We sincerely apologize for the delay in addressing your concern. We've experienced a high volume of tickets recently, but we are committed to resolving each one as quickly as possible.
 
Regarding the website issue you reported, our team has already implemented a fix. Could you please check and let us know if the problem persists on your end?

If the issue still exists, please send us a ticket to https://leetcode.com/support
 
Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:19 UTC
Labels: Waiting for Reply
