### ISSUE TITLE
Missing Test Case - 1845. Seat Reservation Manager

### ISSUE THREAD

**Issue by Neirokan** [LeetCode-Feedback/LeetCode-Feedback#17973] opened 2023-11-10 10:49 UTC
### LeetCode Username

NeiroNeko

### Problem number, title, and link

1845. Seat Reservation Manager https://leetcode.com/problems/seat-reservation-manager/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

It is possible to submit a solution with linked list of ranges.
Custom test case, which first reserves 66666 seats and then unreserves every second seat, exceeds the time limit.

### Language used for code

C++

### Code used for Submit/Run operation

```
#include <forward_list>

class SeatManager {
private:
    std::forward_list<std::pair<int, int>> ranges;
    static constexpr int first_seat = 1;
public:
    SeatManager(int n) {}
    
    int reserve() {
        auto first = ranges.begin();

        if (first == ranges.end() || first->first > first_seat + 1) {
            ranges.emplace_front(first_seat, first_seat);
            return first_seat;
        }

        if (first->first != first_seat) {
            first->first = first_seat;
            return first_seat;
        }

        auto second = first;
        second++;

        if (second == ranges.end() || first->second + 2 != second->first) {
            first->second++;
            return first->second;
        }

        int pos = first->second + 1;
        first->second = second->second;
        ranges.erase_after(first);
        return pos;
    }
    
    void unreserve(int seatNumber) {
        auto it = ranges.begin();
        auto prev = it;

        while (it->second < seatNumber) {
            prev = it;
            it++;
        }

        if (it->first == it->second) {
            if (prev == it) {
                ranges.pop_front();
            } else {
                ranges.erase_after(prev);
            }
        } else if (it->first == seatNumber) {
            it->first++;
        } else if (it->second == seatNumber) {
            it->second--;
        } else {
            ranges.emplace_after(it, seatNumber + 1, it->second);
            it->second = seatNumber - 1;
        }
    }
};
```

### Expected behavior

Result should be `Time Limit Exceeded` instead of `Accepted`.

**Comment by LC-Pam** [comment] 2023-11-13 20:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:12 UTC
Labels: Waiting for Reply
