### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Vishal-Merugu** [LeetCode-Feedback/LeetCode-Feedback#13572] opened 2023-05-20 03:35 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//  Find Pivot Index
class Solution:
    def pivotIndex(self, nums: List[int]) -> int: 
        
        mid = 0
        leftSum = 0
        rightSum = sum(nums) -  nums[0] 

        while True:
            if(leftSum == rightSum):
                return mid

            if mid >= len(nums) - 1:
                return -1 
            else :
                leftSum += nums[mid]
                rightSum -= nums[mid + 1]
                mid += 1
```

#### Screenshots

<img width="313" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118023401/86b8d64a-e3ab-4a01-ae7b-2fabbda282de">

**Comment by LC-Pam** [comment] 2023-05-23 00:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-26 19:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-26 19:46 UTC
Labels: LCUS, problem
