### ISSUE TITLE
Missing Test Case - 482. License Key Formatting

### ISSUE THREAD

**Issue by tushar-nanda** [LeetCode-Feedback/LeetCode-Feedback#16991] opened 2023-10-07 05:04 UTC
#### Your LeetCode username

tushar102nanda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

unexpected behaviour

#### Description of the bug

 
bugs in test case 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string licenseKeyFormatting(string s, int K) {
        string ans = "";
        if(s == "")
            return ans;
        int k = K;
        transform(s.begin() , s.end() ,s.begin() , ::toupper);
        reverse(s.begin() , s.end());
        for(int i = 0 ; i <s.length() ; i++)
        {
            if(s[i] == '-')
                continue;
            if(k>0)
            {
                ans.push_back(s[i]);
                k--;
                if(k == 0)
                {
                    ans.push_back('-');
                    k = K;
                }
            } 
        }
        if(ans == "")
            return ans;
        if(  ans.back() == '-')
        {
            ans.pop_back();
        }
        reverse(ans.begin() , ans.end());
        
        return ans;
    }
};
```

#### Expected behavior

i have written some code intially when i run it with sample test case it show wrong answer but when i submit the same code it actually passes all the test case

the test case that i have attached is making unexpected behaviour.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109102607/9f9234f3-dfad-426b-8732-8e9761b2614d)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109102607/41dce84c-398b-4bac-8505-57e3d51f0b53)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109102607/2c702a7f-a5d5-4bcd-bd7a-37e4112956b9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109102607/de2b6899-52cc-4176-9030-b54c8880963f)

**Comment by tushar-nanda** [comment] 2023-10-07 05:05
i hope you will correct the issue as soon as possible

**Comment by LC-Pam** [comment] 2023-10-09 18:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test cases.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:48 UTC
Labels: Waiting for Reply
