### ISSUE TITLE
Missing Test Case - 647. Palindromic Substrings

### ISSUE THREAD

**Issue by Ankursharma192001** [LeetCode-Feedback/LeetCode-Feedback#20251] opened 2024-02-10 15:27 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [*] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)

### Description of the bug

According to problem the n can be upto to 1000 , hence the code with time  complexity O(N^3) should not pass because of 1e9 operations , but it is still passing thus there might be missing test case for which sum of operations will be 1e9

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isPalindrome( string &str , int start , int end)
    {  

        while( start <= end)
        {
            if(str[start] != str[end]) return false;

            start += 1;
            end -= 1;
        }

        return true;
    }
    int countSubstrings(string s) {
        
        int ans = 0;

        for( int i = 0 ; i < s.length() ; i++)
        {
            for( int j = i ; j < s.length() ; j++)
            {
                ans += isPalindrome( s , i , j);
            }
        }

        return ans;
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Time Limit Exceeded but showing accepted
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100678940/dc42af79-b9f5-4592-8545-7890dae96c6c)

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100678940/a800a129-0f8b-4019-8a88-4ab68301742c)

**Comment by LC-Pam** [comment] 2024-02-14 00:12
Duplicate of #https://trello.com/c/oAUOOwMF/7584-647-palindromic-substrings

**Closed by LC-Pam** 2024-02-14 00:12 UTC
