### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by SaraFatma** [LeetCode-Feedback/LeetCode-Feedback#17545] opened 2023-10-27 09:33 UTC
#### Your LeetCode username
sarafatma

  
- [ ] Missing Test Cases 

#### Description of the bug
Some solutions will run for the arrays with zero in it .but what if thw zero is missing for example [1,2,3,4,5]
as  the size of the array is n=5 in this case it will run for many solutions  but the range provided of numbers is from [0 to n]

#### Code you used for Submit/Run operation

```
int missingNumber(vector<int>& nums) {
        int sum=0;
        int n=nums.size();
        
        for(int index=0;index<n;index++){
            sum=sum+nums[index];
        }
        int totalsum=((n)*(n+1))/2;
        int ans=totalsum-sum;
        return ans;
    }
```

**Comment by LC-Pam** [comment] 2023-10-27 19:19
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:00 UTC
Labels: Waiting for Reply
