### ISSUE TITLE
Contribute Test Case - 1572. Matrix Diagonal Sum

### ISSUE THREAD

**Issue by hahahafafa** [LeetCode-Feedback/LeetCode-Feedback#16404] opened 2023-09-14 00:20 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Here's a new test case to be added, it doesn't have an example of empty matrix case.
You can add:
Example 4:
Input:  ```mat=[[]]```
Output: ```0```

#### Language used for code
C++

**Comment by LC-Pam** [comment] 2023-09-14 01:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:07 UTC
Labels: Waiting for Reply
