### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by 7316Wang** [LeetCode-Feedback/LeetCode-Feedback#18797] opened 2023-12-20 08:29 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
int search(int* nums, int numsSize, int target) {
   int left=0;
   int right=numsSize-1;

   while(left<=right)
   {
           int middle=left+(right-left)/2;

if(nums[middle]<target)
{
left=middle+1;

}
else if(nums[middle]>target)
{
right=middle-1;
}
else{
    return middle;
}
   }

    return -1;
}
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment] 2023-12-21 22:08
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-25 19:34
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-25 19:34 UTC
Labels: Waiting for Reply
