### ISSUE TITLE
Minimum Window Subsequence

### ISSUE THREAD

**Issue by Azizimj** [LeetCode-Feedback/LeetCode-Feedback#8789] opened 2022-08-25 04:13 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 1 in the solution of 727. Minimum Window Subsequence does not even pass simple test cases.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python 3

**Comment by LC-Pam** [comment] 2022-08-25 18:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-27 01:14
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-27 01:14 UTC
Labels: LCUS, problem
