### ISSUE TITLE
wrong description

### ISSUE THREAD

**Issue by Yedla009** [LeetCode-Feedback/LeetCode-Feedback#18812] opened 2023-12-20 18:57 UTC
### LeetCode Username

Captain_Yedla

### Problem number, title, and link

https://leetcode.com/problems/online-stock-span/

### Category of the bug
- [*] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For example, if the prices of the stock in the last four days is [7,2,1,2] and the price of the stock today is 2, then the span of today is 4 because starting from today, the price of the stock was less than or equal 2 for 4 consecutive days.

it's wrong description. having 7, doesnot match the output explanation.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

there not be 7. any number <=2, satisfies the given description.

**Comment by LC-Pam** [comment] 2023-12-21 22:10
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code snippet and programming language you submitted that led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-25 19:35
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-25 19:35 UTC
Labels: Waiting for Reply
