### ISSUE TITLE
Missing Test Case - 172. Factorial Trailing Zeroes

### ISSUE THREAD

**Issue by rakeshssss** [LeetCode-Feedback/LeetCode-Feedback#17926] opened 2023-11-08 11:58 UTC
class Solution {
    public int trailingZeroes(int n) {
        int result = 0;
        if (n >= 5) result += n / 5;
        if (n >= 25) result += n / 25;
        if (n >= 125) result += n / 125;
        if (n >= 625) result += n / 625;
        if (n >= 3125) result += n / 3125;
        return result;
    }
}

**Comment by LC-Pam** [comment] 2023-11-13 21:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:08 UTC
Labels: Waiting for Reply
