### ISSUE TITLE
Bug in test cases

### ISSUE THREAD

**Issue by arpit456jain** [LeetCode-Feedback/LeetCode-Feedback#8900] opened 2022-09-03 14:51 UTC
I am giving the contest biweekly-contest-86/  and in 2nd question ([Strictly Palindromic Number](https://leetcode.com/contest/biweekly-contest-86/problems/strictly-palindromic-number)) i was very confused how to solve so i just write 

return false;

and it got accepted 

Is there no test case for which the ans is true ?

please check

**Comment by LC-Pam** [comment] 2022-09-06 17:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-12 02:35
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-12 02:35 UTC
Labels: LCUS, problem
