### ISSUE TITLE
Missing Test Case - 3047. Find the Largest Area of Square Inside Two Rectangles

### ISSUE THREAD

**Issue by shadan1234** [LeetCode-Feedback/LeetCode-Feedback#20697] opened 2024-02-25 10:42 UTC
LeetCode username- shadan12

[3047. Find the Largest Area of Square Inside Two Rectangles](https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles/)

### Category of the bug
Leetcode Internal Error -> Leads to TLE

### Description of the bug
When I submit my solution with a print statement it generates TLE ( Time Limit Exceeded) but when i submit my solution without print statement it gets accepted.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    long long largestSquareArea(vector<vector<int>>& bottomLeft, vector<vector<int>>& topRight) {
        int n=bottomLeft.size();
        long long int ans=0;
        for(int i=0;i<n;i++){
            for(int j=i+1;j<n;j++){
                int xb=max(bottomLeft[i][0],bottomLeft[j][0]);
                 int yb=max(bottomLeft[i][1],bottomLeft[j][1]);
                 int xu=min(topRight[i][0],topRight[j][0]);
                 int yu=min(topRight[i][1],topRight[j][1]);
                 cout<<xu <<" "<<xb<<" "<<yu<<" "<<yb<<endl;
                if(xu>xb && yu>yb){
                   
                   long long  int s=min(xu-xb,yu-yb);
                    ans=max(ans,s*s);
                }
                
            }
        }
        return ans;
    }
};
```

### Expected behavior
Solution Should be accepted irrespective of the print statement , but it leads to  Time limit exceeded. 

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122110545/9f8fe4d8-0a7c-4e8d-9d92-3b2c75276cff)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122110545/65b0cca5-7a1b-44d5-acc0-3d67f4dc9197)

### Additional context
The Solution should not depend on the print statement , as in other problems also i have used print statements for debugging but those problems didn't generate TLE , but this problem does.

**Comment by LC-Pam** [comment] 2024-02-26 16:21
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by shadan1234** [comment] 2024-02-26 17:57
@LC-Pam , the link which led to accepted submission is 
https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles/submissions/1185685661/

**Comment by LC-Pam** [comment] 2024-03-05 19:58
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We cannot add this test case due to technical issue. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Closed by LC-Pam** 2024-03-05 19:58 UTC
Labels: Waiting for Reply
