### ISSUE TITLE
Missing Test Case - 182. Duplicate Emails (My sql)

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#15231] opened 2023-08-02 18:30 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

SELECT DISTINCT P1.Email FROM PERSON P1,PERSON P2
WHERE P1.id<>P2.id AND P1.Email=P2.Email
```
// 
```

**Comment by LC-Pam** [comment] 2023-08-04 19:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link. The missing test case.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-08 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-08 19:41 UTC
Labels: LCUS, problem, Waiting for Reply
