### ISSUE TITLE
Extra character inside the brute force code in the solution page on line 11. -  611 Valid Triangle Number

### ISSUE THREAD

**Issue by giriteja94495** [LeetCode-Feedback/LeetCode-Feedback#4185] opened 2021-07-15 11:07 UTC
#### Your LeetCode username

lucy94495

#### Category of the bug
- Solution

#### Description of the bug

There is an extra character in the brute force solution written in the article on line number 11.

#### Language used for code

Java

#### Screenshots

<img width="864" alt="Screenshot 2021-07-15 at 4 30 31 PM" src="https://user-images.githubusercontent.com/51397347/125778298-a01ca149-ade0-4a76-bf6a-f256251551f2.png">

**Comment by lc-kay** [comment] 2021-07-15 23:46
Duplicate of #4180. Thank you for your time.

**Closed by lc-kay** 2021-07-15 23:46 UTC
