### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by msms118** [LeetCode-Feedback/LeetCode-Feedback#12515] opened 2023-03-22 11:37 UTC
#### Your LeetCode username

- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public void moveZeroes(int[] nums) {
        int slowIndex = 0;
        int temp = 0;
        for(int fastIndex = 0; fastIndex< nums.length-1;fastIndex++){
            if(nums[fastIndex]!=0){
                nums[slowIndex++]=nums[fastIndex];
                nums[fastIndex]=0;
            }else{
                if(nums[slowIndex]!=0){
                nums[++slowIndex]=nums[fastIndex+1];
                nums[fastIndex+1]=0;
                }else{
                    nums[slowIndex]=nums[fastIndex+1];
                    nums[fastIndex+1]=0;
                }
            }
        }
    }
};
```

**Comment by LC-Pam** [comment] 2023-03-22 20:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-24 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-24 19:45 UTC
Labels: LCUS, problem
