### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by ABHINAYREDDYDODLA** [LeetCode-Feedback/LeetCode-Feedback#10695] opened 2023-01-02 11:43 UTC
#### Your LeetCode username

abhinayreddyd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

The code which is written passes all the test cases given previously but is missing a prominent testcase which helps in increasing the accuracy of the code.

#### Code you used for Submit/Run operation

```
// Basic Calculator II
class Solution {
    public int calculate(String s) {
        int len = s.length();
        Stack<Integer> stack = new Stack<>();
        char sign = '+';
        int num = 0;
        for(int i = 0; i < len; i++){
            char c = s.charAt(i);
            if(Character.isDigit(c))
                num = num * 10 + c - '0';
            if((!Character.isDigit(c) && c != ' ') || i == len - 1){
                if(sign == '+')
                    stack.push(num);
                else if(sign == '-')
                    stack.push(-num);
                else if(sign == '*')
                    stack.push(num * stack.pop());
                else if(sign == '/')
                    stack.push(stack.pop() / num);
                sign = c;
                num = 0;
            }
        }
        int res = 0;
        for(Integer i : stack)
            res += i;
        return res;
    }
}
```

#### Language used for code

java

#### Expected behavior

I thought the code would pass all the test cases but is missing is missing a prominent testcase which is required for the code to be accurate and run successfully.

**Comment by ABHINAYREDDYDODLA** [comment] 2023-01-02 11:43
good program but missing some test cases

**Comment by stormsunshine** [comment] 2023-01-02 12:00
What is the missing test case?

**Comment by LC-Pam** [comment] 2023-01-02 20:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-04 18:58
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-04 18:58 UTC
Labels: LCUS, problem
