### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by MaxVettel** [LeetCode-Feedback/LeetCode-Feedback#11301] opened 2023-01-27 08:26 UTC
#### Your LeetCode username

Frances1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This testcase check that algorithm can see bijection between strings

#### Code you used for Submit/Run operation

```
input: "bacd"
output: "baba"
```

#### Language used for code

Java

**Comment by LC-Pam** [comment] 2023-01-27 19:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code  you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-30 19:44
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-30 19:44 UTC
Labels: LCUS, problem
