### ISSUE TITLE
Missing Test Case - 1486. XOR Operation in an Array

### ISSUE THREAD

**Issue by Praneeth-10** [LeetCode-Feedback/LeetCode-Feedback#11590] opened 2023-02-08 00:28 UTC
#### Your LeetCode username

SPraneeth10

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Contributing a test case.
Just contributing a test case to understand better with bigger integers and for better understanding.

#### Code you used for Submit/Run operation

```
// XOR Operation in an Array
Input: n = 9, start = 15
Output: 15
Explanation: Array nums is equal to [15, 17, 19, 21, 23, 25, 27, 29, 31] where (15 ^ 17 ^ 19 ^ 21 ^ 23 ^ 25 ^ 27 ^ 29 ^ 31) = 15.
Where "^" corresponds to bitwise XOR operator.
(15 ^ 17= 30 ^ 19= 13 ^ 21= 24 ^ 23= 15 ^ 25= 22 ^ 27= 13 ^ 29= 16 ^ 31= 15) which gives as 15.
```

#### Additional context

Just contributing a test case to understand better with bigger integers and for better understanding.

**Comment by LC-Pam** [comment] 2023-02-08 18:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-10 19:01
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-10 19:01 UTC
Labels: LCUS, problem
