### ISSUE TITLE
Missing Test Case - 2185. Counting Words With a Given Prefix

### ISSUE THREAD

**Issue by ShailyJain66** [LeetCode-Feedback/LeetCode-Feedback#14786] opened 2023-07-15 13:22 UTC
#### Your LeetCode username
shailyjain66

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int prefixCount(vector<string>& words, string pref) {
        int ans=0;
        for(int i=0;i<words.size();i++){
            int b=0;
            for(int j=0;j<pref.size();j++){
                if(j>=words[i].size()||words[i][j]!=pref[j]){
                    break;
                }
                else{
                    b++;
                }
  
            }
            if(b==pref.size()){
                ans++;
            }
        }
        return ans;
        
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment] 2023-07-17 20:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:08 UTC
Labels: LCUS, problem, Waiting for Reply
