### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by hittingnote** [LeetCode-Feedback/LeetCode-Feedback#19109] opened 2024-01-04 12:17 UTC
### LeetCode Username

ssmm

### Problem number, title, and link

11. Container With Most Water

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Code used for Submit/Run operation

```bash
// Paste your code here. Don't remove ``` given
// above and below the code.
# The test case is generated through the following bash script
#!/bin/bash

for i in {1..100000}; do
	if [ $i -le 10000 ]; then
		echo -n "$i,"
	else
		echo -n "10000,"
	fi
done

echo ""
```

### Expected behavior

Time exceeded for my submitted code when evaluating the above test case, but the current test cases do not include that. So, my inefficient code passes.

My Code:
```
#define MAXSIZE                 100005
#define SET_TO_ZERO(var)        memset(var, 0, sizeof(var))

int maxArea(int* height, int heightSize) {
    int first_higher_idx_from_left[MAXSIZE];
    int first_higher_idx_from_right[MAXSIZE];
    int farthest_higher_idx_left[MAXSIZE];
    int farthest_higher_idx_right[MAXSIZE];

    int max_result = 0;
    int i, j;

    SET_TO_ZERO(first_higher_idx_from_left);
    SET_TO_ZERO(first_higher_idx_from_right);
    SET_TO_ZERO(farthest_higher_idx_left);
    SET_TO_ZERO(farthest_higher_idx_right);

    for(i = 0; i < heightSize; i++) {
        int idx = i-1;

        if(i == 0) {
            first_higher_idx_from_left[i] = -1;
            continue;
        }

        while(idx >= 0 && height[i] > height[idx]) {
            idx = first_higher_idx_from_left[idx];
        }

        first_higher_idx_from_left[i] = idx;
    }

    for(i = heightSize-1; i >= 0; i--) {
        int idx = i+1;

        if(i == heightSize-1) {
            first_higher_idx_from_right[i] = heightSize;
            continue;
        }

        while(idx < heightSize && height[i] > height[idx]) {
            idx = first_higher_idx_from_right[idx];
        }

        first_higher_idx_from_right[i] = idx;
    }

    for(i = 0; i < heightSize; i++) {
        int idx = 0;
        int cur_res;

        farthest_higher_idx_left[i] = i;

        while(idx < i && height[idx] < height[i]) {
            idx = first_higher_idx_from_right[idx];
        }

        if(idx < i)
            farthest_higher_idx_left[i] = idx;
        
        cur_res = height[i] * (i - farthest_higher_idx_left[i]);
        if(cur_res > max_result)
            max_result = cur_res;
    }

    for(i = heightSize-1; i >= 0; i--) {
        int idx = heightSize - 1;
        int cur_res;

        farthest_higher_idx_right[i] = i;

        while(idx > i && height[idx] < height[i]) {
            idx = first_higher_idx_from_left[idx];
        }

        if(idx > i)
            farthest_higher_idx_right[i] = idx;

        cur_res = height[i] * (farthest_higher_idx_right[i] - i);
        if(cur_res > max_result)
            max_result = cur_res;
    }

    return max_result;
}
```

**Comment by LC-Pam** [comment] 2024-01-04 21:53
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-09 19:22
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-09 19:22 UTC
Labels: Waiting for Reply

**Comment by hittingnote** [comment] 2024-01-27 17:49
Dear LeetCode Support Team,

       First, apologize for replying to the last email too late. I'm
writing to provide the code submission link and details of the missing test
case.

code submission link:
https://leetcode.cn/problems/container-with-most-water/submissions/493251322
(in this submission, the code takes 700ms to finish the test cases, but it
will exceed the time limit when running my test case)

Details of the test case: It is a non-decreasing array, and my submission
code will exceed the time limit when the array is non-decreasing.
The test case I provided is just an example of a non-decreasing array. For
each i from 0 to 9999, a[i] = i + 1, and for i >= 10000, a[i] = 10000.

Best regards
LeetCoder of 11. Container With Most Water (Issue #19109)

LC_M ***@***.***> 于2024年1月5日周五 05:53写道：
