### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by nube-dev** [LeetCode-Feedback/LeetCode-Feedback#16278] opened 2023-09-08 15:58 UTC
#### Your LeetCode username
nube-dev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
example  miss match

#### Description of the bug

Example 1 shows a sample shuffling of the string based on the indices. Here it shows that after indices 0 indices 2 will come but in the output after indices 0 indices 1 are concatenated 

#### Code you used for Submit/Run operation

```class Solution:
    def restoreString(self, s: str, indices: List[int]) -> str:
        t=""
        for i in indices:
            t=t+s[i]
        return t
        ```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

python3

#### Expected behavior

codeleet should be returned based on indices values and the expected answer should be leetcdoe, because indices = [4,5,6,7,0,2,1,3] and s = "codeleet" , here after 0 is 2 so according to s 0th index is c and 2nd index is d so the answer should be cd not co as index of o is 1

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49407558/a7f061c4-62fb-4848-8fb4-f56bbe40c31e)

**Comment by LC-Pam** [comment] 2023-09-11 20:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:10 UTC
Labels: Waiting for Reply
