### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by rishu-bhardwajjjj** [LeetCode-Feedback/LeetCode-Feedback#16662] opened 2023-09-24 13:54 UTC
Code get compiled with correct output in other compilers but not on leetcode
problem: [88. Merge Sorted **Array](https://leetcode.com/problems/merge-sorted-array/)**

here is the code 

**
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int i=0;
        int j=0;
        int k=0;
        int nums3[]= new int [m+n];
        while(i<m&&j<n){
             if((nums1[i]==0)){
                i++;--m;continue;}
               else if(nums2[j]==0){
                j++;--n;continue;}
            else if(nums1[i]<nums2[j])
            nums3[k++]=nums1[i++];
            else
            nums3[k++]=nums2[j++];
        }
        while(i<m)
            nums3[k++]=nums1[i++];
        while(j<n) 
            nums3[k++]=nums2[j++];   
        
       for(int p=0;p<m+n;p++){
           System.out.print(nums3[p]+" ");
       } 
    }}**

**Comment by LC-Pam** [comment] 2023-09-25 21:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-28 15:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-28 15:58 UTC
Labels: Waiting for Reply
