### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by 2100031483** [LeetCode-Feedback/LeetCode-Feedback#16575] opened 2023-09-21 04:45 UTC
#### Your LeetCode username
<2100031483>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ . ] Missing Test Cases 

#### Description of the bug
<missing test cases for negative numbers>

#### Code you used for Submit/Run operation

```
// Two Sum
'''class Solution {
    public boolean isPowerOfTwo(int n) {
        if(n == 0) return false;
        n = Math.abs(n);
        if((n&(n-1))== 0) return true;
        return false;
    }
}'''
```

#### Language used for code
<JAVA>

**Comment by LC-Pam** [comment] 2023-09-21 19:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-25 20:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-25 20:47 UTC
Labels: Waiting for Reply
