### ISSUE TITLE
Missing Test Case - 2180. Count Integers With Even Digit Sum

### ISSUE THREAD

**Issue by rohitmondal03** [LeetCode-Feedback/LeetCode-Feedback#8850] opened 2022-08-30 03:54 UTC
#### Category of the bug
- [x] Question
- [x] Missing Test Cases 
- [x] Solution

- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int countEven(int num) {
        
        int count = 0;
        
        for(int i=1; i<=num; i++){
            
            if(func(i)){
                count++;
            }
        }
        return count;
    }
        
    private static boolean func(int n){
            
        int sum = 0;
            
        while(n > 0){
            sum += n%10;
            n/=10;
        }
            
        if(sum%2 == 0){
            return true;
        }
            
        return false;
    }
}
```

#### Screenshots

![Screenshot (36)](https://user-images.githubusercontent.com/107113353/187345584-20215c45-987c-4941-b51e-47b1d7b99aca.png)

**Comment by LC-Pam** [comment] 2022-08-30 17:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-31 20:30
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-31 20:30 UTC
Labels: LCUS, problem
