### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by Anixton** [LeetCode-Feedback/LeetCode-Feedback#16842] opened 2023-10-01 14:33 UTC
#### Your LeetCode username

HakanGezginci

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem can be solved by concatenating the strings, but there should be a test case where concatenation doesn't yield the desired result.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        string first;
        string second;
        for(int i=0;i<word1.size();i++)
        {
            string str=word1[i];
            first+=str;
        }
        for(int j=0;j<word2.size();j++)
        {
            string str=word2[j];
            second+=str;
        }
        if(first==second)
        {
            return true;
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should have triggered a "memory exceeded" error instead of accepting the solution.

**Comment by LC-Pam** [comment] 2023-10-03 18:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link since we received compile error: https://leetcode.com/submissions/detail/1066165604/
The suggested test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:22 UTC
Labels: Waiting for Reply

**Comment by Anixton** [comment] 2023-10-06 05:54
class Solution {
public:
    bool arrayStringsAreEqual(vector<string>& word1, vector<string>& word2) {
        string first;
        string second;
        for(int i=0;i<word1.size();i++)
        {
            string str=word1[i];
            first+=str;
        }
        for(int j=0;j<word2.size();j++)
        {
            string str=word2[j];
            second+=str;
        }
        if(first==second)
        {
            return true;
        }
        return false;
    }
};
![Ekran görüntüsü 2023-10-06 085336](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121567782/53cfdf2b-2685-42c4-a2c6-ae672d46d753)
