### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by nwt-q** [LeetCode-Feedback/LeetCode-Feedback#18417] opened 2023-12-02 02:27 UTC
### Problem number, title, and link
https://leetcode.cn/problems/two-sum/

### Language used for code

```
int* twoSum(int* nums, int numsSize, int target, int* returnSize){
    int n = numsSize;
    for(int i = 0;i < n;i++){
        for(int j = i + 1;j < n;j++){

            if(nums[i] +nums[j] == target){
                *returnSize = 2;
                int*ans = (int*)malloc(sizeof(int)*2);
                 ans[0] = i;ans[1] = j;
                 return ans;
            }
        
        }
    } 
    *returnSize = 0;
    return NULL;
}
```

**Comment by LC-Pam** [comment] 2023-12-05 21:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-08 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-08 18:30 UTC
Labels: Waiting for Reply
