### ISSUE TITLE
Missing Test Case - 1445. Apples 

### ISSUE THREAD

**Issue by kk-08** [LeetCode-Feedback/LeetCode-Feedback#13948] opened 2023-06-07 07:52 UTC
#### Your LeetCode username
kk94

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```
SELECT a.sale_date, (a.sold_num - o.sold_num) AS diff FROM 
(SELECT * FROM sales WHERE fruit = 'apples') a
INNER JOIN (SELECT * FROM sales WHERE fruit = 'oranges') o
USING(sale_date);
```

#### Language used for code
MySQL

#### Expected behavior
1 or more testcases must fail where the order of sale_date is checked

#### Additional context
The question expects the result to be ordered by the sale_date but there is no test case to check for it
Accepted submission: https://leetcode.com/problems/apples-oranges/submissions/965727405/?envType=study-plan-v2&envId=premium-sql-50

#### Screenshots
<img width="612" alt="Screenshot 2023-06-07 at 1 20 16 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61788247/41494f00-fe00-4860-a81e-dfb81fd32189">

#### Missing Test Case

| sale_date  | fruit   | sold_num |
| ---------- | ------- | -------- |
| 2020-05-04 | apples  | 15       |
| 2020-05-04 | oranges | 15       |
| 2020-05-03 | apples  | 10       |
| 2020-05-03 | oranges | 0        |
| 2020-05-02 | apples  | 6       |
| 2020-05-02 | oranges | 9       |
| 2020-05-01 | apples  | 10       |
| 2020-05-01 | oranges | 8        |

Expected output:

| sale_date  | diff |
| ---------- | ---- |
| 2020-05-04 | 0    |
| 2020-05-03 | 10   |
| 2020-05-02 | -3   |
| 2020-05-01 | 2    |

Output using the above solution:
| sale_date  | diff |
| ---------- | ---- |
| 2020-05-01 | 2    |
| 2020-05-02 | -3   |
| 2020-05-03 | 10   |
| 2020-05-04 | 0    |

Hence, this case would fail (as expected)

**Comment by LC-Pam** [comment] 2023-06-08 19:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kk-08** [comment] 2023-06-08 20:06
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The missing test case.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Updated the original comment to add a sample missing test case

**Comment by LC-Pam** [comment] 2023-06-13 19:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format, such as: {"headers":{"Sales":["sale_date","fruit","sold_num"]},"rows":{"Sales":[["2020-05-01","apples",10],["2020-05-01","oranges",8],["2020-05-02","apples",15],["2020-05-02","oranges",15],["2020-05-03","apples",20],["2020-05-03","oranges",0],["2020-05-04","apples",15],["2020-05-04","oranges",16]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 20:13
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 20:13 UTC
Labels: LCUS, problem

**Comment by kk-08** [comment] 2023-06-20 06:59
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The test case in JSON format, such as: {"headers":{"Sales":["sale_date","fruit","sold_num"]},"rows":{"Sales":[["2020-05-01","apples",10],["2020-05-01","oranges",8],["2020-05-02","apples",15],["2020-05-02","oranges",15],["2020-05-03","apples",20],["2020-05-03","oranges",0],["2020-05-04","apples",15],["2020-05-04","oranges",16]]}}
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Updated comment to add JSON test case
