### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain

### ISSUE THREAD

**Issue by masterujjval** [LeetCode-Feedback/LeetCode-Feedback#16640] opened 2023-09-23 19:52 UTC
#### Your LeetCode username
Mrgupta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
["cbd","xbc","abx","bx","adc","ac","cba",ba","xzcbda"]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestStrChain(vector<string>& words) {
        int n = words.size();
        if (n == 1) return 1;
        sort(words.begin(), words.end(), [&](string& x, string& y) {
            return x.size() < y.size(); 
        });
        vector<unordered_map<string, int>> mapping(17);
        for (auto& w : words)
            mapping[w.size()][w] = 1;

        int ans = 0;

        for (auto& w : words) {
            int wSize = w.size();
            if (wSize == 0) continue;
            for (int i = 0; i < wSize; i++) {
                string s2 = w.substr(0, i) + w.substr(i+1); 
                if (mapping[wSize-1].count(s2) != 0) {
                    mapping[wSize][w] = max(mapping[wSize][w], mapping[wSize-1][s2] + 1);
                }
            }
            ans = max(ans, mapping[wSize][w]);
        }

        return ans;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment] 2023-09-26 13:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

["cbd","xbc","abx","bx","adc","ac","cba",ba","xzcbda"]
received invalid test case: is not a valid value of type string[]

The valid test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-27 18:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by LC-Pam** [comment] 2023-09-28 16:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-28 16:03 UTC
Labels: Waiting for Reply
