### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by Himeshvmishra** [LeetCode-Feedback/LeetCode-Feedback#8230] opened 2022-07-17 10:15 UTC
class Solution {
public:
  bool isValid(string s) {
    stack<char> p, q;
    for (auto it = s.begin(); it != s.end(); ++it) {
      if (*it == '(' || *it == '{' || *it == '[') {
        p.push(*it);
      } else if (p.size() > 0) {
        switch (*it) {
          case ')': if (p.top() == '(') p.pop(); break;
          case ']': if (p.top() == '[') p.pop(); break;
          case '}': if (p.top() == '{') p.pop(); break;
} }
    }
    for (auto it = s.rbegin(); it != s.rend(); ++it) {
      if (*it == ')' || *it == '}' || *it == ']') {
        q.push(*it);
      } else if (q.size() > 0) {
        switch (*it) {
          case '(': if (q.top() == ')') q.pop(); break;
          case '[': if (q.top() == ']') q.pop(); break;
          case '{': if (q.top() == '}') q.pop(); break;
} }
}
    return p.size() == 0 && q.size() == 0;
  }
};

**Comment by LC-Pam** [comment] 2022-07-18 18:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-20 00:26
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-20 00:26 UTC
Labels: LCUS, problem
