### ISSUE TITLE
Solution Error

### ISSUE THREAD

**Issue by UdaySathe786** [LeetCode-Feedback/LeetCode-Feedback#7975] opened 2022-07-01 01:13 UTC
Compiler is showing error even when the code is write for today's daily challenge the error differ by a bit

#### Your LeetCode username

UdaySathe

#### Category of the bug
Solution

#### Description of the bug

NameError: name 'Solution' is not defined ret = Solution().minMoves2(param_1) Line 59 in _driver (Solution.py) _driver() Line 70 in <module> (Solution.py)

#### Code you used for Submit/Run operation

```
import re
from math import*
temp2 = 0
n = -1
res = -1
nums = input("Enter List : ")
temp = re.findall(r'\d+' , nums)
nums = list(map(int , temp))
nums.sort()
if len(nums)%2 == 0:
         temp2 = len(nums)/2
         temp3 = nums[ceil(temp2)]
         temp2 = nums[floor(temp2)]
         temp2 = (temp2 + temp3)/2
         temp2 = int(temp2)
else:
         temp2 = len(nums)/2
         temp2 = nums[int(temp2)]
while len(nums)-1>n:
    n+=1
    if nums[n] != temp2:
          if temp2 > nums[n]:
                 temp3 = temp2 - nums[n]
                 res += temp3
          if temp2 < nums[n]:
                 temp3 = nums[n]-temp2
                 res+= temp3 
else:
         if nums[n] != temp2:
          if temp2 > nums[n]:
                 temp3 = temp2 - nums[n]
                 res += temp3
          if temp2 < nums[n]:
                 temp3 = nums[n]-temp2
                 res+= temp3 
print(res)
```

#### Language used for code

Python
#### Expected behavior

To give the answer 2 for list of elements 1,2,3

**Comment by LC-Pam** [comment] 2022-07-05 17:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-06 16:58
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-06 16:58 UTC
Labels: LCUS, problem
