### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by raphaelrreis** [LeetCode-Feedback/LeetCode-Feedback#17441] opened 2023-10-25 10:58 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
import unittest

class TestSolution(unittest.TestCase):
    def test_moveZeroes(self):
        solution = Solution()
        
        nums1 = [0, 1, 0, 3, 12]
        solution.moveZeroes(nums1)
        self.assertEqual(nums1, [1, 3, 12, 0, 0])
        
        nums2 = [0, 0, 1]
        solution.moveZeroes(nums2)
        self.assertEqual(nums2, [1, 0, 0])
        
        nums3 = [1, 2, 3, 4, 5]
        solution.moveZeroes(nums3)
        self.assertEqual(nums3, [1, 2, 3, 4, 5])
        
        nums4 = [0, 0, 0, 0, 0]
        solution.moveZeroes(nums4)
        self.assertEqual(nums4, [0, 0, 0, 0, 0])

if __name__ == '__main__':
    unittest.main()
```

#### Language used for code
Python

**Comment by LC-Pam** [comment] 2023-10-25 18:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 19:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-27 19:03 UTC
Labels: Waiting for Reply
