### ISSUE TITLE
Wrong Test Case - 2402. Meeting Rooms III

### ISSUE THREAD

**Issue by mj2266** [LeetCode-Feedback/LeetCode-Feedback#8936] opened 2022-09-05 17:40 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong test cases

#### Description of the bug
Test case number 80 for the problem gives wrong answer for the following case. 
I have maintained a heap to keep track of end_time of meetings. 
Whenever I am processing a meeting[i] with some start_time, all the elements from heap less than equal to the start point should get popped off.
If there are no empty rooms present for a meeting, we will change the start time of meeting to whatever is the next end_time in the heap. 
At this point there are two choices, one choice is that suppose at top of heap, element as end time of 11, now you can just pop the top element which had end time of 11, and make its room available, or since we are popping element of end time 11, we will need to pop every other element in heap that has end time of 11 too. 
But popping every other element from heap having the same end time as top element will give wrong answer for test case 80. Note that only popping of the top of heap gives correct answer.

#### Code you used for Submit/Run operation

```
import numpy as np
class Solution:
    def mostBooked(self, n: int, meetings: List[List[int]]) -> int:
        
        meetings.sort()
        rooms = [0] * n
        counts = [0] * n
        
        heap = []
        
        for meeting in meetings:
            duration = meeting[1] - meeting[0]
            # i have reached start time for ith meeting
            # pop off all meetings
            while heap and heap[0][0] <= meeting[0]:
                ele = heapq.heappop(heap)
                rooms[ele[1]] = 0
              
            # get next empty room
            try:
                next_room = rooms.index(0)
            except:
                next_room = -1
            
            # if no room is empty
            if next_room == -1:
                # make meeting timing to end time of the next
                meeting[0] = heap[0][0]
                while heap and heap[0][0] == meeting[0]:
                    ele = heapq.heappop(heap)
                    rooms[ele[1]] = 0
                    
                next_room = rooms.index(0)
                
            
            
            rooms[next_room] = 1
            counts[next_room] += 1
            appender = [meeting[0] + duration, next_room]
            heapq.heappush(heap, appender)
            # print(heap)
        # print(counts)
        return np.argmax(counts)
```

#### Language used for code
Python 

#### Expected behavior
Expected behavior was to get correct answer for test case 80, but Instead I get wrong answer.

**Comment by LC-Pam** [comment] 2022-09-06 17:38
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-12 02:39
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-12 02:39 UTC
Labels: LCUS, problem
