### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by indukvn** [LeetCode-Feedback/LeetCode-Feedback#13672] opened 2023-05-24 14:43 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution

#### Code you used for Submit/Run operation

```
def calculate(self, s):
        """
        :type s: str
        :rtype: int
        """

        stack = []
        curr = 0
        operator = '+'
        for c in s + "+":
            if c == " ":
                continue
            elif c.isdigit():
                curr = (curr * 10) + int(c)
            else:
                if operator == '-':
                    stack.append(-curr)
                elif operator == '+':
                    stack.append(curr)
                elif operator == '*':
                    stack.append(stack.pop() * curr)
                elif operator == '/':
                    stack.append(int(stack.pop() / curr))
                curr = 0
                operator = c 
        return sum(stack)
```

**Comment by LC-Pam** [comment] 2023-05-26 20:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-30 20:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-30 20:40 UTC
Labels: LCUS, problem
