### ISSUE TITLE
10. Regular Expression Matching is broken in Python3

### ISSUE THREAD

**Issue by Autism2B2B** [LeetCode-Feedback/LeetCode-Feedback#12101] opened 2023-03-02 12:23 UTC
last few test-cases on submit are timing out, even if i just put `return False`  as the only code and the last test-case is literally just 
`s =`

**Comment by LC-Pam** [comment] 2023-03-02 20:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-03 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-03 19:45 UTC
Labels: LCUS, problem
