### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by devrajtherani** [LeetCode-Feedback/LeetCode-Feedback#16835] opened 2023-10-01 09:34 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The code does not give desired output if we have two numbers like 501 and 555.

#### Code you used for Submit/Run operation

```class ListNode(object):
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution():
    def createLinkedList(self, lst):
        head = None
        for val in lst:
            head = ListNode(val, head)
        return head

    def addTwoNumbers(self, l1, l2):
        dummy = ListNode()
        result = dummy
        carry = 0

        while l1 or l2 or carry:
            sum = 0
            if l1:
                sum += l1.val
                l1 = l1.next
            if l2:
                sum += l2.val
                l2 = l2.next
            sum += carry
            carry = sum // 10
            result.next = ListNode(sum % 10)
            result = result.next

        return dummy.next

def toList(head):
    lst = []
    while head:
        lst.append(head.val)
        head = head.next
    return lst

# Create instances of the Solution class
sol = Solution()

# Create linked lists from the input lists
l1 = sol.createLinkedList([1, 2, 3])
l2 = sol.createLinkedList([2, 4, 6])

# Add the linked lists and convert the result to a list
result = sol.addTwoNumbers(l1, l2)

# Convert the result linked list to a list for printing
print(toList(result))
```

#### Language used for code
Python

#### Expected behavior
[6,5,0,1] shall be the answer whereas it is [0,6,6]

**Comment by LC-Pam** [comment] 2023-10-03 18:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:22 UTC
Labels: Waiting for Reply
