### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by AkshatUke** [LeetCode-Feedback/LeetCode-Feedback#18070] opened 2023-11-15 05:09 UTC
### LeetCode Username

AkshatUke

### Problem number, title, and link

1846. Maximum Element After Decreasing and Rearranging https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
import java.util.*;
class Solution {
    public int maximumElementAfterDecrementingAndRearranging(int[] arr) {
        Arrays.sort(arr);
        if(arr[arr.length-1] <= arr.length){
            if(arr.length>1 && arr[arr.length-1]-arr[arr.length-2] > 1){
                return arr[arr.length-2]+1;
            }
            return arr[arr.length-1];
        }
        return arr.length;
    }
}
```

### Expected behavior

I submitted my code and it worked properly but some test case that i made was wrong 
ex [1,1,1,1,1,100]
output is 6
expected is 2
But then also its accepting my code

**Comment by LC-Pam** [comment] 2023-11-15 20:35
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18069

**Closed by LC-Pam** 2023-11-15 20:35 UTC
