### ISSUE TITLE
200: Number of Islands. [golang] Miss behaving running my code

### ISSUE THREAD

**Issue by defeng-song** [LeetCode-Feedback/LeetCode-Feedback#11629] opened 2023-02-10 02:47 UTC
This is my submission. The code works very well locally.
```go
func numIslands(grid [][]byte) int {
	m, n := len(grid), len(grid[0])
	var mark func(int, int)
	mark = func(x, y int) {
		grid[x][y]++
		// up
		if x > 0 && grid[x-1][y] == 1 {
			mark(x-1, y)
		}
		// down
		if x < m-1 && grid[x+1][y] == 1 {
			mark(x+1, y)
		}
		// left
		if y > 0 && grid[x][y-1] == 1 {
			mark(x, y-1)
		}
		// right
		if y < n-1 && grid[x][y+1] == 1 {
			mark(x, y+1)
		}
	}
	var result int
	for i := 0; i < m; i++ {
		for j := 0; j < n; j++ {
			if grid[i][j] == 1 {   // <<<<<<< it appears this condition never meets in LeetCode go runtime.
				mark(i, j)
				result++
			}
		}
	}
	return result
}

```

**Comment by LC-Pam** [comment] 2023-02-10 19:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The issue or problem you want to submit. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-11 19:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-11 19:57 UTC
Labels: LCUS, problem

**Comment by defeng-song** [comment] 2023-02-13 06:40
https://leetcode.com/problems/number-of-islands/

this is the LC problem. I'm using Golang.
