### ISSUE TITLE
Invalid Example Output - 27. Remove Element

### ISSUE THREAD

**Issue by itsashish1801** [LeetCode-Feedback/LeetCode-Feedback#9055] opened 2022-09-14 10:32 UTC
#### Category of the bug
- [ ✅] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There's slight error in the Example 2 output
Now -> [0,1,4,0,3,_,_,_] ❌
Need to be -> [0,1,3,0,4,_,_,_] ✅

**Comment by LC-Pam** [comment] 2022-09-16 10:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-18 06:39
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-18 06:39 UTC
Labels: LCUS, problem
