### ISSUE TITLE
Missing Test Case - 137. Single Number II

### ISSUE THREAD

**Issue by Vijayvijay01** [LeetCode-Feedback/LeetCode-Feedback#14534] opened 2023-07-04 14:10 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

class Solution {
public:
    int singleNumber(vector<int>& nums) {
        int ans;
        int  n=nums.size();
        unordered_map<int,int>m;
        for(int i=0;i<n;i++)
        {
        m[nums[i]]++;
        }
        for(auto i:m)
        {
            if(i.second==1)
            {
                ans=i.first;
            }
        }
        return ans;

            }

};

**Comment by LC-Pam** [comment] 2023-07-05 15:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-06 20:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-06 20:34 UTC
Labels: LCUS, problem
