### ISSUE TITLE
Um this is a report regarding how the question wasn't clear and has a flaw.

### ISSUE THREAD

**Issue by lipin1** [LeetCode-Feedback/LeetCode-Feedback#13993] opened 2023-06-09 16:51 UTC
#### Category of the bug
- [ ] Question

#### Description of the bug
The problem is the question said you can jump k-1,k,k+1 but never mentioned the stones are skippable. So correct the question properly or remove this case in the example [0,1,3,5,6,8,12,17]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canCross(vector<int>& stones) {
        bool cross = true;
        int k=1;
        for(int i=0;i<stones.size()-1;i++)
        {
            if(stones[i+1]-stones[i]==k)
                continue;
            else if(stones[i+1]-stones[i]==k+1)
                k++;

            else if(stones[i+1]-stones[i]==k-1)
                k--;
            else
                cross=false;
        }
    return cross;  
    }
}; 
```

#### Expected behavior
To say I'm correct. This small code solved 42 cases out of 52. But the question is unclear.

**Comment by LC-Pam** [comment] 2023-06-13 19:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 20:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 20:10 UTC
Labels: LCUS, problem
