### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Sujanabhandari** [LeetCode-Feedback/LeetCode-Feedback#10538] opened 2022-12-25 16:48 UTC
#### Your LeetCode username
sujana6589

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test case: nums = [3, 10, 8, 5, 14], target = 15 should be added. The following solution will pass all given test cases. However, this test case fails in reality.

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function(nums, target) {
   let result=[];
   let sortedNums = [...nums].sort((a,b) => a - b);
   let left = 0;
   let right = nums.length - 1 ;
   while (left < right) {  // O(n) time
    let sum = sortedNums[left] + sortedNums[right];
    if (sum === target) {
      // find the original indices of the two numbers
      let leftIndex = nums.indexOf(sortedNums[left]);
      let rightIndex = nums.indexOf(sortedNums[right], leftIndex + 1);
      result = [leftIndex, rightIndex];
      break;
    } else if (sum < target) {
      left++;
    } else {
      right--;
    }
  }
  return result;
}
```

#### Language used for code
JavaScript

#### Expected behavior

[3, 1]

**Comment by LC-Pam** [comment] 2022-12-26 19:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-28 20:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-28 20:45 UTC
Labels: LCUS, problem
