### ISSUE TITLE
Missing Test Case - 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by Jagath15SM** [LeetCode-Feedback/LeetCode-Feedback#12250] opened 2023-03-08 11:49 UTC
#### Your LeetCode username

Jagath

#### Category of the bug
- [x] Missing Test Cases / Wrong test case found 

#### Code you used for Submit/Run operation

```
// 875. Koko Eating Bananas
class Solution {
    public int minEatingSpeed(int[] piles, int h) {
    
    }
}
```

###Booleanage used for code

Java

#### Expected behavior

Mine answer is correct but it showing wrong, correct answer = 1, but it showing 3.

#### Screenshots

This below test case is wrong:
![image](https://user-images.githubusercontent.com/121512908/223704346-4c434a59-1ec3-4f1b-9911-bd35aebdde79.png)

**Comment by Jagath15SM** [comment] 2023-03-09 11:55
1 is not an hour (hour value is given in question only), we need to return minimum value of 'k' (here answer, k = 1)

**Comment by LC-Pam** [comment] 2023-03-20 17:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-31 14:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-31 14:55 UTC
Labels: LCUS, problem

**Comment by Jagath15SM** [comment] 2023-04-12 18:15
https://leetcode.com/problems/koko-eating-bananas/submissions/911431912/
