### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by Beni-prog** [LeetCode-Feedback/LeetCode-Feedback#13024] opened 2023-04-18 10:56 UTC
#### Your LeetCode username
BeniAc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Contributing a testcase

#### Code you used for Submit/Run operation

```
class Solution {
    public String mergeAlternately(String word1, String word2) {
       int i = 0, j = 0;
        StringBuilder sb = new StringBuilder();

        while (i < word1.length() && j < word2.length()) {
            sb.append(word1.charAt(i));
            sb.append(word2.charAt(j));
            i++;
            j++;
        }

        while (i < word1.length()) {
            sb.append(word1.charAt(i));
            i++;
        }

        while (j < word2.length()) {
            sb.append(word2.charAt(j));
            j++;
        }

        return sb.toString();
    }
}
```

#### Language used for code
Java

#### Expected behavior
For the strings "Lecd" and "etoe!!!", the output should be "Leetcode!!!"

**Comment by LC-Pam** [comment] 2023-04-18 23:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by xelplogoog** [comment] 2023-04-19 03:12
Constraints:
word1 and word2 consist of lowercase English letters.

no L and ! allowed

**Comment by LC-Pam** [comment] 2023-04-20 18:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-20 18:39 UTC
Labels: LCUS, problem
