### ISSUE TITLE
 148. Sort List

### ISSUE THREAD

**Issue by aditya28tripathi** [LeetCode-Feedback/LeetCode-Feedback#8671] opened 2022-08-15 06:35 UTC
class Solution {
public:
    ListNode* midElement(ListNode* head)
    {
        ListNode* slow= head;
        ListNode* fast= head->next;
        while(slow->next!= NULL && (fast!= NULL && fast->next!= NULL))
        {
            slow= slow->next;
            fast= fast->next->next;
        }
        return slow;
    }
    ListNode* merge(ListNode* head1, ListNode* head2)
    {
        ListNode* dummyNode= new ListNode(-1);
        ListNode* ptr1= head1;
        ListNode* ptr2= head2;
        ListNode* ptr3= dummyNode;
        while(ptr1!= NULL && ptr2!= NULL)
        {
            if(ptr1->val < ptr2->val)
            {
                ptr3->next= ptr1;
                ptr1= ptr1->next;
            }
            else
            {
                ptr3->next= ptr2;
                ptr2= ptr2->next;
            }
            ptr3= ptr3->next;
        }
        while(ptr1!= NULL)
        {
            ptr3->next= ptr1;
            ptr1= ptr1->next;
            ptr3= ptr3->next;
        }
        while(ptr2!= NULL)
        {
            ptr3->next= ptr2;
            ptr2= ptr2->next;
            ptr3= ptr3->next;
        }
        return dummyNode->next;
    }
    
    ListNode* sortList(ListNode* head) 
    {
       if(head== NULL || head->next== NULL)
       {
           return head;
       }
       ListNode* mid= midElement(head);
       ListNode* head2= mid->next;
       mid->next= NULL;
       ListNode* finalHead= merge(sortList(head), sortList(head2));
       return finalHead;
    }
};

**Comment by LC-Pam** [comment] 2022-08-15 16:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-17 02:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding

**Closed by LC-Pam** 2022-08-17 02:45 UTC
Labels: LCUS, problem
