### ISSUE TITLE
Missing Test Case - 1464. Maximum Product of Two Elements in an Array

### ISSUE THREAD

**Issue by dazatar1994** [LeetCode-Feedback/LeetCode-Feedback#18616] opened 2023-12-12 07:02 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation
Please make sure to wrap the code with ``` tags. 

 ``` var maxProduct = function(nums) {
    let sum = 0
    for(let i = 0; i < nums.length-1; i++){
        for(let j =1; j < nums.length; j++){
            			if( i==j) continue

            let num = (nums[i]-1)*(nums[j]-1)
            if(num > sum) sum = num 

        }
    }
    return sum
}; ```

**Comment by dazatar1994** [comment] 2023-12-12 07:02
/**
 * @param {number[]} nums
 * @return {number}
 */
var maxProduct = function(nums) {
    let sum = 0
    for(let i = 0; i < nums.length-1; i++){
        for(let j =1; j < nums.length; j++){
            			if( i==j) continue

            let num = (nums[i]-1)*(nums[j]-1)
            if(num > sum) sum = num 

        }
    }
    return sum
};

**Comment by LC-Pam** [comment] 2023-12-12 23:48
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-14 22:26
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-14 22:26 UTC
Labels: Waiting for Reply
