### ISSUE TITLE
Missing Test Case - 1683. Invalid Tweets

### ISSUE THREAD

**Issue by SriGanesh737** [LeetCode-Feedback/LeetCode-Feedback#15315] opened 2023-08-05 14:47 UTC
#### Your LeetCode username
sriganesh777

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

it is showing wrong expected output for a testcase. the code still gives an AC.
This is the testcase:
| tweet_id | content        |
| -------- | -------------- |
| 1        | Vote for Biden |
| 2        | This is valid€ |

#### Code you used for Submit/Run operation

```
import pandas as pd

def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:
    # Filter rows where the length of 'content' is strictly greater than 15
    invalid_tweets_df = tweets[tweets['content'].str.len() > 15]
    
    # Select only the 'tweet_id' column from the invalid tweets DataFrame
    result_df = invalid_tweets_df[['tweet_id']]
    
    return result_df
```

#### Language used for code
Pandas

#### Expected behavior

Expected output is an empty table but it is showing expected output as id =2.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105561173/6528d054-8900-4bc1-a0c5-7a3ba3ecf3da)

**Comment by vlahovivan** [comment] 2023-08-08 11:44
I just did some research, this test is invalid because the euro sign (€) is in Unicode, which is not supported by the varchar type.
More info on [this StackOverflow thread](https://stackoverflow.com/questions/50173944/euro-sign-%E2%82%AC-in-varchar-column).

**Comment by LC-Pam** [comment] 2023-08-08 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}
.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:46 UTC
Labels: LCUS, problem, Waiting for Reply
