### ISSUE TITLE
Missing Test Case - 2121. Intervals Between Identical Elements

### ISSUE THREAD

**Issue by itbere** [LeetCode-Feedback/LeetCode-Feedback#13413] opened 2023-05-11 20:18 UTC
from typing import List

class Solution:
    def getDistances(self, arr: List[int]) -> List[int]:
        # инициализация словаря для хранения индексов элементов
        indices = {}
        for i, num in enumerate(arr):
            if num not in indices:
                indices[num] = [i]
            else:
                indices[num].append(i)
        
        # вычисление интервалов для каждого элемента
        result = []
        for i, num in enumerate(arr):
            intervals_sum = 0
            for index in indices[num]:
                intervals_sum += abs(i - index)
            result.append(intervals_sum)
        
        return result

**Comment by LC-Pam** [comment] 2023-05-12 21:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-15 00:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-15 00:56 UTC
Labels: LCUS, problem
