### ISSUE TITLE
Wrong result for empty array - 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by Aivean** [LeetCode-Feedback/LeetCode-Feedback#4800] opened 2021-09-15 21:35 UTC
#### Your LeetCode username
Aivean

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Per the problem definition, the result is the "the length of a subarray of arr":
> Given an integer array arr, return the length of a maximum size turbulent subarray of arr.

For the empty input array, the reasonable answer should be 0, while the author's solution returns 1.

#### Code you used for Submit/Run operation

```kotlin
class Solution {
    fun maxTurbulenceSize(arr: IntArray): Int {
        if (arr.size == 0) return 0
    
        var even = 1
        var odd = 1
        var res = 1
        
        for (i in 1 until arr.size) {
            if (arr[i] == arr[i-1]) {
                even = 1
                odd = 1                
            } else {
                if ((arr[i] < arr[i-1]) xor (i % 2 == 0)) {
                    even++
                    odd = 1
                } else {
                    odd ++
                    even = 1
                }
            }
            res = Math.max(res, Math.max(even, odd))
        }
        return res
    }  
}
```

#### Language used for code
Kotlin

#### Expected behavior

```
Input:
[]

Output:
0
```

#### Actual behavior

```
Input:
[]

Output:
1
```

#### Screenshots
![image](https://user-images.githubusercontent.com/2865203/133512466-c28529c4-421c-4739-aff5-e62f6c4168fc.png)

**Comment by Aivean** [comment] 2021-09-15 21:40
Seems that this is a duplicate of #4799

**Comment by lc-kay** [comment] 2021-09-16 17:57
Duplicate of #4799 Please check for updates on that ticket. Thank you!

**Closed by lc-kay** 2021-09-16 17:57 UTC
