### ISSUE TITLE
Missing Test Case - 1046. Last Stone Weight

### ISSUE THREAD

**Issue by SuryaPratap2542** [LeetCode-Feedback/LeetCode-Feedback#6938] opened 2022-04-07 17:42 UTC
`class Solution:
    def lastStoneWeight(self, st: List[int]) -> int:
        st.sort()
        n=len(st)
        if n==1:
            return st[0]
        j=n-2
        while j>=0 and len(st)!=1:
            if st[j]==st[j+1]:
                st.remove(st[j+1])
                st.remove(st[j])
            else:
                st[j+1]=st[j+1]-st[j]
                st.remove(st[j])
            j=j-1
            st.sort()
        return st[0]

**Comment by LC-Yani** [comment] 2022-04-25 17:00
Hi @,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The testcase that you use

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment] 2022-04-27 17:29
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-27 17:29 UTC
Labels: LCUS, problem
