### ISSUE TITLE
Missing Test Case - 1917. Leetcodify Friends Recommendations

### ISSUE THREAD

**Issue by thedrugsdontwork** [LeetCode-Feedback/LeetCode-Feedback#16551] opened 2023-09-20 08:54 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

测试用例预期结果与题目不符。
#### TestCase
Listens
 
| user_id | song_id | day        |
| ------- | ------- | ---------- |
| 1       | 10      | 2021-03-15 |
| 1       | 11      | 2021-03-15 |
| 1       | 12      | 2021-03-15 |
| 2       | 10      | 2021-03-15 |
| 2       | 11      | 2021-03-15 |
| 2       | 12      | 2021-03-15 |
| 3       | 10      | 2021-03-15 |
| 3       | 11      | 2021-03-15 |
| 3       | 12      | 2021-03-15 |
| 4       | 10      | 2021-03-15 |
| 4       | 11      | 2021-03-15 |
| 4       | 13      | 2021-03-15 |
| 5       | 10      | 2021-03-16 |
| 5       | 11      | 2021-03-16 |
| 5       | 12      | 2021-03-16 |
Friendship
 
| user1_id | user2_id |
| -------- | -------- |
| 1        | 2        |

#### Results
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87700233/ff3efddd-4873-46c9-8457-05b2e1429533)

**Comment by LC-Pam** [comment] 2023-09-20 17:07
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-22 20:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-22 20:00 UTC
Labels: Waiting for Reply
