### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by venkatapavannidamanuri** [LeetCode-Feedback/LeetCode-Feedback#11715] opened 2023-02-13 10:49 UTC
class Solution {
    public int removeElement(int[] nums, int val) {
        int i = 0;
        for (int j = 0; j < nums.length; j++) {
            if (nums[j] != val) {
                int temp = nums[i];
                nums[i] = nums[j];
                nums[j] = temp;
                i++;
            }
        }
        return i;
    }
}

**Comment by LC-Pam** [comment] 2023-02-13 19:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code  you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-14 18:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-14 18:55 UTC
Labels: LCUS, problem
