### ISSUE TITLE
Wrong Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by Gyanbardhan** [LeetCode-Feedback/LeetCode-Feedback#17299] opened 2023-10-18 04:08 UTC
#### Your LeetCode username
gyan_10022003

#### Category of the bug
- [ ] Solution
- [ ] Wrong Test Cases 

#### Description of the bug

![Screenshot 2023-10-18 091033](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120886311/8ea4a263-bdb6-404a-87d4-6539222964a9)

In test case
n=4
lefthild=[3,-1,1,-1]
rightChild=[-1,-1,0,-1]
This is the valid binary tree.But for the testcase since rightChild[0] is -1 it should stop and then for leftChild[1]=-1 & rightChild[1]=-1 it should stop and the test case should return false as output.But expected output is true.

#### Code you used for Submit/Run operation

```
// [1361. Validate Binary Tree Nodes
class Solution {
public:
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        int x=0;
        for(int i=0;i<n;i++)
        {
            if(leftChild[i]!=-1)
            x++;
            if(rightChild[i]!=-1)
            x++;
        }
        if(x!=n-1)
        return false;
        else
        {
            queue<int>q;
            int k=0,j=0;
            if(leftChild[k]!=-1)
            q.push(leftChild[k]);
            if(rightChild[j]!=-1)
            q.push(rightChild[j]);
            k=1;
            j=1;
            while(1)
            {
                int s=q.size();
                for(int i=0;i<s;i++)
                {
                    if(leftChild[k]!=-1)
                    q.push(leftChild[k]);
                    if(rightChild[j]!=-1)
                    q.push(rightChild[j]);
                    k++;
                    j++;
                    q.pop();
                }
                if(q.empty())
                break;
            }
            if(j==n&&k==n)
            return true;
            return false;
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

As i have mentioned above i am expecting 'false' as expected output but expected output is 'true'

#### Screenshots

![Screenshot 2023-10-18 091012](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120886311/3c78188b-0624-40d3-b0bd-fe90693ae7ed)
![WhatsApp Image 2023-10-18 at 09 14 58](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120886311/c127783d-2fb0-46e8-ba83-4f25c7e06922)

**Comment by LC-Pam** [comment] 2023-10-18 19:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-20 20:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-20 20:04 UTC
Labels: Waiting for Reply
