### ISSUE TITLE
Missing Test Case - 2346. Compute the Rank as a Percentage

### ISSUE THREAD

**Issue by prasadseemakurthi** [LeetCode-Feedback/LeetCode-Feedback#9988] opened 2022-11-20 07:35 UTC
#### Category of the bug
- [  2346. Compute the Rank as a Percentage]
- [ ] Solution
- [ SQL]
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
with dept_cnt as 
(SELECT department_id, 
    count(*) as cnt
    FROM Students
 GROUP BY department_id
),
stud_rank as (
SELECT student_id
    , department_id
    , RANK() OVER (PARTITION BY department_id ORDER BY mark DESC) as r
FROM students    
)
SELECT s.student_id
    ,d.department_id
    ,ROUND((s.r-1)*100/(d.cnt-1),2) as percentage
FROM stud_rank s
INNER JOIN dept_cnt d
on s.department_id = d.department_id
```

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2022-11-21 19:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.
The issues.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-11-23 22:18
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-11-23 22:18 UTC
Labels: LCUS, problem
