### ISSUE TITLE
472. Concatenated Words

### ISSUE THREAD

**Issue by ayus786** [LeetCode-Feedback/LeetCode-Feedback#11312] opened 2023-01-27 16:41 UTC
**Problem: 472. Concatenated Words**
Link: https://leetcode.com/problems/concatenated-words/
I don't think its difficulty is accurate because it accepted my brute-force dfs solution.
I hope you will look forward to it.

Below is my solution which got accepted -:

`
class Solution {
public:
    bool conCat(string s,unordered_map<string,int>& mp,int st=0,int k=0){
        if(st==s.size() && k>1){
            return true;
        }
        string ss="";
        bool ans=false;
        for(int i=st; i<s.size(); i++){
            ss+=s[i];
            if(mp[ss]){
                ans|=conCat(s,mp,i+1,k+1);
            }
        }
        return ans;
    }
    vector<string> findAllConcatenatedWordsInADict(vector<string>& words) {
        unordered_map<string,int> mp;
        for(auto i:words){
            mp[i]=1;
        }
        vector<string> v;
        for(auto i:words){
            if(conCat(i,mp)){
                v.push_back(i);
            }
        }
        return v;
    }
};
`

**Comment by LC-Pam** [comment] 2023-01-27 19:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-30 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-30 19:45 UTC
Labels: LCUS, problem
