### ISSUE TITLE
Missing Test Case - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by s-ourav** [LeetCode-Feedback/LeetCode-Feedback#14970] opened 2023-07-23 10:07 UTC
Input
s =
"aaabbbabbbaaa"
Output
2
Expected
1
<img width="1406" alt="Screenshot 2023-07-23 at 3 37 30 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/129527787/7283e1aa-f267-4f18-a733-89a45a361e8a">

**Comment by LC-Pam** [comment] 2023-07-25 22:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:17 UTC
Labels: LCUS, problem, Waiting for Reply

**Comment by s-ourav** [comment] 2023-07-29 06:11
https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/submissions/1001718052/
