### ISSUE TITLE
WRONG constraint it will cause TLE! 170. Two Sum III - Data structure design

### ISSUE THREAD

**Issue by HemsBansal** [LeetCode-Feedback/LeetCode-Feedback#4368] opened 2021-08-02 14:04 UTC
Your LeetCode username
hemsbansal

[](https://leetcode.com/hemsbansal/)

Category of the bug
 Question
 Solution
 Language
 Missing Test Cases
Description of the bug
Following is constraint from Leetcode (last updated 02/08/2020):
Constraints:

-10^5 <= number <= 10^5
-2^31 <= value <= 2^31 - 1
At most 5 * 10^4 calls will be made to add and find.
Time complexity of the Official Solution and other discussions are O(1) for Add, O(N) for Find. I wonder if I have the testcase:

Call Add to add 10^4 different numbers
Call Find 4*10^4 times.
=> Each of Find operation take O(N) ~ 10^4 times
=> Total = (10^4) * (4*10^4) = 4 * 10^8
=> Time Limit Exceeded! occurs.
Code you used for Submit/Run operation
class TwoSum(object):

    def __init__(self):
        """
        Initialize your data structure here.
        """
        self.num_counts = {}

    def add(self, number):
        """
        Add the number to an internal data structure..
        :type number: int
        :rtype: None
        """
        if number in self.num_counts:
            self.num_counts[number] += 1
        else:
            self.num_counts[number] = 1

    def find(self, value):
        """
        Find if there exists any pair of numbers which sum is equal to the value.
        :type value: int
        :rtype: bool
        """
        for num in self.num_counts.keys():
            comple = value - num
            if num != comple:
                if comple in self.num_counts:
                    return True
            elif self.num_counts[num] > 1:
                return True
        
        return False
Language used for code
Python

Expected behavior
The constraint from Leetcode problem description is WRONG.
Following is constraint from Leetcode (last updated 02/08/2020):
Constraints:

-10^5 <= number <= 10^5
-2^31 <= value <= 2^31 - 1
At most 5 * 10^4 calls will be made to add and find.
I think we can change the constraint as:
Constraints:

-10^5 <= number <= 10^5
-2^31 <= value <= 2^31 - 1
At most 10^3 calls will be made to add and find.
Since limit to 10^3, it can work in O(N^2).

Screenshots
image

Additional context
This is the valid testcase can cause TLE: https://pastebin.pl/view/385bc1fd

This is the Python code to generate the testcase:

arr = [[]]
operations = ["TwoSum"]
for x in range(2, 10**4 + 1):
    operations.append("add")
    arr.append([x])

operations.append("add")
arr.append([10**4])

for i in range(4 * 10**4):
    operations.append("find")
    arr.append([2 * 10**4])

print(operations)
print(arr)

**Comment by lc-kay** [comment] 2021-08-03 18:19
Duplicate of #4367

**Closed by lc-kay** 2021-08-03 18:19 UTC
