### ISSUE TITLE
Missing Test Case - 1192. Critical Connections in a Network

### ISSUE THREAD

**Issue by kimsey0** [LeetCode-Feedback/LeetCode-Feedback#3279] opened 2021-04-26 15:03 UTC
#### Your LeetCode username

kimsey0

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Description has constraints `1 <= n <= 10^5` and `n-1 <= connections.length <= 10^5`. That should allow `n = 1` and `connections.Length = 0`. However, running code with custom test case
```
1
[]
```
gives run code status `Invalid Testcase` and expected answer `Line 37: java.lang.NullPointerException`. That suggests that the reference implementation incorrectly doesn't handle the case where `connections.Length = 0`. The actual answer should be an empty array `[]` of critical connections.

#### Code you used for Submit/Run operation

``` csharp
public class Solution
{
    private int time = 1;

    public IList<IList<int>> CriticalConnections(int n, IList<IList<int>> connections)
    {
        if (connections.Count == 0)
        {
            return Array.Empty<IList<int>>();
        }

        var graph = Enumerable.Range(0, n).Select(_ => new List<int>()).ToArray();
        foreach (var connection in connections)
        {
            graph[connection[0]].Add(connection[1]);
            graph[connection[1]].Add(connection[0]);
        }

        var timestamp = new int[n];
        var criticalConnections = new List<IList<int>>();
        DepthFirstSearch(graph, timestamp, 0, -1, criticalConnections);
        return criticalConnections;
    }

    private int DepthFirstSearch(IList<IList<int>> graph, int[] timestamp, int vertex, int parent, IList<IList<int>> criticalConnections)
    {
        if (timestamp[vertex] != 0)
        {
            return timestamp[vertex];
        }

        timestamp[vertex] = time++;

        var minTimestamp = graph[vertex]
            .Where(n => n != parent)
            .Select(neighbor => DepthFirstSearch(graph, timestamp, neighbor, vertex, criticalConnections))
            .DefaultIfEmpty(int.MaxValue)
            .Min();

        if (minTimestamp >= timestamp[vertex] && parent >= 0)
        {
            criticalConnections.Add(new[] { parent, vertex });
        }

        return Math.Min(timestamp[vertex], minTimestamp);
    }
}
```

#### Language used for code

C#

#### Expected behavior

Test case
```
1
[]
```
should be allowed.

#### Screenshots

![Run Code Status: Invalid Testcase](https://user-images.githubusercontent.com/984760/116104961-2b407980-a6b1-11eb-86c8-f1a7807524cc.png)

**Comment by kimsey0** [comment] 2021-04-26 15:05
Just noticed this seems to be a duplicate of #3241, but this includes a bit more information, so I'll leave it open for now. Feel free to close it at your leisure.

**Comment by lc-kay** [comment] 2021-04-27 18:38
@kimsey0 Thank you for your report. Since this is a duplicate of #3241, I will close this ticket.

**Closed by lc-kay** 2021-04-27 18:38 UTC
Labels: LCUS, problem, watchlist
