### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by CodeWithtankan** [LeetCode-Feedback/LeetCode-Feedback#14398] opened 2023-06-27 15:50 UTC
class Solution {
public:
    int reverse(int x) {
        int n=0;
        int c=0;
        int flag = 1;
        if(x < 0){
            x = -x;
            flag = 0;
        }
        while(x>0){
            c = x % 10;
            n = ((10*n) + c);
            x = x/10;
        }
        if(flag==1){
            return n;
        }
        else{
            return -n;
        }
    }
};

**Comment by LC-Pam** [comment] 2023-06-27 18:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-29 18:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-29 18:17 UTC
Labels: LCUS, problem
