### ISSUE TITLE
Wrong expected answer for test case  - 1528. Shuffle String

### ISSUE THREAD

**Issue by NoroSaroyan** [LeetCode-Feedback/LeetCode-Feedback#10519] opened 2022-12-24 14:06 UTC
#### Your LeetCode username
noriksaroyan1234

#### Category of the bug
- Wrong test case 

#### Description of the bug
The problem is with indices of the first test case where:
indices: {4,5,6,7,0,2,1,3}
string: "codeleet"
In this case, the right working algorithm will always return "leetcdoe" and not "leetcode"

#### Code you used for Submit/Run operation
```
public String restoreString(String s, int[] indices) {
        StringBuilder res = new StringBuilder();
        for(int i = 0; i<indices.length; i++){
            res.append(s.charAt(indices[i]));
        }
        s = res.toString();
        return s;
    }
```

#### Language used for code
Java

#### Expected behavior
Function, as it should, returns  'leetcdoe', but expected answer is leetcode with indices {4,5,6,7,0,2,1,3} and String s "codeleet"

**Comment by nskybytskyi** [comment] 2022-12-25 15:38
I'm afraid you misread the problem. `indices[i]` denotes the destination of `s[i]`, not the source of `res[i]`.

**Comment by LC-Pam** [comment] 2022-12-26 18:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us, you also can consider above comment as reference: 

The code submit AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-28 20:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed** 2022-12-28 20:44 UTC
Labels: LCUS, problem
