### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by jeeten-dhall** [LeetCode-Feedback/LeetCode-Feedback#13960] opened 2023-06-08 05:40 UTC
#### Your LeetCode username

jeeten-dhall

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

A testcase to provide input of size upper limits.

#### Code you used for Submit/Run operation

```
    private int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }

    @Test void testExample4 () {
        int numCount = (int) Math.pow(10, 5); // 10^5 numbers
        int numRangeLow = (-1) * ((int) Math.pow(10, 9)); // numbers ranging -+ 10^9
        int numRangeHigh = (int) Math.pow(10, 9);
        int [] nums = new int[numCount];
        for(int i=0; i < numCount; i++) {
         nums[i] = getRandomNumber(numRangeLow, numRangeHigh); // randomly generated numbers
        }

        // convert int [] nums to Set to remove duplicates
        Integer [] numsBoxed = Arrays.stream(nums).boxed().toArray(Integer[]::new);
        Set<Integer> numsSet = new HashSet<>(Arrays.asList(numsBoxed));

        if(numsSet.size() < nums.length) {
            // duplicates present in nums
            assertTrue(new ContainsDuplicate().containsDuplicate(nums));
        } else {
            // no duplicates in nums
            assertFalse(new ContainsDuplicate().containsDuplicate(nums));
        }
    }
```

#### Language used for code

Java

#### Expected behavior

I expected a testcase that provided numbers in the range -+ 10^10 and count of numbers = 10^5, to push the program to its memory limits.

**Comment by LC-Pam** [comment] 2023-06-08 19:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case in txt file.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:40 UTC
Labels: LCUS, problem
