### ISSUE TITLE
364 Broken test case

### ISSUE THREAD

**Issue by tyleradams** [LeetCode-Feedback/LeetCode-Feedback#18105] opened 2023-11-16 23:39 UTC
### LeetCode Username

coppero1237

### Problem number, title, and link

https://leetcode.com/problems/nested-list-weight-sum-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Input: [[1,1],2,[1,1],[[[[]]]]] 
Output: 26
This is incorrect. It should either be:
20 (as per the official solution)
8 (if we assume the depth is 2, not 5 given the empty list)

### Language used for code

Used official Java solution

### Code used for Submit/Run operation

Official Java solution 
class Solution {
    public int depthSumInverse(List<NestedInteger> nestedList) {
        int maxDepth = findMaxDepth(nestedList);
        return weightedSum(nestedList, 1, maxDepth);
    }

    private int findMaxDepth(List<NestedInteger> list) {
        int maxDepth = 1;
        
        for (NestedInteger nested : list) {
            if (!nested.isInteger()) {
                maxDepth = Math.max(maxDepth, 1 + findMaxDepth(nested.getList()));
            }
        }
        
        return maxDepth;
    }
    
    private int weightedSum(List<NestedInteger> list, int depth, int maxDepth) {
        int answer = 0;
        for (NestedInteger nested : list) {
            if (nested.isInteger()) {
                answer += nested.getInteger() * (maxDepth - depth + 1);
            } else {
                answer += weightedSum(nested.getList(), depth + 1, maxDepth);
            }
        }
        return answer;
    }
}

### Expected behavior

No idea how this test case got there

### Additional context

Can you also scratch my latest assessment as I was "failed" due to this bug?

**Comment by LC-Pam** [comment] 2023-11-17 19:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:07 UTC
Labels: Waiting for Reply

**Comment by DHRUV6029** [comment] 2024-02-23 19:44
I think the question, doesn't specify what do we consider empty lists , and depths are associated with Intergers , so in TC-26 empty list is not a level down.

We can keep a null or empty check in offical solution to make it work
```
class Solution {
    public int depthSumInverse(List<NestedInteger> nestedList) {
        int maxDepth = findMaxDepth(nestedList);
        return weightedSum(nestedList, 1, maxDepth);
    }

    private int findMaxDepth(List<NestedInteger> list) {
        int maxDepth = 1;
        
        for (NestedInteger nested : list) {
            if (!nested.isInteger()) {
                if(nested.getList().size()>0){
                maxDepth = Math.max(maxDepth, 1 + findMaxDepth(nested.getList()));
                }
            }
        }
        
        return maxDepth;
    }
    
    private int weightedSum(List<NestedInteger> list, int depth, int maxDepth) {
        int answer = 0;
        for (NestedInteger nested : list) {
            if (nested.isInteger()) {
                answer += nested.getInteger() * (maxDepth - depth + 1);
            } else {
                answer += weightedSum(nested.getList(), depth + 1, maxDepth);
            }
        }
        return answer;
    }
}
```
