### ISSUE TITLE
Missing Test Cases - Minimum Time to Visit a Cell In a Grid

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#12015] opened 2023-02-26 05:05 UTC
**FreeYourMind**

**Bug 类型**
- [x] 缺少测试用例

**描述**
Missing test case:
[[0,3,1,1,1],[1,127,1,127,1],[1,127,1,127,1],[1,1,1,127,1]]

**你提交或者运行的代码**
```
dirs4 = ((-1, 0), (1, 0), (0, -1), (0, 1))

class Solution:
    def minimumTime(self, G: List[List[int]]) -> int:
        m, n = len(G), len(G[0])
        if G[0][1] > 1 and G[1][0] > 1:
            return -1
        
        class B:
            def __getitem__(self, t):
                t <<= 1
                q = deque([(0, 0, t)])
                seen = {(0, 0)}
                while q:
                    i, j, cur = q.popleft()
                    for u, v in dirs4:
                        x, y = i + u, j + v
                        if not (0 <= x < m and 0 <= y < n) or (x, y) in seen or cur + 1 < G[x][y]:
                            continue
                        if (x, y) == (m - 1, n - 1):
                            return True
                        seen.add((x, y))
                        q.append((x, y, cur + 1))
                return False
        
        t = bisect_left(B(), True, 0, 50000) * 2

        q = deque([(0, 0, t)])
        seen = {(0, 0)}
        while q:
            i, j, cur = q.popleft()
            for u, v in dirs4:
                x, y = i + u, j + v
                if not (0 <= x < m and 0 <= y < n) or (x, y) in seen or cur + 1 < G[x][y]:
                    continue
                if (x, y) == (m - 1, n - 1):
                    return cur + 1
                seen.add((x, y))
                q.append((x, y, cur + 1))
```

**期望行为**
The correct answer is 9, but the code above passed all tests got 13.

**屏幕截图**
![image](https://user-images.githubusercontent.com/6801919/221393367-3220ef86-d1ba-44bc-b2d2-9198bac3f504.png)

**Comment by LC-Pam** [comment] 2023-02-27 22:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by zouyu9631** [comment] 2023-02-28 05:02
https://leetcode.cn/submissions/detail/406343787/

**Comment by LC-Pam** [comment] 2023-03-02 19:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link on  you LCUS account since we cannot open LCCN account submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-07 18:38
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-07 18:38 UTC
Labels: LCUS, problem
