### ISSUE TITLE
Integer to Roman

### ISSUE THREAD

**Issue by dclechok** [LeetCode-Feedback/LeetCode-Feedback#2339] opened 2021-02-11 01:14 UTC
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
/**
 * @param {number} num
 * @return {string}
 */

var buildingRomanNumeral = [];

var intToRoman = function(num) {
	let numberArray = [num];
	let numberArrayOfChars = [];

    numberArrayOfChars = numberArray.toString().split('');

	//sort each place for thousands, hundreds, tens (doubles), and ones (singles)
	if(numberArrayOfChars.length === 4) {
		sortThousands(numberArrayOfChars);
		numberArrayOfChars = numberArrayOfChars.slice(1, numberArrayOfChars.length);
	}
	if(numberArrayOfChars.length === 3) {
		sortHundreds(numberArrayOfChars);
		numberArrayOfChars = numberArrayOfChars.slice(1, numberArrayOfChars.length);
	}
	if(numberArrayOfChars.length === 2) {
		sortDoubles(numberArrayOfChars);
		numberArrayOfChars = numberArrayOfChars.slice(1, numberArrayOfChars.length);
	}
	if(numberArrayOfChars.length === 1) {
		sortSingles(numberArrayOfChars);
		numberArrayOfChars = numberArrayOfChars.slice(1, numberArrayOfChars.length);
	}
    
    return buildingRomanNumeral.join('');
};


function sortSingles(numArray){ //ones
	//console.log('sorting singles - first digit' + numArray[0]);
	if(numArray[0] == 1){buildingRomanNumeral.push('I');}
	else if(numArray[0] == 2){buildingRomanNumeral.push('II');}
	else if(numArray[0] == 3){buildingRomanNumeral.push('III');}
	else if(numArray[0] == 4){buildingRomanNumeral.push('IV');}
	else if(numArray[0] == 5){buildingRomanNumeral.push('V');}
	else if(numArray[0] == 6){buildingRomanNumeral.push('VI');}
	else if(numArray[0] == 7){buildingRomanNumeral.push('VII');}
	else if(numArray[0] == 8){buildingRomanNumeral.push('VIII');}
	else if(numArray[0] == 9){buildingRomanNumeral.push('IX');}
	//console.log(buildingRomanNumeral);
}

function sortDoubles(numArray){ //tens
	//console.log('sorting doubles - first digit ' + numArray[0]);
	if(numArray[0] == 1){buildingRomanNumeral.push('X');}
	else if(numArray[0] == 2){buildingRomanNumeral.push('XX');}
	else if(numArray[0] == 3){buildingRomanNumeral.push('XXX');}
	else if(numArray[0] == 4){buildingRomanNumeral.push('XL');}
	else if(numArray[0] == 5){buildingRomanNumeral.push('L');}
	else if(numArray[0] == 6){buildingRomanNumeral.push('LX');}
	else if(numArray[0] == 7){buildingRomanNumeral.push('LXX');}
	else if(numArray[0] == 8){buildingRomanNumeral.push('LXXX');}
	else if(numArray[0] == 9){buildingRomanNumeral.push('XC');}
	//console.log(buildingRomanNumeral);
}

function sortHundreds(numArray){ //hundreds
	//console.log('sorting hundreds - first digit ' + numArray[0]);
	if(numArray[0] == 1){buildingRomanNumeral.push('C');}
	else if(numArray[0] == 2){buildingRomanNumeral.push('CC');}
	else if(numArray[0] == 3){buildingRomanNumeral.push('CCC');}
	else if(numArray[0] == 4){buildingRomanNumeral.push('CD');}
	else if(numArray[0] == 5){buildingRomanNumeral.push('D');}
	else if(numArray[0] == 6){buildingRomanNumeral.push('DC');}
	else if(numArray[0] == 7){buildingRomanNumeral.push('DCC');}
	else if(numArray[0] == 8){buildingRomanNumeral.push('DCCC');}
	else if(numArray[0] == 9){buildingRomanNumeral.push('CM');}
	//console.log(buildingRomanNumeral);
}

function sortThousands(numArray){ //thousands
	//console.log('sorting thousands - first digit ' + numArray[0]);
	for(let c = 1; c <= Number(numArray[0]); c++){
		buildingRomanNumeral.push('M');
	}
}
```

**Comment by lc-kay** [comment] 2021-02-11 19:25
@dclechok What content-related issue are you trying to report? If you are posting your solution for other users to see, please do so on the discuss tab of the problem. Thank you for your time.

**Comment by dclechok** [comment] 2021-02-11 20:50
I'm trying to find help resolving what I feel is a bug.  Apparently I didn't fill out the form the correct way, which I apologize.  I'm still very new to this.  

When I run this code, it comes back and tests perfect with any test cases...then I go to submit it, and I get marked 'wrong answer' with a result that doesn't seem to make sense to me, and didn't show to be the case in multiple IDE's I tested the code in.

If the input is a 4, under every circumstance I've tested it under (including on leetcode) it comes back "IV".  However, when I submit it it says wrong answer and says the result is 'IIIIV' which makes no sense to me.  Sorry, still new to all of this.

**Comment by stormsunshine** [comment] 2021-02-12 01:56
@dclechok Please try this solution.
Add the following statement as the first statement in function `intToRoman`:
```
buildingRomanNumeral = [];
```
The problem is that `buildingRomanNumeral` is used for all test cases. After one test case is executed, `buildingRomanNumeral` is not cleared and therefore all the elements in `buildingRomanNumeral` are joined.
If you use a global variable, remember to clear the content of the global variable before executing a new test case.

**Comment by dclechok** [comment] 2021-02-12 01:57
Ahh!  Thank you so much!

**Comment by lc-kay** [comment] 2021-02-12 18:40
@dclechok I'm glad to see that another LeetCoder was able to assist you. I will close this ticket now. Thank you for your time!

**Closed by lc-kay** 2021-02-12 18:40 UTC
Labels: LCUS, watchlist
