### ISSUE TITLE
Missing Test Case - 12. Integer to Roman

### ISSUE THREAD

**Issue by BhargavGembali** [LeetCode-Feedback/LeetCode-Feedback#17137] opened 2023-10-11 13:42 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ #16621 ]Missing Test Cases 

#### Code you used for Submit/Run operation

```
// INTEGER TO ROMAN
// PROBLEM 12
class Solution {
    public static int[] VALUES= {1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1};
    public static String[] Roman={"M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"};
    public String intToRoman(int num) {
        StringBuilder res= new StringBuilder();
        for(int i=0; i<VALUES.length; i++){
            while(num>=VALUES[i]){
                res.append(Roman[i]);
                num-=VALUES[i];
            }
        }
        return res.toString();
    }
}
```

#### Additional context
```
 I would request you to add a test case containing the value "3904" Some times there is an issue with this particular value so it would be better to add this testcase. 
```

**Comment by LC-Pam** [comment] 2023-10-11 16:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:58 UTC
Labels: Waiting for Reply

**Comment by BhargavGembali** [comment] 2023-10-18 17:05
### Hello @LC-Pam  , 
sorry for late reply I was having examination for the last 5 days. 
https://leetcode.com/problems/integer-to-roman/description/ 
here is the submission link.
Thank you for the work you do!
