### ISSUE TITLE
Input parameters change during execution in 88. Merge Sorted Array

### ISSUE THREAD

**Issue by IgorSuvorov** [LeetCode-Feedback/LeetCode-Feedback#10533] opened 2022-12-25 10:01 UTC
#### Category of the bug
- [ +] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I use while loop, after condition is no longer true, all variables - both declared before the loop and provided by the input are reset to zero.

#### Code you used for Submit/Run operation

```
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int p1 = 0;
        int p2 = 0;
        int i = 1;
        while (p1 < m) {
            System.out.println("i " + i);
            System.out.println("nums1.length " + nums1.length);
            System.out.println("nums2.length " + nums2.length);
            System.out.println("m " + m);
            System.out.println("n " + n);
            System.out.println("p1 " + n);
            System.out.println("p2 " + n);
            System.out.println("--------" );
            i++;
            if (nums1[p1] > nums2[p2]) {
                p2++;
            }
            p1++;
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

I expected the loop to just finish, because condition is no longer true, however it continues with reset value.

Input:
nums1 = [1,2,3,0,0,0]
m = 3
nums2 = [2,5,6]
n = 3

Actual output:
i 1
nums1.length 6
nums2.length 3
m 3
n 3
p1 3
p2 3
--------
i 2
nums1.length 6
nums2.length 3
m 3
n 3
p1 3
p2 3
--------
i 3
nums1.length 6
nums2.length 3
m 3
n 3
p1 3
p2 3
--------
i 1
nums1.length 1
nums2.length 0
m 1
n 0
p1 0
p2 0
--------

**Comment by nskybytskyi** [comment] 2022-12-25 15:30
What you see is a concatenated output of running your solution on multiple test cases, namely all examples.

**Comment by LC-Pam** [comment] 2022-12-26 19:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link.
Your code received Wrong Answer. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-28 20:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-28 20:45 UTC
Labels: LCUS, problem
