### ISSUE TITLE
I believe I should pass test case with extremely large input.

### ISSUE THREAD

**Issue by MConstantinoGuzman** [LeetCode-Feedback/LeetCode-Feedback#13567] opened 2023-05-19 18:58 UTC
Hello,

I was able to solve the problem, "Find All Numbers Disappeared in an Array" (under the "Arrays 101" section), in LeetCode with an overall time complexity of O(n) and space complexity of O(1). However, the extremely large input for my code exceeds my time limit. Considering the suggested and efficient time complexity is up to O(n) (with the recommended space efficiency being O(1)), I believe my code falls in the category of passing the any test case. I was hoping you could look into my code and see if it is worthy to pass the extremely large test case. Just copy and past my code (below) in the development environment and see what test case is causing this. Thank you.

Here is my code: 

import java.util.Arrays;
class Solution {
    public List<Integer> findDisappearedNumbers(int[] nums) {
        int n = nums.length;
        // Sort the array: O(nlogn)
        Arrays.sort(nums);   
        // Declare an array of type List
        List<Integer> newarr = new ArrayList<Integer>();
        
        int i = 0;
        int b = 1;
        // Insert only numbers that range from 1 to n and are not in nums: O(n)
        while (b <= n) {
            if (i == nums.length - 1 && nums[i] != b) {
                newarr.add(b);
                ++b;
                i = 0;
                continue;
            }
            else if (b == nums[i]) {
                ++b;
                i = 0;
                continue;
            }
            ++i;
        }
        
        return newarr;
        
    }
}

**Comment by LC-Pam** [comment] 2023-05-19 20:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-23 00:13
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-23 00:13 UTC
Labels: LCUS, problem
