### ISSUE TITLE
Array Lesson

### ISSUE THREAD

**Issue by PyProInitiate** [LeetCode-Feedback/LeetCode-Feedback#13062] opened 2023-04-20 22:05 UTC
#### Your LeetCode username
PyProInitiate

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It describes the array going up to 9, yet the answer shows it equaling to 10.

#### Code you used for Submit/Run operation
``
// Go through each of the Array indexes, from 0 to 9.
for (int i = 0; i < 10; i++) {
    // Access and print what's at the i'th index.
    System.out.println(squareNumbers[i]);
}

// Will print:
// 1
// 4
// 9
// 16
// 25
// 36
// 49
// 64
// 81
// 100
``

#### Expected behavior
It describes the array going up to 9, yet the answer shows it equaling to 10.
![Capture](https://user-images.githubusercontent.com/59515196/233497024-1e2b3216-4148-414d-a08c-bf6f49649894.PNG)

#### Screenshots

![Capture](https://user-images.githubusercontent.com/59515196/233497102-01f9016d-fdde-4b59-9cff-1d21d0f77e3e.PNG)

#### Additional context
Please update these lessons as soon as possible

**Comment by LC-Pam** [comment] 2023-04-21 19:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-24 18:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-24 18:16 UTC
Labels: LCUS, problem
