### ISSUE TITLE
Missing Test Case - 1186. Maximum Subarray Sum with One Deletion

### ISSUE THREAD

**Issue by SkanderSoltani** [LeetCode-Feedback/LeetCode-Feedback#17340] opened 2023-10-20 01:34 UTC
#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

How can the solution to this test case [8,-1,6,-7,-4,5,-4,7,-6]  be 17?
there are four positive numbers [8,6,5,7] no sum combination will give the number 17. 

The solution here should be 14.  

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-10-20 20:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-23 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-23 19:08 UTC
Labels: Waiting for Reply
