### ISSUE TITLE
Tab size is not saved.

### ISSUE THREAD

**Issue by DcXiaoBing** [LeetCode-Feedback/LeetCode-Feedback#10488] opened 2022-12-23 00:11 UTC
I prefer to set the tab size to 2 space.
But when I restart the browser, the tab size is reset to 4 space (although the value in setting is still 2 spaces.)

**Comment by LC-Pam** [comment] 2022-12-23 18:36
Hi @,
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The screenshot of the issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-26 18:08
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-26 18:08 UTC
Labels: LCUS

**Comment by DcXiaoBing** [comment] 2023-02-24 19:58
https://youtu.be/40bA7iSPElE

This is a video for reproduce steps.
This is a main blocker for me to use the new question page.
