### ISSUE TITLE
how can this code not work and its showing me error for this testcase: Input: [9,9,9,9,9,9,9,9,9,9] 1 Output: [1,4,1,0,0,6,5,4,0,8] Expected: [1,0,0,0,0,0,0,0,0,0,0]

### ISSUE THREAD

**Issue by Shubhamkumarhub** [LeetCode-Feedback/LeetCode-Feedback#17356] opened 2023-10-20 17:07 UTC
class Solution {
    public List<Integer> addToArrayForm(int[] num, int k) {
        int comb_num=0;
        int i=0;
        ArrayList<Integer> list=new ArrayList<>();
       /*Here i am combining the digits from array to a number
        while(i<num.length){
            comb_num=(comb_num*10)+num[i];
            i++;
        }
      //Here i am adding the number k
        comb_num=comb_num+k;
     //After adding the number,i am seperating the digits and pushing in the list and in correct order.
        while(comb_num>0){
            int digit=comb_num%10;
            list.add(0,digit);
            comb_num=comb_num/10;
        }
    return list;
    }
}

**Comment by LC-Pam** [comment] 2023-10-20 20:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-23 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-23 19:08 UTC
Labels: Waiting for Reply
