### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by urielraz** [LeetCode-Feedback/LeetCode-Feedback#14910] opened 2023-07-20 22:04 UTC
#### Your LeetCode username
1urielraz

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
When I solve it in the way that seems the simplest, which is: for inside for, I encounter an error when I want to insert in the second for: i+1.
But somehow when I do I+1 in the second for it does give a good result.

#### Code you used for Submit/Run operation

function twoSum(nums: number[], target: number): number[] {
  for(let i=0; i<=nums.length; i++){
    for(let j=nums[i+1]; j<=nums.length; j++){
      if(nums[i]+nums[j]==target){
        return[i,j]
      }
    }
  }
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
TypeScript

**Comment by LC-Pam** [comment] 2023-07-21 19:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-25 21:24
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-25 21:24 UTC
Labels: LCUS, problem, Waiting for Reply
