### ISSUE TITLE
Wrong Test Case - 2035. Partition Array Into Two Arrays to Minimize Sum Difference

### ISSUE THREAD

**Issue by yatharth-1504** [LeetCode-Feedback/LeetCode-Feedback#14503] opened 2023-07-02 19:04 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int minimumDifference(vector<int>& nums) {
        int n = nums.size();
        // handling edge conditions
        int _min = *min_element(nums.begin(), nums.end());
        if (_min < 0){
            for (int i = 0; i < n; i++) nums[i] -= _min; 
        }

        int sum = accumulate(nums.begin(), nums.end(), 0);
        vector<vector<bool>> dp(n, vector<bool>(sum  + 1, false));
        for (int i = 0; i < n; i++) dp[i][0] = 1;
        for (int i = 1; i < n; i++){
            for (int target = 0; target <= sum; target++){
                bool notPick = dp[i - 1][target];
                bool pick = false;
                if (target - nums[i] >= 0) pick = dp[i - 1][target - nums[i]];
                dp[i][target] = pick | notPick; 
            }
        }
        int ans = INT_MAX;
        for (int i = 0; i <= sum; i++) {
            if (dp[n - 1][i]) ans = min(ans, abs(i - (sum - i)));
        }
        return ans;
    }
};
```

**Comment by LC-Pam** [comment] 2023-07-03 20:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:21
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:21 UTC
Labels: LCUS, problem
