### ISSUE TITLE
88. Merge Sorted Array test case does not match description 

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#14451] opened 2023-06-30 13:20 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

the test case has m = 0 while n = 1, this `m<n` is not inline with the description in the question:

          The final sorted array should not be returned by the function, but instead be stored inside the array nums1. 
          To accommodate this, nums1 has a length of `m + n`, where the first m elements denote the elements that should be merged, 
          and the last n elements are set to 0 and should be ignored. nums2 has a length of n.

this implies, the first 0 element should be merged, i.e. when m is 0, no element shall be mored, 
thus, the expect answer shall be [0]

#### Screenshots

<img width="1397" alt="Screenshot 2023-06-30 at 16 11 16" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1387249/0739aa70-a57c-45bf-9bc3-89fa49860af4">

**Comment by LC-Pam** [comment] 2023-07-03 19:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:10 UTC
Labels: LCUS, problem
