### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by Suhani-Lalla** [LeetCode-Feedback/LeetCode-Feedback#16892] opened 2023-10-03 10:14 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

there is no test case provided where the target is the last element in the array after rotating

#### Code you used for Submit/Run operation

```
int search(int* nums, int numsSize, int target){
int left = 0;
    int right = numsSize - 1;

    while (left <= right) {
        int mid = left + (right - left) / 2;

        if (nums[mid] == target) {
            return mid;
        }

        // Check which part of the array is sorted
        if (nums[left] <= nums[mid]) {
            // The left half is sorted
            if (nums[left] <= target && target < nums[mid]) {
                // Target is in the left half
                right = mid - 1;
            } else 0{
                // Target is in the right half
                left = mid + 1;
            }
        } else {
            // The right half is sorted
            if (nums[mid] < target && target <= nums[right]) {
                // Target is in the right half
                left = mid + 1;
            } else {
                // Target is in the left half
                right = mid - 1;
            }
        }
    }

    return -1; // Target not found
}

```

#### Language used for code

C

#### Expected behavior

this code does not work for the case in which target is the last element in the array, but all test cases where accepted while it should not have been the case

**Comment by LC-Pam** [comment] 2023-10-03 20:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:32
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:32 UTC
Labels: Waiting for Reply
