### ISSUE TITLE
392. Is Subsequence

### ISSUE THREAD

**Issue by alexandrehsantos** [LeetCode-Feedback/LeetCode-Feedback#13570] opened 2023-05-19 23:59 UTC
I think that test case 17 is wrong because if you put all letters of t in a Java HashSet for example, you will get only these characters eyl. The string in s is leeeeetcode, so it's impossible to write s in t if not all necessary characters are present. 

#### Your LeetCode username
[alexandrehsantos](https://leetcode.com/alexandrehsantos/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I think that test case 17 is wrong because if you put all letters of t in a Java HashSet for example, you will get only these characters eyl. The string in s is leeeeetcode, so it's impossible to write s in t if not all necessary characters are present. 

#### Code you used for Submit/Run operation

```
 public boolean isSubsequence(String s, String t) {
         Set<String> countOcurrences = new HashSet<>();
        String[] sString = s.split("");
        String[] tString = t.split("");
        int lastFountIndex = 0;
        for (int i = 0; i < s.length(); i++) {
            for (int j = 0; j < t.length(); j++) {
                if (sString[i].equals(tString[j]) && (j >= i)) {
                    if (lastFountIndex > j) {
                        continue;
                    }
                    countOcurrences.add(tString[j]);
                    lastFountIndex = j;
                }
            }
        }

        if (countOcurrences.size() == s.length()) {
            return true;
        }
        return false;
    }
```

#### Language used for code
Java

#### Expected behavior
In my opinion, the expected behavior is to return false for this test case. 

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8659462/21a242c6-a297-479b-863e-e586d02d2e8f)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8659462/e926a5a9-746e-41c3-b7f6-d5b068630e3c)

#### Additional context
Here are the two strings in the test case. 
```
s="leeeeetcode"
t="yyyyylyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy...

````

**Comment by LC-Pam** [comment] 2023-05-23 00:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-26 19:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-26 19:46 UTC
Labels: LCUS, problem

**Comment by alexandrehsantos** [comment] 2023-05-26 19:54
> Since we have not heard from you for a while, we will close this ticket now.
> 
> If you have any new information to share with us, please don't hesitate to share them here with us.
> 
> Thank you again for your support and understanding.

I'm sorry. I saw your response only today. 

Here is the link to the submitted code.

**Comment by alexandrehsantos** [comment] 2023-05-26 19:54
https://leetcode.com/submissions/detail/953018333/
