### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by MUNEERWANI** [LeetCode-Feedback/LeetCode-Feedback#14993] opened 2023-07-24 12:05 UTC
#### Your LeetCode username

/**
 * @param {number[]} nums
 * @param {number} k
 * @return {void} Do not return anything, modify nums in-place instead.
 */
var rotate = function(nums, k) {
    //let arr=[];
    if (nums.length===0||k===0) return null
    let n=nums.length;
    k=k%n;
    for(let i=0;i<k;i++){
        nums.unshift(nums.pop());
    }
    //console.log(nums)
    //  for(let i=0;i<n-k;i++){
    //     let j=n-k;
    //     nums[j++]=nums[i]
    // }
    // console.log(arr)
    
};

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-07-25 22:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:18
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:18 UTC
Labels: LCUS, problem, Waiting for Reply
