### ISSUE TITLE
Missing Test Case - 2073. Time Needed to Buy Tickets

### ISSUE THREAD

**Issue by Harsha335** [LeetCode-Feedback/LeetCode-Feedback#13575] opened 2023-05-20 05:51 UTC
#### Category of the bug
- [Missing Test Case - 2073. Time Needed to Buy Tickets ] Question
- [ class Solution {
    public int timeRequiredToBuy(int[] tickets, int k) {
     Queue<Integer> q=new LinkedList<>();
     for(int i=0;i<tickets.length;i++){
         q.add(i);
     }   
     int count=0;
     while(!q.isEmpty()){
         int x=q.poll();
            tickets[x]-=1;
        count+=1;
         if(tickets[k]==0){
             return count;
         }
        if(tickets[x]!=0)
            q.add(x);
     }
     return -1;
    }
}] Solution
- [JAVA ] Language
- [ 1 1 1 1 10 1 1 1 1 1 1 1 1 1 1 11 18 1 1 1 1 1 1 19 1 1 1
- k=16] Missing Test Cases

**Comment by LC-Pam** [comment] 2023-05-23 00:19
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-26 19:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-26 19:46 UTC
Labels: LCUS, problem
