### ISSUE TITLE
Missing Test Case - 151. Reverse Words in a String

### ISSUE THREAD

**Issue by Ishukumarpathak** [LeetCode-Feedback/LeetCode-Feedback#14969] opened 2023-07-23 08:50 UTC
class Solution {
public:
    string reverseWords(string s) {
        int n = s.size(),i=0;
        string ans = "";
        while(i<n){
            string temp = "";
            while(s[i]== ' '&& i<n)
                i++;
            while(s[i] != ' ' && i<n){
                temp += s[i];
                i++;
            }
            
            if(temp.size()>0){
                if(ans.size()== 0)
                    ans =temp;
                else
                    ans = temp+" "+ans;
            }
        }
         return ans;
    }
};

**Comment by LC-Pam** [comment] 2023-07-25 22:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:17 UTC
Labels: LCUS, problem, Waiting for Reply
