### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by heyitsshome** [LeetCode-Feedback/LeetCode-Feedback#17798] opened 2023-11-04 18:09 UTC
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

contributed a test case

#### Code you used for Submit/Run operation

```
class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        hashset=set()
        for s in nums:
            if s in hashset:
                return True
            hashset.add(s)
        
};
```

#### Language used for code

-Python 3

#### Expected behavior

test case 1 :
[2,3,4,5,5,6,7,8]
test case 2:
[8,9,7,5,4,3,2]
test case 3:
[66,656,890,789]

**Comment by LC-Pam** [comment] 2023-11-13 22:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:05 UTC
Labels: Waiting for Reply
