### ISSUE TITLE
2818. Apply Operations to Maximize Score

### ISSUE THREAD

**Issue by rip-nsk** [LeetCode-Feedback/LeetCode-Feedback#15541] opened 2023-08-13 04:49 UTC
#### Your LeetCode username
rip

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
1,1,1... 1 // 100'000 ones
1'000'000'000

**Comment by LC-Pam** [comment] 2023-08-14 17:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rip-nsk** [comment] 2023-08-14 19:43
accepted submission of at least 2 users:
https://leetcode.com/contest/weekly-contest-358/submissions/detail/1019751631/
https://leetcode.com/contest/weekly-contest-358/submissions/detail/1019802748/

**Comment by LC-Pam** [comment] 2023-08-18 19:43
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results.

The below code not received Accepted after submission:
https://leetcode.com/contest/weekly-contest-358/submissions/detail/1019751631/
https://leetcode.com/contest/weekly-contest-358/submissions/detail/1019802748/

This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.  It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Closed by LC-Pam** 2023-08-18 19:43 UTC
Labels: LCUS, problem, Waiting for Reply
