### ISSUE TITLE
658. Find K Closest Elements- Missing test case

### ISSUE THREAD

**Issue by xxiaomm** [LeetCode-Feedback/LeetCode-Feedback#8541] opened 2022-08-05 15:58 UTC
#### Your LeetCode username

Micca_Xx

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I submitted my solution and it was accepted. But I considered a test case and run it with my code, it gave the wrong result.  
So I think there must miss some test cases for this question.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> findClosestElements(int[] nums, int k, int x) {
        int l = 0, r = nums.length - 1;
        int minIndex = -1, min = Integer.MAX_VALUE;
        while (l <= r) {
            int mid = l + (r - l)/2;
            int abs = Math.abs(nums[mid] - x);
            if (nums[mid] == x) {
                minIndex = mid;
                min = 0;
                break;
            } else if (nums[mid] > x) 
                r = mid - 1;
            else
                l = mid + 1;
            if (abs < min) {
                min = abs;
                minIndex = mid;
            }    
        }
        
        List<Integer> res = new LinkedList<>();
        l = minIndex;
        r = minIndex+1;
        while (k > 0) {
            int abs1 = l >= 0 ? Math.abs(x - nums[l]) : Integer.MAX_VALUE;
            int abs2 = r < nums.length ? Math.abs(x - nums[r]) : Integer.MAX_VALUE;
            if (abs1 <= abs2)
                res.add(0, nums[l--]);
            else
                res.add(nums[r++]);
            k--;
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Add my test case and consider some corner cases.

**Comment by LC-Pam** [comment] 2022-08-08 18:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-09 17:46
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-09 17:46 UTC
Labels: LCUS, problem

**Comment by xxiaomm** [comment] 2022-08-09 21:32
[1,25,35,45,50,59]
1
30
