### ISSUE TITLE
1907. Count Salary Categories - Time Limit Exceeded with Empty Test Case for MS SQL

### ISSUE THREAD

**Issue by Boooke** [LeetCode-Feedback/LeetCode-Feedback#14098] opened 2023-06-13 21:04 UTC
#### Your LeetCode username
Boooke

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The following code for MS SQL will fail due to time limit. Looking further into the failing test case (11/11), it is seemingly empty.

#### Code you used for Submit/Run operation

```sql
SELECT 
    'Low Salary' AS category,
    COUNT(account_id) AS accounts_count
FROM 
    Accounts
WHERE
    income < 20000
UNION
SELECT 
    'Average Salary' AS category,
    COUNT(account_id) AS accounts_count
FROM 
    Accounts
WHERE
    income >= 20000
    AND
    income <= 50000
UNION
SELECT 
    'High Salary' AS category,
    COUNT(account_id) AS accounts_count
FROM 
    Accounts
WHERE
    income > 50000
```

#### Language used for code
MS SQL

#### Expected behavior
Success of test case and thus the problem.

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment] 2023-06-14 19:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case in json format: {"headers":{"Accounts":["account_id","income"]},"rows":{"Accounts":[[3,108939],[2,12747],[8,87709],[6,91796]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-19 19:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-19 19:56 UTC
Labels: LCUS, problem

**Comment by AgentIvan** [comment] 2023-08-17 20:29
It's still not resolved!!!
T-SQL is impossible to solve even with optimised solution
