### ISSUE TITLE
Missing Test Case - 1009. Complement of Base 10 Integer

### ISSUE THREAD

**Issue by agrawalakshat108** [LeetCode-Feedback/LeetCode-Feedback#16810] opened 2023-09-30 14:43 UTC
0

#### Your LeetCode username

akshat51

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There should be an extra test code(sample output) for the problem question. For n = 0, when input is zero.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-10-03 17:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:19 UTC
Labels: Waiting for Reply
