### ISSUE TITLE
wrong test case

### ISSUE THREAD

**Issue by Crysisun** [LeetCode-Feedback/LeetCode-Feedback#11250] opened 2023-01-25 00:54 UTC
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/find-closest-node-to-given-two-nodes
is this test case wrong? [4,4,8,-1,9,8,4,4,1,1] 5 6
I don't understand how it is possible that the answer node is 1 when the min distance is 5, 5->8->1<-9<-4<-6
but the node 4 has min distance 4, 5->8->1->4<-6

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Trance-0** [comment] 2023-01-25 04:51
Agree. I got the same concern.

**Comment by Trance-0** [comment] 2023-01-25 04:52
Test case 74 is incorrect. If the node2 wants to reach 1, it must pass from 4 -> 9 -> 1, which increases the distance from node2 by 2, making the solution not optimal. The answer for test case 74 should be 4.

**Comment by LC-Pam** [comment] 2023-01-25 18:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-27 18:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-27 18:57 UTC
Labels: LCUS, problem
