### ISSUE TITLE
digits[]=[1,3,4,9];Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by RatikaDogra** [LeetCode-Feedback/LeetCode-Feedback#13810] opened 2023-06-01 12:47 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by RatikaDogra** [comment] 2023-06-01 12:49
The code of maximum users runs and even gets accepted but i found a testcase for which the code doesnt work that efficiently.
the testcase is    digits[]=[2,3,4,9]

**Comment by LC-Pam** [comment] 2023-06-01 20:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:41 UTC
Labels: LCUS, problem
