### ISSUE TITLE
Missing Test Case - 901. Online Stock Span

### ISSUE THREAD

**Issue by shivangi806** [LeetCode-Feedback/LeetCode-Feedback#15955] opened 2023-08-27 10:19 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class StockSpanner {
public:
    stack<int> st;
    vector<int> v;
    int i=0;
    StockSpanner() {
        
    }
    int next(int price) {
        v.push_back(price);
        while(!st.empty() && v[st.top()]<=price){
            st.pop();
        }
        int ans =0;
        if(st.empty()) ans= i+1;
        else ans =  i-st.top();
        st.push(i++);
        return ans ;
    }
};
```

**Comment by LC-Pam** [comment] 2023-08-28 20:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:45 UTC
Labels: Waiting for Reply
