### ISSUE TITLE
Missing Test Case - 572. Subtree of Another Tree

### ISSUE THREAD

**Issue by faizanfayazmir1** [LeetCode-Feedback/LeetCode-Feedback#8046] opened 2022-07-06 11:31 UTC
class Solution:
    def isSubtree(self, s: Optional[TreeNode], t: Optional[TreeNode]) -> bool:
        if not t:
            return True
        if not s: 
            return False
        if self.sameTree(s, t): 
            return True
        return (self.isSubtree(s.left,t) or self.isSubtree(s.right, t))
        
    def sameTree(self, s, t):
        if not s and not t:
            return True
        if not s and not t and s.val == t.val:
            return (self.sameTree(s.left,t.left) and self.sameTree(s.right, t.right))
        return False

**Comment by LC-Pam** [comment] 2022-07-06 23:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
What is the missing test case and language?
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-11 19:47
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-11 19:47 UTC
Labels: LCUS, problem
