### ISSUE TITLE
Missing Test Case - 402. Remove K Digits

### ISSUE THREAD

**Issue by C16H22O4** [LeetCode-Feedback/LeetCode-Feedback#11763] opened 2023-02-15 11:27 UTC
#### Your LeetCode username
yeVegeTable

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√ ] Missing Test Cases 

#### Description of the bug

Just a hack test case.

#### Code you used for Submit/Run operation

```
The problem number: 402
class Solution {
public:
    string removeKdigits(string s, int k) {
        if(s.size() == k) return "0";
        for(int i = 0; i < k; i++) {
            int idx = 0;
            for(int j = 1; j < s.size() && s[j] >= s[j - 1]; j++) idx = j;
            s.erase(s.begin() + idx);
            while(s.size() > 1 && s[0] == '0') s.erase(s.begin());
        }
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Add the test case to system and rejudge it.

**Comment by C16H22O4** [comment] 2023-02-15 11:28
> #### Your LeetCode username
> yeVegeTable
> 
> #### Category of the bug
> * [ ]  Question
> * [ ]  Solution
> * [ ]  Language
> * [√ ] Missing Test Cases
> 
> #### Description of the bug
> Just a hack test case.
num="1000", k = 3
> 
> #### Code you used for Submit/Run operation
> ```
> The problem number: 402
> class Solution {
> public:
>     string removeKdigits(string s, int k) {
>         if(s.size() == k) return "0";
>         for(int i = 0; i < k; i++) {
>             int idx = 0;
>             for(int j = 1; j < s.size() && s[j] >= s[j - 1]; j++) idx = j;
>             s.erase(s.begin() + idx);
>             while(s.size() > 1 && s[0] == '0') s.erase(s.begin());
>         }
>         return s;
>     }
> };
> ```
> 
> #### Language used for code
> C++
> 
> #### Expected behavior
> Add the test case to system and rejudge it.
> 
> #### Screenshots
> #### Additional context

**Comment by LC-Pam** [comment] 2023-02-15 18:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-17 19:09
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-17 19:09 UTC
Labels: LCUS, problem
