### ISSUE TITLE
Missing Testcase : Problem Number 507. Perfect Number

### ISSUE THREAD

**Issue by Priyam-jain123** [LeetCode-Feedback/LeetCode-Feedback#13309] opened 2023-05-05 18:53 UTC
#### Your LeetCode username
Priyam_Jain1

#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

The last test case when you submit the problem is an empty input, i.e no input is provided when the expected return is boolean and the input is int. Also, no constraints are properly provided and the problem is stated as easy. No time constraints are properly given.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java,Python

**Comment by LC-Pam** [comment] 2023-05-05 19:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-08 21:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-08 21:07 UTC
Labels: LCUS, problem
