### ISSUE TITLE
Missing Test Case - 417. Pacific Atlantic Water Flow

### ISSUE THREAD

**Issue by SSnake234** [LeetCode-Feedback/LeetCode-Feedback#15533] opened 2023-08-12 14:48 UTC
#### Your LeetCode username

[SSnake234](https://leetcode.com/SSnake234/)

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug

In test case: heights = [[1,2,3],[8,9,4],[7,6,5]]
how [2,1] is the part of the answer? The number 6 cannot reach the Pacific Ocean

#### Code you used for Submit/Run operation

```
rows, cols = len(heights), len(heights[0])
        res = []
        
        def pacific(r, c):
            if r == 0 or c == 0:
                return True
            if (heights[r][c] < heights[r - 1][c] and
                heights[r][c] < heights[r][c - 1]):
                return False
            res = (pacific(r - 1, c) or pacific(r, c - 1))
            return res
        
        def atlantic(r, c):
            if r == rows - 1 or c == cols - 1:
                return True
            if (heights[r][c] < heights[r + 1][c] and
                heights[r][c] < heights[r][c + 1]):
                return False
            res = (atlantic(r + 1, c) or atlantic(r, c + 1))
            return res
        
        for r in range(rows):
            for c in range(cols):
                if pacific(r, c) and atlantic(r, c):
                    res.append((r, c))
        
        return res
```

#### Language used for code

Python

#### Expected behavior

In test case: heights = [[1,2,3],[8,9,4],[7,6,5]]
how [2,1] is the part of the answer? The number 6 cannot reach the Pacific Ocean

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125550603/3ceb2d97-ebca-4cd6-bac8-2f065e644bca)

**Comment by agrawalishaan** [comment] 2023-08-12 16:14
It can reach the ocean. It goes right, up, up.

**Comment by LC-Pam** [comment] 2023-08-15 19:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-18 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-18 19:41 UTC
Labels: Waiting for Reply
