### ISSUE TITLE
Missing Test Case - 2704. To Be Or Not To Be

### ISSUE THREAD

**Issue by thehuanxie** [LeetCode-Feedback/LeetCode-Feedback#15992] opened 2023-08-28 12:09 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a missing test case for ```expect(val).notToBe(val)```

#### Code you used for Submit/Run operation
``` () => expect(5).notToBe(5) ``` 

#### Language used for code
JavaScript

#### Expected behavior
Expected output:
`{"error":"Equal"}`

**Comment by LC-Pam** [comment] 2023-08-29 19:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:54
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:54 UTC
Labels: Waiting for Reply

**Comment by thehuanxie** [comment] 2023-08-31 18:02
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Sorry for missing the reply, here is the link: https://leetcode.com/problems/to-be-or-not-to-be/submissions/1034036968/?envType=study-plan-v2&envId=30-days-of-javascript
