### ISSUE TITLE
Missing Test Case - 286. Walls and Gates

### ISSUE THREAD

**Issue by tushar19892002** [LeetCode-Feedback/LeetCode-Feedback#2900] opened 2021-03-29 19:03 UTC
#### Your LeetCode username
tushar19892002

#### Category of the bug
- [ ] Test case with the dfs solution

#### Description of the bug

Following dfs solution is being passed by the test case

class Solution {
    
    public void wallsAndGates(int[][] rooms) {
        List<int[]> gates = new ArrayList<>();
        for (int x = 0; x < rooms.length; x++) {
            for (int y = 0; y < rooms[0].length; y++) {
                if(rooms[x][y]==0) dfs(x,y,rooms, 0);
            }
        }
    }

    public void dfs(int x, int y, int[][] rooms, int val){
        if(x<0 || y<0 || x>rooms.length-1 || y> rooms[0].length-1 || rooms[x][y] < val) return;
        rooms[x][y] = val;
        wallsAndGates(x+1, y, rooms, 1+val);
        wallsAndGates(x-1, y, rooms, 1+val);
        wallsAndGates(x, y+1, rooms, 1+val);
        wallsAndGates(x, y-1, rooms, 1+val);
    }
    
} 

#### Above solution can be easily failed by below test case. Time limit exceed

```
// Two Sum
public class WallsAndGatesTest {
    public static void main(String[] args) {
        new Solution().wallsAndGates(getRooms(20));
    }

    private static int[][] getRooms(int count) {
        int[][] rooms = new int[count][count];
        for (int i = 0; i < count; i++) {
            Arrays.fill(rooms[i], Integer.MAX_VALUE);
            for (int j = 0; j < count; j++) {
                if(i==j)rooms[i][j]=0;
            }
        }
        return rooms;
    }
}
```

#### Language used for code
Java

**Comment by riteshsangwan** [comment] 2021-03-30 11:47
Anyone from the admin verify this and if correct please add this test case to the question. The current top solution is DFS one and that is not correct.

**Comment by lc-kay** [comment] 2021-03-30 17:25
@riteshsangwan Please provide the test case in [[]] format, like the example test cases. Thank you!

**Comment by riteshsangwan** [comment] 2021-04-06 17:35
```
[[0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0]]
```

**Comment by tushar19892002** [comment] 2021-04-07 07:52
@riteshsangwan, thanks for the test case.

**Comment by lc-kay** [comment] 2021-04-07 18:37
@tushar19892002 Can you please provide the submission details link to your code? I am receiving Compile Error and cannot reproduce the issue. Thank you.

**Comment by lc-kay** [comment] 2021-04-15 22:00
Hi @tushar19892002 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Comment by tushar19892002** [comment] 2021-04-16 11:46
@lc-kay - Apologies for late response
here is the submission link
https://leetcode.com/submissions/detail/473818385/

**Comment by lc-kay** [comment] 2021-04-16 18:11
Hi @tushar19892002 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment] 2021-04-21 01:06
Hi @tushar19892002 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Closed by LC-Pamela** 2021-04-21 01:06 UTC
