### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by ashtkr01** [LeetCode-Feedback/LeetCode-Feedback#17323] opened 2023-10-19 05:43 UTC
#### Your LeetCode username

ashtkr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ C++] Language
- [ n = 7
-  leftChild = [1,-1,-1,0,3,4,-1] 
-  rightChild = [1,-1,-1,0,3,4,-1] ] Missing Test Cases 

#### Description of the bug
For the input given , My code is wrong but It has been accepted by the Leetcode as a valid solution.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    //Helper:
    bool helper(int node , list<int> *l , vector<bool> &visited){
        visited[node] = true;
        //Iterate:
        for(auto nbrs : l[node]){
            if(!visited[nbrs]){
                bool res = helper(nbrs , l , visited);
                if(!res){
                    //Return:
                    return false;
                }
            }
            else{
                //Return:
                return false;
            }
        }
        //Return  :
        return true;
    }
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        bool answer = false;
        list<int> *l = new list<int>[n];
        int cnt = 0;
        int root = -1;
        //Visited:
        vector<int> dp(n , 0);
        vector<bool> visited(n , false);
        //Iterate:
        for(int i=0;i<n;i++){
            int left = leftChild[i];
            int right = rightChild[i];
            if(left != -1){
                l[i].push_back(left);
                dp[left] = 1;
            }
            if(right != -1){
                l[i].push_back(right);
                dp[right] = 1;
            }
        }
        for(int i=0;i<n;i++){
            if(dp[i] == 0){
                root = i;
                cnt++;
            }
        }
        //Base Case :
        if(cnt != 1){
            //Return:
            return false;
        }
        //Call:
        answer = helper(0 , l , visited);
        //Return:
        return answer;
    }
};
```

#### Language used for code

C++

#### Expected behavior

"Our LeetCode solution should have been marked as incorrect according to the provided input, but it was mistakenly accepted by LeetCode."

**Comment by LC-Pam** [comment] 2023-10-19 17:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-23 19:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-23 19:07 UTC
Labels: Waiting for Reply
