### ISSUE TITLE
Missing Test Cases - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Krish-in-real** [LeetCode-Feedback/LeetCode-Feedback#13481] opened 2023-05-15 09:35 UTC
[[–2147483648,1,1],[1,0,1],[1,1,–2147483648 ]]

**Comment by Krish-in-real** [comment] 2023-05-15 09:35
[[-999,1,1],[1,0,1],[1,1,-999]]

**Comment by LC-Pam** [comment] 2023-05-16 00:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-19 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-19 19:41 UTC
Labels: LCUS, problem
