### ISSUE TITLE
Very few test cases

### ISSUE THREAD

**Issue by rahul97407** [LeetCode-Feedback/LeetCode-Feedback#1060] opened 2020-09-23 07:28 UTC
Sir,i solved a problem on leetcode.
Problem Name:928.Minimize Malware II
 I submitted a code and it got accepted.
But,when i gave my custom input test case,my answer is wrong.So this shows that you have provided very few test cases.

My Custom Input Test Case:
[[0,0,0,1,0],[0,0,0,1,0],[0,0,0,0,1],[1,1,0,0,0],[0,0,1,0,0]]
[3,2]

My Code:
`class Solution {
public:
    vector<vector<int>> g;
    vector<bool> vis;
    vector<bool> inf;
    int no_of_inf=0;
    int no_of_nodes=0;
    int ans=-1;
    int val=-1;
    int min_idx;
    
    void dfs(int src,vector<vector<int>>& graph)
    {
        if(vis[src])
         return;
        if(inf[src])
        {  min_idx=min(min_idx,src);  no_of_inf++;return;}
        no_of_nodes++;
        vis[src]=true;
        for(int i=0;i<graph.size();i++)
        {
            if(graph[src][i])
                dfs(i,graph);
        }
        
    }
    int minMalwareSpread(vector<vector<int>>& graph, vector<int>& initial) {
        int size=graph.size();ans=size;
        g.resize(size);
        vis.resize(size);
        inf.resize(size);
        for(auto i:initial)
        {
            inf[i]=true;
        }
        for(int i=0;i<size;i++)
        {
            no_of_nodes=0;
            no_of_inf=0;
            min_idx=size;
            if(inf[i])
                continue;
            
            dfs(i,graph);
            if(no_of_inf>1)
                ;
            else if(no_of_inf==1)
            {
                if(no_of_nodes>val)
                {val=no_of_nodes;ans=min_idx;}
                else if(no_of_nodes==val)
                {ans=min(ans,min_idx);}
            }
        }
        if(ans==size)
        {
            int mn=size;
            for(auto i:initial)
            {mn=min(mn,i);}
            ans=mn;
        }
        return ans;
        
        
                   
    }
};`

**Comment by lc-kay** [comment] 2020-09-25 23:05
Hi @rahul97407, 

Please share a minimal reproducible example on https://leetcode.com/playground/new/empty to help us read your code and verify it. Thank you!

**Comment by lc-kay** [comment] 2020-10-07 00:19
Hi @rahul97407 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2020-10-07 00:19 UTC
Labels: LCUS, problem, watchlist
