### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Akhileshsingh994** [LeetCode-Feedback/LeetCode-Feedback#11016] opened 2023-01-14 05:48 UTC
#### Your LeetCode username
Akhilesh_singh

#### Category of the bug
Test case error

#### Description of the bug

In the response of a question i was tring to find length of string with my test case
I entered a string which it is not taking showing error it is not format of string
I had attached screenshot 

#### Code you used for Submit/Run operation

```
#include<iostream>
#include<string>

using namespace std;

int main()
    {
    string a;
    int len;
    cin>>a;
    len=strlen(a);
    cout<<len;
    return 0;
    }
```

#### Language used for code
 C++ 

#### Expected behavior

It should take string as input and gives length of string as output

#### Screenshots

![Screenshot_20230114_111111_Chrome.jpg](https://user-images.githubusercontent.com/103052539/212457927-010df74c-faba-4e4d-876e-db4114e4111a.jpg)

**Comment by LC-Pam** [comment] 2023-01-16 19:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link.
We received Compile Error when we submit your above code.
https://leetcode.com/submissions/detail/879424818/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-18 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-18 18:30 UTC
Labels: LCUS, problem
