### ISSUE TITLE
Wrong complexity analysis on LeetCode's Interview Crash Course

### ISSUE THREAD

**Issue by abannura** [LeetCode-Feedback/LeetCode-Feedback#16356] opened 2023-09-11 18:29 UTC
#### Your LeetCode username
anbasch

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It's not really about a question, but a explanatory text within "LeetCode's Interview Crash Course - Data Structures and Algorithms". Particularly on a new chapter that was added about Dijkstra.

It says: "There are O(V) pop operations and O(E) push operations.", when in reality, given the implementation shown, there are O(E) pop operations too. 

Additionally, it says: "The space complexity is O(V) for the heap and distances.", which is not true, as the space used by the heap is O(E) (in that particular implementation).

#### Screenshots
<img width="853" alt="Screenshot 2023-09-11 at 3 28 06 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20782578/14d5db86-3fe3-4a4b-98ae-378e8d7b54a9">

**Comment by LC-Pam** [comment] 2023-09-11 20:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-15 15:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-15 15:08 UTC
Labels: Waiting for Reply

**Comment by abannura** [comment] 2023-10-11 14:06
Sorry about the delay. Didn't get notified about your response. The link is: https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/714/bonus/4841/
