### ISSUE TITLE
Missing Test Case - 180. Consecutive Numbers

### ISSUE THREAD

**Issue by jnandeepdevsarma** [LeetCode-Feedback/LeetCode-Feedback#12690] opened 2023-04-01 12:16 UTC
jnandeepdevsarma

#### Category of the bug
Write an SQL query to find all numbers that appear at least n-th times consecutively.

Return the result table in any order.

Input: 

number of appearance 3
Logs table:
+----+-----+
| id | num |
+----+-----+
| 1  | 1   |
| 2  | 1   |
| 3  | 1   |
| 4  | 2   |
| 5  | 5   |
| 6  | 5   |
| 7  | 5   |
| 8  | 5   |
+----+-----+
Output: 
+-----------------+
| ConsecutiveNums |
+-----------------+
| 1               |
+-----------------+

+-----------------+
| ConsecutiveNums |
+-----------------+
| 5              |
+-----------------+
Explanation: 1 is the only number that appears consecutively for at least three times.

Language sql ,mssql

If number of appearance change it should work fine 

Here is my Solution in mssql
-----------------------------------------------------------------
DECLARE @I INT=1;
DECLARE @num INT;
DECLARE @negnum INT;
DECLARE @COUNT INT=0;
DECLARE @MAX INT;
DECLARE @COUNTER INT=0;
DECLARE @TOTALCOUNT INT=3;
SET @MAX=(select max(id) from Logs)

IF( @MAX>1)
BEGIN
    WHILE(@I<=@MAX)
    BEGIN
        IF(@I>1)
        BEGIN
            SET @num=(SELECT num from Logs
                    WHERE id=@I)

            SET @negnum=( SELECT num from Logs
                        WHERE id=@I-1)
            
            IF(@num=@negnum )
            BEGIN
                SET @COUNT= @COUNT+1
            END

            IF(@num!=@negnum OR @I=@MAX)
            BEGIN
                IF(@COUNT>0)
                BEGIN
                    SET @COUNT= @COUNT+1
                END
                IF(@COUNT>=@TOTALCOUNT)
                BEGIN
                    SELECT  @negnum AS ConsecutiveNums
                    SET @COUNTER=@COUNTER+1
                END
                SET @COUNT= 0
            END
        END
        

        SET @I=@I+1

    END
END
IF(@COUNTER=0)
BEGIN
    SELECT num AS ConsecutiveNums
    FROM Logs
    WHERE @COUNT>=@TOTALCOUNT
END

-----------------------------------------------------------------

**Comment by LC-Pam** [comment] 2023-04-01 16:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case in json format like this:
{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,8,"1970-01-01",0],[2,9,"1970-01-01",0]]}}


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by jnandeepdevsarma** [comment] 2023-04-01 16:21
here is the json test case that ultimately lead to crash

{"headers": {"Logs": ["id", "num"]}, "rows": {"Logs": [[1, 9], [2, 9], [3,
9], [4, 8], [5, 8], [6, 8]]}}

My solution for the problem is :

DECLARE @I INT=1;DECLARE @num INT;DECLARE @negnum INT;DECLARE @COUNT
INT=0;DECLARE @MAX INT;DECLARE @COUNTER INT=0;DECLARE @TOTALCOUNT
INT=3;SET @MAX=(select max(id) from Logs)IF( @MAX>1)BEGIN
***@***.******@***.***)    BEGIN        ***@***.***>1)        BEGIN            SET
@num=(SELECT num from Logs                    WHERE ***@***.***)
SET @negnum=( SELECT num from Logs                        WHERE
***@***.***)                        ***@***.******@***.*** )            BEGIN
           SET @COUNT= @COUNT+1            END
***@***.******@***.*** OR @***@***.***)            BEGIN
***@***.***>0)                BEGIN                    SET @COUNT=
@COUNT+1                END                ***@***.***>***@***.***)
           BEGIN                    SELECT  @negnum AS ConsecutiveNums
                   SET @***@***.***+1                END
      SET @COUNT= 0            END        END                SET
@***@***.***+1    ***@***.***=0)BEGIN    SELECT num AS ConsecutiveNums
  FROM Logs    WHERE @***@***.***

**Comment by LC-Pam** [comment] 2023-04-05 18:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-10 22:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-10 22:19 UTC
Labels: LCUS, problem
