### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by mudassiransari12** [LeetCode-Feedback/LeetCode-Feedback#9598] opened 2022-10-24 02:47 UTC
class Solution {
public:
    int climbStairs(int n) {
    if(n<=2)
            return n;
          
            int prev1=2;
            int prev2=1;
            int ans;
           for(int i=3; i<=n; i++){
              ans=prev1+prev2;
                   prev2=prev1;
                   prev1=ans;
                   
           }
         return ans;   
            
    }
};
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-10-24 18:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 16:02
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 16:02 UTC
Labels: LCUS, problem
