### ISSUE TITLE
443 - String compression, Python test runner behaves odd

### ISSUE THREAD

**Issue by anand2312** [LeetCode-Feedback/LeetCode-Feedback#12104] opened 2023-03-02 17:24 UTC
#### Your LeetCode username
anand2312

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

A Python solution that runs and gives the right output for the sample testcases on my machine is rejected by the test runner.
It seems to be running the compress function multiple times on a single input, which ends up screwing with the output.

#### Code you used for Submit/Run operation

```
class Solution:
    def compress(self, chars):
        print("Function called!")
        i, j, p = 0, 0, 0
        n = len(chars)
        while j != n:
            if chars[i] == chars[j]:
                print(f"equal - {i=} {j=} {p=}")
                j += 1
                print(f"j incremented - {j=}")
            else:
                count = j - i
                if count == 1:
                    i = j
                    j += 1
                    p += 1
                    continue
                chars[p] = chars[i]
                p += 1
                for ch in str(count):
                    chars[p] = ch
                    p += 1
                print(f"{count=} {p=} {chars[i]=}")
                print(chars)
                i = j
                j += 1
                print(f"{i=} {j=} {p=}")
        else:
            count = j - i
            chars[p] = chars[i]
            p += 1
            for ch in str(count):
                chars[p] = ch
                p += 1
            return p
```
Running this code on the problem, we can see that the "Function called!" print runs twice for the same output,
hence messing up the result.

#### Language used for code

Python

#### Expected behavior

The test runner is sane and runs the function only once per input.

**Comment by LC-Pam** [comment] 2023-03-02 20:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The test case that you use. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-03 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-03 19:45 UTC
Labels: LCUS, problem

**Comment by anand2312** [comment] 2023-03-06 12:46
@LC-Pam sorry for the delay, I was a bit busy

The submission link - https://leetcode.com/problems/string-compression/submissions/910150451/
Test cases - it fails the sample cases given in the problem description

**Comment by anand2312** [comment] 2023-03-09 11:12
@LC-Pam any updated?
