### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by raghuaanand** [LeetCode-Feedback/LeetCode-Feedback#13243] opened 2023-05-01 17:58 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    double average(vector<int>& salary) {
        float minSal = *std::min_element(begin(salary), end(salary));
        float maxSal = *std::max_element(begin(salary), end(salary));

        float sum = 0;
        for(int i = 0; i<salary.size(); i++){
            sum = sum + salary[i];
        }
        float finalSum = sum - minSal - maxSal;
        float average = finalSum/(salary.size() - 2);
        return average;
    }
};
```

**Comment by LC-Pam** [comment] 2023-05-02 22:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-04 19:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-04 19:27 UTC
Labels: LCUS, problem
