### ISSUE TITLE
Missing Test Case - 850. Rectangle Area II

### ISSUE THREAD

**Issue by Justin-YimYim** [LeetCode-Feedback/LeetCode-Feedback#10712] opened 2023-01-03 03:57 UTC
#### Your LeetCode username

[doppelgangerOfMeow](https://leetcode.com/doppelgangerOfMeow/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Suppose x1 could equal x2, which means there is no rectangle drawn but is an allowed input. However, there is no results for this case. 

#### Screenshots

<img width="659" alt="Screenshot 2023-01-03 at 11 56 07" src="https://user-images.githubusercontent.com/55522706/210298227-ead1951b-c566-497f-b69e-fa8a08cacb38.png">
<img width="659" alt="Screenshot 2023-01-03 at 11 56 26" src="https://user-images.githubusercontent.com/55522706/210298250-9f3bd13b-2eaa-4dbf-90f8-2383c03d1702.png">

**Comment by LC-Pam** [comment] 2023-01-04 03:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-07 15:32
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-07 15:32 UTC
Labels: LCUS, problem
