### ISSUE TITLE
Missing Test Case - 1909. Remove One Element to Make the Array Strictly Increasing 

### ISSUE THREAD

**Issue by Anurag7752** [LeetCode-Feedback/LeetCode-Feedback#17529] opened 2023-10-26 19:44 UTC
class Solution {
public:
    bool canBeIncreasing(vector<int>& arr) {
        int f = 1, prev = arr [0];
        for(int i = 1; i<arr.size();i++){
            if(arr[i]<=prev){
                if(!f) return false;
                if(i>=2){
                    if(arr[i-2]<arr[i]) prev = arr[i];
                    else prev = arr[i-1];
                }
                else if(i<arr.size()-1 && arr[i]<arr[i+1]) prev = arr[i];
                else prev = arr[i];
                f = 0;

            }
            else prev = arr[i];

        } 
        
        return true;
    }
};

**Comment by Anurag7752** [comment] 2023-10-26 19:50
Very Easy fixed question #17529

**Comment by LC-Pam** [comment] 2023-10-27 19:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:00 UTC
Labels: Waiting for Reply
