### ISSUE TITLE
Missing Test Case - 2855. Minimum Right Shifts to Sort the Array

### ISSUE THREAD

**Issue by nikhilsharma-github** [LeetCode-Feedback/LeetCode-Feedback#16473] opened 2023-09-17 04:31 UTC
#### Your LeetCode username

NikhilSharma_LC

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug

TestCase Bug.
Missing Testcase.

#### Code you used for Submit/Run operation

```
// [2855. Minimum Right Shifts to Sort the Array]
class Solution {
public:
    int minimumRightShifts(vector<int>& nums) {
        int maxval=INT_MIN,minval=INT_MAX,n=nums.size(),rsc=0,rsi=-1,cmax=INT_MIN;
        for(int v:nums){
            maxval=max(maxval,v);
            minval=min(minval,v);
        }
        for(int i=1;i<n;i++){
            if(nums[i-1]>nums[i]){
                rsc++;
            }
        }
        if(rsc==0)
            return 0;
        
        for(int i=1;i<n;i++){
            if(nums[i-1]>nums[i]){
                rsi=i;
                cmax=nums[i-1];
            }
        }
        
        if(rsc<=1&&cmax==maxval){
            return n-rsi;
        }
        else{
            return -1;
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the Test Case: 
[2, 3, 6, 7, 1, 4, 5]
Leetcode gives the Correct answer as -1, but my code gives 3.
But Leetcode passed my code when I submitted it.
This Testcase is not Included in the Problem Testcases Maybe.

#### Screenshots

![Leetcode Testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72336848/a0f8087a-5be0-4519-b743-dabdb8468aa8)

#### Additional context

Why Did it passed my code even when it showed the correct answer but my code gives the wrong answer, please rectify this. Thankyou Leetcode.

**Comment by LC-Pam** [comment] 2023-09-18 15:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-20 16:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-20 16:34 UTC
Labels: Waiting for Reply
