### ISSUE TITLE
BUG - 10. Regular Expression Matching - Newly added test case break the checker.

### ISSUE THREAD

**Issue by BrycePy** [LeetCode-Feedback/LeetCode-Feedback#11644] opened 2023-02-10 22:17 UTC
#### Your LeetCode username
MinitWolf

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**I spent way too much time on this already. please give a minute to read this fully.** This question is impossible to not get "Time limit exceeded" right now in C++. Even with a known accepted solution. it appear that there were new test case added recently (https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/10798) and I assume the internal reference solution that is used to generate a reference result in C++ on your side cannot solve the new test case properly causing "Time limit exceeded". The previous issue (https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11642) was closed but the bug is still there. 

The following code should be able to handle the problematic test case by simplifying the pattern. but it gets "Time limit exceeded". I suspect that there is actually something wrong with the checker.

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    int nextPatternLength(string p){
        if(p.size() == 1) {
            return 1;
        }
        if(p.size() >= 2 && p.at(1) == '*') {
            return 2;
        }
        for(int l=0; l<p.size(); l++){
            if(p.at(l) == '*'){
                return l - 1;
            }
        }
        return p.size();
    }

    bool isExpandable(string p){
        return (p.size() == 2)? (p.at(1) == '*'): false;
    }

    int maxMatchLength(string s, string p){
        if(p.at(0) == '.') return s.size();
        int i = s.find_first_not_of(p.at(0));
        if(i < 0){
            return s.size();
        }
        return i;
    }

    bool staticCompare(string s, string p){
        if(s.size() < p.size()) return false;
        int counter = 0;
        for(auto c: p){
            if(c != '.' && c!=s.at(counter)) return false;
            counter++;
        }
        return true;
    }

    string simplifyPattern(string p){
        string remaining = p;
        string simplified = "";
        char lastExpandable = 0;
        while(remaining.size()){
            std::cout << remaining << std::endl;
            int patternLength = nextPatternLength(remaining);
            string currentPattern = remaining.substr(0, patternLength);
            remaining = remaining.substr(patternLength);
            if(isExpandable(currentPattern)){
                if(currentPattern.at(0) == lastExpandable){
                    continue;
                }else if(lastExpandable == '.'){
                    continue;
                }else{
                    lastExpandable = currentPattern.at(0);
                    simplified = simplified + currentPattern;
                }
            }else{
                lastExpandable = 0;
                simplified = simplified + currentPattern;
            }
        }
        return simplified;
    }

    bool solve(string s, string p) {
        if(!s.size() && (!p.size() || isExpandable(p))) return true;
        if(!p.size() && s.size()) return false;
        int patternLength = nextPatternLength(p);
        string currentPattern = p.substr(0, patternLength);
        string remaining = p.substr(patternLength, p.size() - patternLength);
        if(isExpandable(currentPattern)){
            int expandableLength = maxMatchLength(s, currentPattern);
            for(int i=expandableLength+1; i--;){
                if(solve(s.substr(i), remaining)) return true;
            }
            return false;
        }else{
            if(staticCompare(s, currentPattern)){
                return solve(s.substr(currentPattern.size()), remaining);
            }
            return false;
        }
        return false;
    }

    bool isMatch(string s, string p){
        std::cout << "simplified pattern: " << simplifyPattern(p) << std::endl;
        return solve(s, simplifyPattern(p));
    }
};
```

#### Language used for code

C++

#### Expected behavior
Possible to not get "Time limit exceeded".

#### Screenshots

same as: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11642

**Comment by LC-Pam** [comment] 2023-02-13 18:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code TLE link since the above code received AC after submit: https://leetcode.com/submissions/detail/897391468/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-14 18:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-14 18:48 UTC
Labels: LCUS, problem
