### ISSUE TITLE
Missing Test Case - 1009. Complement of Base 10 Integer

### ISSUE THREAD

**Issue by vaibhav-sahu** [LeetCode-Feedback/LeetCode-Feedback#9608] opened 2022-10-24 14:43 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int bitwiseComplement(int n) {
        int m = n ;
        int mask = 0 , ans = 0;  
        if (n==0){
            return 1;
        }
        while (m != 0){
            mask = (mask << 1) |1;
            m = m >> 1;
        }
        ans = (~n) & mask;
        return ans;
    }
};
```

**Comment by LC-Pam** [comment] 2022-10-24 17:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-27 15:59
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-27 15:59 UTC
Labels: LCUS, problem
