### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by dmitrymazitov** [LeetCode-Feedback/LeetCode-Feedback#18207] opened 2023-11-21 22:54 UTC
# Given an integer x, return true if x is a palindrome, and false otherwise.

# Example 1:
# Input: x = 121
# Output: true
# Explanation: 121 reads as 121 from left to right and from right to left.

# Example 2:
# Input: x = -121
# Output: false
# Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.

# Example 3:
# Input: x = 10
# Output: false
# Explanation: Reads 01 from right to left. Therefore it is not a palindrome.

class Solution:
    def isPalindrome(self, x: int) -> bool:
        cxt_list = list(str(x))
        rev_cxt_list = cxt_list[::-1]
        if cxt_list == rev_cxt_list:
            return True
        else:
            return False

x = 121

s = Solution().isPalindrome(x)
print(s)

**Comment by dmitrymazitov** [comment] 2023-11-21 22:54
first les

**Comment by LC-Pam** [comment] 2023-11-23 01:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-28 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 18:15 UTC
Labels: Waiting for Reply
