### ISSUE TITLE
Missing Test Case - 2671. Frequency Tracker

### ISSUE THREAD

**Issue by zhenliang153** [LeetCode-Feedback/LeetCode-Feedback#13328] opened 2023-05-07 05:22 UTC
#### Your LeetCode username

zhenliang153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

`std::multiset::count` or `std::unordered_multiset::count` should not be used here.
We can generate a test case through the following Python code:
```python
a = ["FrequencyTracker"]
b = [[]]

N = 5 * 10**4

for i in range(N):
    a.append("add")
    a.append("hasFrequency")
    b.append([i + 1])
    b.append([1])

print("[%s]" % ",".join(map(lambda x : "\"%s\"" % x, a)))
print("[%s]" % ",".join(map(str, b)))
```

#### Code you used for Submit/Run operation

```
// 2671. Frequency Tracker
class FrequencyTracker {
public:
    FrequencyTracker() {

    }
    
    void add(int number) {
        int num = ++m[number];
        if (num - 1 != 0) {
            ms.erase(num - 1);
        }
        ms.insert(num);
    }
    
    void deleteOne(int number) {
        auto itor = m.find(number);
        if (itor == m.end() || itor->second == 0) {
            return;
        }
        int num = --itor->second;
        ms.erase(num + 1);
        if (num != 0) {
            ms.insert(num);
        }
    }
    
    bool hasFrequency(int frequency) {
        return ms.count(frequency) != 0;
    }
    
private:
    unordered_map<int, int> m;
    unordered_multiset<int> ms;
};
```

#### Language used for code

C++

#### Expected behavior

Output: TLE
Expected: Right Answer

**Comment by LC-Pam** [comment] 2023-05-08 17:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:17 UTC
Labels: LCUS, problem
