### ISSUE TITLE
Missing Test Case - 2708. Maximum Strength of a Group

### ISSUE THREAD

**Issue by PratyushKargeti** [LeetCode-Feedback/LeetCode-Feedback#13730] opened 2023-05-27 21:43 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by PratyushKargeti** [comment] 2023-05-27 21:56
<img width="960" alt="Screenshot 2023-05-28 030424" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125042918/f78f0abe-3c0c-4f86-a060-4a0901248c08">
<img width="839" alt="Screenshot 2023-05-28 030742" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125042918/964b6d75-a8fa-498b-8743-e42fab534cb6">

**Comment by LC-Pam** [comment] 2023-05-29 16:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-31 18:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-31 18:08 UTC
Labels: LCUS, problem
