### ISSUE TITLE
32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by TJOKOLI17** [LeetCode-Feedback/LeetCode-Feedback#19626] opened 2024-01-21 20:48 UTC
### Problem number, title, and link

32. Longest Valid Parentheses: https://leetcode.com/problems/longest-valid-parentheses/description/

### Category of the bug
- [This one ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The answers to some custom test cases are incorrect.

i.e i had a test case "(()())(()()())" and expected answer to be 6 for (()())( $ ()()() $ ) longest valid parenthesis. However, the answer I got was 14 which is the number of all the parenthesis. according to the description and examples, that shouldn't be right.

Edit: upon further testing it looks like as long as there are an even amount of (s and )s it counts but the description doesn't make it clear that they don't have to be next to each other like "()"

### Language used for code

Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

<img width="305" alt="Screenshot 2024-01-21 at 3 46 59 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111609074/dc260d73-5cc3-450d-9bdc-275845bb9f17">

**Comment by LC-Pam** [comment] 2024-01-23 20:44
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:18
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:18 UTC
Labels: Waiting for Reply
