### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by satyanshpandey** [LeetCode-Feedback/LeetCode-Feedback#12971] opened 2023-04-15 09:06 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by satyanshpandey** [comment] 2023-04-15 09:07
Input:
s ="()([]{()})"

**Comment by saikumar8639** [comment] 2023-04-15 12:46
#Python code   
class Solution:
    def isValid(self, s: str) -> bool:
        dic=[]
        for i in s:
            if len(dic)==0:
                dic.append(i)
            elif (dic[-1]== '(' and i==")" ) or (dic[-1]== '{' and i=="}" ) or (dic[-1]== '[' and i=="]" )   :
                dic.pop()
            else:
                dic.append(i)
        return len(dic)==0

Input:
s="(){{{(({{}}])))"

output:
False

**Comment by LC-Pam** [comment] 2023-04-18 22:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-21 18:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-21 18:16 UTC
Labels: LCUS, problem
