### ISSUE TITLE
Typo in - 948. Bag of Tokens

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#20977] opened 2024-03-04 15:35 UTC
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Typo in the problem description..

### Fix
Just correct the spelling of `donates` to `denotes`. Refer to below screenshot.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77012237/a27df04a-face-4473-88ae-5f7fddf7ef3e)

**Comment by LC-Pam** [comment] 2024-03-05 20:35
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/20950

**Closed by LC-Pam** 2024-03-05 20:35 UTC
