### ISSUE TITLE
Problem 772 does not specify order of operations

### ISSUE THREAD

**Issue by quidryan** [LeetCode-Feedback/LeetCode-Feedback#6952] opened 2022-04-09 05:33 UTC
#### Your LeetCode username

quidryan

#### Category of the bug
- [ X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Basic Calculator III description does not specific which order the operands should be evaluated. Meaning the test case of "6-4/2" could be interpreted as "6-4" first resulting in 2, then "2/2" making the answer 1.  In another problem, Basic Calculator IV it is very explicit: "Expressions are evaluated in the usual order: brackets first, then multiplication, then addition and subtraction.". Since it's specified in one problem, the hints that it's important in that problem and consequently not important in other problems.

#### Code you used for Submit/Run operation

Irrelevant, the problem is in the description.

#### Language used for code

Not relevant.

#### Expected behavior

Either the test case should support answers like "1" for "6-4/2", or the description needs to specify order of operations.

#### Screenshots

<img width="666" alt="Screen Shot 2022-04-08 at 10 33 08 PM" src="https://user-images.githubusercontent.com/360255/162557985-f9d0292d-d540-4cc0-9f44-4171d347915e.png">

**Comment by LC-Yani** [comment] 2022-04-25 17:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment] 2022-04-27 17:29
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-27 17:29 UTC
Labels: LCUS, problem
