### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by anujjha13** [LeetCode-Feedback/LeetCode-Feedback#16522] opened 2023-09-19 06:05 UTC
#### Your LeetCode username
<anujjha9211>

#### Category of the bug
- [] Wrong test case is inserted

#### Code you used for Submit/Run operation
```
    int findDuplicate(vector<int>& nums) {
        
        //fails when all are duplicates ,also this should not to be the test case
        int x=0;
        for(int i=0;i<nums.size();i++){
            x^=(nums[i]^i);
        }
        return x;
    }

```

#### Screenshot
<img width="1436" alt="Screenshot 2023-09-19 at 11 25 44 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56735384/f21f83cd-7429-4818-8a4d-6029a0e69373">

<img width="1436" alt="Screenshot 2023-09-19 at 11 25 59 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56735384/8f529db5-58e9-41c5-978e-8f96271d1b99">

**Comment by LC-Pam** [comment] 2023-09-20 16:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-22 19:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-22 19:59 UTC
Labels: Waiting for Reply
