### ISSUE TITLE
Missing Test Case - 2851. String Transformation

### ISSUE THREAD

**Issue by zhuzhirui2005** [LeetCode-Feedback/LeetCode-Feedback#17586] opened 2023-10-28 17:07 UTC
#### Your LeetCode username
meyi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution exceeded the time limit on the following testcase:
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13196374/input.txt)

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    int sumCounts(vector<int>& nums) {
        int n = nums.size();
        char f[100001] = {0};
        unsigned long a = 0, M = 1e9+7;
        int ii[100001], len = 0, ll[100001];
        for(int i = 0; i < n; ++i){
            int x = nums[i];
            if(!f[x]){
                f[x] = 1;
                ii[x] = len++;
            }
            ll[i] = len;
            //cout << i << " " << ll[i] << endl;
        }
        for(auto &x: nums) x = ii[x];
        //cout << n << " :" << len << endl;
        for(int j = n-1; j>=0; --j){
            memset(f, 0, sizeof(f[0]) * len);
            unsigned c = 0;
            for(int i = j; i>=0; --i){
                //cout << " " << i << " " << nums[i] << " " << c << " " << a << endl;
                if(c + 1 + i == ll[i]){
                    a += ((unsigned long)ll[i] * (ll[i] + 1) * (1+2*ll[i]) - (unsigned long)c * (c + 1) * (1 + 2*c)) / 6;
                    //cout << "  :" << i << " " << ll[i] << " " << c << " " << a << endl;
                    break;
                }
                c += f[nums[i]] == 0;
                f[nums[i]] = 1;
                a += c*c;
                if(c == ll[j]){
                    a += c*c * (unsigned long)i;
                    //cout << "  ;" << i << " " << ll[i] << " " << c << " " << a << endl;
                    break;
                }
                //cout << "  " << i << " " << nums[i] << " " << c << " " << a << endl;
            }
            // for(int j = i; j < n; ++j){
            //     c += f[nums[j]] == 0;
            //     f[nums[j]] = 1;
            //     a += c*c;
            // }
            //cout << j << " " << a << endl;
        }
        return a % M;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Time Limit Exceeded

**Comment by LC-Pam** [comment] 2023-10-30 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:01
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:01 UTC
Labels: Waiting for Reply
