### ISSUE TITLE
Missing Test Case - 51. N-Queens

### ISSUE THREAD

**Issue by Aditya-21052131** [LeetCode-Feedback/LeetCode-Feedback#12532] opened 2023-03-23 18:37 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Aditya-21052131** [comment] 2023-03-23 18:42
In the question it is said that it run n queens but in  the case of 3 queens the program is not executed but we have a provision that in every row or every column one queen is necessary but in the case of n=3 the queen can clashed at any position in the   chess board.

**Comment by LC-Pam** [comment] 2023-03-24 20:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-28 16:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-28 16:51 UTC
Labels: LCUS, problem
