### ISSUE TITLE
Missing Test Case - 1281. Subtract the Product and Sum of Digits of an Integer

### ISSUE THREAD

**Issue by Satya-Prakash-Dwivedi** [LeetCode-Feedback/LeetCode-Feedback#15217] opened 2023-08-02 06:32 UTC
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
lass Solution {
    public int subtractProductAndSum(int n) {
        int r;
        int sum=0;
        int product =1;
        int result;
        while (n>0){
            r=n%10;
            n=n/10;
            sum+=r;
            product *= r;
        }
        result = product - sum;
        System.out.println(result);
         return result;
    }
   
}
```

**Comment by LC-Pam** [comment] 2023-08-04 19:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Satya-Prakash-Dwivedi** [comment] 2023-08-06 19:11
I have some problems with my laptop , so give me a time of 3 days

**Comment by LC-Pam** [comment] 2023-08-08 19:41
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-08 19:41 UTC
Labels: LCUS, problem, Waiting for Reply
