### ISSUE TITLE
Test Case No. 208 Returns Incorrect Result in "Balanced Binary Tree" Problem(Question no 110)

### ISSUE THREAD

**Issue by badhonnandi1** [LeetCode-Feedback/LeetCode-Feedback#18584] opened 2023-12-10 13:40 UTC
### Problem number, title, and link
110.Balanced Binary Tree https://leetcode.com/problems/balanced-binary-tree/

### Category of the bug
-  Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
In a binary tree, if the difference between the heights of the left and right subtrees is less than or equal to 1, then it is a balanced binary tree. In test case no. 208 (see picture below), the left subtree height and the right subtree height are both 3, making the difference 0. According to the definition, a tree with a difference of 0 should be considered a balanced binary tree, so it should return True. However, it's returning False.

### Code used for Submit/Run operation:
# Definition for a binary tree node.
class TreeNode:
     def __init__(self, val=0, left=None, right=None):
         self.val = val
         self.left = left
         self.right = right
class Solution:
    def isBalanced(self, root: Optional[TreeNode]) -> bool:
        if not root:
            return True

        def findMaxDepth(root):
            if not root:
                return 0
            
            if not root.left and not root.right:
                return 1
            
            elif not root.left:
                return findMaxDepth(root.right) + 1
            
            elif not root.right:
                return findMaxDepth(root.left) + 1
            
            return max(findMaxDepth(root.left),findMaxDepth(root.right)) + 1
            
        
        left = findMaxDepth(root.left)
        right = findMaxDepth(root.right)
        if abs(left-right)>1:
            return False
        else:
            return True

### Expected behavior
For the test care no 208 its given that False will be correct but it should return true.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/116469086/61a575c8-24f4-4876-b114-8cffeddcc38f)

**Comment by LC-Pam** [comment] 2023-12-12 23:28
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-14 22:27
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-14 22:27 UTC
Labels: Waiting for Reply

**Comment by nik0145** [comment] 2024-02-04 02:26
This test is correct, but I think the author was confused by the visualization of this tree in the test case, like me.
This is what the tree visualization looks like when I added it to the test case.
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23018061/d3eef7da-551c-45d8-9444-6d0e25885551)
But it looks completely different.
For example, if I add 9 instead of null, then I will see how the tree is built for real (Don’t forget, instead of 9 there is null).
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23018061/e9f97ffa-52ea-4a7f-bce8-5c8a2e350512)
This is what the tree itself should look like
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23018061/4bb7296b-817a-4f92-aea0-5043675da0d9)
