### ISSUE TITLE
Missing Test Case - 1378. Replace Employee ID With The Unique Identifier

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#17037] opened 2023-10-08 16:38 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

Write a solution to show the unique ID of each user, If a user does not have a unique ID replace just show null.
Return the result table in any order.

#### Code you used for Submit/Run operation

```
// Replace Employee ID With The Unique Identifier
Select u.unique_Id,e.name from Employees e
left join  EmployeeUNI u on u.id=e.id```

#### Language used for code
<!-- MS SQL Server -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![Screenshot (71)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/75bb45b4-ad70-470b-89fe-0369435a074a)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-10-09 19:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:39 UTC
Labels: Waiting for Reply
