### ISSUE TITLE
Missing Test Case - 977. Squares of a Sorted Array

### ISSUE THREAD

**Issue by PanXu888** [LeetCode-Feedback/LeetCode-Feedback#18792] opened 2023-12-20 04:10 UTC
![leetcode 2023-12-19 230926](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22653425/45e11900-7338-43d7-aec1-3ffd213acc84)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

JAVA

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
public int[] sortedSquares(int[] nums) {
        int i=0,j=nums.length-1;
        
        while(i<=j){
            int temp=0;
            if(Math.abs(nums[i]) <= Math.abs(nums[j])){
                nums[j]=nums[j]*nums[j];
           
            }else{
                temp=nums[j];
                nums[j]=nums[i]*nums[i];
                nums[i]=temp;

            }
            j--;
            
        }
        return nums;
    }
// above and below the code.
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22653425/4a73a975-6593-4ebc-9cb7-eae7fdb4bb09)

**Comment by LC-Pam** [comment] 2023-12-21 22:07
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-25 19:34
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-25 19:34 UTC
Labels: Waiting for Reply
