### ISSUE TITLE
Missing Test Case - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by vijull** [LeetCode-Feedback/LeetCode-Feedback#15467] opened 2023-08-10 06:10 UTC
#### Your LeetCode username
vijull

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ *] Missing Test Cases 

#### Description of the bug

missing test case for duplicasy of elements

#### Code you used for Submit/Run operation

```
//  Search in Rotated Sorted Array II

class Solution {
    public boolean search(int[] nums, int target) {
        int low = 0 , high = nums.length -1;

        while(low <= high ){
            int mid = (low + high)/2;
            if(nums[mid] == target) return true;
            
            //duplicate
            if(nums[low] == nums[mid] && nums[high] ==nums[mid]){
                low++ ; --high;
                continue ;
            }
            if(nums[low]<=nums[mid]){
                if(nums[low]<=target && target <= nums[mid]) high = mid - 1;
                else low = mid+1;
            }
            else{
                if(nums[mid]<=target && target <= nums[high]) low = mid+1;
                else high = mid-1;
            }
        }
        return false;
    }
}
```

#### Expected behavior

A test case for duplicates on both left side  , right side and mid elemets are same . That could be [3, 1, 2, 3, 3, 3, 3]

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71919355/a0b036bb-fbc8-4df4-9177-15aa32fe59a5)

**Comment by LC-Pam** [comment] 2023-08-11 19:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The VALID missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-16 19:49
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-16 19:49 UTC
Labels: LCUS, problem, Waiting for Reply
