### ISSUE TITLE
wrong Test Case - 437. Path Sum III

### ISSUE THREAD

**Issue by chetak123** [LeetCode-Feedback/LeetCode-Feedback#8448] opened 2022-07-31 08:25 UTC
Input [1000000000,1000000000,null,294967296,null,1000000000,null,1000000000,null,1000000000]
          0
Output 2
Expected 0

Not able to pass any solution (previous excepted solution also not passing.  

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-08-01 17:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-03 16:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-03 16:44 UTC
Labels: LCUS, problem
