### ISSUE TITLE
Unexpected testcase behaviour

### ISSUE THREAD

**Issue by auraticabhi** [LeetCode-Feedback/LeetCode-Feedback#7469] opened 2022-05-28 09:46 UTC
For the question no. 898 https://leetcode.com/problems/orderly-queue/ of leetcode the testcase :
"pyplrzxucp"
1
is returning the expected ans as "cppyplrzxu" but there can be this "plrzxucppy" possible ans to this question also as both the string has same smallest lexicographical order and as it is mentioned in question that we can find the ans in any number of step therefore there can be 2 possible ans to this question.

**Comment by LC-Pam** [comment] 2022-05-31 02:15
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 00:32
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 00:32 UTC
Labels: LCUS, problem
