### ISSUE TITLE
Missing Test Case - 853. Car Fleet

### ISSUE THREAD

**Issue by MatthewCochrane** [LeetCode-Feedback/LeetCode-Feedback#7212] opened 2022-05-06 05:13 UTC
#### Your LeetCode username
matt_cochrane_1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases (incorrect test case)

#### Description of the bug
This test case seems to give an incorrect answer by the online judge.

#### Code you used for Submit/Run operation
Test case:
```
12
[2,1,0]
[1,2,2]
```
Judge says the expected result is 2 fleets.  But there should clearly be only one fleet.

```
Car A starts at 2 with a speed of 1
Car B starts at 1 with a speed of 2
Car C starts at 0 with a speed of 2


pos 0123
t=0 CBA   Start out here, with three seperate fleets
t=1  CBA  B catches up with a, the fleets merge.  C also catches up with B, all should merge into one fleet

The result should be one fleet.
```

Note that the question states:
> If a car catches up to a car fleet right at the destination point, it will still be considered as one car fleet.

This sounds like the car should even merge fleets if a car had passed the finish and another car caught up to it so that it finishes at a time that would merge the fleets.

#### Language used for code
N/A

#### Expected behavior
The result for this test case should be `1` fleet.

**Comment by LC-Yani** [comment] 2022-05-07 02:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-17 22:12
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-17 22:12 UTC
Labels: LCUS, problem
