### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by ajay00sharma** [LeetCode-Feedback/LeetCode-Feedback#18738] opened 2023-12-17 07:23 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        stack<int> x, y, z;
        while (l1 != nullptr) {
            x.push(l1->val);
            l1 = l1->next;
        }
        while (l2 != nullptr) {
            y.push(l2->val);
            l2 = l2->next;
        }

        int carry = 0;
        ListNode* result = nullptr;

        while (!x.empty() || !y.empty() || carry != 0) {
            int sum = carry + (x.empty() ? 0 : x.top()) + (y.empty() ? 0 : y.top());
            carry = sum / 10;
            z.push(sum % 10);

            if (!x.empty()) x.pop();
            if (!y.empty()) y.pop();
        }

        while (!z.empty()) {
            ListNode* newNode = new ListNode(z.top());
            z.pop();
            newNode->next = result;
            result = newNode;
        }

        return result;
    }
};

### Expected behavior

On running this code it passes the all the 3 given test case but when I tried it with a different case it fails.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112599886/2180f085-50b9-4dda-8465-f98ee5e86b64)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112599886/04a40b2d-451b-42c0-8433-d6927a61ed8b)

**Comment by LC-Pam** [comment] 2023-12-19 18:42
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission code.
The missing test case is in text format. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2023-12-21 21:46
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2023-12-21 21:46 UTC
Labels: Waiting for Reply
