### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by rohitmultani** [LeetCode-Feedback/LeetCode-Feedback#8622] opened 2022-08-11 08:04 UTC
#### Your LeetCode username
rohitmultani

#### Category of the bug
- [ ] Missing Test Cases 
[10,5,15,1,6,11,16,null,null,null,8,null,12,null,20]

**Comment by LC-Pam** [comment] 2022-08-11 23:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-15 01:01
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-15 01:01 UTC
Labels: LCUS, problem
