### ISSUE TITLE
Missing Test Case - 1791. Find Center of Star Graph

### ISSUE THREAD

**Issue by 6202Binit** [LeetCode-Feedback/LeetCode-Feedback#11920] opened 2023-02-22 12:52 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
public int findCenter(int[][] edges) {
        int a = edges[0][0];
        int b = edges[0][1];
        int c = edges[1][0];
        int d = edges[1][1];
        return a==c||a==d?a:b;
    }
```

**Comment by LC-Pam** [comment] 2023-02-22 20:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-24 19:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-24 19:07 UTC
Labels: LCUS, problem
