### ISSUE TITLE
Missing Test Case - 2349. Design a Number Container System

### ISSUE THREAD

**Issue by hackybacky** [LeetCode-Feedback/LeetCode-Feedback#8307] opened 2022-07-23 18:47 UTC
#### Your LeetCode username
demonstrator

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
TestCase is missing.

#### Code you used for Submit/Run operation
```
class NumberContainers {
public:


  map<int,int> m;
    NumberContainers() {
      
        
    }
    
    void change(int index, int number) {
      m[index]=number;
        
    }
    
    int find(int number) {
         int ans=-1;
        for(auto it:m){
            if(it.second==number){
                ans=it.first;
                break;
            }
        }
         
        return ans;
        
    }
};



#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2022-07-25 16:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the missing test case?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:53
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:53 UTC
Labels: LCUS, problem
