### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by nandrack** [LeetCode-Feedback/LeetCode-Feedback#15961] opened 2023-08-27 14:45 UTC
#### Your LeetCode username
nandrack

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ [2,11,7,15]] Missing Test Cases 

#### Description of the bug
Seems string may not be in order, but single loop with adjacent indexes works for all presented cases.
If we'd add a case like  [2,11,7,15] it would force people to test on non-adjacent numbers.

Can be stupid, I don't know, I'm coding little drunk... :)

**Comment by LC-Pam** [comment] 2023-08-28 20:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-31 17:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-31 17:45 UTC
Labels: Waiting for Reply
