### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hucuanbin** [LeetCode-Feedback/LeetCode-Feedback#2556] opened 2021-03-02 10:13 UTC
12

**Comment by hucuanbin** [comment] 2021-03-02 10:16
理解出错

**Comment by hucuanbin** [comment] 2021-03-02 10:17
请问

**Comment by hucuanbin** [comment] 2021-03-02 10:20
是我理解错误

**Comment by lc-kay** [comment] 2021-03-02 19:17
@hucuanbin Please provide a more detailed report on the content-related issue you are trying to report, such as the problem title, the code you used, the actual and expected behavior.

**Comment by lc-kay** [comment] 2021-03-08 21:23
Hi @hucuanbin 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-03-08 21:23 UTC
