### ISSUE TITLE
Unclear description for 1023. Camelcase Matching

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#13202] opened 2023-04-29 10:11 UTC
#### Your LeetCode username
jjzzzmd

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/22430379/235297163-b3ece2de-e33b-4b09-a781-604fb74265b6.png">
the underlined sentence doesn't make sense at all...

#### Expected behavior

Please fix the description.

**Comment by LC-Pam** [comment] 2023-05-02 21:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The correct statement that you suggest.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-04 19:25
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-04 19:25 UTC
Labels: LCUS, problem
