### ISSUE TITLE
Missing TestCases isValidNumber

### ISSUE THREAD

**Issue by sainiteshGit** [LeetCode-Feedback/LeetCode-Feedback#3529] opened 2021-05-15 22:39 UTC
The following code is accepted :::

class Solution {
    public boolean isNumber(String s) {
       if(s==null || s.trim().length()==0)return false;
        
        boolean numberSeen=false;
        boolean eSeen=false;
        boolean decimalSeen=false;
        s=s.trim();
        for(int i=0;i<s.length();i++){
            char c=s.charAt(i);
            switch(c){
                    
                case '.':
                    if(decimalSeen||eSeen)return false; //already deimalSeen or exponential seen 
                    decimalSeen=true;
                    break;
                    
                case 'E':
                case 'e':
                    if(eSeen|| !numberSeen)return false;
                    eSeen=true;
                    numberSeen=false;
                    break;
                
                case '+':
                case '-':
                    if(i!=0 && (s.charAt(i-1)!='e'))return false;
                    numberSeen=false;
                    break;
                default:
                    if(!Character.isDigit(c))return false;
                    numberSeen=true;
                    
            }
        }
        return numberSeen;
        
    }
    
}

Even if the following input 
"005047E+6" returns false, which is not expected

**Comment by lc-kay** [comment] 2021-05-17 23:08
@sainiteshGit This is a duplicate of #3519 and we only reward the first reported case. Thank you for your time.

**Closed by lc-kay** 2021-05-17 23:08 UTC
