### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by binduMdm** [LeetCode-Feedback/LeetCode-Feedback#17562] opened 2023-10-27 20:54 UTC
**SELECT A.Id
FROM (SELECT ID,temperature 
LAG (temperature ,1)
OVER ( ORDER BY recordDate ) PREV_TEMP
FROM Weather) AS A
WHERE A.temperature  > A.PREV_TEMP**

#### Category of the bug

- [ ] Solution
- [x] Language - SQL sever
- [ ] Missing Test Cases

**Comment by LC-Pam** [comment] 2023-10-29 03:19
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:00 UTC
Labels: Waiting for Reply
