### ISSUE TITLE
Incorrect test case task 287. Find the Duplicate Number, Test case # 18

### ISSUE THREAD

**Issue by gleberof** [LeetCode-Feedback/LeetCode-Feedback#16530] opened 2023-09-19 16:09 UTC
#### Your LeetCode username
gleberof

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases (incorrect)

#### Description of the bug
Task description defines that:
```
There is only one repeated number in nums, return this repeated number.
```

However, in test # 18, the sequence appears:
```
[2,2,2,2,2]
```
Which contradicts the task condition

#### Code you used for Submit/Run operation

This Python code does not pass the wrong test case but solves the initial task correctly
```
//  287. Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/)
class Solution:
    def findDuplicate(self, nums: List[int]) -> int:
        mask = 0
        for n in nums:
            mask = mask ^ n
        for i in range(1, len(nums)):
            mask = mask ^ i
        return mask
```

#### Language used for code
Python

#### Expected behavior
Either the test case needs to be removed or the task description corrected

**Comment by LC-Pam** [comment] 2023-09-20 16:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-22 20:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-22 20:00 UTC
Labels: Waiting for Reply
