### ISSUE TITLE
 Missing test case for Problem 123

### ISSUE THREAD

**Issue by CodeWithtankan** [LeetCode-Feedback/LeetCode-Feedback#14387] opened 2023-06-27 07:10 UTC
The problem 123 is missing a test case that covers the edge case where the input is a negative number.

Steps taken to resolve:
I have tried to add the missing test case myself, but I am not able to get it to pass.

Screenshots or other supporting evidence:
[Screenshot of the problem description]
[Screenshot of the missing test case]

Once you have created the issue, the LeetCode team will be able to see it and investigate the problem. They will then get back to you with a response.

**Comment by LC-Pam** [comment] 2023-06-27 18:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-29 18:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-29 18:17 UTC
Labels: LCUS, problem
