### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by ravigupta0210** [LeetCode-Feedback/LeetCode-Feedback#15213] opened 2023-08-02 04:58 UTC
#### Your LeetCode username
xyz_abc_123

#### Category of the bug
-A peak element is an element that is strictly greater than its neighbors.

Given a 0-indexed integer array nums, find a peak element, and return its index. If the array contains multiple peaks, return the index to any of the peaks.

You may imagine that nums[-1] = nums[n] = -∞. In other words, an element is always considered to be strictly greater than a neighbor that is outside the array.

You must write an algorithm that runs in O(log n) time.

"class Solution {
public:
    int findPeakElement(vector<int>& nums) {
       int s=0,e=nums.size()-1;
       while(s<e){
           int mid=s+(e-s)/2;
           if(nums[mid]>nums[mid+1])
           e=mid;
           else if(nums[mid]<nums[mid+1])
           s=mid+1;
       }
       return s;
    }
};"

- c++
- [ 1,5,3,4,2]

#### Description of the bug
In this test case if we perform binary search template then it give output 3 but according to question answer is 1

#### Code you used for Submit/Run operation
"class Solution {
public:
    int findPeakElement(vector<int>& nums) {
       int s=0,e=nums.size()-1;
       while(s<e){
           int mid=s+(e-s)/2;
           if(nums[mid]>nums[mid+1])
           e=mid;
           else if(nums[mid]<nums[mid+1])
           s=mid+1;
       }
       return s;
    }
};"

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++


#### Expected behavior
In this test case if we perform binary search template then it give output 3 but according to question answer is 1



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by ravigupta0210** [comment] 2023-08-02 04:59
Correct it!!

**Comment by LC-Pam** [comment] 2023-08-04 19:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-08 19:38
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-08 19:38 UTC
Labels: LCUS, problem, Waiting for Reply
