### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by jaketomo4** [LeetCode-Feedback/LeetCode-Feedback#18327] opened 2023-11-27 20:35 UTC
### LeetCode Username

jaketomo4

### Problem number, title, and link

1. Two Sum https://leetcode.com/problems/two-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is no test case for the list values being apart from one another, allowing a simple solution of the code below.

### Language used for code

Python

### Code used for Submit/Run operation

```
count = 0
        while count+1 <= len(nums):
            if nums[count] + nums[count+1] == target:
                return [count,count+1]
            count += 1
```

### Expected behavior

If we took Test Case 1 as an example, if the nums list was [2, 11, 7, 15], then the above code would not work.

**Comment by jaketomo4** [comment] 2023-11-27 20:38
After clicking "submit" on the solution, the mentioned test case occurred.

**Comment by LC-Pam** [comment] 2023-11-28 19:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-01 21:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-01 21:48 UTC
Labels: Waiting for Reply
