### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays      

### ISSUE THREAD

**Issue by Harshpathakjnp** [LeetCode-Feedback/LeetCode-Feedback#10482] opened 2022-12-22 14:04 UTC
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Missing Test Case - 4. Median of Two Sorted Arrays      

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Harshpathakjnp** [comment] 2022-12-22 14:05
Input
nums1 =
[1,3,7,9,11,13,114,115]

nums2 =
[2,8,9,10,11,13,15]

Output
22.73333

**Comment by LC-Pam** [comment] 2022-12-23 18:24
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-26 18:08
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-26 18:08 UTC
Labels: LCUS, problem
