### ISSUE TITLE
Missing Test Case - 767. Reorganize String

### ISSUE THREAD

**Issue by alexmadman776** [LeetCode-Feedback/LeetCode-Feedback#8797] opened 2022-08-25 19:39 UTC
class compare
{
    public:
    bool operator()(pair<char,int> a, pair<char,int> b)
    {
        return a.second < b.second;
    }
};
class Solution {
public:
    string reorganizeString(string s) {
        int n = s.length();
        
        unordered_map<char,int> umap;
        for(auto ch : s)
        {
            umap[ch]++;
        }
        
        priority_queue<pair<char,int>,vector<pair<char,int>>,compare> pq;
        
        for(auto pair : umap)
        {
            pq.push(pair);
        }
        
        string ans ="";
        
        pair<char,int> prev ={' ',-1};
        
        while(!pq.empty())
        {
            pair<char,int> curr = pq.top();
            pq.pop();
            if(curr.second == -1) break;
            ans.push_back(curr.first);
            curr.second -=1;
            if(prev.second >0 )
            pq.push(prev);
            prev = curr;
        }
        
        if(ans.length() != n) return "";
                
        return ans;
    }
};

**Comment by LC-Pam** [comment] 2022-08-25 20:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-27 01:14
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-27 01:14 UTC
Labels: LCUS, problem
