### ISSUE TITLE
Explore Card:  Principle of Recursion - example says print in reverse instead of printing in forward order

### ISSUE THREAD

**Issue by bognevivien** [LeetCode-Feedback/LeetCode-Feedback#11136] opened 2023-01-20 06:27 UTC
#### Category of the bug
- [x] Explore Card
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The example of the Principle of recursion is saying print in reverse order but the solution is for a forward order.

![image](https://user-images.githubusercontent.com/71817685/213631547-761a11cd-0078-45e0-9022-1f6c8c86e028.png)

**Comment by LC-Pam** [comment] 2023-01-24 17:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-26 18:33
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-26 18:33 UTC
Labels: LCUS, solution
