### ISSUE TITLE
Missing Test Case - 2156. Find Substring With Given Hash Value

### ISSUE THREAD

**Issue by RubinsJ** [LeetCode-Feedback/LeetCode-Feedback#16047] opened 2023-08-30 15:48 UTC
#### Your LeetCode username
janis__

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Description of the bug
The standard Two Sum problem can often be solved with the use of hash tables, or by initially sorting the array. To make it more challenging, let's consider a case where the array has multiple pairs that sum up to the target, but one of them involves larger indices.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # A dictionary to store the complement and its index
        d = {}
        for i, num in enumerate(nums):
            complement = target - num
            if complement in d:
                return [d[complement], i]
            d[num] = i
        return []
```

#### Language used for code
Python

#### Expected behavior
For a test case like nums = [3, 3, 2, 4, 5, 1, 7, 8, 9, 6] and target = 10, there are multiple solutions possible such as (2, 8), (3, 7), (4, 6), and (1, 9). The algorithm should be capable of handling cases where there are multiple valid answers and should ideally return the one involving the largest indices, i.e., (1, 9) for the example provided.
Input:
[3,3,2,4,5,1,7,8,9,6]
10
Expected Output:
[2,8]

#### Additional context
Such a test case forces solutions to account for scenarios where the obvious or first encountered solution might not be the only or the best answer. It pushes the algorithm to explore deeper to find the best possible solution, emphasizing the importance of considering all possible solutions.

**Comment by LC-Pam** [comment] 2023-08-30 16:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by RubinsJ** [comment] 2023-08-30 17:56
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # A dictionary to store the complement and its index
        d = {}
        for i, num in enumerate(nums):
            complement = target - num
            if complement in d:
                return [d[complement], i]
            d[num] = i
        return [] 

Description of the bug
The standard Two Sum problem can often be solved with the use of hash tables, or by initially sorting the array. To make it more challenging, let's consider a case where the array has multiple pairs that sum up to the target, but one of them involves larger indices.
Expected behavior
For a test case like nums = [3, 3, 2, 4, 5, 1, 7, 8, 9, 6] and target = 10, there are multiple solutions possible such as (2, 8), (3, 7), (4, 6), and (1, 9). The algorithm should be capable of handling cases where there are multiple valid answers and should ideally return the one involving the largest indices, i.e., (1, 9) for the example provided.
Input:
[3,3,2,4,5,1,7,8,9,6]
10
Expected Output:
[2,8]

**Comment by LC-Pam** [comment] 2023-08-31 18:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The above code received Runtime Error: https://leetcode.com/submissions/detail/1037027882/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-04 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-04 16:52 UTC
Labels: Waiting for Reply
