### ISSUE TITLE
Wrong description in the Data structure Stack

### ISSUE THREAD

**Issue by isi-frischmann** [LeetCode-Feedback/LeetCode-Feedback#7046] opened 2022-04-19 07:44 UTC
#### Your LeetCode username
isabell

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
When looking at the data structure Stack Card you are saying: "In a LIFO data structure, the newest element added to the queue will be processed first." 

But this is not a Queue, it is called Stack!

#### Screenshots
![Screen Shot 2022-04-19 at 9 43 46 AM](https://user-images.githubusercontent.com/36458622/163951857-007562a5-6e1f-425d-91a4-83dce865a078.png)

**Comment by LC-Yani** [comment] 2022-04-20 21:40
Hi @isi-frischmann ,

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The link of this page. 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Yani** [comment] 2022-04-27 17:27
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-27 17:27 UTC
Labels: LCUS
