### ISSUE TITLE
Missing Test Case - 103. Binary Tree Zigzag Level Order Traversal

### ISSUE THREAD

**Issue by rahulbhardwaj0711** [LeetCode-Feedback/LeetCode-Feedback#12232] opened 2023-03-07 16:30 UTC
#### Your LeetCode username 
<rahulbhardwaj0711>rahulbhardwaj0711

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug
 Some test case is missing for accurate solution

#### Code you used for Submit/Run operation

```
class Solution {

public:
    vector<vector<int>> zigzagLevelOrder(TreeNode* root) {
        vector<vector<int>> ans;
        if(!root) return ans;
        queue<TreeNode*> q;
        q.push(root);
        bool f = false;
        while(!q.empty()){
            int k = q.size();
            vector<int>t;
            while(k--){
                TreeNode* temp = q.front();
                q.pop();
                if(f){
                    if(temp->left) q.push(temp->left);
                    if(temp->right) q.push(temp->right);
                    f = false;
                }
                else{
                    if(temp->right) q.push(temp->right);
                    if(temp->left) q.push(temp->left);
                    f = true;
                }
                t.push_back(temp->val);
            }
                
            ans.push_back(t);
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

for the test case : [9,7,9,4,5,10,6,9,7] 
above solution code is giving wrong answer but it is accepting the code.

#### Screenshots

![Screenshot (8)](https://user-images.githubusercontent.com/127230056/223486242-78294986-3f7d-4320-95da-8f7d4749a31b.png)

#### Additional context

add the above test code to this problem

**Comment by LC-Pam** [comment] 2023-03-07 19:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-08 19:04
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-08 19:04 UTC
Labels: LCUS, problem
