### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by mohammed-fandees** [LeetCode-Feedback/LeetCode-Feedback#11716] opened 2023-02-13 11:27 UTC
#### Mohammed-Fandees

Problem : https://leetcode.com/problems/two-sum/description/
```
// Two Sum
var twoSum = (nums, target) => {
    for(let i = 0; i < nums.length; i++) {
        let test = nums[i] + nums[i + 1];
        if (test === target) 
           return [i , i + 1];
        else if (test === undefined)
            return `Not Found`;
    }
};
```
#### OOP code
```
class twoSum {
    constructor(array, find) {
        this.nums = array;
        this.find = find;
    }

    check() {
        for(let i = 0; i < this.nums.length ; i++) {
            let test = this.nums[i] + this.nums[i + 1];
            if(test === this.find) {
                return [i , i + 1];
            } else if (test === undefined) {
                return `Not Found`;
            }
        }
    }
}
```

**Comment by LC-Pam** [comment] 2023-02-13 19:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-14 18:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-14 18:55 UTC
Labels: LCUS, problem
