### ISSUE TITLE
Missing Test Case - 511. Game Play Analysis I

### ISSUE THREAD

**Issue by rosanguyen263** [LeetCode-Feedback/LeetCode-Feedback#11418] opened 2023-02-01 22:14 UTC
#### Write an SQL query to report the first login date for each player.
Return the result table in any order.
The query result format is in the following example.

![Untitled](https://user-images.githubusercontent.com/122941482/216175699-a1730f12-f2ae-4657-aedd-0a891ddd9d23.png)

SELECT 
player_id,
event_date as first_login
From Activity
Group by player_id

**Comment by LC-Pam** [comment] 2023-02-02 17:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-07 19:01
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-07 19:01 UTC
Labels: LCUS, problem
