### ISSUE TITLE
In the solution we discuss about `void pop()` but in the problem statement requires `int pop()`

### ISSUE THREAD

**Issue by allan-init** [LeetCode-Feedback/LeetCode-Feedback#8405] opened 2022-07-28 05:59 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution we discuss about `void pop()` but in the problem statement requires `int pop()`  *Removes the element from the front of the queue and returns it.* The solution of solution 1 and solution 2 do not fulfill the requirements of the problem and do not pass the tests.

#### Code you used for Submit/Run operation

Possible implementation of the approach 1

```
    private Stack<Integer> s1;
    private Stack<Integer> s2;
    private int front;
    
    public MyQueue() {
        
        s1 = new Stack<Integer>();
        s2 = new Stack<Integer>();

    }
    
    public void push(int x) {
        
        if (s1.empty())
            front = x;
        while (!s1.isEmpty())
            s2.push(s1.pop());
        s2.push(x);
        while (!s2.isEmpty())
            s1.push(s2.pop());
    }
    
    public int pop() {
        return s1.pop(); 
    }
    
    public int peek() {
        return s1.peek();
    }
    
    public boolean empty() {
        return s1.isEmpty();
    }
```

#### Language used for code

Java

**Comment by LC-Pam** [comment] 2022-07-28 17:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number or name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:55
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:55 UTC
Labels: LCUS, problem
