### ISSUE TITLE
https://leetcode.com/explore/learn/card/graph/619/depth-first-search-in-graph/3848/

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#8143] opened 2022-07-12 02:37 UTC
The overall O(V^3) deduction is fine, but the intermediate
≈V⋅(V−1)/2+1 
is confusing

(V - 1) - 1 + (V - 2) - 1 + (V - 3) - 1 + ...(V−1)−1+(V−2)−1+(V−3)−1+... 
≈V⋅(V−1)/2+1  (= V*V - V/2 +1  Is this what you meant?)

I dunno why the "approximately equal" value has been chosen, since this should be able to be caluculated exactly ... though the exact value doesn't match:

Assuming V terms:
V*V - 1*V - V*(V+1)/2

Assuming V-1 terms:
V*(V-1) -1*(V-1) - (V-1)*V/2  = (V-1) * [V-1 -V/2)]
                                             = (V-1) * [V/2 - 1]
                                             = V*V/2 -3/2V +1

**Comment by LC-Pam** [comment] 2022-07-12 17:31
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:44 UTC
Labels: LCUS, problem
