### ISSUE TITLE
876. Middle of the Linked List test case contribute

### ISSUE THREAD

**Issue by sambhavmahajan** [LeetCode-Feedback/LeetCode-Feedback#21083] opened 2024-03-07 10:57 UTC
[2840, 5670, 3392, 5099, 2141, 7392, 5817, 6245, 8201, 9536, 3678, 1024, 4963, 3150, 7089, 2846, 6571, 4018, 1792, 8634, 5291, 2075, 9468, 1380, 5729, 6942, 8053, 2198, 4705, 6318, 9840, 7582, 4269, 5931, 1074, 3825, 8506, 2694, 9157, 7360, 6483, 5217, 3104, 8942, 7548, 3692, 1025, 8637, 5401, 1759, 2038, 6985, 4507, 8146, 9270, 1865, 3251, 5713, 4972, 8206, 6389, 5743, 1098, 3640, 8952, 7308, 2816, 6059, 3427, 9176, 5096, 7482, 2619, 1364, 3892, 7504, 6438, 5812, 9275, 3054, 4721, 6948, 1382, 8460, 5296, 6315, 7184, 9430, 2079, 6581, 4927, 8740, 3609, 5196, 2847, 7412, 6038, 8752, 1978, 4693, 8250, 3641]

**Comment by LC-Pam** [comment] 2024-03-08 16:18
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-03-11 17:24 UTC
Labels: Waiting for Reply
