### ISSUE TITLE
Not getting accepted

### ISSUE THREAD

**Issue by is124** [LeetCode-Feedback/LeetCode-Feedback#13257] opened 2023-05-03 05:55 UTC
2215. Find the Difference of Two Arrays

#### Your LeetCode username
 @tilak_

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

As given in the question that order of list doesn't matter, but while submitting the solution I'm getting wrong answer

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> findDifference(int[] nums1, int[] nums2) {
        List<List<Integer>> ans = new ArrayList<>();
        List<Integer> first = new ArrayList<>();
        List<Integer> second = new ArrayList<>();

        HashSet<Integer> set = new HashSet<>();

        for(int i: nums1) set.add(i);

        for(int j : nums2){
            if(!set.contains(j)){
                first.add(j);
            }
        }

        set.clear();

        for(int i : nums2) set.add(i);

        for(int j : nums1){
            if(!set.contains(j)){
                second.add(j);
            }
        }

        ans.add(first);
        ans.add(second);

        return ans;
    }
}
```
#### Screenshots

![Screenshot from 2023-05-03 10-53-44](https://user-images.githubusercontent.com/51227848/235841399-e19cab5c-4008-49c5-aa3f-6920e21b53c4.png)

**Comment by LC-Pam** [comment] 2023-05-03 18:18
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-04 19:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-04 19:29 UTC
Labels: LCUS, problem

**Comment by is124** [comment] 2023-05-04 19:30
Hi @LC-Pam I've already mentioned the problem in the first line. It's `2215. Find the Difference of Two Arrays`
