### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by Neilus03** [LeetCode-Feedback/LeetCode-Feedback#9039] opened 2022-09-13 08:46 UTC
class Solution:
    def numberOfSteps(self, num: int) -> int:
        steps= 0
        while num != 0:
            if num %2 != 0:
                num-=1
            else:
                num/=2
            steps+=1
        return steps

DONE IN PYTHON 3 BY @neiluss in leetcode

**Comment by GuruTheCoderYoutube** [comment] 2022-09-13 12:32
We'll need more information.

**Comment by LC-Pam** [comment] 2022-09-14 07:49
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-16 10:37
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-16 10:37 UTC
Labels: LCUS, problem
