### ISSUE TITLE
Missing Test Case - 2730. Find the Longest Semi-Repetitive Substring

### ISSUE THREAD

**Issue by yashdesigns** [LeetCode-Feedback/LeetCode-Feedback#14019] opened 2023-06-10 19:28 UTC
#### Your LeetCode username
yashg7842

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

when all digits in the string are distinct, it should return 0, but is is returning length of  string

#### Code you used for Submit/Run operation

```

```

#### Expected behavior

s =
"5490"
Expected
0

**Comment by yashdesigns** [comment] 2023-06-10 19:29
s =
"5490"
Expected
0

**Comment by LC-Pam** [comment] 2023-06-12 18:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:23
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:23 UTC
Labels: LCUS, problem
