### ISSUE TITLE
Missing Test Case - 506. Relative Ranks

### ISSUE THREAD

**Issue by faijanbaig** [LeetCode-Feedback/LeetCode-Feedback#17417] opened 2023-10-24 12:14 UTC
#### Your LeetCode username
faizanbaig

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases  {2,56,987,7675,73673,767,57757,4746,766,98,23}

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
class Solution {
    public String[] findRelativeRanks(int[] score) {
        int n =score.length;
        int [] a = new int[n];
        for(int i=0;i<n;i++) a[i] = score[i];
        Arrays.sort(a);
        HashMap<Integer,String> h = new HashMap<>();
        for(int i=n-1,k=4;i>=0;i--){
            if(i==n-1) h.put(a[i],"Gold Medal");
            else if(i==n-2) h.put(a[i],"Silver Medal");
            else if(i==n-3) h.put(a[i],"Bronze Medal");
            else{
                h.put(a[i],Integer.toString(k));
                k++;
            }
        }
        String [] result = new String[n];
        for(int i=0;i<n;i++){
            result[i] = h.get(score[i]);
        }
        return result;
    }
}
    }
};
```

#### Language used for code
 JAVA

**Comment by LC-Pam** [comment] 2023-10-24 17:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 19:01
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-27 19:01 UTC
Labels: Waiting for Reply
