### ISSUE TITLE
JS judge problem for 2195

### ISSUE THREAD

**Issue by poppinlp** [LeetCode-Feedback/LeetCode-Feedback#6632] opened 2022-03-06 04:52 UTC
#### Your LeetCode username

[poppinlp](https://leetcode.com/poppinlp/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

[I sent a post here](https://leetcode.com/problems/append-k-integers-with-minimal-sum/discuss/1823867/problem-theres-a-bigint-problem-with-javascript).

In short words, the result for that test case is a big number rather than JS general number. But when I return `BigInt` or covert the `BigInt` to string, the judge shows my answer as the general number result which is wrong. I guess that's because the judge tries to convert the result to a general JS number.

#### Code you used for Submit/Run operation

```js
const minimalKSum = (nums, k) => {
  const set = new Set();
  let sum = BigInt((1 + k) * k / 2);
  let more = 0;
  nums = Array.from(new Set(nums))
  for (const n of nums) {
    if (n > k) { set.add(n); continue; }
    ++more;
    sum -= BigInt(n);
  }
  while (more > 0) {
    ++k;
    if (set.has(k)) continue;
    sum += BigInt(k);
    --more;
  }
  console.log(sum, sum.toString());
  return sum;
};
```

#### Language used for code

JavaScript

#### Expected behaviour

could pass that test case

#### Screenshots

Just like the code above, I log the result before returning it and you could see it's not the same as the final result from the judge.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1970625/156909676-8f2a105b-9326-414d-b84e-81d81bd89f26.png">

**Comment by paultman** [comment] 2022-03-06 16:05
I had the same problem and unfortunately didn't move on to other questions as I was stuck on this one. 
As mentioned above, the problem is easily reproducible and an oversight regarding JS integer limitations.

**Comment by faustaleonardo** [comment] 2022-03-07 00:50
Upvoted. Thanks for this post.

**Comment by LC-Sue** [comment] 2022-03-16 23:32
Hi @poppinlp 
Thank you for reaching out to us! The issue has been resolved by our team! We appreciate your support!

**Closed by LC-Sue** 2022-03-16 23:32 UTC
Labels: LCUS
