### ISSUE TITLE
unique email address 

### ISSUE THREAD

**Issue by niranjandasMM** [LeetCode-Feedback/LeetCode-Feedback#8582] opened 2022-08-08 08:01 UTC
#### Category of the bug
- [ 1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def numUniqueEmails(self, emails: List[str]) -> int:
        def ets(email):
            preprocessed_email = []
            name, domain = email[:email.index('@')] , email[email.index('@'):]
            domain = domain[:domain.index('.com')]
        if '.' not  in domain:
            name = name.replace(".","")
            name = name[:name.index("+")]
            email = name + domain + ".com"
            preprocessed_email.append(email)
            print(preprocessed_email)
            return preprocessed_email

    results = [ ets(i) for i in email ]
    result = [x for x in results if x is not None]
    print(len(result))
```

**Comment by LC-Pam** [comment] 2022-08-08 19:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-10 17:48
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-10 17:48 UTC
Labels: LCUS, problem
