### ISSUE TITLE
Missing Test Case - 998. Maximum Binary Tree II

### ISSUE THREAD

**Issue by tinkusharma1** [LeetCode-Feedback/LeetCode-Feedback#16953] opened 2023-10-05 12:42 UTC
#### Your LeetCode username
tinkusharmarock

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [this ] Missing Test Cases 

#### Description of the bug

As per its Last variant i.e Maximum Binary Tree(leetcode-654), we have to make a binary tree , as per descrimination.
That is find the largest element in the array make it root_node then its Left SubTree will be made by all the element in the left of the largest element, similarly for right. But in Maximum Binary Tree || (leetcode-998) , we have already given a Binary Tree we just have insert val(given) into the the Binary tree. If you notice the pattern in the  Maximum Binary Tree(leetcode-654), value of roots decrease as we construct Binary Tree. In  Maximum Binary Tree || (leetcode-998) the Test Case missing is [4,1,7,null,null,2],however 4 is smaller than 7 still 4 is root. 

#### Code you used for Submit/Run operation

class Solution {
public:
    void in_order(TreeNode* root, vector<int> &v){
        if(!root) return ;
        in_order(root->left,v) ;
        v.push_back(root->val) ;
        in_order(root->right,v) ;
    }
     int max_idx(vector<int> v , int lo , int hi){
        int idx = lo ;
        for(int i = lo ; i <= hi ; i++)if(v[idx] < v[i]) idx = i ;
        return idx ;
    }
    TreeNode* construc(vector<int> v, int lo , int hi){
        if(lo > hi) return NULL ;
        int idx = max_idx(v,lo,hi) ;
        TreeNode* node = new TreeNode(v[idx]) ;
        node->left = construc(v,lo,idx-1) ;
        node->right = construc(v,idx+1,hi) ;
        return node ;
    }
    TreeNode* insertIntoMaxTree(TreeNode* root, int val) {
        vector<int> v ;
        in_order(root,v) ;
        v.push_back(val) ;
        return construc(v,0,v.size()-1) ;
    }
};

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/147061288/981ff7d8-fe2b-40de-890a-d778ab7a85a2)

**Comment by tinkusharma1** [comment] 2023-10-05 12:43
I hope you'll respond to me

**Comment by LC-Pam** [comment] 2023-10-05 17:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-09 18:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-09 18:40 UTC
Labels: Waiting for Reply
