### ISSUE TITLE
Typo in Problem #378

### ISSUE THREAD

**Issue by AidanFarhi** [LeetCode-Feedback/LeetCode-Feedback#3091] opened 2021-04-12 22:12 UTC
#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment] 2021-04-14 18:37
Duplicate of #3092

**Closed by lc-kay** 2021-04-14 18:37 UTC
