### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle -- C++ solution with explanation

### ISSUE THREAD

**Issue by lovkesh07** [LeetCode-Feedback/LeetCode-Feedback#7387] opened 2022-05-21 06:52 UTC
class Solution {
public:
    vector<vector<int>> generate(int numRows) {
	vector<vector<int>> ret(numRows);
        
	for (int i = 0; i < numRows; i++) {
        ret[i].resize(i+1);         // for everyrow the no. of columns will always be equal to the of row. Therefore resizing the empty vector to a size (i+1).
        ret[i][0] = ret[i][i] =1;   // as here the 1st and the last element is always 1
		
        
		for (int j = 1; j < i; j++)   // linearly traversing from the 1st column to the 2nd last column.
			ret[i][j] = ret[i - 1][j] + ret[i - 1][j - 1];   // here we are adding the j-1 colimn value of the previous row and 
                                                                    //  adding to it the jth                                                                     
                                                                   //  column value of the previous row
	}
	return ret;     // return the pascal triangle
    }
};  

// tc = O(n*n)
// sc = O(n*n)

**Comment by LC-Pam** [comment] 2022-05-23 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the missing test case or issues?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-24 03:04
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-24 03:04 UTC
Labels: LCUS, problem
