### ISSUE TITLE
Problem 1498 asks for subsequences but the given solution provides subsets.

### ISSUE THREAD

**Issue by jodakar1192** [LeetCode-Feedback/LeetCode-Feedback#13316] opened 2023-05-06 09:11 UTC
#### Your LeetCode username
jokarakoj

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem asks for number of subsequences.
The provided solution (`nlog(n)`) gives the number of subsets.
Both test cases `[3,4,7,6]` and `[3,4,6,7]` expect the same answer (15) however `[3,4,6,7]` is not an appropriate subsequence of the first.

**Comment by jodakar1192** [comment] 2023-05-06 10:18
Actually, the fact that its couting subsets doesnt matter. But maybe this should be explicitly called out in the explanation of the solution?

**Comment by LC-Pam** [comment] 2023-05-08 21:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:19 UTC
Labels: LCUS, problem
