### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Vasudeva-bit** [LeetCode-Feedback/LeetCode-Feedback#8673] opened 2022-08-15 10:56 UTC
#### Your LeetCode username

VasudevaK

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

There is no test case that breaks the condition ```umap[s[i]]  < umap[s[i+1]]``` even though we loop from``` i = 0``` to ```i < s.size()```.  Ideally, it should work for the code with condition ```i < s.size()-1``` instead of ```i < s.size()```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int romanToInt(string s) {
        unordered_map<char, int> umap;
        
        umap['I'] = 1;
        umap['V'] = 5;
        umap['X'] = 10;
        umap['L'] = 50;
        umap['C'] = 100;
        umap['D'] = 500;
        umap['M'] = 1000;
        
        int result = 0;
        for(int i=0;i<s.size();i++) {
            if(umap[s[i]] < umap[s[i+1]])
                result -= umap[s[i]];
            else
                result += umap[s[i]];
        }
        return result;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The loop should break in case of indexing values in such a case from a string, in other words, when comparing values in a string by indices ```i``` and ```i+1``` the loop should be from ```0``` to ```s.size()-1``` where s is the string given to the problem.

#### Additional context

Try to add a test case that breaks the current version of the code, I submitted!

**Comment by stormsunshine** [comment] 2022-08-15 11:21
All possible 3999 test cases already exist. Which test case do you want to add?

**Comment by LC-Pam** [comment] 2022-08-15 16:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-17 02:46
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding

**Closed by LC-Pam** 2022-08-17 02:46 UTC
Labels: LCUS, problem
