### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by petertarek291** [LeetCode-Feedback/LeetCode-Feedback#11547] opened 2023-02-05 15:47 UTC
#### Category of the bug
- [88. Merge Sorted Array ] Question
- [   const newNums = nums1.slice(0, m);
  const newNums2 = nums2.slice(0, n);
  const x = [...newNums, ...newNums2];
  x.sort((a, b) => a - b);
  return x;] Solution
- [javascript ] Language
- [ 1,3] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by petertarek291** [comment] 2023-02-05 15:49
const newNums = nums1.slice(0, m);
  const newNums2 = nums2.slice(0, n);
  const x = [...newNums, ...newNums2];
  x.sort((a, b) => a - b);
  return x;

**Comment by LC-Pam** [comment] 2023-02-07 19:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-08 18:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-08 18:19 UTC
Labels: LCUS, problem
