### ISSUE TITLE
The mistake in the example #1 about  Verbal Arithmetic Puzzle(#1307).

### ISSUE THREAD

**Issue by gogojoe520** [LeetCode-Feedback/LeetCode-Feedback#7508] opened 2022-05-30 02:53 UTC
#### Description of the bug
Iin the descript of example #1 about  Verbal Arithmetic Puzzle(#1307),
there is a mistake should be corrected.

Input: bottom = "BCD", allowed = ["BCC","CDE","CEA","FFF"]
Output: true
Explanation: The allowed triangular patterns are shown on the right.
Starting from the bottom (level 3), 
we can build "CE" on level 2 and then build "E" on level 1. *********<== mistake *********
we can build "CE" on level 2 and then build "A" on level 1. *********<== It should be "A", *********

#### Code you used for Submit/Run operation
not available

#### Expected behavior
we can build "CE" on level 2 and then build "A" on level 1. *********<== It should be "A", *********

#### Screenshots
not available

#### Additional context
not available

**Comment by LC-Pam** [comment] 2022-05-31 02:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Can you confirm the problem name and specific example showing in the problem?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 00:39
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 00:39 UTC
Labels: LCUS, problem
