### ISSUE TITLE
Missing Test Case - 218. The Skyline Problem

### ISSUE THREAD

**Issue by uKER** [LeetCode-Feedback/LeetCode-Feedback#13676] opened 2023-05-25 03:46 UTC
#### Your LeetCode username
uKER

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Missing test case for two consecutive buildings of the same height with a gap between them.

#### Code you used for Submit/Run operation
```
var buildings = new int[][] {
	new int[] {2,5,10},
	new int[] {6,9,10}
};
```

#### Language used for code
C#

#### Expected behavior
The expected output is [2, 10], [5, 0], [9, 0]
Some implementation of the algorithm can just assume it's two consecutive buildings with the same height and just ignore the gap.

**Comment by LC-Pam** [comment] 2023-05-26 20:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-30 20:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-30 20:40 UTC
Labels: LCUS, problem
