### ISSUE TITLE
416. Partition Equal Subset Sum Test Case

### ISSUE THREAD

**Issue by r2roesk** [LeetCode-Feedback/LeetCode-Feedback#256] opened 2020-05-05 02:40 UTC
What kind of the bug

 [x] problem
 [x] solution
 [] language

New test case 

what language is your code written in: python3

The code you submit/run:
```
 def canPartition(self, nums: List[int]) -> bool:
        sm = sum(nums)
       
        if sm%2 != 0 or len(nums) <= 1:
            return False
        
        dp = [[False]*((sm//2)+1) for i in range(len(nums))]
        
        for row in range(len(dp)):
            dp[row][0] = True
            
        dp[0][nums[0]] = True
        
        sm = nums[0]
        
        for i in range(1, len(dp)):
            sm += nums[i]
            for j in range(1,len(dp[0])):
                if dp[i-1][j]:
                    dp[i][j] = True
                elif  sm-j < len(dp[0]):
                    dp[i][j] = dp[i-1][sm-j]
        return dp[-1][-1]
        
```
Expected behavior:  This test case fails when I run it but still is accepted as a solution: [9,2]

Anything with nums[0] being higher than half of sum of all elements.

**Comment by CooperCooperCooper** [comment] 2020-05-05 04:17
Hi @r2roesk ,
Thank you for reaching out to us. Would you please share with us which test case failed?

**Comment by r2roesk** [comment] 2020-05-05 04:35
[9,2] or anything with nums[0] being higher than half of sum of all elements.

**Comment by CooperCooperCooper** [comment] 2020-05-06 20:48
Hi @r2roesk ,
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment] 2020-05-08 00:22
Hi @r2roesk ,

Thank you for your time. Upon our investigation, the test case [9,2] is not failing with the submitted code. 

In the future, please consider submitting the submission code in the submission link format like this: https://leetcode.com/submissions/detail/335570343/. This helps us to assess and target the issue quickly. 

If you have any other questions about this issue, please feel free to tag me in a new comment. We appreciate your support.

**Comment by r2roesk** [comment] 2020-05-14 02:49
Hi. It does fail. Sorry you have to use array elements that their sum is odd. Try [9,3]

**Comment by r2roesk** [comment] 2020-05-14 02:50
@CooperCooperCooper also that link is 404

**Comment by CooperCooperCooper** [comment] 2020-05-15 00:10
Hi @r2roesk ,
Thank you for your clarification. I've filed this update to our team to investigate.

**Comment by CooperCooperCooper** [comment] 2020-05-15 03:36
Hi @r2roesk ,
Thank you for your time. We were still unable to reproduce this issue for test case [9,3] because your code returns Runtime Error. Please double-check.

**Comment by r2roesk** [comment] 2020-05-15 03:45
@CooperCooperCooper hi. Yes it fails. That’s what I’m saying. But it doesn’t fail when I submit it. Isn’t that incorrect?

**Comment by CooperCooperCooper** [comment] 2020-05-27 21:50
Hi @r2roesk ,

Can you please share a screenshot of the "fails" and non-"fail" comparison here so we can take a better look at this issue from your end?

**Comment by CooperCooperCooper** [comment] 2020-06-04 21:52
Hi @r2roesk ,
Since you have not responded to this ticket for a while, I will close it for now. If you have more information to add to your message, please tag me in a new comment. Thank you.

**Closed by CooperCooperCooper** 2020-06-04 21:52 UTC
Labels: LCUS, problem
