### ISSUE TITLE
Question - Problems 5, 198, 213 expecting incorrect answers

### ISSUE THREAD

**Issue by matthewcuan** [LeetCode-Feedback/LeetCode-Feedback#14150] opened 2023-06-15 20:35 UTC
#### Your LeetCode username
matthewcuan

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When adding my own test cases to certain problems, all test cases return incorrect (the expected answer field is empty), despite having been correct prior to adding an additional test case. However, when submitting, the code will pass. Even if the additional test case is identical to a default test case, all test cases still return incorrect. 

This occurs with a select few problems. Of the ones that I have attempted so far, this issue occurs with problems 5 (Longest Palindromic Substring), 198 (House Robber), and 213 (House Robber II).

#### Code you used for Submit/Run operation

Code I used for 198 (House Robber)
```
class Solution:
    def rob(self, nums: List[int]) -> int:

        rob1, rob2 = 0, 0

        for n in nums:
            temp = max(n + rob1, rob2)
            rob1 = rob2
            rob2 = temp

        return rob2
```

#### Language used for code
Python

#### Expected behavior
When adding an additional, valid test case, all the test cases should still return Correct.

**Comment by LC-Pam** [comment] 2023-06-20 19:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The submission AC link for each reported problem. (5, 198, 213)
The additional, valid test cases.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-22 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-22 18:15 UTC
Labels: LCUS, problem
