### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by malyshevig** [LeetCode-Feedback/LeetCode-Feedback#11910] opened 2023-02-21 16:03 UTC
#### Category of the bug
- [+ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

-2147483648 / -1 = 2147483648

#### Screenshots

Input
dividend =
-2147483648
divisor =
-1
Output
2147483648
Expected
2147483647

**Comment by LC-Pam** [comment] 2023-02-21 19:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ahmmed-sde** [comment] 2023-02-22 01:10
hey @malyshevig 
There is no Issues in this problem(```29. Divide Two Integers```) for this particular test case(```-2147483648, -1```).
I think you don't understand the problem clearly.
So please read the problem carefully, you will find the solution.

**Comment by LC-Pam** [comment] 2023-02-22 18:35
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-22 18:35 UTC
Labels: LCUS, problem
