### ISSUE TITLE
Missing Test Case - 143. Reorder List

### ISSUE THREAD

**Issue by Mayurmunje9** [LeetCode-Feedback/LeetCode-Feedback#17428] opened 2023-10-24 19:08 UTC
#### Category of the bug

- [ ] Solution

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public void reorderList(ListNode head) {
        ListNode fast=head,slow=head,start=head;
        int count=0;
        while(fast.next!=null && fast.next.next!=null){
            count++;
            slow=slow.next;
            fast=fast.next.next;
        }
        ListNode ab=slow.next;
        ListNode del=slow.next;
        ListNode prev=slow;
        ListNode curr=slow.next;
        ListNode next;
        while(curr!=null){
            next=curr.next;
            curr.next=prev;
            prev=curr;
            curr=next;
        }
        slow.next=prev;
        del.next=null;
        // The half part is now reversed

        ListNode firstHead=head;
        ListNode secondHead=prev;

       while (firstHead.next!= null && secondHead != null) {
    ListNode temp = firstHead.next;
    firstHead.next = secondHead;
    firstHead = temp;

    temp = secondHead.next;
    secondHead.next = firstHead;
    secondHead = temp;
}

        if(firstHead!=null){
            firstHead.next=null;
        }
        
        
        


    }
}
```

**Comment by LC-Pam** [comment] 2023-10-25 18:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-27 19:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-27 19:03 UTC
Labels: Waiting for Reply
