### ISSUE TITLE
Test Case Wrong in the Contest first question

### ISSUE THREAD

**Issue by RiyaGupta89** [LeetCode-Feedback/LeetCode-Feedback#12455] opened 2023-03-19 14:56 UTC
#### Your LeetCode username
<!riyagupt08

#### Category of the bug
- [x] Question

#### Description of the bug

Example 2:- 1 is present at index 0 and not at 1st index therefore output is also wrong.

#### Expected behavior

Test case should say that 1 is present at 0th index.

#### Screenshots
![image](https://user-images.githubusercontent.com/72425181/226184352-78bee6ff-800e-4f67-afb8-04066aa091d2.png)

**Comment by RiyaGupta89** [comment] 2023-03-19 14:58
Problem number:-  2595

**Comment by LC-Pam** [comment] 2023-03-19 23:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by nskybytskyi** [comment] 2023-03-20 18:18
> Example 2:- 1 is present at index 0 and not at 1st index therefore output is also wrong.
> Test case should say that 1 is present at 0th index.

I'm afraid you misunderstood the problem. Bits are indexed starting from the least significant bit. In other words, 0th bit is always the rightmost one, regardless of how long the binary representation is.

**Comment by LC-Pam** [comment] 2023-03-22 20:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-22 20:29 UTC
Labels: LCUS, problem
