### ISSUE TITLE
Missing Test Case - 1059. All Paths from Source Lead to Destination

### ISSUE THREAD

**Issue by madamut** [LeetCode-Feedback/LeetCode-Feedback#16669] opened 2023-09-24 16:24 UTC
#### Your LeetCode username

madamut

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
From the description of the problem, it looks to me that there is no guarantee that the "edges" input parameter is sorted by the starting node. I've written a solution in Java that takes advantage of this and gets 2ms execution time and passes all the tests.

#### Code you used for Submit/Run operation

```
class Solution {
    
    private short[] nodeIndex;
    private boolean[] visited;
    private boolean[] cache;
    private int[][] edges;
    private int destination;
    private static short NO_IDX = (short) -1;
    
    
    public boolean leadsToDestination(int n, int[][] edges, int source, int destination) {
        if(edges.length == 0) {
            return source == destination;
        }
            
        this.destination = destination;
        this.edges = edges;
        
        //sort the edges
        //Arrays.sort(edges,(o1, o2) -> Integer.compare(o1[0], o2[0]));
        
        //node index
        nodeIndex = new short[n];
        Arrays.fill(nodeIndex, NO_IDX);
        int currentNode = edges[0][0];
        nodeIndex[currentNode] = 0;
        for(int i = 0; i < edges.length; i++) {
              if(currentNode != edges[i][0]) {
                  currentNode = edges[i][0];
                  nodeIndex[currentNode] = (short) i;
              }
        }
        
        //visited nodes
        visited = new boolean[n];
        //resolved nodes
        cache = new boolean[n];
        
        return traverse(source);
    }
    
    private boolean traverse(int currentNode) {
        //if this node processed already
        if(cache[currentNode]) return true;
        
        boolean result = true;
        if(visited[currentNode]) {
            result = false;
        } else {
            if(nodeIndex[currentNode] == NO_IDX) {
                result = currentNode == destination;
            } else {
                visited[currentNode] = true;
                int currentNodeIdx = nodeIndex[currentNode];
                while(currentNodeIdx < edges.length && edges[currentNodeIdx][0] == currentNode) {
                    boolean t = traverse(edges[currentNodeIdx++][1]);
                    if(!t) {
                        result = false;
                        break;
                    }
                }
                visited[currentNode] =  false;
            }
        }
        
        if(result) cache[currentNode] = result;
        return result;
    }
}
```

#### Expected behavior

There should be a test case that verifies the algorithm works correctly if the edges are not sorted.

**Comment by LC-Pam** [comment] 2023-09-26 14:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-28 16:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-28 16:00 UTC
Labels: Waiting for Reply
