### ISSUE TITLE
sizeof(arr)/sizeof(arr[0]) not working properly

### ISSUE THREAD

**Issue by kash03cow** [LeetCode-Feedback/LeetCode-Feedback#10732] opened 2023-01-03 14:33 UTC
When I was trying to submit the leetcode daily question, I found out this bug on leetcode.
sizeof(strs)/sizeof(strs[0]) was working completly fine in my vs code, but not on leetcode.
ON leetcode it was returning 0 all the time.
#### Your LeetCode username

https://leetcode.com/keshav_bansal/
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Sizeof not working
class Solution {
public:
        int sizenotworking(vectors<string>& strs){
        return sizeof(strs)/sizeof(strs[0]);
    }

};
```

#### Expected behavior

sizeof(strs)/sizeof(strs[0]) should give me the size of the array

**Comment by LC-Pam** [comment] 2023-01-04 19:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-07 15:37
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-07 15:37 UTC
Labels: LCUS, problem
