### ISSUE TITLE
Missing Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by arslaan07** [LeetCode-Feedback/LeetCode-Feedback#8452] opened 2022-07-31 11:15 UTC
#### Category of the bug
- [ ] Question
- [1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Valid Sudoku
class Solution {
public:
    bool IsValid(vector<vector<char>> &board,char c,
                int row,int col){
        for(int i=0;i<9;i++){
            if(board[row][i]==c){
                return false;
            }
            if(board[i][col]==c){
                return false;
            }
            if(board[3*(row/3)+i/3][3*(col/3)+i%3]==c){
                return false;
            }
        }
        return true;
    }
public:
    bool isValidSudoku(vector<vector<char>>& board) {
        for(int i=0;i<board.size();i++){
            for(int j=0;j<board[i].size();j++){
                if(board[i][j]=='.'){
                    for(char c='1';c<='9';c++){
                        if(IsValid(board,c,i,j)){
                            board[i][j]=c;
                            if(isValidSudoku(board)==true){
                                return true;
                            }
                            board[i][j]='.';
                        }
                    }
                    return false;
                }
            }
        }
        return true;
    }
};
```

**Comment by LC-Pam** [comment] 2022-08-01 18:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-03 16:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-03 16:44 UTC
Labels: LCUS, problem
