### ISSUE TITLE
Solutions don't run - 1448 Count Good Nodes in Binary Tree

### ISSUE THREAD

**Issue by xkyyxj** [LeetCode-Feedback/LeetCode-Feedback#2188] opened 2021-01-30 09:54 UTC
With the test case: [3,3,null,4,2],  execute my code, the result is right, but commit with same code,  leetcode return message that the result is wrong with this test case. Here is my code:

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    public static int count = 0;
	public int goodNodes(TreeNode root) {
		List<TreeNode> nodePath = new LinkedList<>();
		goodNodesDeep(root, nodePath);
		return count;
	}
	
	public void goodNodesDeep(TreeNode root, List<TreeNode> pathRoot) {
		if(root == null) {
			return;
		}
		
		Boolean isRight = true;
		for(int i = 0;i < pathRoot.size() && isRight;i++) {
			if(root.val < pathRoot.get(i).val) {
				isRight = false;
			}
		}
		if(isRight) {
			++count;
		}
		
		if(root.left != null) {
			pathRoot.add(root);
			goodNodesDeep(root.left, pathRoot);
			pathRoot.remove(pathRoot.size() - 1);
		}
		if(root.right != null) {
			pathRoot.add(root);
			goodNodesDeep(root.right, pathRoot);
			pathRoot.remove(pathRoot.size() - 1);
		}
		
	}
}

**Comment by lc-kay** [comment] 2021-02-01 23:17
@xkyyxj Please provide the submission details link so we can reproduce the issue. Thank you!

**Comment by lc-kay** [comment] 2021-02-10 19:55
Hi @xkyyxj 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-02-10 19:55 UTC
Labels: LCUS, watchlist
