### ISSUE TITLE
Missing Test Case - 2911. Minimum Changes to Make K Semi-palindromes

### ISSUE THREAD

**Issue by sober-Sherlock** [LeetCode-Feedback/LeetCode-Feedback#17466] opened 2023-10-26 03:51 UTC
#### Your LeetCode username

海风吹过的夏天

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

测试样例的答案有问题，字符串“acba" 2 这个测试样例只需要修改一个字符即可。因为我们可以把这个字符串拆分成”acb"和“a“,这样只需将第一个字符串里的字符"a"修改成字符”b",或者字符"b"修改成字符“a"即可。为此，答案应该是1，而不是2。

#### Language used for code

'''
class Solution {
public:
    int segment_mini(string& s,int start,int end)
    {
        int len = end - start + 1;
        int min = len;
        int count;
        int left;
        int right;
        for(int i = 1;i < len;i++)
        {
            if(len % i == 0)
            {
                count = 0;
                for(int j = 0;j < i;j++)
                {
                    left = start + j;   
                    right = end - i + 1;
                    while(left < right)
                    {
                        if(s[left] != s[right])
                            count++;
                        left += i;
                        right -= i;
                    }
                }
                if(count < min)
                    min  = count;
            }
        }
        
        return min;
    }
    int minimumChanges(string s, int k) {
        //s组成简单正常，长度字少为2，且k范围正常，自然定义域与题目要求合理定义域都正常
        int len = s.size();
        vector<vector<int>> dp_table(len,vector<int>(k+1,len));  //用空间减少一点编程,以及赋值方便自己处理
        
        for(int i = 0; i <= k;i++)
            dp_table[0][i] = 0;
        for(int i = 1;i < len;i++)
        {
            dp_table[i][0] = 0;
            dp_table[i][1] = segment_mini(s,0,i);
        }
        
        int temp;
        for(int i = 1;i < len;i++)
        {
            //dp_table[i][1] = segment_mini(s,0,i);
            for(int j = 2;j <= k;j++)
            {
                if(i < j)
                {
                    dp_table[i][j] = 0;
                    continue;
                }
                
                //最少前面至少有j-1段
                for(int start = j - 1;start <= i;start++)
                {
                        dp_table[i][j] = min(dp_table[i][j],dp_table[start-1][j-1] + segment_mini(s,start,i));
                }
                //dp_table[i][j] = min(dp_table[i][j],dp_table[i-1][j-1]);
            }
        }
        
        return dp_table[len-1][k];
    }
};
'''

#### Expected behavior

期待上述测试样例答案的修正。

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/c4e4808f-4967-45c3-b63d-796b2f915e19)

**Comment by LC-Pam** [comment] 2023-10-27 19:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 17:55
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 17:55 UTC
Labels: Waiting for Reply
