### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Hiteker67** [LeetCode-Feedback/LeetCode-Feedback#14873] opened 2023-07-19 02:23 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        set<int>r;
        set<int>c;
        int rows=matrix.size();
        int cols=matrix[0].size();
        for(int i=0;i<rows;i++){
            for(int j=0;j<cols;j++){
                if(matrix[i][j]==0){
                    r.insert(i);
                    c.insert(j);
                }
            }
        }

        //now comes the part of making rows and col = 0
        //for rows
        for(auto i:r){
            for(int j=0;j<cols;j++){
                matrix[i][j]=0;
            }
        }

        // for cols
        for(auto j:c){
            for(int i=0;i<rows;i++){
                matrix[i][j]=0;
            }
        }
        
    }
};
```

**Comment by LC-Pam** [comment] 2023-07-19 15:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Hiteker67** [comment] 2023-07-19 17:09
test case 75

**Comment by LC-Pam** [comment] 2023-07-20 19:13
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-25 21:18
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-25 21:18 UTC
Labels: LCUS, problem, Waiting for Reply
