### ISSUE TITLE
Missing Test Case - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by Mayank6768** [LeetCode-Feedback/LeetCode-Feedback#18097] opened 2023-11-16 09:34 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
/**
 * @return {null|boolean|number|string|Array|Object}
 */
Array.prototype.last = function () {
    const length = this.length
    const lastIndex = length - 1
    if (length === 0) {
        return lastIndex
    }
    else {
        return this[lastIndex]
    }

};

const arr2 = [null, {}, 3]
arr2.last()
const arr = [];
arr.last(); // 3
```

**Comment by LC-Pam** [comment] 2023-11-16 16:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:07
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:07 UTC
Labels: Waiting for Reply
