### ISSUE TITLE
LeetCode -> TwoSum Challenge

### ISSUE THREAD

**Issue by gpavankumarnov** [LeetCode-Feedback/LeetCode-Feedback#17759] opened 2023-11-02 08:06 UTC
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.

Example 1:
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

**Solution:**
var twoSum = function(nums, target) {
  const obj = {
//number: index
 //2:0
  };

//loop through array
    for(let i=0; i<nums.length; i++){

    //check the difference with the current number    
   let diff = target - nums[i];
       // 7=2-9
 //if difference is presented in obj then return the final
 //otherwise add it
       if(diff in obj){
       return [obj[diff], i]
       }else{
   obj[nums[i]] = i
       }     
    }

   return []  
};

twoSum([2,7,11,15], 9);

**Comment by LC-Pam** [comment] 2023-11-02 19:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-13 17:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-13 17:27 UTC
Labels: Waiting for Reply
