### ISSUE TITLE
Missing Test Case - 1976. Number of Ways to Arrive at Destination

### ISSUE THREAD

**Issue by Rutvik0512** [LeetCode-Feedback/LeetCode-Feedback#14615] opened 2023-07-08 09:03 UTC
#### Your LeetCode username
Rutvik0512

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

This is an edge case that's failed due to the non-usage of "long" datatype

#### Code you used for Submit/Run operation

```
// Two Sum
class WeightPair{
    int vertex;
    long weight;
    WeightPair(int _v, long _w){
        vertex = _v;
        weight = _w;
    }
}

class Pair{
    int vertex;
    long distance;
    Pair(int _v,long _d){
        vertex = _v;
        distance = _d;
    }
}

class Solution {
    public int countPaths(int n, int[][] roads) {
        ArrayList<ArrayList<WeightPair>> al = new ArrayList<>();
        
        for(int i=0;i<=n;i++){
            al.add(new ArrayList<WeightPair>());
        }
        
        for(int i=0;i<roads.length;i++){
            int u = roads[i][0];
            int v = roads[i][1];
            long w = (long)roads[i][2];
            al.get(u).add(new WeightPair(v,w));
            al.get(v).add(new WeightPair(u,w));
        }
        
        // System.out.println(al);
        int m = (int)1e9 +7;
        
        long dist[] = new long[n];
        Arrays.fill(dist,Long.MAX_VALUE);

        dist[0] = 0L;
        int paths[] = new int[n];
        paths[0] = 1;
        
        PriorityQueue<Pair> pq = new PriorityQueue<>((a,b)->  (int)(a.distance-b.distance));
        pq.add(new Pair(0,0));
        
        
        while(!pq.isEmpty()){
            Pair temp = pq.poll();
            int parent = temp.vertex;
            long distance = temp.distance;
            for(WeightPair neighbor: al.get(parent)){
                long new_distance = distance + neighbor.weight;
                if(new_distance < dist[neighbor.vertex]){
                    dist[neighbor.vertex] = new_distance;
                    pq.add(new Pair(neighbor.vertex,new_distance));
                    paths[neighbor.vertex] = paths[parent]%m;
                }
                else if(new_distance == dist[neighbor.vertex]){
                    paths[neighbor.vertex] =  (paths[neighbor.vertex] + paths[parent]) %m;
                }
            }
        }
        
        return paths[n-1];  
    }
}
```

#### Language used for code

Java

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88983725/0f49c444-8b66-4216-a060-df806922bdd3)
After correction
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88983725/d6caab33-154d-4021-a33c-3c9c0936f115)

**Comment by LC-Pam** [comment] 2023-07-11 23:19
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-12 19:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-12 19:08 UTC
Labels: LCUS, problem

**Comment by Rutvik0512** [comment] 2023-07-13 07:57
Hey I didnt see the message. Here is the missing test case:
6 8
0 1 1000000000
0 3 1000000000
1 3 1000000000
1 2 1000000000
1 5 1000000000
3 4 1000000000
4 5 1000000000
2 5 1000000000

Expected output: 2
