### ISSUE TITLE
Invalid Accepted Return Value - 2221. Find Triangular Sum of an Array

### ISSUE THREAD

**Issue by akshajmody** [LeetCode-Feedback/LeetCode-Feedback#8474] opened 2022-08-02 06:31 UTC
#### Your LeetCode username
akshajmody

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**Using JAVASCRIPT:** The expected return value for this question is an **number** as described in the examples. I am able to submit and **pass test cases where my return value is an array containing the final number**, rather than the number itself. 

`[8]` as a return value is passing when it should be simply `8`

#### Code you used for Submit/Run operation

```
  let newArr = nums;
  let temp = [];
  function pascal(array) {
    for (let i = 0; i <= array.length - 2; i++) {
      let sum = array[i] + array[i + 1];
      if (sum > 9) {
        temp.push(sum - 10);
      } else {
        temp.push(sum);
      }
    }
    console.log(temp);
    newArr = temp;
    temp = [];
  }
  while (newArr.length > 1) {
    pascal(newArr);
  }
  return newArr;
```

#### Language used for code
Javascript

#### Expected behavior
With the my current code, I should not pass test cases since I am returning an array. The expected behavior is to return a number only, not a number within an array.

**Comment by LC-Pam** [comment] 2022-08-02 17:52
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-04 18:36
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-04 18:36 UTC
Labels: LCUS, problem
