### ISSUE TITLE
Missing Test Case - 1238. Circular Permutation in Binary Representation

### ISSUE THREAD

**Issue by Tikshanshu** [LeetCode-Feedback/LeetCode-Feedback#15475] opened 2023-08-10 12:06 UTC
#### Your LeetCode username
Tikshanshu

#### Category of the bug
- [ 1238] Question
- [ ] Solution
- [c++ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[2,6,7,5,4,3,1,0] this can be one of the valid answer for test case n=3 and start=2.

#### Code you used for Submit/Run operation
class Solution {
public:
vector<int>tik;
    void solve(int y,vector<int>&ans,int start,vector<int>&v,vector<bool>&b)
    {
           if(ans.size()==y)
           {
               if(abs(__builtin_popcount(ans[y-1])-__builtin_popcount(ans[0]))==1)
                    tik=ans;
              return;
           }
          

        for(int i=1;i<v.size();i++ )
        {   
            int one1=abs(__builtin_popcount(start)-__builtin_popcount(v[i]));
         
            if(!b[i] && one1==1 )
            {
                   cout<<v[i]<<" ";
            ans.push_back(v[i]);
            b[i]=true;
            solve(y,ans,v[i],v,b);
            ans.pop_back();
            cout<<"---";
            b[i]=false;
            }
        }
    }
    vector<int> circularPermutation(int n, int start) {
        vector<int>v;

        v.push_back(start);
        int y=pow(2,n);
        for(int i=0;i<y;i++)
        {
            if(i!=start)
            
            v.push_back(i);
        }
        vector<int>ans;
        vector<bool>b(v.size(),false);
        ans.push_back(start);
        solve(y,ans,start,v,b);
        return tik;
    }
};

#### Language used for code
C++

#### Expected behavior
[2,6,7,5,4,3,1,0]  can be a valid answer

**Comment by LC-Pam** [comment] 2023-08-11 19:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-16 19:49
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-16 19:49 UTC
Labels: LCUS, problem, Waiting for Reply
