### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by ShubhodeepDutta** [LeetCode-Feedback/LeetCode-Feedback#12970] opened 2023-04-15 05:52 UTC
#### Your LeetCode username

ShubhodeepDutta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

I have found a test case for which my code gives wrong result.

#### Code you used for Submit/Run operation

```
class TimeMap:

    def __init__(self):
        self.timeMap = dict()       

    def set(self, key: str, value: str, timestamp: int) -> None:
        if key not in self.timeMap.keys():
            self.timeMap[key] = [(timestamp, value)]
        else:
            self.timeMap[key].append((timestamp, value))

    def get(self, key: str, timestamp: int) -> str:
        if key in self.timeMap.keys() and self.timeMap[key]:
            left = 0
            right = len(self.timeMap[key])-1
            arr = self.timeMap[key]

            while left < right:
                mid = (left + right) // 2
                if arr[mid][0] < timestamp and arr[mid+1][0] <= timestamp:
                    left = mid+1
                elif arr[mid][0] > timestamp and arr[mid-1][0] >= timestamp:
                    right = mid-1
                else:
                    if arr[right][0] == timestamp:
                        return arr[right][1]
                    elif arr[left][0] <= timestamp:
                        return arr[left][1]
                    else: return ""

            if arr[right][0] == timestamp:
                return arr[right][1]
            elif arr[left][0] <= timestamp:
                return arr[left][1]
            else: return ""
        else:
            return ""
        


# Your TimeMap object will be instantiated and called as such:
# obj = TimeMap()
# obj.set(key,value,timestamp)
# param_2 = obj.get(key,timestamp)
```

#### Language used for code

Python

#### Expected behavior

Expected Output -
[null,null,null,null,null,null,null,null,"bar4"]

Output-
[null,null,null,null,null,null,null,null,"bar"]

#### Screenshots

![image](https://user-images.githubusercontent.com/29196539/232187131-823492dc-994d-424f-8c6a-4055ae3c133d.png)

**Comment by LC-Pam** [comment] 2023-04-18 22:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case in text format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-21 18:11
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-21 18:11 UTC
Labels: LCUS, problem
