### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by jhashashi** [LeetCode-Feedback/LeetCode-Feedback#4780] opened 2021-09-14 07:28 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

We have to deserialize and then serialize the same . We can store the root value in a static variable and return the same which will give out the answer.
Instead we should check the intermediate solution after deserialization and then after serialization.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment] 2021-09-14 19:05
@jhashashi Can you please provide more details on the issue you are reporting? What's the current behavior and expected behavior?

**Comment by lc-kay** [comment] 2021-10-06 19:01
Hi @jhashashi 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-10-06 19:01 UTC
