### ISSUE TITLE
Missing Test Case - 25. Reverse Nodes in k-Group

### ISSUE THREAD

**Issue by Harsh-2503** [LeetCode-Feedback/LeetCode-Feedback#8628] opened 2022-08-11 13:37 UTC
#### Your LeetCode username

Harsh-2003

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ ] One test case has wrong answer

#### Description of the bug

Input
[1,2,3,4]
4
Output
[4,2,3,1]
Expected
[4,3,2,1]

#### Code you used for Submit/Run operation

```
class Solution:
    def reverseKGroup(self, head: Optional[ListNode], k: int) -> Optional[ListNode]:
        dummy = head
        temp1 = None
        temp2 = None
        n = 1
        while head != None:
            if n == 1:
                temp1 = head
            if n == k:
                temp2 = head
                if temp1 and temp2:
                    self.helper(temp1,temp2,dummy)
                    n = 0
                    temp1 = None
                    temp2 = None
            head = head.next
            n +=1
        return dummy
    
    def helper(self,l1,l2,l):
        temp = l1.val
        while l:
            if l == l1:
                l.val = l2.val
                l = l.next
                continue
            if l == l2:
                l.val = temp
                break
            l = l.next
        return
```

#### Language used for code
\

**Comment by LC-Pam** [comment] 2022-08-11 23:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-15 01:01
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-15 01:01 UTC
Labels: LCUS, problem
