### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by ankitkhadria1** [LeetCode-Feedback/LeetCode-Feedback#12633] opened 2023-03-28 18:34 UTC
#### Your LeetCode username
ankitkhadria1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In Longest Palindromic Substring, output should be longest substring which in palindrome, so if you see the result with input value

s = `"aacabdkacaa`" output can be `"aacabacaa"` but system is not accepting it.

#### Code you used for Submit/Run operation
```

# @param {String} s
# @return {String}
def longest_palindrome(s)

    rev_s = s.reverse()
    n = s.length
    m = rev_s.length

    dp = (0..n).map { |_i| [-1] * (m + 1)}
    (0..n).each do |i|
        (0..m).each do |j|

            if i == 0 || j == 0
                dp[i][j] = 0
            elsif s[i-1] == rev_s[j-1]
                dp[i][j] = 1 + dp[i-1][j-1]
            else
                dp[i][j] = [dp[i-1][j], dp[i][j-1]].max
            end
        end
    end

    # Backtrack the DP matrix
    i = n
    j = m
    pal_lcs_sub = ""

    while i > 0 && j > 0

        if s[i-1] == rev_s[j-1]
            pal_lcs_sub = s[i-1] + pal_lcs_sub
            i -= 1
            j -= 1
        elsif dp[i][j-1] > dp[i-1][j]
            j -= 1
        else
            i -= 1
        end
    end
    pal_lcs_sub
end

```

#### Language used for code
Ruby

#### Expected behavior
Test result is giving wrong output for input value `"aacabdkacaa"` 

 Output should be `"aacabacaa"`,
 
  but the system is showing `"aca"`

**Comment by nskybytskyi** [comment] 2023-03-28 19:13
Duplicate of #12435

**Comment by LC-Pam** [comment] 2023-03-29 23:24
A quote from the pop-up that appears when you hover over the word "substring" in the statement:

A substring is a contiguous non-empty sequence of characters within a string.

"aacabacaa" is hence not a substring of "aacabdkacaa" since its characters are not consecutive. Perhaps your solution finds the [longest palindromic subsequence](https://leetcode.com/problems/longest-palindromic-subsequence/) (problem no. 516) instead?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Closed by LC-Pam** 2023-03-29 23:24 UTC
