### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by Maga-create** [LeetCode-Feedback/LeetCode-Feedback#13384] opened 2023-05-10 02:04 UTC
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

![2023-05-09 (1)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/80921538/fcf0d0a1-7609-47b0-9e77-b85cf6a56329)

**Comment by LC-Pam** [comment] 2023-05-10 22:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-12 21:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-12 21:34 UTC
Labels: LCUS, problem
