### ISSUE TITLE
Missing Test Case - 1252. Cells with Odd Values in a Matrix

### ISSUE THREAD

**Issue by MuhammadSaad20** [LeetCode-Feedback/LeetCode-Feedback#18302] opened 2023-11-26 11:18 UTC
### Problem number, title, and link
Problem Number 1252
https://leetcode.com/problems/cells-with-odd-values-in-a-matrix/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
Add this case it cover inbound index case m=5,   n=4 , incides[[2,3]]

```

### Expected behavior
expected output is 7

### Additional context
its not a bug just want add this test case

**Comment by LC-Pam** [comment] 2023-11-28 19:32
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-01 21:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-01 21:40 UTC
Labels: Waiting for Reply
