### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by YujenM** [LeetCode-Feedback/LeetCode-Feedback#17300] opened 2023-10-18 04:51 UTC
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Reverse Integer
class Solution(object):
    def reverse(self, x):
        """
        :type x: int
        :rtype: int
        """
        if x < 0:
            sign = -1
            x = abs(x)
        else:
            sign = 1

        b = 0
        while x != 0:
            a = x % 10
            b = b * 10 + a
            x = x // 10

        if b > 2**31 - 1:
            return 0

        return b * sign

```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121010820/bcb37cc9-6555-4061-a092-30154131d701)

**Comment by LC-Pam** [comment] 2023-10-18 19:17
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug or issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-20 20:05
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-20 20:05 UTC
Labels: Waiting for Reply
