### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by artanmerko** [LeetCode-Feedback/LeetCode-Feedback#16935] opened 2023-10-04 15:18 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
function ListNode(val, next) {
    this.val = (val===undefined ? 0 : val);
    this.next = (next===undefined ? null : next);
}

var addTwoNumbers = function(l1, l2) {
    let dummy = new ListNode(0);
    let current = dummy;
    let carry = 0;
    
    while (l1 !== null || l2 !== null || carry) {
        let sum = carry;
        
        if (l1) {
            sum += l1.val;
            l1 = l1.next;
        }
        
        if (l2) {
            sum += l2.val;
            l2 = l2.next;
        }
        
        if (sum >= 10) {
            carry = 1;
            sum -= 10;
        } else {
            carry = 0;
        }

        current.next = new ListNode(sum);
        current = current.next;
    }
    
    return dummy.next;
};

```

#### Language used for code
JS

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97398977/76bdbeda-0188-4297-aa1f-532da9a991fc)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97398977/cbc3cdb6-dd2c-4aa9-b7e1-ad882755c88a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97398977/c812bd6b-2023-4b8e-aca1-eb515ed15fda)

**Comment by LC-Pam** [comment] 2023-10-04 16:57
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug or the issue of this problem. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-09 18:37
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-09 18:37 UTC
Labels: Waiting for Reply
