### ISSUE TITLE
##Output Mismatch even the program output the correct result with other compiler

### ISSUE THREAD

**Issue by mk14lib** [LeetCode-Feedback/LeetCode-Feedback#13770] opened 2023-05-30 14:27 UTC
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59381047/1df81023-8786-49c2-a0d2-d148832f99da)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59381047/95cd4b15-188e-4deb-a8c2-5420103b060b)

**_Code :_**

`

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define I 1
#define V 5
#define X 10
#define L 50
#define C 100
#define D 500
#define M 1000

int value = 0;
int romanToInt(char * s){
    for(int i=0; i<=strlen(s); i++)
    {
        while(*s != '\0')
        {
            
            if(*s == 'I') {
                if(*(1+s) == 'V') 
                {
                    value+=(V-I); 
                    s++;
                }
                else if(*(1+s) == 'X') {
                    value+=(X-I);
                    s++;
                }
                else value+=I;
            }
            else if(*s == 'V') {
                value+=V;
            }
            else if(*s == 'X') {
                if(*(1+s) == 'L') {
                    value+=(L-X);
                    s++;
                }
                else if(*(1+s) == 'C') {
                    value+=(C-X);
                    s++;
                }
                else value+=X;
            }
            else if(*s == 'L') {
                value+=L;
            }
            else if(*s == 'C') {
                if(*(1+s) == 'D') {
                    value+=(D-C);
                    s++;
                }
                else if(*(1+s) == 'M') {
                    value+=(M-C);
                    s++;
                }
                else value+=C;
            }
            else if(*s == 'D') {
                value+=D;
            }
            else if(*s == 'M') {
                value+=M;
            }
            
            s++;
        }
    }
    return value;
}

int main()
{
    char s[] = "LVIII";
    printf("%d", romanToInt(s));
    return 0;
}

`

**Comment by LC-Pam** [comment] 2023-05-31 18:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The problem issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:37
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:37 UTC
Labels: LCUS, problem
