### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by blbnv** [LeetCode-Feedback/LeetCode-Feedback#8451] opened 2022-07-31 10:51 UTC
#### Your LeetCode username
blbnv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
If the lowest price for buying stocks is at the index 0 (in 0-indexed array), there is no test case that will check it.

#### Code you used for Submit/Run operation

```
class Solution {
    func maxProfit(_ prices: [Int]) -> Int {
        var buy = prices[1]
        var profit = 0
        
        for i in 1..<prices.count {
            let sell = prices[i]
            profit = max(profit, sell-buy)
            buy = min(buy, sell)
        }
        
        return profit
    }
}
```

#### Language used for code
Swift

#### Expected behavior
The platform accepts the solution above, where I've put a price at index 1 (in 0-indexed array) as a start price.

Seems like there is no test case when the best price to buy is at index 0, because the code above is green during submission.

My proposal is to add `[1,7,5,3,6,4]` as an additional test case. 

Thanks!

#### Screenshots

N/A.

#### Additional context

N/A.

**Comment by LC-Pam** [comment] 2022-08-01 18:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-03 16:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-03 16:44 UTC
Labels: LCUS, problem
