### ISSUE TITLE
Missing Test Case 97 ( 934. Shortest Bridge )

### ISSUE THREAD

**Issue by AnkitGunwal** [LeetCode-Feedback/LeetCode-Feedback#13602] opened 2023-05-21 14:11 UTC
- Missing Test Case
- Submission Error

<img width="644" alt="Screenshot 2023-05-21 193839" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130600098/5cda2fae-3a79-4745-abeb-296ef1ab7080">

LeetCode id : Eat_Leet_Repeat

**Comment by AnkitGunwal** [comment] 2023-05-21 18:28
Can this issued be resolved soon, as this is a daily challenge and I don't want to loose my streak.

**Comment by LC-Pam** [comment] 2023-05-23 00:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by AnkitGunwal** [comment] 2023-05-23 04:56
**This is the missing test case:** 
![](https://user-images.githubusercontent.com/130600098/239746515-5cda2fae-3a79-4745-abeb-296ef1ab7080.png)
**Submission AC link:**
https://leetcode.com/Eat_Leet_Repeat/

**Comment by LC-Pam** [comment] 2023-05-26 19:53
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-30 20:37
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-30 20:37 UTC
Labels: LCUS, problem
