### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by nikgun1984** [LeetCode-Feedback/LeetCode-Feedback#7008] opened 2022-04-15 01:57 UTC
#### Your LeetCode username
nikgun

#### Category of the bug
Missing Test Cases 

#### Description of the bug

Missing test case. For example, [-2,0,10,-19,4,6,-8,0], in this case there are 2 0s but
0*2=0. This case is not included.

**Comment by LC-Yani** [comment] 2022-04-18 21:02
Hi @nikgun1984 

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Best,

LC_Yani

**Comment by LC-Yani** [comment] 2022-04-22 17:26
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Yani** 2022-04-22 17:26 UTC
Labels: LCUS, problem
