### ISSUE TITLE
[0,10,15,12,11,17,14]

### ISSUE THREAD

**Issue by Sardik-Bhardwaj-au45** [LeetCode-Feedback/LeetCode-Feedback#7236] opened 2022-05-08 14:19 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Yani** [comment] 2022-05-09 02:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name.
The code and language you submitted to reach this result.
what is the missing test?


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-11 17:22
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-11 17:22 UTC
Labels: LCUS, problem
