### ISSUE TITLE
691. (Stickers to Spell Word) editorial not available

### ISSUE THREAD

**Issue by patrickkasper** [LeetCode-Feedback/LeetCode-Feedback#18936] opened 2023-12-26 23:22 UTC
I cannot access the editorial for [691. Stickers to Spell Word. It says "the topic does not exist." I have tried this several times across multiple days but no luck. I have the premium subscription and have solved more than 300 LC questions but this is the first time this happens, Please fix it!

**Comment by xelplogoog** [comment] 2023-12-27 01:13
I confirm. Not available, even with premium

**Comment by LC-Pam** [comment] 2024-01-04 20:14
Hello,
 
Thank you for reaching out to us.
 
Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.
 
Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.
 
To help us better find the root cause about this problem, would you mind help us generate a HAR file: https://support.zendesk.com/hc/en-us/articles/4408828867098 and Include any console logs (https://support.happyfox.com/kb/article/882-accessing-the-browser-console-and-network-logs/) in addition to a HAR file.
 
Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-23 21:21
Hi there,
 
We sincerely apologize for the delay in addressing your concern. We've experienced a high volume of tickets recently, but we are committed to resolving each one as quickly as possible.
 
Regarding the website issue you reported, our team has already implemented a fix. Could you please check and let us know if the problem still persists on your end?

If the issue still exists, please send us a support ticket at https://leetcode.com/support

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:21 UTC
Labels: in progress
