### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by randomguy70** [LeetCode-Feedback/LeetCode-Feedback#18418] opened 2023-12-02 03:40 UTC
### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Two of the 3 test cases have incorrect solutions.

### Code used for Submit/Run operation

```
import math

class Solution:
    def searchInsert(nums, target) -> int:
        left = 0
        right = len(nums)
        while left < right:
            middle = left + math.floor((right - left) / 2)
            if nums[middle] == target:
                return middle
            elif nums[middle] < target:
                left += math.floor((right - left) / 2) + 1
            elif nums[middle] > target:
                right -= math.floor((right - left) / 2) + 1
        return False
```

### Expected behavior
My code should have worked for every test case, and it did in VSCode, but since Leetcode's test cases were incorrect, it failed.

### Screenshots

<img width="646" alt="Screenshot 2023-12-01 at 9 40 10 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74500505/d7f4b294-5c5b-4b5a-805f-18d547cbb85f">

**Comment by LC-Pam** [comment] 2023-12-05 21:35
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-08 18:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-08 18:31 UTC
Labels: Waiting for Reply
