### ISSUE TITLE
Missing Test Case - 736. Parse Lisp Expression 

### ISSUE THREAD

**Issue by shishirofficial** [LeetCode-Feedback/LeetCode-Feedback#14206] opened 2023-06-18 06:10 UTC
#### Your LeetCode username
shishir_chaurasiya

#### Category of the bug
- [736. Parse Lisp Expression] Question
- [ ] Solution
- [ ] Language
- ["(let x 2 (mult x (let y 4 x (add x y))))"] Missing Test Cases 

#### Description of the bug

The answer should be 12 and its expecting 20 please look into it

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-06-20 20:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-22 18:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-22 18:10 UTC
Labels: LCUS, problem
