### ISSUE TITLE
Missing Test Case - 2623. Memoize

### ISSUE THREAD

**Issue by araghuth** [LeetCode-Feedback/LeetCode-Feedback#13230] opened 2023-05-01 04:16 UTC
#### Your LeetCode username
araghut

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Does not check certain key sequences

#### Code you used for Submit/Run operation

```
function memoize(fn) {
    let store = new Map();
    function mem(...args){
        let key = " "
        for(let arg of args){
            key = arg.toString() + key
        }
        if(!store.has(key)){
            store.set(key, fn(...args))
        }
        return store.get(key)
    }
    return mem
}
```

#### Language used for code
JavaScript

#### Expected behavior

Expected Behavior: Wrong Answer
Actual Behavior: Accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/67435130/235405822-8e02676a-9705-4052-9e3b-200542321d67.png)

#### Additional context

Attached Screenshot of accepted submission but wrong answer on custom test case

**Comment by LC-Pam** [comment] 2023-05-02 22:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-04 19:26
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-04 19:26 UTC
Labels: LCUS, problem

**Comment by araghuth** [comment] 2023-05-09 20:48
Hi Pam, 

Kindly find the missing test case in the screenshot provided i.e.

"sum"
["call", "call", "getCallCount", "call", "getCallCount"] 
[[2,32], [22,3], [], [1,2], []]
