### ISSUE TITLE
695. Max Area of Island

### ISSUE THREAD

**Issue by pratyushmn** [LeetCode-Feedback/LeetCode-Feedback#439] opened 2020-06-08 22:57 UTC
#### Your LeetCode username

pratyushmn

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

When I try to run my code, I get this error. I tried running my code on the same test case in my own environment and it worked fine.

ValueError: Expected object or value
Line 23 in _deserialize (./python3/__deserializer__.py)
    param_1 = des._deserialize(line, 'integer[][]')
Line 46 in _driver (Solution.py)
    _driver()
Line 59 in <module> (Solution.py)

#### Code you used for Submit/Run operation

```
class Solution:
    def maxAreaOfIsland(self, grid: List[List[int]]) -> int:
        visited = [[False for i in range(len(grid[0]))] for j in range(len(grid))]
        
        def computeArea(grid, visited, x, y, x_lim, y_lim):
                if x < 0 or y < 0 or x >= x_lim or y >= y_lim:
                    return 0
                elif visited[x][y]:
                    return 0
                elif grid[x][y] == 0:
                    return 0
                else:
                    visited[x][y] = True
                    return 1 + computeArea(grid, visited, x + 1, y, x_lim, y_lim) + computeArea(grid, visited, x - 1, y, x_lim, y_lim) + computeArea(grid, visited, x, y + 1, x_lim, y_lim) + computeArea(grid, visited, x, y - 1, x_lim, y_lim)   
                
        maxArea = 0
        max_x = len(grid)
        max_y = len(grid[0])
        
        for x in range(len(grid)):
            for y in range(len(grid[x])):
                if grid[x][y] == 1 and not visited[x][y]:
                    area = computeArea(grid, visited, x, y, max_x, max_y)
                    if area > maxArea:
                        maxArea = area
                else:
                    visited[x][y] = True
                    
        return maxArea
```

#### Language used for code

Python 3

#### Expected behavior

I expected the code to run properly.

**Comment by CooperCooperCooper** [comment] 2020-06-09 22:24
Hi @pratyushmn ,
Thank you for reaching out to us. I tested your code on this problem and it was accepted on both Run Code and Submit (please see screenshot for the results). Nice work on the code! 
<img width="1440" alt="Screen Shot 2020-06-09 at 3 21 31 PM" src="https://user-images.githubusercontent.com/59751300/84206981-2527b700-aa65-11ea-9a27-05adcaed786f.png">
  
Since we're not able to reproduce the error on our end, can you please share with me if the issue still occurs on your end? If so, can you please share a screenshot of what it looks like?

**Comment by lc-kate** [comment] 2020-07-07 01:00
Hi @pratyushmn ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag @lc-christina  in a new comment. Thank you.

**Closed by lc-kate** 2020-07-07 01:00 UTC
Labels: LCUS, problem
