### ISSUE TITLE
Missing Test Case - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by nancyyPandya** [LeetCode-Feedback/LeetCode-Feedback#11581] opened 2023-02-07 17:16 UTC
#### First Unique Character in a String
Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

```
class Solution {
    func firstUniqChar(_ s: String) -> Int {
      
      var hashDict = sortHash(value: s)
      for (index,val) in s.enumerated() {
           if let count = hashDict[val] {
                  if count == 1 {
                    return index 
                  }
           }
      }
      return -1
    }
  
     func sortHash(value: String) -> [Character: Int]{
       var hashDict =  [Character: Int]()
       var cnt = 1
       for str in value {
       if let _ = hashDict[str] {
           hashDict[str] = cnt + 1
          } else {
          hashDict[str] = cnt
        }
     }
       return hashDict
     } 
}
```

**Comment by LC-Pam** [comment] 2023-02-07 20:19
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11576

**Closed by LC-Pam** 2023-02-07 20:19 UTC
