### ISSUE TITLE
Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by raghavendra95r** [LeetCode-Feedback/LeetCode-Feedback#16626] opened 2023-09-23 09:10 UTC
#### Your LeetCode username
rrgowda

#### Category of the bug
- [ ] Question
- [  ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// String Comression
var compress = function(chars) {
    if (chars.length <= 1) {
        return chars.length;
    }

    let count = 1;
    let index = 0;

    for (let i = 1; i < chars.length; i++) {
        if (chars[i] === chars[i - 1]) {
            count++;
        } else {
            chars[index++] = chars[i - 1];
            if (count > 1) {
                const countStr = count.toString();
                for (let j = 0; j < countStr.length; j++) {
                    chars[index++] = countStr[j];
                }
            }
            count = 1;
        }
    }

    chars[index++] = chars[chars.length - 1];
    if (count > 1) {
        const countStr = count.toString();
        for (let j = 0; j < countStr.length; j++) {
            chars[index++] = countStr[j];
        }
    }

    chars.length = index; 

    return chars.length;
};

```

#### Language used for code
JavaScirpt

**Comment by LC-Pam** [comment] 2023-09-25 20:56
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-27 18:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-27 18:51 UTC
Labels: Waiting for Reply
