### ISSUE TITLE
Missing Test Case - 44. Wildcard Matching

### ISSUE THREAD

**Issue by manoj11055** [LeetCode-Feedback/LeetCode-Feedback#15340] opened 2023-08-06 06:08 UTC
tle occured in this code :
The code I provided was an implementation of a recursive approach with memoization using dynamic programming (DP) to solve the wildcard matching problem. Although DP with memoization could significantly improve the performance of recursive algorithms by avoiding redundant computations, it might still not be efficient enough for certain inputs.

The time complexity of this recursive DP algorithm is O(m*n), where m is the length of string "s" and n is the length of string "p." In the worst case, this algorithm may still end up exploring all possible combinations of characters in the strings, which can be very time-consuming.

If we are getting a TLE (Time Limit Exceeded) error, it means the input strings "s" and "p" are too large, and the algorithm is taking too much time to process them. To optimize the solution further, we may consider using a different algorithmic approach.
class Solution {
public:
    bool solve(string str1,string str2 ,int i,int j,vector<vector<int>> &dp)
    {
      if (i<0 && j<0)
      return true;
      if (i>=0 && j<0)
      return false;
      if(j>=0 && i<0)
      {
          for(int k=0;k<=j;k++)
          {
              if(str2[k]!='*')
              return false;
          }
          return true;
      }
      if(dp[i][j]!=-1)
      return dp[i][j];
      if (str1[i]==str2[j] || str2[j]=='?')
         return dp[i][j]=solve(str1,str2,i-1,j-1,dp);
         else if(str2[j]=='*')
         return dp[i][j]=(solve(str1,str2,i,j-1,dp) || solve(str1,str2,i-1,j,dp));
     else 
     return false;
    
    }
    bool isMatch(string s, string p) {
        vector<vector<int>> dp(s.length(),vector<int>(p.length(),-1));
        return solve(s,p,s.length()-1,p.length()-1,dp);
    }
};
One alternative approach is to use an iterative bottom-up DP approach, which can be more efficient for large inputs. Here's a possible implementation of the bottom-up DP approach:
class Solution {
public:
    bool isMatch(string s, string p) {
        int m = s.length();
        int n = p.length();
        vector<vector<bool>> dp(m + 1, vector<bool>(n + 1, false));
        
        dp[0][0] = true; // Empty pattern matches empty string
        
        for (int j = 1; j <= n; j++) {
            if (p[j - 1] == '*')
                dp[0][j] = dp[0][j - 1];
        }
        
        for (int i = 1; i <= m; i++) {
            for (int j = 1; j <= n; j++) {
                if (p[j - 1] == '?' || s[i - 1] == p[j - 1])
                    dp[i][j] = dp[i - 1][j - 1];
                else if (p[j - 1] == '*')
                    dp[i][j] = dp[i][j - 1] || dp[i - 1][j];
            }
        }
        
        return dp[m][n];
    }
};
This bottom-up DP approach has a time complexity of O(m*n), where m is the length of string "s" and n is the length of string "p." It avoids the recursion overhead and is generally more efficient for large inputs compared to the recursive approach with memoization.

**Comment by LC-Pam** [comment] 2023-08-08 20:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:47 UTC
Labels: LCUS, problem, Waiting for Reply
