### ISSUE TITLE
Wrong Test Case - 487. Max Consecutive Ones II

### ISSUE THREAD

**Issue by arindam369** [LeetCode-Feedback/LeetCode-Feedback#13885] opened 2023-06-04 13:21 UTC
#### Your LeetCode username
its_me_ari

#### Category of the bug
- [ ] Wrong Test Case

#### Description of the bug
I have solved this  solution and pass all the testcases except the last testcase that passes the array as nothing. This behaviour is not expected. It was clearly mentioned in the Constraints section that the array size must be >= 1. So, solutions are not getting accepted due to this one testcase. Please fix this.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void helper(int i, int n, vector<int> &nums, bool isFlipped, int curr, int &ans){
        if(i==n){
            ans = max(curr, ans);
            return;
        }

        if(nums[i]==1){
            helper(i+1, n, nums, isFlipped, curr+1, ans);
        }
        else{
            if(isFlipped){
                ans = max(ans, curr);
                helper(i+1, n, nums, isFlipped, 0, ans);
            }
            else{
                helper(i+1, n, nums, true, curr+1, ans);

                ans = max(ans, curr);
                helper(i+1, n, nums, isFlipped, 0, ans);
            }
        }
    }
    int findMaxConsecutiveOnes(vector<int>& nums) {
        int ans=0;
        helper(0, nums.size(), nums, false, 0, ans);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

It should pass and mark an ACCEPTED solution, but it just failed the last testcase which passes the array nothing. Though it is clearly mentioned there in the constraints that array.length must be >= 1.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92720594/605097c1-a322-4835-91e3-dca7a6c72f71)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92720594/8c96eafd-ff91-4fa2-8e0d-54a6d174fd0a)

Due to this, my solution has been marked as "Time Limit Exceeded". It has not yet been ACCEPTED. Please fix this issue.

**Comment by stormsunshine** [comment] 2023-06-04 14:07
The result is TLE, which is not caused by any single test case.

Although you have passed all test cases, the total run time is too long so the submission is not accepted. You should reduce the time complexity of your solution to get accepted.

**Comment by LC-Pam** [comment] 2023-06-13 19:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:31 UTC
Labels: LCUS, problem
