### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by Kundan8889** [LeetCode-Feedback/LeetCode-Feedback#19724] opened 2024-01-24 20:46 UTC
class Solution {
public:
    bool isValid(string s) {
        stack<int>st;
        for(int i=0;i<s.size();i++){
            char ch=s[i];
            if(ch=='('||ch=='{'||ch=='['){
                st.push(ch);
            }
            else{
                if(!s.empty()){
                    if(ch==')'&& st.top()=='('){
                        st.pop();
                    }
                   else if(ch==']'&& st.top()=='['){
                        st.pop();
                    }
                   else if(ch=='}'&& st.top()=='{'){
                        st.pop();
                    }
                    else{
                        // no match
                        return false;
                    }
                }
                    else{
                        return false;
                    }
                }
            }
        if(st.size()==0){
            return true;
        }
        else{
            return false;
        }
        
    }

};

**Comment by LC-Pam** [comment] 2024-01-24 21:13
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.
The bug or the issue. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:17
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:17 UTC
Labels: Waiting for Reply
