### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#5850] opened 2022-01-07 08:16 UTC
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[6,4,5,4,1,1,10,1,7,6,4,2,10,1,3,5]
10

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canPartitionKSubsets(vector<int>& nums, int k) {
        
        vector<int>dp;
        
        int sum=0;
        int i;
        int n=nums.size();
        for(i=0;i<nums.size();i++)
        {
            sum+=nums[i];
        }
        
        if(sum%k!=0)
            return false;
        
        sum=sum/k;
        
        int ans=0;
        
        for(i=0;i<(1<<nums.size());i++)
        {
            int tsum=0;
            
            for(int j=0;j<nums.size();j++)
            {
                if(i&(1<<j))
                {
                    tsum+=nums[n-j-1];
                }
            }
            
            if(tsum==sum)
                dp.push_back(i);
        }
        
        if(dp.size()<k)
            return false;
      //  for(i=0;i<dp.size();i++)
          //  cout<<dp[i]<<endl;
        for(i=0;i<dp.size();i++)
        {
            int ct=0;
            for(int j=0;j<dp.size();j++)
            {
                if(i!=j)
                {
                    if((dp[i]|dp[j])==(dp[i]^dp[j]))
                        ct++;
                }
            }
            //cout<<ct<<" ";
            if(ct>=k-1)
                ans++;
        }
        
        if(ans>=k)
            return true;
        return false;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: true
Expected: false

**Comment by LC-Sue** [comment] 2022-01-12 00:21
Duplicate of #5849

**Closed by LC-Sue** 2022-01-12 00:21 UTC
Labels: LCUS
