### ISSUE TITLE
Missing Test Case - 453. Minimum Moves to Equal Array Elements

### ISSUE THREAD

**Issue by divyafrndzz09** [LeetCode-Feedback/LeetCode-Feedback#11525] opened 2023-02-05 14:54 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by divyafrndzz09** [comment] 2023-02-05 14:55
class Solution {
public:
    int minMoves(vector<int>& nums) {
        sort(nums.begin(),nums.end());
        int n = nums.size();
        if(n&1){
            int k=nums[n/2];
            int total =0;
        for(int i= 0;i<n; i++)
            total +=abs(k-nums[i]);

            return total;
        }
        int k=nums[n/2];
        int m =nums[(n/2)-1];
        int total1 = 0;
        int total2 = 0;
        int total3 = 0;
        for(int i= 0;i<n; i++){
            total1+= abs(k-nums[i]);
            total2+= abs(m-nums[i]);
            total3+= abs(m-nums[i]);
        }
        return min(total1,total2);
    }
    

};

**Comment by divyafrndzz09** [comment] 2023-02-05 14:55
output 2
but the correct one is 3

**Comment by LC-Pam** [comment] 2023-02-07 19:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-08 18:18
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-08 18:18 UTC
Labels: LCUS, problem
