### ISSUE TITLE
leetcode1011

### ISSUE THREAD

**Issue by KevinMingCat** [LeetCode-Feedback/LeetCode-Feedback#11508] opened 2023-02-05 03:35 UTC
type: need clarification (compilation error?)

coding language: java

problem description:
1) failed with case 1 with exceed time limit: **the binary-search while-loop termination condition is not triggered** when min_cap = max_cap = 10;
2) passed only after changing the  if-else condition a bit within the  while-loop as below:
`if (min_day <= days){
max_cap = mid_cap;
} else {
min_cap = mid_cap + 1;
}`

-----------------------------
class Solution {

    public int calculateMinDay(int[] arr, int cap){
        int numOfDay = 1;
        int weight_sum = 0;
        for (int weight : arr){
            if (weight_sum + weight > cap){
                numOfDay += 1;
                weight_sum = weight;
            } else {
                weight_sum += weight;
            }
        }
        System.out.println("min_day: " + numOfDay); // for verification
        return numOfDay;
    }
    public int shipWithinDays(int[] weights, int days) {
        int min_cap = Arrays.stream(weights).max().getAsInt();
        int max_cap = Arrays.stream(weights).sum();
        int mid_cap = 0;
        int min_day = 0;
        while (min_cap < max_cap){
            mid_cap = min_cap + ((max_cap - min_cap) >> 1);
            System.out.println("before adjust => min: " + min_cap + "; max: " + max_cap + "; mid: " + mid_cap); // for verification
            min_day = calculateMinDay(weights, mid_cap); 
            System.out.println("min_day: " + min_day + "; days: " + days); // for verification
            if (min_day < days){
                System.out.println("enter if...."); // for verification
                max_cap = mid_cap - 1;
            } else {
                System.out.println("enter else...."); // for verification
                min_cap = mid_cap;
            }
            System.out.println("after adjust => min: " + min_cap + "; max: " + max_cap + "; mid: " + mid_cap); // for verification
        }

        return min_cap;
    }
}

----------------
<img width="898" alt="leetcode1011" src="https://user-images.githubusercontent.com/37907714/216800025-4ba19bd5-df5d-4cb4-a6c2-ef79945ed3fb.png">

**Comment by LC-Pam** [comment] 2023-02-07 19:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-08 18:15
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-08 18:15 UTC
Labels: LCUS, problem

**Comment by KevinMingCat** [comment] 2023-02-09 02:34
hi @LC-Pam,

Thank you for the replying, I may miss your message due to time-difference. 

To follow up again from here, I am not very sure about how to generate the "problem page" you referred to, therefore I just screenshot the result page(error message = time limit exceeded) as below from both "leetcode.com.cn" and "leetcode.com": 

<img width="1279" alt="leetcode1011_problem_page_01" src="https://user-images.githubusercontent.com/37907714/217698803-73b68786-1fe4-4544-9951-eb751c9fd1d0.png">

<img width="1276" alt="leetcode1011_problem_page_02" src="https://user-images.githubusercontent.com/37907714/217698861-fbaf36fb-b089-4c9c-88e3-e0670bd81596.png">

Code I am using is exactly the same as posted previously. Would you mind to run the piece of code and verify again if it can be reproduced at your side?

Lastly, this is not a critical issue, working-around (to pass it) was also given previously. However, due to different coding behaviours/habits from different coders, sometimes it becomes a bit complicated to find out that the submission failure may probably don't come from pure logical errors.
