### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by vivic04** [LeetCode-Feedback/LeetCode-Feedback#15742] opened 2023-08-20 05:25 UTC
#### Your LeetCode username
vihaanchugh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [! ] Missing Test Cases 

#### Description of the bug

Need to add test case to check for empty array and consecutive triple occurance

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        counter = 2
        for i in range(2, len(nums)):
            if (nums[i] != nums[counter-2]):
                nums[counter] = nums[i]
                counter  +=1 
        return counter
```

**Comment by LC-Pam** [comment] 2023-08-21 20:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-25 14:29
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-25 14:29 UTC
Labels: Waiting for Reply
