### ISSUE TITLE
Missing Test Case - 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by Jyotirmay-Chowdhury** [LeetCode-Feedback/LeetCode-Feedback#18052] opened 2023-11-14 13:36 UTC
### Problem number, title, and link

Here is the link to the solution:- 
https://leetcode.com/problems/substring-with-concatenation-of-all-words/submissions/1098668479/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.

#include <vector>
#include <string>
#include <unordered_map>

using namespace std;

class Solution {
public:
    vector<int> findSubstring(string s, vector<string>& words) {
        if (words.empty()) return {};
        unordered_map<string, int> wordCount;
        for (const string& word : words) {
            ++wordCount[word];
        }

        int wordNum = words.size();
        int wordLen = words[0].size();
        vector<int> result;

        for (int i = 0; i < wordLen; ++i) {
            int left = i, right = i, count = 0;
            unordered_map<string, int> curStr;
            while (right + wordLen <= s.size()) {
                string w = s.substr(right, wordLen);
                right += wordLen;
                if (wordCount.count(w)) {
                    ++curStr[w];
                    if (curStr[w] <= wordCount[w]) {
                        ++count;
                    } else {
                        while (curStr[w] > wordCount[w]) {
                            string t_w = s.substr(left, wordLen);
                            left += wordLen;
                            --curStr[t_w];
                            if (curStr[t_w] < wordCount[t_w]) --count;
                        }
                    }
                    if (count == wordNum) result.push_back(left);
                } else {
                    left = right;
                    count = 0;
                    curStr.clear();
                }
            }
        }
        return result;
    }
};


```

**Comment by LC-Pam** [comment] 2023-11-14 15:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Jyotirmay-Chowdhury** [comment] 2023-11-15 13:58
Hi @LC-Pam here is the link to the Solution:- 
https://leetcode.com/problems/substring-with-concatenation-of-all-words/submissions/1098668479/

**Comment by LC-Pam** [comment] 2023-11-16 16:21
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-20 21:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-20 21:08 UTC
Labels: Waiting for Reply
