### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by SrilathaSaladi** [LeetCode-Feedback/LeetCode-Feedback#8843] opened 2022-08-29 10:12 UTC
var findNumbers = function(nums) {
    var count =0;
     for(var i=0; i<nums.length; i++){
    if((nums[i].toString().length % 2) == 0){
      count++;  
    }
   }
  return count; 
}

**Comment by LC-Pam** [comment] 2022-08-29 18:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-31 20:30
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-31 20:30 UTC
Labels: LCUS, problem
