### ISSUE TITLE
Missing Test Case - 2550. Count Collisions of Monkeys on a Polygon

### ISSUE THREAD

**Issue by Praveen-Kumar-Dwivedi** [LeetCode-Feedback/LeetCode-Feedback#11362] opened 2023-01-29 16:58 UTC
#### Your LeetCode username

_PraveenKD636

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Expected output is not correct mathematically

#### Code you used for Submit/Run operation

```
 int monkeyMove(int n) {
        
        int mod = 1e9+7;

        long totalWays = 1;

        for(int i=0; i<n; i++) {

            totalWays *= 2;
            totalWays %= mod;
        }

        if(n&1){
            return totalWays - 2;
        }

        return totalWays-4;

    }
```

#### Expected behavior

for n = 4 answer should be 12 instead of 14. If n is even then we have 2 choice when monkeys will not collide when all the monkeys jump in same direction either clockwise or counter clockwise but here we have 2 more cases when they will not collide. consider an situation n = 4, monkey 0 jump to 1 and monkey 1 jump to 0 and in the same way 2 and 3 swap their position.
Hence in even cases we have pow(2, n) - 4 answer

#### Screenshots

![image](https://user-images.githubusercontent.com/91280842/215343296-8d10545a-95cd-49f0-817a-92659cfdd10c.png)

**Comment by LC-Pam** [comment] 2023-01-30 18:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link since the above code received Compile Error when we submitted it. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-31 19:24
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-31 19:24 UTC
Labels: LCUS, problem
