### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by Pritamart** [LeetCode-Feedback/LeetCode-Feedback#13851] opened 2023-06-03 02:04 UTC
#### Category of the bug
- [x] Question

#### Code you used for Submit/Run operation

```
// ContainsDuplicate of an array
class Solution {
    public boolean containsDuplicate(int[] nums) { 
        Arrays.sort(nums); 
        for (int i = 0; i < nums.length - 1; i++) {
            if (nums[i] == nums[i + 1]) {
                return true;
            }
        }
        
        return false;      
    }
}
```

**Comment by LC-Pam** [comment] 2023-06-06 19:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:19 UTC
Labels: LCUS, problem
