### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by KiranEC11** [LeetCode-Feedback/LeetCode-Feedback#15099] opened 2023-07-27 21:20 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by KiranEC11** [comment] 2023-07-27 21:25
class Solution:
    def next_arr(self, arr):
        
        first = arr[0]
        index_first  = arr.index(first)
        sorted_list = sorted(arr)
        higher_numbers = [num for num in arr if num>first]
        if len(higher_numbers)>0:
            high_num = sorted(higher_numbers)[0]
            index_sec = arr.index(high_num)
            arr[index_first], arr[index_sec] = arr[index_sec],arr[index_first]
        
        return arr
            
    
    
    def nextPermutation(self, nums):
        """
        Do not return anything, modify nums in-place instead.
        """
        output=[]
        n = len(nums)
        i=1
        while (i<n):
            arr = self.next_arr(nums[i:])
            if arr == nums[i:]:
                i +=1
            else:
                nums[i:]=arr
                break
        if i==n:
            first = nums[0]
            higher_numbers = [num for num in nums if num>first]
            if len(higher_numbers)>0:
                higher_num= sorted([num for num in nums if num>first])[0]
                nums.pop(nums.index(higher_num))
                output.append(higher_num)
                nums = output+sorted(nums)
            else:
                nums = sorted(nums)
        return nums
![sol](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123507880/43c00b98-99d2-4bad-8dc9-c96be6643fd8)


![sol1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123507880/79611e17-2b50-49f9-86ba-40f64ddc13ef)
.

This code gave the correct solution for the test case in my Jupyter notebook. But, it is wrong in leetcode. Please have a look

**Comment by LC-Pam** [comment] 2023-07-28 18:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-01 17:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:56 UTC
Labels: LCUS, problem, Waiting for Reply
