### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by NishantBhujwan** [LeetCode-Feedback/LeetCode-Feedback#11374] opened 2023-01-30 15:48 UTC
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    /**
     * @param Integer[] $nums1
     * @param Integer[] $nums2
     * @return Float
     */
    function findMedianSortedArrays($nums1, $nums2) {
        $m = count($nums1);
        $n = count($nums2);
        if ($m > $n) {
            $temp = $nums1; $nums1 = $nums2; $nums2 = $temp;
            $temp = $m; $m = $n; $n = $temp;
        }
        $iMin = 0;
        $iMax = $m;
        $halfLen = ($m + $n + 1) / 2;
        while ($iMin <= $iMax) {
            $i = intval(($iMin + $iMax) / 2);
            $j = intval($halfLen - $i);
            if ($i < $m && $nums2[$j-1] > $nums1[$i]){
                $iMin = $i + 1; 
            } elseif ($i > 0 && $nums1[$i-1] > $nums2[$j]) {
                $iMax = $i - 1;
            } else {
                $maxLeft = 0;
                if ($i == 0) { $maxLeft = $nums2[$j-1]; }
                elseif ($j == 0) { $maxLeft = $nums1[$i-1]; }
                else { $maxLeft = max($nums1[$i-1], $nums2[$j-1]); }
                if (($m + $n) % 2 == 1) {
                    return $maxLeft;
                }
                $minRight = 0;
                if ($i == $m) { $minRight = $nums2[$j]; }
                elseif ($j == $n) { $minRight = $nums1[$i]; }
                else { $minRight = min($nums1[$i], $nums2[$j]); }
                return ($maxLeft + $minRight) / 2;
            }
        }
        return 0.0;
    }
}

```

**Comment by LC-Pam** [comment] 2023-01-30 20:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-31 19:24
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-31 19:24 UTC
Labels: LCUS, problem
