### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Fedasov** [LeetCode-Feedback/LeetCode-Feedback#16089] opened 2023-09-01 14:27 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    void rotate(vector<int>& nums, int k) {
        while (k > nums.size()) {
            k = k % nums.size();
        }
        nums.insert(nums.begin(), nums.end() - k, nums.end());
        nums.erase(nums.end() - k, nums.end());
    }
};
```

**Comment by LC-Pam** [comment] 2023-09-01 17:23
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-05 20:06
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-05 20:06 UTC
Labels: Waiting for Reply
