### ISSUE TITLE
Bugs in Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by Whycodex** [LeetCode-Feedback/LeetCode-Feedback#6237] opened 2022-02-01 15:47 UTC
#### Your LeetCode username

neerajgupta12300

#### Category of the bug
- [ ] Question
- [✔️] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This code results in true no matter whatsoever we write in code. we can get accepted on all of the testcases by just writing a return true statement

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool stoneGame(vector<int>& piles) {
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This never returns false;

**Comment by stormsunshine** [comment] 2022-02-02 01:50
So what is the problem? Do you think there exists a test case that should return false? If you think so, why don't you provide such a test case?

**Comment by snehel4510** [comment] 2022-02-04 17:47
The problem isn't with the solution or the test cases, the problem is the question statement itself and the kind of inputs allowed. So There isn't going to be a single valid input that will return false. That's why just returning true will surely be correct.

**Comment by LC-Sue** [comment] 2022-02-06 07:20
Hi @snehel4510,
Thank you for reaching out to us, if you'd like to suggest a test case that would return false please feel free to do so! Otherwise since there is no missing test case, I will close this ticket for now!

**Closed by LC-Sue** 2022-02-06 07:20 UTC
Labels: LCUS
