### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by hellojyoti01** [LeetCode-Feedback/LeetCode-Feedback#10580] opened 2022-12-28 05:57 UTC
#### Your LeetCode username

[jyotiprakash4001](https://leetcode.com/jyotiprakash4001/)

#### Category of the bug
- [https://leetcode.com/problems/two-sum/ ] Question
- [ /**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function(nums, target) {
    for(let i=0 ; i<nums.length ; i++){
        for(let j=1 ; j<nums.length ; j++){
            if((nums[i] + nums[j]) == target ){
                return [i,j]
            }
        }
    }
};] Solution
- [ Javascript] Language
- [2,3,-1,0,7,-8 ]  Missing Test Cases 
- Target -9;

#### Description of the bug

-Check For Negetive It not Work Some Time 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2022-12-28 20:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-30 19:31
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-30 19:31 UTC
Labels: LCUS, problem
