### ISSUE TITLE
Mismatched Output Test Case Despite Corrected Input on LeetCode(Problem Number 2621)

### ISSUE THREAD

**Issue by Shubhamtribhuvan8** [LeetCode-Feedback/LeetCode-Feedback#12923] opened 2023-04-12 04:23 UTC
#### Your LeetCode username
Shubhamtribhuvan8

#### Category of the bug
- [ Yes] Question:https://leetcode.com/problems/sleep/description/
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The bug occurs when the input provided in the problem description has been corrected, but the output test case provided does not match with the corrected input. This can lead to incorrect answers being marked as correct or correct answers being marked as incorrect. It can also cause confusion and frustration for users who are trying to improve their coding skills.

One possible reason for this issue is that the output test case provided may have an error. It's possible that the expected output does not actually match the corrected input, or that there is a typo or mistake in the test case. In this case, users can report the issue to LeetCode's support team and request a review of the test case.

#### Code you used for Submit/Run operation
/**
 * @param {number} millis
 */
async function sleep(millis) {
   return new Promise(resolve => setTimeout(resolve, millis));
}
/** 
 * let t = Date.now()
 * sleep(100).then(() => console.log(Date.now() - t)) // 100
 */

```

#### Language used for code 

Javascript



#### Additional context

<!-- Add any other additional context about the bug. -->
```
#### Screenshots 

![testcasebug](https://user-images.githubusercontent.com/106821254/231348787-10ff7b3c-177d-4579-823e-1e3b2013ce5f.png)

**Comment by LC-Pam** [comment] 2023-04-12 20:06
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-14 19:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-14 19:12 UTC
Labels: LCUS, problem
