### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by Aryanujan01729** [LeetCode-Feedback/LeetCode-Feedback#21298] opened 2024-03-14 12:15 UTC
![Screenshot (118)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139656147/f9d14baa-1529-4a21-abba-effea812c855)

###
  209. Minimum Size Subarray Sum  https://leetcode.com/problems/minimum-size-subarray-sum/?source=submission-noac

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

the answer should be 0 but expected answer is 3

### Language used for code

c++

### Code used for Submit/Run operation

```
class Solution {
public:
    int minSubArrayLen(int target, vector<int>& nums) 
    {
        int i,l,j,sumi=0,sumj=0;
        l=nums.size();
        for(i=0;i<l;i++)
        {
            sumi=sumi+nums[i];
            sumj=sumi;
            if(sumj==target)
                {
                    return i+1;
                }
            for(j=i+1;j<l;j++)
            {
                sumj=sumj+nums[j]-nums[j-i-1];

                if(sumj==target)
                {
                    return i+1;
                }
                
            }
      
        }
    
        return 0;
        
        
    }
};
```

### Expected behavior

![Screenshot (118)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139656147/abb8880c-c576-4d9f-82de-d4399bef6e5a)

**Comment by LC-Pam** [comment] 2024-03-14 18:31
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-03-18 14:13
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-03-18 14:13 UTC
Labels: Waiting for Reply
