### ISSUE TITLE
new and old graph are same but still wrong ans

### ISSUE THREAD

**Issue by satyam5340** [LeetCode-Feedback/LeetCode-Feedback#7733] opened 2022-06-13 15:54 UTC
I have cloned graph, i do BFS for both and the result is same but the judge says wrong ans.
     

import queue
class Solution:
    def cloneGraph(self, node: 'Node') -> 'Node':
        q = queue.Queue()
        newG = Node(node.val)
        q.put([node,newG])
        
        visited = [False for _ in range(101)]
        while not q.empty():
            arr = [x[0].val for x in q.queue]
            old,new = q.get()
            a = old.val
            b = new.val
            if visited[old.val]:
                continue
            visited[old.val] = True
            for n in old.neighbors:
                x = n.val
                curr = Node(n.val)
                new.neighbors += [curr]
                q.put([n,curr])
        q.put(node)
        visited = [False for _ in range(101)]
        while not q.empty():
            
            old = q.get()
            
            if visited[old.val]:
                continue
            print(old.val,[x.val for x in old.neighbors],end=" ")
            visited[old.val] = True
            for n in old.neighbors:
                q.put(n)
        q.put(newG)
        print()
        visited = [False for _ in range(101)]
        while not q.empty():
            
            old = q.get()
            
            if visited[old.val]:
                continue
            print(old.val,[x.val for x in old.neighbors],end=" ")
            visited[old.val] = True
            for n in old.neighbors:
                q.put(n)
        return newG

**Comment by LC-Pam** [comment] 2022-06-13 18:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 
The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-16 17:10
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-16 17:10 UTC
Labels: LCUS, problem
