### ISSUE TITLE
A string S made of uppercase English letters is given. In one move, six letters forming the word "BANANA" (one 'B', three 'A's and two 'N's) can be deleted from S. What is the maximum number times such a move can be applied to S?

### ISSUE THREAD

**Issue by domwokorach** [LeetCode-Feedback/LeetCode-Feedback#13469] opened 2023-05-14 16:20 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// A string S made of uppercase English letters is given. 
In one move, six letters forming the word "BANANA" (one 'B', three 'A's and two 'N's) can be deleted from S. 
What is the maximum number times such a move can be applied to S?

function solution(S) {
  const word = "BANANA";
  const wordCounts = {};
  for (const char of word) {
    if (!wordCounts[char]) {
      wordCounts[char] = 0;
    }
    wordCounts[char]++;
  }
  let deletions = Infinity;
  for (const char of word) {
    const charCount = S.split(char).length - 1;
    if (charCount < wordCounts[char]) {
      return 0;
    }
    deletions = Math.min(deletions, Math.floor(charCount / wordCounts[char]));
  }
  return deletions;
}
```

**Comment by LC-Pam** [comment] 2023-05-16 00:38
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-18 20:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-18 20:59 UTC
Labels: LCUS, problem
