### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by zhFIsHappy** [LeetCode-Feedback/LeetCode-Feedback#18390] opened 2023-11-30 16:09 UTC
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [^ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

No bug, just adding a test case 
[1,2], pos = -1.

### Language used for code

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment] 2023-12-01 22:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-05 16:52
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-05 16:52 UTC
Labels: Waiting for Reply
