### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by krishna-p060** [LeetCode-Feedback/LeetCode-Feedback#16192] opened 2023-09-05 06:22 UTC
#### Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### ```class Solution {
public:
    int maxProfit(vector<int>& arr) {
        //int n=sizeof(arr)/sizeof(arr[0]);
        //int arr[n];
        // for(int i=0;i<n;i++){
        //     arr[i]= prices[i];
        // }
        //int profit(int arr[]) {
        int min= arr[0];
        int l=sizeof(arr)/sizeof(arr[0]);
        for(int i=0;i<l;i++){
            if(min>arr[i]){
                min= arr[i];
            }
        }
        int pos=-1;
        for(int j=0;j<l;j++){
            if(arr[j]==min){
                pos=j;
                break;
            }
        }
        int max=min;
        for(int i=pos+1;i<l;i++){
            if(max< arr[i]){
                max= arr[i];
            }
        }
        // if(l==1){
        //     return 0;
        // }
        if(max!=min){
            return max-min;
        }
        else{
            return 0;
        }
        // else{
        //     for(int j=pos;j<l-1;j++) {
        //         arr[j]=arr[j+1];
        //     }
        //     return maxProfit(arr);
        // }
        //profit(arr);

    
        
    }
};```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-09-05 21:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-11 19:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-11 19:27 UTC
Labels: Waiting for Reply
