### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by nishchayMish** [LeetCode-Feedback/LeetCode-Feedback#13962] opened 2023-06-08 07:18 UTC
#### Your LeetCode username
nishchay1234

#### Category of the bug
- [1502 ] Question
- [unordered_set<int> uset(arr.begin(),arr.end());
        
        int max = *max_element(arr.begin(),arr.end());
        int min = *min_element(arr.begin(),arr.end());
        
        if ((max - min) % (arr.size() - 1) != 0) 
            return false;
        
        int diff = (max-min)/(arr.size()-1);
        for(int i=1;i<arr.size();i++){
            if(!uset.count(min + i * diff)){
                return false;
            }
        }
        return true; ] Solution
- [C++ ] Language
- [0,0,1 ] Missing Test Cases 

#### Description of the bug

when there are duplicates numbers the code breaks.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-06-08 19:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:40
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:40 UTC
Labels: LCUS, problem
