### ISSUE TITLE
Missing Test Case - 2731. Movement of Robots

### ISSUE THREAD

**Issue by AndreMouche** [LeetCode-Feedback/LeetCode-Feedback#17106] opened 2023-10-11 04:10 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

can not get the result of the following case when try to run the following case online:
input
```
nums =[-2000000000,2000000000]
s ="LR"
d =1000000000
```

expect  output
```
999999965
```

get output : N/A

#### Code you used for Submit/Run operation

```
impl Solution {
       /**
     * https://leetcode.cn/problems/movement-of-robots/?envType=daily-question&envId=2023-10-10
     * math,O(N)
     * 2 <= nums.length <= 105
     * -2 * 1e9 <= nums[i] <= 2 * 1e9
     * 0 <= d <= 1e9
     * nums.length == s.length
     */
    pub fn sum_distance(nums: Vec<i32>, s: String, d: i32) -> i32 {
        let mut nums_final = s
            .as_bytes()
            .iter()
            .enumerate()
            .map(|(id, b)| {
                if *b == b'L' {
                    /*Pay attention to the precision, nums[i]+/-d(1) 2*1e9+1e9 > i32::MAX */
                    nums[id] as i64 - d as i64
                } else {
                    nums[id] as i64 + d as i64
                }
            })
            .collect::<Vec<i64>>();
        nums_final.sort();

        let total = nums_final.len();
        let modd = 1000000007;
        let mut id = total / 2;
        let mut ans = if total % 2 == 0 {
            let cur_cnt = ((total - id) * id) as i64 % modd;
            let dis1 = (nums_final[id] - nums_final[id - 1]) % modd;
            id = id - 1;
            cur_cnt * dis1
        } else {
            0
        };
        while id > 0 {
            let cur = (((total - id) * id) as i64) % modd;
            let dis1 = (nums_final[id] - nums_final[id - 1]) % modd;
            // println!("id {},dis1:{},cur{}",id,dis1,cur);
            ans = ans % modd + (cur * dis1) % modd;

            let dis2 = (nums_final[total - id] - nums_final[total - id - 1]) % modd;
            ans = ans % modd + (cur * dis2) % modd;
            //println!("total-id {},dis1:{},cur{}",total-id,dis2,cur);
            id = id - 1;
        }
        return (ans % modd) as i32;
    }
}
```

**Comment by LC-Pam** [comment] 2023-10-11 15:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-13 18:58
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-13 18:58 UTC
Labels: Waiting for Reply
