### ISSUE TITLE
1373. Maximum Sum BST in Binary Tree

### ISSUE THREAD

**Issue by ritusingh208** [LeetCode-Feedback/LeetCode-Feedback#232] opened 2020-05-01 22:52 UTC
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language

**Describe the bug**
There's a testcase missing because of which wrong solutions are getting accepted.

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    class pair{
        int min,max,sum;
        boolean isBst;
        pair(int min, int max, int sum, boolean isBst){
            this.min = min;
            this.max = max;
            this.sum = sum;
            this.isBst = isBst;
        }
    }
    int maxSum = Integer.MIN_VALUE;
    pair postorder(TreeNode root){
        if(root == null){
            return new pair(Integer.MAX_VALUE, Integer.MIN_VALUE, 0, true);
        }
        pair left = postorder(root.left);
        pair right = postorder(root.right);
        if(left.isBst && right.isBst && left.max < root.val && right.min > root.val){
            maxSum = Math.max(maxSum,left.sum+right.sum+root.val);
            return new pair(left.min!=Integer.MAX_VALUE? left.min : root.val,
                            right.max!=Integer.MIN_VALUE? right.max : root.val,
                            left.sum+right.sum+root.val,
                            true);
        }
        return new pair (0,0,0,false); 
    }
    public int maxSumBST(TreeNode root) {
        postorder(root);
        return maxSum<0?0:maxSum;
    }
}
```

**Expected behavior**
The output for input [4,2,6,1,5,null,null] should be 8. While the solutions for which the output is different are getting accepted.

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment] 2020-05-05 02:06
Hi @ritusingh208,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment] 2020-05-07 23:24
Hi @ritusingh208 ,
Upon investigating this issue, we were unable to reproduce the issue as the provided given code gets Accepted and return 8 on the given test case (which doesn't show unexpected behavior). Please provide us with the submission code/ solution(s) that fails this test case so we can take a deeper look into it. Thank you.

**Comment by CooperCooperCooper** [comment] 2020-06-04 21:49
Hi @ritusingh208 ,
Since you have not responded to this ticket for a while, I will close this ticket for now.

**Closed by CooperCooperCooper** 2020-06-04 21:49 UTC
Labels: LCUS, problem, watchlist
