### ISSUE TITLE
Missing Test Case - 914. X of a Kind in a Deck of Cards

### ISSUE THREAD

**Issue by rishighai97** [LeetCode-Feedback/LeetCode-Feedback#15054] opened 2023-07-26 10:24 UTC
#### Your LeetCode username
rishighai97

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
Seems like incorrect code is passing all test cases. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean hasGroupsSizeX(int[] deck) {
        int[] map = new int[10001];
        for (int num : deck) map[num]++;
        int leastFreq = 10001;
        boolean allEven = true;
        for (int i = 0 ; i < map.length ; i++) {
            if (map[i] == 1) return false;
            else if (map[i] > 1) {
                 System.out.println(i+" "+map[i]);
                if (map[i] % 2 == 1) allEven = false;
                if (map[i] < leastFreq) { 
                   leastFreq =  map[i];
                }
                
            }
        }
        
        if (allEven) return true;

        int mod =  leastFreq;
        if (leastFreq % 5 == 0) mod = 5;
        else if (leastFreq % 3 == 0) mod = 3; 
        System.out.println(mod);
        for (int i = 0 ; i < map.length ; i++) {
            if (map[i] > 0 && map[i] % mod != 0) {
                return false;
            }
        }
        
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For following frequencies - 
1 26
2 39
3 78

Code must return true but returns false

Code is passing other test cases

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36986582/737391ad-d71c-46e8-908e-0d7d16fe38b7)

#### Additional context
NA

**Comment by LC-Pam** [comment] 2023-07-26 21:26
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:27 UTC
Labels: LCUS, problem, Waiting for Reply
