### ISSUE TITLE
Missing Test Case - 1154. Day of the Year

### ISSUE THREAD

**Issue by bansal3103** [LeetCode-Feedback/LeetCode-Feedback#15023] opened 2023-07-25 14:31 UTC
Username : bansalalgo03

#### Category of the bug
- [x] Missing Test Cases 

A " invalid " test case is missing in the problem number 1154 (Day of the year)
Invalid in the sense , like 2014-02-29 this date don't exist so leetcode testcase runner should throw back invalid testcase or some message to the user if we use that test case but if we use that test case to test the code i don't know why it is showing unusual behaviour. All the correct test cases with correct outputs are showing in red. I hope i was able to explain this. For furthur clarification i am attaching the screenshots please look into it.

```
class Solution {
    public int dayOfYear(String date) {
        int days=0;
        int year=Integer.parseInt(date.substring(0,4));
        int month=Integer.parseInt(date.substring(5,7));
        int datee=Integer.parseInt(date.substring(8));
        for(int i=1;i<month;i++){
            if(i==1 || i==3 || i==5 || i==7 || i==8 || i==10 || i==12){
                days+=31;
            }else if(i==2){
                if((year%4==0 && year%100!=0) || (year%100==0 && year%400==0)){                
                    days+=29;
                }else{
                    days+=28;
                }
            }else{
                days+=30;
            }
        }
        return days+datee;
    }
}
```

Java

Please add a condition to your test code that if the date is invalid then it should show any message.

![Screenshot (171)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/9b71ff7a-fc40-4790-a3bd-21b123b3e556)
![Screenshot (172)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/6d1eacce-0d92-4a58-ac80-b929aae72565)
![Screenshot (173)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/24be90e2-9da9-41ed-a078-80309131ba89)
![Screenshot (174)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/11bb783b-6a0a-4e53-a751-46c492e8768d)

As you can see in the attached screenshots, that if the testcase is invalid date then it is showing all other testcase outputs in red though they are correct. And if i change the test case it is working good. Something wrong.
Please look into this and add the necessary changes.

(P.S. :  Please add 100 leetcoins for my previous testcase contribution which i did last month )

Thank you !

**Comment by LC-Pam** [comment] 2023-07-26 21:13
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15022

**Closed by LC-Pam** 2023-07-26 21:13 UTC
