### ISSUE TITLE
Incorrect test case for Trips and Users SQL problem

### ISSUE THREAD

**Issue by VishweshwarKammari** [LeetCode-Feedback/LeetCode-Feedback#8150] opened 2022-07-12 12:09 UTC
Hello Team,

I have found an issue with a test case which failed with my solution, As per my understanding the solution is correct and the test case which failed is not. Below is the code that I have written. 
`SELECT Day,ROUND(SUM(CANCELLED_ID)/COUNT(ID),2) AS "Cancellation Rate" FROM (
SELECT REQUEST_AT AS Day,T.ID, 
CASE WHEN STATUS IN('CANCELLED_BY_DRIVER','CANCELLED_BY_CLIENT') THEN 1 ELSE 0 END AS CANCELLED_ID 
FROM TRIPS T INNER JOIN
(SELECT USERS_ID AS DRIVER_ID FROM USERS WHERE ROLE = 'DRIVER' AND BANNED = 'NO')D
ON T.DRIVER_ID = D.DRIVER_ID INNER JOIN
(SELECT USERS_ID AS CLIENT_ID FROM USERS WHERE ROLE = 'CLIENT' AND BANNED = 'NO')C
ON T.CLIENT_ID = C.CLIENT_ID
)A
GROUP BY DAY`

Below is the test case which failed 
`Input: {"headers": {"Trips": ["id", "client_id", "driver_id", "city_id", "status", "request_at"], "Users": ["users_id", "banned", "role"]}, "rows": {"Trips": [["1", "1", "10", "1", "cancelled_by_client", "2013-10-04"]], "Users": [["1", "No", "client"], ["10", "No", "driver"]]}}`
`My Output: {"headers": ["Day", "Cancellation Rate"], "values": [["2013-10-04", 1.00]]}`
`Expected: {"headers": ["Day", "Cancellation Rate"], "values": []}`

There is only a single trip which was cancelled by client and both driver and client are not banned in which case the cancellation rate should have been 1.00 like its in my answer but it shows no output as expected.

**Comment by LC-Pam** [comment] 2022-07-12 17:39
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:44 UTC
Labels: LCUS, problem
