### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by SlowedWalk** [LeetCode-Feedback/LeetCode-Feedback#13502] opened 2023-05-16 10:54 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

The test cases provided are only valid when two of the indexes are adjacent to each other.   

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
var twoSum = function (nums, target) {
    let result = [];
    for (let i = 0; i < nums.length; i++) {
        if (nums[i] + nums[i+1] === target) {
            return [i, i+1];
        }
    }
};
```
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Javascript

#### Expected behavior

For a case where the correct indexes do not directly follow each other, the test should fail.

**Comment by LC-Pam** [comment] 2023-05-16 20:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The SPECIFIC test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-19 19:42
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-19 19:42 UTC
Labels: LCUS, problem
