### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by theehob** [LeetCode-Feedback/LeetCode-Feedback#7294] opened 2022-05-13 20:30 UTC
#### Your LeetCode username

Dauromonte 

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution with template III

#### Code you used for Submit/Run operation

```
class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        # pre-processing to gurantee Search Space is at least 3 in size
        if len(nums) == 1:
            return [0, 0] if nums[0] == target else [-1, -1]
        elif len(nums) == 2:
            if nums[0] == nums[1] == target:
                return [0, 1]  
            elif nums[0] == target:
                return [0, 0]
            elif nums[1] == target:
                return [1, 1]
            else:
                return [-1, -1]
        else:
            return [self.findBounds(nums, target, True), self.findBounds(nums, target, False)]
        
    def findBounds(self, nums: List[int], target: int, isLeft: bool) -> int:
        if len(nums) == 0:
            return -1
        l, r = 0, len(nums) - 1
        while l + 1 < r:
            p = (l + r) // 2
            if nums[p] == target:
                if isLeft:
                    if nums[p - 1] == target:
                        r = p
                    else:
                        return p
                else:
                    print('B')
                    if nums[p + 1] == target:
                        l = p
                    else:
                        return p
            elif nums[p] < target:
                l = p
            else:
                r = p
        # post-processing
        if isLeft:
            if nums[l] == target: 
                return l
            elif nums[r] == target: 
                return r
        else:
            if nums[r] == target: 
                return r
            elif nums[l] == target: 
                return l
        return -1
```
#### Language used for code

Python 3

#### Expected behavior

Using Template III of Binary Search

**Comment by LC-Pam** [comment] 2022-05-16 17:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

What is the solution bug?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-05-20 02:39
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-05-20 02:39 UTC
Labels: LCUS, solution
