### ISSUE TITLE
Missing Test Case - 412. Fizz Buzz

### ISSUE THREAD

**Issue by Abelabebe313** [LeetCode-Feedback/LeetCode-Feedback#7516] opened 2022-05-30 13:05 UTC
#### Your LeetCode username
 Abel Abebe 

#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
class Solution:
    def fizzBuzz(self, n: int) -> List[str]:
        result = []
        for i in range (1, n+1):
            if i % 15 == 0:
                result.append("FizzBuzz")
            elif i % 3 == 0:
                result.append("Fizz")
            elif i % 5 == 0:
                result.append("Buzz")
            else:
                result.append(str(i))
        return result
```

**Comment by LC-Pam** [comment] 2022-05-31 02:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-09 00:49
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-09 00:49 UTC
Labels: LCUS, problem
