### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by DrShengPeng** [LeetCode-Feedback/LeetCode-Feedback#7650] opened 2022-06-08 04:03 UTC
#### Your LeetCode username
shengp

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Some passing solutions would fail.

#### Code you used for Submit/Run operation
Add test case:
```
5
[[0,2],[0,3],[2,4],[1,4]]
[false,false,false,false,true]
```

#### Language used for code
Java

#### Expected behavior
Some very fast passing solutions not using proper DFS/BFS would fail.

**Comment by LC-Pam** [comment] 2022-06-13 17:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-15 22:44
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-15 22:44 UTC
Labels: LCUS, problem
