### ISSUE TITLE
SQL 50 - 595. Big Countries

### ISSUE THREAD

**Issue by HemaS2023** [LeetCode-Feedback/LeetCode-Feedback#19482] opened 2024-01-17 17:33 UTC
A country is big if:

it has an area of at least three million (i.e., 3000000 km2), ******or******
it has a population of at least twenty-five million (i.e., 25000000).
Write a solution to find the name, population, and area of the big countries.

The above question has an or condition. When we execute the where clause with or condition its returning 3 records and is not matching with the expected results.
The result is as expected with and condition but is logically wrong according to the question

**Comment by LC-Pam** [comment] 2024-01-17 20:09
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by HemaS2023** [comment] 2024-01-17 20:26
Big Countries - LeetCode
<https://leetcode.com/problems/big-countries/?envType=study-plan-v2&envId=top-sql-50>

output while using "or"

[image: image.png]

**Comment by LC-Pam** [comment] 2024-01-18 17:25
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-23 21:11
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:11 UTC
Labels: Waiting for Reply
