### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by NishilShah1012** [LeetCode-Feedback/LeetCode-Feedback#17913] opened 2023-11-07 18:43 UTC
#### LeetCode username
Nishil1012

### problem
Missing Test Case - 595. Big Countries
Table: World

+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| name        | varchar |
| continent   | varchar |
| area        | int     |
| population  | int     |
| gdp         | bigint  |
+-------------+---------+
name is the primary key (column with unique values) for this table.
Each row of this table gives information about the name of a country, the continent to which it belongs, its area, the population, and its GDP value.
 

A country is big if:

it has an area of at least three million (i.e., 3000000 km2), or
it has a population of at least twenty-five million (i.e., 25000000).
Write a solution to find the name, population, and area of the big countries.

Return the result table in any order.

The result format is in the following example.

 

Example 1:

Input: 
World table:
+-------------+-----------+---------+------------+--------------+
| name        | continent | area    | population | gdp          |
+-------------+-----------+---------+------------+--------------+
| Afghanistan | Asia      | 652230  | 25500100   | 20343000000  |
| Albania     | Europe    | 28748   | 2831741    | 12960000000  |
| Algeria     | Africa    | 2381741 | 37100000   | 188681000000 |
| Andorra     | Europe    | 468     | 78115      | 3712000000   |
| Angola      | Africa    | 1246700 | 20609294   | 100990000000 |
+-------------+-----------+---------+------------+--------------+
Output: 
+-------------+------------+---------+
| name        | population | area    |
+-------------+------------+---------+
| Afghanistan | 25500100   | 652230  |
| Algeria     | 37100000   | 2381741 |
+-------------+------------+---------+

#### Description of the bug

Here we have to show a list of big country whose area is more than 300000 km2 or population is more than 25000000 people.

#### Code you used for Submit/Run operation

```select name, population, area from world where area>=3000000 or population >=25000000;```

#### Language used for code
SQL

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/149922426/a0b31724-1545-48b0-ad98-6ef569374e49)

**Comment by LC-Pam** [comment] 2023-11-13 21:54
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

The missing test case in Json format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-16 16:08
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-16 16:08 UTC
Labels: Waiting for Reply
