### ISSUE TITLE
Missing Test Case - 405. Convert a Number to Hexadecimal

### ISSUE THREAD

**Issue by DevamPanchasara** [LeetCode-Feedback/LeetCode-Feedback#7708] opened 2022-06-11 17:58 UTC
class Solution {
    public String toHex(int num) {
        if(num==0){
            return "0";
        }
       String hex="";
        char[] hexa={'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};
        while(num>0){
            int rem=num%16;   
            hex=hexa[rem]+hex;   
            num=num/16;
        }
        return hex;
    }
}

**Comment by LC-Pam** [comment] 2022-06-13 03:16
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name.
The test case. 
The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-14 17:37
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-14 17:37 UTC
Labels: LCUS, problem
