### ISSUE TITLE
Missing Test Case - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by Lucio1590** [LeetCode-Feedback/LeetCode-Feedback#12191] opened 2023-03-05 20:22 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

i think a more complex test case should be added  so the problem is more understandable

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
       console.log("I don't understand what should I put Here");
    }
};
```

#### Language used for code

Javascript

#### Expected behavior

[14,8,16,12,3,5,1,4,7,2,6] is expected to be returned

#### Screenshots

![image](https://user-images.githubusercontent.com/47029235/222983830-1641fd7f-6630-492b-b95a-8469daa05b35.png)

**Comment by LC-Pam** [comment] 2023-03-07 19:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-08 19:02
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-08 19:02 UTC
Labels: LCUS, problem
