### ISSUE TITLE
Missing Test Case - 881. Boats to Save People

### ISSUE THREAD

**Issue by bhartiupkar6** [LeetCode-Feedback/LeetCode-Feedback#12734] opened 2023-04-03 11:54 UTC
public int numRescueBoats(int[] people, int limit) {
    Arrays.sort(people);
    int i=0;
    int j=people.length-1;
    int boats =0;

    while(i<=j){
        if(people[j]+people[i] <= limit){
            i++;
            j--;
            boats++;
        }
        else{
            j--;
            boats++;
        }
    }
    return boats;

        
    }

**Comment by LC-Pam** [comment] 2023-04-03 18:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-05 17:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-05 17:51 UTC
Labels: LCUS, problem
