### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by yahya-10** [LeetCode-Feedback/LeetCode-Feedback#2921] opened 2021-04-01 13:41 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ javascript] Language

#### Code you used for Submit/Run operation

```
// Two Sum
/**
 * @param {number[]} nums
 * @return {number}
 */
var findNumbers = function(nums) {
    
    let count = 0;
    
    for(let i = 0; i <= nums.length; i++){
        (Math.floor(Math.log(nums[i]) / Math.LN10 + 1) % 2) === 0 ? count++ : null;
    }
    return count;
};
```

#### Screenshots

![Capture d’écran (15)](https://user-images.githubusercontent.com/71073320/113302777-4d381d80-92f8-11eb-86e1-0cf4f72dc5e9.png)

**Comment by lc-kay** [comment] 2021-04-01 18:22
@yahya-10 Please provide a more detailed explanation of the issue. Thank you!

**Comment by yahya-10** [comment] 2021-04-01 20:22
The exercise goes like this: 

### Given an array nums of integers, return how many of them contain an even number of digits.
Example 1:

> Input: nums = [12,345,2,6,7896]
Output: 2
Explanation: 
12 contains 2 digits (even number of digits). 
345 contains 3 digits (odd number of digits). 
2 contains 1 digit (odd number of digits). 
6 contains 1 digit (odd number of digits). 
7896 contains 4 digits (even number of digits). 
Therefore only 12 and 7896 contain an even number of digits.

Example 2:

> Input: nums = [555,901,482,1771]
Output: 1 
Explanation: 
Only 1771 contains an even number of digits.

Constraints:

- 1 <= nums.length <= 500
- 1 <= nums[i] <= 10^5

**Comment by lc-kay** [comment] 2021-04-02 18:50
@yahya-10 Yes, I understand the problem. Please state the issue that you encountered and the expected behavior. In addition, please provide a reasoning for the expected behavior.

**Comment by lc-kay** [comment] 2021-04-08 18:37
Hi @yahya-10 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Closed by lc-kay** 2021-04-08 18:37 UTC
