### ISSUE TITLE
Missing Test Case - 1921. Eliminate Maximum Number of Monsters

### ISSUE THREAD

**Issue by Sohel440** [LeetCode-Feedback/LeetCode-Feedback#15013] opened 2023-07-25 06:49 UTC
#### Your LeetCode username

SOHEL440

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases  -> dist =[4 , 3 ,2]  speed = [2 ,1,1] ans =2 but here showing ans = 3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment] 2023-07-26 00:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:22 UTC
Labels: LCUS, problem, Waiting for Reply
