### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array leetcode

### ISSUE THREAD

**Issue by Akash7985** [LeetCode-Feedback/LeetCode-Feedback#8404] opened 2022-07-28 05:06 UTC
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        l, r = 0, len(nums) - 1
        while l <= r:
            i = (l + r) // 2
            if target == nums[i]:
                return i
            elif nums[l] <= target <= nums[i] or nums[i] <= nums[r] and (target < nums[i] or target > nums[r]):
                r = i - 1
            else:
                l = i + 1
        return -1

**Comment by LC-Pam** [comment] 2022-07-28 17:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-29 17:54
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-29 17:54 UTC
Labels: LCUS, problem
