### ISSUE TITLE
amanaplanacanalpanama

### ISSUE THREAD

**Issue by tapanraghuvanshi** [LeetCode-Feedback/LeetCode-Feedback#13074] opened 2023-04-21 10:15 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by tapanraghuvanshi** [comment] 2023-04-21 10:18
if i run the code on leet code then for input "A man, a plan, a canal: Panama" the output is false but if i run the same code on VS code , the output is true .

**Comment by LC-Pam** [comment] 2023-04-21 19:34
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-24 18:17
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-24 18:17 UTC
Labels: LCUS, problem
