### ISSUE TITLE
Missing Test Case - 2704. To Be Or Not To Be

### ISSUE THREAD

**Issue by quintenverniers** [LeetCode-Feedback/LeetCode-Feedback#15094] opened 2023-07-27 18:18 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A fourth test cases is needed to test all 4 options. function notToBe can also throw an error which isn't tested

#### Code you used for Submit/Run operation
```
// Test case 4
() => expect(5).notToBe(5)
```

#### Language used for code
JavaScript

#### Expected behavior
Add a fourth test case with the code mentioned above

**Comment by LC-Pam** [comment] 2023-07-27 18:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-01 17:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:56 UTC
Labels: LCUS, problem, Waiting for Reply
