### ISSUE TITLE
Missing Test Case - 482. License Key Formatting

### ISSUE THREAD

**Issue by rasheduzzaman-brur** [LeetCode-Feedback/LeetCode-Feedback#15322] opened 2023-08-05 20:13 UTC
#### Your LeetCode username

Rashedcse

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The output for the test case  "----" become at least one character but the expect show None

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        string st="";
        string st1=""; 
        for(int i=0;i<s.size();i++){
            if(s[i]!='-'){
                st += toupper(s[i]); // remove - and convert upper case
            }
        }

        cout<<st.size();
        for(int i=st.size()-1;i>=0;i=i-k){
            cout<<i;
            for(int j=i;j>i-k && j>=0;j--){ //segment in k size
                st1+=st[j];
            }
            st1+='-';
        }
        st1.pop_back();
        int i =0,j=st1.size()-1;
        while(i<=j){
            swap(st1[i],st1[j]);
            i++;
            j--;
        }

        return st1;
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment] 2023-08-08 20:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-11 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-11 19:47 UTC
Labels: LCUS, problem, Waiting for Reply
