### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by yinkp666** [LeetCode-Feedback/LeetCode-Feedback#17708] opened 2023-10-31 13:33 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
lass Solution:
    def isPalindrome(self, x: int) -> bool:
        if x <= 10:
            return False

        list1 = []
        xx = x
        while xx > 10:
            list1.append(xx % 10)
            xx = xx // 10
        list1.append(xx)

        length = len(list1)
        item = 1
        xxx = 0
        for num in range(0, length):
            xxx = xxx + list1[(length-1) - num] * item
            item = item * 10

        if x == xxx:
            return True
        else:
            return False

```

#### Language used for code

Python3

**Comment by yinkp666** [comment] 2023-10-31 13:34
sulution without use string

**Comment by LC-Pam** [comment] 2023-10-31 16:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-02 18:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-02 18:10 UTC
Labels: Waiting for Reply
