### ISSUE TITLE
Sliding window example

### ISSUE THREAD

**Issue by jbmoorhouse** [LeetCode-Feedback/LeetCode-Feedback#19697] opened 2024-01-24 09:55 UTC
### LeetCode Username

josmoor98

### Problem number, title, and link

One of the sliding window examples in the Algorithms and DataStructures course I believe in invalid

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

```python
def find_length(nums, k):
    # curr is the current sum of the window
    left = curr = ans = 0
    for right in range(len(nums)):
        curr += nums[right]
        while curr > k:
            curr -= nums[left]
            left += 1
        ans = max(ans, right - left + 1)
    
    return ans
```

This implementation doesn't work for `nums = [3, 1, 2, 7, 4, 2, 1, 2, 4]` and `k = 8`. This returns 3, but there is no valid solution. You need to check if `curr == k` in the `while` loop

### Language used for code

Python

**Comment by LC-Pam** [comment] 2024-01-24 20:53
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The problem page link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-31 15:16
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-31 15:16 UTC
Labels: Waiting for Reply
