### ISSUE TITLE
Missing Test Case - 2655. Find Maximal Uncovered Ranges

### ISSUE THREAD

**Issue by gagalina** [LeetCode-Feedback/LeetCode-Feedback#16837] opened 2023-10-01 10:07 UTC
#### Your LeetCode username
[LinaGaga](https://leetcode.com/LinaGaga)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution to [2655. Find Maximal Uncovered Ranges](https://leetcode.com/problems/find-maximal-uncovered-ranges/)

#### Code you used for Submit/Run operation

```
// Two Sum
var findMaximalUncoveredRanges = function(n, ranges) {
    //convert ranges to the 1-d array with 0,1 
    let l = ranges.length;
    let arr = new Array(n).fill(0);
    let result = [];

    for(let i=0; i<l; i++){
        let start = ranges[i][0];
        let end = ranges[i][1];

        for(let j=start; j<=end; j++){
            arr[j] = 1;
        }
    }


    //find the ranges;
    for(let i=0; i<arr.length-1; i++){
        while(arr[i]==1){
            i++
        }
        let start = i;

        while(arr[i+1]== 0){
            i++
        }
        let end = i;

        if(start < arr.length){
            result.push([start, end])
        }
 
    }
    return result;
};
```

#### Language used for code
JS

**Comment by LC-Pam** [comment] 2023-10-03 18:43
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-05 17:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-05 17:22 UTC
Labels: Waiting for Reply
