### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by MANOJRAJPUT2065** [LeetCode-Feedback/LeetCode-Feedback#16536] opened 2023-09-19 17:47 UTC
class Solution {
public:
    ListNode* removeNthFromEnd(ListNode* head, int n) {
        ListNode* dummy = new ListNode(0);
        dummy->next = head;

        ListNode* fast = dummy;
        ListNode* slow = dummy;

        // Move the fast pointer n+1 nodes ahead
        for (int i = 0; i <= n; i++) {
            fast = fast->next;
        }

        // Move both fast and slow pointers until fast reaches the end
        while (fast != nullptr) {
            fast = fast->next;
            slow = slow->next;
        }

        // Now, slow is pointing to the (n-1)-th node from the end
        ListNode* toDelete = slow->next;
        slow->next = toDelete->next;
        delete toDelete;

        return dummy->next;
    }
};

**Comment by LC-Pam** [comment] 2023-09-20 16:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-22 20:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-22 20:00 UTC
Labels: Waiting for Reply
