### ISSUE TITLE
There is a bug in testcase

### ISSUE THREAD

**Issue by Thashreef45** [LeetCode-Feedback/LeetCode-Feedback#17243] opened 2023-10-16 04:38 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
for a test case list  =[5,5,3.5] and k = 2, there is no expected output .

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    

};
```

#### Screenshots
![Screenshot from 2023-10-16 10-00-16](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113377703/bb7433c3-22f8-4788-8824-b3ef850879ab)
![Screenshot from 2023-10-16 09-59-54](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113377703/5090eddb-34c8-4704-99ee-5a2eec0933e9)
![Screenshot from 2023-10-16 09-59-50](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113377703/034a3fdd-6147-4ce3-a9be-cbf98e0b4e03)

**Comment by LC-Pam** [comment] 2023-10-17 21:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The test case that you used. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-20 20:03
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-10-20 20:03 UTC
Labels: Waiting for Reply

**Comment by Thashreef45** [comment] 2023-10-21 04:04
You can check with testcase , which is in the first screen shot
