### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by shwetobr** [LeetCode-Feedback/LeetCode-Feedback#15012] opened 2023-07-25 06:25 UTC
#### Your LeetCode username
shwetobr

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

Select id
from(Select id, temperature,Lag(temperature) over()  as a
from(Select *
from Weather) as t1) t2
where temperature > a

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
MYSQL


#### Expected behavior
It should be returning the id of the temperatures which is greater than the previous day



#### Screenshots

![Screenshot (26)](https://github.com/LeetCode-Feedback/LeetCode
![Screenshot (27)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/140483844/cfe4aaf3-d443-4f51-a2df-5e9d74bb1d40)
-Feedback/assets/140483844/ad69eb34-f2d0-484a-b3b9-6c40c54879c7)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-07-26 00:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:22
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:22 UTC
Labels: LCUS, problem, Waiting for Reply
