### ISSUE TITLE
Missing Test Case - 315. Count of Smaller Numbers After Self

### ISSUE THREAD

**Issue by darkCoder001** [LeetCode-Feedback/LeetCode-Feedback#11448] opened 2023-02-03 16:46 UTC
#### Your LeetCode username
 Ishank_Lalwani

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug
 I saw the first and foremost case which was stated wrong the output given was [2,1,1,0] but the explanation explained that the answer should be [2,1,1,1,0]. As in the array of [5,2,6,1] we see that the answer should be 2,1 for 5, 1 for 2, 1 for 6 and a 0 for 1. Seems like 1 is missing there.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
 I expected that the outcome should be [2,1,1,1,0] but the expected out was [2,1,1,0]. This means that there was some mistyping or something was missing!

**Comment by LC-Pam** [comment] 2023-02-03 17:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment] 2023-02-04 16:41
The output size should be the same as the input size. Since the input array has size 4, why should the output array has size 5?

The requirement is very clear: return an integer array `counts` where `counts[i]` is **the number of smaller elements** to the right of `nums[i]`. For nums[0] = 5, there are two elements to the right of the element that is smaller, so counts[0] = 2.

Why do you think this question requires returning the actual elements in the array?

**Comment by LC-Pam** [comment] 2023-02-07 18:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-07 18:57 UTC
Labels: LCUS, problem
