### ISSUE TITLE
Missing Test Case - 948. Bag of Tokens

### ISSUE THREAD

**Issue by icortes99** [LeetCode-Feedback/LeetCode-Feedback#20993] opened 2024-03-04 21:00 UTC
### LeetCode Username
icortes99

### Problem number, title, and link
948. Bag of Tokens https://leetcode.com/problems/bag-of-tokens/

### Category of the bug
- [ ] Problem description
- [ X ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Contribute for a test case.
Test case: bagOfTokensScore([50, 200, 1800, 459, 499, 366], 488)
Expected output: 4

### Language used for code
TypeScript / JavaScript

### Code used for Submit/Run operation

```
function getExtremity(items: number[], type?: string): number {
    if (type && type === 'max'){
        return Math.max(...items)
    } else {
        return Math.min(...items)
    }
}

function removeValue(items: number[], value: number): number[] {
    const index = items.indexOf(value);

    if (index !== -1) {
        items.splice(index, 1);
    }

    return items
}

function bagOfTokensScore(tokens: number[], power: number): number {
    let score = 0
    let faceUp = getExtremity(tokens)
    let faceDown = getExtremity(tokens, 'max')
    
    while (tokens.length >= 1){
        if (faceUp <= power){
            power -= faceUp
            tokens = removeValue(tokens, faceUp)
            score++
            faceUp = getExtremity(tokens)
        } else if (tokens.filter(token => token <= (faceDown + power)).length > 1){
            score--
            tokens = removeValue(tokens, faceDown)
            power += faceDown
            faceDown = getExtremity(tokens, 'max')
        } else {
            break
        }
    }

    return score
}
```

### Expected behavior
Contribute for a test case.
Test case: bagOfTokensScore([50, 200, 1800, 459, 499, 366], 488)
Expected output: 4

**Comment by LC-Pam** [comment] 2024-03-05 20:36
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link you submitted led to the observed result.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Closed** 2024-03-11 17:24 UTC
Labels: Waiting for Reply
