### ISSUE TITLE
Missing Test Case - 1004. Max Consecutive Ones III

### ISSUE THREAD

**Issue by keithyuk** [LeetCode-Feedback/LeetCode-Feedback#14442] opened 2023-06-30 05:06 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [# ] Missing Test Cases 

#### Description of the bug

The test cases  are not enough which will accept my wrong solution. So I add one more test cases.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int longestOnes(int[] nums, int k) {
        int i =0;
        int j = 0;
        int remain = k;
        int count =0 ;
        int max =0 ;
        // 1 1 1 0 0 0 1 1 1 1 0
        // i         j
        while(i< nums.length) {
            while(j<i) j++;
            while(j< nums.length && (nums[j] == 1 || remain  > 0)) {
                if(nums[j]==0) remain--;
                j++;
            }
            max = Math.max(max,(j-i) );
            System.out.println("b i = " +i +" j= " +j +" remain=" + remain);
            if(nums[i] ==0 && remain +1<k)remain++;
            i++;
            System.out.println("i = " +i +" j= " +j +" remain=" + remain);
            
        }
        return max;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

The test case is 
nums = [0,0,1,0,0]
k=1
the result supposed to be 2, my Solution return 1 . but when i submit my solution . it accepts as correct ans.

#### Screenshots

<img width="1396" alt="Screenshot 2023-06-30 at 1 05 37 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53367567/abd4c38e-4264-4591-9fa3-d5cded870436">

**Comment by LC-Pam** [comment] 2023-07-03 19:19
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-05 15:10
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-05 15:10 UTC
Labels: LCUS, problem
