### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by utkarsh462255** [LeetCode-Feedback/LeetCode-Feedback#19478] opened 2024-01-17 15:46 UTC
### LeetCode Username
utkarsh462255

### Problem number, title, and link

1207. Unique Number of Occurrences https://leetcode.com/problems/unique-number-of-occurrences/

### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

A test case is missing:
Input :- [45,95,555,99,45,95,455,99,99,99,95,95,555,555,555,555,555]
Output :- true

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by naXa777** [comment] 2024-01-17 16:07
why is it necessary?

**Comment by naXa777** [comment] 2024-01-17 18:33
@utkarsh462255 why do you think that for input `[45,95,555,99,45,95,455,99,99,99,95,95,555,555,555,555,555]` the expected result is `true`? it's `false`. Because there are 4 x 95 and 4 x 99. Read the description carefully.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/89c8bb5f-2f01-4eb3-8656-ca3b7fd1cb18)

**Comment by LC-Pam** [comment] 2024-01-17 20:09
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-23 21:11
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:11 UTC
Labels: Waiting for Reply
