### ISSUE TITLE
Simple Java Solution Using Brute Force - LEETCODE TWOSUMS

### ISSUE THREAD

**Issue by AyraKhans** [LeetCode-Feedback/LeetCode-Feedback#13826] opened 2023-06-01 22:54 UTC
//JAVA 
class Solution {
    public int[] twoSum(int[] nums, int target) {
       for (int i = 0; i < nums.length; i++){
        for (int j = i + 1; j < nums.length; j++){
            if (nums[i] + nums[j] == target) {
                return new int[] {i,j};
            }
            }
    
        }
        return null; 
    }
}

**Comment by LC-Pam** [comment] 2023-06-02 19:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:39 UTC
Labels: LCUS, problem
