### ISSUE TITLE
This test case is missing  2384. Largest Palindromic Number

### ISSUE THREAD

**Issue by Drontitan** [LeetCode-Feedback/LeetCode-Feedback#8743] opened 2022-08-21 08:07 UTC
Here it was showing wrong but got submitted later 

![Screenshot (76)](https://user-images.githubusercontent.com/81355585/185781789-e0c84742-6d01-46f1-a11d-8f71f507eb55.png)

This was showing wrong still it is get getting submitted

![Screenshot (77)](https://user-images.githubusercontent.com/81355585/185781844-aac1f084-96da-4c51-bf3e-cfc4bda16c0d.png)
pls try to resolve it it is missing or what ?

missing test case 
"000011"

**Comment by LC-Pam** [comment] 2022-08-22 17:11
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-08-23 17:18
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-08-23 17:18 UTC
Labels: LCUS, problem
