### ISSUE TITLE
738: Daily Temperature TLE issue

### ISSUE THREAD

**Issue by WorstUcdProgrammer** [LeetCode-Feedback/LeetCode-Feedback#8878] opened 2022-09-01 18:31 UTC
#### Your LeetCode username

PauPauna

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem should be solved using a Monotonic Stack, however, I got a TLE after submitting even though I passed all cases. There are several users on the discussion board who claimed that they encounter the same issue. 

#### Code you used for Submit/Run operation

```
// Daily Temperature
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        stack = []
        res = [0] * len(temperatures)
        for i, temp in enumerate(temperatures):
            while stack and temp > temperatures[stack[-1]]:
                day = stack.pop()
                res[day] = i - day
            stack.append(i)
        return res
```

#### Language used for code

Python3

#### Expected behavior

This solution should correctly solve this problem within the time limit. I saw other users posting their solution which is identical to mine, and they successfully solved it.

#### Screenshots

![TLE](https://user-images.githubusercontent.com/50061136/187987071-f1886bf1-dc3d-43c9-8740-1efd32885150.JPG)

**Comment by LC-Pam** [comment] 2022-09-06 16:37
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission TLE link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-12 02:34
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-12 02:34 UTC
Labels: LCUS, problem
