### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by sober-Sherlock** [LeetCode-Feedback/LeetCode-Feedback#16594] opened 2023-09-22 01:52 UTC
#### Category of the bug
- [ ] Question

#### Description of the bug

平台的数据格式是不是有点问题，使用floyd算法有一个样例过不了，但是这又不是加法不存在大数吃小数现象，而且如果是64位的double是能将10^50次方与10^(-50)次方表示出来，那么应该结果是1不会是0.9994。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/3b827199-66a0-45a6-8097-b3ac19d95d38)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/dea5f0a4-aa1b-41e2-a30c-9d0c4e5839e9)

#### Code you used for Submit/Run operation

```
vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {
        map<string,int> sign_table;
        int len = equations.size();
        int index = 0;
        for(int i = 0;i < len;i++)
        {
            if(sign_table.count(equations[i][0]) == 0)
            {
                sign_table[equations[i][0]] = index;
                index++;
            }
            if(sign_table.count(equations[i][1]) == 0)
            {
                sign_table[equations[i][1]] = index;
                index++;
            } 
        }

        int sign_size = sign_table.size();
        vector<vector<double>> adjcent_matrix(sign_size,vector<double>(sign_size,0));
        for(int i = 0;i < len;i++)
        {
            adjcent_matrix[sign_table[equations[i][0]]][sign_table[equations[i][1]]] = values[i];
            adjcent_matrix[sign_table[equations[i][1]]][sign_table[equations[i][0]]] = 1.0 / values[i];
        }
        for(int k = 0;k < sign_size;k++)
        {
            for(int i = 0;i < sign_size;i++)
            {
                for(int j = 0;j < sign_size;j++)
                {   
                    if(adjcent_matrix[i][k] != 0 && adjcent_matrix[k][j] != 0)
                        adjcent_matrix[i][j] = adjcent_matrix[i][k] * adjcent_matrix[k][j];
                }
            }
        }
        len = queries.size();
        vector<double> ans(len,-1.0);
        for(int i = 0;i < len;i++)
        {
            if(sign_table.count(queries[i][0]) && sign_table.count(queries[i][1]))
            {
                ans[i] = adjcent_matrix[sign_table[queries[i][0]]][sign_table[queries[i][1]]];
                if(ans[i] == 0)
                    ans[i] = -1.0;
            }
        }
        return ans;
    }
```

#### Expected behavior

上面的反馈应该是输出结果和预期结果一致，而且也尝试过官方的floyd算法也是输出0.99994而不是1，因而对平台的底层系统运行等产生怀疑，是不是用的32位导致出问题。

**Comment by LC-Pam** [comment] 2023-09-22 20:05
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-25 20:46
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-25 20:46 UTC
Labels: Waiting for Reply
