### ISSUE TITLE
Missing Test Case - 976. Largest Perimeter Triangle

### ISSUE THREAD

**Issue by GauravRewaliya** [LeetCode-Feedback/LeetCode-Feedback#9461] opened 2022-10-12 19:17 UTC
#### Your LeetCode username
gauravrewaliya

#### Category of the bug

- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug
false test case

#### Code you used for Submit/Run operation

```
class Solution {
    public int largestPerimeter(int[] nums) {
        Arrays.sort(nums); ///how to put in custom order
        int sum =0;
        int a = 0 ,b=0;
        
        for(int i=nums.length-1;i>=0;i--)
        {System.out.print(nums[i]+" ");
            a= nums[i];//last
              // last - pre !cont 
            for(int j=i-1;j>=0;j--)
            {
                b=nums[j];
                for(int k =j-1;k>=0;k--)
                {
                    if(nums[k] == a-b)
                        continue;
                    else
                    return a+b+nums[k];
                    
                }
            }
        }
         return sum;
    }
}
```

#### Expected behavior
At test case 
[3,6,2,3]
output must be 11
but it shows 8

**Comment by ashwin-acharya01** [comment] 2022-10-12 23:29
I don't think it's wrong as a triangle with dimensions 6, 2, and 3 cannot be possible. One possibility is 3, 3 and 2 which gives 8 as the sum

**Comment by LC-Pam** [comment] 2022-10-13 22:03
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-10-17 15:22
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-10-17 15:22 UTC
Labels: LCUS, problem
