### ISSUE TITLE
Bug report solution 37 https://leetcode.com/problems/length-of-last-word/

### ISSUE THREAD

**Issue by SalomonKisters** [LeetCode-Feedback/LeetCode-Feedback#18376] opened 2023-11-30 00:31 UTC
### LeetCode Username
[SalomonKisters](https://leetcode.com/SalomonKisters)
### Problem number, title, and link
https://leetcode.com/problems/length-of-last-word/
length-of-last-word/
58.
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
"Today is a nice day" is test case 37 and the supposed solution is 3, but it should be 5.

### Code used for Submit/Run operation
``` class Solution {
    public int lengthOfLastWord(String s) {
        StringBuilder str = new StringBuilder(s);
        int maxLen = 0;
        int currentMax= 0;
        for(int i = 0; i< str.length(); i++){
            if(s.charAt(i) == " ".charAt(0)){
                if(currentMax>maxLen) maxLen = currentMax;
                currentMax = 0;
            }else{
                currentMax++;
            }
        }
        if(currentMax>maxLen){
            maxLen = currentMax;
        } 
        return maxLen;
    }
}
 ``` 

### Expected behavior
Expected response should clearly be 5, as Today has length 5.

### Screenshots
![grafik](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/141818828/1fbda044-ba94-446d-8236-3aeb4fbe0398)

**Comment by LC-Pam** [comment] 2023-12-01 22:12
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-12-05 16:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-12-05 16:51 UTC
Labels: Waiting for Reply
