### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by Aishwarya-Jadhav** [LeetCode-Feedback/LeetCode-Feedback#12430] opened 2023-03-18 18:17 UTC
#### Your LeetCode username
<Aishwarya_Jadhav>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int findNumbers(int[] nums) {
        int count=0;
     for(int num : nums)
     {
         if(isEven(num)==true)
         {
             count++;
             
         }
         
     }
      return count;  
    }

    int digits(int num)
    { 
        if(num<0)
        {
            num = num * -1;   //If number is negative we will still count its digits, so make it positive 
        }
        
        if(num==0)      //If the number is 0 then the while loop will not work as it will consider the number of digits in the number 0 as 0. Hence the condition to return 1. here 1 signfies no of digit
        {
            return 1;
        }
        
        int count=0;
        while(num>0)
        {
            count++;
            num=num/10;
            
            //System.out.println("Count is  "+count);
        }
        
        return count;
    }

    boolean isEven(int num)
    {
        int numofdigit=digits(num);
        
        if(numofdigit%2==0)
        {return true;}
        else
        {return false;}
    }
}
```

**Comment by nskybytskyi** [comment] 2023-03-18 20:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-20 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-20 18:30 UTC
