### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by globitosparty** [LeetCode-Feedback/LeetCode-Feedback#11087] opened 2023-01-17 13:41 UTC
I have a issue with the excersice in java language, in a different IDE to leet code I put the number "DCXXI" y as a result gives me a 621 but, in leet code show me an issue and show me a "121" this is my code 
-------------------------------------------
 public static String romanToInt(String s) {
        int values = 0;
        String auxiliarData;
        Map<String, Integer> map = new TreeMap<String, Integer>();
        map.put("I", 1);
        map.put("V", 5);
        map.put("X", 10);
        map.put("L", 50);
        map.put("C", 100);
        map.put("D", 500);
        map.put("M", 1000);
        String[] individualValue = s.split("");

        for (int i = 1; i < individualValue.length; i++) {
            auxiliarData = individualValue[i - 1] + individualValue[i];
            if (auxiliarData.equals("IV") || auxiliarData.equals("IX")) {
                values--;
            } else if (auxiliarData.equals("XL") || auxiliarData.equals("XC")) {

                values = values - 10;
            } else if (auxiliarData.equals("CD") || auxiliarData.equals("CM")) {

                values = values - 100;
            } else {
                values = values + map.get(individualValue[i - 1]);
            }
            if ((i + 1) == individualValue.length) {

                values = values + map.get(individualValue[i]);
            }
        }
        return "values are: " + values;
    }
-------------------------------------------

**Comment by LC-Pam** [comment] 2023-01-17 18:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-18 18:31
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-18 18:31 UTC
Labels: LCUS, problem
