### ISSUE TITLE
Broken Test Case N6 - 64. Minimum Path Sum

### ISSUE THREAD

**Issue by hanif101** [LeetCode-Feedback/LeetCode-Feedback#8861] opened 2022-08-30 22:10 UTC
#### Category of the bug
- [ ] Broken Test Cases 

#### Description of the bug

The solution is the same idea of robot path which is the left and down recursive helper functions will hit the leaf node or the end. At the end, the sum supposed to be checked if it is less than a res (response). But test case 6 is not working. With this solution, bigger matrix cases, it will print out the TLE error. Not WRONG ANSWER error for the 2x3 matrix. Please review, thanks in advance!

#### Code you used for Submit/Run operation

```
var minPathSum = function(grid) {
    let m = grid.length - 1
    let n = grid[0].length -1
    let res = Infinity

    const helper = (sum, row, col) => {
    
        // base case
        if(row > m || col > n) return 
        
        // recusive case
        sum += grid[row][col]
        
        if(row == n && col == n) {
            console.log(sum)
            
            if(sum < res){
                res = sum
            }
            
            return 
        }
        
        //recursive case
        helper(sum, row, col + 1)
        helper(sum, row + 1, col)
        
        sum -= grid[row][col]
    }
    
    helper(0, 0, 0)
    return res 
};
```

**Comment by LC-Pam** [comment] 2022-08-31 20:27
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-09-02 19:21
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-09-02 19:21 UTC
Labels: LCUS, problem
