### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by pradipspidy** [LeetCode-Feedback/LeetCode-Feedback#16749] opened 2023-09-27 22:11 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ -] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
      
      nums1 =[i for i in nums1 if i!=0]
      nums2 =[i for i in nums2 if i!=0]
      # print(nums1,nums2)
      if len(nums1)>0 and len(nums2)>0:
        merged_list= nums1 + nums2
      elif len(nums1)>0 and len(nums2)==0:
        merged_list=nums1
      elif len(nums1)==0 and len(nums2)>0:
        merged_list=nums2
      merged_list.sort()
      # print(merged_list)
      return merged_list
```

#### Screenshots

![Uploading leet.png…]()

**Comment by LC-Pam** [comment] 2023-09-28 16:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-10-03 17:19
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed as completed by LC-Pam** 2023-10-03 17:19 UTC
Labels: Waiting for Reply
