### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Vidushika0316** [LeetCode-Feedback/LeetCode-Feedback#12186] opened 2023-03-05 15:21 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

This is about a missing test case. 
Integer with leading zeros: For example, 00100. The method should return true because leading zeros are ignored.

#### Code you used for Submit/Run operation

```
// Palindrome Number
class Solution {
    public boolean isPalindrome(int x) {
    String str = Integer.toString(x);
    String reverseStr = new StringBuilder(str).reverse().toString();
    return str.equals(reverseStr);
    }
}
```

#### Expected behavior

Should return true. But received is false

#### Screenshots

![image](https://user-images.githubusercontent.com/68911270/222969475-f5aef6e4-eaa6-4ed8-9bc0-f34bf999275b.png)

**Comment by Vidushika0316** [comment] 2023-03-05 15:22
Missing Test cases;

**Comment by LC-Pam** [comment] 2023-03-07 18:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case. 00100 shows an invalid test case.  

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-08 19:02
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-08 19:02 UTC
Labels: LCUS, problem
