### ISSUE TITLE
Incorrect Solution - 2542. Maximum Subsequence Score

### ISSUE THREAD

**Issue by sarwagya-p** [LeetCode-Feedback/LeetCode-Feedback#13679] opened 2023-05-25 05:46 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Accepts wrong solution - The index of the minimum number chosen from nums2 should be chosen from nums1 also, but an incorrect code of mine got accepted in which I am pushing the new n1 onto heap, and same number might get popped 

#### Code you used for Submit/Run operation

```
class Solution:
    def maxScore(self, nums1: List[int], nums2: List[int], k: int) -> int:
        paired_nums = list(zip(nums2, nums1))
        paired_nums.sort(reverse=True)

        heap = []
        sum, score = 0, 0

        for (n2, n1) in paired_nums:
            sum += n1

            heapq.heappush(heap, n1)

            if len(heap) < k:
                continue

            if len(heap) > k:
                removed = heapq.heappop(heap)
                sum -= removed
            
            if (sum*n2) > score:
                score = sum * n2

        return score
```

#### Language used for code

Python

#### Expected behavior

There should be cases where this errors out - since the n1 pushed can get popped in removed. However, we NEED to keep this particular number, since this index has been chosen in nums2.

**Comment by LC-Pam** [comment] 2023-05-26 20:26
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment] 2023-05-31 18:01
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Please provide the test case explicitly.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:33
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:33 UTC
Labels: LCUS, problem
