### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by jadeleafmoon** [LeetCode-Feedback/LeetCode-Feedback#13244] opened 2023-05-01 18:33 UTC
#### Your LeetCode username

jadeleafmoon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I would like to add a test case, where `t` contains all of the letters from `s` plus some extra letters.

#### Code you used for Submit/Run operation

```
const actual = isAnagram("table", "tablets");
const expected = false;
```

#### Language used for code

JavaScript

#### Expected behavior

When the correct code is run with the test case given above, the expected result is true. This makes sure the user's implementation takes account for strings of different length.

**Comment by LC-Pam** [comment] 2023-05-02 22:09
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-04 19:27
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-04 19:27 UTC
Labels: LCUS, problem

**Comment by jadeleafmoon** [comment] 2023-05-05 17:31
No problem at all! I'm glad I learned more about the process behind test cases.
