### ISSUE TITLE
Missing Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by amangupta590** [LeetCode-Feedback/LeetCode-Feedback#3416] opened 2021-05-05 18:57 UTC
<In the question of Find Smallest Letter Greater Than Target , If we return the integer value rather than the char value ,its get accepted and get the same output. In the function there is character return value thats shown in the question>

Code you used for Submit/Run operation
<
// Find Smallest Letter Greater Than Target //
'''
class Solution {
public:
char nextGreatestLetter(vector<char>& let,char target) {
int n=let.size();
int start=0,end=n-1;
int fix;
while(start<=end){
int mid=(start+end)/2;
if(let[mid]==target){
if(mid==n-1)
return let[(mid+1)%n];
else
start=mid+1;
}
else if(let[mid]>target){
fix=let[mid];
end=mid-1;
}
else{
if(mid==n-1)
return let[(mid+1)%n];
start=mid+1;
}
}
return fix;
}
};
'''

Language used for code
< C++ >

Expected behavior
<
Just like in my code there is we return the fix integer variable which is integer rather than the character value>

**Comment by lc-kay** [comment] 2021-05-06 18:21
Duplicate of #3412

**Closed by lc-kay** 2021-05-06 18:21 UTC
Labels: LCUS, invalid
