### ISSUE TITLE
invalid test case

### ISSUE THREAD

**Issue by PratikParida2** [LeetCode-Feedback/LeetCode-Feedback#18135] opened 2023-11-18 15:57 UTC
for question Lowest Common Ancestor of a Binary Tree there is a invalid test case occurs

**Comment by jutikorn** [comment] 2023-11-18 18:50
Face the same error:
**[236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)**
<img width="560" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3265887/a1c0cb77-7822-402c-9aed-f5f10b6ef037">

**Comment by LC-Pam** [comment] 2023-11-20 21:20
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-11-23 01:22
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment] 2023-11-28 00:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-11-28 00:56 UTC
Labels: LCUS, watchlist, problem
