### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by navneetguptacse** [LeetCode-Feedback/LeetCode-Feedback#14549] opened 2023-07-05 04:34 UTC
#### Your LeetCode username
navneetguptacse

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Find K Pairs with Smallest Sums
The expected output for the given code is not displayed in the console test result window, which is causing difficulty in verifying the correctness of the code.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        auto compare=[&](const vector<int> &a, const vector<int> &b){
            return a[0]+a[1]>b[0]+b[1];
        };
        
        priority_queue<vector<int> , vector<vector<int>> , decltype(compare)> pq(compare);

        vector<vector<int>> ans;
        if(nums1.empty()||nums2.empty()||k==0)
            return ans;

        for(int i=0;i<nums1.size()&&i<k;i++)
            pq.push({nums1[i],nums2[0],0});
            
        while(k--&& !pq.empty()){
            vector<int> curr=pq.top();
            pq.pop();
            ans.push_back({curr[0],curr[1]});
            if(curr[2]==nums2.size()-1)
                continue;
            
            pq.push({curr[0],nums2[curr[2]+1],curr[2]+1});
        }
        return ans;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment] 2023-07-05 15:52
Duplicate of #https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14548

**Closed by LC-Pam** 2023-07-05 15:52 UTC
