### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14848] opened 2023-07-17 17:46 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// First And Last Position Of Sorted Array
class Solution {
    public int[] searchRange(int[] nums, int target) {
        int low=0;
        int high=nums.length-1;
        int ans[]=new int[2];
        ans[0]=searchFirst(nums,target);
        ans[1]=searchLast(nums,target);
        return ans;
    }

    public int searchFirst(int[] nums, int target){
        int low=0;
        int high=nums.length-1;
        int res=-1;
        while(low<=high){
            int mid=(low+(high-low)/2);
            
            if(nums[mid]==target){
                res=mid;
                high=mid-1;
            }
            
            else if(target>nums[mid]){             
                low=mid+1;
            }
            else{
                high=mid-1;
            }
        }
        return res;
    }

    public int searchLast(int[] nums, int target){
        int low=0;
        int high=nums.length-1;
        int res=-1;
        while(low<=high){
            int mid=(low+(high-low)/2);
            
            if(nums[mid]==target){
                res=mid;
                low=mid+1;
            }
            
            else if(target>nums[mid]){             
                low=mid+1;
            }
            else{
                high=mid-1;
            }
        }
        return res;
    }
}
```

**Comment by LC-Pam** [comment] 2023-07-17 20:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:12 UTC
Labels: LCUS, problem, Waiting for Reply
