### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by ananytripathi** [LeetCode-Feedback/LeetCode-Feedback#13265] opened 2023-05-03 16:07 UTC
#### Your LeetCode username

cd_anany

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [#] Missing Test Cases 
Missing test cases

#### Description of the bug

In the Continuous Subarray Sum problem, their is one missing test case, the test case is 0 after any number which is divisible by k
[27,4,,6,0,7]
k=6
any of these types of test cases in which 0 after any integer which is divisible by k is missing

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```
''' //Continuous Subarray Sum
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        int arr[nums.size()];
        int i;
        arr[0]=nums[0];
        for(i=1;i<nums.size();i++)
        { if(nums[i]%k==0&&nums[i-1]==0)
            return true;
            if(nums[i]%k==0&&i<nums.size()-1&&nums[i+1]==0)
            return true;
              if(nums[i]==0&&nums[i-1]==0)
               return true;
           arr[i]=nums[i]+arr[i-1];
        }
        unordered_map<int,int> mp;
        mp[arr[0]%k]++;
        for(i=1;i<nums.size();i++)
        {   if(arr[i]%k==0&&i>0){
             return true;
          } 
        else{                    
            if(arr[i]!=arr[i-1]&&arr[i]%k!=arr[i-1]%k)
              mp[arr[i]%k]++;
        }
        }
      for(auto it:mp){
          if(it.second==0||it.second>1)
            return true;
      }
     return false;
    }
};
'''

#### Language used for code

C++
#### Expected behavior

A type of Test Case is missing in which 0 is followed by any integer which is divisible by k.
example:
1.>[1,5,0]
k=5
2.>[27,4,6,0,7]
k=6

My solution is accepted but for one of the test case, it is wrong.

#### Screenshots

My solution is accepted but for one of the test case, it is wrong.
![Screenshot (40)](https://user-images.githubusercontent.com/110540495/235974403-21b86e31-d9d6-46fa-b855-063857875611.png)

**Comment by LC-Pam** [comment] 2023-05-03 18:25
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-05 18:59
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-05 18:59 UTC
Labels: LCUS, problem
