### ISSUE TITLE
Missing Test Case - 1704. Determine if String Halves Are Alike

### ISSUE THREAD

**Issue by HasnainAliT** [LeetCode-Feedback/LeetCode-Feedback#19312] opened 2024-01-12 11:24 UTC
class Solution {
    public boolean halvesAreAlike(String s) {
        int n=s.length();
        int j=n/2;
        int count1=0,count2=0;
        String vowels="aeiouAEIOU";
        for(int i=0;i<n/2;i++)
        {
            char ch1=s.charAt(i);
            char ch2=s.charAt(j+i);
            if(vowels.indexOf(ch1)!=-1)
             count1++;
             if(vowels.indexOf(ch2)!=-1)
             count2++;
        }
        return count1==count2;
    }
}

**Comment by LC-Pam** [comment] 2024-01-12 17:41
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment] 2024-01-15 17:00
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-15 17:00 UTC
Labels: Waiting for Reply
