### ISSUE TITLE
Missing Test Case - 75. Sort Colors

### ISSUE THREAD

**Issue by debojyotiJha** [LeetCode-Feedback/LeetCode-Feedback#12449] opened 2023-03-19 08:15 UTC
Input: nums = [1,1,0,2,0,1,2,0,1]
Output: [0,0,01,1,1,2,2]

**Comment by LC-Pam** [comment] 2023-03-20 18:50
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-03-22 20:26
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-03-22 20:26 UTC
Labels: LCUS, problem
