### ISSUE TITLE
Missing Test Case - 707. Design Linked List

### ISSUE THREAD

**Issue by MossesRoss** [LeetCode-Feedback/LeetCode-Feedback#14304] opened 2023-06-23 04:27 UTC
#### Your LeetCode username

MossesRoss

#### Category of the bug
- [ ] Question

#### Description of the bug

There's an unwanted "object" thing in the class.

#### Code you used for Submit/Run operation

class MyLinkedList(object):

    def __init__(self):
        
        

    def get(self, index):
        """
        :type index: int
        :rtype: int
        """
        

    def addAtHead(self, val):
        """
        :type val: int
        :rtype: None
        """
        

    def addAtTail(self, val):
        """
        :type val: int
        :rtype: None
        """
        

    def addAtIndex(self, index, val):
        """
        :type index: int
        :type val: int
        :rtype: None
        """
        

    def deleteAtIndex(self, index):
        """
        :type index: int
        :rtype: None
        """
        

# Your MyLinkedList object will be instantiated and called as such:
# obj = MyLinkedList()
# param_1 = obj.get(index)
# obj.addAtHead(val)
# obj.addAtTail(val)
# obj.addAtIndex(index,val)
# obj.deleteAtIndex(index)
#### Language used for code

Python

#### Expected behavior

clear run

#### Screenshots

none

#### Additional context

Remove this object in the, class MyLinkedList(object): coz you don't wanna explicitly write that.

**Comment by LC-Pam** [comment] 2023-06-23 20:04
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:36
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:36 UTC
Labels: LCUS, problem
