### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by AnshulOG** [LeetCode-Feedback/LeetCode-Feedback#16478] opened 2023-09-17 07:35 UTC
Your LeetCode username
Anshul29

Category of the bug
 Missing Test Cases
Description of the bug
A testcase is missing.

Code you used for Submit/Run operation
class Solution {
    public boolean isPalindrome(ListNode head) {
        long num=0;
        long mun=0;
        long mul=1;
        while(head!=null){
            num=num*10+head.val;
            mun=head.val*mul+mun;
            mul*=10;
            head=head.next;
        }
        return num==mun;
    }
}
Language used for code
Java

Expected behavior
The constraints of this question allows upto 10^5 nodes (linked list) but each node is <=9 and >=0 so if we convert the nodes of a long list to one number, it will flow out of the range of long and any non palindrome list with nodes long enough and which is palindrome upto many nodes and then a digit changes will return true as opposed to expected false because it falls out of range.

Screenshots
Additional context
Input: head=[1,2,2,1,5,7,5,3,8,9,0,6,5,9,6,9,2,1,3,0,8,8,4,8,9,0,3,5,6,8,9,0,1,3,2,6,0,2,5,1,7,5,8,0,3,6,9,1,2,0,6,4,5,3,5,8,0,1,5,4,8,9,7,3,2,1,6,8,9,6,1,2,3,7,9,8,4,5,1,0,8,5,3,5,4,6,0,2,1,9,6,3,0,8,5,7,1,5,2,0,6,2,3,1,0,9,8,6,5,3,0,9,8,4,8,8,0,3,1,2,9,6,9,5,6,0,9,8,3,5,7,5,1,2,2,1]
Output: true
Expected: false

**Comment by LC-Pam** [comment] 2023-09-18 18:47
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-20 16:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-20 16:34 UTC
Labels: Waiting for Reply
