### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain

### ISSUE THREAD

**Issue by erikajansson** [LeetCode-Feedback/LeetCode-Feedback#16639] opened 2023-09-23 18:50 UTC
#### Your LeetCode username
erika_jansson

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I had a valid submission for the problem [1048. Longest String Chain](https://leetcode.com/problems/longest-string-chain/) with the following test case even if my implementation gave the wrong answer.

["a","b","bca","bda","bdca"]

#### Language used for code
Python3

#### Expected behavior
An implementation which fails the test case should not be accepted as a submission.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4054943/cfded7da-9bf6-41d4-9400-3d753b5214f4)

**Comment by LC-Pam** [comment] 2023-09-25 20:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-27 18:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-27 18:51 UTC
Labels: Waiting for Reply
