### ISSUE TITLE
Missing Test Case - 2345. Finding the Number of Visible Mountains

### ISSUE THREAD

**Issue by jasonechiu** [LeetCode-Feedback/LeetCode-Feedback#13749] opened 2023-05-29 03:31 UTC
#### Your LeetCode username
jasonechiu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing some test case so that some wrong answer accept.
The test case is [[3,1],[4,1],[4,1],[4,1]]
The expect should be 1.

#### Language used for code
Java

#### Expected behavior
The expect of the test case should be 1.

**Comment by LC-Pam** [comment] 2023-05-30 20:58
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-02 19:33
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-02 19:33 UTC
Labels: LCUS, problem
