### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by rojonbarnett** [LeetCode-Feedback/LeetCode-Feedback#13345] opened 2023-05-07 18:01 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases  - 

#### Description of the bug

There is no test case that includes the D roman numeral

#### Code you used for Submit/Run operation

```
import java.util.*;
import java.io.*;

//A class that converts roman numerals to numbers
class Solution
 {
	//Variable declarations
     int numOut;
     int numIn;
     Scanner scan = new Scanner(System.in);
    
     char romanChar;
     char romanCharBefore;
     char romanCharAfter;
     
     //Roman numeral to interger converter
    public int romanToInt(String s) 
    {
    	//Variable declarations
        int romanIsum = 0;
        int romanVsum = 0;
        int romanXsum = 0;
        int romanLsum = 0;
        int romanCsum = 0;
        int romanDsum = 0;
        int romanMsum = 0;
        int answer = 0;
        
        //Checking for I in the string
        if(s.contains("I") )
        {
           for (int i = 0; i < s.length(); i++)
           {
        	   romanChar = s.charAt(i);
               if (romanChar == 'I')
               {
                   romanIsum++;
               }   
           }
        }
        //Checking for v in the string
        if(s.contains("V"))
        {
        	//Loop through entire string
        	for (int i = 0; i < s.length(); i++)
            {
	        	  //
	         	  romanChar = s.charAt(i);
	         	  
	         	  //If the current character is V
	         	  if (romanChar == 'V')
	              {
	         		  romanVsum  = romanVsum + 5;
	         		  //If not on the first character
	                  if(i > 0)
	                  {
	                	
	                  	romanCharBefore = s.charAt(i-1);
	                  	//Checking if before character is an I
	                  	if(romanCharBefore == 'I' )
	                  	{
	                  		//Take 1 away from both V and I
	                  		romanLsum = romanLsum - 1;
	                  		romanIsum = romanIsum -1;
	                  	}
	                  	
	                  	
	                  }  
	              }
         	   
         	  }
        	
            }
         //Checking for X in the string
          if(s.contains("X"))
	      {
	        	//Loop through entire string
	        	for (int i = 0; i < s.length(); i++)
	            {
	        	  //
	         	  romanChar = s.charAt(i);
	         	  
	         	  //If the current character is X
	         	  if (romanChar == 'X')
	              {
	         		  romanXsum  = romanXsum + 10;
	         		  //If not on the first character
	                  if(i > 0)
	                  {
	                	//Check previous index
	                  	romanCharBefore = s.charAt(i-1);
	                  	//Checking if before character is an I
	                  	if(romanCharBefore == 'I' )
	                  	{
	                  		//Take 1 away from both X sum and I sum
	                  		romanXsum = romanXsum - 1;
	                  		romanIsum = romanIsum -1;
	                  	}
	                  	
	                   }    
	                }  
         	  
                 }
	        }
        //Checking for L in the string
          if(s.contains("L"))
	      {
	        	//Loop through entire string
	        	for (int i = 0; i < s.length(); i++)
	            {
	        	  //Initialize romanChar to current variable
	         	  romanChar = s.charAt(i);
	         	  
	         	  //If the current character is L
	         	  if (romanChar == 'L')
	              {
	         		  romanLsum  = romanLsum + 50;
	         		  //If not on the first character
	                  if(i > 0)
	                  {
	                	//Check previous index
	                  	romanCharBefore = s.charAt(i-1);
	                  	//Checking if before character is an I
	                  	if(romanCharBefore == 'X' )
	                  	{
	                  		//Take 10 away from both X sum and L sum
	                  		romanLsum = romanLsum - 10;
	                  		romanXsum = romanXsum - 10;
	                  	}
	                  	
	                   }    
	                }  
         	  
                }
	        	
	        }
          
          
	        	
	    //Checking for C in the string
	    if(s.contains("C"))
	    {
	      	//Loop through entire string
	      	for (int i = 0; i < s.length(); i++)
	        {
		      	  //Initialize romanChar to current variable
		       	  romanChar = s.charAt(i);
	       	  
		       	  //If the current character is C
		       	  if (romanChar == 'C')
		          {
		       		  romanCsum  = romanCsum + 100;
		       		  //If not on the first character
		                if(i > 0)
		                {
		                	//Check previous index
		                	romanCharBefore = s.charAt(i-1);
		                	//Checking if before character is an I
		                	if(romanCharBefore == 'X' )
		                	{
		                		//Take 10 away from both C sum and X sum
		                		romanCsum = romanCsum - 10;
		                		romanXsum = romanXsum - 10;
		                	}
		                	
		                }    
		           }  
	   	  
	          }
	      }
	    
	    //Checking for D in the string
	    if(s.contains("D"))
	    {
	      	//Loop through entire string
	      	for (int i = 0; i < s.length(); i++)
	        {
	      	  //Initialize romanChar to current variable
	       	  romanChar = s.charAt(i);
	       	  
	       	  //If the current character is C
	       	  if (romanChar == 'D')
	            {
	       		  romanDsum  = romanDsum + 500;
	       		  //If not on the first character
	                if(i > 0)
	                {
	                	//Check previous index
	                	romanCharBefore = s.charAt(i-1);
	                	//Checking if before character is a D
	                	if(romanCharBefore == 'C' )
	                	{
	                		//Take 100 away from both D sum and C sum
	                		romanDsum = romanDsum - 100;
	                		romanCsum = romanCsum - 100;
	                	}
	                	
	                }    
	           }  
	   	  
	        }
	    }
	    
	  //Checking for M in the string
	    if(s.contains("M"))
	    {
	      	//Loop through entire string
	      	for (int i = 0; i < s.length(); i++)
	        {
	      	  //Initialize romanChar to current variable
	       	  romanChar = s.charAt(i);
	       	  
		       	  //If the current character is M
		       	  if (romanChar == 'M')
		          {
		       		  //Add 1000 to the M sum
		       		  romanMsum  = romanMsum + 1000;
		       		  //If not on the first character
		                if(i > 0)
		                {
		                	//Check previous index
		                	romanCharBefore = s.charAt(i-1);
		                	
		                	//Checking if before character is a C
		                	if(romanCharBefore == 'C' )
		                	{
		                		//Take 100 away from both D sum and C sum
		                		romanMsum = romanMsum - 100;
		                		romanCsum = romanCsum - 100;
		                	}
		                	
		                }    
		          } 
	         }
	    }
	    
	    
	    
	    
	    		//Add all roman numeral sums
            	answer = romanIsum + romanVsum + romanXsum + romanLsum + romanCsum + romanDsum + romanMsum;
     	        return answer;   
             
    } 
    //Main driver function
    public static void main(String[] args)
    {
    	//Create userNum variable
    	String userNum;
  
    	//Instantiate a new instance of the solution class
    	Solution solution = new Solution();
    	//Print Input prompt to console
    	System.out.println("Input: ");
    	//Scan the user Input
    	userNum = solution.scan.nextLine();
    	//Print Output label and the corresponding answers to the screen
    	System.out.println("Output: " + solution.romanToInt(userNum));
    }
 }
};
```

#### Language used for code
Java

#### Expected behavior
I expected a test case that would include the D roman Numeral

**Comment by LC-Pam** [comment] 2023-05-08 21:28
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-10 22:16
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-10 22:16 UTC
Labels: LCUS, problem
