### ISSUE TITLE
leetcode1163 test case

### ISSUE THREAD

**Issue by Universe-E** [LeetCode-Feedback/LeetCode-Feedback#13120] opened 2023-04-24 03:20 UTC
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
universe-explorer

**Bug 类型**
- [ √] 缺少测试用例

**描述**
缺少测试用例构造如下：
```
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 199999; i++) {
            sb.append("b");
        }
        sb.append("a");
        for (int i = 0; i < 200000; i++) {
            sb.append("b");
        }
        String s = sb.toString();
```

**你使用的语言**
Java

**期望行为**
补充关键测试用例

**Comment by LC-Pam** [comment] 2023-04-24 18:51
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-26 19:48
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-26 19:48 UTC
Labels: LCUS, problem
