### ISSUE TITLE
Missing Test Case - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by prachiprajita** [LeetCode-Feedback/LeetCode-Feedback#14330] opened 2023-06-24 13:45 UTC
####prachiprajita

#### Category of the bug
- [987 ] Question
- [class Solution {
    static class Pair
    {
        int hd;
        TreeNode node;

        public Pair(int hd,TreeNode node)
        {
            this.hd= hd;
            this.node=node;
        }
    }
    public List<List<Integer>> verticalTraversal(TreeNode root) {
        Queue<Pair> q= new ArrayDeque<>();
        TreeMap<Integer, ArrayList<Integer>> map= new TreeMap<>();
        q.add(new Pair(0, root));
        while(!q.isEmpty())
        {
            Pair curr= q.poll();
            if(map.containsKey(curr.hd))
            {
               map.get(curr.hd).add(curr.node.val); 
            }
            else
            {
                ArrayList<Integer> temp= new ArrayList<>();
                temp.add(curr.node.val);
                map.put(curr.hd, temp);
            }
            if(curr.node.left!=null)
            {
                q.add(new Pair(curr.hd-1, curr.node.left));
            }
            if(curr.node.right!=null)
            {
                q.add(new Pair(curr.hd+1, curr.node.right));
            }

        }
        List<List<Integer>> output= new ArrayList<>();
        for(Map.Entry<Integer, ArrayList<Integer>> entry: map.entrySet())
        {
            output.add(entry.getValue());
        }
        return output;

    }
} ] Solution
- [ Java] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation:
```
class Solution {
    static class Pair
    {
        int hd;
        TreeNode node;

        public Pair(int hd,TreeNode node)
        {
            this.hd= hd;
            this.node=node;
        }
    }
    public List<List<Integer>> verticalTraversal(TreeNode root) {
        Queue<Pair> q= new ArrayDeque<>();
        TreeMap<Integer, ArrayList<Integer>> map= new TreeMap<>();
        q.add(new Pair(0, root));
        while(!q.isEmpty())
        {
            Pair curr= q.poll();
            if(map.containsKey(curr.hd))
            {
               map.get(curr.hd).add(curr.node.val); 
            }
            else
            {
                ArrayList<Integer> temp= new ArrayList<>();
                temp.add(curr.node.val);
                map.put(curr.hd, temp);
            }
            if(curr.node.left!=null)
            {
                q.add(new Pair(curr.hd-1, curr.node.left));
            }
            if(curr.node.right!=null)
            {
                q.add(new Pair(curr.hd+1, curr.node.right));
            }

        }
        List<List<Integer>> output= new ArrayList<>();
        for(Map.Entry<Integer, ArrayList<Integer>> entry: map.entrySet())
        {
            output.add(entry.getValue());
        }
        return output;

    }
} ```
<!-- 
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code: Java
<!-- C++ -->


#### 
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment] 2023-06-27 17:44
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-28 18:50
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-28 18:50 UTC
Labels: LCUS, problem
