### ISSUE TITLE
1385. Find the Distance Value Between Two Arrays

### ISSUE THREAD

**Issue by MathiasKandelborg** [LeetCode-Feedback/LeetCode-Feedback#11029] opened 2023-01-14 21:29 UTC
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Someone didn't understand the problem, but still tried to define & explain it

#### Expected behavior
Redo of the entire problem definition

#### Additional context
This isn't the only one I've been annoyed with... but it seems I'm in the majority on this one.

**Comment by LC-Pam** [comment] 2023-01-16 19:36
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The suggestion definition or which part should be fixed/add more explanation.
Please provide us more details about your suggestion. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-18 18:30
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-18 18:30 UTC
Labels: LCUS, problem
