### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by mkrioutchkov** [LeetCode-Feedback/LeetCode-Feedback#14301] opened 2023-06-22 23:56 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I think a one byte integer should be insufficient given the constraints.

#### Code you used for Submit/Run operation

```
// Two Sum
    int findKthLargest(vector<int>& nums, int k) {
        char counts[20'001]{};
        for (auto& num : nums)
            counts[10'000 - num]++;

        for (size_t i = 0; i < size(counts); ++i) {
            k -= counts[i];
            if (k <= 0)
                return 10'000 - i;
        }
        throw "impossible";
    }
```

**Comment by LC-Pam** [comment] 2023-06-23 20:02
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More explanation about the issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-27 17:34
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-27 17:34 UTC
Labels: LCUS, problem
