### ISSUE TITLE
Missing Test Case - 60. Permutation Sequence

### ISSUE THREAD

**Issue by rjanshuman** [LeetCode-Feedback/LeetCode-Feedback#15083] opened 2023-07-27 08:58 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by rjanshuman** [comment] 2023-07-27 08:59
class Solution {
    public String getPermutation(int n, int k) {

        int m=n, I=0;
        String st = "", S = "";

        while(m>0){I += (m)*Math.pow(10,n-m); m--;}
        S = Integer.toString(I);
        m=n-1;

        while(m>0){

            I=1;
            for(int j=1; j<=m; j++){I *= j;}

            st += S.substring((k -1)/I,1+(k -1)/I);
            S = S.substring(0, (k -1)/I) + S.substring(1 +(k -1)/I,m+1);

            k = 1+ (k-1)%I;
            m--;
        }

        return st+S;

    }
}

**Comment by LC-Pam** [comment] 2023-07-27 18:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-01 17:56
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-01 17:56 UTC
Labels: LCUS, problem, Waiting for Reply
