### ISSUE TITLE
Missing Test Case - 1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by jatinbharadwaj** [LeetCode-Feedback/LeetCode-Feedback#16342] opened 2023-09-11 09:50 UTC
#### Your LeetCode username

jeeku

#### Category of the bug
- [ ] Question
- [x] Solution: The test case should verify that values are not repeated
- [ ] Language
- [x] Missing Test Cases 
output:
[[0,1,2],[1,2,3],[5]]
expected Output
[[5],[0,1,2],[3,4,6]]

#### Description of the bug

The expected output is [[5],[0,1,2],[3,4,6]] and my output was [[0,1,2],[1,2,3],[5]]
and in the question it is mentioned **"Each person should appear in exactly one group, and every person must be in a group."**
so 1, 2 should not repeat in output

#### Code you used for Submit/Run operation

```GO
func groupThePeople(groupSizes []int) [][]int {
    groupsMap := make(map[int][]int)
    sol := [][]int{}
    for idx, group := range groupSizes {
        groupsMap[group] = append(groupsMap[group], idx)
    }

    for key, val := range groupsMap {
        noOfGroups := len(val) / key
        for i := 0; i < noOfGroups; i++ {
            sol = append(sol, val[i:i+key])
        }
    }
    return sol
}
```

#### Expected behavior

I expected that it should not pass the test case as the expected output is [[5],[0,1,2],[3,4,6]] and my output was [[0,1,2],[1,2,3],[5]]
and the question mentioned **"Each person should appear in exactly one group, and every person must be in a group."**
Hence it should not work by tweaking my solution `sol = append(sol, val[i*key:(i*key)+key])` then it should be accepted otherwise it should not.

**Comment by LC-Pam** [comment] 2023-09-11 20:33
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-12 18:10
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-09-18 19:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-09-18 19:12 UTC
Labels: Waiting for Reply
