### ISSUE TITLE
Missing Test Case - 168. Excel Sheet Column Title

### ISSUE THREAD

**Issue by Sanjai1112** [LeetCode-Feedback/LeetCode-Feedback#15025] opened 2023-07-25 14:54 UTC
#### Case Bug

- [ ] 168. Excel Sheet Column Title
- [ ] Solution
- [ ] public String convertToTitle(int columnNumber) {
        StringBuilder sb = new StringBuilder();
        while(columnNumber > 0) {
            columnNumber--;
            sb.insert(0, (char) (65 + columnNumber % 26));
            columnNumber = columnNumber / 26;
        }
        return sb.toString();
    }
- [ ] 677

#### Code you used for Submit/Run operation

```
public String convertToTitle(int columnNumber) {
        StringBuilder sb = new StringBuilder();
        while(columnNumber > 0) {
            columnNumber--;
            sb.insert(0, (char) (65 + columnNumber % 26));
            columnNumber = columnNumber / 26;
        }
        return sb.toString();
    }
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38290625/579e108c-9bc9-4d1d-b68a-ef9888b635a2)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38290625/ad918105-23f0-449a-a5e0-b5cf282171cc)

**Comment by LC-Pam** [comment] 2023-07-26 21:14
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug or issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-28 18:24
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-28 18:24 UTC
Labels: LCUS, problem, Waiting for Reply
