### ISSUE TITLE
9. Palindrome Number

### ISSUE THREAD

**Issue by thapa-in** [LeetCode-Feedback/LeetCode-Feedback#15873] opened 2023-08-24 12:14 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[9. Palindrome Number](https://leetcode.com/problems/palindrome-number/)
Easy 10.7K 2.6K Companies
Given an integer x, return true if x is a 
palindrome
, and false otherwise.

Example 1:

Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.
Example 2:

Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
Example 3:

Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool IsPalindrome(int x) {
        int num = x; string revnum=string.Empty;
        for(int i=0;i<x.ToString().Length;i++){
            int ans = num/10;
            int rem = num%10;
            if(ans!=null){
                num = ans;
                revnum+=rem;
            }else{revnum+=ans;}
        } 
        if(revnum==x.ToString()){ return true;}else {return false;}
    }
}
```

#### Expected behavior
Here 2 main things used Remainder, Answer to get Reverse order number and Loop for Use divide remain part of original number.
#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40119660/b213cd1c-a252-433b-81a9-cabfe47495fe)

#### Additional context
-

**Comment by LC-Pam** [comment] 2023-08-24 17:46
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-28 19:50
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-28 19:50 UTC
Labels: Waiting for Reply
