### ISSUE TITLE
Sample Test cases failed just because of function call order - 189. Rotate Array

### ISSUE THREAD

**Issue by codesbysalman** [LeetCode-Feedback/LeetCode-Feedback#15170] opened 2023-07-30 18:56 UTC
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

ok so initially i wrote the code like this -> 
void rotate(int* nums, int k) {
  k = k % (std::size(nums));
  reverse(nums, 0, k - 1);
  reverse(nums, k, std::size(nums) - 1);
  reverse(nums, 0, std::size(nums) - 1);
}
then i just changed the order of calling reverse function like this
void rotate(int* nums, int k) {
  k = k % (std::size(nums));
  reverse(nums, 0, std::size(nums) - 1);
  reverse(nums, 0, k - 1);
  reverse(nums, k, std::size(nums) - 1);
}
Then this code passed all the sample test cases? Why is it done so?

#### Code you used for Submit/Run operation

```
// Rotate Array
class Solution {
public:
    void reverse(vector<int>& nums, int start, int end){
        while(start<end){
            int temp = nums[start];
            nums[start] = nums[end];
            nums[end] = temp;
            start++;
            end--;
        }
    } 
    void rotate(vector<int>& nums, int k) {
        k = k % nums.size();
        reverse(nums, 0, k-1);
        reverse(nums, k, nums.size()-1);
        reverse(nums, 0, nums.size()-1);
    }
};

```
#### Language used for code 
C++

#### Expected behavior

It was supposed to be passed all the sample test cases but it did not.

#### Screenshots

Initial code in which some sample test cases failed:
![Screenshot from 2023-07-31 00-16-40](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/133004022/7d95f43a-114c-4928-9ed0-b6ac1c071356)

After changing the order of the reverse function call:
![Screenshot from 2023-07-31 00-22-40](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/133004022/bb2c3d9d-85d6-4987-bd6b-68152b455a9c)

**Comment by LC-Pam** [comment] 2023-08-01 18:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-03 18:20
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-03 18:20 UTC
Labels: LCUS, problem, Waiting for Reply

**Comment by codesbysalman** [comment] 2023-08-03 18:32
Hi Thanks for replying. i have attached below the submission link. please check it.
https://leetcode.com/submissions/detail/1007952628/
