### ISSUE TITLE
Bug in shortest palindrome problem #7865

### ISSUE THREAD

**Issue by sahilm26** [LeetCode-Feedback/LeetCode-Feedback#7891] opened 2022-06-24 16:07 UTC
Bug in shortest palindrome problem #7865

**Comment by sahilm26** [comment] 2022-06-24 16:07
class Solution {
    public String shortestPalindrome(String s) {
              ArrayList<Character> list = new ArrayList<>();
               for(int i=0;i<s.length();i++) {
                   list.add(s.charAt(i));
               }
             
               int i =0;
               int j=s.length()-1;
               while(j>0){
                   if(s.charAt(i)==s.charAt(j)){
                       i++;
                       j--;
                     
                   }
                   else{
                       list.add(i,s.charAt(j));
                       String revStr="";
                       for(int k=0;k<list.size();k++){
                           revStr+=list.get(k);
                       }
                       s=revStr;
                       j=s.length()-1;
                       i=0;
                      
                   }
                   
                   if(i==j){
                      return s;
                   }
               }
                              
           return s;
    }      
}

**Comment by LC-Pam** [comment] 2022-06-24 17:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-06-27 16:43
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-06-27 16:43 UTC
Labels: LCUS, problem
