### ISSUE TITLE
705. Design HashSet

### ISSUE THREAD

**Issue by Swastik-1411** [LeetCode-Feedback/LeetCode-Feedback#13833] opened 2023-06-02 07:23 UTC
class MyHashSet {
public:
    int M;
    vector<list<int>> buck;
    int getIndex(int key){
        return key%M;
    }
    MyHashSet() {
        M = 1;
        buck = vector<list<int>> (M,list<int> {});
    }
    
    void add(int key) {
        int idx = getIndex(key);
        auto itr = find(buck[idx].begin(),buck[idx].end(),key);

        if(itr == buck[idx].end())
            buck[idx].push_back(key);
    }
    
    void remove(int key) {
        int idx = getIndex(key);
        auto itr = find(buck[idx].begin(),buck[idx].end(),key);

        if(itr != buck[idx].end())
            buck[idx].erase(itr);
    }
    
    bool contains(int key) {
        int idx = getIndex(key);
        auto itr = find(buck[idx].begin(),buck[idx].end(),key);

        return itr != buck[idx].end();
    }
};

The above code should not run as M = 1, and the number of calls can be 10 to the power of 4 and taking the worst cases scenario the M should be strictly greater than 10000 and below this the test cases should not be satisfied so there is need of improvement in the test cases.

Hope this help.

**Comment by LC-Pam** [comment] 2023-06-02 19:59
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-05 20:39
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-05 20:39 UTC
Labels: LCUS, problem
