### ISSUE TITLE
Missing Test Case - 2300. Successful Pairs of Spells and Potions

### ISSUE THREAD

**Issue by iamkorobitsyn** [LeetCode-Feedback/LeetCode-Feedback#12720] opened 2023-04-02 19:08 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 2300. Successful Pairs of Spells and Potions


class Solution {
   func successfulPairs(_ spells: [Int], _ potions: [Int], _ success: Int) -> [Int] {
    var result: [Int] = []
    let potions = potions.sorted()
    
    for spell in spells {
        var counter = 0
        var low = 0
        let hight = potions.count - 1
        
        while low <= hight {
            if spell * potions[low] >= success {
                low += 1
                counter += 1
            } else {
                low += 1
            }
        }
        result.append(counter)
    }
    return result
}

```

**Comment by LC-Pam** [comment] 2023-04-02 20:55
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-04 20:51
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-04 20:51 UTC
Labels: LCUS, problem
