### ISSUE TITLE
Missing Test Case - 13. Roman to Integer 

### ISSUE THREAD

**Issue by Pat108** [LeetCode-Feedback/LeetCode-Feedback#10910] opened 2023-01-09 21:34 UTC
#### Category of the bug
- [ Given a roman numeral, convert it to an integer. ] Question
- [ Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M. For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.] Solution
- [ Java] Language
- [ zero] Missing Test Cases 

#### Code you used for Submit/Run operation
 
```
class Solution 
{
    public int romanToInt(String s) 
   {

      Map<Character, Integer> map=new HashMap<Character, Integer>();  
        //adding elements to the Map   
        map.put('I',1);  
        map.put('V',5);  
        map.put('X',10);  
        map.put('L',50);  
        map.put('C',100);  
        map.put('D',500);  
        map.put('M',1000);    
        s = s.replace("IV","IIII");  
        s = s.replace("IX","VIIII");  
        s = s.replace("XL","XXXX");  
        s = s.replace("XC","LXXXX");  
        s = s.replace("CD","CCCC");  
        s = s.replace("CM","DCCCC");  
        int number = 0;  
     //loop iterates over the roman numeral   
        for (int i = 0; i < s.length(); i++)  
        {  
     //getting each character of roman numeral and adding it to the variable number  
            number = number + (map.get(s.charAt(i)));  
            
        }     
        return number;
    }  
}

```

#### Expected behavior

Works as Expected

**Comment by LC-Pam** [comment] 2023-01-10 18:41
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug or issues with the description. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:45
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:45 UTC
Labels: LCUS, problem
