### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by MetaChristie** [LeetCode-Feedback/LeetCode-Feedback#13288] opened 2023-05-04 11:12 UTC
#### Category of the bug
- [ Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.
Given a roman numeral, convert it to an integer.] Question
- [ Python] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def romanToInt(self, s: str) -> int:
        roman={"I":1,
        "V":5,
        "X":10,
        "L":50,
        "C":100,
        "D":500,
        "M":1000}
        number=0
        for N in range(len(s)-1):
            if roman[s[N]] < roman[s[(N+1)]]:
                number-=roman[s[N]]
            else:
                number+=roman[s[N]]
        return number+roman[s[-1]]

    }
};
```

![image](https://user-images.githubusercontent.com/108213850/236188931-9dde7157-47b8-43d4-a22d-c4fd72254ee3.png)

**Comment by LC-Pam** [comment] 2023-05-04 19:45
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-05-05 19:00
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-05-05 19:00 UTC
Labels: LCUS, problem
