### ISSUE TITLE
Missing Test Case - 6. Zigzag Conversion

### ISSUE THREAD

**Issue by aryaratan** [LeetCode-Feedback/LeetCode-Feedback#13867] opened 2023-06-03 16:30 UTC
#### Your LeetCode username
arya_ratan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug
a found that one test case should when string is of length less than numsRow

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string convert(string s, int numRows) {
        
        int i = 0;
        int l = s.length();

        vector<vector<char>> temp(numRows,vector<char>(1000,'1'));

        int k = 0;
        int c = 0;
        string ans = "";
        for(;k<l;){
            for(int i=0;i<numRows && k < l;i++){
                temp[i][c] = s[k++];
                // ans.push_back(s[k++]);

            }
            c++;
            for(int i = numRows-2;i>=1 && k < l;i--){
                temp[i][c++] = s[k++];
                // ans.push_back(s[k++]);
            }
        }
        // return ans;
        // string ans = "";


        for(int i=0;i<numRows;i++){
            for(int j=0;j<1000;j++){
                if(temp[i][j] !='1'){
                    // cout << temp[i][j] << " " ;
                    ans.push_back(temp[i][j]);
                }
            }
            // cout << endl;
        }
return ans;


        // int k = numRows + 1;
        
        // for(int j=0;j<;j++){
        //     ans.push_back(s[i%l]);
        //     i += (k);
        // }
        



        // return ans;
        
    }

};
```

#### Language used for code
C++ 

#### Expected behavior
in that case answer should be same as given string.

**Comment by LC-Pam** [comment] 2023-06-06 19:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-06-13 19:26
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-06-13 19:26 UTC
Labels: LCUS, problem
