### ISSUE TITLE
Missing Test Case - 1470. Shuffle the Array

### ISSUE THREAD

**Issue by TanishqDawar** [LeetCode-Feedback/LeetCode-Feedback#10882] opened 2023-01-08 19:27 UTC
#### Your LeetCode username
 https://leetcode.com/dawar_tanishq/

#### Category of the bug
- [1470. Shuffle the Array ] Question 
- [ ] Solution
- [ C++] Language
- [ ] Missing Test Cases 

#### Description of the bug

code just overflows

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s)
 {
vector<int> ans;
       
       for(int i=0;i<a.size();i++)
       {
           ans.push_back(a[i]);
           ans.push_back(a[i+s]);
       }
      
    return ans;}
    }
};
```

**Comment by LC-Pam** [comment] 2023-01-09 19:08
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link since we received Compile Error when we submitted above code: https://leetcode.com/submissions/detail/874950574/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-01-11 19:43
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-01-11 19:43 UTC
Labels: LCUS, problem
