### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by AmirKamali** [LeetCode-Feedback/LeetCode-Feedback#18572] opened 2023-12-10 01:42 UTC
### LeetCode Username
amirnet

### Problem number, title, and link
https://leetcode.com/problems/jump-game-ii

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Current test cases don't check if there's large number of 0's in the steps, as a result input like this will pass the test:
[2,3,0,0,0,0,1,1,4]
However, the below algorithms will pass the test and returns 3 jumps.

Input: [2,3,0,0,0,0,1,1,4]
Currently: 3 // Acceptec
Expected output : -1 // Not possible
### Language used for code
Swift

### Code used for Submit/Run operation

```
func jump(_ nums: [Int]) -> Int {
    var jumps = 0, farthest = 0, currentEnd = 0

    for i in 0..<nums.count - 1 {
        farthest = max(farthest, i + nums[i])

        if i == currentEnd {
            jumps += 1
            currentEnd = farthest
        }
    }

    return jumps
}
```

### Expected behavior
Fail

### Additional context
correct algorithm:
```
 func jump(_ nums: [Int]) -> Int {
        let n = nums.count
        if n < 2 { return 0 }
        
        var jumps = 1
        var maxReach = nums[0]
        var end = nums[0]
        
        for i in 1..<n {
            if i > maxReach { return -1 } // cannot reach the end
            
            if i > end {
                jumps += 1
                end = maxReach
            }
            
            maxReach = max(maxReach, i + nums[i])
        }
        
        return jumps
    }
```

**Comment by LC-Pam** [comment] 2023-12-12 23:22
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by AmirKamali** [comment] 2023-12-12 23:46
https://leetcode.com/problems/jump-game-ii/submissions/1116085434

**Comment by AmirKamali** [comment] 2023-12-12 23:47
https://leetcode.com/problems/jump-game-ii/submissions/1116085272

**Comment by LC-Pam** [comment] 2024-01-23 21:24
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team

**Closed by LC-Pam** 2024-01-23 21:24 UTC
Labels: Waiting for Reply
