### ISSUE TITLE
Missing Test Case - 137. Single Number II

### ISSUE THREAD

**Issue by KIET7UKE** [LeetCode-Feedback/LeetCode-Feedback#9927] opened 2022-11-16 10:43 UTC
#### Your LeetCode username
KIET7UKE

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I want to contribute a TestCase,
[4, 5, 6, 5, 7, 7, 5, 4, 4, 7]

#### Code you used for Submit/Run operation

```
Arrays.sort(nums);
        for(int i = 0; i < nums.length - 3; i = i+3) {
            if(nums[i] != nums[i+2]) {
                return nums[i];
            }
        }
        return nums[nums.length -1];
```

#### Language used for code
Java

**Comment by nskybytskyi** [comment] 2022-11-16 12:26
Thank you for reaching out. The suggested test case is invalid, as it violates this constraint:

> Each element in nums appears exactly **three times** except for one element which appears **once**.

In your test case, the value `5` appears twice.

**Comment by KIET7UKE** [comment] 2022-11-16 13:04
@nskybytskyi  Sorry for the inconvenience, Actually its [4, 5, 6, 5, 7, 7, 5, 4, 4, 7]

**Comment by nskybytskyi** [comment] 2022-11-16 13:06
When I run your solution on this test case, it gets accepted. We typically don't add test cases if there are no issues with the current test suite, as additional test cases make the testing slower and take up additional space. Perhaps you have a solution that gets accepted but fails on the suggested test case?

**Comment by LC-Pam** [comment] 2022-11-18 18:48
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-11-21 16:56
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-11-21 16:56 UTC
Labels: LCUS, problem
