### ISSUE TITLE
Missing Test Case - 713. Subarray Product Less Than K

### ISSUE THREAD

**Issue by henrysoftware6** [LeetCode-Feedback/LeetCode-Feedback#12835] opened 2023-04-08 17:22 UTC
#### Your LeetCode username
leetcodehenry

#### Category of the bug
- [ ] Missing Test Cases 
- [array: [5,6,7,8], K==1

#### Code you used for Submit/Run operation

```
    public int NumSubarrayProductLessThanK(int[] nums, int k) 
    {
        int i=0,j=0, product=nums[0],res=0;
        while(j<nums.Length && i<nums.Length)
        {
            if(product<k)
            {
                res+=j-i+1;
                j++;
                if(j<nums.Length)
                {
                    product*=nums[j];
                }
            }
            else
            {
                i++;
                product/=nums[i-1];
            }
        }
        return res;
    }
```

#### Language used for code
c#

#### Expected behavior
<img width="506" alt="image" src="https://user-images.githubusercontent.com/17484861/230734647-c42cd78a-eae7-4b51-816d-2653289b164f.png">

**Comment by LC-Pam** [comment] 2023-04-10 22:40
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-04-12 19:47
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-04-12 19:47 UTC
Labels: LCUS, problem
