### ISSUE TITLE
Missing Test Case - 1084. Sales Analysis III

### ISSUE THREAD

**Issue by ApicaSharma15** [LeetCode-Feedback/LeetCode-Feedback#10595] opened 2022-12-28 20:45 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

when i run the query it is accepted. the solution works but not accepted on submission

**Comment by ApicaSharma15** [comment] 2022-12-28 20:49
![Screenshot (70)](https://user-images.githubusercontent.com/85416479/209870433-e8b9833c-be86-4181-b3ae-cea3318f21f9.png)

**Comment by ApicaSharma15** [comment] 2022-12-28 20:49
the query gives expected results but while submission the expected results have changed. 
LEETCODE BUG

**Comment by LC-Pam** [comment] 2022-12-29 19:42
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-12-30 19:34
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-12-30 19:34 UTC
Labels: LCUS, problem
