### ISSUE TITLE
Missing Test Case - 1233. Remove Sub-Folders from the Filesystem

### ISSUE THREAD

**Issue by THYshy6666** [LeetCode-Feedback/LeetCode-Feedback#11622] opened 2023-02-09 09:55 UTC
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 

#### Description of the bug

缺少空字符或者单斜杠的测试用例，算法题目提供的测试用例不严谨

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    public static List<String> removeSubfolders(String[] folder) {
        List<String> result = new ArrayList<>();
        String[] array = Arrays.stream(folder).filter(v -> ((!("".equals(v.trim())) && !("/".equals(v.trim()))))).toArray(String[]::new);
        Arrays.sort(array);
        result.add(array[0]);
        for (int i = 1; i < array.length; i++) {
            String str = result.get(result.size() - 1);
            StringBuilder sb = new StringBuilder(str).append("/");
            if (!(array[i].startsWith(sb.toString())))
                result.add(array[i]);
        }
        return result;
    }
};
```

#### Language used for code

Java

#### Expected behavior

输入：folder = ["/a","/a/b","/c/d","/c/d/e","/c/f"," ","  ","/"," / ","  /  "]
输出：["/a","/c/d","/c/f"]
解释："/a/b" 是 "/a" 的子文件夹，而 "/c/d/e" 是 "/c/d" 的子文件夹。

**Comment by LC-Pam** [comment] 2023-02-10 19:22
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test case. 
["/a","/a/b","/c/d","/c/d/e","/c/f"," "," ","/"," / "," / "] is an invalid test case. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-02-11 19:57
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-02-11 19:57 UTC
Labels: LCUS, problem
