### ISSUE TITLE
Missing Test Case - 2784. Check if Array is Good

### ISSUE THREAD

**Issue by Nitin0000** [LeetCode-Feedback/LeetCode-Feedback#15614] opened 2023-08-15 13:20 UTC
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//Check if array is  Good
class Solution {
public:
    bool isGood(vector<int>& nums) {
        int p=*max_element(nums.begin(),nums.end());
        int c=0;
        for(auto i:nums){
            if(p==i)
                c++;
        }
        if(c==2 and p==nums.size()-1)
            return true;
        return false;
    }
};
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113214474/6c497502-2c13-4029-aa43-67ab8e47d4f1)

**Comment by LC-Pam** [comment] 2023-08-15 20:00
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Bug.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-08-18 19:45
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-08-18 19:45 UTC
Labels: Waiting for Reply

**Comment by Nitin0000** [comment] 2024-01-04 09:31
Can you please Open it again . In This I want you to tell about the bug -- which is in this image after submitting the solution leetcode is showing wrong answer as an most optimistic answer .
