### ISSUE TITLE
https://leetcode.com/explore/learn/card/graph/619/depth-first-search-in-graph/3848/

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#8139] opened 2022-07-11 21:37 UTC
(V - 1) - 1 + (V - 2) - 1 + (V - 3) - 1 + ...(V−1)−1+(V−2)−1+(V−3)−1+... ≈ V \cdot (V - 1) / 2 + 1≈V⋅(V−1)/2+1

**Comment by LC-Pam** [comment] 2022-07-12 17:29
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The problem name.
The code and language you submitted to reach this result.
The issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2022-07-15 23:31
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Closed by LC-Pam** 2022-07-15 23:31 UTC
Labels: LCUS, problem
