### ISSUE TITLE
Typo in solution of 'Decode Ways II'

### ISSUE THREAD

**Issue by EaseTheWorld** [LeetCode-Feedback/LeetCode-Feedback#4131] opened 2021-07-12 08:11 UTC
#### Your LeetCode username
easetheworld

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the approach 1, '8 times' should be '9 times'.
> Thus, this 1* pair leads to 8 times the number of decodings possible with the string ss upto the index i-2. Thus, this adds a factor of 9 * ways(s, i - 2) to the total number of decodings.

**Comment by lc-kay** [comment] 2021-07-13 18:47
Duplicate of #4119 Thank you for your time.

**Closed by lc-kay** 2021-07-13 18:47 UTC
