### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by b1tburn3r20** [LeetCode-Feedback/LeetCode-Feedback#14849] opened 2023-07-17 18:38 UTC
#### Your LeetCode username
antewy

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Leetcode was missing this test case

#### Code you used for Submit/Run operation

```
class Solution(object):
    def twoSum(self, nums, target):
        self.nums = nums
        for i in range(0, len(nums)):
            for l in range(1, len(nums)):
                if l != i and nums[l] + nums[i] == target:
                    return(i, l)
        return []
```

#### Language used for code
Python

**Comment by LC-Pam** [comment] 2023-07-17 20:30
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment] 2023-07-20 19:12
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Closed by LC-Pam** 2023-07-20 19:12 UTC
Labels: LCUS, problem, Waiting for Reply
